/**
 * se_parameter_grid — Screen Layout Data
 *
 * Base address: 0xF144E7
 * Size: 221 bytes, 18 commands
 *
 * Auto-generated by screendata_parser.py
 */

#include "screendata_types.h"
#include <stddef.h>

/* Handler data tables (resolved by linker via se_screens_link.ld) */
extern const char SE_ParamGrid_ControlNames;
extern const char SE_ParamGrid_TriggerNames;
extern const char SE_ParamGrid_CursorCoords;

#define HANDLER_ADDR(sym) ((uint32_t)&(sym))

typedef struct __attribute__((packed)) {
	sd_widget_t                    widget_0;  /* trigger names (79,13) */
	sd_widget_t                    widget_1;  /* trigger names (119,18) */
	sd_widget_t                    widget_2;  /* trigger names (79,23) */
	sd_widget_t                    widget_3;  /* trigger names (79,28) */
	sd_nop_10_t                    nop_0;
	sd_nop_10_t                    nop_1;
	sd_nop_10_t                    nop_2;
	sd_nop_10_t                    nop_3;
	sd_nop_10_t                    nop_4;
	sd_widget_t                    widget_4;  /* control names (96,13) */
	sd_widget_t                    widget_5;  /* control names (136,18) */
	sd_widget_t                    widget_6;  /* control names (96,23) */
	sd_widget_t                    widget_7;  /* control names (96,28) */
	sd_block_hdr_t                 setup_0;  /* id=0x065d cursor coords */
	sd_nop_10_t                    nop_5;
	sd_nop_10_t                    nop_6;
	sd_nop_10_t                    nop_7;
	sd_nop_10_t                    nop_8;
} screendata_se_parameter_grid_t;

_Static_assert(sizeof(screendata_se_parameter_grid_t) == 221,
	"se_parameter_grid must be exactly 221 bytes");

#define SE_PARAMETER_GRID_BASE  0x00F144E7u
#define SD_PTR(field)  (SE_PARAMETER_GRID_BASE + offsetof(screendata_se_parameter_grid_t, field))

const screendata_se_parameter_grid_t se_parameter_grid
	__attribute__((section(".text"), used)) = {
	.widget_0 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x0661, .flags = 0x0003, .ref_tag = 0x20, .handler = HANDLER_ADDR(SE_ParamGrid_TriggerNames), .param = 7, .x = 79, .y = 13 },
	.widget_1 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x0661, .flags = 0x020c, .ref_tag = 0x20, .handler = HANDLER_ADDR(SE_ParamGrid_TriggerNames), .param = 7, .x = 119, .y = 18 },
	.widget_2 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x0661, .flags = 0x0430, .ref_tag = 0x20, .handler = HANDLER_ADDR(SE_ParamGrid_TriggerNames), .param = 7, .x = 79, .y = 23 },
	.widget_3 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x0661, .flags = 0x06c0, .ref_tag = 0x20, .handler = HANDLER_ADDR(SE_ParamGrid_TriggerNames), .param = 7, .x = 79, .y = 28 },
	.nop_0 = { .opcode = 0x00, .length = 0x0a, .data = { 0x62, 0x06, 0x3f, 0x00, 0x20, 0x59, 0x0d, 0x02 } },
	.nop_1 = { .opcode = 0x00, .length = 0x0a, .data = { 0x63, 0x06, 0x3f, 0x00, 0x20, 0x81, 0x12, 0x02 } },
	.nop_2 = { .opcode = 0x00, .length = 0x0a, .data = { 0x64, 0x06, 0x3f, 0x00, 0x20, 0x59, 0x17, 0x02 } },
	.nop_3 = { .opcode = 0x00, .length = 0x0a, .data = { 0x65, 0x06, 0x3f, 0x00, 0x20, 0x59, 0x1c, 0x02 } },
	.nop_4 = { .opcode = 0x00, .length = 0x0a, .data = { 0x6a, 0x06, 0x7f, 0x00, 0x20, 0x30, 0x1d, 0x03 } },
	.widget_4 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x066b, .flags = 0x0003, .ref_tag = 0x06, .handler = HANDLER_ADDR(SE_ParamGrid_ControlNames), .param = 3, .x = 96, .y = 13 },
	.widget_5 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x066b, .flags = 0x020c, .ref_tag = 0x06, .handler = HANDLER_ADDR(SE_ParamGrid_ControlNames), .param = 3, .x = 136, .y = 18 },
	.widget_6 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x066b, .flags = 0x0430, .ref_tag = 0x06, .handler = HANDLER_ADDR(SE_ParamGrid_ControlNames), .param = 3, .x = 96, .y = 23 },
	.widget_7 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x066b, .flags = 0x06c0, .ref_tag = 0x06, .handler = HANDLER_ADDR(SE_ParamGrid_ControlNames), .param = 3, .x = 96, .y = 28 },
	.setup_0 = { .type = SD_BLOCK_SETUP, .length = 0x0b, .id = 0x065d, .flags = 0x000f, .tag = 0x05, .handler = HANDLER_ADDR(SE_ParamGrid_CursorCoords) },
	.nop_5 = { .opcode = 0x00, .length = 0x0a, .data = { 0x6c, 0x06, 0x7f, 0x00, 0x20, 0x61, 0x0d, 0x02 } },
	.nop_6 = { .opcode = 0x00, .length = 0x0a, .data = { 0x6d, 0x06, 0x7f, 0x00, 0x20, 0x89, 0x12, 0x02 } },
	.nop_7 = { .opcode = 0x00, .length = 0x0a, .data = { 0x6e, 0x06, 0x7f, 0x00, 0x20, 0x61, 0x17, 0x02 } },
	.nop_8 = { .opcode = 0x00, .length = 0x0a, .data = { 0x6f, 0x06, 0x7f, 0x00, 0x20, 0x61, 0x1c, 0x02 } },
};
