#!/usr/bin/env python3
"""gen_stale_help_duplicate.py -- the last 17,570 B of table_data raw .incbin, DERIVED not dumped.

QUESTION ANSWERED: table_data/scripts/analysis/table_data_debt.py classifies exactly two
.incbin directives, totalling 17,570 B, as 'stale-remnant' (a documented dead slice, kept
byte-exact because "the tail no longer exists"):

    table_data/style_records.s:20081   StyleRecords_Residue        8,167 B
    table_data/help_databases.s:87     HelpDB_German_Stale (body)  9,403 B

Both are slices of includes/icons_to_strings.bin, a static blob with no generator -- real debt
by the lane brief's definition, *unless* something else produces the same bytes.

IT DOES. scripts/analysis/verify_stale_band.py already established that ROM 0x981570-0x985FFF
(which contains both slices, plus 1,518 B of ALREADY-typed header/ramp source in between) is
byte-identical to ROM 0x989570-0x98DFFF -- the live help region, 0x8000 (32 KiB) lower -- except
for one byte at 0x983B39 that falls OUTSIDE both slices (it's the last byte of the already-typed
StyleRecords_ResidueRamp). "The live help region" there is exactly
HelpDB_English's SLIDE8K header+payload immediately followed by HelpDB_German's: both of those
are themselves build products, regenerated byte-exact from committed decompressed sources by
scripts/build/compress_slide8k.py (see Makefile's help-database rules). So the two "stale-remnant"
slices need NO raw blob at all -- they are a straight copy out of bytes the build already
regenerates for a different, live purpose.

Verified exactly (see `verify()`, which re-derives from the ROM + built compressed files with
zero fudge factors and zero diffs across both slices):

    ROM 0x981570-0x983556 (8,167 B) == [english header+payload][german header+payload]
                                        sliced at combined-stream offset 0x98956F-0x988690
    ROM 0x983B45-0x985FFF (9,403 B) == the same combined stream, continuing to 0x98DFFF-0x988690

This is option 1 of the lane brief's fork ("it is reproducible... generate it and retire the
blob"), just via a raw shifted copy instead of a codec. `build()` writes the two derived .bin
files that table_data/style_records.s and table_data/help_databases.s now .incbin instead of
the static blob.

    python3 scripts/generators/gen_stale_help_duplicate.py build    # write the two .bin files
    python3 scripts/generators/gen_stale_help_duplicate.py verify   # re-derive vs the ROM, byte-exact
"""
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent.parent
HELP_DB_DIR = REPO / "table_data" / "includes" / "help_databases"
ROM = REPO / "original_ROMs" / "kn5000_table_data.rom"

# The 11-byte header every SLIDE8K block carries in the ROM (magic + 24-bit BE size = 0x9000);
# help_databases.s emits it separately from the .incbin, so it is not in the *_compressed.bin
# files and has to be reattached here to reconstruct the ROM's real byte layout.
HDR = b"SLIDE8K\x00" + bytes([0x00, 0x90, 0x00])

ENGLISH_COMPRESSED = HELP_DB_DIR / "help_db_english_compressed.bin"
GERMAN_COMPRESSED = HELP_DB_DIR / "help_db_german_compressed.bin"

STREAM_BASE = 0x988690  # ROM address of HelpDB_English's header (see table_data/help_databases.s)

# (output filename, destination ROM lo/hi, matching the .incbin this replaces)
SLICES = [
    ("stale_style_records_residue.bin", 0x981570, 0x983556,
     "table_data/style_records.s StyleRecords_Residue"),
    ("stale_help_db_german_head.bin", 0x983B45, 0x985FFF,
     "table_data/help_databases.s HelpDB_German_Stale body"),
]
SHIFT = 0x8000  # the duplicate sits exactly 32 KiB below its live source


def combined_stream():
    """The ROM bytes from STREAM_BASE onward: English's header+payload, then German's --
    reconstructed from the build products compress_slide8k.py regenerates from committed
    decompressed sources, not read from any raw dump."""
    if not ENGLISH_COMPRESSED.exists() or not GERMAN_COMPRESSED.exists():
        sys.exit(f"missing {ENGLISH_COMPRESSED} or {GERMAN_COMPRESSED} -- run "
                  f"`make table_data/includes/help_databases/help_db_english_compressed.bin "
                  f"table_data/includes/help_databases/help_db_german_compressed.bin` first")
    return HDR + ENGLISH_COMPRESSED.read_bytes() + HDR + GERMAN_COMPRESSED.read_bytes()


def derive(lo, hi):
    stream = combined_stream()
    src_lo, src_hi = lo + SHIFT, hi + SHIFT
    return stream[src_lo - STREAM_BASE: src_hi - STREAM_BASE + 1]


def build():
    HELP_DB_DIR.mkdir(parents=True, exist_ok=True)
    for name, lo, hi, _ in SLICES:
        data = derive(lo, hi)
        (HELP_DB_DIR / name).write_bytes(data)
        print(f"  wrote {name}  {len(data):,} B  (ROM 0x{lo:06X}-0x{hi:06X})")


def verify():
    rom = ROM.read_bytes()

    def o(a):
        return a - 0x800000

    bad = 0
    for name, lo, hi, label in SLICES:
        derived = derive(lo, hi)
        actual = rom[o(lo):o(hi) + 1]
        if derived == actual:
            print(f"  ok  {label:<55} {len(actual):>6,} B  ROM 0x{lo:06X}-0x{hi:06X}")
        else:
            bad += 1
            n = (sum(1 for a, b in zip(derived, actual) if a != b)
                 if len(derived) == len(actual) else -1)
            print(f"  *** {label}: MISMATCH ({n} bytes differ, expected 0)")
    if bad:
        sys.exit(f"{bad} slice(s) do not re-derive byte-exact")
    print(f"ROUND TRIP EXACT: both stale-remnant slices ({sum(h - l + 1 for _, l, h, _ in SLICES):,} B) "
          f"re-derive byte-for-byte from the live English+German SLIDE8K build products, "
          f"shifted 0x{SHIFT:X} -- no raw blob required.")


if __name__ == "__main__":
    {"build": build, "verify": verify}[sys.argv[1] if len(sys.argv) > 1 else "verify"]()
