/**
 * naka_accomp7_widgets.c — NAKA widget descriptors (fully decoded)
 *
 * Base ROM address: 0xE1A73E
 * Total size: 1050 bytes
 * Auto-generated by scripts/naka_struct_decode.py
 */

#include "naka_types.h"

/* ── External symbols (resolved by linker script) ── */

extern const char Naka_PresentationRootState;
extern const char PlySngSel2Func;

#define BASE  0x00E1A73Eu

/* NAKA class AcWindowPage -- class id 0x01600025 (Class table slot 0x160, entry 37),
 * parent PsPageBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t page;              /* +28 n */
    uint16_t pagemin;           /* +32 A */
    uint16_t pagemax;           /* +34 A */
} naka_cls_AcWindowPage_t;

/* NAKA class IvPageControl -- class id 0x01600028 (Class table slot 0x160, entry 40),
 * parent PsInvisibleBox; allsize 28.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t page;              /* +22 A */
    uint32_t window;            /* +24 t */
} naka_cls_IvPageControl_t;

/* NAKA class IvShowHide -- class id 0x01600064 (Class table slot 0x160, entry 100),
 * parent PsInvisibleBox; allsize 26.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint32_t func;              /* +22 j */
} naka_cls_IvShowHide_t;

/* NAKA class IvIntVari -- class id 0x01600062 (Class table slot 0x160, entry 98),
 * parent IvInterrupt; allsize 24.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t time;              /* +22 w */
} naka_cls_IvIntVari_t;

/* NAKA class Window -- class id 0x01600035 (Class table slot 0x160, entry 53),
 * parent GroupBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t modal;             /* +26 G */
    uint32_t parent;            /* +28 r */
    uint32_t child;             /* +32 r */
} naka_cls_Window_t;

/* NAKA class VwVariBox -- class id 0x01640024 (Class table slot 0x164, entry 36),
 * parent VwBox; allsize 44.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
    uint16_t editsw;            /* +36 e */
    uint32_t selected;          /* +38 m */
    uint8_t mspbnk;            /* +42 C */
    uint8_t _pad_43[1];
} naka_cls_VwVariBox_t;

typedef struct __attribute__((packed)) {
    /* element 1 of Viewable slot 0xC8 "MspBkslWin": AcWindowPage (class id 0x01600025) */
    naka_cls_AcWindowPage_t MspBkslWin;
    /* element 2 of Viewable slot 0xC8 "MspBnkP1Ctl": IvPageControl (class id 0x01600028) */
    naka_cls_IvPageControl_t MspBnkP1Ctl;
    /* element 3 of Viewable slot 0xC8 "MspBnkP2Ctl": IvPageControl (class id 0x01600028) */
    naka_cls_IvPageControl_t MspBnkP2Ctl;
    /* element 4 of Viewable slot 0xC8: IvShowHide (class id 0x01600064) */
    naka_cls_IvShowHide_t vC8_e4;
    /* element 5 of Viewable slot 0xC8: IvIntVari (class id 0x01600062) */
    naka_cls_IvIntVari_t vC8_e5;
    /* element 6 of Viewable slot 0xC8 "MspBkslP1Win": Window (class id 0x01600035) */
    naka_cls_Window_t MspBkslP1Win;
    /* element 7 of Viewable slot 0xC8 "Eff1Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t Eff1Bnk;
    /* element 8 of Viewable slot 0xC8 "Eff2Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t Eff2Bnk;
    /* element 9 of Viewable slot 0xC8 "ComicBnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t ComicBnk;
    /* element 10 of Viewable slot 0xC8 "MovieBnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t MovieBnk;
    /* element 11 of Viewable slot 0xC8 "EnterBnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t EnterBnk;
    /* element 12 of Viewable slot 0xC8 "ArpgioBnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t ArpgioBnk;
    /* element 13 of Viewable slot 0xC8 "Rock1Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t Rock1Bnk;
    /* element 14 of Viewable slot 0xC8 "Rock2Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t Rock2Bnk;
    /* element 15 of Viewable slot 0xC8 "DanceBnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t DanceBnk;
    /* element 16 of Viewable slot 0xC8 "FunkBnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t FunkBnk;
    /* element 17 of Viewable slot 0xC8 "MspBkslP2Win": Window (class id 0x01600035) */
    naka_cls_Window_t MspBkslP2Win;
    /* element 18 of Viewable slot 0xC8 "JazzBnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t JazzBnk;
    /* element 19 of Viewable slot 0xC8 "LatinBnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t LatinBnk;
    /* element 20 of Viewable slot 0xC8 "HitBnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t HitBnk;
    /* element 21 of Viewable slot 0xC8 "User1Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t User1Bnk;
    /* element 22 of Viewable slot 0xC8 "User2Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t User2Bnk;
    /* element 23 of Viewable slot 0xC8 "Cmpile1Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t Cmpile1Bnk;
    /* element 24 of Viewable slot 0xC8 "Cmpile2Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t Cmpile2Bnk;
    /* element 25 of Viewable slot 0xC8 "Ctrl1Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t Ctrl1Bnk;
    /* element 26 of Viewable slot 0xC8 "Ctrl2Bnk": VwVariBox (class id 0x01640024) */
    naka_cls_VwVariBox_t Ctrl2Bnk;
} naka_accomp7_widgets_t;

#define SELF(field) \
    ((uint32_t)(BASE + __builtin_offsetof(naka_accomp7_widgets_t, field)))

_Static_assert(sizeof(naka_accomp7_widgets_t) == 1050,
    "naka_accomp7_widgets must be exactly 1050 bytes");

const naka_accomp7_widgets_t naka_accomp7_widgets_data
    __attribute__((section(".text"), used)) = {

    .MspBkslWin = {
        .class_ = 0x01600025,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 2,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 245, 6, 315, 23 },
        .color = 0x00F3,
        .border = 0x00C1,
        .index = 0xFFFF,
        .page = 0x0003D72A,
        .pagemin = 0x0001,
        .pagemax = 0x0002,
    },

    .MspBnkP1Ctl = {
        .class_ = 0x01600028,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 3,
        .prev = 1,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .page = 0x0001,
        .window = 0x00C80006,
    },

    .MspBnkP2Ctl = {
        .class_ = 0x01600028,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 4,
        .prev = 2,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .page = 0x0002,
        .window = 0x00C80011,
    },

    .vC8_e4 = {
        .class_ = 0x01600064,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 5,
        .prev = 3,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .func = 0x01240016,
    },

    .vC8_e5 = {
        .class_ = 0x01600062,
        .super = 0,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 4,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .time = 0x0001,
    },

    .MspBkslP1Win = {
        .class_ = 0x01600035,
        .super = NAKA_NONE,
        .sub = 7,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 0, 30, 319, 239 },
        .color = 0x00F5,
        .border = 0x0000,
        .modal = 0x0000,
        .parent = 0x0003D72C,
        .child = 0x0003D730,
    },

    .Eff1Bnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 8,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 8, 30, 156, 55 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x0088,
        .selected = 0x0003D734,
        .mspbnk = 0x00,
        ._pad_43 = { 0x00 },
    },

    .Eff2Bnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 9,
        .prev = 7,
        .flag = 0x0008,
        .rect = { 8, 72, 156, 97 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x0089,
        .selected = 0x0003D736,
        .mspbnk = 0x01,
        ._pad_43 = { 0x00 },
    },

    .ComicBnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 10,
        .prev = 8,
        .flag = 0x0008,
        .rect = { 8, 114, 156, 139 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x008A,
        .selected = 0x0003D738,
        .mspbnk = 0x02,
        ._pad_43 = { 0x00 },
    },

    .MovieBnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 11,
        .prev = 9,
        .flag = 0x0008,
        .rect = { 8, 156, 156, 181 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x008B,
        .selected = 0x0003D73A,
        .mspbnk = 0x03,
        ._pad_43 = { 0x00 },
    },

    .EnterBnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 12,
        .prev = 10,
        .flag = 0x0008,
        .rect = { 8, 198, 156, 223 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x008C,
        .selected = 0x0003D73C,
        .mspbnk = 0x04,
        ._pad_43 = { 0x00 },
    },

    .ArpgioBnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 13,
        .prev = 11,
        .flag = 0x0008,
        .rect = { 163, 30, 311, 55 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x0008,
        .selected = 0x0003D73E,
        .mspbnk = 0x05,
        ._pad_43 = { 0x00 },
    },

    .Rock1Bnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 14,
        .prev = 12,
        .flag = 0x0008,
        .rect = { 163, 72, 311, 97 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x0009,
        .selected = 0x0003D740,
        .mspbnk = 0x06,
        ._pad_43 = { 0x00 },
    },

    .Rock2Bnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 15,
        .prev = 13,
        .flag = 0x0008,
        .rect = { 163, 114, 311, 139 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x000A,
        .selected = 0x0003D742,
        .mspbnk = 0x07,
        ._pad_43 = { 0x00 },
    },

    .DanceBnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 16,
        .prev = 14,
        .flag = 0x0008,
        .rect = { 163, 156, 311, 181 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x000B,
        .selected = 0x0003D744,
        .mspbnk = 0x08,
        ._pad_43 = { 0x00 },
    },

    .FunkBnk = {
        .class_ = 0x01640024,
        .super = 6,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 15,
        .flag = 0x0008,
        .rect = { 163, 198, 311, 223 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x000C,
        .selected = 0x0003D746,
        .mspbnk = 0x09,
        ._pad_43 = { 0x00 },
    },

    .MspBkslP2Win = {
        .class_ = 0x01600035,
        .super = NAKA_NONE,
        .sub = 18,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 0, 30, 319, 239 },
        .color = 0x00F5,
        .border = 0x0000,
        .modal = 0x0000,
        .parent = 0x0003D748,
        .child = 0x0003D74C,
    },

    .JazzBnk = {
        .class_ = 0x01640024,
        .super = 17,
        .sub = NAKA_NONE,
        .next = 19,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 8, 30, 156, 55 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x0088,
        .selected = 0x0003D750,
        .mspbnk = 0x0A,
        ._pad_43 = { 0x00 },
    },

    .LatinBnk = {
        .class_ = 0x01640024,
        .super = 17,
        .sub = NAKA_NONE,
        .next = 20,
        .prev = 18,
        .flag = 0x0008,
        .rect = { 8, 72, 156, 97 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x0089,
        .selected = 0x0003D752,
        .mspbnk = 0x0B,
        ._pad_43 = { 0x00 },
    },

    .HitBnk = {
        .class_ = 0x01640024,
        .super = 17,
        .sub = NAKA_NONE,
        .next = 21,
        .prev = 19,
        .flag = 0x0008,
        .rect = { 8, 114, 156, 139 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x008A,
        .selected = 0x0003D754,
        .mspbnk = 0x0C,
        ._pad_43 = { 0x00 },
    },

    .User1Bnk = {
        .class_ = 0x01640024,
        .super = 17,
        .sub = NAKA_NONE,
        .next = 22,
        .prev = 20,
        .flag = 0x0008,
        .rect = { 8, 156, 156, 181 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x008B,
        .selected = 0x0003D756,
        .mspbnk = 0x0D,
        ._pad_43 = { 0x00 },
    },

    .User2Bnk = {
        .class_ = 0x01640024,
        .super = 17,
        .sub = NAKA_NONE,
        .next = 23,
        .prev = 21,
        .flag = 0x0008,
        .rect = { 8, 198, 156, 223 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x008C,
        .selected = 0x0003D758,
        .mspbnk = 0x0E,
        ._pad_43 = { 0x00 },
    },

    .Cmpile1Bnk = {
        .class_ = 0x01640024,
        .super = 17,
        .sub = NAKA_NONE,
        .next = 24,
        .prev = 22,
        .flag = 0x0008,
        .rect = { 163, 30, 311, 55 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x0008,
        .selected = 0x0003D75A,
        .mspbnk = 0x0F,
        ._pad_43 = { 0x00 },
    },

    .Cmpile2Bnk = {
        .class_ = 0x01640024,
        .super = 17,
        .sub = NAKA_NONE,
        .next = 25,
        .prev = 23,
        .flag = 0x0008,
        .rect = { 163, 72, 311, 97 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x0009,
        .selected = 0x0003D75C,
        .mspbnk = 0x10,
        ._pad_43 = { 0x00 },
    },

    .Ctrl1Bnk = {
        .class_ = 0x01640024,
        .super = 17,
        .sub = NAKA_NONE,
        .next = 26,
        .prev = 24,
        .flag = 0x0008,
        .rect = { 163, 114, 311, 139 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x000A,
        .selected = 0x0003D75E,
        .mspbnk = 0x11,
        ._pad_43 = { 0x00 },
    },

    .Ctrl2Bnk = {
        .class_ = 0x01640024,
        .super = 17,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 25,
        .flag = 0x0008,
        .rect = { 163, 156, 311, 181 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0001,
        .editsw = 0x000B,
        .selected = 0x0003D760,
        .mspbnk = 0x12,
        ._pad_43 = { 0x00 },
    },

};

#undef SELF
#undef BASE
