/**
 * naka_accomp7_widgets.c — NAKA widget descriptors (fully decoded)
 *
 * Base ROM address: 0xE1A73E
 * Total size: 1050 bytes
 * Auto-generated by scripts/naka_struct_decode.py
 */

#include "naka_types.h"

/* ── External symbols (resolved by linker script) ── */

extern const char Naka_PresentationRootState;
extern const char PlySngSel2Func;

#define BASE  0x00E1A73Eu

typedef struct __attribute__((packed)) {
    naka_dispatch_t w0;  /* 0x25 */
    uint16_t field_0018;
    uint16_t field_001a;
    uint16_t field_001c;
    uint16_t field_001e;
    uint16_t field_0020;
    uint16_t field_0022;
    char str_0[2];
    uint16_t field_0026;
    uint8_t pad_0[2];  /* zero padding */
    uint16_t field_002a;
    uint16_t field_002c;
    uint16_t field_002e;
    uint16_t field_0030;
    uint8_t pad_1[4];  /* zero padding */
    uint16_t field_0036;
    uint16_t field_0038;
    uint16_t field_003a;
    uint16_t field_003c;
    uint16_t field_003e;
    char str_1[2];
    uint16_t field_0042;
    uint8_t pad_2[2];  /* zero padding */
    uint16_t field_0046;
    uint16_t field_0048;
    uint16_t field_004a;
    uint16_t field_004c;
    uint8_t pad_3[4];  /* zero padding */
    uint16_t field_0052;
    uint16_t field_0054;
    uint16_t field_0056;
    uint16_t field_0058;
    uint16_t field_005a;
    char str_2[2];
    uint16_t field_005e;
    uint8_t pad_4[2];  /* zero padding */
    uint16_t field_0062;
    uint16_t field_0064;
    uint16_t field_0066;
    uint16_t field_0068;
    uint8_t pad_5[4];  /* zero padding */
    uint16_t field_006e;
    uint16_t field_0070;
    uint16_t field_0072;
    uint16_t field_0074;
    char str_3[2];
    uint16_t field_0078;
    uint8_t pad_6[2];  /* zero padding */
    uint16_t field_007c;
    uint16_t field_007e;
    uint16_t field_0080;
    uint16_t field_0082;
    uint8_t pad_7[4];  /* zero padding */
    uint16_t field_0088;
    uint16_t field_008a;
    uint16_t field_008c;
    char str_4[2];
    uint16_t field_0090;
    uint16_t field_0092;
    uint16_t field_0094;
    uint16_t field_0096;
    uint16_t field_0098;
    uint16_t field_009a;
    uint8_t pad_8[2];  /* zero padding */
    uint16_t field_009e;
    uint32_t ptr_00a0;
    uint16_t field_00a4;
    uint8_t pad_9[4];  /* zero padding */
    uint16_t field_00aa;
    uint16_t field_00ac;
    uint16_t field_00ae;
    uint16_t field_00b0;
    char str_5[2];
    uint16_t field_00b4;
    uint16_t field_00b6;
    uint16_t field_00b8;
    uint16_t field_00ba;
    uint16_t field_00bc;
    uint16_t field_00be;
    uint16_t field_00c0;
    uint16_t field_00c2;
    uint16_t field_00c4;
    char str_6[2];
    uint16_t field_00c8;
    uint16_t field_00ca;
    uint8_t pad_10[8];  /* zero padding */
    uint16_t field_00d4;
    uint16_t field_00d6;
    uint16_t field_00d8;
    uint16_t field_00da;
    uint8_t pad_11[2];  /* zero padding */
    char str_7[2];
    uint16_t field_00e0;
    uint16_t field_00e2;
    uint16_t field_00e4;
    uint16_t field_00e6;
    uint16_t field_00e8;
    uint16_t field_00ea;
    uint16_t field_00ec;
    char str_8[2];
    uint16_t field_00f0;
    char str_9[2];
    uint16_t field_00f4;
    uint16_t field_00f6;
    uint8_t pad_12[8];  /* zero padding */
    uint16_t field_0100;
    uint16_t field_0102;
    uint16_t field_0104;
    uint16_t field_0106;
    uint16_t field_0108;
    char str_10[2];
    uint16_t field_010c;
    uint16_t field_010e;
    uint16_t field_0110;
    uint16_t field_0112;
    uint16_t field_0114;
    uint16_t field_0116;
    uint16_t field_0118;
    char str_11[2];
    uint16_t field_011c;
    uint16_t field_011e;
    uint16_t field_0120;
    uint16_t field_0122;
    uint8_t pad_13[8];  /* zero padding */
    uint16_t field_012c;
    uint16_t field_012e;
    uint16_t field_0130;
    uint16_t field_0132;
    uint16_t field_0134;
    char str_12[2];
    uint16_t field_0138;
    uint16_t field_013a;
    uint16_t field_013c;
    uint16_t field_013e;
    uint16_t field_0140;
    uint16_t field_0142;
    uint16_t field_0144;
    uint16_t field_0146;
    uint16_t field_0148;
    uint16_t field_014a;
    uint16_t field_014c;
    uint16_t field_014e;
    uint8_t pad_14[8];  /* zero padding */
    uint16_t field_0158;
    uint16_t field_015a;
    uint16_t field_015c;
    uint16_t field_015e;
    uint16_t field_0160;
    char str_13[2];
    uint16_t field_0164;
    uint16_t field_0166;
    uint16_t field_0168;
    uint16_t field_016a;
    uint16_t field_016c;
    uint16_t field_016e;
    uint16_t field_0170;
    uint16_t field_0172;
    uint16_t field_0174;
    uint16_t field_0176;
    uint16_t field_0178;
    uint16_t field_017a;
    uint8_t pad_15[8];  /* zero padding */
    uint16_t field_0184;
    uint16_t field_0186;
    uint16_t field_0188;
    uint16_t field_018a;
    uint16_t field_018c;
    char str_14[2];
    uint16_t field_0190;
    uint16_t field_0192;
    uint16_t field_0194;
    uint16_t field_0196;
    uint16_t field_0198;
    uint16_t field_019a;
    uint16_t field_019c;
    uint16_t field_019e;
    uint16_t field_01a0;
    char str_15[2];
    uint16_t field_01a4;
    uint16_t field_01a6;
    uint8_t pad_16[8];  /* zero padding */
    uint16_t field_01b0;
    uint16_t field_01b2;
    uint16_t field_01b4;
    uint16_t field_01b6;
    uint16_t field_01b8;
    char str_16[2];
    uint16_t field_01bc;
    uint16_t field_01be;
    uint16_t field_01c0;
    uint16_t field_01c2;
    uint16_t field_01c4;
    uint16_t field_01c6;
    uint16_t field_01c8;
    char str_17[2];
    uint16_t field_01cc;
    char str_18[2];
    uint16_t field_01d0;
    uint16_t field_01d2;
    uint8_t pad_17[8];  /* zero padding */
    uint16_t field_01dc;
    uint16_t field_01de;
    uint16_t field_01e0;
    uint16_t field_01e2;
    uint16_t field_01e4;
    char str_19[2];
    uint16_t field_01e8;
    uint16_t field_01ea;
    uint16_t field_01ec;
    uint16_t field_01ee;
    uint16_t field_01f0;
    uint16_t field_01f2;
    uint16_t field_01f4;
    char str_20[2];
    uint16_t field_01f8;
    uint16_t field_01fa;
    uint16_t field_01fc;
    uint16_t field_01fe;
    uint8_t pad_18[8];  /* zero padding */
    uint16_t field_0208;
    uint16_t field_020a;
    uint16_t field_020c;
    uint16_t field_020e;
    uint16_t field_0210;
    char str_21[2];
    uint16_t field_0214;
    uint16_t field_0216;
    uint16_t field_0218;
    uint16_t field_021a;
    uint16_t field_021c;
    uint16_t field_021e;
    uint16_t field_0220;
    uint16_t field_0222;
    uint16_t field_0224;
    uint16_t field_0226;
    uint16_t field_0228;
    uint16_t field_022a;
    uint8_t pad_19[8];  /* zero padding */
    uint16_t field_0234;
    uint16_t field_0236;
    uint16_t field_0238;
    uint16_t field_023a;
    uint16_t field_023c;
    char str_22[2];
    uint16_t field_0240;
    uint16_t field_0242;
    uint16_t field_0244;
    uint16_t field_0246;
    uint16_t field_0248;
    uint16_t field_024a;
    uint16_t field_024c;
    uint16_t field_024e;
    uint16_t field_0250;
    uint16_t field_0252;
    uint16_t field_0254;
    uint16_t field_0256;
    uint8_t pad_20[8];  /* zero padding */
    uint16_t field_0260;
    uint16_t field_0262;
    uint16_t field_0264;
    uint16_t field_0266;
    uint16_t field_0268;
    char str_23[2];
    uint16_t field_026c;
    uint16_t field_026e;
    uint16_t field_0270;
    uint16_t field_0272;
    uint16_t field_0274;
    uint16_t field_0276;
    uint8_t pad_21[2];  /* zero padding */
    uint16_t field_027a;
    uint32_t ptr_027c;
    uint16_t field_0280;
    uint8_t pad_22[4];  /* zero padding */
    uint16_t field_0286;
    uint16_t field_0288;
    uint16_t field_028a;
    uint16_t field_028c;
    char str_24[2];
    uint16_t field_0290;
    uint16_t field_0292;
    uint16_t field_0294;
    uint16_t field_0296;
    uint16_t field_0298;
    uint16_t field_029a;
    uint16_t field_029c;
    uint16_t field_029e;
    uint16_t field_02a0;
    char str_25[2];
    uint16_t field_02a4;
    uint16_t field_02a6;
    uint8_t pad_23[8];  /* zero padding */
    uint16_t field_02b0;
    uint16_t field_02b2;
    uint16_t field_02b4;
    uint16_t field_02b6;
    uint16_t field_02b8;
    char str_26[2];
    uint16_t field_02bc;
    uint16_t field_02be;
    uint16_t field_02c0;
    uint16_t field_02c2;
    uint16_t field_02c4;
    uint16_t field_02c6;
    uint16_t field_02c8;
    char str_27[2];
    uint16_t field_02cc;
    char str_28[2];
    uint16_t field_02d0;
    uint16_t field_02d2;
    uint8_t pad_24[8];  /* zero padding */
    uint16_t field_02dc;
    uint16_t field_02de;
    uint16_t field_02e0;
    uint16_t field_02e2;
    uint16_t field_02e4;
    char str_29[2];
    uint16_t field_02e8;
    uint16_t field_02ea;
    uint16_t field_02ec;
    uint16_t field_02ee;
    uint16_t field_02f0;
    uint16_t field_02f2;
    uint16_t field_02f4;
    char str_30[2];
    uint16_t field_02f8;
    uint16_t field_02fa;
    uint16_t field_02fc;
    uint16_t field_02fe;
    uint8_t pad_25[8];  /* zero padding */
    uint16_t field_0308;
    uint16_t field_030a;
    uint16_t field_030c;
    uint16_t field_030e;
    uint16_t field_0310;
    char str_31[2];
    uint16_t field_0314;
    uint16_t field_0316;
    uint16_t field_0318;
    uint16_t field_031a;
    uint16_t field_031c;
    uint16_t field_031e;
    uint16_t field_0320;
    uint16_t field_0322;
    uint16_t field_0324;
    uint16_t field_0326;
    uint16_t field_0328;
    uint16_t field_032a;
    uint8_t pad_26[8];  /* zero padding */
    uint16_t field_0334;
    uint16_t field_0336;
    uint16_t field_0338;
    uint16_t field_033a;
    uint16_t field_033c;
    char str_32[2];
    uint16_t field_0340;
    uint16_t field_0342;
    uint16_t field_0344;
    uint16_t field_0346;
    uint16_t field_0348;
    uint16_t field_034a;
    uint16_t field_034c;
    uint16_t field_034e;
    uint16_t field_0350;
    uint16_t field_0352;
    uint16_t field_0354;
    uint16_t field_0356;
    uint8_t pad_27[8];  /* zero padding */
    uint16_t field_0360;
    uint16_t field_0362;
    uint16_t field_0364;
    uint16_t field_0366;
    uint16_t field_0368;
    char str_33[2];
    uint16_t field_036c;
    uint16_t field_036e;
    uint16_t field_0370;
    uint16_t field_0372;
    uint16_t field_0374;
    uint16_t field_0376;
    uint16_t field_0378;
    uint16_t field_037a;
    uint16_t field_037c;
    char str_34[2];
    uint16_t field_0380;
    uint16_t field_0382;
    uint8_t pad_28[8];  /* zero padding */
    uint16_t field_038c;
    uint16_t field_038e;
    uint16_t field_0390;
    uint16_t field_0392;
    uint16_t field_0394;
    char str_35[2];
    uint16_t field_0398;
    uint16_t field_039a;
    uint16_t field_039c;
    uint16_t field_039e;
    uint16_t field_03a0;
    uint16_t field_03a2;
    uint16_t field_03a4;
    char str_36[2];
    uint16_t field_03a8;
    char str_37[2];
    uint16_t field_03ac;
    uint16_t field_03ae;
    uint8_t pad_29[8];  /* zero padding */
    uint16_t field_03b8;
    uint16_t field_03ba;
    uint16_t field_03bc;
    uint16_t field_03be;
    uint16_t field_03c0;
    char str_38[2];
    uint16_t field_03c4;
    uint16_t field_03c6;
    uint16_t field_03c8;
    uint16_t field_03ca;
    uint16_t field_03cc;
    uint16_t field_03ce;
    uint16_t field_03d0;
    char str_39[2];
    uint16_t field_03d4;
    uint16_t field_03d6;
    uint16_t field_03d8;
    uint16_t field_03da;
    uint8_t pad_30[8];  /* zero padding */
    uint16_t field_03e4;
    uint16_t field_03e6;
    uint16_t field_03e8;
    uint16_t field_03ea;
    uint16_t field_03ec;
    char str_40[2];
    uint16_t field_03f0;
    uint16_t field_03f2;
    uint16_t field_03f4;
    uint16_t field_03f6;
    uint16_t field_03f8;
    uint16_t field_03fa;
    uint16_t field_03fc;
    uint16_t field_03fe;
    uint16_t field_0400;
    uint16_t field_0402;
    uint16_t field_0404;
    uint16_t field_0406;
    uint8_t pad_31[8];  /* zero padding */
    uint16_t field_0410;
    uint16_t field_0412;
    uint16_t field_0414;
    uint16_t field_0416;
    uint16_t field_0418;
} naka_accomp7_widgets_t;

#define SELF(field) \
    ((uint32_t)(BASE + __builtin_offsetof(naka_accomp7_widgets_t, field)))

_Static_assert(sizeof(naka_accomp7_widgets_t) == 1050,
    "naka_accomp7_widgets must be exactly 1050 bytes");

const naka_accomp7_widgets_t naka_accomp7_widgets_data
    __attribute__((section(".text"), used)) = {

    .w0 = {
        .header    = NAKA_HDR(0x25),
        .field_04   = 0x0000,
        .field_06   = NAKA_NONE,
        .name_ptr   = 0xFFFF0002,
        .inst_ptr   = 0x00F50008,
        .link_ptr   = 0x013B0006,
        .proc_addr  = NAKA_ADDR(PlySngSel2Func),
    },

    .field_0018 = 0x00C1,

    .field_001a = NAKA_NONE,

    .field_001c = 0xD72A,

    .field_001e = 0x0003,

    .field_0020 = 0x0001,

    .field_0022 = 0x0002,

    .str_0 = "(",

    .field_0026 = 0x0160,

    .pad_0 = { 0 },

    .field_002a = NAKA_NONE,

    .field_002c = 0x0003,

    .field_002e = 0x0001,

    .field_0030 = 0x0018,

    .pad_1 = { 0 },

    .field_0036 = 0x001F,

    .field_0038 = 0x001F,

    .field_003a = 0x0001,

    .field_003c = 0x0006,

    .field_003e = 0x00C8,

    .str_1 = "(",

    .field_0042 = 0x0160,

    .pad_2 = { 0 },

    .field_0046 = NAKA_NONE,

    .field_0048 = 0x0004,

    .field_004a = 0x0002,

    .field_004c = 0x0018,

    .pad_3 = { 0 },

    .field_0052 = 0x001F,

    .field_0054 = 0x001F,

    .field_0056 = 0x0002,

    .field_0058 = 0x0011,

    .field_005a = 0x00C8,

    .str_2 = "d",

    .field_005e = 0x0160,

    .pad_4 = { 0 },

    .field_0062 = NAKA_NONE,

    .field_0064 = 0x0005,

    .field_0066 = 0x0003,

    .field_0068 = 0x0018,

    .pad_5 = { 0 },

    .field_006e = 0x001F,

    .field_0070 = 0x001F,

    .field_0072 = 0x0016,

    .field_0074 = 0x0124,

    .str_3 = "b",

    .field_0078 = 0x0160,

    .pad_6 = { 0 },

    .field_007c = NAKA_NONE,

    .field_007e = NAKA_NONE,

    .field_0080 = 0x0004,

    .field_0082 = 0x0018,

    .pad_7 = { 0 },

    .field_0088 = 0x001F,

    .field_008a = 0x001F,

    .field_008c = 0x0001,

    .str_4 = "5",

    .field_0090 = 0x0160,

    .field_0092 = NAKA_NONE,

    .field_0094 = 0x0007,

    .field_0096 = NAKA_NONE,

    .field_0098 = NAKA_NONE,

    .field_009a = 0x0008,

    .pad_8 = { 0 },

    .field_009e = 0x001E,

    .ptr_00a0 = NAKA_ADDR(Naka_PresentationRootState),

    .field_00a4 = 0x00F5,

    .pad_9 = { 0 },

    .field_00aa = 0xD72C,

    .field_00ac = 0x0003,

    .field_00ae = 0xD730,

    .field_00b0 = 0x0003,

    .str_5 = "$",

    .field_00b4 = 0x0164,

    .field_00b6 = 0x0006,

    .field_00b8 = NAKA_NONE,

    .field_00ba = 0x0008,

    .field_00bc = NAKA_NONE,

    .field_00be = 0x0008,

    .field_00c0 = 0x0008,

    .field_00c2 = 0x001E,

    .field_00c4 = 0x009C,

    .str_6 = "7",

    .field_00c8 = 0x0007,

    .field_00ca = 0x00C1,

    .pad_10 = { 0 },

    .field_00d4 = 0x0001,

    .field_00d6 = 0x0088,

    .field_00d8 = 0xD734,

    .field_00da = 0x0003,

    .pad_11 = { 0 },

    .str_7 = "$",

    .field_00e0 = 0x0164,

    .field_00e2 = 0x0006,

    .field_00e4 = NAKA_NONE,

    .field_00e6 = 0x0009,

    .field_00e8 = 0x0007,

    .field_00ea = 0x0008,

    .field_00ec = 0x0008,

    .str_8 = "H",

    .field_00f0 = 0x009C,

    .str_9 = "a",

    .field_00f4 = 0x0007,

    .field_00f6 = 0x00C1,

    .pad_12 = { 0 },

    .field_0100 = 0x0001,

    .field_0102 = 0x0089,

    .field_0104 = 0xD736,

    .field_0106 = 0x0003,

    .field_0108 = 0x0001,

    .str_10 = "$",

    .field_010c = 0x0164,

    .field_010e = 0x0006,

    .field_0110 = NAKA_NONE,

    .field_0112 = 0x000A,

    .field_0114 = 0x0008,

    .field_0116 = 0x0008,

    .field_0118 = 0x0008,

    .str_11 = "r",

    .field_011c = 0x009C,

    .field_011e = 0x008B,

    .field_0120 = 0x0007,

    .field_0122 = 0x00C1,

    .pad_13 = { 0 },

    .field_012c = 0x0001,

    .field_012e = 0x008A,

    .field_0130 = 0xD738,

    .field_0132 = 0x0003,

    .field_0134 = 0x0002,

    .str_12 = "$",

    .field_0138 = 0x0164,

    .field_013a = 0x0006,

    .field_013c = NAKA_NONE,

    .field_013e = 0x000B,

    .field_0140 = 0x0009,

    .field_0142 = 0x0008,

    .field_0144 = 0x0008,

    .field_0146 = 0x009C,

    .field_0148 = 0x009C,

    .field_014a = 0x00B5,

    .field_014c = 0x0007,

    .field_014e = 0x00C1,

    .pad_14 = { 0 },

    .field_0158 = 0x0001,

    .field_015a = 0x008B,

    .field_015c = 0xD73A,

    .field_015e = 0x0003,

    .field_0160 = 0x0003,

    .str_13 = "$",

    .field_0164 = 0x0164,

    .field_0166 = 0x0006,

    .field_0168 = NAKA_NONE,

    .field_016a = 0x000C,

    .field_016c = 0x000A,

    .field_016e = 0x0008,

    .field_0170 = 0x0008,

    .field_0172 = 0x00C6,

    .field_0174 = 0x009C,

    .field_0176 = 0x00DF,

    .field_0178 = 0x0007,

    .field_017a = 0x00C1,

    .pad_15 = { 0 },

    .field_0184 = 0x0001,

    .field_0186 = 0x008C,

    .field_0188 = 0xD73C,

    .field_018a = 0x0003,

    .field_018c = 0x0004,

    .str_14 = "$",

    .field_0190 = 0x0164,

    .field_0192 = 0x0006,

    .field_0194 = NAKA_NONE,

    .field_0196 = 0x000D,

    .field_0198 = 0x000B,

    .field_019a = 0x0008,

    .field_019c = 0x00A3,

    .field_019e = 0x001E,

    .field_01a0 = 0x0137,

    .str_15 = "7",

    .field_01a4 = 0x0007,

    .field_01a6 = 0x00C1,

    .pad_16 = { 0 },

    .field_01b0 = 0x0001,

    .field_01b2 = 0x0008,

    .field_01b4 = 0xD73E,

    .field_01b6 = 0x0003,

    .field_01b8 = 0x0005,

    .str_16 = "$",

    .field_01bc = 0x0164,

    .field_01be = 0x0006,

    .field_01c0 = NAKA_NONE,

    .field_01c2 = 0x000E,

    .field_01c4 = 0x000C,

    .field_01c6 = 0x0008,

    .field_01c8 = 0x00A3,

    .str_17 = "H",

    .field_01cc = 0x0137,

    .str_18 = "a",

    .field_01d0 = 0x0007,

    .field_01d2 = 0x00C1,

    .pad_17 = { 0 },

    .field_01dc = 0x0001,

    .field_01de = 0x0009,

    .field_01e0 = 0xD740,

    .field_01e2 = 0x0003,

    .field_01e4 = 0x0006,

    .str_19 = "$",

    .field_01e8 = 0x0164,

    .field_01ea = 0x0006,

    .field_01ec = NAKA_NONE,

    .field_01ee = 0x000F,

    .field_01f0 = 0x000D,

    .field_01f2 = 0x0008,

    .field_01f4 = 0x00A3,

    .str_20 = "r",

    .field_01f8 = 0x0137,

    .field_01fa = 0x008B,

    .field_01fc = 0x0007,

    .field_01fe = 0x00C1,

    .pad_18 = { 0 },

    .field_0208 = 0x0001,

    .field_020a = 0x000A,

    .field_020c = 0xD742,

    .field_020e = 0x0003,

    .field_0210 = 0x0007,

    .str_21 = "$",

    .field_0214 = 0x0164,

    .field_0216 = 0x0006,

    .field_0218 = NAKA_NONE,

    .field_021a = 0x0010,

    .field_021c = 0x000E,

    .field_021e = 0x0008,

    .field_0220 = 0x00A3,

    .field_0222 = 0x009C,

    .field_0224 = 0x0137,

    .field_0226 = 0x00B5,

    .field_0228 = 0x0007,

    .field_022a = 0x00C1,

    .pad_19 = { 0 },

    .field_0234 = 0x0001,

    .field_0236 = 0x000B,

    .field_0238 = 0xD744,

    .field_023a = 0x0003,

    .field_023c = 0x0008,

    .str_22 = "$",

    .field_0240 = 0x0164,

    .field_0242 = 0x0006,

    .field_0244 = NAKA_NONE,

    .field_0246 = NAKA_NONE,

    .field_0248 = 0x000F,

    .field_024a = 0x0008,

    .field_024c = 0x00A3,

    .field_024e = 0x00C6,

    .field_0250 = 0x0137,

    .field_0252 = 0x00DF,

    .field_0254 = 0x0007,

    .field_0256 = 0x00C1,

    .pad_20 = { 0 },

    .field_0260 = 0x0001,

    .field_0262 = 0x000C,

    .field_0264 = 0xD746,

    .field_0266 = 0x0003,

    .field_0268 = 0x0009,

    .str_23 = "5",

    .field_026c = 0x0160,

    .field_026e = NAKA_NONE,

    .field_0270 = 0x0012,

    .field_0272 = NAKA_NONE,

    .field_0274 = NAKA_NONE,

    .field_0276 = 0x0008,

    .pad_21 = { 0 },

    .field_027a = 0x001E,

    .ptr_027c = NAKA_ADDR(Naka_PresentationRootState),

    .field_0280 = 0x00F5,

    .pad_22 = { 0 },

    .field_0286 = 0xD748,

    .field_0288 = 0x0003,

    .field_028a = 0xD74C,

    .field_028c = 0x0003,

    .str_24 = "$",

    .field_0290 = 0x0164,

    .field_0292 = 0x0011,

    .field_0294 = NAKA_NONE,

    .field_0296 = 0x0013,

    .field_0298 = NAKA_NONE,

    .field_029a = 0x0008,

    .field_029c = 0x0008,

    .field_029e = 0x001E,

    .field_02a0 = 0x009C,

    .str_25 = "7",

    .field_02a4 = 0x0007,

    .field_02a6 = 0x00C1,

    .pad_23 = { 0 },

    .field_02b0 = 0x0001,

    .field_02b2 = 0x0088,

    .field_02b4 = 0xD750,

    .field_02b6 = 0x0003,

    .field_02b8 = 0x000A,

    .str_26 = "$",

    .field_02bc = 0x0164,

    .field_02be = 0x0011,

    .field_02c0 = NAKA_NONE,

    .field_02c2 = 0x0014,

    .field_02c4 = 0x0012,

    .field_02c6 = 0x0008,

    .field_02c8 = 0x0008,

    .str_27 = "H",

    .field_02cc = 0x009C,

    .str_28 = "a",

    .field_02d0 = 0x0007,

    .field_02d2 = 0x00C1,

    .pad_24 = { 0 },

    .field_02dc = 0x0001,

    .field_02de = 0x0089,

    .field_02e0 = 0xD752,

    .field_02e2 = 0x0003,

    .field_02e4 = 0x000B,

    .str_29 = "$",

    .field_02e8 = 0x0164,

    .field_02ea = 0x0011,

    .field_02ec = NAKA_NONE,

    .field_02ee = 0x0015,

    .field_02f0 = 0x0013,

    .field_02f2 = 0x0008,

    .field_02f4 = 0x0008,

    .str_30 = "r",

    .field_02f8 = 0x009C,

    .field_02fa = 0x008B,

    .field_02fc = 0x0007,

    .field_02fe = 0x00C1,

    .pad_25 = { 0 },

    .field_0308 = 0x0001,

    .field_030a = 0x008A,

    .field_030c = 0xD754,

    .field_030e = 0x0003,

    .field_0310 = 0x000C,

    .str_31 = "$",

    .field_0314 = 0x0164,

    .field_0316 = 0x0011,

    .field_0318 = NAKA_NONE,

    .field_031a = 0x0016,

    .field_031c = 0x0014,

    .field_031e = 0x0008,

    .field_0320 = 0x0008,

    .field_0322 = 0x009C,

    .field_0324 = 0x009C,

    .field_0326 = 0x00B5,

    .field_0328 = 0x0007,

    .field_032a = 0x00C1,

    .pad_26 = { 0 },

    .field_0334 = 0x0001,

    .field_0336 = 0x008B,

    .field_0338 = 0xD756,

    .field_033a = 0x0003,

    .field_033c = 0x000D,

    .str_32 = "$",

    .field_0340 = 0x0164,

    .field_0342 = 0x0011,

    .field_0344 = NAKA_NONE,

    .field_0346 = 0x0017,

    .field_0348 = 0x0015,

    .field_034a = 0x0008,

    .field_034c = 0x0008,

    .field_034e = 0x00C6,

    .field_0350 = 0x009C,

    .field_0352 = 0x00DF,

    .field_0354 = 0x0007,

    .field_0356 = 0x00C1,

    .pad_27 = { 0 },

    .field_0360 = 0x0001,

    .field_0362 = 0x008C,

    .field_0364 = 0xD758,

    .field_0366 = 0x0003,

    .field_0368 = 0x000E,

    .str_33 = "$",

    .field_036c = 0x0164,

    .field_036e = 0x0011,

    .field_0370 = NAKA_NONE,

    .field_0372 = 0x0018,

    .field_0374 = 0x0016,

    .field_0376 = 0x0008,

    .field_0378 = 0x00A3,

    .field_037a = 0x001E,

    .field_037c = 0x0137,

    .str_34 = "7",

    .field_0380 = 0x0007,

    .field_0382 = 0x00C1,

    .pad_28 = { 0 },

    .field_038c = 0x0001,

    .field_038e = 0x0008,

    .field_0390 = 0xD75A,

    .field_0392 = 0x0003,

    .field_0394 = 0x000F,

    .str_35 = "$",

    .field_0398 = 0x0164,

    .field_039a = 0x0011,

    .field_039c = NAKA_NONE,

    .field_039e = 0x0019,

    .field_03a0 = 0x0017,

    .field_03a2 = 0x0008,

    .field_03a4 = 0x00A3,

    .str_36 = "H",

    .field_03a8 = 0x0137,

    .str_37 = "a",

    .field_03ac = 0x0007,

    .field_03ae = 0x00C1,

    .pad_29 = { 0 },

    .field_03b8 = 0x0001,

    .field_03ba = 0x0009,

    .field_03bc = 0xD75C,

    .field_03be = 0x0003,

    .field_03c0 = 0x0010,

    .str_38 = "$",

    .field_03c4 = 0x0164,

    .field_03c6 = 0x0011,

    .field_03c8 = NAKA_NONE,

    .field_03ca = 0x001A,

    .field_03cc = 0x0018,

    .field_03ce = 0x0008,

    .field_03d0 = 0x00A3,

    .str_39 = "r",

    .field_03d4 = 0x0137,

    .field_03d6 = 0x008B,

    .field_03d8 = 0x0007,

    .field_03da = 0x00C1,

    .pad_30 = { 0 },

    .field_03e4 = 0x0001,

    .field_03e6 = 0x000A,

    .field_03e8 = 0xD75E,

    .field_03ea = 0x0003,

    .field_03ec = 0x0011,

    .str_40 = "$",

    .field_03f0 = 0x0164,

    .field_03f2 = 0x0011,

    .field_03f4 = NAKA_NONE,

    .field_03f6 = NAKA_NONE,

    .field_03f8 = 0x0019,

    .field_03fa = 0x0008,

    .field_03fc = 0x00A3,

    .field_03fe = 0x009C,

    .field_0400 = 0x0137,

    .field_0402 = 0x00B5,

    .field_0404 = 0x0007,

    .field_0406 = 0x00C1,

    .pad_31 = { 0 },

    .field_0410 = 0x0001,

    .field_0412 = 0x000B,

    .field_0414 = 0xD760,

    .field_0416 = 0x0003,

    .field_0418 = 0x0012,

};

#undef SELF
#undef BASE
