/**
 * accomp_section_widget — Screen Layout Data
 *
 * Base address: 0xF6A88D (v7; v9/v10: 0xF6AC91)
 * Size: 15 bytes, 1 commands
 *
 * Auto-generated by screendata_parser.py
 *
 * v7 COPY: identical layout to v9/v10; the RAM variable ids are 0x9C lower
 * (v10 0x39ba -> v7 0x391e) and every ROM address 0x404 lower, which is the
 * whole byte difference between the v7 and v10 AccScreen_UIDataBlock (2,096 B,
 * 66 differing bytes, all of them id low bytes or pointer bytes).  Measured by
 * scripts/converters/lane_accomp_v7_uidatablock.py.
 */

#include "screendata_types.h"
#include <stddef.h>

/* Handler data tables (resolved by linker via accomp_screens_link.ld) */
extern const char Accomp_SectionParam_Names;

#define HANDLER_ADDR(sym) ((uint32_t)&(sym))

typedef struct __attribute__((packed)) {
	sd_widget_t                    widget_0;  /* section parameter names (133,27) */
} screendata_accomp_section_widget_t;

_Static_assert(sizeof(screendata_accomp_section_widget_t) == 15,
	"accomp_section_widget must be exactly 15 bytes");

#define ACCOMP_SECTION_WIDGET_BASE  0x00F6A88Du
#define SD_PTR(field)  (ACCOMP_SECTION_WIDGET_BASE + offsetof(screendata_accomp_section_widget_t, field))

const screendata_accomp_section_widget_t accomp_section_widget
	__attribute__((section(".text"), used)) = {
	.widget_0 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x391e, .flags = 0x0007, .ref_tag = 0x06, .handler = HANDLER_ADDR(Accomp_SectionParam_Names), .param = 20, .x = 133, .y = 27 },
};
