#!/usr/bin/env python3
"""Emit lane promB3's four prom_b spans as real source, and prove the framing.

QUESTION ANSWERED
  What is in prom_b's four remaining `.incbin` spans 0xF0D4D2+454,
  0xF0D7E2+442, 0xF2B422+338 and 0xF2BB0D+523 (1,757 bytes), and what says so?

  All four are display-list DATA, not code.  Nothing in any of the four images
  branches into them; what names them are POINTERS -- the `+7` field of an
  interpreter-B record, a `ld XIY/XIX/XIZ` immediate in prom_a, or an entry of
  a pointer table inside the span itself.  Every object below is typed, and its
  EXTENT is forced by the next named address, not chosen.

  The pointer evidence is regenerated by notes/lane_promB3/xref_scan.py; the
  record framing by --selftest here.

THE FOUR SPANS
  0xF0D4D2 +454  three 8-byte-entry operand tables with the four interpreter-B
                 records that point at them interleaved, a 33-byte ramp, and
                 the first 217 bytes of an 80x24 bitmap that runs 23 bytes past
                 the span's end.
  0xF0D7E2 +442  16 interpreter-A op-07 text records, two 11-entry tables of
                 4-byte pointers INTO those records, and 2 character codes.
  0xF2B422 +338  the tail of a word array, three interpreter-B records, two
                 8-byte-entry tables, a 10-entry pointer table and the five
                 word arrays it points at.
  0xF2BB0D +523  one interpreter-B record and the 64-entry, 8-byte table its
                 own AND mask sizes EXACTLY.

WHY THE 0xF0D698 RECORD IS REWRITTEN TOO
  The bitmap that starts at 0xF0D5BF is 240 bytes and ends at 0xF0D6AF.  The 23
  bytes past this span's end were framed as the operand run of an `op 0C, 28
  bytes` record at 0xF0D698 whose handler (0xF31AEB) is a bare `ret` -- it reads
  nothing, so ANY length "fits" and the framing asserted nothing.  Dropping it
  moves the walk start from +454 to +477 and the first real record becomes the
  `op 23, 5 bytes` glyph record at 0xF0D6AF, which lands on 0xF0D6B4 -- the same
  zero-drift walk, 22 records instead of 23.  gen_prom_b_untouched_pool_module.py
  states this exact hazard about a DIFFERENT span and then admits offset 454
  here because it only required SOME record to be non-weak, not the first.

RUN
  python3 notes/lane_promB3/gen_promB3_spans.py --selftest   # the framing checks
  python3 notes/lane_promB3/gen_promB3_spans.py --render     # the bitmap, as pixels
  python3 notes/lane_promB3/gen_promB3_spans.py --show       # the assembly
  python3 notes/lane_promB3/gen_promB3_spans.py --splice     # into prom_b/wsa1_prom_b.s
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "scripts", "analysis"))
import prom_b_display_lists as DL              # noqa: E402

B_BASE = 0xF00000
ROM = "original_ROMs/wsa1_prom_b.ic13"
S_FILE = "prom_b/wsa1_prom_b.s"

BM_START, BM_COLS, BM_ROWS = 0xF0D5BF, 10, 24   # the bitmap that straddles 0xF0D698
FAIL = []


def rom():
    return open(os.path.join(ROOT, ROM), "rb").read()


def at(b, a, n):
    return b[a - B_BASE:a - B_BASE + n]


def w16(b, a):
    return int.from_bytes(at(b, a, 2), "little")


def w32(b, a):
    return int.from_bytes(at(b, a, 4), "little")


def check(msg, got, want):
    ok = got == want
    print("  %-72s %-22s %s" % (msg, got, "OK" if ok else "FAIL want %s" % (want,)))
    if not ok:
        FAIL.append(msg)


# ---------------------------------------------------------------- emitters --

def b_record(b, p, target_sym):
    """One interpreter-B op 03/08 record, len 11, handler 0xF31B57.

    Field names are FINDINGS-ui-display-list-interpreter-b.md's, and the
    spelling is the one DL_F2B379 in this file already uses."""
    d = at(b, p, 11)
    return ["\t.byte 0x%02X, 0x0B\t; B op %02X, 11 bytes -> handler 0xF31B57 -- four words of entry[value] -> (0x2530..0x2536)\n"
            % (d[0], d[0]),
            "\t.short 0x%04X\t; +0x02 source variable, 16-bit address\n" % (d[2] | d[3] << 8),
            "\t.byte 0x%02X\t; +0x04 AND mask\n" % d[4],
            "\t.byte 0x%02X\t; +0x05 right shift, low 3 bits\n" % d[5],
            "\t.byte 0x%02X\t; +0x06 swi 7 function\n" % d[6],
            "\t.long %s\t; +0x07 -> XIX: array of 8-byte entries, indexed by the value\n" % target_sym]


def table8(b, p, n, label):
    out = ["%s:\n" % label]
    for i in range(n):
        e = at(b, p + i * 8, 8)
        w = [int.from_bytes(e[k * 2:k * 2 + 2], "little") for k in range(4)]
        out.append("\t.short 0x%04X, 0x%04X, 0x%04X, 0x%04X\t; [%d]\n" % (*w, i))
    return out


def byte_rows(b, p, n, per=12, tag=""):
    out = []
    for o in range(0, n, per):
        raw = at(b, p + o, min(per, n - o))
        out.append("\t.byte %s\t; %06X%s\n"
                   % (", ".join("0x%02X" % c for c in raw), p + o, tag))
    return out


# ------------------------------------------------------------------ span 1 --

S1_HEAD = """
; ==================================================================
; 0xF0D4D2-0xF0D697 -- interpreter-B operand tables and their records, a
; 33-byte ramp, and the head of an 80x24 bitmap (454 bytes)
; ==================================================================
;
; ⚠ THE STATED REASON THIS SPAN CARRIED IS OVERTURNED, AND REWRITTEN HERE.
;   It read "decodes as neither interpreter's records and is not a uniform
;   fill".  The first half of that is true and is not the point: the span does
;   not BEGIN with records, so no op/len walk from 0xF0D4D2 can frame it.  Its
;   first byte is the low half of a 16-bit coordinate in the TABLE that the two
;   records immediately IN FRONT of the span point at.  Records and tables then
;   alternate the whole way through:
;
;     0xF0D4D2 +72   9 x 8-byte entries    <- +7 of the records at 0xF0D4BC/0xF0D4C7
;     0xF0D51A +11   B record, op 08       -> 0xF0D530
;     0xF0D525 +11   B record, op 03       -> 0xF0D530
;     0xF0D530 +72   9 x 8-byte entries
;     0xF0D578 +11   B record, op 08       -> 0xF0D58E
;     0xF0D583 +11   B record, op 03       -> 0xF0D58E
;     0xF0D58E +16   2 x 8-byte entries
;     0xF0D59E +33   byte ramp, entry k = k + 1
;     0xF0D5BF +217  the first 217 bytes of a 240-byte bitmap
;
; Evidence for the tables -- POINTERS, not a walk.  Interpreter B's ops 03 and
; 08 both reach handler 0xF31B57, which does `sla 3,HL` before adding the +7
; long: 8-byte entries (notes/FINDINGS-ui-display-list-interpreter-b.md).  Six
; such records name three addresses, and every one of the six pointers sits at
; record+7 exactly -- 0xF0D4C3 and 0xF0D4CE name 0xF0D4D2, 0xF0D521 and
; 0xF0D52C name 0xF0D530, 0xF0D57F and 0xF0D58A name 0xF0D58E
; (notes/lane_promB3/xref_scan.py 0xF0D4D2 0xF0D698).  Each table's EXTENT is
; forced rather than chosen: it runs to the next named address, and 72, 72 and
; 16 are all whole numbers of 8-byte entries.  The entry count the AND mask
; would allow is 256, an upper bound on the INDEX and not a measurement -- the
; extent is the measurement, which is the rule notes/prom_b_dl_operand_tables.py
; states.
;
; ⚠ The two records in front of the span, at 0xF0D4BC and 0xF0D4C7, are printed
;   above with INTERPRETER A's field layout, which puts a 32-bit pointer at +2
;   and reads 0x00FF2720 there.  The +7 reading -- interpreter B's -- reads
;   0x00F0D4D2, which is where this table is.  Both emit the same bytes; only
;   one of them lands on an object.  Left as they are: they are outside this
;   span, and this note is the record of it.
; ==================================================================
"""

S1_RAMP = """
; ------------------------------------------------------------------
; Data_F0D59E -- 33 bytes: entry k = k + 1, for k = 0..32 (0x01..0x21)
; Evidence: the run is bounded below by the 2-entry table above, which ends at
;           0xF0D59D, and above by the bitmap, whose start is fixed by the
;           24-row alignment argument below.  Nothing in any of the four images
;           holds a pointer to 0xF0D59E, so what INDEXES it is not established
;           -- only that it is 33 bytes of monotone byte data and not records.
; ------------------------------------------------------------------
"""

S1_BITMAP = """
; ------------------------------------------------------------------
; Bitmap_F0D5BF_80x24 -- 10 bytes x 24 rows = 240 bytes, COLUMN-MAJOR
; ⚠ IT DOES NOT END INSIDE THIS SPAN.  217 of its 240 bytes are here; the last
;   23 are at 0xF0D698, where they were framed as the operand run of an op-0C
;   record -- see the correction printed there.
; Evidence, in the order that forces the shape:
;   1. swi 7 service 3 (prom_a 0xF8EDB4) is the blitter.  Its outer loop runs BC
;      times, once per DESTINATION COLUMN, and its inner loop reads HL bytes
;      consecutively from XIY (`ld E,(XIY)` / `inc 1,XIY` at 0xF8EE0A) -- so a
;      bitmap is stored column by column, HL bytes per column, BC columns.
;      DrawValueGlyph_24x24 in this file calls it with BC = 3, HL = 24 for the
;      72-byte glyphs at 0xF31EE1, the same arrangement.
;   2. The run must END at 0xF0D6AF: that is the first byte of the `op 23, 5
;      bytes` glyph record whose length lands on 0xF0D6B4, the already-converted
;      "SYSEX BULK DUMP" record.  Two 24-aligned starts below it clear the
;      2-entry table -- 0xF0D5A7 and 0xF0D5BF -- and the lower one falls
;      strictly inside the 0x01..0x21 ramp, which it would have to split.  That
;      leaves 0xF0D5BF, giving exactly 10 columns.
;   3. At that width and only at that width the bytes are a single connected
;      line drawing: the long horizontal rules run unbroken across all ten byte
;      columns and the diagonals advance one pixel per row across every column
;      boundary.  `python3 notes/lane_promB3/gen_promB3_spans.py --render`
;      prints it; one column more or fewer shears it into noise.
;   Nothing holds a pointer to 0xF0D5BF, so WHO draws it is not established.
; ------------------------------------------------------------------
"""


def span1(b):
    out = [S1_HEAD]
    out += table8(b, 0xF0D4D2, 9, "DLTable_F0D4D2")
    out.append("\n")
    out += b_record(b, 0xF0D51A, "DLTable_F0D530")
    out += b_record(b, 0xF0D525, "DLTable_F0D530")
    out.append("\n")
    out += table8(b, 0xF0D530, 9, "DLTable_F0D530")
    out.append("\n")
    out += b_record(b, 0xF0D578, "DLTable_F0D58E")
    out += b_record(b, 0xF0D583, "DLTable_F0D58E")
    out.append("\n")
    out += table8(b, 0xF0D58E, 2, "DLTable_F0D58E")
    out.append(S1_RAMP)
    out.append("Data_F0D59E:\n")
    out += byte_rows(b, 0xF0D59E, 33, 11)
    out.append(S1_BITMAP)
    out.append("Bitmap_F0D5BF_80x24:\n")
    for c in range(BM_COLS):
        p = BM_START + c * BM_ROWS
        n = min(BM_ROWS, 0xF0D698 - p)          # this span stops at 0xF0D697
        if n <= 0:
            break
        out += byte_rows(b, p, n, 12, "  column %d" % c)
    return out


# -- the correction to the neighbouring block, which holds the bitmap's tail --

D698_OLD = ("\t.byte 0x0C, 0x1C\t; op 0C, 28 bytes -> handler 0xF31AEB\n"
            "\t.byte 0x34, 0x24, 0x44, 0xC4, 0x84, 0x84, 0x84, 0x04, 0x04, 0x0C, 0x18, 0x30,"
            " 0x60, 0xC0, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x23, 0x05, 0x1D, 0x07, 0x00"
            "\t; operand bytes the handler does not read\n")

D698_HEAD = """; --- 0xF0D698-0xF0D6AE: the last 23 bytes of Bitmap_F0D5BF_80x24 (see its
;     header above) -- rows 1-23 of its last byte column, column 9, whose row 0
;     is the last byte of the span above.
; ⚠ WAS FRAMED AS `op 0C, 28 bytes -> handler 0xF31AEB`, with 26 "operand bytes
;   the handler does not read".  That is the whole objection: 0xF31AEB is a bare
;   `ret`, so a record on it asserts NOTHING -- any length byte at all would
;   have walked, and this one swallowed the bitmap's tail and the glyph record
;   that follows it.  gen_prom_b_untouched_pool_module.py's own docstring
;   excludes a different span for exactly this reason; the offset-454 walk it
;   chose here slipped through because it only required SOME record in the walk
;   to be non-weak, not the FIRST one.  Starting at +477 instead walks the same
;   records minus this one, still landing on 0xF0D79C with zero drift.
;     Rewritten by notes/lane_promB3/gen_promB3_spans.py --splice.
"""


def d698_fix(b):
    out = [D698_HEAD]
    out += byte_rows(b, 0xF0D698, 23, 12, "  bitmap tail")
    out.append("\t.byte 0x23, 0x05\t; op 23, 5 bytes -> handler 0xF31ACE\n")
    out.append("\t.byte 0x%02X\t; +0x02 glyph index\n" % at(b, 0xF0D6B1, 1)[0])
    out.append("\t.short 0x%04X\t; +0x03 -> IX\n" % w16(b, 0xF0D6B2))
    return out


# ------------------------------------------------------------------ span 2 --

S2_HEAD = """
; ==================================================================
; 0xF0D7E2-0xF0D99B -- the bulk-dump progress lines, the two tables that pick
; one of them, and two loose character codes (442 bytes)
; ==================================================================
;
;   0xF0D7E2 +352  16 interpreter-A records, all op 07 (handler 0xF31A3A)
;   0xF0D942 +44   11 x 4-byte pointers into those records
;   0xF0D96E +44   11 x 4-byte pointers into those records
;   0xF0D99A +2    two character codes, one per row, for swi 7 service 7
;
; Evidence:
;   * prom_a 0xF99C61 `ld XIY,0x00F0D7E2` / `ld XIX,0x00F0D82E` (or 0x00F0D81B
;     at 0xF99C71) / `call 0xF417F0` -- interpreter A.  Walking the length bytes
;     from 0xF0D7E2 lands with zero drift on 0xF0D942, the first byte of the
;     first pointer table; 12 of the 16 record starts are also named directly by
;     that table.
;   * prom_a 0xF99BDB `ld XIY,0x00F0D942` and 0xF99CFA `ld XIY,0x00F0D96E`, both
;     falling into 0xF99C5C, which does `sla 0x02,HL` / `ld IY,(XIY+HL)` /
;     `call 0xF4182C` -- 4-byte entries indexed by a flag byte the same routine
;     compares against 7 and 8.  Each table's extent is forced by the next named
;     address: 0xF0D942 + 11*4 = 0xF0D96E, and 0xF0D96E + 11*4 = 0xF0D99A.
;     Entry [0] of each is 0, and the other 20 are all record starts above.
;   * prom_a 0xF99C1F and 0xF99C49 `ld XIY,0x00F0D99A` with BC = 1 and HL = 0 or
;     1, then `ld A,7` / `swi 7`.  Service 7 (prom_a 0xF8F130) reads
;     `(XIY + HL*BC + i)` for i in 0..BC-1 and uses each byte x 16 as an index
;     into the 16-byte glyph font at 0xF1BEF0: XIY is a character array of BC
;     per row and HL is the row.  Two rows of one byte is exactly the 2 bytes
;     the tables leave.
; ==================================================================
"""


def span2(b):
    htab = [int.from_bytes(b[DL.HTBL + i * 4:DL.HTBL + i * 4 + 4], "little") for i in range(36)]
    recs = DL.walk(b, 0xF0D7E2, 0xF0D942)
    starts = {p for p, _op, _ln in recs}
    out = [S2_HEAD]
    out += DL.render(b, recs, htab, starts)
    for tbl, row in ((0xF0D942, 0), (0xF0D96E, 1)):
        out.append("\n; ------------------------------------------------------------------\n")
        out.append("; DLPtrTable_%06X -- 11 entries of 4 bytes, row %d\n" % (tbl, row))
        out.append("; Evidence: prom_a %s `ld XIY,0x00%06X` reaches 0xF99C5C's\n"
                   ";           `sla 0x02,HL` / `ld IY,(XIY+HL)`; the extent runs to the\n"
                   ";           next address prom_a names.\n"
                   % ("0xF99BDB" if row == 0 else "0xF99CFA", tbl))
        out.append("; ------------------------------------------------------------------\n")
        out.append("DLPtrTable_%06X:\n" % tbl)
        for i in range(11):
            v = w32(b, tbl + i * 4)
            out.append("\t.long %s\t; [%d]\n"
                       % ("DL_%06X" % v if v in starts else "0x%08X" % v, i))
    out.append("\n; ------------------------------------------------------------------\n")
    out.append("; Chars_F0D99A -- 2 rows of 1 character, drawn by swi 7 service 7\n")
    out.append("; Evidence: prom_a 0xF99C1F (HL = 0) and 0xF99C49 (HL = 1), both with\n"
               ";           BC = 1 and XIY = 0x00F0D99A.\n")
    out.append("; ------------------------------------------------------------------\n")
    out.append("Chars_F0D99A:\n")
    for i in range(2):
        c = at(b, 0xF0D99A + i, 1)[0]
        out.append("\t.byte 0x%02X\t; row %d%s\n"
                   % (c, i, "  '%s'" % chr(c) if 0x20 <= c <= 0x7E else ""))
    return out


# ------------------------------------------------------------------ span 3 --

S3_HEAD = """
; ==================================================================
; 0xF2B422-0xF2B573 -- the tail of a word array, three interpreter-B records,
; two operand tables, a pointer table and the five arrays it names (338 bytes)
; ==================================================================
;
;   0xF2B422 +13   the last 13 bytes of the 16-byte word array at 0xF2B41F
;   0xF2B42F +11   B record, op 03       -> 0xF2B445
;   0xF2B43A +11   B record, op 03       -> 0xF2B445
;   0xF2B445 +128  16 x 8-byte entries
;   0xF2B4C5 +11   B record, op 03       -> 0xF2B4D0
;   0xF2B4D0 +64   8 x 8-byte entries
;   0xF2B510 +40   10 x 4-byte pointers  -> the five arrays below
;   0xF2B538 +60   five word arrays of 2, 4, 6, 8 and 10 entries
;
; Evidence:
;   * The three record starts are named by prom_a as single records, not lists:
;     0xF928C3 `ld XIY,0x00F2B42F` / `call 0xF41820`, 0xF928CC
;     `ld XIY,0x00F2B43A` / `call 0xF4181C`, and 0xF933D4 / 0xF93433 / 0xF93E64 /
;     0xF93EC3 `ld XIY,0x00F2B4C5`.  Their +7 longs land on 0xF2B445 and
;     0xF2B4D0, and handler 0xF31B57's `sla 3,HL` makes those 8-byte entries;
;     128 and 64 are whole numbers of them, each running to the next named
;     address.
;   * 0xF2B510: prom_a 0xF934CB and 0xF93EF0 `ld XIZ,0x00F2B510` immediately
;     after `sla 0x02,HL`, then `ld XIZ,(XIZ+HL)` -- 4-byte entries.  All ten
;     hold one of five addresses, and those five tile 0xF2B538-0xF2B573 with no
;     slack, ending exactly on 0xF2B574, a proven interpreter-A list start.
;   * ⚠ THE SPAN OPENS MID-OBJECT.  0xF2B41F-0xF2B42E is eight 16-bit values in
;     arithmetic progression, step 0x320: 0x05B7 0x08D7 0x0BF7 0x0F17 0x1237
;     0x1557 0x1877 0x1B97.  Its first three bytes are the last `.byte` row of
;     Data_F2B38F above, whose own header says its extent is the reachability
;     walk's and not the object's -- this is that seam.  The array is the twin
;     of the one at 0xF2B40F, same eight elements and same 0x320 step, starting
;     0x05A3 instead of 0x05B7.  Only its last 13 bytes can be typed here.
; ==================================================================
"""


def span3(b):
    out = [S3_HEAD]
    out.append("\t.byte 0x%02X\t; F2B422  high half of 0x08D7, the 2nd element of the array at 0xF2B41F\n"
               % at(b, 0xF2B422, 1)[0])
    out.append("\t.short %s\t; F2B423  elements 3-8, step 0x320\n"
               % ", ".join("0x%04X" % w16(b, 0xF2B423 + i * 2) for i in range(6)))
    out.append("\n")
    out += b_record(b, 0xF2B42F, "DLTable_F2B445")
    out += b_record(b, 0xF2B43A, "DLTable_F2B445")
    out.append("\n")
    out += table8(b, 0xF2B445, 16, "DLTable_F2B445")
    out.append("\n")
    out += b_record(b, 0xF2B4C5, "DLTable_F2B4D0")
    out.append("\n")
    out += table8(b, 0xF2B4D0, 8, "DLTable_F2B4D0")
    out.append("\n; ------------------------------------------------------------------\n")
    out.append("; DLPtrTable_F2B510 -- 10 entries of 4 bytes\n")
    out.append("; Evidence: prom_a 0xF934CB / 0xF93EF0 `ld XIZ,0x00F2B510` after\n"
               ";           `sla 0x02,HL`, then `ld XIZ,(XIZ+HL)`.  The extent ends where\n"
               ";           its own lowest target begins.\n")
    out.append("; ------------------------------------------------------------------\n")
    out.append("DLPtrTable_F2B510:\n")
    for i in range(10):
        out.append("\t.long WordArray_%06X\t; [%d]\n" % (w32(b, 0xF2B510 + i * 4), i))
    out.append("\n; ------------------------------------------------------------------\n")
    out.append("; The five arrays DLPtrTable_F2B510 names, 2/4/6/8/10 16-bit values.  Each\n"
               "; is two halves of n/2: the first half starts 0x05A3 and the second 0x05B5,\n"
               "; both stepping 0x618, with the last array repeating its final value in each\n"
               "; half.  They tile 0xF2B538-0xF2B573 exactly.\n")
    out.append("; ------------------------------------------------------------------\n")
    for a, n in ((0xF2B538, 2), (0xF2B53C, 4), (0xF2B544, 6), (0xF2B550, 8), (0xF2B560, 10)):
        out.append("WordArray_%06X:\n" % a)
        out.append("\t.short %s\n" % ", ".join("0x%04X" % w16(b, a + i * 2) for i in range(n)))
    return out


# ------------------------------------------------------------------ span 4 --

S4_HEAD = """
; ==================================================================
; 0xF2BB0D-0xF2BD17 -- one interpreter-B record and the 64-entry operand table
; its own AND mask sizes exactly (523 bytes)
; ==================================================================
;
;   0xF2BB0D +11   B record, op 03, mask 0x3F -> 0xF2BB18
;   0xF2BB18 +512  64 x 8-byte entries
;
; Evidence: prom_a names 0xF2BB0D six times -- 0xF92A06 and 0xF92A36
;           `ld XIY,0x00F2BB0D` / `call 0xF4181C` run it as a single record, and
;           0xF929D1, 0xF929F8, 0xF92A2D, 0xF92A4A use it as the XIX end of the
;           list that starts at the already-converted DL_F2BB03.  Its +7 long is
;           0xF2BB18 and handler 0xF31B57's `sla 3,HL` makes 8-byte entries.
;           The size is EXACT rather than tiled, which is the strong case in
;           notes/prom_b_dl_operand_tables.py: mask 0x3F with shift 0 allows
;           (0x3F >> 0) + 1 = 64 indices, 64 x 8 = 512, and 0xF2BB18 + 512 =
;           0xF2BD18, the first byte of the proven interpreter-A list DL_Usr1.
;           The implied count and the measured extent agree with no slack.
; ==================================================================
"""


def span4(b):
    out = [S4_HEAD]
    out += b_record(b, 0xF2BB0D, "DLTable_F2BB18")
    out.append("\n")
    out += table8(b, 0xF2BB18, 64, "DLTable_F2BB18")
    return out


# ------------------------------------------------------------------- splice --

EDITS = [
    ("; --- 0xF0D4D2-0xF0D697: not converted -- decodes as neither interpreter's records "
     "and is not a uniform fill ---\n"
     '\t.incbin "original_ROMs/wsa1_prom_b.ic13", 0x00D4D2, 0x0001C6\n', span1),
    ('; --- 0xF0D7E2-0xF0D99B: not converted ---\n'
     '\t.incbin "original_ROMs/wsa1_prom_b.ic13", 0x00D7E2, 0x0001BA\n', span2),
    ('\t.incbin "original_ROMs/wsa1_prom_b.ic13", 0x02B422, 0x000152\n', span3),
    ('; --- 0xF2BB0D-0xF2BD17: not converted ---\n'
     '\t.incbin "original_ROMs/wsa1_prom_b.ic13", 0x02BB0D, 0x00020B\n', span4),
]

# The pool module's header for the block that holds the bitmap's tail.  Only the
# two numbers the correction moves are changed; the prose is kept.
HDR_OLD = ("; 0xF0D698-0xF0D79B -- 23 display-list records, 260 bytes -- interpreter A\n")
HDR_NEW = ("; 0xF0D6AF-0xF0D79B -- 22 display-list records, 237 bytes -- interpreter A\n")
# The pool module's header for the block that holds the bitmap's tail.  The
# whole paragraph is matched at once (it is unique) and rewritten so the two
# numbers the correction moves change IN PLACE and the original wording of the
# rest survives verbatim, with the correction appended after it.
HDR_OLD = (
    "; 0xF0D698-0xF0D79B -- 23 display-list records, 260 bytes -- interpreter A\n"
    "; NOT reached by any known call shape (reachability.py: prom_b has 0\n"
    "; bytes with start evidence) and not named by any converted record's\n"
    "; own table field either -- found because a plain op/len walk, starting\n"
    "; 454 bytes into this span, lands with ZERO DRIFT exactly on the span's\n"
    "; declared end, and every record's length satisfies ITS OWN handler's\n"
    "; implied-length rule (notes/prom_b_dl_length_audit.py), not merely\n"
    "; `op < bound`.  Regenerate: python3 notes/gen_prom_b_untouched_pool_module.py\n"
    "; --splice\n")
HDR_NEW = (
    "; 0xF0D6AF-0xF0D79B -- 22 display-list records, 237 bytes -- interpreter A\n"
    "; NOT reached by any known call shape (reachability.py: prom_b has 0\n"
    "; bytes with start evidence) and not named by any converted record's\n"
    "; own table field either -- found because a plain op/len walk, starting\n"
    "; 477 bytes into this span, lands with ZERO DRIFT exactly on the span's\n"
    "; declared end, and every record's length satisfies ITS OWN handler's\n"
    "; implied-length rule (notes/prom_b_dl_length_audit.py), not merely\n"
    "; `op < bound`.  Regenerate: python3 notes/gen_prom_b_untouched_pool_module.py\n"
    "; --splice\n"
    "; ⚠ IT SAID 454 BYTES AND 23 RECORDS UNTIL 2026-09-02.  The record that walk\n"
    ";   began with -- `op 0C, 28 bytes` at 0xF0D698 -- was the last 23 bytes of\n"
    ";   Bitmap_F0D5BF_80x24 plus the `op 23, 5 bytes` glyph record at 0xF0D6AF.\n"
    ";   op 0C's handler, 0xF31AEB, is a bare `ret`: its length byte asserted\n"
    ";   NOTHING, any value at all would have walked, and the per-handler rule\n"
    ";   that rejects this module's other false positives is vacuous on it.\n"
    ";   Starting at +477 walks the same stream minus that one record, still\n"
    ";   landing on 0xF0D79C with zero drift.  Corrected by\n"
    ";   notes/lane_promB3/gen_promB3_spans.py --splice.\n")


def render_bitmap(b):
    print("Bitmap_F0D5BF_80x24 -- %d columns x %d rows, column-major" % (BM_COLS, BM_ROWS))
    for r in range(BM_ROWS):
        line = ""
        for c in range(BM_COLS):
            v = at(b, BM_START + c * BM_ROWS + r, 1)[0]
            line += "".join("#" if (v >> (7 - i)) & 1 else "." for i in range(8))
        print("  %2d %s" % (r, line))


def main():
    b = rom()

    if "--render" in sys.argv:
        render_bitmap(b)
        return 0

    if "--selftest" in sys.argv:
        print("gen_promB3_spans.py --selftest")
        # span 1: the six +7 pointers, and the extents they force
        for rec, tgt in ((0xF0D4BC, 0xF0D4D2), (0xF0D4C7, 0xF0D4D2),
                         (0xF0D51A, 0xF0D530), (0xF0D525, 0xF0D530),
                         (0xF0D578, 0xF0D58E), (0xF0D583, 0xF0D58E),
                         (0xF2B42F, 0xF2B445), (0xF2B43A, 0xF2B445),
                         (0xF2B4C5, 0xF2B4D0), (0xF2BB0D, 0xF2BB18)):
            d = at(b, rec, 11)
            check("0x%06X is op 03/08 len 11" % rec, (d[0] in (3, 8), d[1]), (True, 11))
            check("0x%06X +7 long" % rec, "0x%06X" % w32(b, rec + 7), "0x%06X" % tgt)
        for tbl, nxt in ((0xF0D4D2, 0xF0D51A), (0xF0D530, 0xF0D578), (0xF0D58E, 0xF0D59E),
                         (0xF2B445, 0xF2B4C5), (0xF2B4D0, 0xF2B510), (0xF2BB18, 0xF2BD18)):
            check("table 0x%06X extent is a whole number of 8-byte entries" % tbl,
                  (nxt - tbl) % 8, 0)
        # span 4 only: the mask-implied count EQUALS the extent
        d = at(b, 0xF2BB0D, 11)
        check("0xF2BB0D mask/shift imply exactly the extent",
              ((d[4] >> (d[5] & 7)) + 1) * 8, 0xF2BD18 - 0xF2BB18)
        # span 1: the ramp
        check("0xF0D59E is the ramp 0x01..0x21",
              list(at(b, 0xF0D59E, 33)), list(range(1, 34)))
        # span 1: the bitmap's alignment and its end
        check("bitmap 0xF0D5BF + 10*24 ends at the op-23 record",
              "0x%06X" % (BM_START + BM_COLS * BM_ROWS), "0x%06X" % 0xF0D6AF)
        check("0xF0D6AF is op 23 len 5 (handler 0xF31ACE, implied 5)",
              tuple(at(b, 0xF0D6AF, 2)), (0x23, 0x05))
        check("and it lands on the converted record at 0xF0D6B4",
              "0x%06X" % (0xF0D6AF + 5), "0x%06X" % 0xF0D6B4)
        cand = [a for a in range(0xF0D59E, 0xF0D5C0) if (0xF0D6AF - a) % 24 == 0]
        check("only two 24-aligned starts clear the 2-entry table",
              ["0x%06X" % a for a in cand], ["0x%06X" % 0xF0D5A7, "0x%06X" % 0xF0D5BF])
        check("the lower one, 0xF0D5A7, falls strictly inside the 0x01..0x21 ramp",
              0xF0D59E < 0xF0D5A7 < 0xF0D59E + 33, True)
        # span 2: the walk, the pointer tables, the two characters
        recs = DL.walk(b, 0xF0D7E2, 0xF0D942)
        check("0xF0D7E2 walks to 0xF0D942 with zero drift", recs is not None, True)
        check("all 16 records are op 07", sorted({op for _p, op, _l in recs}), [7])
        starts = {p for p, _o, _l in recs}
        for tbl in (0xF0D942, 0xF0D96E):
            vals = [w32(b, tbl + i * 4) for i in range(11)]
            check("0x%06X entry [0] is 0" % tbl, vals[0], 0)
            check("0x%06X entries 1-10 are all record starts" % tbl,
                  sorted({v in starts for v in vals[1:]}), [True])
        check("the two tables end exactly on Chars_F0D99A",
              "0x%06X" % (0xF0D942 + 22 * 4), "0x%06X" % 0xF0D99A)
        check("Chars_F0D99A leaves 0 bytes before DL_F0D99C",
              0xF0D99C - (0xF0D99A + 2), 0)
        # span 3: the word array seam, the pointer table, the five arrays
        arr = [w16(b, 0xF2B41F + i * 2) for i in range(8)]
        check("0xF2B41F is 8 words stepping 0x320",
              sorted({arr[i + 1] - arr[i] for i in range(7)}), [0x320])
        ptrs = [w32(b, 0xF2B510 + i * 4) for i in range(10)]
        check("DLPtrTable_F2B510 holds 5 distinct targets",
              ["0x%06X" % v for v in sorted(set(ptrs))],
              ["0x%06X" % v for v in (0xF2B538, 0xF2B53C, 0xF2B544, 0xF2B550, 0xF2B560)])
        tg = sorted(set(ptrs)) + [0xF2B574]
        check("the five arrays tile 0xF2B538-0xF2B573 with no slack",
              [tg[i + 1] - tg[i] for i in range(5)], [4, 8, 12, 16, 20])
        # every span's pieces add up to the span
        for s, e, parts in ((0xF0D4D2, 0xF0D698, [72, 11, 11, 72, 11, 11, 16, 33, 217]),
                            (0xF0D7E2, 0xF0D99C, [352, 44, 44, 2]),
                            (0xF2B422, 0xF2B574, [13, 11, 11, 128, 11, 64, 40, 60]),
                            (0xF2BB0D, 0xF2BD18, [11, 512])):
            check("0x%06X pieces sum to the span" % s, sum(parts), e - s)
        print("FAILURES: %d" % len(FAIL))
        return 1 if FAIL else 0

    if "--show" in sys.argv:
        for _old, fn in EDITS:
            sys.stdout.write("".join(fn(b)))
        sys.stdout.write("".join(d698_fix(b)))
        return 0

    if "--splice" in sys.argv:
        path = os.path.join(ROOT, S_FILE)
        cur = open(path, "rb").read()                 # bytes: these sources are latin-1
        before = len(cur)
        for old, fn in EDITS:
            o = old.encode("utf-8")
            if cur.count(o) != 1:
                raise SystemExit("expected exactly one %r, found %d" % (old[:60], cur.count(o)))
            cur = cur.replace(o, "".join(fn(b)).encode("utf-8"), 1)
        for old, new in ((D698_OLD, "".join(d698_fix(b))), (HDR_OLD, HDR_NEW)):
            o = old.encode("utf-8")
            if cur.count(o) != 1:
                raise SystemExit("expected exactly one %r, found %d" % (old[:60], cur.count(o)))
            cur = cur.replace(o, new.encode("utf-8"), 1)
        tmp = path + ".tmp%d" % os.getpid()
        open(tmp, "wb").write(cur)
        os.replace(tmp, path)
        print("spliced 4 spans (1,757 bytes) + the 0xF0D698 correction; %d -> %d bytes"
              % (before, len(cur)))
        return 0

    print("pass --selftest, --render, --show or --splice")
    return 1


if __name__ == "__main__":
    sys.exit(main())
