/**
 * se_setup_ctrl_full — Screen Layout Data
 *
 * Base address: 0xF14809
 * Size: 167 bytes, 21 commands
 *
 * Auto-generated by screendata_parser.py
 */

#include "screendata_types.h"
#include <stddef.h>

/* Entry points into this block:
 *   se_setup_ctrl_full: offset 0 (0xF14809, 167 bytes)
 *   se_setup_ctrl_sub: offset 47 (0xF14838, 120 bytes)
 */

typedef struct __attribute__((packed)) {
	SD_UNKNOWN_TYPE(14)            field_label_0;  /* "rC0NTR0LLER" */
	SD_UNKNOWN_TYPE(14)            param_label_0;  /* "SOUND EDIT" */
	sd_rect_t                      rect_0;  /* (4,4)-(68,16) */
	SD_UNKNOWN_TYPE(3)             unknown_23_0;
	SD_UNKNOWN_TYPE(3)             unknown_23_1;
	SD_SHORT_REF_TYPE(4)           short_ref_0;
	SD_SHORT_REF_TYPE(3)           short_ref_1;
	SD_SHORT_REF_TYPE(3)           short_ref_2;
	SD_SHORT_REF_TYPE(4)           short_ref_3;
	SD_SHORT_REF_TYPE(3)           short_ref_4;
	SD_SHORT_REF_TYPE(3)           short_ref_5;
	SD_UNKNOWN_TYPE(9)             param_label_1;  /* "AFTER" */
	SD_UNKNOWN_TYPE(9)             param_label_2;  /* ".TOUCH" */
	SD_LABELED_REF_TYPE(5)         labeled_ref_0;  /* "DEPTH" */
	SD_LABELED_REF_TYPE(8)         labeled_ref_1;  /* "FUNCTION" */
	SD_SHORT_REF_TYPE(3)           short_ref_6;
	SD_SHORT_REF_TYPE(3)           short_ref_7;
	SD_SHORT_REF_TYPE(3)           short_ref_8;
	SD_SHORT_REF_TYPE(3)           short_ref_9;
	sd_rect_t                      rect_1;  /* (75,72)-(300,91) */
	sd_rect_t                      rect_2;  /* (75,108)-(300,127) */
} screendata_se_setup_ctrl_full_t;

_Static_assert(sizeof(screendata_se_setup_ctrl_full_t) == 167,
	"se_setup_ctrl_full must be exactly 167 bytes");

#define SE_SETUP_CTRL_FULL_BASE  0x00F14809u
#define SD_PTR(field)  (SE_SETUP_CTRL_FULL_BASE + offsetof(screendata_se_setup_ctrl_full_t, field))

const screendata_se_setup_ctrl_full_t se_setup_ctrl_full
	__attribute__((section(".text"), used)) = {
	.field_label_0 = { .opcode = 0x1c, .length = 0x10, .data = { 0x72, 0x00, 0x05, 0x00, 0x43, 0x30, 0x4e, 0x54, 0x52, 0x30, 0x4c, 0x4c, 0x45, 0x52 } },
	.param_label_0 = { .opcode = 0x17, .length = 0x10, .data = { 0x06, 0x00, 0x07, 0x00, 0x53, 0x4f, 0x55, 0x4e, 0x44, 0x20, 0x45, 0x44, 0x49, 0x54 } },
	.rect_0 = { .opcode = SD_OP_RECT, .length = 0x0a, .top_left = { .x = 4, .y = 4 }, .bottom_right = { .x = 68, .y = 16 } },
	.unknown_23_0 = { .opcode = 0x23, .length = 0x05, .data = { 0x5f, 0x83, 0x00 } },
	.unknown_23_1 = { .opcode = 0x23, .length = 0x05, .data = { 0x5f, 0x83, 0x00 } },
	.short_ref_0 = { .opcode = SD_OP_SHORT_REF, .length = 6, .data = { 0x1f, 0x0b, 0x5f, 0x5f } },
	.short_ref_1 = { .opcode = SD_OP_SHORT_REF, .length = 5, .data = { 0x68, 0x0b, 0x10 } },
	.short_ref_2 = { .opcode = SD_OP_SHORT_REF, .length = 5, .data = { 0x8f, 0x0b, 0x11 } },
	.short_ref_3 = { .opcode = SD_OP_SHORT_REF, .length = 6, .data = { 0xbf, 0x10, 0x5f, 0x5f } },
	.short_ref_4 = { .opcode = SD_OP_SHORT_REF, .length = 5, .data = { 0xa8, 0x11, 0x10 } },
	.short_ref_5 = { .opcode = SD_OP_SHORT_REF, .length = 5, .data = { 0xcf, 0x11, 0x11 } },
	.param_label_1 = { .opcode = 0x17, .length = 0x0b, .data = { 0x0a, 0x00, 0x86, 0x00, 0x41, 0x46, 0x54, 0x45, 0x52 } },
	.param_label_2 = { .opcode = 0x17, .length = 0x0b, .data = { 0x2e, 0x00, 0x86, 0x00, 0x54, 0x4f, 0x55, 0x43, 0x48 } },
	.labeled_ref_0 = { .opcode = SD_OP_LABELED_REF, .length = 9, .addr = 0x2067, .label = { 'D', 'E', 'P', 'T', 'H' } },
	.labeled_ref_1 = { .opcode = SD_OP_LABELED_REF, .length = 12, .addr = 0x214b, .label = { 'F', 'U', 'N', 'C', 'T', 'I', 'O', 'N' } },
	.short_ref_6 = { .opcode = SD_OP_SHORT_REF, .length = 5, .data = { 0x1e, 0x24, 0x12 } },
	.short_ref_7 = { .opcode = SD_OP_SHORT_REF, .length = 5, .data = { 0x51, 0x24, 0x12 } },
	.short_ref_8 = { .opcode = SD_OP_SHORT_REF, .length = 5, .data = { 0x57, 0x24, 0x12 } },
	.short_ref_9 = { .opcode = SD_OP_SHORT_REF, .length = 5, .data = { 0x5c, 0x24, 0x12 } },
	.rect_1 = { .opcode = SD_OP_RECT, .length = 0x0a, .top_left = { .x = 75, .y = 72 }, .bottom_right = { .x = 300, .y = 91 } },
	.rect_2 = { .opcode = SD_OP_RECT, .length = 0x0a, .top_left = { .x = 75, .y = 108 }, .bottom_right = { .x = 300, .y = 127 } },
};
