/**
 * se_setup_sel1 — Screen Layout Data
 *
 * Base address: 0xF12B49
 * Size: 10 bytes, 1 commands
 *
 * Auto-generated by screendata_parser.py
 */

#include "screendata_types.h"
#include <stddef.h>

typedef struct __attribute__((packed)) {
	sd_boundary_block_t            boundary_0;  /* (13,73)-(307,197) */
} screendata_se_setup_sel1_t;

_Static_assert(sizeof(screendata_se_setup_sel1_t) == 10,
	"se_setup_sel1 must be exactly 10 bytes");

#define SE_SETUP_SEL1_BASE  0x00F12B49u
#define SD_PTR(field)  (SE_SETUP_SEL1_BASE + offsetof(screendata_se_setup_sel1_t, field))

const screendata_se_setup_sel1_t se_setup_sel1
	__attribute__((section(".text"), used)) = {
	.boundary_0 = { .type = 0x1b, .length = 0x0a, .p1 = { .x = 13, .y = 73 }, .p2 = { .x = 307, .y = 197 } },
};
