/* run_edc2a4.c -- 22 sound-parameter descriptors, ROM 0xEDC2A4-0xEDC430.
 * Generated by scripts/generators/gen_sndparam_records_c.py.
 * Field meanings and their provenance: sndparam_types.h.
 */
#include "sndparam_types.h"

const sndparam_descriptor_t run_edc2a4[22]
    __attribute__((section(".text"), used)) = {
    /* [  0] 0xEDC2A4  MidiChParam_Entry_031 */
    { .key = 0x00002D0B, .bank_index = 0x47, .bank_offset = 0x00,
      .mask = 0x20, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x05, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [  1] 0xEDC2B6  MidiChParam_Entry_032 */
    { .key = 0x00002D0C, .bank_index = 0x47, .bank_offset = 0x06,
      .mask = 0xFF, .clamp_min = 0x00, .clamp_max = 0xFF, .shift = 0x00, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [  2] 0xEDC2C8  MidiChParam_Entry_033 */
    { .key = 0x00002D0D, .bank_index = 0x47, .bank_offset = 0x06,
      .mask = 0x7F, .clamp_min = 0x00, .clamp_max = 0x7F, .shift = 0x00, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [  3] 0xEDC2DA  MidiChParam_Entry_034 */
    { .key = 0x00002D0E, .bank_index = 0x47, .bank_offset = 0x06,
      .mask = 0x80, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x07, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [  4] 0xEDC2EC  MidiChParam_Entry_035 */
    { .key = 0x00002D0F, .bank_index = 0x47, .bank_offset = 0x00,
      .mask = 0x40, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x06, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [  5] 0xEDC2FE  MidiChParam_Entry_036 */
    { .key = 0x00002D10, .bank_index = 0x47, .bank_offset = 0x07,
      .mask = 0xFF, .clamp_min = 0x00, .clamp_max = 0xFF, .shift = 0x00, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [  6] 0xEDC310  MidiChParam_Entry_037 */
    { .key = 0x00002D11, .bank_index = 0x47, .bank_offset = 0x07,
      .mask = 0x7F, .clamp_min = 0x00, .clamp_max = 0x7F, .shift = 0x00, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [  7] 0xEDC322  MidiChParam_Entry_038 */
    { .key = 0x00002D12, .bank_index = 0x47, .bank_offset = 0x07,
      .mask = 0x80, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x07, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [  8] 0xEDC334  MidiChParam_Entry_039 */
    { .key = 0x00002D13, .bank_index = 0x47, .bank_offset = 0x00,
      .mask = 0x80, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x07, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [  9] 0xEDC346  MidiChParam_Entry_040 */
    { .key = 0x00004000, .bank_index = 0xB0, .bank_offset = 0x00,
      .mask = 0x7F, .clamp_min = 0x00, .clamp_max = 0x7F, .shift = 0x00, .xor_value = 0x00,
      .aux_index = 0x01,
      .read_accessor     = 2, /* SndParam_ReadRegWithLUT */
      .register_accessor = 3, /* SndParam_UpdateEntry_Data */
      .lookup2_accessor  = 0, /* SndParam_DeregisterEntry_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 10] 0xEDC358  MidiChParam_Entry_041 */
    { .key = 0x00004001, .bank_index = 0xB0, .bank_offset = 0x01,
      .mask = 0x7F, .clamp_min = 0x00, .clamp_max = 0x7F, .shift = 0x00, .xor_value = 0x00,
      .aux_index = 0x00,
      .read_accessor     = 2, /* SndParam_ReadRegWithLUT */
      .register_accessor = 3, /* SndParam_UpdateEntry_Data */
      .lookup2_accessor  = 0, /* SndParam_DeregisterEntry_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 11] 0xEDC36A  MidiChParam_Entry_042 */
    { .key = 0x00004002, .bank_index = 0x60, .bank_offset = 0x01,
      .mask = 0x80, .clamp_min = 0x00, .clamp_max = 0x7F, .shift = 0x07, .xor_value = 0x00,
      .aux_index = 0x00,
      .read_accessor     = 3, /* SndParam_CompareRegField */
      .register_accessor = 4, /* SndParam_RegisterMultiField_Data */
      .lookup2_accessor  = 3, /* SndParam_RegisterComplex_Data */
      .codec             = 1, /* SndParam_EncodeFieldSub_Data / SndParam_DecodeFieldAlt_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 12] 0xEDC37C  MidiChParam_Entry_043 */
    { .key = 0x00004003, .bank_index = 0x70, .bank_offset = 0x00,
      .mask = 0x04, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x02, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 13] 0xEDC38E  MidiChParam_Entry_044 */
    { .key = 0x00004004, .bank_index = 0x60, .bank_offset = 0x01,
      .mask = 0x40, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x06, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 14] 0xEDC3A0  MidiChParam_Entry_045 */
    { .key = 0x00004005, .bank_index = 0xB0, .bank_offset = 0x03,
      .mask = 0x7F, .clamp_min = 0x00, .clamp_max = 0x7F, .shift = 0x00, .xor_value = 0x00,
      .aux_index = 0x00,
      .read_accessor     = 2, /* SndParam_ReadRegWithLUT */
      .register_accessor = 3, /* SndParam_UpdateEntry_Data */
      .lookup2_accessor  = 0, /* SndParam_DeregisterEntry_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 15] 0xEDC3B2  MidiChParam_Entry_046 */
    { .key = 0x00004006, .bank_index = 0x60, .bank_offset = 0x01,
      .mask = 0x20, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x05, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 16] 0xEDC3C4  MidiChParam_Entry_047 */
    { .key = 0x00004080, .bank_index = 0x98, .bank_offset = 0x02,
      .mask = 0x80, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x07, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 2, /* SndParam_RegisterEntryAlt_Data */
      .lookup2_accessor  = 2, /* SndParam_RegisterChained2_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 17] 0xEDC3D6  MidiChParam_Entry_048 */
    { .key = 0x00004081, .bank_index = 0x98, .bank_offset = 0x02,
      .mask = 0x40, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x06, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 2, /* SndParam_RegisterEntryAlt_Data */
      .lookup2_accessor  = 2, /* SndParam_RegisterChained2_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 18] 0xEDC3E8  MidiChParam_Entry_049 */
    { .key = 0x000040C0, .bank_index = 0x98, .bank_offset = 0x0B,
      .mask = 0x80, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x07, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 19] 0xEDC3FA  MidiChParam_Entry_050 */
    { .key = 0x000040C1, .bank_index = 0x98, .bank_offset = 0x0B,
      .mask = 0x40, .clamp_min = 0x00, .clamp_max = 0x01, .shift = 0x06, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 1, /* SndParam_RegisterChained_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 20] 0xEDC40C  MidiChParam_Entry_051 */
    { .key = 0x000040E0, .bank_index = 0x90, .bank_offset = 0x04,
      .mask = 0xFF, .clamp_min = 0x28, .clamp_max = 0x58, .shift = 0x00, .xor_value = 0x00,
      .aux_index = 0xFF,
      .read_accessor     = 1, /* SndParam_ReadRegField */
      .register_accessor = 1, /* SndParam_RegisterEntry_Data */
      .lookup2_accessor  = 7, /* SndParam_RegisterWide_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
    /* [ 21] 0xEDC41E  MidiChParam_Entry_052 */
    { .key = 0x00004100, .bank_index = 0x90, .bank_offset = 0x00,
      .mask = 0x1F, .clamp_min = 0x00, .clamp_max = 0x05, .shift = 0x00, .xor_value = 0x00,
      .aux_index = 0x00,
      .read_accessor     = 4, /* SndParam_ReadRegWord */
      .register_accessor = 5, /* SndParam_RegisterBitfield_Data */
      .lookup2_accessor  = 4, /* SndParam_NotifyQuick_Data */
      .codec             = 0, /* SndParam_EncodeFieldDirect_Data / SndParam_DecodeField_Data */
      .write_accessor    = 0, /* SndParam_ReturnInvalid */
      .unknown_0x11 = 0xFF },
};
