#!/usr/bin/env python3
r"""Replace NUMERIC CPU-1 ROM-address operands in wsa1/prom_a with the label already AT that address.

QUESTION THIS ANSWERS / JOB IT DOES
    After the branch symboliser, wsa1_prom_a.s still spells thousands of
    CPU-1 ROM addresses (0xF00000-0xFFFFFF) as numbers: `call 0xf417f0` into
    prom_b's routine directory, `.long 0x00fab894` in pointer tables,
    `ld XIY,0x00fe8e31`, `lda xiy, (0xfcb3d3:24)`, `add XBC,0x00fcf000`.
    CLAUDE.md's symbolic-cross-reference policy wants every one of them to be a
    name.  This does ONE conservative thing: where the value is EXACTLY the
    address of a label that already exists, it writes the label.  It creates no
    label and claims nothing beyond what the existing label says.

      * a value in prom_a (0xF80000-0xFFFFFF): the label comes from prom_a's own
        linked ELF; the assembler resolves it, so a wrong choice changes the
        bytes and the gate goes red -- THE BYTE GATE PROTECTS THIS EDIT;
      * a value in prom_b (0xF00000-0xF7FFFF): prom_b is linked separately, so
        prom_a cannot reference its labels.  One GENERATED block of
        `.set <prom_b label>, <address>` equates (between the markers below)
        carries the names.  The gate protects each equate's VALUE (it is in the
        operand's bytes); it does NOT protect the NAME.  `--check-equates`
        re-reads prom_b's ELF and lists every equate whose name no longer
        labels that address: run it after any prom_b rename.  A prom_b name
        that prom_a also defines (the routines both images carry, the kernel,
        the DSP driver) is never used, so an equate cannot collide.
    This is the mirror image of the prom_b lane's
    scripts/converters/symbolize_wsa1_rom_addresses.py (same marker shape, same
    label ranking, same second-decoder guard), written separately because that
    tool edits prom_b only.

WHICH SITES, AND THE GUARD ON CODE
    `.long N`                              data: replaced whenever N is a label address
    `call N` / `jp N` into prom_b          } code: replaced only when MAME unidasm, run
    `ld xRR,N` / `add xRR,N`               } linearly over the dump, sees an instruction
    `lda xRR,(N:24)`                       } START at the line's address whose last
                                             operand is N (the symboliser's R5 rule) --
                                             a phantom instruction made of data bytes
                                             does not get a symbolic operand
    A value that is not exactly a label address (e.g. `add XBC, TABLE - 4*k`)
    stays numeric.  Macro operands are left alone.  `call`/`jp` INTO prom_a are
    left to scripts/converters/symbolize_numeric_branches.py and its guards.

WHICH LABEL, when several share an address: a descriptive name beats a
    structural one (`_Skip`/`_Join`/...), which beats an address-derived one
    (`sub_F12345`, `Data_F12345`); ties go to the name defined first.

RUN
    python3 notes/proma-2026-09-25/symbolize_prom_a_addresses.py                   # dry run
    python3 notes/proma-2026-09-25/symbolize_prom_a_addresses.py --apply
    python3 notes/proma-2026-09-25/symbolize_prom_a_addresses.py --check-equates
    python3 notes/proma-2026-09-25/symbolize_prom_a_addresses.py --arms --offsets [--apply]
      --arms   labels an UNLABELLED instruction start that a .long/ld/lda/add names,
               when unidasm also sees an instruction start there and the bytes are
               not text: sub_<ADDR> when the code before it is a terminator or data
               (a routine start), else .L<ADDR>; an `lda` return point is .L<ADDR>
      --offsets spells a value inside DATA as <nearest data label>+0xN (N <= 0x1000),
               the object plus its offset; a mid-instruction value stays numeric
    make gate-wsa1
"""
import argparse
import collections
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "scripts", "analysis"))
sys.path.insert(0, os.path.join(ROOT, "scripts", "converters"))
import data_range_census as drc                 # noqa: E402
import symbolize_numeric_branches as snb        # noqa: E402

WSA1 = os.path.join(ROOT, "wsa1")
REL = "prom_a/wsa1_prom_a.s"
PATH = os.path.join(WSA1, REL)
BEGIN = ("; >>> BEGIN prom_b ADDRESS EQUATES (generated by "
         "notes/proma-2026-09-25/symbolize_prom_a_addresses.py)")
END = "; <<< END prom_b ADDRESS EQUATES"
ANCHOR = '\t.include "include/tlcs900_mem_ops.inc"'
STRUCT = re.compile(r'_(Skip|Join|Loop|Sub|Return|Epilogue|Entry|Helper)\d*$')
NUM = r'(?P<num>0x[0-9a-fA-F]+|\d+)'
XR = r'x(?:wa|bc|de|hl|ix|iy|iz|sp)'
FORMS = [
    ("long", re.compile(r'^(?P<pre>\.long\s+)' + NUM + r'(?P<post>\s*)$', re.I)),
    ("jp", re.compile(r'^(?P<pre>jp\s+)' + NUM + r'(?P<post>\s*)$', re.I)),
    ("call", re.compile(r'^(?P<pre>call\s+)' + NUM + r'(?P<post>\s*)$', re.I)),
    ("ld", re.compile(r'^(?P<pre>ld\s+' + XR + r'\s*,\s*)' + NUM + r'(?P<post>\s*)$', re.I)),
    ("add", re.compile(r'^(?P<pre>add\s+' + XR + r'\s*,\s*)' + NUM + r'(?P<post>\s*)$', re.I)),
    ("lda", re.compile(r'^(?P<pre>lda\s+' + XR + r'\s*,\s*\(\s*)' + NUM + r'(?P<post>\s*:\s*24\s*\)\s*)$', re.I)),
]
ABSURD = re.compile(r'^(halt|incf|decf|ldf|normal|max|min)\b|^(jr|jrl)\s+[a-z]+\s*,\s*(0x)?0+$'
                    r'|^(jr|jrl)\s+f\s*,')
UNI_MN = {"jp": ("jp",), "call": ("call",), "ld": ("ld",), "add": ("add",), "lda": ("lda",)}


def sh(cmd, **kw):
    r = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if r.returncode != 0:
        sys.exit("FAILED: %s\n%s" % (" ".join(cmd), r.stderr[-3000:]))
    return r.stdout


def elf_labels(elf):
    out = collections.defaultdict(list)
    names = set()
    for ln in sh([drc.NM, "--defined-only", "-n", elf]).split("\n"):
        p = ln.split()
        if len(p) != 3:
            continue
        names.add(p[2])
        if p[1] not in ("t", "T") or p[2].startswith((".L", "__", drc.MARK)):
            continue
        out[int(p[0], 16)].append(p[2])
    return out, names


def rank(name, order):
    if re.search(r'[0-9A-Fa-f]{6}', name):
        r = 3 if name.startswith("sub_") else 2
    elif STRUCT.search(name):
        r = 1
    else:
        r = 0
    return (r, order.get(name, 1 << 30), name)


def split_code(text):
    q, cut = None, len(text)
    for i, ch in enumerate(text):
        if q:
            if ch == q:
                q = None
            continue
        if ch in "\"'":
            q = ch
        elif ch == ";":
            cut = i
            break
    body, tail = text[:cut], text[cut:]
    stripped = body.rstrip()
    tail = body[len(stripped):] + tail
    lead, rest = "", stripped
    while True:
        m = re.match(r'^(\s*[A-Za-z_.$][\w.$@]*:\s*)', rest)
        if not m:
            break
        lead += m.group(1)
        rest = rest[m.end():]
    ws = re.match(r'^\s*', rest).group(0)
    return lead + ws, rest[len(ws):], tail


def block_of(lines):
    """(first, last) line indices of the generated equate block, or None."""
    try:
        s = next(i for i, t in enumerate(lines) if t.startswith(BEGIN))
        e = next(i for i in range(s, len(lines)) if lines[i].startswith(END))
        return s, e
    except StopIteration:
        return None


def analyse(arms=False, offsets=False):
    img = snb.image_by_key("prom_a")
    sh(["make", "-C", WSA1, "rebuilt_ROMs/wsa1_prom_a.llvm.elf", "rebuilt_ROMs/wsa1_prom_b.llvm.elf"])
    a_lab, a_names = elf_labels(os.path.join(WSA1, "rebuilt_ROMs/wsa1_prom_a.llvm.elf"))
    b_lab, _ = elf_labels(os.path.join(WSA1, "rebuilt_ROMs/wsa1_prom_b.llvm.elf"))
    marks, addrs, spans, rom_ok, src, macros = snb.build_map(img, WSA1)
    if not rom_ok:
        sys.exit("prom_a mirror is not byte-identical to the dump -- refusing")
    line_addr = {li: a for (a, end, rel, li) in spans if rel == REL}
    uni = snb.independent_decode(img)
    lines = src.lines(REL)
    order = {}
    for i, t in enumerate(lines):
        m = drc.LABEL_RE.match(t.strip())
        if m and m.group(1) not in order:
            order[m.group(1)] = i
    blk = block_of(lines)
    eq_now = {}
    if blk:
        for t in lines[blk[0]:blk[1] + 1]:
            m = re.match(r'^\s*\.set\s+([\w.$@]+)\s*,\s*(0x[0-9a-fA-F]+)', t)
            if m:
                eq_now[m.group(1)] = int(m.group(2), 16)
    own = a_names - set(eq_now)
    stats = collections.Counter()
    edits, equates = {}, {}
    import bisect
    starts = [sp[0] for sp in spans]
    rom = open(os.path.join(snb.ROOT, img["rom"]), "rb").read()
    new_labels = {}                 # tli -> name  (inserted before line tli)
    lab_addrs = sorted(a for a, ns in a_lab.items() if any(not STRUCT.search(n) for n in ns))

    def src_label_at(tli):
        """a label (any, .L included) written directly above line tli"""
        j = tli - 1
        while j >= 0:
            t = lines[j].strip()
            m = drc.LABEL_RE.match(t)
            if m and not snb.code_of(lines[j]):
                return m.group(1)
            if t and not t.startswith(";"):
                return None
            j -= 1
        return None

    def plan_new(v, kind):
        """--arms / --offsets: a name for an unlabelled prom_a address, or None."""
        k = bisect.bisect_right(starts, v) - 1
        if k < 0 or spans[k][2] != REL:
            return None
        a0, _, _, tli = spans[k]
        bk, _ = drc.classify_line(lines[tli], macros)
        if bk == "code" and a0 == v and arms and kind != "add":
            # (an `add xRR,N` names a TABLE base; one that lands on "code" is
            #  misframe evidence, not a routine -- never labelled here)
            if v not in uni:
                stats["arm_refused_second_decoder"] += 1
                return None
            blob = rom[v - 0xF80000:v - 0xF80000 + 16]
            if sum(0x20 <= c < 0x7F for c in blob) >= 13:
                stats["arm_refused_text"] += 1
                return None
            # R3's rule: no data-as-code marker within 12 statement lines either side
            near, j = [], tli - 1
            while j >= 0 and len(near) < 12:
                c = snb.code_of(lines[j]).lower()
                if c:
                    near.append(c)
                j -= 1
            j = tli
            while j < len(lines) and len(near) < 24:
                c = snb.code_of(lines[j]).lower()
                if c:
                    near.append(c)
                j += 1
            if any(ABSURD.match(c) for c in near) or sum(c == "nop" for c in near) >= 2:
                stats["arm_refused_absurd_neighbourhood"] += 1
                return None
            have = src_label_at(tli)
            if have:
                return have
            if tli in new_labels:
                return new_labels[tli]
            prev = None
            for j in range(tli - 1, max(-1, tli - 400), -1):
                bj, _ = drc.classify_line(lines[j], macros)
                if bj in ("data", "fill"):
                    prev = "DATA"
                    break
                if bj == "code":
                    prev = snb.code_of(lines[j]).lower()
                    break
            routine = prev == "DATA" or (prev and re.match(r'^(ret|reti|retd|jp\s+[^,]+$|jr\s+[^,]+$|jrl\s+[^,]+$)', prev))
            name = ("sub_%06X" if (routine and kind != "lda") else ".L%06X") % v
            new_labels[tli] = name
            return name
        if bk in ("data", "fill") and offsets:
            j = bisect.bisect_right(lab_addrs, v) - 1
            if j < 0 or v - lab_addrs[j] > 0x1000:
                return None
            base = lab_addrs[j]
            kb = bisect.bisect_right(starts, base) - 1
            if kb < 0 or spans[kb][2] != REL:
                return None
            bb, _ = drc.classify_line(lines[spans[kb][3]], macros)
            if bb not in ("data", "fill"):
                return None
            nm = sorted([n for n in a_lab[base] if not STRUCT.search(n)], key=lambda n: rank(n, order))[0]
            return nm if base == v else "%s+0x%X" % (nm, v - base)
        return None
    for li, text in enumerate(lines):
        if blk and blk[0] <= li <= blk[1]:
            continue
        lead, code, tail = split_code(text)
        if not code:
            continue
        for kind, rx in FORMS:
            m = rx.match(code)
            if m:
                break
        else:
            continue
        v = int(m.group("num"), 0)
        if not (0xF00000 <= v <= 0xFFFFFF):
            continue
        img_of = "a" if v >= 0xF80000 else "b"
        if img_of == "a" and kind in ("call", "jp"):
            # prom_a-internal branches belong to the branch symboliser and its
            # guards (R1-R6); what it refused stays refused here too
            stats["left_to_branch_symboliser"] += 1
            continue
        stats["candidate_%s_%s" % (kind, img_of)] += 1
        cands = a_lab.get(v, []) if img_of == "a" else [n for n in b_lab.get(v, []) if n not in own]
        made = None
        if not cands and img_of == "a" and (arms or offsets):
            made = plan_new(v, kind)
        if not cands and not made:
            stats["no_label_%s_%s" % (kind, img_of)] += 1
            continue
        if kind != "long":
            a = line_addr.get(li)
            d = uni.get(a) if a is not None else None
            ok = False
            if d and d[0] in UNI_MN[kind]:
                last = d[1].split(",")[-1].strip().strip("()")
                try:
                    ok = int(last, 16) == v
                except ValueError:
                    ok = False
            if not ok:
                stats["refused_second_decoder_%s" % kind] += 1
                continue
        name = made or sorted(cands, key=lambda n: rank(n, order))[0]
        if made:
            stats["made_%s_%s" % ("offset" if "+" in made else "label", kind)] += 1
        if img_of == "b":
            equates[name] = v
        new_code = m.group("pre") + name + m.group("post").rstrip()
        if tail.strip():
            col = len(lead) + len(code) + (len(tail) - len(tail.lstrip()))   # the `;` column
            pad = max(1, col - len(lead) - len(new_code))
            edits[li] = lead + new_code + " " * pad + tail.lstrip()
        else:
            edits[li] = lead + new_code
        stats["replaced_%s_%s" % (kind, img_of)] += 1
    return dict(lines=lines, edits=edits, equates=equates, stats=stats, blk=blk, eq_now=eq_now,
                b_lab=b_lab, new_labels=new_labels)


def render_block(equates):
    out = [BEGIN,
           "; prom_b is linked separately: these name the prom_b addresses this file calls or",
           "; points at.  Each name is the label prom_b's own linked ELF defines at that address",
           "; (best non-structural name).  The gate checks every VALUE; `--check-equates`",
           "; checks the NAMES against prom_b after a rename there.  Regenerate, never edit."]
    for n, v in sorted(equates.items(), key=lambda t: (t[1], t[0])):
        out.append("\t.set %-40s 0x%08X" % (n + ",", v))
    out.append(END)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--check-equates", action="store_true")
    ap.add_argument("--arms", action="store_true",
                    help="also LABEL unlabelled instruction starts that a .long/ld/lda/add names "
                         "(unidasm must see an instruction start there; sub_<ADDR> after a "
                         "terminator or data, else .L<ADDR>; lda return points are .L)")
    ap.add_argument("--offsets", action="store_true",
                    help="also spell a value inside DATA as <nearest data label>+0xN (N <= 0x1000)")
    a = ap.parse_args()
    res = analyse(a.arms, a.offsets)
    if a.check_equates:
        bad = [(n, v) for n, v in res["eq_now"].items() if n not in res["b_lab"].get(v, [])]
        for n, v in bad:
            print("STALE  %s = 0x%06X  (prom_b now: %s)" % (n, v, res["b_lab"].get(v)))
        print("%d equates, %d stale" % (len(res["eq_now"]), len(bad)))
        sys.exit(1 if bad else 0)
    for k in sorted(res["stats"]):
        print("  %-36s %6d" % (k, res["stats"][k]))
    print("  %-36s %6d" % ("equates", len(res["equates"])))
    if not a.apply:
        return
    lines = list(res["lines"])
    for li, t in res["edits"].items():
        lines[li] = t
    for tli in sorted(res["new_labels"], reverse=True):
        lines[tli:tli] = ["%s:" % res["new_labels"][tli]]
    eq = dict(res["eq_now"])
    eq.update(res["equates"])
    blk = block_of(lines)
    new_blk = render_block(eq)
    if blk:
        lines[blk[0]:blk[1] + 1] = new_blk
    else:
        i = lines.index(ANCHOR)
        lines[i + 1:i + 1] = new_blk
    open(PATH, "wb").write("\n".join(lines).encode("latin-1"))
    print("APPLIED: %d operands, %d equates, %d labels inserted" % (len(res["edits"]), len(eq),
                                                                  len(res["new_labels"])))


if __name__ == "__main__":
    main()
