#!/usr/bin/env python3
r"""data_as_code_census.py -- finish the HD-AE5000 data-as-code census.

QUESTION ANSWERED
    notes/DEBT-INVENTORY-2026-09-02.md records HD-AE5000 as "measured,
    PARTIAL" for the third kind of debt: bytes that are really DATA but are
    written in the source as instruction mnemonics. Two instances were found
    and converted -- the 309 B version string ("Technics Software section
    M. Kitajima") disassembled as ~35 garbage instructions, and
    HDAE5000_RECORD_TABLE at 0x29C0AA, 6,356 B written as ~6,150 lines of
    mnemonics. Neither the `.incbin` coverage tool nor the byte gate can see
    this category: re-assembling a wrong interpretation reproduces the same
    bytes. What ELSE in this image is framed as code but is not?

THE INSTRUMENT IS "WHO READS IT", NOT A DECODER STATISTIC
    HDAE5000_RECORD_TABLE was settled by one argument: every reference to
    0x29C0AA LOADS ITS ADDRESS (`lda_24 xwa, (0x29c0aa)`), and there is no
    call or jump site targeting anything inside it anywhere in the tree. That
    argument depends on no decoder, no framing judgement and no threshold, and
    it cannot be confounded. It is the primary test here.

    ⚠ A byte-statistical instrument was offered for this job and is NOT used:
    the "blind-start enrichment" was RETRACTED on 2026-09-02 (a shuffle of the
    same bytes scored 82.1% against the real 82.8%, and the ratio was
    structurally confounded because a force-disassembled run begins at the
    refused byte by construction). Only a decoder-independent signal, plus a
    coherence metric with a calibrated null, is used below.

WHAT IT DOES, per maximal run of INSTRUCTION lines in hdae5000/*.s
    * CALLED       -- some source `call`/`jp`/`jr`/`jrl`/`calr`/`djnz` resolves
                      to an address INSIDE the run. Settled code; done.
    * ADDR-ONLY    -- nothing branches into it, but something loads an address
                      inside it. This is the RECORD_TABLE signature.
    * UNREFERENCED -- nothing at all names it.
    The last two are then scored by branch-target coherence over unidasm,
    normalised by boundary density, with the threshold CALIBRATED on this
    image's own ground truth: runs that are called (proven code) versus the
    `.incbin` bitmap assets (proven data, regenerated byte-exactly from
    committed PNGs).

⚠ THE NULL. The report prints, for the CALLED population, how many would have
been flagged by the ADDR-ONLY-plus-low-coherence rule if their call evidence
were withheld. That is the rule's false-positive rate against proven code from
the same image. Read it before believing any finding.

⚠ RECALL LIMIT, stated not corrected. A `call (xhl)` or `jp (xiy)` resolves to
nothing statically, so a run reached only through an indirect dispatch will
look UNREFERENCED. That inflates the candidate pool; it cannot manufacture a
confirmed finding, because a finding also has to fail the coherence test.

RUN (from the lane worktree root):
    python3 hdae5000/tools/data_as_code_census.py
    python3 hdae5000/tools/data_as_code_census.py --list 40
"""
import os
import re
import subprocess
import sys
import tempfile
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "scripts/analysis"))
import tier2_byte_split_census as C          # noqa: E402

TAG = "hdae5000"
BASE, LENGTH = 0x280000, 0x80000
MIN_RUN = 24                 # bytes; a shorter island is not a "region"
W_SCORE = None               # runs are scored at their own length
UNI_LINE = re.compile(r'^\s*([0-9a-fA-F]{4,8}):\s+((?:[0-9a-fA-F]{2} )+)\s*(\S+)\s*(.*)$')
FLOW = {"jr", "jrl", "jp", "call", "calr", "djnz"}
TGT = re.compile(r'0x([0-9a-fA-F]+)')
HEXNUM = re.compile(r'\b0x([0-9a-fA-F]{5,6})\b')
DECNUM = re.compile(r'\b(\d{6,8})\b')


def code_regions(amap):
    """[(rel, line, name, start, size)] -- one region per LABEL, running from
    the label to the next label (or to the first data directive after it),
    counting only bytes that are INSTRUCTIONS in the source.

    ⚠ THE GRANULARITY IS THE POINT, and the first version of this tool got it
    wrong. Merging maximal runs of instruction lines gave 15 regions for the
    whole image, one of them 50 KB: a 6,356 B data island inside such a run is
    invisible, because SOMETHING in a 50 KB span is always called. The
    calibration case this census exists to generalise --
    HDAE5000_RECORD_TABLE -- is a LABELLED region, and so is every other
    object the tree names. Labels are therefore the unit.
    """
    out = []
    for rel in C.source_files(TAG):
        lines = open(os.path.join(ROOT, TAG, rel), encoding="latin-1").read().split("\n")
        ad = amap[rel]
        cur = None
        for i in range(1, len(ad) - 1):
            if ad[i] is None or ad[i + 1] is None:
                continue
            txt = lines[i - 1] if i - 1 < len(lines) else ""
            m = C.LABEL_DEF.match(txt)
            if m:
                if cur and cur[4] > 0:
                    out.append(tuple(cur))
                cur = [rel, i, m.group(1), ad[i], 0]
                if not txt.split(":", 1)[1].strip():
                    continue
            sz = ad[i + 1] - ad[i]
            if sz == 0 or cur is None:
                continue
            if C.LINE_DIR.match(txt):
                if cur[4] > 0:
                    out.append(tuple(cur))
                cur = None
                continue
            cur[4] += sz
        if cur and cur[4] > 0:
            out.append(tuple(cur))
    return out


def address_refs():
    """{address: n} for every NON-branch mention of an in-image address in the
    sources -- an immediate or a `.long`/`.word` value."""
    refs = Counter()
    for rel in C.source_files(TAG):
        for line in open(os.path.join(ROOT, TAG, rel), encoding="latin-1"):
            body = line.split(";")[0]
            if C.SRC_XFER.match(body):
                continue
            for m in HEXNUM.finditer(body):
                v = int(m.group(1), 16)
                if BASE <= v < BASE + LENGTH:
                    refs[v] += 1
            for m in DECNUM.finditer(body):
                v = int(m.group(1))
                if BASE <= v < BASE + LENGTH:
                    refs[v] += 1
    return refs


_RAWF = None


def rawfile():
    global _RAWF
    if _RAWF is None:
        with tempfile.NamedTemporaryFile(suffix=".bin", delete=False) as f:
            f.write(C.rom_bytes(TAG))
            _RAWF = f.name
    return _RAWF


def coherence(off, length, min_targets=25):
    out = subprocess.run([C.UNIDASM, rawfile(), "-arch", "tlcs900",
                          "-basepc", hex(BASE + off), "-skip", str(off),
                          "-count", str(length)], capture_output=True, text=True).stdout
    ins = []
    for ln in out.splitlines():
        m = UNI_LINE.match(ln.rstrip())
        if m:
            ins.append((int(m.group(1), 16), len(m.group(2).split()),
                        m.group(3), m.group(4) or ""))
    if not ins:
        return None, 0
    starts = {a for a, _, _, _ in ins}
    nb = sum(n for _, n, _, _ in ins)
    if nb == 0:
        return None, 0
    density = len(ins) / nb
    lo, hi = BASE + off, BASE + off + length
    t = h = 0
    for a, n, mn, op in ins:
        if mn.split(".")[0] not in FLOW:
            continue
        m = TGT.search(op)
        if not m:
            continue
        v = int(m.group(1), 16)
        if not (lo <= v < hi) or v == a or v == a + n:
            continue
        t += 1
        h += v in starts
    if t < min_targets:
        return None, t
    return (h / t) / density, t


def selftest():
    """The two KNOWN instances must fire. A detector that cannot see the cases
    it generalises measures nothing, and the first version of the content test
    could not see either of them."""
    raw = C.rom_bytes(TAG)
    ok = True

    def cov(st, sz):
        d = raw[st - BASE:st + sz - BASE]
        tot = 0
        for _sa, sd, isfill in C.fill_segments(d, st):
            if isfill or C.struct_signal(sd):
                tot += len(sd)
        return tot / float(sz)

    i = raw.find(b"Technics Software")
    cases = [("HDAE5000_RECORD_TABLE 0x29C0AA", 0x29C0AA, 6356)]
    if i >= 0:
        cases.append(("version string region 0x%06X" % (BASE + i - 40),
                      BASE + i - 40, 309))
    for name, st, sz in cases:
        f = cov(st, sz)
        good = f >= 0.25
        ok = ok and good
        print("   [%s] %-36s %5d B  %3.0f%% structured"
              % ("ok" if good else "FAIL", name, sz, 100 * f))
    print("SELFTEST", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def main():
    if "--selftest" in sys.argv:
        return selftest()
    nlist = 0
    if "--list" in sys.argv:
        nlist = int(sys.argv[sys.argv.index("--list") + 1])
    amap = C.build_addrmap(TAG)
    allr = code_regions(amap)
    runs = [r for r in allr if r[4] >= MIN_RUN]
    small = [r for r in allr if r[4] < MIN_RUN]
    tgts = C.entry_targets("HDAE5000")
    refs = address_refs()

    called, addr_only, unref = [], [], []
    for r in runs:
        _rel, _l0, _nm, st, sz = r
        if any(a in tgts for a in range(st, st + sz)):
            called.append(r)
        elif any(a in refs for a in range(st, st + sz)):
            addr_only.append(r)
        else:
            unref.append(r)

    print("=" * 78)
    print("HD-AE5000: %d labelled instruction regions of >= %d B, %d B total"
          % (len(runs), MIN_RUN, sum(r[4] for r in runs)))
    for name, pop in (("CALLED (settled code)", called),
                      ("ADDR-ONLY (the RECORD_TABLE signature)", addr_only),
                      ("UNREFERENCED", unref)):
        print("   %-40s %5d runs %9d B" % (name, len(pop), sum(r[4] for r in pop)))

    print("   NOT EXAMINED: %d regions below %d B, %d B total -- too short for any"
          % (len(small), MIN_RUN, sum(r[4] for r in small)))
    print("   of the tests below to say anything. Stated as a bound, not hidden.")

    print()
    print("CALIBRATION of the coherence metric, on this image's own ground truth")
    code_s = []
    for r in called:
        s, _t = coherence(r[3] - BASE, r[4])
        if s is not None:
            code_s.append(s)
    gen = os.path.join(ROOT, TAG, "includes/generated")
    raw = C.rom_bytes(TAG)
    data_s = []
    if os.path.isdir(gen):
        for fn in sorted(os.listdir(gen)):
            if not fn.endswith(".bin"):
                continue
            blob = open(os.path.join(gen, fn), "rb").read()
            at = raw.find(blob)
            if at < 0 or len(blob) < 0x2000:
                continue
            for o in range(at, at + len(blob) - 0x2000, 0x2000):
                s, _t = coherence(o, 0x2000)
                if s is not None:
                    data_s.append(s)

    def dist(v, n):
        if not v:
            print("   %-34s none scorable" % n)
            return None
        v = sorted(v)
        print("   %-34s n=%4d  min %.2f  med %.2f  max %.2f"
              % (n, len(v), v[0], v[len(v) // 2], v[-1]))
        return v

    cs = dist(code_s, "PROVEN CODE (called runs)")
    ds = dist(data_s, "PROVEN DATA (PNG-derived blobs)")
    if not cs:
        sys.exit("no scorable proven-code runs -- refusing to report a threshold")
    floor = cs[0]
    print("   separation: proven-code min %.2f vs proven-data max %s"
          % (floor, ("%.2f" % ds[-1]) if ds else "n/a"))
    print("   threshold = the lowest-scoring PROVEN-CODE run: %.2f" % floor)

    print()
    print("NULL -- the rule applied to PROVEN CODE with its call evidence withheld")
    fp = 0
    for r in called:
        s, _t = coherence(r[3] - BASE, r[4])
        if s is not None and s < floor:
            fp += 1
    print("   %d of %d scorable called runs would be flagged: %.2f%%"
          % (fp, len(code_s), 100.0 * fp / len(code_s) if code_s else 0.0))
    print("   ⚠ That is the false-positive rate of the coherence half of the")
    print("   rule. A finding must ALSO have no call site anywhere, which is")
    print("   the decoder-independent half.")

    print()
    print("⚠ COHERENCE IS THE WRONG INSTRUMENT AT THIS GRANULARITY, and saying")
    print("   so is the result. A region needs ~25 in-region branch targets to")
    print("   be scorable at all, i.e. several KB; only %d of %d proven-code"
          % (len(code_s), len(called)))
    print("   regions clear that bar. It is kept because when it CAN score it")
    print("   separates perfectly, but it decides almost nothing here.")

    print()
    print("THE TESTS THAT DO WORK ON A SMALL REGION")
    print("   (1) CONTENT. Are the region's bytes a string, a fill, a pointer")
    print("       table or a periodic record array? That is how the 309 B")
    print("       version string was caught. False-positive rate against proven")
    print("       code is measured below, on this image's own called regions.")
    print("   (2) NO EXIT. A routine ends by returning or jumping. A data region")
    print("       framed as code often contains no flow-terminating instruction")
    print("       at all.")
    raw = C.rom_bytes(TAG)

    COVER = 0.25

    def content(r):
        """(kinds, covered_fraction) if structured data covers at least COVER
        of the region, else None.

        ⚠ THE WHOLE-REGION TEST WAS VACUOUS AND THE PLANTED CASES PROVED IT.
        A first version asked `struct_signal` about the region's bytes as one
        span. It returned None for BOTH known instances -- the 309 B version
        string (which is text plus alignment padding, so neither is >=60% of
        the whole) and HDAE5000_RECORD_TABLE (312 B of records, 5,832 B of
        zeros, 212 B of strings, so no single signal owns the span). A
        detector that cannot fire on the two cases it was built to generalise
        measures nothing. Segmenting first -- fills carved out, each remainder
        tested on its own -- puts them at 92% and 71% covered."""
        st, sz = r[3], r[4]
        d = raw[st - BASE:st + sz - BASE]
        tot, kinds = 0, []
        for sa, sd, isfill in C.fill_segments(d, st):
            if isfill:
                tot += len(sd)
                kinds.append("FILL:%d" % len(sd))
            else:
                g = C.struct_signal(sd)
                if g:
                    tot += len(sd)
                    kinds.append("%s:%d" % (g[0], len(sd)))
        frac = tot / float(sz) if sz else 0.0
        return (",".join(kinds[:3]), frac) if frac >= COVER else None

    def no_exit(r):
        rel, l0, _nm, st, sz = r
        ls = open(os.path.join(ROOT, TAG, rel), encoding="latin-1").read().split("\n")
        ad = amap[rel]
        i = l0
        while i < len(ad) - 1 and ad[i] is not None and ad[i] < st + sz:
            t = (ls[i - 1] if i - 1 < len(ls) else "").split(";")[0].strip()
            if C.FLOW_END.match(t) or t.startswith(("ret", "reti", "retd", "jp ")):
                return False
            i += 1
        return True

    fp_c = sum(1 for r in called if content(r))
    fp_x = sum(1 for r in called if no_exit(r))
    print("   NULL on %d PROVEN-CODE regions: content fires %d (%.2f%%), "
          "no-exit fires %d (%.2f%%)"
          % (len(called), fp_c, 100.0 * fp_c / len(called),
             fp_x, 100.0 * fp_x / len(called)))
    both_fp = sum(1 for r in called if content(r) and no_exit(r))
    print("   NULL for BOTH together: %d of %d = %.2f%%"
          % (both_fp, len(called), 100.0 * both_fp / len(called)))

    print()
    print("CANDIDATES -- framed as code, NEVER the target of a call or jump")
    findings = []
    for r in addr_only + unref:
        c = content(r)
        x = no_exit(r)
        s, t = coherence(r[3] - BASE, r[4])
        if c or x or (s is not None and s < floor):
            findings.append((r, c, x, s))
    print("   %d of the %d candidate regions carry a second signal, %d B"
          % (len(findings), len(addr_only) + len(unref),
             sum(f[0][4] for f in findings)))
    strong = [f for f in findings if f[1] and f[2]]
    print("   of which %d carry BOTH content and no-exit, %d B  <- the findings"
          % (len(strong), sum(f[0][4] for f in strong)))
    for r, c, x, sc in sorted(strong, key=lambda f: -f[0][4])[:nlist or 40]:
        rel, l0, nm, st, sz = r
        print("      %-24s %-24s 0x%06X %6d B  %3.0f%% structured  %s"
              % (rel[:24], nm[:24], st, sz, 100 * c[1], c[0][:34]))
    if not strong:
        print("      (none)")
    print()
    print("   the remaining %d single-signal candidates are NOT reported as"
          % (len(findings) - len(strong)))
    print("   findings: one signal at these false-positive rates is not enough.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
