#!/usr/bin/env python3
"""gen_evt_label_names.py -- write rename_evt_number_labels.sed: labels named by a raw event number take its name.

QUESTION IT ANSWERS / WHAT IT DOES
  Some labels carry the firmware event they handle as a number -- AcGridBoxProc_Evt1C00017 is the case of
  AcGridBoxProc's `switch (event - EVT_INDEXSW_UP)` for 0x1C00017, PmemOutLGridCheck_Evt1C0001D_Str_Fmt3d a
  string used on that event's path.  shared/event_codes.s names every such code after the firmware's own
  EV_* table (EVT_INDEXSW_UP = 0x1C00017).  This script maps each `_Evt<hex>` token of every label in the
  v10/v9/v7 sources to `_On<Event>`, the spelling scripts/tools/frame_switch_cases.py uses (EVT_INDEXSW_UP ->
  OnIndexswUp), and writes the rules as a sed file.  A code with no EVT_ name, or a new name that already
  exists, stops the script.

RUN (repository root)
  python3 scripts/renaming/gen_evt_label_names.py            # writes scripts/renaming/rename_evt_number_labels.sed
  then: sed -i -f scripts/renaming/rename_evt_number_labels.sed <files that use the names>; make all
"""
import glob
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TOKEN = re.compile(r'_Evt([0-9A-Fa-f]{6,8})(?=_|$)')


def main():
    ev = {}
    for line in open(os.path.join(REPO, "v10/maincpu/shared/event_codes.s"), "rb").read().decode("latin-1").split("\n"):
        m = re.match(r'\.equ\s+(EVT_\w+),\s*(0x[0-9A-Fa-f]+)', line)
        if m:
            v = int(m.group(2), 16)
            assert v not in ev, (hex(v), ev.get(v), m.group(1))
            ev[v] = m.group(1)
    labels, existing = set(), set()
    for tree in ("v10", "v9", "v7"):
        for p in glob.glob(os.path.join(REPO, tree, "maincpu", "**", "*.s"), recursive=True):
            for line in open(p, "rb").read().decode("latin-1").split("\n"):
                m = re.match(r'^([A-Za-z_]\w*):', line) or re.match(r'^\s*\.set\s+([A-Za-z_]\w*),', line)
                if m:
                    existing.add(m.group(1))
                    if TOKEN.search(m.group(1)):
                        labels.add(m.group(1))
    rules = {}
    for lab in sorted(labels):
        def sub(m):
            v = int(m.group(1), 16)
            if v not in ev:
                sys.exit("no EVT_ name for 0x%X in %s" % (v, lab))
            return "_On" + "".join(w.capitalize() for w in ev[v][4:].split("_"))
        new = TOKEN.sub(sub, lab)
        if new in existing or new in rules.values():
            sys.exit("%s -> %s exists already" % (lab, new))
        rules[lab] = new
    out = os.path.join(REPO, "scripts/renaming/rename_evt_number_labels.sed")
    with open(out, "w") as f:
        f.write("# Labels named by a raw event number take the event's EVT_ name (shared/event_codes.s), as\n"
                "# frame_switch_cases.py spells them: _Evt1C00017 -> _OnIndexswUp.  Generated by gen_evt_label_names.py.\n")
        for a, b in sorted(rules.items(), key=lambda x: -len(x[0])):
            f.write("s/\\b%s\\b/%s/g\n" % (a, b))
    print("%d labels -> %s" % (len(rules), os.path.relpath(out, REPO)))


if __name__ == "__main__":
    main()
