# generated by scripts/renaming/harmonize_version_labels.py: v7 labels renamed to the
# v10 name of the same code (anchor deltas + 12 identical ROM bytes).
s/\bFileIO_ByteBlock_DemoProc1_Helper7_Loop2\b/TmFlashWrite_ValidateParams_Loop2/g
s/\bFileIO_ByteBlock_DemoProc1_Helper7_Join\b/TmFlashWrite_ValidateParams_Join/g
s/\bSeMenu_PresetBrowser_Data_Code_Entry\b/SeMenu_PresetBrowser_Select_Helper_Skip/g
s/\bAccPlayback_AdvanceRingBuffer_Code\b/AccPlayback_AdvanceRingBuffer_Join/g
s/\bSeMenu_PresetManager_Data_Entry2\b/SeMenu_PresetManager_SaveApply_Helper2_Skip2/g
s/\bSeMenu_PresetManager_Data_Join3\b/SeMenu_PresetManager_SaveApply_Helper2_Join2/g
s/\bMssNameFunc_Helper_Skip\b/TmFlash_CompareStrings_Skip/g
