# generated by scripts/renaming/harmonize_version_labels.py: v7 labels renamed to the
# v10 name of the same code (anchor deltas + 12 identical ROM bytes).
s/\bMemConfig_Handler_3_Helper\b/SndDispatch_ProcessCommand_0xF/g
