# generated by scripts/renaming/harmonize_version_labels.py: v7 labels renamed to the
# v10 name of the same code (anchor deltas + 12 identical ROM bytes).
s/\bInitializeNaka_Data\b/Naka_ClassCount_16B/g
