# generated by scripts/renaming/harmonize_version_labels.py: v9 labels renamed to the
# v10 name of the same code (anchor deltas + 12 identical ROM bytes).
s/\bExtData_ToneParam_MultiChannel_Entry\b/ExtData_ToneParam_MultiChannel_Skip11/g
s/\bSeMenu_FilterEdit_DataBlock5_Data\b/SeMenu_FilterEdit_DataBlock5_Data_2/g
s/\bSwbtWr_WriteParamBlock_Epilogue\b/VoiceParam_CompareAndUpdate_Epilogue/g
s/\bSeScreenData_0x114A\b/SeMenu_ShowConfirmDialog_Sub_Data_2/g
s/\bSeScreenData_0x1154\b/SeMenu_ShowConfirmDialog_Sub_Data_3/g
s/\bSeScreenData_0x175E\b/SeMenu_Utility_FormatNumber_Data_2/g
s/\bSeScreenData_0x178B\b/SeMenu_Utility_CompareBlock_Data_2/g
s/\bSeScreenData_0x1901\b/SeMenu_Utility_CompareBlock_Data_3/g
s/\bSeScreenData_0x3563\b/SeMenu_FxEdit_Init_Data_2/g
