#!/usr/bin/env python3
r"""lane_accomp_name_wrappers.py -- give the XIZ-preserving call wrappers of the
accompaniment engine names that say what they wrap.

QUESTION ANSWERED
-----------------
Many `*_Helper<N>` / `*_Sub<N>` labels in accompaniment_engine.s (names the
branch symboliser gave by position, e.g. AccTone_InlineBytecodeData_Code_Helper4)
sit on routines whose ENTIRE body is

    push xiz
    [ld xiy, xwa]  [ld w, a]  [ld xhl, xbc]  [and xwa, 255]  [and xhl, 0xffff]
    call <Target>
    [and xhl, 0xffff]
    pop xiz
    ret

i.e. a thunk that preserves XIZ and moves the caller's argument registers into
the ones <Target> takes.  The tree already names that shape `<Target>_Wrap`
(AccPatch_InitSlotChain_Wrap).  This tool finds every such routine whose label
is structural, and writes a sed script renaming it to `<Target>_Wrap` -- only
when the body matches the shape EXACTLY, the target is symbolic, and the new
name is not already defined anywhere in the image.

RUN
    python3 scripts/renaming/lane_accomp_name_wrappers.py --image v10 \
        --out scripts/renaming/rename_accomp_wrappers_v10.sed
    sed -i -f scripts/renaming/rename_accomp_wrappers_v10.sed v10/maincpu/sequencer/accompaniment_engine.s
"""
import argparse
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
STRUCT = re.compile(r'_(Helper|Sub)\d*$')
ARGMOVE = re.compile(r'^(ld\s+xiy,\s*xwa|ld\s+w,\s*a|ld\s+xhl,\s*xbc|and\s+xwa,\s*(255|0xff)|'
                     r'and\s+xhl,\s*(0xffff|65535))$', re.I)


def code_of(line):
    c = line.split(";")[0].strip()
    return re.sub(r'\s+', ' ', c)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=True)
    ap.add_argument("--file", default="sequencer/accompaniment_engine.s")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    src = os.path.join(ROOT, a.image, "maincpu")
    defined = set()
    for dp, _, fn in os.walk(src):
        for f in fn:
            if f.endswith(".s"):
                for ln in open(os.path.join(dp, f), encoding="latin-1"):
                    m = re.match(r'^([A-Za-z_.$][\w.$@]*):', ln)
                    if m:
                        defined.add(m.group(1))
                    m = re.match(r'^\s*\.set\s+([A-Za-z_.$][\w.$@]*)\s*,', ln)
                    if m:
                        defined.add(m.group(1))
    L = open(os.path.join(src, a.file), encoding="latin-1").read().split("\n")
    rules, seen = [], set()
    for i, ln in enumerate(L):
        m = re.match(r'^([A-Za-z_][\w]*):\s*$', ln)
        if not m or not STRUCT.search(m.group(1)):
            continue
        body = []
        for x in L[i + 1:i + 12]:
            c = code_of(x)
            if not c:
                continue
            if re.match(r'^[A-Za-z_.$][\w.$@]*:', c):
                break
            body.append(c)
            if c == "ret":
                break
        if len(body) < 4 or body[0].lower() != "push xiz" or body[-1] != "ret" \
                or body[-2].lower() != "pop xiz":
            continue
        calls = [c for c in body[1:-2] if c.lower().startswith("call ")]
        others = [c for c in body[1:-2] if not c.lower().startswith("call ")]
        if len(calls) != 1 or not all(ARGMOVE.match(o) for o in others):
            continue
        tgt = calls[0].split(None, 1)[1].strip()
        if not re.match(r'^[A-Za-z_][\w]*$', tgt):
            continue
        # a wrapper of a routine that itself only has a structural name would
        # get a structural name too -- leave it for whoever names the target
        if STRUCT.search(tgt) or re.search(r'_(Skip|Join|Entry|Loop|Return|Code)\d*(_|$)', tgt):
            continue
        new = tgt + "_Wrap"
        if new in defined or new in seen:
            continue
        seen.add(new)
        rules.append((m.group(1), new, " / ".join(body)))
    with open(os.path.join(ROOT, a.out) if not os.path.isabs(a.out) else a.out, "w") as fh:
        fh.write("# %s -- generated by scripts/renaming/lane_accomp_name_wrappers.py\n" % os.path.basename(a.out))
        fh.write("# image %s, %s.  One rule per XIZ-preserving wrapper; the body each\n" % (a.image, a.file))
        fh.write("# rule was matched on is the comment above it.\n")
        for old, new, body in rules:
            fh.write("# %s\ns/\\b%s\\b/%s/g\n" % (body, old, new))
    print("%d wrapper renames written to %s" % (len(rules), a.out))


if __name__ == "__main__":
    main()
