# WSA1 prom_a: the LEAVE (+4) and BUTTON (+8) methods of screen objects whose ENTER (+0) is a ScreenCode<XX>_Handler,
# as notes/prom_a_screen_methods_wave29.py --plan proposes them (its refusals applied), named ScreenLeave_/ScreenButton_Code<XX>.
s/\bsub_FCFDA7\b/ScreenButton_Code80/g
s/\bsub_FD053D\b/ScreenButton_CodeCD/g
s/\bsub_FD058E\b/ScreenButton_Code9B/g
s/\bsub_FD0AA5\b/ScreenButton_Code82/g
s/\bsub_FD0AF6\b/ScreenButton_Code83/g
s/\bsub_FD0B47\b/ScreenButton_Code84/g
s/\bsub_FD0BA7\b/ScreenButton_Code85/g
s/\bsub_FD0C07\b/ScreenButton_Code86/g
s/\bsub_FD2751\b/ScreenButton_Code8B/g
s/\bsub_FD27A2\b/ScreenButton_Code8C/g
s/\bsub_FD27F2\b/ScreenButton_Code8D/g
s/\bsub_FD2852\b/ScreenButton_Code8E/g
s/\bsub_FD28B2\b/ScreenButton_Code8F/g
s/\bsub_FDE152\b/ScreenLeave_Code80/g
s/\bsub_FDE160\b/ScreenLeave_Code87/g
s/\bsub_FDE16E\b/ScreenLeave_Code88/g
s/\bsub_FDE17C\b/ScreenLeave_Code89/g
s/\bsub_FDE18A\b/ScreenLeave_Code8A/g
s/\bsub_FDE198\b/ScreenLeave_Code8B/g
s/\bsub_FDE1A6\b/ScreenLeave_Code8C/g
s/\bsub_FDE1B4\b/ScreenLeave_Code8D/g
s/\bsub_FDE1C2\b/ScreenLeave_Code8E/g
s/\bsub_FDE1D0\b/ScreenLeave_Code8F/g
s/\bsub_FDE1DE\b/ScreenLeave_CodeCD/g
s/\bsub_FDE1EC\b/ScreenLeave_Code9B/g
s/\bsub_FDE1FA\b/ScreenLeave_Code9C/g
s/\bsub_FDE208\b/ScreenLeave_Code82/g
s/\bsub_FDE216\b/ScreenLeave_Code83/g
s/\bsub_FDE224\b/ScreenLeave_Code84/g
s/\bsub_FDE232\b/ScreenLeave_Code85/g
s/\bsub_FDE240\b/ScreenLeave_Code86/g
s/\bsub_FDE24E\b/ScreenLeave_Code90/g
s/\bsub_FDE25C\b/ScreenLeave_Code91/g
s/\bsub_FDE26A\b/ScreenLeave_Code92/g
s/\bsub_FDE278\b/ScreenLeave_Code93/g
s/\bsub_FDE286\b/ScreenLeave_Code94/g
s/\bsub_FDE294\b/ScreenLeave_Code95/g
s/\bsub_FDE2A2\b/ScreenLeave_Code96/g
s/\bsub_FDE2B0\b/ScreenLeave_Code97/g
s/\bsub_FDE2BE\b/ScreenLeave_Code98/g
s/\bsub_FDE2CC\b/ScreenLeave_Code99/g
s/\bsub_FDE2FA\b/ScreenLeave_Code9D/g
s/\bsub_FDE308\b/ScreenLeave_CodeCA/g
s/\bsub_FDE316\b/ScreenLeave_CodeCB/g
s/\bsub_FDE332\b/ScreenLeave_CodeC0/g
s/\bsub_FDE3A2\b/ScreenLeave_CodeC8/g
s/\bsub_FDE3BE\b/ScreenButton_Code90/g
s/\bsub_FDE41E\b/ScreenButton_Code91/g
s/\bsub_FDE47E\b/ScreenButton_Code92/g
s/\bsub_FDE4DE\b/ScreenButton_Code93/g
s/\bsub_FDE53E\b/ScreenButton_Code94/g
s/\bsub_FDE59E\b/ScreenButton_Code95/g
s/\bsub_FDE5EF\b/ScreenButton_Code96/g
s/\bsub_FDE64F\b/ScreenButton_Code97/g
s/\bsub_FDE6AF\b/ScreenButton_Code98/g
s/\bsub_FDE70F\b/ScreenButton_Code99/g
