# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F7E2ED\b/LCD_ClearCurrentLayer/g
s/\bsub_F44B95\b/Seq_ResetPositionToSongStart/g
s/\bsub_F55C44\b/SeqScreen_DrawCountInMeasure/g
s/\bsub_F6B399\b/StepRecord_BStoreAppendBytes/g
s/\bsub_F6F94E\b/Smf_ResetTrackAssignToIdentity/g
s/\bsub_F70DD6\b/SmfCC_UpdateSelectedRpn/g
s/\bsub_F7659B\b/InputStream_OpenAndReadFirstBlock/g
s/\bsub_F7C6FB\b/Transp0se_StepSelectedFieldDown/g
s/\bsub_F7F935\b/Vel0cityChange_FormatSignedValue/g
s/\bsub_FAABB3\b/Mode_InitSavedPartBlocks/g
s/\bsub_FB4F8F\b/SysExTx_SendPartParamValue/g
s/\bsub_FB7B0B\b/SysExSession_StartProgressScreen/g
s/\bsub_FBF020\b/CombinationNaming_StepWriteNumber/g
s/\bsub_FD6BC6\b/SoundEdit_SetSlotEnabled/g
s/\bsub_FD7A05\b/PartRecord0_GetProgramAndBank/g
s/\bsub_FDA7B0\b/SoundEditController_FieldCodeToListPos/g
s/\bsub_FE0514\b/Disk_PrepareForMount/g
s/\bsub_FE2F93\b/DiskProgress_DrawDotAndAdvance/g
s/\bsub_FF5F1B\b/MidiFileSave_MoveNameCursor/g
s/\bsub_FF70D8\b/PartRecords_RestoreShadowedField/g
s/\bsub_F0EA9F\b/Blink_SetupNumberFieldAndDraw/g
s/\bsub_F10175\b/DspEffect_ToggleCommonAlgorithm/g
s/\bsub_F10222\b/DspEffect_StepSelectedBlockSend/g
s/\bsub_F11329\b/DspEffect_SendToneMsg80/g
s/\bsub_F36E21\b/SysExThirdRegion_FetchNextChunk/g
s/\bsub_F37F70\b/Asr16ByCount/g
s/\bsub_F45489\b/Seq_RestoreTrackMaskAndRewind/g
s/\bsub_F455E6\b/SeqMasterTrack_UpdateActive/g
s/\bsub_F45BCD\b/SeqCycle_LocateTracksToCurrentMeasure/g
s/\bsub_FE1CA7\b/Playback_AcceptMidiStartAgain/g
s/\bsub_F4A57E\b/SeqRecord_SaveCursorBaseline/g
s/\bsub_F62C14\b/BStore_LoadStartBeatsPerBar/g
s/\bsub_F6C984\b/StepRecord_LoadPartParamValue/g
s/\bsub_F6FB38\b/Smf_ClearPendingNoteSlots/g
s/\bsub_F710BA\b/Smf_StepCursorOneByte/g
s/\bsub_F765E6\b/SmfWrite_CreateFileWithFirstWindow/g
s/\bsub_F7C918\b/N0teChange_StepSelectedFieldUp/g
s/\bsub_F90F9F\b/ModeScreen_PaintDirtyFields2/g
s/\bsub_FAAC0F\b/ParamImage_PostPartRecordAsChangeEvents/g
s/\bsub_FB5425\b/SysExTx_ProgramChangeAndBank/g
s/\bsub_FC17DF\b/ScaleTuning_PostPitchClassOffset/g
s/\bsub_FD6F96\b/SoundEditLfo_GetStateParamId/g
s/\bsub_FD9F9D\b/ModelingPage_StorePercSource2Reply/g
s/\bsub_FDA901\b/MemoryProtect_IsSoundOn/g
s/\bsub_FE16FE\b/Playback_StopAll/g
s/\bsub_FE8F0C\b/EditScreen_FindMasterTrack/g
s/\bsub_FF5FA0\b/MidiFileSave_StepNameChar/g
s/\bsub_FF7333\b/L0adSingleC0mbination_DrawGroupList/g
s/\bsub_F0F788\b/DspEffectSection0_QueuePaintJobs/g
s/\bsub_F1018F\b/DspEffect_ToggleBypass/g
s/\bsub_F10CC4\b/DspEffect_ToggleParamMarkAtCursor/g
s/\bsub_F123F4\b/MainOutEqualizer_PaintEqValues/g
s/\bsub_F36F8C\b/SysExThirdRegion_AcceptRequest/g
s/\bsub_F38800\b/ParamImage_CopyToSongWorkspace/g
s/\bsub_F4477F\b/Seq_SeekTrackToBeatTick/g
s/\bsub_F454A6\b/Seq_SaveTrackMaskAndStopAll/g
s/\bsub_F456EC\b/SeqRecord_StartOnFirstEvent/g
s/\bsub_F45BD3\b/Seq_LocateToCurrentMeasure/g
s/\bsub_F44237\b/SeqCycle_ResetSettings/g
s/\bsub_F4E30F\b/CycleRecord_CheckOn/g
s/\bsub_F62C18\b/BStore_TimeSigNextMeasure_Call/g
s/\bsub_F6F404\b/MidiFileSave_WriteSeqBankSmf/g
s/\bsub_F701F1\b/SmfPart_SetSoundFromProgramChange/g
s/\bsub_F710E7\b/Smf_ApplyDeltaTime/g
s/\bsub_F7A402\b/BStore_AllocBlock_Veneer/g
s/\bsub_F7C964\b/N0teChange_StepFieldDown/g
s/\bsub_FA15CC\b/Initial_RedrawSelectionHighlight/g
s/\bsub_FAAD19\b/PartControllers_ResetAllParts/g
s/\bsub_FB56D3\b/ParamApply_ResetPairTablesForGm/g
s/\bsub_FB9DA0\b/Medley_ToggleMidiFileStream/g
s/\bsub_FD5F52\b/ToneEditPage_A8_StepLayerPan/g
s/\bsub_FD7181\b/SoundEditController_LoadField0/g
s/\bsub_FDA252\b/DrumSoundNames_FetchNext/g
s/\bsub_FDBE90\b/SoundEditController_DashSwitchesForEffectDest/g
s/\bsub_FE1C67\b/DiskSaveScreen_MountAndScanDirectory/g
s/\bsub_FF7084\b/DiskEntry_CopySelectedToFileName/g
s/\bsub_F0FD5F\b/DspEffect_EnterEqSection/g
s/\bsub_F101C8\b/DspEffect_AdjustBlockByte21/g
s/\bsub_F10EE9\b/DspEffect_RepaintParamPage/g
s/\bsub_F379AB\b/SysExToneImage_WriteByte/g
s/\bsub_F44143\b/BStore_CopyByteD6ToAllBanks/g
s/\bsub_F45119\b/Seq_ApplyLoadedSongSetup/g
s/\bsub_F45524\b/TimedEvents_ClearEndedTrackBits/g
s/\bsub_F45CC4\b/SeqTrackCursors_LocateAllToCurrentMeasure/g
s/\bsub_F44582\b/Seq_MainLoopService/g
s/\bsub_F4EC56\b/RealtimeRecord_Disarm/g
s/\bsub_F683D4\b/StepRecord_BuildCurrentMeasureRow/g
s/\bsub_F6F929\b/Smf_ClearChannelBankSelects/g
s/\bsub_F70C3F\b/Smf_ClampTrackToSlot/g
s/\bsub_F729D9\b/Smf_MergeTrack2IntoTrack1/g
s/\bsub_F7C6B2\b/Transp0se_StepFieldUp/g
s/\bsub_F7E354\b/TrackGrid_DrawPartLabels/g
s/\bsub_FAA418\b/SoundSel_ClampToProgramAndBankRegs/g
s/\bsub_FAB728\b/CombiSel_GroupMemberFromNumberAndBank/g
s/\bsub_FB7A63\b/SysExXfer_InitCpu2Forward/g
s/\bsub_FBACF3\b/SeqMasterTrack_SetFlagFromTrackMask/g
s/\bsub_FD60F2\b/PanelScreen_PostModeRequest/g
s/\bsub_FD785C\b/SoundEditText_GetSlot/g
s/\bsub_FE1CB3\b/DiskSave_CheckFreeSpace/g
s/\bsub_FEF81D\b/EditScreen_EraseVelocityCell/g
s/\bsub_FF70B6\b/MidiFilePlay_SnapshotRecordBytes/g
s/\bsub_F09E02\b/SoundEditMenu_PaintPanAmountField/g
s/\bsub_F1008E\b/DspEffect_EnterParamSection/g
s/\bsub_F112ED\b/DspEffect_ToneMsg88_Id00/g
s/\bsub_F37D17\b/SysExParam_ExecSoundWriteRequest/g
s/\bsub_F45445\b/Seq_RewindOnMidiStart/g
s/\bsub_F45D09\b/SeqRecord_TerminateTracksIfRecording/g
