# Sub CPU RAM interrupt trampolines (0x400 + 5*slot): slot-numbered INT_HANDLER_xx -> the hardware vector each slot serves
# Vector order: MAME src/devices/cpu/tlcs900/tmp94c241.cpp tmp94c241_irq_vector_map; slot map read from the boot ROM's VECTOR_TABLE.
s/\bINT_HANDLER_00\b/PAYLOAD_ENTRY/g
s/\bINT_HANDLER_01\b/IntTramp_SWI1/g
s/\bINT_HANDLER_02\b/IntTramp_SWI2/g
s/\bINT_HANDLER_03\b/IntTramp_SWI3/g
s/\bINT_HANDLER_04\b/IntTramp_SWI4/g
s/\bINT_HANDLER_05\b/IntTramp_SWI5/g
s/\bINT_HANDLER_06\b/IntTramp_SWI6/g
s/\bINT_HANDLER_07\b/IntTramp_SWI7/g
s/\bINT_HANDLER_08\b/IntTramp_INTWD/g
s/\bINT_HANDLER_09\b/IntTramp_INT0/g
s/\bINT_HANDLER_0A\b/IntTramp_INT4/g
s/\bINT_HANDLER_0B\b/IntTramp_INT5/g
s/\bINT_HANDLER_0C\b/IntTramp_INT6/g
s/\bINT_HANDLER_0D\b/IntTramp_INT7/g
s/\bINT_HANDLER_0E\b/IntTramp_Reserved/g
s/\bINT_HANDLER_0F\b/IntTramp_INT8/g
s/\bINT_HANDLER_10\b/IntTramp_INT9/g
s/\bINT_HANDLER_11\b/IntTramp_INTA/g
s/\bINT_HANDLER_12\b/IntTramp_INTB/g
s/\bINT_HANDLER_13\b/IntTramp_INTT0/g
s/\bINT_HANDLER_14\b/IntTramp_INTT1/g
s/\bINT_HANDLER_15\b/IntTramp_INTT2/g
s/\bINT_HANDLER_16\b/IntTramp_INTT3/g
s/\bINT_HANDLER_17\b/IntTramp_INTTR4/g
s/\bINT_HANDLER_18\b/IntTramp_INTTR5/g
s/\bINT_HANDLER_19\b/IntTramp_INTTR6/g
s/\bINT_HANDLER_1A\b/IntTramp_INTTR7/g
s/\bINT_HANDLER_1B\b/IntTramp_INTTR8/g
s/\bINT_HANDLER_1C\b/IntTramp_INTTR9/g
s/\bINT_HANDLER_1D\b/IntTramp_INTTRA/g
s/\bINT_HANDLER_1E\b/IntTramp_INTTRB/g
s/\bINT_HANDLER_1F\b/IntTramp_INTRX0/g
s/\bINT_HANDLER_20\b/IntTramp_INTTX0/g
s/\bINT_HANDLER_21\b/IntTramp_INTRX1/g
s/\bINT_HANDLER_22\b/IntTramp_INTTX1/g
s/\bINT_HANDLER_23\b/IntTramp_INTAD/g
s/\bINT_HANDLER_24\b/IntTramp_INTTC0/g
s/\bINT_HANDLER_25\b/IntTramp_INTTC1/g
s/\bINT_HANDLER_26\b/IntTramp_INTTC2/g
s/\bINT_HANDLER_27\b/IntTramp_INTTC3/g
s/\bINT_HANDLER_28\b/IntTramp_INTTC4/g
s/\bINT_HANDLER_29\b/IntTramp_INTTC5/g
s/\bINT_HANDLER_2A\b/IntTramp_INTTC6/g
s/\bINT_HANDLER_2B\b/IntTramp_INTTC7/g
s/\bINT_HANDLER_2C\b/IntTramp_NMI/g
s/\bINT16_TaskSwitch_Handler\b/INTT3_TaskSwitch_Handler/g
