# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F4E56F\b/SeqTrackKey_Press/g
s/\bsub_F7129A\b/SmfEvent_MarkChannelUsed/g
s/\bsub_F71417\b/SmfPart_ResetAllRecords/g
s/\bsub_F5BFBD\b/SoundEdit_PaintPageLabelBackdrop/g
s/\bsub_F556D2\b/PartIndex_PostChangeEvent/g
s/\bsub_F5C929\b/SoundEditFilter_PaintHeader/g
s/\bsub_F533DC\b/Drawbar_StepLevel/g
s/\bsub_F54210\b/Drawbar_WaitReloadMark/g
s/\bsub_F68F62\b/LcdKeyErs_StepRecord/g
s/\bsub_F6B8F1\b/BStore_ReadByteAtSongPositionPlus1/g
s/\bsub_F6D6DC\b/MsgLine_MeasureNumber/g
s/\bsub_F7E788\b/TrackAssign_PaintTrackGroup/g
s/\bsub_F4542D\b/Seq_RequestRewind/g
s/\bsub_F0B91C\b/NameEntry_Begin/g
s/\bsub_F5C916\b/SoundEdit_PaintPage12Label/g
s/\bsub_F31899\b/UiPaint_PageLabelBackdrop/g
s/\bsub_F44AEE\b/Seq_SetTrackBeatsFromTransportB/g
s/\bsub_F48464\b/SeqCycle_LocateToStart/g
s/\bsub_F48580\b/SeqCycle_CaptureEndCursors/g
s/\bsub_F5C144\b/ToneEditPage_PaintMainAndSubFocus/g
s/\bsub_F5C94B\b/SoundEditFilter_PaintModeField/g
s/\bsub_F60B22\b/Seq_LoadTimeSigAtCurrentMeasure/g
s/\bsub_F70AE9\b/SmfCC_PutSelectedRpnValueEvent/g
s/\bsub_F71A95\b/SmfCC_PutParamEventWithNumber/g
s/\bsub_F7E2FC\b/TrackAssign_DrawSelectedPart/g
s/\bsub_F7F397\b/MeasureErase_DrawValues/g
s/\bsub_F7F9FB\b/Vel0cityChange_DrawValues/g
s/\bsub_F7FD45\b/Transp0se_DrawValues/g
s/\bsub_F5C727\b/SoundEditAmp_PaintHeader/g
s/\bsub_F726C6\b/SmfCC_PutPartParamEvent_MultiTrack/g
