# rename_event_arms_v9.sed -- written by scripts/renaming/gen_event_arm_names.py
# generic `cp xbc, EVT_X / jr z, <arm>` targets -> <dispatcher>_On<Event>
s/\bStylCnvStorBnk_ProcDataBlock_Skip\b/StylCnvStorBnk_ProcDataBlock_OnPaint/g
s/\bIvNamingExit_ScreenData_Skip2\b/IvNamingExit_ScreenData_OnParaDraw/g
s/\bWndEvt_EventCodeDispatch_Skip\b/WndEvt_EventCodeDispatch_OnIndexswUp/g
s/\bIvNamingExit_ScreenData_Skip\b/IvNamingExit_ScreenData_OnPaint/g
s/\bAcDiskFileName_HandleEvent1\b/AcDiskFileNameBoxProc_OnHide/g
s/\bAcDiskFileName_HandleEvent2\b/AcDiskFileNameBoxProc_OnShow/g
s/\bPsCstmCpNameBox_HandleEvt2D\b/PsCstmCpNameBoxProc_OnCstmFNmDisp/g
s/\bPsCstmCpNameBox_HandleEvt2E\b/PsCstmCpNameBoxProc_OnCstmTNmDisp/g
s/\bAcCurSongName_HandleEvent1\b/AcCurSongNameBoxProc_OnHide/g
s/\bAcCurSongName_HandleEvent2\b/AcCurSongNameBoxProc_OnShow/g
s/\bAcDocSongName_HandleEvent1\b/AcDocSongNameBoxProc_OnHide/g
s/\bAcDocSongName_HandleEvent2\b/AcDocSongNameBoxProc_OnShow/g
s/\bAcSmfFileName_HandleEvent1\b/AcSmfFileNameBoxProc_OnHide/g
s/\bAcSmfFileName_HandleEvent2\b/AcSmfFileNameBoxProc_OnShow/g
s/\bAcSmfSongName_HandleEvent1\b/AcSmfSongNameBoxProc_OnHide/g
s/\bAcSmfSongName_HandleEvent2\b/AcSmfSongNameBoxProc_OnShow/g
s/\bMiddleCmpClr_HandleEvent07\b/MiddleCmpClrFunc_OnCmpClrNo/g
s/\bPsCmpCpFVariBox_HandleEvt1\b/PsCmpCpFVariBoxProc_OnShow/g
s/\bPsCmpCpFVariBox_HandleEvt2\b/PsCmpCpFVariBoxProc_OnHide/g
s/\bPsCmpCpFVariBox_HandleEvt5\b/PsCmpCpFVariBoxProc_OnApRhyVariNm/g
s/\bPsCstmCpNameBox_HandleEvt1\b/PsCstmCpNameBoxProc_OnShow/g
s/\bPsCstmCpNameBox_HandleEvt2\b/PsCstmCpNameBoxProc_OnHide/g
s/\bPsCstmCpNameBox_HandleEvtD\b/PsCstmCpNameBoxProc_OnDraw/g
s/\bPsMixer_CtlTypeProc10_Skip\b/PsMixer_CtlTypeProc10_OnDraw/g
s/\bPsMixer_CtlTypeProc1_Skip2\b/PsMixer_CtlTypeProc1_OnParaDraw/g
s/\bPsMixer_CtlTypeProc1_Skip3\b/PsMixer_CtlTypeProc1_OnSoundName/g
s/\bPsMixer_CtlTypeProc2_Skip5\b/PsMixer_CtlTypeProc2_OnIndexswBoth/g
s/\bPsMixer_CtlTypeProc2_Skip7\b/PsMixer_CtlTypeProc2_OnLswData/g
s/\bPsMixer_CtlTypeProc3_Skip2\b/PsMixer_CtlTypeProc3_OnParaDraw/g
s/\bPsMixer_CtlTypeProc3_Skip8\b/PsMixer_CtlTypeProc3_OnIndexswBoth/g
s/\bPsMixer_CtlTypeProc4_Skip2\b/PsMixer_CtlTypeProc4_OnParaDraw/g
s/\bPsMixer_CtlTypeProc7_Skip2\b/PsMixer_CtlTypeProc7_OnParaDraw/g
s/\bPsMixer_CtlTypeProc7_Skip7\b/PsMixer_CtlTypeProc7_OnIndexswBoth/g
s/\bPsMixer_CtlTypeProc8_Skip2\b/PsMixer_CtlTypeProc8_OnIndexswUpAic/g
s/\bPsMixer_CtlTypeProc8_Skip4\b/PsMixer_CtlTypeProc8_OnLswData/g
s/\bPsMixer_CtlTypeProc9_Skip2\b/PsMixer_CtlTypeProc9_OnParaDraw/g
s/\bAcCmpTempoBox_HandleEvt1C\b/AcCmpTempoBoxProc_OnLswData/g
s/\bAcPDSongName_HandleEvent1\b/AcPDSongNameBoxProc_OnHide/g
s/\bAcPDSongName_HandleEvent2\b/AcPDSongNameBoxProc_OnShow/g
s/\bCmpSetP1_GridCheck_Return\b/CmpSetP1GridCheck_OnRequestGridDraw/g
s/\bMspBnkNameBox_HandleEvt1B\b/PsMspBnkNameBoxProc_OnMspUsr1NmDisp/g
s/\bMspBnkNameBox_HandleEvt1C\b/PsMspBnkNameBoxProc_OnMspUsr2NmDisp/g
s/\bMspBnkNameBox_HandleEvt1D\b/PsMspBnkNameBoxProc_OnMspRgp1NmDisp/g
s/\bPsCmpCpFGrpBox_HandleEvt1\b/PsCmpCpFGrpBoxProc_OnShow/g
s/\bPsCmpCpFGrpBox_HandleEvt2\b/PsCmpCpFGrpBoxProc_OnHide/g
s/\bPsCmpCpFGrpBox_HandleEvt4\b/PsCmpCpFGrpBoxProc_OnApRhyGrpNm/g
s/\bPsCmpCpFPtnBox_HandleEvt1\b/PsCmpCpFPtnBoxProc_OnShow/g
s/\bPsCmpCpFPtnBox_HandleEvt2\b/PsCmpCpFPtnBoxProc_OnHide/g
s/\bPsCstmCpBnkBox_HandleEvt1\b/PsCstmCpBnkBoxProc_OnShow/g
s/\bPsCstmCpBnkBox_HandleEvt2\b/PsCstmCpBnkBoxProc_OnHide/g
s/\bPsCtmAttStrBox_HandleEvt1\b/PsCtmAttStrBoxProc_OnShow/g
s/\bPsCtmAttStrBox_HandleEvt2\b/PsCtmAttStrBoxProc_OnHide/g
s/\bPsMixer_CtlTypeProc1_Skip\b/PsMixer_CtlTypeProc1_OnSeleDraw/g
s/\bPsMixer_CtlTypeProc3_Skip\b/PsMixer_CtlTypeProc3_OnSeleDraw/g
s/\bPsMixer_CtlTypeProc4_Skip\b/PsMixer_CtlTypeProc4_OnSeleDraw/g
s/\bPsMixer_CtlTypeProc5_Skip\b/PsMixer_CtlTypeProc5_OnParaDraw/g
s/\bPsMixer_CtlTypeProc6_Skip\b/PsMixer_CtlTypeProc6_OnParaDraw/g
s/\bPsMixer_CtlTypeProc7_Skip\b/PsMixer_CtlTypeProc7_OnSeleDraw/g
s/\bPsMixer_CtlTypeProc9_Skip\b/PsMixer_CtlTypeProc9_OnSeleDraw/g
s/\bAcCmpTempoBox_HandleEvt1\b/AcCmpTempoBoxProc_OnShow/g
s/\bAcCmpTempoBox_HandleEvt2\b/AcCmpTempoBoxProc_OnHide/g
s/\bAcDocFileNo_HandleEvent1\b/AcDocFileNoBoxProc_OnHide/g
s/\bAcDocFileNo_HandleEvent2\b/AcDocFileNoBoxProc_OnShow/g
s/\bCmpSetP1_GridCheck_Case1\b/AcCmpSetGridBoxProc_OnGetFixedRowStr/g
s/\bMiddleName_HandleEvent01\b/MiddleNameFunc_OnMspNameSet/g
s/\bMspBnkNameBox_HandleEvt2\b/PsMspBnkNameBoxProc_OnHide/g
s/\bMspBnkNameBox_HandleEvtD\b/PsMspBnkNameBoxProc_OnDraw/g
s/\bPsCstmCpSwBox_HandleEvt1\b/PsCstmCpSwBoxProc_OnShow/g
s/\bPsCstmCpSwBox_HandleEvt2\b/PsCstmCpSwBoxProc_OnHide/g
s/\bResourceWidget_Init_Loop\b/FunctionProc_OnGetFunction/g
s/\bSngSelFunc_HandleEvent47\b/SngSelFunc_OnGetRamString/g
s/\bAcPDFileNo_HandleEvent1\b/AcPDFileNoBoxProc_OnHide/g
s/\bAcPDFileNo_HandleEvent2\b/AcPDFileNoBoxProc_OnShow/g
s/\bEasyCmp_GridCheck_Case1\b/AcEasyCmpGridBoxProc_OnGetFixedRowStr/g
s/\bMainCmpCp_HandleEvent03\b/MainCmpCpFunc_OnRhyVariNmGet/g
s/\bMspRecBnkBox_HandleEvt1\b/PsMspRecBnkBoxProc_OnShow/g
s/\bMspRecBnkBox_HandleEvt2\b/PsMspRecBnkBoxProc_OnHide/g
s/\bMspRecPadBox_HandleEvt1\b/PsMspRecPadBoxProc_OnShow/g
s/\bMspRecPadBox_HandleEvt2\b/PsMspRecPadBoxProc_OnHide/g
s/\bMspRgpSet_HandleEvent13\b/MainMspRgpSetFunc_OnRgpBnkDn/g
s/\bPsMspNameBnk_HandleEvt1\b/PsMspNameBnkProc_OnShow/g
s/\bPsMspNameBnk_HandleEvt2\b/PsMspNameBnkProc_OnHide/g
s/\bPsNameMemBox_HandleEvt1\b/PsNameMemBoxProc_OnShow/g
s/\bPsNameMemBox_HandleEvt2\b/PsNameMemBoxProc_OnHide/g
s/\bRgpSetBnkBox_HandleEvt1\b/PsRgpSetBnkBoxProc_OnShow/g
s/\bRgpSetBnkBox_HandleEvt2\b/PsRgpSetBnkBoxProc_OnHide/g
s/\bAcCmpRecBox_HandleEvt1\b/AcCmpRecBoxProc_OnShow/g
s/\bAcCmpRecBox_HandleEvt2\b/AcCmpRecBoxProc_OnHide/g
s/\bAcCurSong_HandleEvent1\b/AcCurrentSongBoxProc_OnHide/g
s/\bAcCurSong_HandleEvent2\b/AcCurrentSongBoxProc_OnShow/g
s/\bCmpNameMenu_HandleEvtD\b/CmpNameMenuBoxProc_OnDraw/g
s/\bCstmName_HandleEvent2C\b/MainCstmNameFunc_OnCstmTNmGet/g
s/\bEffectBox_HandleEvent0\b/EffectBoxProc_OnRetEffFix/g
s/\bEffectBox_HandleEvent1\b/EffectBoxProc_OnRetEffPara/g
s/\bLyricsBox_HandleEvent9\b/LyricsBoxProc_OnLyricsAllClear/g
s/\bParaListBox_HandleEvtB\b/PsParaListBoxProc_OnPaint/g
s/\bParaListBox_HandleEvtF\b/PsParaListBoxProc_OnParaDraw/g
s/\bPsCmpQtzBox_HandleEvt1\b/PsCmpQtzBoxProc_OnShow/g
s/\bPsCmpQtzBox_HandleEvt2\b/PsCmpQtzBoxProc_OnHide/g
s/\bSndArgNm_HandleEvent21\b/SndArgNm_CheckChannelDone_OnArgChoGet/g
s/\bSndArgNm_HandleEvent24\b/SndArgNm_CheckChannelDone_OnSetPtSel/g
s/\bStylCnvVer_HandleEvt89\b/PsStylCnvVerProc_OnGetStrPtr/g
s/\bAcMemNoBox_HandleEvt1\b/AcMemNoBoxProc_OnShow/g
s/\bAcMemNoBox_HandleEvt2\b/AcMemNoBoxProc_OnHide/g
s/\bConstFlagProc_Default\b/ConstFlagProc_OnGetPropertyEx/g
s/\bEnumList_Reset_Return\b/ResEventProc_OnGetName/g
s/\bMspMeasBox_HandleEvt1\b/PsMspMeasBoxProc_OnShow/g
s/\bMspMeasBox_HandleEvt2\b/PsMspMeasBoxProc_OnHide/g
s/\bS2cFunc_HandleEvent11\b/MainS2cFunc_OnS2cTrDn/g
s/\bSCTxtBox2_HandleEvt89\b/PsSCTxtBox2Proc_OnGetStrPtr/g
s/\bScrollbar_Case1C00001\b/AcRotStrBoxProc_OnNotParaDraw/g
s/\bScrollbar_Case1E00067\b/AcRotStrBoxProc_OnHide/g
s/\bScrollbar_Case1E00068\b/AcRotStrBoxProc_OnWakeUpNow/g
s/\bScrollbar_Case1E00069\b/AcRotStrBoxProc_OnPaint/g
s/\bScrollbar_Case1E5000A\b/AcRotStrBoxProc_OnParaDraw/g
s/\bStylCnvVer_HandleEvt1\b/PsStylCnvVerProc_OnShow/g
s/\bStylCnvVer_HandleEvt2\b/PsStylCnvVerProc_OnHide/g
s/\bEntGridCheck_Default\b/EntertainerGridCheck_OnRetEffPara/g
s/\bIvInterruptProc_Skip\b/ScrollDelta_ComputeDirection_OnSwInAic/g
s/\bMspMemBox_HandleEvt1\b/PsMspMemBoxProc_OnShow/g
s/\bMspMemBox_HandleEvt2\b/PsMspMemBoxProc_OnHide/g
s/\bRamCtrl_Adjust_Entry\b/MainRamControl_OnRamAdd/g
s/\bSCTxtBox2_HandleEvt1\b/PsSCTxtBox2Proc_OnShow/g
s/\bSCTxtBox2_HandleEvt2\b/PsSCTxtBox2Proc_OnHide/g
s/\bSound_Navigate_Entry\b/MainGetSoundName_OnAddSoundSwNo/g
s/\bEntGridCheck_Return\b/EntertainerGridCheck_OnRetEffFix/g
s/\bEsCmp_HandleEvent28\b/MainEsCmpFunc_OnEsCmpStylDn/g
s/\bEsCmp_HandleEvent29\b/MainEsCmpFunc_OnEsCmpVariUp/g
s/\bEsCmp_HandleEvent2A\b/MainEsCmpFunc_OnEsCmpVariDn/g
s/\bSCTxtBox_HandleEvt1\b/PsSCTxtBoxProc_OnShow/g
s/\bSCTxtBox_HandleEvt2\b/PsSCTxtBoxProc_OnHide/g
s/\bTitleWidget_Default\b/SupportClassProc_OnGetPropSize/g
s/\bBounds_Case1E0006A\b/IvIndexSwDelayProc_OnGetString/g
s/\bBounds_Case1E0006B\b/IvIndexSwDelayProc_OnDraw/g
s/\bDpMdlySmfLyr_CaseA\b/DpMdlySmfLyrTtlFunc_OnSwIn/g
s/\bLswLeftHold_Case42\b/LswLeftHold_OnGetLswString/g
s/\bSeqNameOK_Return10\b/SeqNamingCheck_OnGetStringLength/g
s/\bParaLoadOpt_Entry\b/InOutGridCheck_OnRequestGridDraw/g
s/\bRamCtrl_Set_Entry\b/MainRamControl_OnRamGet/g
s/\bSqTrAsPsTtl_CaseD\b/SqTrAsPsTtlFunc_OnSwIn/g
s/\bAcPresCtrl_Case4\b/AcPresentationControlProc_OnStartSong/g
s/\bAcPresCtrl_Case5\b/AcPresentationControlProc_OnEndSong/g
s/\bEdit_Case1E00067\b/IvWaitWinCtlProc_OnDraw/g
s/\bEdit_Case1E00068\b/IvWaitWinCtlProc_OnOnWindow/g
s/\bEdit_Case1E00069\b/IvWaitWinCtlProc_OnGetString/g
s/\bMspMenuTtl_Case1\b/MainMspRgpSetFunc_OnRgpPadDn/g
s/\bCheckOk_Return2\b/CheckPasswordOk_OnGetStringLength/g
s/\bDpMdlyDoc_CaseA\b/DpMdlyDocTtlFunc_OnSwIn/g
s/\bDpMdlySmf_CaseA\b/DpMdlySmfTtlFunc_OnSwIn/g
s/\bNameProc_Return\b/NameProc_OnCheckPropString/g
s/\bDirmdEmu_CaseC\b/IvDirmdScreenProc_OnOldTitle/g
s/\bDirmdEmu_CaseD\b/IvDirmdScreenProc_OnGetBoxBorder/g
s/\bDpMdlyPd_CaseA\b/DpMdlyPdTtlFunc_OnSwIn/g
s/\bDpSmfLyr_CaseA\b/DpSmfLyrTtlFunc_OnSwIn/g
s/\bDpSmfLyr_CaseB\b/DpSmfLyrTtlFunc_OnSwOn/g
s/\bDpSmfLyr_CaseC\b/DpSmfLyrTtlFunc_OnSwOff/g
s/\bSeqEvent_CaseC\b/ApEditSyori_OnIncVal/g
s/\bSeqEvent_CaseD\b/ApEditSyori_OnDecVal/g
s/\bSqAftSet_Case0\b/SqAftSetFunc_OnGetBitAddress/g
s/\bSqAftSet_Case1\b/SqAftSetFunc_OnGetBit/g
s/\bWakeUp_Return1\b/WakeUpPassword_OnAreYouClassProc/g
s/\bPwdOk_Return2\b/PasswordOk_OnGetStringLength/g
s/\bSqTrSel_CaseB\b/MiddleFuncCall_OnLyricsCharaReq/g
s/\bEdit_Default\b/IvWaitWinCtlProc_OnOffWindow/g
s/\bDpDoc_CaseA\b/DpDocTtlFunc_OnSwIn/g
s/\bDpDoc_CaseG\b/DpDocTtlFunc_OnSwOn/g
s/\bDpDoc_CaseI\b/DpDocTtlFunc_OnSwOff/g
s/\bDpSmf_CaseA\b/DpSmfTtlFunc_OnSwIn/g
s/\bDpSmf_CaseG\b/DpSmfTtlFunc_OnSwOn/g
s/\bDpSmf_CaseI\b/DpSmfTtlFunc_OnSwOff/g
s/\bDpPd_CaseA\b/DpPdTtlFunc_OnSwIn/g
s/\bDpPd_CaseG\b/DpPdTtlFunc_OnSwOn/g
s/\bDpPd_CaseI\b/DpPdTtlFunc_OnSwOff/g
