# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FC0227\b/PartSound_RequeuePartIfUserBank/g
s/\bsub_FC19E0\b/Msg0716_PostClearSoundRamRequest/g
s/\bsub_FDA808\b/PanelLed_SetOrClearRequestBits/g
s/\bsub_FDA829\b/PanelLed_SetCompareFlag/g
s/\bsub_FE14E9\b/MidiOut_SendSongSelect/g
s/\bsub_F45463\b/BStore_TrackToPart_CopyToBackup/g
s/\bsub_F45478\b/BStore_TrackToPart_CopyFromBackup/g
s/\bsub_F49B43\b/SeqRecord_WriteModulationResetToTakeTracks/g
s/\bsub_F49B5C\b/SeqRecord_WritePitchBendResetToTakeTracks/g
s/\bsub_F49BFA\b/SeqRecord_CloseAllHeldNotes/g
s/\bsub_F49DE6\b/SeqRecord_SplitHeldNoteAtBeatLimit/g
s/\bsub_F4A4E3\b/BStore_ExtendChainAtCursor_B_SaveRegs/g
s/\bsub_F4A4F6\b/SeqRecord_TerminateTrackOnMemoryFull/g
s/\bsub_F4A53E\b/SeqRecord_LoadHeldNoteListHeadTail/g
s/\bsub_F4A56C\b/SeqRecord_HeldNoteSlotAddress/g
s/\bsub_F4ABE8\b/CycleRecord_WriteStagedEventToRecordTrack/g
s/\bsub_F77F20\b/InputStream_Refill_Copy2/g
s/\bsub_F77F2A\b/InputStream_RefillDone_Copy2/g
s/\bJumpTable_FA08BF\b/SystemTest_NoteKeyItemHandlers/g
s/\bsub_FA08D7\b/SystemTest_NoteKeys_SetTestOnOff/g
s/\bsub_FA08F0\b/SystemTest_NoteKeys_SetMonoPoly/g
s/\bsub_FA0909\b/SystemTest_StepFirstNote/g
s/\bsub_FA0925\b/SystemTest_StepSecondNote/g
s/\bsub_FA0940\b/SystemTest_StepThirdNote/g
s/\bsub_FA095B\b/SystemTest_StepFourthNote/g
s/\bJumpTable_FA09BD\b/SystemTest_VelocityKeyItemHandlers/g
s/\bJumpTable_FA09BD__FA09D5\b/SystemTest_VelocityKeys_SetTestOnOff/g
s/\bsub_FA09EE\b/SystemTest_VelocityKeys_SetMonoPoly/g
s/\bsub_FA0A07\b/SystemTest_StepFirstVelocity/g
s/\bsub_FA0A22\b/SystemTest_StepSecondVelocity/g
s/\bsub_FA0A3D\b/SystemTest_StepThirdVelocity/g
s/\bsub_FA0A58\b/SystemTest_StepFourthVelocity/g
s/\bJumpTable_FA0B13\b/SystemTest_ValueHeaderItemHandlers/g
s/\bsub_FA0B2B\b/SystemTest_ShowValueHeader/g
s/\bsub_FA0B51\b/SystemTest_ShowNoteVelocityHeader/g
s/\bSeqEvt_SelectCtrlEventSlot_JumpTable_FAF410\b/SeqEvt_SelectCtrlEventSlot_StatusHandlers/g
s/\bsub_FAF420\b/SeqEvt_SelectChanPressureSlot/g
s/\bsub_FAF431\b/SeqEvt_SelectModulationSlot/g
s/\bsub_FAF442\b/SeqEvt_SelectPitchBendSlot/g
s/\bsub_FAF453\b/SeqEvt_SelectExpressionSlot/g
s/\bSeqEvt_ApplyCtrlEvent_JumpTable_FAF16C\b/SeqEvt_ApplyCtrlEvent_StatusHandlers/g
s/\bJumpTable_FAB8B4\b/List2030_PartFieldHandlers/g
s/\bsub_FAB8E4\b/List2030_PartProgramChange_Apply_Call/g
s/\bJumpTable_FAC326\b/Ctrl_CookedCellNumberHandlers/g
s/\bJumpTable_FAC326_Code_Skip\b/Ctrl_CookedCellFor_Default/g
s/\bJumpTable_FBD25F\b/CombiEditSound_PageTextHandlers/g
s/\bsub_FBD277\b/CombiEditSound_DrawLevelsPageText/g
s/\bsub_FBD286\b/CombiEditSound_DrawControllerFilterPageText/g
s/\bsub_FBD294\b/CombiEditSound_DrawAssignAndInputFilterPageText/g
s/\bsub_FBD2A2\b/CombiEditSound_DrawMidiOutPageText/g
s/\bsub_FBD2C5\b/CombiEditSound_DrawMidiOutFilterPageText/g
s/\bJumpTable_FBD320\b/CombiEditSound_PageRowCursorHandlers/g
s/\bsub_FBD338\b/CombiEditSound_MoveLevelsPageRowCursor/g
s/\bsub_FBD346\b/CombiEditSound_MoveControllerFilterPageRowCursor/g
s/\bsub_FBD354\b/CombiEditSound_MoveAssignAndInputFilterPageRowCursor/g
s/\bsub_FBD362\b/CombiEditSound_MoveMidiOutPageRowCursor/g
s/\bsub_FBD370\b/CombiEditSound_MoveMidiOutFilterPageRowCursor/g
s/\bsub_FBD37E\b/CombiEditSound_MoveMultipleMessagesPageRowCursor/g
s/\bDispatchTable_F0F0CE\b/DspEffect_OnParamEvent_BySection/g
s/\bsub_F0F0E6\b/DspEffect_OnParamEvent_ParamSections/g
s/\bStateDispatchTable_F5693F\b/CycleRecordScreen_FieldIncHandlers/g
s/\bStateDispatchTable_F56A79\b/CycleRecordScreen_FieldDecHandlers/g
s/\bsub_F56953\b/CycleRecordScreen_SwitchCycleOn/g
s/\bsub_F5698E\b/CycleRecordScreen_IncStartMeasure/g
s/\bsub_F56A1D\b/CycleRecordScreen_IncEndMeasure/g
s/\bsub_F56A8D\b/CycleRecordScreen_SwitchCycleOff/g
s/\bsub_F56AB1\b/CycleRecordScreen_DecStartMeasure/g
s/\bsub_F56AF3\b/CycleRecordScreen_DecEndMeasure/g
s/\bDispatchState36CE_F56925\b/CycleRecordScreen_IncField/g
s/\bDispatchState36CE_F56A5F\b/CycleRecordScreen_DecField/g
s/\bSelect36CE_F568AB\b/CycleRecordScreen_SelectCycleField/g
s/\bSelect36CE_F568E9\b/CycleRecordScreen_SelectStartMeasureField/g
s/\bSelect36CE_F56907\b/CycleRecordScreen_SelectEndMeasureField/g
s/\bStateDispatchTable_F5706A\b/CyclePlayScreen_FieldIncHandlers/g
s/\bStateDispatchTable_F571A6\b/CyclePlayScreen_FieldDecHandlers/g
s/\bsub_F5707E\b/CyclePlayScreen_SwitchCycleOn/g
s/\bsub_F570BB\b/CyclePlayScreen_IncStartMeasure/g
s/\bsub_F5714A\b/CyclePlayScreen_IncEndMeasure/g
s/\bsub_F573BA\b/CyclePlayEditScreen_SwitchSoloOn/g
s/\bsub_F571BA\b/CyclePlayScreen_SwitchCycleOff/g
s/\bsub_F571D8\b/CyclePlayScreen_DecStartMeasure/g
s/\bsub_F5721A\b/CyclePlayScreen_DecEndMeasure/g
s/\bsub_F573F3\b/CyclePlayEditScreen_SwitchSoloOff/g
s/\bDispatchState3627_F57050\b/CyclePlayScreen_IncField/g
s/\bDispatchState3627_F5718C\b/CyclePlayScreen_DecField/g
s/\bDispatchTable_F542D1\b/DrawbarSettingPage_RowStepHandlers/g
s/\bsub_F53320\b/DrawbarSettingPage_StepPercussiveToneDecay/g
s/\bsub_F53381\b/DrawbarSettingPage_StepPercussiveToneLevel/g
s/\bsub_F53264\b/DrawbarSettingPage_StepAttackTime/g
s/\bsub_F532BF\b/DrawbarSettingPage_StepReleaseTime/g
s/\bDispatchTable_F674CE\b/StepRecord_CursorKeyTrackKindHandlers/g
s/\bsub_F674DE\b/StepRecord_SongTrackCursorKey/g
s/\bsub_F67558\b/StepRecord_MasterTrackCursorKey/g
s/\bDispatchTable_F67548\b/StepRecord_SongTrackCursorKeyHandlers/g
s/\bDispatchTable_F675BB\b/StepRecord_MasterTrackCursorKeyHandlers/g
s/\bDispatchTable_F674CE_Nop0\b/StepRecord_NoAction/g
s/\bDispatchTable_F68972\b/StepRecord_MainLoopService_TrackKindHandlers/g
s/\bsub_F68982\b/StepRecord_MainLoopService_SongOrMasterTrack/g
s/\bsub_F689AD\b/StepRecord_MainLoopService_Kind3/g
s/\bsub_F689E0\b/StepRecord_MainLoopService_Kind0/g
s/\bDispatchTable_F68FB4\b/StepRecordSub00_LcdKeyRow4_TrackKindHandlers/g
s/\bDispatchTable_F6953C\b/StepRecord_TrackKindPageEnterHandlers/g
s/\bsub_F6954C\b/StepRecord_ShowSongTrackPage/g
s/\bsub_F69556\b/StepRecord_ShowMasterTrackPage/g
s/\bsub_F69560\b/StepRecord_ShowKind3Page/g
s/\bDispatchTable_F69C24\b/StepRecord_TrackKindPageReturnHandlers/g
s/\bsub_F69C34\b/StepRecord_ReturnToSongTrackPage/g
s/\bsub_F69C50\b/StepRecord_ReturnToMasterTrackPage/g
s/\bsub_F69C71\b/StepRecord_ReturnToKind3Page/g
s/\bDispatchTable_F6C272\b/StepRecord_TrackKindMsgLineHandlers/g
s/\bsub_F6C269\b/StepRecord_PutKind3MsgLine/g
s/\bDispatchTable_F6828B\b/StepRecordKind3Sub12_ButtonTable/g
s/\bDispatchTable_F5B8F8\b/Dispatch_Code80_PaintTable/g
s/\bDispatchTable_F5B9F8\b/Dispatch_Code80_RepaintFieldTable/g
s/\bDispatchTable_F5B8F8_Nop42\b/Dispatch_Code80_PaintNoAction/g
s/\bDispatchTable_F5B9F8_Nop42\b/Dispatch_Code80_RepaintFieldNoAction/g
