# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bSelectorRoutines_F558AE\b/ButtonTable_RealtimeRecordScreen/g
s/\bCallSelectorTable_F558AE\b/ScreenButton_RealtimeRecordScreen/g
s/\bFwd_F55810\b/ScreenEnter_RealtimeRecordScreen_Fwd/g
s/\bsub_F56058\b/ScreenEnter_RealtimeRecordScreen/g
s/\bFwd_F55814\b/ScreenLeave_RealtimeRecordScreen_Fwd/g
s/\bsub_F56129\b/ScreenLeave_RealtimeRecordScreen/g
s/\bsub_F56342\b/LcdKeyRow1_RealtimeRecordScreen/g
s/\bsub_F563DD\b/LcdKeyRow2_RealtimeRecordScreen/g
s/\bsub_F56474\b/LcdKeyRow3_RealtimeRecordScreen/g
s/\bsub_F56511\b/ExitKey_RealtimeRecordScreen/g
s/\bSelectorRoutines_F5592E\b/ButtonTable_MetronomeBalanceScreen/g
s/\bCallSelectorTable_F5592E\b/ScreenButton_MetronomeBalanceScreen/g
s/\bFwd_F55826\b/ScreenEnter_MetronomeBalanceScreen_Fwd/g
s/\bsub_F5658C\b/ScreenEnter_MetronomeBalanceScreen/g
s/\bFwd_F5582A\b/ScreenLeave_MetronomeBalanceScreen_Fwd/g
s/\bsub_F565BD\b/LcdKeyRow4_MetronomeBalanceScreen/g
s/\bsub_F565FD\b/LcdKeyRow5_MetronomeBalanceScreen/g
s/\bsub_F5663C\b/ExitKey_MetronomeBalanceScreen/g
s/\bSelectorRoutines_F559AE\b/ButtonTable_CycleRecordScreen/g
s/\bCallSelectorTable_F559AE\b/ScreenButton_CycleRecordScreen/g
s/\bFwd_F5583C\b/ScreenEnter_CycleRecordScreen_Fwd/g
s/\bsub_F5664A\b/ScreenEnter_CycleRecordScreen/g
s/\bFwd_F55840\b/ScreenLeave_CycleRecordScreen_Fwd/g
s/\bsub_F5670C\b/ScreenLeave_CycleRecordScreen/g
s/\bsub_F5672B\b/LcdKeyRow1_CycleRecordScreen/g
s/\bsub_F56752\b/LcdKeyRow2_CycleRecordScreen/g
s/\bsub_F5676B\b/LcdKeyRow3_CycleRecordScreen/g
s/\bsub_F56791\b/LcdKeyRow4_CycleRecordScreen/g
s/\bsub_F5679B\b/LcdKeyRow5_CycleRecordScreen/g
s/\bsub_F567C9\b/ExitKey_CycleRecordScreen/g
s/\bSelectorRoutines_F55A2E\b/ButtonTable_SeqPlayScreen/g
s/\bCallSelectorTable_F55A2E\b/ScreenButton_SeqPlayScreen/g
s/\bFwd_F55856\b/ScreenEnter_SeqPlayScreen_Fwd/g
s/\bsub_F56B95\b/ScreenEnter_SeqPlayScreen/g
s/\bFwd_F5585A\b/ScreenLeave_SeqPlayScreen_Fwd/g
s/\bsub_F56C35\b/ScreenLeave_SeqPlayScreen/g
s/\bsub_F56C57\b/LcdKeyRow1_SeqPlayScreen/g
s/\bsub_F56CD6\b/LcdKeyRow2_SeqPlayScreen/g
s/\bsub_F56D1D\b/LcdKeyRow3_SeqPlayScreen/g
s/\bsub_F56DD9\b/ExitKey_SeqPlayScreen/g
s/\bSelectorRoutines_F55AAE\b/ButtonTable_CyclePlayScreen/g
s/\bCallSelectorTable_F55AAE\b/ScreenButton_CyclePlayScreen/g
s/\bFwd_F5586C\b/ScreenEnter_CyclePlayScreen_Fwd/g
s/\bsub_F56DF1\b/ScreenEnter_CyclePlayScreen/g
s/\bFwd_F55870\b/ScreenLeave_CyclePlayScreen_Fwd/g
s/\bsub_F56E99\b/ScreenLeave_CyclePlayScreen/g
s/\bsub_F56EB8\b/LcdKeyRow2_CyclePlayScreen/g
s/\bsub_F56EC6\b/LcdKeyRow3_CyclePlayScreen/g
s/\bsub_F56ED4\b/LcdKeyRow4_CyclePlayScreen/g
s/\bsub_F56EDE\b/LcdKeyRow5_CyclePlayScreen/g
s/\bsub_F56EF4\b/ExitKey_CyclePlayScreen/g
s/\bSelectorRoutines_F55B2E\b/ButtonTable_CyclePlayEditScreen/g
s/\bCallSelectorTable_F55B2E\b/ScreenButton_CyclePlayEditScreen/g
s/\bFwd_F55882\b/ScreenEnter_CyclePlayEditScreen_Fwd/g
s/\bsub_F57286\b/ScreenEnter_CyclePlayEditScreen/g
s/\bFwd_F55886\b/ScreenLeave_CyclePlayEditScreen_Fwd/g
s/\bsub_F57311\b/ScreenLeave_CyclePlayEditScreen/g
s/\bsub_F57338\b/LcdKeyRow1_CyclePlayEditScreen/g
s/\bsub_F5734A\b/LcdKeyRow2_CyclePlayEditScreen/g
s/\bsub_F57358\b/LcdKeyRow3_CyclePlayEditScreen/g
s/\bFwd_F57366\b/LcdKeyRow4_CyclePlayEditScreen/g
s/\bsub_F5736B\b/ExitKey_CyclePlayEditScreen/g
s/\bSelectorRoutines_F55BAE\b/ButtonTable_CyclePlayEditScreen29/g
s/\bCallSelectorTable_F55BAE\b/ScreenButton_CyclePlayEditScreen29/g
s/\bFwd_F55898\b/ScreenEnter_CyclePlayEditScreen29_Fwd/g
s/\bFwd_F5589C\b/ScreenLeave_CyclePlayEditScreen29_Fwd/g
s/\bFwd_F57419\b/LcdKeyRow1_CyclePlayEditScreen29/g
s/\bFwd_F5741D\b/LcdKeyRow2_CyclePlayEditScreen29/g
s/\bFwd_F57421\b/LcdKeyRow3_CyclePlayEditScreen29/g
s/\bFwd_F57425\b/LcdKeyRow4_CyclePlayEditScreen29/g
s/\bFwd_F5742A\b/ExitKey_CyclePlayEditScreen29/g
