# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FE1907\b/DiskError_SoundAlertAndWait/g
s/\bsub_F556EA\b/PartSound_CopyNameToDrawScratch/g
s/\bsub_F7CCDB\b/SeqJob_StepValueInRange/g
s/\bsub_F0FD2F\b/EffectEditor_PaintBypassIndicator/g
s/\bsub_F55CC8\b/MetronomeBalanceScreen_PaintValue/g
s/\bsub_F5BF8A\b/ModelingPage_PaintFields11And12/g
s/\bsub_F69C03\b/StepRecord_ReturnToTrackKindPage/g
s/\bsub_F6B387\b/StepRecord_AppendBytesToCurrentEntry/g
s/\bsub_F6C935\b/StepRecord_BuildPartParamEvent/g
s/\bsub_F72F2D\b/Smf_ResultToStatusCode/g
s/\bsub_FAA71F\b/ParamB0_PublishField0IfPending/g
s/\bsub_FDA194\b/PartNotes_GetCurrentPartHeldNote/g
s/\bsub_FF490F\b/DiskEntry_GetPointer/g
s/\bsub_F09AF1\b/ToneEditPage_A0_PaintResonatorIcon/g
s/\bsub_F0C291\b/SoundEditCopy_ResolveSelectedSound/g
s/\bsub_F486D9\b/SeqTrackCursors_ResetAll/g
s/\bsub_F4ED84\b/SongMemory_UpdateFreePercent/g
s/\bsub_F531F5\b/DrawbarSettingPage_StepCursorRow/g
s/\bsub_F56DA8\b/SeqMasterTrack_SwitchOff/g
s/\bsub_F5C27D\b/ToneEditPage_A8_PaintField5Switch/g
s/\bsub_F5CBD9\b/ToneEditPage_A0_PaintGroupBrackets/g
s/\bsub_F5D3C6\b/SoundEditNaming_HighlightPaletteChar/g
s/\bsub_F674AD\b/StepRecord_CursorKeyByTrackKind/g
s/\bsub_F103AB\b/DspEffect_StepEqBandGain/g
s/\bsub_F5C39C\b/SoundEdit_PaintSlotOrdinals/g
s/\bsub_F705F7\b/SmfCC_CombineFineTuneDataEntry/g
s/\bsub_F7E770\b/TrackAssignPresets_MoveFieldHighlight/g
s/\bsub_F44367\b/BStore_ResetWorkspaceFields/g
s/\bsub_F55D3D\b/RealtimeRecordScreen_DrawValues/g
s/\bsub_F62CFE\b/BStore_SeekMeasure/g
s/\bsub_F6A20F\b/StepRecord_LoadMeasureBeat/g
s/\bsub_F6BA11\b/TrackCursor_AdvanceBytes/g
s/\bsub_F6D890\b/MsgLine_ControlTypeAndValue/g
s/\bsub_F7EEEF\b/TrackMerge_DrawFieldHighlight/g
s/\bsub_FAAB28\b/ParamImage_LoadFactoryDefaults/g
s/\bsub_FD5E06\b/ToneEditPage_A8_CommitSendOutput/g
s/\bsub_FDA911\b/DspEffect_SendAllToCpu2/g
s/\bsub_FE1C5D\b/DiskLoadScreen_MountAndScanDirectory/g
s/\bsub_FF50E8\b/MidiFile_CountFileList/g
s/\bsub_F09C63\b/SoundEditCopy_DrawSoundName/g
s/\bsub_F440A0\b/BStore_CopyWorkspaceToAllBanks/g
s/\bsub_F4EDC6\b/SeqPlayScreen_StepMeasure/g
s/\bsub_F5323E\b/DrawbarScreen_ToggleRowFlag/g
s/\bsub_F56E66\b/CyclePlayScreen_UpdateFieldBlink/g
s/\bsub_F5C424\b/ToneEditPage_A0_PaintSlotOrdinals/g
s/\bsub_F5CC64\b/SoundEditModelingDriverWaveform_PaintRows/g
s/\bsub_F5D46B\b/SoundEditToneLayerPanning_DrawChordTriggers/g
s/\bsub_F63A59\b/SongEdit_ResetJobFields/g
s/\bsub_F6833E\b/StepRecord_RedrawMeasureRows/g
s/\bsub_F6B76A\b/TrackCursor_StepBack/g
s/\bsub_F44131\b/Seq_ApplySongBeatsPerBar/g
s/\bsub_F63510\b/BStore_TruncateChainAfterBlock/g
s/\bsub_F70E1D\b/SmfCC_PutParamEvent/g
s/\bsub_FF7153\b/L0adSingleS0und_DrawGroupList/g
s/\bsub_F450F7\b/Seq_RewindAfterSongLoad/g
s/\bsub_F55D67\b/SeqScreen_DrawTrackPartLabels/g
s/\bsub_F67400\b/StepRecordSub00_StepValueClamped_Veneer/g
s/\bsub_F6C292\b/StepRecord_SaveCursorToSlot/g
s/\bsub_F6D9AE\b/MsgLine_PutTempoDigits/g
s/\bsub_F911B6\b/ModeScreen_DrawGmModeGlyph/g
s/\bsub_FAAC7D\b/ParamImage_PostRecordAsChangeEvents/g
s/\bsub_FD7D18\b/ToneLayerPan_SplitSideAndAmount/g
s/\bsub_FE152E\b/Medley_NormFileCommand/g
s/\bsub_FF475C\b/MidiFileList_CopyEntryToFileName/g
s/\bsub_FF796C\b/DiskScreen_LeaveOnScreenChange/g
s/\bsub_F09D91\b/SoundEditMenu_PaintOrdinals/g
s/\bsub_F44260\b/BStore_ResetWorkspaceToDefault/g
s/\bsub_F541FF\b/Drawbar_EnterScreenIfMarked/g
s/\bsub_F57433\b/Seq_RestorePlayingTrackMask/g
s/\bsub_F5C549\b/SoundEditLfo_PaintOrdinals/g
s/\bsub_F5CFA4\b/SoundEditLfo_DrawField0RowLine/g
s/\bsub_F5D497\b/SoundEditToneLayerPanning_PaintPanAmounts/g
s/\bsub_F6B134\b/BStore_TruncateAfterSongPosition/g
s/\bsub_F6B9DF\b/BStore_WriteByteAtSongPosition/g
s/\bsub_F4A5AD\b/CycleRecord_SetUpRecordTrack/g
s/\bsub_F65D26\b/TrackAssign_CommitEditedPart/g
s/\bsub_F7C440\b/SongStore_CopyBankSongName/g
s/\bsub_F00AFF\b/TransportA_ResetCountersAndPattern/g
s/\bsub_F5517B\b/EditValue_SetBit/g
s/\bsub_F55D90\b/SeqScreen_QueueTrackRecPlayLabels/g
s/\bsub_F6C2E5\b/StepRecord_RestoreCursorFromSlot/g
s/\bsub_F6DBF9\b/MsgLine_FormatLengthAndPhrasing/g
s/\bsub_FAA43A\b/SoundSel_FromProgramAndBankRegs/g
s/\bsub_FAACC0\b/Queue2C00_Append4DrainWhenFull/g
s/\bsub_FD9D6C\b/ToneCatalogue_StoreFooterReply/g
s/\bsub_FE1BCE\b/BStore_Workspace_StoreParamImage/g
s/\bsub_FF48F0\b/DiskLoad_SetContentTypeFromSelectedEntry/g
s/\bsub_F099C7\b/SoundEditController_PaintDepthAndSwitches/g
s/\bsub_F09DED\b/SoundEditMenu_PaintPanAmounts/g
s/\bsub_F46031\b/CountIn_SetMeasureToFirstBar/g
s/\bsub_F4D690\b/BStore_SeekChainToMeasure/g
s/\bsub_F531DC\b/DrawbarScreen_StepParamAtCursor/g
s/\bsub_F56525\b/Transport_StopWhileRecording/g
s/\bsub_F57443\b/Seq_SavePlayingTrackMask/g
s/\bsub_F5C5A5\b/SoundEditLfo_DrawRowLinks/g
s/\bsub_F5D199\b/SoundEditMemoryWrite_DrawSlotSoundName/g
s/\bsub_F5EBD0\b/BStore_ReadCursorAdvance_Call/g
s/\bsub_F6360E\b/Seq_FindMasterTrack/g
s/\bsub_F662D7\b/SequencerMedley_ClampRangeAfterStep/g
s/\bsub_F69B40\b/StepRecord_AdjustEventByte/g
s/\bsub_F6B1EA\b/StepRecord_ClearMsgLineField/g
s/\bsub_F6C4A5\b/BStore_IsDirEntryUnused/g
