# rename_nakarest_reviewed_v7.sed -- written by scripts/converters/nakarest_reviewed_slices.py
s/\bBitMapOut_DeltaEncode_Type90Final_Data_2\b/PanelTlv_PartResolveRecs_CompanionCol/g
s/\bCtrlPanel_HandleSerialPort_Data\b/CtrlPanel_DialStepByDelta/g
s/\bLswMasterTuning_Data\b/LswMasterTuning_ValueByStep/g
s/\bIvSdpart_ShowHide_Data\b/IvSdpart_PartNumberByRow/g
s/\bMidi_PartToChMappingTable\b/PsMixer_DefaultGridPartRows/g
s/\bCtrlPanel_FuncDispatch_Data\b/GroupBox_EventCaseMap/g
s/\bEffectMode_SetAllLEDs_SetOne_Data\b/LED_AllOnPatternByRow/g
s/\bNakaInst_LM_RightDown\b/NakaInst_LineModeID_EnumTable/g
s/\bPad_AfterStr_No\b/GraphicsRender_PaletteSrc192/g
s/\bAcIndexEdit_DispatchDSP_Data\b/AcIndexEdit_SwitchDirCaseMap/g
s/\bDrawbarBitmapHelper_Data\b/DrawbarBitmap_SliderX/g
s/\bNakaProp_BoolEntry1\b/NakaInst_pFunc_EnumTable/g
s/\bNakaProp_BoolEntry5\b/NakaInst_RectX1_EnumTable/g
s/\bNakaProp_Align_Header\b/NakaInst_TitleID_EnumTable/g
s/\bNakaInst_pUlong_FormatData\b/NakaInst_pUlong_EnumTable/g
s/\bMultiPass_RetryLoop_Data\b/FileIO_TypeProbeOrder/g
s/\bSeqChan_Map_8ch\b/VariScreen_EditSwLayout8/g
s/\bSeqChan_Map_6ch\b/VariScreen_EditSwLayout6/g
s/\bRVari_Select_CheckSameBank_Data\b/RVari_SubItemEditSw/g
s/\bIvSdpart_OK_Data\b/IvSdpart_TopPageViewId/g
s/\bFDemoText_ByteData_VoiceProbeA_Data\b/FDemoText_PartFlagBit/g
s/\bFDemoText_ByteData_LayoutEngine_Data_2\b/FDemoText_NameValueInit/g
s/\bFDemoText_ByteData_LayoutEngine_Data_7\b/FDemoText_ObjValueInit/g
s/\bInitializeCheap_PtrTable_5_EndName\b/Cheap_ResNameTable_36C_EndName/g
s/\bUnregisteredTitle_Data\b/UnregisteredTitle_EmptyName/g
s/\bNakaInst_Sqmixer_Term1\b/Murai_ResNameTable_3A5_EndName/g
s/\bMidiParam_MixerCfgData\b/TrackMixer_Ctl0_EmptyCaption/g
s/\bObjAttr_Empty\b/ObjAttr_EndName/g
s/\bFileIO_GetDiskRecordPtr_Data\b/FileIO_DiskInfoInit_Capacity/g
s/\bValidateAndSearchFile_Str_Empty\b/ValidateAndSearchFile_PathInit/g
s/\bData_VariPad_EA081C\b/Str_Variation5_Empty/g
s/\bData_NakaSep_EA13CA\b/Cheap_FuncNameTable_405_EndName/g
s/\bEffectMode_UpdateBitFlags_CheckCount_Data\b/EffectMode_PresetFieldMap/g
s/\bSndParam_SendDiskMenuEvents_Data\b/CtrlPanel_SwitchRowBit/g
s/\bNoteEvent_LoadSoundGenParams_Data\b/NoteEvent_DefaultPatternSlot/g
s/\bIvSdtecd1Proc_Data\b/Sdtecd1_TypeButtonView/g
s/\bPartMixer_Init_Data_2\b/PartMixer_ColumnPartMap/g
s/\bChangePalette_Impl_Data\b/ChangePalette_WallpaperPalettes/g
s/\bLswScalingType_Data\b/LswScalingType_TypeCodes/g
s/\bIvSdpart_Init_LoadDescriptor_Data\b/IvSdpart_PageViews/g
s/\bNakaProp_CFlagEntry\b/SupportClass_NameValueNames/g
s/\bGraphicsRender_ByteData_Data\b/GraphicsRender_LowBandColorIndex/g
s/\bNakaProp_FontEntry0\b/SupportClass_SwordValueNames/g
s/\bNakaProp_BoolEntry2\b/SupportClass_PPropValueNames/g
s/\bNakaProp_BoolEntry6\b/SupportClass_RectX2ValueNames/g
s/\bNakaProp_Frame_Header\b/SupportClass_BitmapIDValueNames/g
s/\bNakaInst_pUchar_FormatData\b/SupportClass_PUcharValueNames/g
s/\bPsTrackSwitchProc_Data\b/PsTrkSw_SelectStateColor/g
s/\bFDemoText_ByteData_LayoutEngine_PtrTable_3\b/ObjAttr_NameTable/g
s/\bTitleProc_Data\b/TitleProc_EasySetTable/g
s/\bMsaMode_Select_Data\b/MsaMode_EditSwByValue/g
s/\bMidiParamStr1_Empty\b/MidiParamStr1_BlankRow10/g
s/\bFDemoText_ProcessVoiceFlags_CheckBits_Data\b/FDemoText_VoiceActiveBit/g
s/\bFDemoText_ByteData_LayoutEngine_Data_3\b/FDemoText_SongSrcInit/g
s/\bFileIO_InitRecordTable_Data\b/FileIO_DiskInfoInit/g
s/\bInputDialog_Confirm_Data\b/RegisterObject_Str_EmptyName/g
s/\bNameProc_Init_SetPtr_Data\b/NameProc_MakeDump_Str_Empty/g
s/\bNakaInst_pSlong_EmptyStr\b/SupportClass_PSlongValueNamesEndText/g
s/\bDrawbarStrNull_E8638A\b/Murai_ResNameEB_End/g
s/\bFileTypeName_Empty\b/SongAttrName_Empty/g
s/\bFDemoText_RenderTextLine_Data\b/FDemoText_ScreenClipRect/g
s/\bInitRecordTable_CopyLoop_Data\b/FileIO_EmptyFileRecord/g
s/\bCompLoad_DrawItem_Empty_Data\b/CompLoad_Str_EmptyFileName/g
s/\bData_DrumKitPad_EA08D4\b/WP_SectionName_Vari3Blank/g
s/\bNakaInst_CharaList_Pad\b/NakaStr_FontFileBlank/g
s/\bEnumList_HitTest_Data\b/TitleProc_EasySetHold0Tail/g
s/\bGroupBox_HandleStateCompare_Data\b/GroupBox_ModeSwitchGroup/g
s/\bPsMixer_CtlTypeProc3_Data\b/PsMixer_KnobPointerOffsets/g
s/\bIvSdscltyp2Proc_Data\b/Sdscltyp2_KeyWidgetIds/g
s/\bDrawbarBitmapHelper_Data_2\b/Drawbar_LevelBitmapOffsets/g
s/\bSdtecd1_ScrollDown_Lookup_Data\b/Sdtecd1_ValueScreenOrder/g
s/\bIvDrawbar1_LoadVals_Data\b/IvDrawbar1_DrawbarParamIds/g
s/\bNakaProp_FontEntry1\b/SupportClass_UcharValueNames/g
s/\bNakaProp_BoolEntry3\b/SupportClass_ClassIDValueNames/g
s/\bNakaProp_BoolEntry7\b/SupportClass_POINTWValueNames/g
s/\bTest_SRAM_IC21_Data\b/SramTest_IC21Regions/g
s/\bBitMapOut_DeltaEncode_Type90Final_Data\b/PanelMemory_PartResolveTable/g
s/\bNakaProp_VisFlag_Header\b/SupportClass_ViewIDValueNames/g
s/\bChangeWall_Impl_Data\b/ChangeWall_WallpaperTable/g
s/\bSeqChan_Map_4ch\b/EditSw_PageMap4/g
s/\bMidiParamStr2_Empty\b/PartMixer_Ctl11Caption/g
s/\bFDemoText_ByteData_VoiceProbeC_Data\b/FDemoText_FullSendBitByPart/g
s/\bFDemoText_ByteData_LayoutEngine_Data_5\b/FDemoText_ImgSrcBufInit/g
s/\bWPScan_LoopBody_Data\b/WPScan_SlotFlagBits/g
s/\bUnRegisterObject_Data\b/UnRegisterObject_EmptyName/g
s/\bConstFlagProc_GetValue_Set_Data\b/ConstFlagProc_DumpText/g
s/\bNakaInst_TrackID_EmptyStr\b/TrackIDProc_NameListEnd/g
s/\bMidiParamStr1_End\b/MidiParam_Ctl0Caption/g
s/\bImgAttr_Empty\b/FDemoText_SizeColorAttrNamesEnd/g
s/\bSeq_LoadDisplayResource_Str_Empty\b/Seq_LoadDisplayResource_NameBufInit/g
s/\bFilename_TemplateArea\b/FileIO_EmptyEntryName/g
s/\bData_VariPad_EA0814\b/WP_VariationName8_Empty/g
s/\bData_DrumKitPad_EA08D6\b/WP_BankMemName1_Empty/g
s/\bPsMixer_MidiScanOuterLoop_Data\b/PsMixer_RowKindApFuncId/g
s/\bAcMixerVol_PartSelect_DrawIcon_Data\b/AcMixerVol_GroupIconBitmap/g
s/\bClipBlit_Replace_ScanlineLoop_Data\b/ClipBlit_DiscHalfWidth/g
s/\bValidateSigned_LookupTable_Data\b/FileIO_StatusToErrorCode/g
s/\bAcTrackMixerProc_Data\b/TrackMixer_PartCodeToItem/g
s/\bFDemoText_ByteData_LayoutEngine_Data_4\b/FDemoText_FontSizeToFont/g
s/\bDemo_ScanPartLoop_Data\b/Demo_PartBitMask/g
s/\bMemDraw_ParamLoopBody_Data\b/MemDraw_LswIdTable/g
s/\bEnumList_Reset_Data\b/Title_InterruptTimeTicks/g
s/\bScoop_EventLoop_36Entry_Branch3_Data_3\b/TextStyle_NibbleFontTable/g
s/\bNakaProp_FontEntry2\b/NakaInst_slong_EnumTable/g
s/\bNakaProp_BoolEntry4\b/NakaInst_EventID_EnumTable/g
s/\bNakaProp_BoolEntry8\b/NakaInst_PointY_EnumTable/g
s/\bNakaInst_pUword_FormatData\b/NakaInst_pUword_EnumTable/g
s/\bSeqChan_Map_10ch\b/EditSw_SplitMap10/g
s/\bDramTest_IC10IC9_NextChip_Data\b/DramTest_IC10IC9_Regions/g
s/\bEffectMode_DiagSeq_AnimFrame_Data\b/EffectMode_DiagSeq_TitleCycle/g
s/\bRVari_Select_Data\b/RVari_SlotEditSw/g
s/\bPsMixer_CtlTypeProc2_Data\b/PsMixer_MuteApFuncId/g
s/\bMidiParamStr3_Empty\b/TrackMixer_Row10Caption/g
s/\bFDemoText_ByteData_VoiceProbeC_Data_2\b/FDemoText_PartialResendBit/g
s/\bFDemoText_ByteData_LayoutEngine_Data_6\b/FDemoText_ImgAltInit/g
s/\bData_VariPad_EA0818\b/Str_Variation7_Empty/g
s/\bData_VariPad_EA0816\b/Str_Variation8_Empty/g
s/\bUnregisteredMode_Data\b/Mode_UnregisteredName/g
s/\bNaka_ReverbScreen_EmptyStr\b/Kubo_FunctionNameTable_408_EndName/g
s/\bMidiParamStr2_End\b/PartMixer_Row14Caption/g
s/\bImgAttrName_Empty\b/ImgAttr_NameListEnd/g
s/\bUpdateFileEntry_Data\b/UpdateFileEntry_BaseNameInit/g
s/\bPtrTbl_DrumKitNames\b/Str_BankMem0_Empty/g
