# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F4D935\b/BStore_BlockAddrFromIY/g
s/\bsub_F4C811\b/BStore_CompactBlocks/g
s/\bsub_F6452B\b/SongEdit_CheckAllTracksToStartMeasure/g
s/\bsub_F64594\b/SongEdit_CheckFreeBlocksForInsert/g
s/\bsub_F6466E\b/SongEdit_CheckFreeBlocksForCopy/g
s/\bsub_F448C6\b/SeqCycle_CheckOn/g
s/\bsub_F4CB0D\b/BStore_Workspace_CopyToBank/g
s/\bsub_F4CB34\b/BStore_Workspace_CopyFromBank/g
s/\bsub_F4E426\b/SeqTrack_PlayOnWhileStopped/g
s/\bsub_F4E478\b/SeqTrack_SwitchPlayOnWhileRunning/g
s/\bsub_F569FA\b/CycleRecordScreen_BlinkStartAndEndMeasures/g
s/\bsub_F57127\b/CyclePlayScreen_BlinkStartAndEndMeasures/g
s/\bsub_F44903\b/CycleRecord_CheckOnPreviousScreen/g
s/\bsub_F4403C\b/Seq_LocateNowIfPending_Veneer/g
s/\bsub_F44B2D\b/Seq_ResetPositionOnRequest/g
s/\bsub_F44ADA\b/SeqRecord_BeginTakeOnTransportStart/g
s/\bsub_F45761\b/SeqRecord_BeginTake/g
s/\bsub_F451E6\b/SeqRecord_RewindForTake/g
s/\bsub_F452D3\b/SeqTrack_CompletePlayOff/g
s/\bsub_F44E58\b/TimedEvents_QueueRoutingRebuild/g
s/\bsub_F442DA\b/BStore_TrackOutChannel_LoadDefaults/g
s/\bsub_FABD33\b/Seq_PublishPendingParamB0/g
s/\bsub_F36888\b/SysExThirdRegion_LocateElementModellingChunk/g
s/\bsub_F368E0\b/SysExThirdRegion_LocateElementChunk/g
s/\bsub_F36B94\b/SysExThirdRegion_LocateDrumEntryChunk/g
s/\bsub_F37DB4\b/SysExThirdRegion_BuildReplyHeader/g
s/\bsub_F458EA\b/Transport_PromoteStartsToRunning/g
s/\bsub_F458FE\b/SeqRecord_TerminateTrackAtCursor/g
s/\bsub_F45942\b/SeqRecord_SetRecordedTracksPlaying/g
s/\bsub_F459D9\b/Seq_RebuildPlayingSet/g
s/\bsub_F45B6E\b/SeqTrack_QueueNoteOffAndBendCentre/g
s/\bsub_F45E5F\b/SeqCycle_CountDownDeferredAction/g
s/\bsub_F45E76\b/SeqCycle_RunDueDeferredAction/g
s/\bsub_F48647\b/BStore_StepCursorBackToLeadByte/g
s/\bsub_F493FA\b/UserSoundBank_RemoteGroupAddr/g
s/\bsub_F49800\b/SeqRecord_LoadTakeCursor_Veneer/g
s/\bsub_F49802\b/SeqRecord_SaveTakeCursor_Veneer/g
s/\bsub_F49806\b/SeqRecord_DrainEventRingAtTakeEnd/g
s/\bsub_F4A6FF\b/CycleRecord_PlayTrackFromTakeChain2/g
s/\bsub_F4A756\b/CycleRecord_CopyCycleRangeToTakeChain2/g
s/\bsub_F4AB8A\b/CycleRecord_AllocRecordChain/g
s/\bsub_F4B104\b/CycleRecord_CommitTake/g
s/\bsub_F4C6E0\b/CreatorSelectController_CopyNameLabels/g
s/\bsub_F4C804\b/BStore_RebuildFreeListAfterLoad/g
s/\bsub_F4D002\b/BStore_ExtendChainAtCursor_B/g
s/\bsub_F4D346\b/BStore_ClearTrack/g
s/\bsub_F4E1B6\b/SeqRecord_SelectArmedTrackPart/g
s/\bsub_F4E259\b/SeqRecord_ArmTrack/g
s/\bsub_F4E4C4\b/StepRecordPartSelect_OnTrackKey/g
s/\bsub_F4E4F6\b/TrackClear_OnTrackKey/g
s/\bsub_F4E545\b/Seq_RequestRewindIfIdle/g
s/\bsub_F4EC2F\b/RealtimeRecord_ArmAtFirstMeasure/g
s/\bsub_F4ED10\b/Seq_DelayedLocateToMeasure/g
s/\bsub_F55E20\b/SeqScreen_PaintActiveTrackHighlights/g
s/\bsub_F5686B\b/CycleRecordScreen_BlinkStartMeasureReadout/g
s/\bsub_F56898\b/CycleRecordScreen_BlinkEndMeasureReadout/g
s/\bsub_F56F96\b/CyclePlayScreen_BlinkStartMeasureReadout/g
s/\bsub_F56FC3\b/CyclePlayScreen_BlinkEndMeasureReadout/g
s/\bsub_F5DB97\b/Quantize_Track/g
s/\bsub_F5E570\b/SongEdit_DeleteMeasuresFromTrack/g
s/\bsub_F5E83A\b/MeasureErase_EraseTrack/g
s/\bsub_F5EE9A\b/MeasureInsert_InsertToTrack/g
s/\bsub_F5F02C\b/MeasureInsert_InsertWithinTrack/g
s/\bsub_F5F476\b/SongEdit_CopyMeasuresToTrack/g
s/\bsub_F5FB04\b/SongEdit_CopyMeasuresWithinTrack/g
s/\bsub_F60012\b/TrackMerge_Execute/g
s/\bsub_F60598\b/Vel0cityChange_Execute/g
s/\bsub_F6079A\b/SongEdit_ClearTrack_Call/g
s/\bsub_F60B4E\b/Transp0se_Execute/g
s/\bsub_F60D3E\b/N0teChange_Execute/g
s/\bsub_F60F4F\b/BStore_EmptyBank/g
s/\bsub_F610E3\b/SongClear_ResetAllBanks/g
s/\bsub_F6119A\b/S0ngC0py_Execute/g
s/\bsub_F61907\b/S0ngC0py_ClearDestTrack/g
s/\bsub_F61A16\b/AdvanceDelay_Execute/g
s/\bsub_F62C05\b/SongGmFlag_OnEventPassB_Veneer/g
s/\bsub_F6306A\b/BStore_CopyRangeBackward/g
s/\bsub_F63317\b/BStore_MovePosForward/g
s/\bsub_F63383\b/BStore_MovePosBackward/g
s/\bsub_F6382B\b/BStore_TimeSigAdvanceOneMeasure/g
s/\bsub_F63C41\b/BStore_ApplyTrackPartChange/g
s/\bsub_F647DD\b/BStore_BlocksNeededToGrow/g
s/\bsub_F64838\b/BStore_BlocksFreedByShrink/g
s/\bsub_F64B1B\b/BStore_LoadSongFromCurrentBank/g
s/\bsub_F65000\b/SongEdit_SaveTimeSigOfDeletedMeasures/g
s/\bsub_F65003\b/SongEdit_InsertTimeSigsForMeasureInsert/g
s/\bsub_F65006\b/SongEdit_InsertTimeSigsForMeasureCopy/g
s/\bsub_F65009\b/SongEdit_ReinsertTimeSigAfterDelete/g
s/\bsub_F6657A\b/AfterT0uchSetting_SetRecordEnable/g
s/\bsub_F66668\b/TrackAssignPresets_ApplyPreset/g
s/\bsub_F67404\b/StepRecordKind3Sub12_ButtonDispatch_Veneer/g
s/\bsub_F67408\b/StepRecordKind3Sub13_ButtonDispatch_Veneer/g
s/\bsub_F6740C\b/StepRecord_CursorForward_Veneer/g
s/\bsub_F67438\b/TrackCursor_StepOneEvent_Veneer/g
s/\bsub_F67448\b/StepRecord_RepaintThenMsgLineControl_Veneer/g
s/\bsub_F6746C\b/StepRecord_ReadScanEvent_Veneer/g
s/\bsub_F67479\b/BStore_WriteBytesAtSongPosition_Call/g
s/\bsub_F678C6\b/StepRecordSub00_StepValueClamped/g
s/\bsub_F6820F\b/StepRecord_WriteEventByte/g
s/\bsub_F68234\b/StepRecord_WriteEventByteSplitBit7/g
s/\bsub_F68354\b/StepRecord_BuildPrevMeasureRow/g
s/\bsub_F68473\b/StepRecord_BuildNextMeasureRow/g
s/\bsub_F684FA\b/StepRecord_TimeSigFromCurrentEntry/g
s/\bsub_F68504\b/StepRecord_SetRowEventFlags/g
s/\bsub_F6857E\b/StepRecord_BlankCurrentRowText/g
s/\bsub_F6079E\b/SongEdit_ClearTrack/g
