# rename_dsp_param_formats.sed -- written by scripts/tools/name_dsp_param_value_formats.py
# the DSP parameter value formatter (FormatParamValueStr) and its value-text tables, named by the
# parameter ids that select them (derived and asserted by that script).
s/\bEqualizer_CopyFixedString_Str_Blank5\b/DspParamFmt_BlankText/g
s/\bEqualizer_FormatDispatch_CaseTable\b/DspParamFmt_CaseTable/g
s/\bEqualizer_FormatDispatch_Case12\b/DspParamFmt_Signed/g
s/\bEqualizer_FormatDispatch_Case14\b/DspParamFmt_SlowFast/g
s/\bEqualizer_FormatDispatch_Case16\b/DspParamFmt_WindTime/g
s/\bEqualizer_FormatDispatch_Case17\b/DspParamFmt_OscSpeed/g
s/\bEqualizer_FormatDispatch_Case11\b/DspParamFmt_EqGain/g
s/\bEqualizer_FormatDispatch_Case10\b/DspParamFmt_EqQ/g
s/\bEqualizer_FormatDispatch_Table\b/DspParamFmt_CaseByParamId/g
s/\bEqualizer_FormatDispatch_Case2\b/DspParamFmt_ReverbTime/g
s/\bEqualizer_FormatDispatch_Case3\b/DspParamFmt_HighDampGain/g
s/\bEqualizer_FormatDispatch_Case8\b/DspParamFmt_GateTime/g
s/\bEqualizer_FormatDefault_Data_2\b/DspValueText_ReleaseRate/g
s/\bEqualizer_FormatDispatch_Case7\b/DspParamFmt_ReleaseRate/g
s/\bEqualizer_FormatDefault_Data_3\b/DspValueText_AttackRate/g
s/\bEqualizer_FormatDispatch_Case6\b/DspParamFmt_AttackRate/g
s/\bEqualizer_FormatDefault_Data_4\b/DspValueText_SensTime/g
s/\bEqualizer_FormatDispatch_Case5\b/DspParamFmt_SensTime/g
s/\bEqualizer_FormatDefault_Data_5\b/DspValueText_Pitch/g
s/\bEqualizer_FormatDispatch_Case4\b/DspParamFmt_Pitch/g
s/\bEqualizer_FormatDefault_Data_6\b/DspValueText_SlowFast/g
s/\bEqualizer_FormatDefault_Data_7\b/DspValueText_WindTime/g
s/\bEqualizer_FormatDefault_Data_8\b/DspValueText_RotorSpeed/g
s/\bEqualizer_FormatDispatch_Case9\b/DspParamFmt_Waveform/g
s/\bEqualizer_FormatDefault_Data\b/DspValueText_GateTime/g
s/\bEqualizer_FormatDefault_Str\b/DspParamFmt_NegativeFmt/g
s/\bFormatParamStr_CopyEnumName\b/DspParamFmt_CopyValueText/g
s/\bEqualizer_PadSpaceAndReturn\b/DspParamFmt_PadAndReturn/g
s/\bEqFormat_PositiveValue_Data\b/DspValueText_HighDampGain/g
s/\bEntertainerGridCheck_Data_2\b/DspValueText_EqGain/g
s/\bEntertainerGridCheck_Data_3\b/DspValueText_EqFreq/g
s/\bEqFormat_NegativeValue_Str\b/DspParamFmt_PositiveFmt/g
s/\bEqFormat_PositiveValue_Str\b/DspParamFmt_ZeroFmt/g
s/\bNakaData_WidgetDescriptors\b/DspValueText_ReverbTime/g
s/\bEqualizer_FormatCases_Data\b/DspValueText_EqQ/g
s/\bEqualizer_CopyFixedString\b/DspParamFmt_Blank/g
s/\bEqualizer_FormatDispatch\b/DspParamFmt_BySwitch/g
s/\bFormatParamString_Data_2\b/DspValueText_Waveform/g
s/\bFormatParamString_Data_3\b/DspValueText_LfoSpeed/g
s/\bEqualizer_FormatDefault\b/DspParamFmt_RotorSpeed/g
s/\bEqFormat_NegativeValue\b/DspParamFmt_SignedNonNegative/g
s/\bEqFormat_PositiveValue\b/DspParamFmt_SignedZero/g
s/\bFormatParamString_Data\b/DspValueText_OscSpeed/g
s/\bPrepareAudioParam_Str\b/DspParamFmt_DecimalFmt/g
s/\bDspValueText_0000_Pad\b/DspValueText_ReverbTime_Pad/g
s/\bDspValueText_01F4_Pad\b/DspValueText_HighDampGain_Pad/g
s/\bDspValueText_0272_Pad\b/DspValueText_GateTime_Pad/g
s/\bDspValueText_0466_Pad\b/DspValueText_ReleaseRate_Pad/g
s/\bDspValueText_065A_Pad\b/DspValueText_AttackRate_Pad/g
s/\bDspValueText_084E_Pad\b/DspValueText_SensTime_Pad/g
s/\bDspValueText_0A42_Pad\b/DspValueText_Pitch_Pad/g
s/\bDspValueText_0BB0_Pad\b/DspValueText_SlowFast_Pad/g
s/\bDspValueText_0BBA_Pad\b/DspValueText_WindTime_Pad/g
s/\bDspValueText_0DAE_Pad\b/DspValueText_RotorSpeed_Pad/g
s/\bDspValueText_0FA2_Pad\b/DspValueText_OscSpeed_Pad/g
s/\bDspValueText_1196_Pad\b/DspValueText_Waveform_Pad/g
s/\bDspValueText_11A6_Pad\b/DspValueText_LfoSpeed_Pad/g
s/\bDspValueText_139A_Pad\b/DspValueText_EqGain_Pad/g
s/\bDspValueText_1490_Pad\b/DspValueText_EqQ_Pad/g
s/\bEqualizer_FormatCases\b/DspParamFmt_EqFreq/g
s/\bDspValueText_1530_Pad\b/DspValueText_EqFreq_Pad/g
s/\bPrepareAudioParam\b/DspParamFmt_Decimal/g
s/\bDspValueText_0000\b/DspValueText_ReverbTime/g
s/\bDspValueText_01F4\b/DspValueText_HighDampGain/g
s/\bDspValueText_0272\b/DspValueText_GateTime/g
s/\bDspValueText_0466\b/DspValueText_ReleaseRate/g
s/\bDspValueText_065A\b/DspValueText_AttackRate/g
s/\bDspValueText_084E\b/DspValueText_SensTime/g
s/\bDspValueText_0A42\b/DspValueText_Pitch/g
s/\bDspValueText_0BB0\b/DspValueText_SlowFast/g
s/\bDspValueText_0BBA\b/DspValueText_WindTime/g
s/\bDspValueText_0DAE\b/DspValueText_RotorSpeed/g
s/\bDspValueText_0FA2\b/DspValueText_OscSpeed/g
s/\bDspValueText_1196\b/DspValueText_Waveform/g
s/\bFormatParamString\b/DspParamFmt_LfoSpeed/g
s/\bDspValueText_11A6\b/DspValueText_LfoSpeed/g
s/\bDspValueText_139A\b/DspValueText_EqGain/g
s/\bDspValueText_1490\b/DspValueText_EqQ/g
s/\bDspValueText_1530\b/DspValueText_EqFreq/g
s/\bSendAudioCommand\b/DspParamFmt_Sprintf/g
