#!/usr/bin/env python3
"""rename_wsa1_directory_slots.py -- routine-directory slots `T_F4xxxx` take the name of the routine they jump to.

QUESTION THIS ANSWERS / JOB IT DOES
  prom_b's routine directory is a run of `T_<ADDR>: jp <routine>` thunks that both CPUs' code
  calls (`call T_F400D4`).  Where the slot's target has a real name, the house convention is
  `T_<Target>` (T_DisplayList_Run, T_Blink_SetEnable); on 2026-10-03, 243 slots still carried
  their address while their target was named (`T_F400D4: jp ScreenLeave_GateArrayCheck`).  Each
  becomes `T_<Target>` (unique with _2, ...).  Targets that are placeholders (`sub_`, numbers) or
  whose name embeds an address (`T_F42348_Nop`, named after the slot itself) are left.  Renames
  go through scripts/renaming/rename_wsa1_directory_slots.sed over wsa1/**/*.s and the wsa1
  notes generators.  No byte changes: `make gate-all`.

USAGE
  python3 scripts/renaming/rename_wsa1_directory_slots.py [--apply]
"""
import argparse
import glob
import os
import re
import subprocess
import sys

REPO = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True,
                      text=True).stdout.strip() or "."


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    files = sorted(glob.glob(os.path.join(REPO, "wsa1", "**", "*.s"), recursive=True))
    taken, ren = set(), {}
    slots = []
    for f in files:
        for l in open(f, "rb").read().decode("latin-1").split("\n"):
            m = re.match(r'^([A-Za-z_][\w.$]*):', l)
            if m:
                taken.add(m.group(1))
            m = re.match(r'^(T_F[0-9A-F]{5}):\s*(jp|jrl|jr)\s+(\S+)', l.split(";")[0])
            if m:
                slots.append((m.group(1), m.group(3)))
    for slot, tgt in slots:
        if re.match(r'^(sub_|0x|loc_)', tgt) or re.search(r'[0-9A-F]{6}', tgt) or not re.match(r'^[A-Za-z_]\w*$', tgt):
            continue
        base = "T_" + tgt
        nm, k = base, 1
        while nm in taken:
            k += 1
            nm = "%s_%d" % (base, k)
        taken.add(nm)
        ren[slot] = nm
    print("%d slots, %d renamed%s" % (len(slots), len(ren), "" if a.apply else " (dry run)"))
    if a.apply and ren:
        sed = os.path.join(REPO, "scripts", "renaming", "rename_wsa1_directory_slots.sed")
        with open(sed, "w") as s:
            s.write("# generated by scripts/renaming/rename_wsa1_directory_slots.py: T_<ADDR> slots -> T_<Target>.\n")
            for old, new in sorted(ren.items()):
                s.write("s/\\b%s\\b/%s/g\n" % (old, new))
        subprocess.run(["sed", "-i", "-f", sed] + files, check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
