# v9: part sound-parameter descriptors named by part tag and field (gen_sndparam_desc_names.py;
# v10's map, each alias checked against the key at its address in this ROM).
s/\bSndParam_Part00_ChorusSend\b/SndParam_Part00_DspEffect/g
s/\bSndParam_Part01_ChorusSend\b/SndParam_Part01_DspEffect/g
s/\bSndParam_Part02_ChorusSend\b/SndParam_Part02_DspEffect/g
s/\bSndParam_Part03_ChorusSend\b/SndParam_Part03_DspEffect/g
s/\bSndParam_Part04_ChorusSend\b/SndParam_Part04_DspEffect/g
s/\bSndParam_Part05_ChorusSend\b/SndParam_Part05_DspEffect/g
s/\bSndParam_Part06_ChorusSend\b/SndParam_Part06_DspEffect/g
s/\bSndParam_Part07_ChorusSend\b/SndParam_Part07_DspEffect/g
s/\bSndParam_Part08_ChorusSend\b/SndParam_Part08_DspEffect/g
s/\bSndParam_Part09_ChorusSend\b/SndParam_Part09_DspEffect/g
s/\bSndParam_Part0A_ChorusSend\b/SndParam_Part0A_DspEffect/g
s/\bSndParam_Part0B_ChorusSend\b/SndParam_Part0B_DspEffect/g
s/\bSndParam_Part0C_ChorusSend\b/SndParam_Part0C_DspEffect/g
s/\bSndParam_Part0D_ChorusSend\b/SndParam_Part0D_DspEffect/g
s/\bSndParam_Part0E_ChorusSend\b/SndParam_Part0E_DspEffect/g
s/\bSndParam_Part0F_ChorusSend\b/SndParam_Part0F_DspEffect/g
s/\bSndParam_Part10_ChorusSend\b/SndParam_Part10_DspEffect/g
s/\bSndParam_Part11_ChorusSend\b/SndParam_Part11_DspEffect/g
s/\bSndParam_Part12_ChorusSend\b/SndParam_Part12_DspEffect/g
s/\bSndParam_Part13_ChorusSend\b/SndParam_Part13_DspEffect/g
s/\bSndParam_Part14_ChorusSend\b/SndParam_Part14_DspEffect/g
s/\bSndParam_Part15_ChorusSend\b/SndParam_Part15_DspEffect/g
s/\bSndParam_Part16_ChorusSend\b/SndParam_Part16_DspEffect/g
s/\bSndParam_Part17_ChorusSend\b/SndParam_Part17_DspEffect/g
s/\bSndParam_Part18_ChorusSend\b/SndParam_Part18_DspEffect/g
s/\bVoiceParamEx_Entry_019\b/SndParam_Part01_BendRange/g
s/\bVoiceParamEx_Entry_020\b/SndParam_Part01_Tuning/g
s/\bVoiceParamEx_Entry_021\b/SndParam_Part01_KeyShift/g
s/\bVoiceParamEx_Entry_052\b/SndParam_Part02_BendRange/g
s/\bVoiceParamEx_Entry_053\b/SndParam_Part02_Tuning/g
s/\bVoiceParamEx_Entry_054\b/SndParam_Part02_KeyShift/g
s/\bVoiceParamEx_Entry_085\b/SndParam_Part03_BendRange/g
s/\bExtPartParam_Entry_238\b/SndParam_Part11_BendRange/g
s/\bExtPartParam_Entry_239\b/SndParam_Part11_Tuning/g
s/\bExtPartParam_Entry_240\b/SndParam_Part11_KeyShift/g
s/\bExtPartParam_Entry_255\b/SndParam_Part12_BendRange/g
s/\bExtPartParam_Entry_256\b/SndParam_Part12_Tuning/g
s/\bExtPartParam_Entry_257\b/SndParam_Part12_KeyShift/g
s/\bExtPartParam_Entry_272\b/SndParam_Part13_BendRange/g
s/\bExtPartParam_Entry_273\b/SndParam_Part13_Tuning/g
s/\bExtPartParam_Entry_274\b/SndParam_Part13_KeyShift/g
s/\bExtPartParam_Entry_289\b/SndParam_Part14_BendRange/g
s/\bExtPartParam_Entry_290\b/SndParam_Part14_Tuning/g
s/\bExtPartParam_Entry_291\b/SndParam_Part14_KeyShift/g
s/\bExtPartParam_Entry_306\b/SndParam_Part15_BendRange/g
s/\bExtPartParam_Entry_307\b/SndParam_Part15_Tuning/g
s/\bExtPartParam_Entry_308\b/SndParam_Part15_KeyShift/g
s/\bExtPartParam_Entry_323\b/SndParam_Part16_BendRange/g
s/\bExtPartParam_Entry_324\b/SndParam_Part16_Tuning/g
s/\bExtPartParam_Entry_325\b/SndParam_Part16_KeyShift/g
s/\bExtPartParam_Entry_340\b/SndParam_Part17_BendRange/g
s/\bExtPartParam_Entry_341\b/SndParam_Part17_Tuning/g
s/\bExtPartParam_Entry_342\b/SndParam_Part17_KeyShift/g
s/\bExtPartParam_Entry_357\b/SndParam_Part18_BendRange/g
s/\bExtPartParam_Entry_358\b/SndParam_Part18_Tuning/g
s/\bExtPartParam_Entry_359\b/SndParam_Part18_KeyShift/g
s/\bMidiChParam_Entry_098\b/SndParam_Part00_BendRange/g
s/\bMidiChParam_Entry_099\b/SndParam_Part00_Tuning/g
s/\bMidiChParam_Entry_100\b/SndParam_Part00_KeyShift/g
s/\bPartParam_Entry_001\b/SndParam_Part03_Tuning/g
s/\bPartParam_Entry_002\b/SndParam_Part03_KeyShift/g
s/\bPartParam_Entry_017\b/SndParam_Part04_BendRange/g
s/\bPartParam_Entry_018\b/SndParam_Part04_Tuning/g
s/\bPartParam_Entry_019\b/SndParam_Part04_KeyShift/g
s/\bPartParam_Entry_034\b/SndParam_Part05_BendRange/g
s/\bPartParam_Entry_035\b/SndParam_Part05_Tuning/g
s/\bPartParam_Entry_036\b/SndParam_Part05_KeyShift/g
s/\bPartParam_Entry_051\b/SndParam_Part06_BendRange/g
s/\bPartParam_Entry_052\b/SndParam_Part06_Tuning/g
s/\bPartParam_Entry_053\b/SndParam_Part06_KeyShift/g
s/\bPartParam_Entry_068\b/SndParam_Part07_BendRange/g
s/\bPartParam_Entry_069\b/SndParam_Part07_Tuning/g
s/\bPartParam_Entry_070\b/SndParam_Part07_KeyShift/g
s/\bPartParam_Entry_085\b/SndParam_Part08_BendRange/g
s/\bPartParam_Entry_086\b/SndParam_Part08_Tuning/g
s/\bPartParam_Entry_087\b/SndParam_Part08_KeyShift/g
s/\bPartParam_Entry_102\b/SndParam_Part09_BendRange/g
s/\bPartParam_Entry_103\b/SndParam_Part09_Tuning/g
s/\bPartParam_Entry_104\b/SndParam_Part09_KeyShift/g
s/\bPartParam_Entry_119\b/SndParam_Part0A_BendRange/g
s/\bPartParam_Entry_120\b/SndParam_Part0A_Tuning/g
s/\bPartParam_Entry_121\b/SndParam_Part0A_KeyShift/g
s/\bPartParam_Entry_136\b/SndParam_Part0B_BendRange/g
s/\bPartParam_Entry_137\b/SndParam_Part0B_Tuning/g
s/\bPartParam_Entry_138\b/SndParam_Part0B_KeyShift/g
s/\bPartParam_Entry_153\b/SndParam_Part0C_BendRange/g
s/\bPartParam_Entry_154\b/SndParam_Part0C_Tuning/g
s/\bPartParam_Entry_155\b/SndParam_Part0C_KeyShift/g
s/\bPartParam_Entry_170\b/SndParam_Part0D_BendRange/g
s/\bPartParam_Entry_171\b/SndParam_Part0D_Tuning/g
s/\bPartParam_Entry_172\b/SndParam_Part0D_KeyShift/g
s/\bPartParam_Entry_187\b/SndParam_Part0E_BendRange/g
s/\bPartParam_Entry_188\b/SndParam_Part0E_Tuning/g
s/\bPartParam_Entry_189\b/SndParam_Part0E_KeyShift/g
s/\bPartParam_Entry_204\b/SndParam_Part0F_BendRange/g
s/\bPartParam_Entry_205\b/SndParam_Part0F_Tuning/g
s/\bPartParam_Entry_206\b/SndParam_Part0F_KeyShift/g
s/\bPartParam_Entry_221\b/SndParam_Part10_BendRange/g
s/\bPartParam_Entry_222\b/SndParam_Part10_Tuning/g
s/\bPartParam_Entry_223\b/SndParam_Part10_KeyShift/g
