#!/usr/bin/env python3
"""Rename LABEL_* to semantic names in region E1C168-E1E332.
Uses binary I/O to handle encoding safely.

This region is almost entirely display string data tables for the
Composer, Sequencer, MSP (Music Style Pattern), APC, and related
screens. Labels are strings used to build on-screen menus/displays.
"""
import os, re

RENAMES = [
    # --- Composer NCP (Notation Copy) / CP screen string tables ---
    # These are aligned_string entries in a pointer table ending at E1C1EC
    ('LABEL_E1C168', 'StrCmpCpFVari_Empty1',    'Composer CP-F Variation: empty slot 1'),
    ('LABEL_E1C16A', 'StrCmpCpFVari_Empty2',    'Composer CP-F Variation: empty slot 2'),
    # E1C16C already named CmpCpFVari (aligned_string "CmpCpFVari") - but still LABEL_
    ('LABEL_E1C16C', 'StrCmpCpFVari',            'Composer CP-F Variation screen string'),
    ('LABEL_E1C178', 'StrCmpCpFGrp',             'Composer CP-F Group screen string'),
    ('LABEL_E1C182', 'StrCmpCpFGrp_Empty1',      'Composer CP-F Group: empty slot 1'),
    ('LABEL_E1C184', 'StrCmpCpFGrp_Empty2',      'Composer CP-F Group: empty slot 2'),
    ('LABEL_E1C186', 'StrCmpCpTPtn',             'Composer CP-T Pattern screen string'),
    ('LABEL_E1C190', 'StrCmpCpTMem',             'Composer CP-T Memory screen string'),
    ('LABEL_E1C19A', 'StrCmpCpTMem_Empty1',      'Composer CP-T Memory: empty slot 1'),
    ('LABEL_E1C19C', 'StrCmpCpTMem_Empty2',      'Composer CP-T Memory: empty slot 2'),
    ('LABEL_E1C19E', 'StrCmpCpTMem_Empty3',      'Composer CP-T Memory: empty slot 3'),
    ('LABEL_E1C1A0', 'StrCmpCpTMem_Empty4',      'Composer CP-T Memory: empty slot 4'),
    ('LABEL_E1C1A2', 'StrCmpCpTMem_Empty5',      'Composer CP-T Memory: empty slot 5'),
    ('LABEL_E1C1A4', 'StrCmpCpTMem_Empty6',      'Composer CP-T Memory: empty slot 6'),
    ('LABEL_E1C1A6', 'StrCmpCpTMem_Empty7',      'Composer CP-T Memory: empty slot 7'),
    ('LABEL_E1C1A8', 'StrCmpCpFPtn',             'Composer CP-F Pattern screen string'),
    ('LABEL_E1C1B2', 'StrCmpCpFPtn_Empty1',      'Composer CP-F Pattern: empty slot 1'),
    ('LABEL_E1C1B4', 'StrCmpCpFPtn_Empty2',      'Composer CP-F Pattern: empty slot 2'),
    ('LABEL_E1C1B6', 'StrCmpCpFPtn_Empty3',      'Composer CP-F Pattern: empty slot 3'),
    ('LABEL_E1C1B8', 'StrCmpCpFPtn_Empty4',      'Composer CP-F Pattern: empty slot 4'),
    ('LABEL_E1C1BA', 'StrCmpCpFPtn_Empty5',      'Composer CP-F Pattern: empty slot 5'),
    ('LABEL_E1C1BC', 'StrCmpCpFPtn_Empty6',      'Composer CP-F Pattern: empty slot 6'),
    ('LABEL_E1C1BE', 'StrCmpCpFPtn_Empty7',      'Composer CP-F Pattern: empty slot 7'),
    ('LABEL_E1C1C0', 'StrCmpCpFPtn_Empty8',      'Composer CP-F Pattern: empty slot 8'),
    ('LABEL_E1C1C2', 'StrCmpCpFPtn_Empty9',      'Composer CP-F Pattern: empty slot 9'),
    ('LABEL_E1C1C4', 'StrCmpCpFPtn_EmptyA',      'Composer CP-F Pattern: empty slot 10'),
    ('LABEL_E1C1C6', 'StrCmpCpFPtn_EmptyB',      'Composer CP-F Pattern: empty slot 11'),
    ('LABEL_E1C1C8', 'StrCmpCpFPtn_EmptyC',      'Composer CP-F Pattern: empty slot 12'),
    ('LABEL_E1C1CA', 'StrCmpCpFPtn_EmptyD',      'Composer CP-F Pattern: empty slot 13'),
    ('LABEL_E1C1CC', 'StrCmpNcpTitmSw',          'Composer NCP title item switch string'),
    ('LABEL_E1C1DA', 'StrCmpNcpTitmSw_Empty',    'Composer NCP title item switch: empty'),
    ('LABEL_E1C1DC', 'StrCmpNcpFitmSw',          'Composer NCP from-item switch string'),
    ('LABEL_E1C1EA', 'StrCmpNcpFitmSw_Empty',    'Composer NCP from-item switch: empty'),
    ('LABEL_E1C1EC', 'StrCmpNcpScreen',          'Composer NCP screen title string'),

    # --- S2c (Song-to-Composer) screen string pointer table ---
    ('LABEL_E1C1FA', 'PtrTbl_S2cScreenStrs',     'Pointer table: Song-to-Composer screen strings'),
    ('LABEL_E1C292', 'StrS2cGrid_Empty1',         'S2c Grid: empty slot 1'),
    ('LABEL_E1C294', 'StrS2cGrid_Empty2',         'S2c Grid: empty slot 2'),
    ('LABEL_E1C296', 'StrS2cGrid_Empty3',         'S2c Grid: empty slot 3'),
    ('LABEL_E1C298', 'StrS2cGrid_Empty4',         'S2c Grid: empty slot 4'),
    ('LABEL_E1C29A', 'StrS2cGrid',                'S2c Grid screen string'),
    ('LABEL_E1C2A2', 'StrS2cLmeas_Empty',         'S2c Last-measure: empty'),
    ('LABEL_E1C2A4', 'StrS2cLmeas',               'S2c Last-measure screen string'),
    ('LABEL_E1C2AE', 'StrS2cMemNo',               'S2c Memory number screen string'),
    ('LABEL_E1C2B8', 'StrS2cSeqSongNo',           'S2c Sequencer song number screen string'),
    ('LABEL_E1C2C6', 'StrS2cFmeas',               'S2c From-measure screen string'),
    ('LABEL_E1C2D0', 'StrS2cFmeas_Empty1',        'S2c From-measure: empty slot 1'),
    ('LABEL_E1C2D2', 'StrS2cFmeas_Empty2',        'S2c From-measure: empty slot 2'),
    ('LABEL_E1C2D4', 'StrS2cFmeas_Empty3',        'S2c From-measure: empty slot 3'),
    ('LABEL_E1C2D6', 'StrS2cTrans',               'S2c Transpose screen string'),
    ('LABEL_E1C2E0', 'StrS2cTrans_Empty1',        'S2c Transpose: empty slot 1'),
    ('LABEL_E1C2E2', 'StrS2cTrans_Empty2',        'S2c Transpose: empty slot 2'),
    ('LABEL_E1C2E4', 'StrS2cTrans_Empty3',        'S2c Transpose: empty slot 3'),
    ('LABEL_E1C2E6', 'StrS2cTrans_Empty4',        'S2c Transpose: empty slot 4'),
    ('LABEL_E1C2E8', 'StrS2cTrans_Empty5',        'S2c Transpose: empty slot 5'),
    ('LABEL_E1C2EA', 'StrS2cTrans_Empty6',        'S2c Transpose: empty slot 6'),
    ('LABEL_E1C2EC', 'StrS2cTrans_Empty7',        'S2c Transpose: empty slot 7'),
    ('LABEL_E1C2EE', 'StrS2cTrans_Empty8',        'S2c Transpose: empty slot 8'),
    ('LABEL_E1C2F0', 'StrS2cTrans_Empty9',        'S2c Transpose: empty slot 9'),
    ('LABEL_E1C2F2', 'StrS2cTrans_EmptyA',        'S2c Transpose: empty slot 10'),
    ('LABEL_E1C2F4', 'StrS2cTrans_EmptyB',        'S2c Transpose: empty slot 11'),
    ('LABEL_E1C2F6', 'StrS2cTrans_EmptyC',        'S2c Transpose: empty slot 12'),
    ('LABEL_E1C2F8', 'StrS2cTrans_EmptyD',        'S2c Transpose: empty slot 13'),
    ('LABEL_E1C2FA', 'StrS2cTrans_EmptyE',        'S2c Transpose: empty slot 14'),
    ('LABEL_E1C2FC', 'StrS2cTrans_EmptyF',        'S2c Transpose: empty slot 15'),
    ('LABEL_E1C2FE', 'StrS2cTrans_Empty10',       'S2c Transpose: empty slot 16'),
    ('LABEL_E1C300', 'StrS2cTrans_Empty11',       'S2c Transpose: empty slot 17'),
    ('LABEL_E1C302', 'StrS2cTrans_Empty12',       'S2c Transpose: empty slot 18'),
    ('LABEL_E1C304', 'StrS2cTrans_Empty13',       'S2c Transpose: empty slot 19'),
    ('LABEL_E1C306', 'StrS2cTrans_Empty14',       'S2c Transpose: empty slot 20'),
    ('LABEL_E1C308', 'StrS2cTrans_Empty15',       'S2c Transpose: empty slot 21'),
    ('LABEL_E1C30A', 'StrS2cTrans_Empty16',       'S2c Transpose: empty slot 22'),
    ('LABEL_E1C30C', 'StrS2cTrans_Empty17',       'S2c Transpose: empty slot 23'),
    ('LABEL_E1C30E', 'StrS2cScreen',              'S2c (Song-to-Composer) screen title string'),

    # --- Easy Composer screen string table ---
    ('LABEL_E1C318', 'PtrTbl_EasyCompScreenStrs', 'Pointer table: Easy Composer screen strings'),
    ('LABEL_E1C354', 'StrEasyCmpGrid_Empty1',     'Easy Composer Grid: empty slot 1'),
    ('LABEL_E1C356', 'StrEasyCmpGrid_Empty2',     'Easy Composer Grid: empty slot 2'),
    ('LABEL_E1C358', 'StrEasyCmpGrid_Empty3',     'Easy Composer Grid: empty slot 3'),
    ('LABEL_E1C35A', 'StrEasyCmpGrid_Empty4',     'Easy Composer Grid: empty slot 4'),
    ('LABEL_E1C35C', 'StrEasyCmpGrid',            'Easy Composer Grid screen string'),
    ('LABEL_E1C368', 'StrEsCmpMemNo',             'Easy Composer Memory number screen string'),
    ('LABEL_E1C374', 'StrEsCmpMemNo_Empty1',      'Easy Composer Memory number: empty slot 1'),
    ('LABEL_E1C376', 'StrEsCmpMemNo_Empty2',      'Easy Composer Memory number: empty slot 2'),
    ('LABEL_E1C378', 'StrEsCmpMemNo_Empty3',      'Easy Composer Memory number: empty slot 3'),
    ('LABEL_E1C37A', 'StrEsCmpMemNo_Empty4',      'Easy Composer Memory number: empty slot 4'),
    ('LABEL_E1C37C', 'StrEsCmpMemNo_Empty5',      'Easy Composer Memory number: empty slot 5'),
    ('LABEL_E1C37E', 'StrEsCmpMemNo_Empty6',      'Easy Composer Memory number: empty slot 6'),
    ('LABEL_E1C380', 'StrEsCmpMemNo_Empty7',      'Easy Composer Memory number: empty slot 7'),
    ('LABEL_E1C382', 'StrEsCmpMemNo_Empty8',      'Easy Composer Memory number: empty slot 8'),
    ('LABEL_E1C384', 'StrCmpEasyScreen',          'Composer Easy screen title string'),

    # --- Bend screen string table ---
    ('LABEL_E1C392', 'PtrTbl_BendScreenStrs',    'Pointer table: Bend screen strings'),
    ('LABEL_E1C3A6', 'StrCmpBendScreen_Empty1',  'Composer Bend screen: empty slot 1'),
    ('LABEL_E1C3A8', 'StrCmpBendScreen_Empty2',  'Composer Bend screen: empty slot 2'),
    ('LABEL_E1C3AA', 'StrCmpBendScreen_Empty3',  'Composer Bend screen: empty slot 3'),
    ('LABEL_E1C3AC', 'StrCmpBendScreen_Empty4',  'Composer Bend screen: empty slot 4'),
    ('LABEL_E1C3AE', 'StrCmpBendScreen',         'Composer Bend screen title string'),

    # --- Mode screen string table ---
    ('LABEL_E1C3C0', 'PtrTbl_ModeScreenStrs',    'Pointer table: Composer Mode screen strings'),
    ('LABEL_E1C3EC', 'StrCmpModeScreen_Empty1',  'Composer Mode screen: empty slot 1'),
    ('LABEL_E1C3EE', 'StrCmpModeScreen_Empty2',  'Composer Mode screen: empty slot 2'),
    ('LABEL_E1C3F0', 'StrCmpModeScreen_Empty3',  'Composer Mode screen: empty slot 3'),
    ('LABEL_E1C3F2', 'StrCmpModeScreen_Empty4',  'Composer Mode screen: empty slot 4'),
    ('LABEL_E1C3F4', 'StrCmpModeScreen_Empty5',  'Composer Mode screen: empty slot 5'),
    ('LABEL_E1C3F6', 'StrCmpModeScreen_Empty6',  'Composer Mode screen: empty slot 6'),
    ('LABEL_E1C3F8', 'StrCmpModeScreen_Empty7',  'Composer Mode screen: empty slot 7'),
    ('LABEL_E1C3FA', 'StrCmpModeScreen_Empty8',  'Composer Mode screen: empty slot 8'),
    ('LABEL_E1C3FC', 'StrCmpModeScreen_Empty9',  'Composer Mode screen: empty slot 9'),
    ('LABEL_E1C3FE', 'StrCmpModeScreen_EmptyA',  'Composer Mode screen: empty slot 10'),
    ('LABEL_E1C400', 'StrCmpModeScreen_EmptyB',  'Composer Mode screen: empty slot 11'),
    ('LABEL_E1C402', 'StrCmpModeScreen',         'Composer Mode screen title string'),

    # --- Custom Control Preset screen string table ---
    ('LABEL_E1C410', 'PtrTbl_CstmCpScreenStrs',  'Pointer table: Custom Control Preset screen strings'),
    ('LABEL_E1C498', 'StrCtmSMemStr_Empty1',      'Custom CP Source Memory string: empty slot 1'),
    ('LABEL_E1C49A', 'StrCtmSMemStr_Empty2',      'Custom CP Source Memory string: empty slot 2'),
    ('LABEL_E1C49C', 'StrCtmSMemStr_Empty3',      'Custom CP Source Memory string: empty slot 3'),
    ('LABEL_E1C49E', 'StrCtmSMemStr',             'Custom CP Source Memory string'),
    ('LABEL_E1C4AA', 'StrCstmFuncSelWin_Empty1',  'Custom CP Function Select window: empty slot 1'),
    ('LABEL_E1C4AC', 'StrCstmFuncSelWin_Empty2',  'Custom CP Function Select window: empty slot 2'),
    ('LABEL_E1C4AE', 'StrCstmFuncSelWin_Empty3',  'Custom CP Function Select window: empty slot 3'),
    ('LABEL_E1C4B0', 'StrCstmFuncSelWin_Empty4',  'Custom CP Function Select window: empty slot 4'),
    ('LABEL_E1C4B2', 'StrCstmFuncSelWin',         'Custom CP Function Select window string'),
    ('LABEL_E1C4C2', 'StrCtmMFulStr_Empty1',      'Custom CP Memory Full string: empty slot 1'),
    ('LABEL_E1C4C4', 'StrCtmMFulStr_Empty2',      'Custom CP Memory Full string: empty slot 2'),
    ('LABEL_E1C4C6', 'StrCtmMFulStr',             'Custom CP Memory Full string'),
    ('LABEL_E1C4D2', 'StrCstmMemFulWin_Empty1',   'Custom CP Memory Full window: empty slot 1'),
    ('LABEL_E1C4D4', 'StrCstmMemFulWin_Empty2',   'Custom CP Memory Full window: empty slot 2'),
    ('LABEL_E1C4D6', 'StrCstmMemFulWin_Empty3',   'Custom CP Memory Full window: empty slot 3'),
    ('LABEL_E1C4D8', 'StrCstmMemFulWin_Empty4',   'Custom CP Memory Full window: empty slot 4'),
    ('LABEL_E1C4DA', 'StrCstmMemFulWin',          'Custom CP Memory Full window string'),
    ('LABEL_E1C4E8', 'StrCstmCpTName_Empty',      'Custom CP T-side Name: empty'),
    ('LABEL_E1C4EA', 'StrCstmCpTName',            'Custom CP T-side Name string'),
    ('LABEL_E1C4F6', 'StrCstmCpTChar',            'Custom CP T-side Character string'),
    ('LABEL_E1C502', 'StrCstmCpFChar',            'Custom CP F-side Character string'),
    ('LABEL_E1C50E', 'StrCstmCpToVal_Empty',      'Custom CP T-side On value: empty'),
    ('LABEL_E1C510', 'StrCstmCpToVal',            'Custom CP T-side On value string'),
    ('LABEL_E1C51C', 'StrCstmCpToSw',             'Custom CP T-side On switch string'),
    ('LABEL_E1C528', 'StrCstmCpFName_Empty1',     'Custom CP F-side Name: empty slot 1'),
    ('LABEL_E1C52A', 'StrCstmCpFName_Empty2',     'Custom CP F-side Name: empty slot 2'),
    ('LABEL_E1C52C', 'StrCstmCpFName_Empty3',     'Custom CP F-side Name: empty slot 3'),
    ('LABEL_E1C52E', 'StrCstmCpFName_Empty4',     'Custom CP F-side Name: empty slot 4'),
    ('LABEL_E1C530', 'StrCstmCpFName_Empty5',     'Custom CP F-side Name: empty slot 5'),
    ('LABEL_E1C532', 'StrCstmCpFName',            'Custom CP F-side Name string'),
    ('LABEL_E1C53E', 'StrCstmCpFrmVal',           'Custom CP From-value string'),
    ('LABEL_E1C54C', 'StrCmpCstmCpScreen_Empty1', 'Composer Custom CP screen: empty slot 1'),
    ('LABEL_E1C54E', 'StrCmpCstmCpScreen_Empty2', 'Composer Custom CP screen: empty slot 2'),
    ('LABEL_E1C550', 'StrCmpCstmCpScreen',        'Composer Custom CP screen title string'),

    # --- MSP (Music Style Pattern) Backslot / Bank screen string table ---
    ('LABEL_E1C560', 'PtrTbl_MspBkslScreenStrs',  'Pointer table: MSP Backslot screen strings'),
    ('LABEL_E1C5D0', 'StrCtrl2Bnk_Empty',         'Control-2 bank: empty'),
    ('LABEL_E1C5D2', 'StrCtrl2Bnk',               'Control-2 bank name string'),
    ('LABEL_E1C5DC', 'StrCtrl1Bnk',               'Control-1 bank name string'),
    ('LABEL_E1C5E6', 'StrCmpile2Bnk',             'Compile-2 bank name string'),
    ('LABEL_E1C5F2', 'StrCmpile1Bnk',             'Compile-1 bank name string'),
    ('LABEL_E1C5FE', 'StrUser2Bnk',               'User-2 bank name string'),
    ('LABEL_E1C608', 'StrUser1Bnk',               'User-1 bank name string'),
    ('LABEL_E1C612', 'StrHitBnk',                 'Hit bank name string'),
    ('LABEL_E1C61A', 'StrLatinBnk',               'Latin bank name string'),
    ('LABEL_E1C624', 'StrJazzBnk',                'Jazz bank name string'),
    ('LABEL_E1C62C', 'StrMspBkslP2Win',           'MSP Backslot page-2 window string'),
    ('LABEL_E1C63A', 'StrFunkBnk',                'Funk bank name string'),
    ('LABEL_E1C642', 'StrDanceBnk',               'Dance bank name string'),
    ('LABEL_E1C64C', 'StrRock2Bnk',               'Rock-2 bank name string'),
    ('LABEL_E1C656', 'StrRock1Bnk',               'Rock-1 bank name string'),
    ('LABEL_E1C660', 'StrArpgioBnk',              'Arpeggio bank name string'),
    ('LABEL_E1C66A', 'StrEnterBnk',               'Entertainer bank name string'),
    ('LABEL_E1C674', 'StrMovieBnk',               'Movie bank name string'),
    ('LABEL_E1C67E', 'StrComicBnk',               'Comical bank name string'),
    ('LABEL_E1C688', 'StrEff2Bnk',                'Effect-2 bank name string'),
    ('LABEL_E1C690', 'StrEff1Bnk',                'Effect-1 bank name string'),
    ('LABEL_E1C698', 'StrMspBkslP1Win',           'MSP Backslot page-1 window string'),
    ('LABEL_E1C6A6', 'StrMspBnkP2Ctl_Empty1',     'MSP Bank page-2 control: empty slot 1'),
    ('LABEL_E1C6A8', 'StrMspBnkP2Ctl_Empty2',     'MSP Bank page-2 control: empty slot 2'),
    ('LABEL_E1C6AA', 'StrMspBnkP2Ctl',            'MSP Bank page-2 control string'),
    ('LABEL_E1C6B6', 'StrMspBnkP1Ctl',            'MSP Bank page-1 control string'),
    ('LABEL_E1C6C2', 'StrMspBkslWin',             'MSP Backslot window string'),
    ('LABEL_E1C6CE', 'StrMspBkslScreen',          'MSP Backslot screen title string'),

    # --- MSP Recording screen string table ---
    ('LABEL_E1C6E0', 'PtrTbl_MspRecScreenStrs',   'Pointer table: MSP Recording screen strings'),
    ('LABEL_E1C720', 'StrMspPadLbl_Empty1',        'MSP Pad label: empty slot 1'),
    ('LABEL_E1C722', 'StrMspPadLbl_Empty2',        'MSP Pad label: empty slot 2'),
    ('LABEL_E1C724', 'StrMspPadLbl_Empty3',        'MSP Pad label: empty slot 3'),
    ('LABEL_E1C726', 'StrMspPadLbl_Empty4',        'MSP Pad label: empty slot 4'),
    ('LABEL_E1C728', 'StrMspPadLbl',               'MSP Pad label string'),
    ('LABEL_E1C732', 'StrMspMem_Empty',            'MSP Memory: empty'),
    ('LABEL_E1C734', 'StrMspMem',                  'MSP Memory string'),
    ('LABEL_E1C73C', 'StrMspMeas',                 'MSP Measure string'),
    ('LABEL_E1C744', 'StrMspTempo',                'MSP Tempo string'),
    ('LABEL_E1C74E', 'StrMspRecBox2_Empty',        'MSP Record box-2: empty'),
    ('LABEL_E1C750', 'StrMspRecBox2',              'MSP Record box-2 string'),
    ('LABEL_E1C75C', 'StrRecBankName',             'MSP Recording bank name string'),
    ('LABEL_E1C768', 'StrRecPadNo',                'MSP Recording pad number string'),
    ('LABEL_E1C772', 'StrMspBnkLbl',              'MSP Bank label string'),
    ('LABEL_E1C77C', 'StrMspRecBox1_Empty',       'MSP Record box-1: empty'),
    ('LABEL_E1C77E', 'StrMspRecBox1',             'MSP Record box-1 string'),
    ('LABEL_E1C78A', 'StrMspRecScreen',           'MSP Recording screen title string'),

    # --- MSP Menu screen string table ---
    ('LABEL_E1C798', 'PtrTbl_MspMenuScreenStrs',  'Pointer table: MSP Menu screen strings'),
    ('LABEL_E1C7B4', 'StrMspMenuScreen_Empty1',   'MSP Menu screen: empty slot 1'),
    ('LABEL_E1C7B6', 'StrMspMenuScreen_Empty2',   'MSP Menu screen: empty slot 2'),
    ('LABEL_E1C7B8', 'StrMspMenuScreen_Empty3',   'MSP Menu screen: empty slot 3'),
    ('LABEL_E1C7BA', 'StrMspMenuScreen_Empty4',   'MSP Menu screen: empty slot 4'),
    ('LABEL_E1C7BC', 'StrMspMenuScreen_Empty5',   'MSP Menu screen: empty slot 5'),
    ('LABEL_E1C7BE', 'StrMspMenuScreen_Empty6',   'MSP Menu screen: empty slot 6'),
    ('LABEL_E1C7C0', 'StrMspMenuScreen',          'MSP Menu screen title string'),

    # --- MSP Naming screen string table ---
    ('LABEL_E1C7D2', 'PtrTbl_MspNamingScreenStrs', 'Pointer table: MSP Naming screen strings'),
    ('LABEL_E1C7E2', 'StrMspNamingScreen_Empty1',  'MSP Naming screen: empty slot 1'),
    ('LABEL_E1C7E4', 'StrMspNamingScreen_Empty2',  'MSP Naming screen: empty slot 2'),
    ('LABEL_E1C7E6', 'StrMspNamingScreen_Empty3',  'MSP Naming screen: empty slot 3'),
    ('LABEL_E1C7E8', 'StrMspNamingScreen_Empty4',  'MSP Naming screen: empty slot 4'),
    ('LABEL_E1C7EA', 'StrMspNamingScreen',         'MSP Naming screen title string'),

    # --- MSP ReGroup screen string table ---
    ('LABEL_E1C7FA', 'PtrTbl_MspReGrpScreenStrs', 'Pointer table: MSP ReGroup screen strings'),
    ('LABEL_E1C822', 'StrRgpSetBnk_Empty1',       'ReGroup Set Bank: empty slot 1'),
    ('LABEL_E1C824', 'StrRgpSetBnk_Empty2',       'ReGroup Set Bank: empty slot 2'),
    ('LABEL_E1C826', 'StrRgpSetBnk',              'ReGroup Set Bank string'),
    ('LABEL_E1C830', 'StrMspRGrpGrid_Empty1',     'MSP ReGroup Grid: empty slot 1'),
    ('LABEL_E1C832', 'StrMspRGrpGrid_Empty2',     'MSP ReGroup Grid: empty slot 2'),
    ('LABEL_E1C834', 'StrMspRGrpGrid_Empty3',     'MSP ReGroup Grid: empty slot 3'),
    ('LABEL_E1C836', 'StrMspRGrpGrid',            'MSP ReGroup Grid string'),
    ('LABEL_E1C842', 'StrRGrpBnkSw_Empty',        'ReGroup Bank switch: empty'),
    ('LABEL_E1C844', 'StrRGrpBnkSw',              'ReGroup Bank switch string'),
    ('LABEL_E1C84E', 'StrMspReGrpScreen',         'MSP ReGroup screen title string'),

    # --- Sound Arranger (SndArgr) screen string table ---
    ('LABEL_E1C85E', 'PtrTbl_SndArgrScreenStrs',  'Pointer table: Sound Arranger screen strings'),
    ('LABEL_E1C882', 'StrSndArgrGrid_Empty1',     'Sound Arranger Grid: empty slot 1'),
    ('LABEL_E1C884', 'StrSndArgrGrid_Empty2',     'Sound Arranger Grid: empty slot 2'),
    ('LABEL_E1C886', 'StrSndArgrGrid_Empty3',     'Sound Arranger Grid: empty slot 3'),
    ('LABEL_E1C888', 'StrSndArgrGrid',            'Sound Arranger Grid string'),
    ('LABEL_E1C894', 'StrSndArgRhyName_Empty1',   'Sound Arranger Rhythm Name: empty slot 1'),
    ('LABEL_E1C896', 'StrSndArgRhyName_Empty2',   'Sound Arranger Rhythm Name: empty slot 2'),
    ('LABEL_E1C898', 'StrSndArgRhyName',          'Sound Arranger Rhythm Name string'),
    ('LABEL_E1C8A6', 'StrSndArgrScreen_Empty',    'Sound Arranger screen: empty'),
    ('LABEL_E1C8A8', 'StrSndArgrScreen',          'Sound Arranger screen title string'),

    # --- APC (Auto Play Chord) Selection screen string table ---
    ('LABEL_E1C8B6', 'PtrTbl_ApcSelScreenStrs',  'Pointer table: APC Selection screen strings'),
    ('LABEL_E1C8D2', 'StrApcOnBass_Empty',        'APC On-Bass: empty'),
    ('LABEL_E1C8D4', 'StrApcOnBass',              'APC On-Bass string'),
    ('LABEL_E1C8DE', 'StrApcMem',                 'APC Memory string'),
    ('LABEL_E1C8E6', 'StrApcSelScreen_Empty1',    'APC Selection screen: empty slot 1'),
    ('LABEL_E1C8E8', 'StrApcSelScreen_Empty2',    'APC Selection screen: empty slot 2'),
    ('LABEL_E1C8EA', 'StrApcSelScreen_Empty3',    'APC Selection screen: empty slot 3'),
    ('LABEL_E1C8EC', 'StrApcSelScreen',           'APC Selection screen title string'),

    # --- Function name string lookup table (for debug/UI function names) ---
    ('LABEL_E1CB02', 'PtrTbl_FuncNameStrs',       'Pointer table: function name strings for display'),
    ('LABEL_E1CB96', 'StrFuncNames_Empty',         'Function name strings: empty entry'),
    ('LABEL_E1CB98', 'StrMainStylCnvFunc',         'Function name: MainStylCnvFunc'),
    ('LABEL_E1CBA8', 'StrStylCnvStorTtlFunc',      'Function name: StylCnvStorTtlFunc'),
    ('LABEL_E1CBBC', 'StrStylCnvContTtlFunc',      'Function name: StylCnvContTtlFunc'),
    ('LABEL_E1CBD0', 'StrStylCnvSelTtlFunc',       'Function name: StylCnvSelTtlFunc'),
    ('LABEL_E1CBE2', 'StrStylCnvCnvtTtlFunc',      'Function name: StylCnvCnvtTtlFunc'),
    ('LABEL_E1CBF6', 'StrStylCnvModlTtlFunc',      'Function name: StylCnvModlTtlFunc'),
    ('LABEL_E1CC0A', 'StrStylCnvTxtTtlFunc',       'Function name: StylCnvTxtTtlFunc'),
    ('LABEL_E1CC1C', 'StrStylCnvWaitTtlFunc',      'Function name: StylCnvWaitTtlFunc'),
    ('LABEL_E1CC30', 'StrSndArgNmGet',             'Function name: SndArgNmGet'),
    ('LABEL_E1CC3C', 'StrMainCstmNameFunc',        'Function name: MainCstmNameFunc'),
    ('LABEL_E1CC4E', 'StrCmpStepTitleFunc',        'Function name: CmpStepTitleFunc'),
    ('LABEL_E1CC60', 'StrMainEsCmpFunc',           'Function name: MainEsCmpFunc'),
    ('LABEL_E1CC6E', 'StrSndArgTtlFunc',           'Function name: SndArgTtlFunc'),
    ('LABEL_E1CC7C', 'StrSndArgModeFunc',          'Function name: SndArgModeFunc'),
    ('LABEL_E1CC8C', 'StrMspRecTtlFunc',           'Function name: MspRecTtlFunc'),
    ('LABEL_E1CC9A', 'StrMspRecModeFunc',          'Function name: MspRecModeFunc'),
    ('LABEL_E1CCAA', 'StrMspNameTtlFunc',          'Function name: MspNameTtlFunc'),
    ('LABEL_E1CCBA', 'StrMspMenuTtlFunc',          'Function name: MspMenuTtlFunc'),
    ('LABEL_E1CCCA', 'StrMspBkslTtlFunc',          'Function name: MspBkslTtlFunc'),
    ('LABEL_E1CCDA', 'StrMainMspBnkNameFunc',      'Function name: MainMspBnkNameFunc'),
    ('LABEL_E1CCEE', 'StrMainMspRgpSetFunc',       'Function name: MainMspRgpSetFunc'),
    ('LABEL_E1CD00', 'StrMainS2cFunc',             'Function name: MainS2cFunc'),
    ('LABEL_E1CD0C', 'StrMainCmpSetFunc',          'Function name: MainCmpSetFunc'),
    ('LABEL_E1CD1C', 'StrMiddleCmpClrFunc',        'Function name: MiddleCmpClrFunc'),
    ('LABEL_E1CD2E', 'StrMainCmpCpFunc',           'Function name: MainCmpCpFunc'),
    ('LABEL_E1CD3C', 'StrMiddleNameFunc',          'Function name: MiddleNameFunc'),
    ('LABEL_E1CD4C', 'StrCstmCpTtlFunc',          'Function name: CstmCpTtlFunc'),
    ('LABEL_E1CD5A', 'StrS2cTtlFunc',             'Function name: S2cTtlFunc'),
    ('LABEL_E1CD66', 'StrCmEsyTtlFunc',           'Function name: CmEsyTtlFunc'),
    ('LABEL_E1CD74', 'StrCmpNcpTtlFunc',          'Function name: CmpNcpTtlFunc'),
    ('LABEL_E1CD82', 'StrCmpMenuTtlFunc',         'Function name: CmpMenuTtlFunc'),
    ('LABEL_E1CD92', 'StrCmpBksl_STtlFunc',       'Function name: CmpBksl_STtlFunc'),
    ('LABEL_E1CDA4', 'StrCmpBkslTtlFunc',         'Function name: CmpBkslTtlFunc'),
    ('LABEL_E1CDB4', 'StrCmpRealTtlFunc',         'Function name: CmpRealTtlFunc'),
    ('LABEL_E1CDC4', 'StrCmpSetTtlFunc',          'Function name: CmpSetTtlFunc'),
    ('LABEL_E1CDD2', 'StrCmpModeFunc',            'Function name: CmpModeFunc'),

    # --- Note value / step grid display strings ---
    # LABEL_E1CDDE is data starting with ldb w, 0x31 followed by raw bytes
    # Bytes decode to: "12\0 11\0 10\0  9\0  8\0  7\0  6\0  5\0  4\0  3\0  2\0  1\0  0\0ERR\0"
    # Then word-size data (01,01,01,01,02,03,...) for grid column widths/counts
    # Followed by pixel coordinate pairs
    ('LABEL_E1CDDE', 'NoteStepDisplayData',       'Note step display column labels and layout data'),

    # --- Note name bytes: pairs of (note_byte, flags) terminated by 0xFF ---
    # B=0x42, Bb=0x62 (b suffix), A=0x41, Ab=0x61, G=0x47, F#=0x46 sharp=0x23, F=0x46, E=0x45, Eb=0x65, D=0x44, Db=0x64, C=0x43
    ('LABEL_E1CE48', 'NoteDataB_Natural',         'Note data entry: B natural'),
    ('LABEL_E1CE4C', 'NoteDataB_Flat',            'Note data entry: Bb (B flat)'),
    ('LABEL_E1CE50', 'NoteDataA_Natural',         'Note data entry: A natural'),
    ('LABEL_E1CE54', 'NoteDataA_Flat',            'Note data entry: Ab (A flat)'),
    ('LABEL_E1CE58', 'NoteDataG_Natural',         'Note data entry: G natural'),
    ('LABEL_E1CE5C', 'NoteDataF_Sharp',           'Note data entry: F# (F sharp)'),
    ('LABEL_E1CE60', 'NoteDataF_Natural',         'Note data entry: F natural'),
    ('LABEL_E1CE64', 'NoteDataE_Natural',         'Note data entry: E natural'),
    ('LABEL_E1CE68', 'NoteDataE_Flat',            'Note data entry: Eb (E flat)'),
    ('LABEL_E1CE6C', 'NoteDataD_Natural',         'Note data entry: D natural'),
    ('LABEL_E1CE70', 'NoteDataD_Flat',            'Note data entry: Db (D flat)'),
    ('LABEL_E1CE74', 'NoteDataC_Natural',         'Note data entry: C natural'),

    # --- Generic string literals used in Composer displays ---
    ('LABEL_E1CE78', 'StrEnable',                 'String literal: "ENABLE "'),
    ('LABEL_E1CE80', 'StrDisable',                'String literal: "DISABLE"'),
    ('LABEL_E1CE88', 'StrMinor',                  'String literal: "MINOR"'),
    ('LABEL_E1CE8E', 'StrMajor',                  'String literal: "MAJOR"'),
    ('LABEL_E1CE94', 'StrSeventh',                'String literal: "7th   "'),
    ('LABEL_E1CE9C', 'StrNormal',                 'String literal: "NORMAL"'),

    # --- Time signature display strings (numerator/denominator pairs) ---
    ('LABEL_E1CEA4', 'StrTimeSig_4_8',            'Time signature string: 4/8'),
    ('LABEL_E1CEA8', 'StrTimeSig_3_8',            'Time signature string: 3/8'),
    ('LABEL_E1CEAC', 'StrTimeSig_2_8',            'Time signature string: 2/8'),
    ('LABEL_E1CEB0', 'StrTimeSig_1_8',            'Time signature string: 1/8'),
    ('LABEL_E1CEB4', 'StrTimeSig_8_4',            'Time signature string: 8/4'),
    ('LABEL_E1CEB8', 'StrTimeSig_7_4',            'Time signature string: 7/4'),
    ('LABEL_E1CEBC', 'StrTimeSig_6_4',            'Time signature string: 6/4'),
    ('LABEL_E1CEC0', 'StrTimeSig_5_4',            'Time signature string: 5/4'),
    ('LABEL_E1CEC4', 'StrTimeSig_4_4',            'Time signature string: 4/4'),
    ('LABEL_E1CEC8', 'StrTimeSig_3_4',            'Time signature string: 3/4'),
    ('LABEL_E1CECC', 'StrTimeSig_2_4',            'Time signature string: 2/4'),
    ('LABEL_E1CED0', 'StrTimeSig_1_4',            'Time signature string: 1/4'),
    ('LABEL_E1CED4', 'StrTimeSig_4_2',            'Time signature string: 4/2'),
    ('LABEL_E1CED8', 'StrTimeSig_3_2',            'Time signature string: 3/2'),
    ('LABEL_E1CEDC', 'StrTimeSig_2_2',            'Time signature string: 2/2'),
    ('LABEL_E1CEE0', 'StrTimeSig_1_2',            'Time signature string: 1/2'),

    # --- Pan position display strings (Right 63 .. Right 1, CENTER, Left 1 .. Left 64) ---
    ('LABEL_E1CF0E', 'StrPanRight63',             'Pan position string: Right 63'),
    ('LABEL_E1CF18', 'StrPanRight62',             'Pan position string: Right 62'),
    ('LABEL_E1CF22', 'StrPanRight61',             'Pan position string: Right 61'),
    ('LABEL_E1CF2C', 'StrPanRight60',             'Pan position string: Right 60'),
    ('LABEL_E1CF36', 'StrPanRight59',             'Pan position string: Right 59'),
    ('LABEL_E1CF40', 'StrPanRight58',             'Pan position string: Right 58'),
    ('LABEL_E1CF4A', 'StrPanRight57',             'Pan position string: Right 57'),
    ('LABEL_E1CF54', 'StrPanRight56',             'Pan position string: Right 56'),
    ('LABEL_E1CF5E', 'StrPanRight55',             'Pan position string: Right 55'),
    ('LABEL_E1CF68', 'StrPanRight54',             'Pan position string: Right 54'),
    ('LABEL_E1CF72', 'StrPanRight53',             'Pan position string: Right 53'),
    ('LABEL_E1CF7C', 'StrPanRight52',             'Pan position string: Right 52'),
    ('LABEL_E1CF86', 'StrPanRight51',             'Pan position string: Right 51'),
    ('LABEL_E1CF90', 'StrPanRight50',             'Pan position string: Right 50'),
    ('LABEL_E1CF9A', 'StrPanRight49',             'Pan position string: Right 49'),
    ('LABEL_E1CFA4', 'StrPanRight48',             'Pan position string: Right 48'),
    ('LABEL_E1CFAE', 'StrPanRight47',             'Pan position string: Right 47'),
    ('LABEL_E1CFB8', 'StrPanRight46',             'Pan position string: Right 46'),
    ('LABEL_E1CFC2', 'StrPanRight45',             'Pan position string: Right 45'),
    ('LABEL_E1CFCC', 'StrPanRight44',             'Pan position string: Right 44'),
    ('LABEL_E1CFD6', 'StrPanRight43',             'Pan position string: Right 43'),
    ('LABEL_E1CFE0', 'StrPanRight42',             'Pan position string: Right 42'),
    ('LABEL_E1CFEA', 'StrPanRight41',             'Pan position string: Right 41'),
    ('LABEL_E1CFF4', 'StrPanRight40',             'Pan position string: Right 40'),
    ('LABEL_E1CFFE', 'StrPanRight39',             'Pan position string: Right 39'),
    ('LABEL_E1D008', 'StrPanRight38',             'Pan position string: Right 38'),
    ('LABEL_E1D012', 'StrPanRight37',             'Pan position string: Right 37'),
    ('LABEL_E1D01C', 'StrPanRight36',             'Pan position string: Right 36'),
    ('LABEL_E1D026', 'StrPanRight35',             'Pan position string: Right 35'),
    ('LABEL_E1D030', 'StrPanRight34',             'Pan position string: Right 34'),
    ('LABEL_E1D03A', 'StrPanRight33',             'Pan position string: Right 33'),
    ('LABEL_E1D044', 'StrPanRight32',             'Pan position string: Right 32'),
    ('LABEL_E1D04E', 'StrPanRight31',             'Pan position string: Right 31'),
    ('LABEL_E1D058', 'StrPanRight30',             'Pan position string: Right 30'),
    ('LABEL_E1D062', 'StrPanRight29',             'Pan position string: Right 29'),
    ('LABEL_E1D06C', 'StrPanRight28',             'Pan position string: Right 28'),
    ('LABEL_E1D076', 'StrPanRight27',             'Pan position string: Right 27'),
    ('LABEL_E1D080', 'StrPanRight26',             'Pan position string: Right 26'),
    ('LABEL_E1D08A', 'StrPanRight25',             'Pan position string: Right 25'),
    ('LABEL_E1D094', 'StrPanRight24',             'Pan position string: Right 24'),
    ('LABEL_E1D09E', 'StrPanRight23',             'Pan position string: Right 23'),
    ('LABEL_E1D0A8', 'StrPanRight22',             'Pan position string: Right 22'),
    ('LABEL_E1D0B2', 'StrPanRight21',             'Pan position string: Right 21'),
    ('LABEL_E1D0BC', 'StrPanRight20',             'Pan position string: Right 20'),
    ('LABEL_E1D0C6', 'StrPanRight19',             'Pan position string: Right 19'),
    ('LABEL_E1D0D0', 'StrPanRight18',             'Pan position string: Right 18'),
    ('LABEL_E1D0DA', 'StrPanRight17',             'Pan position string: Right 17'),
    ('LABEL_E1D0E4', 'StrPanRight16',             'Pan position string: Right 16'),
    ('LABEL_E1D0EE', 'StrPanRight15',             'Pan position string: Right 15'),
    ('LABEL_E1D0F8', 'StrPanRight14',             'Pan position string: Right 14'),
    ('LABEL_E1D102', 'StrPanRight13',             'Pan position string: Right 13'),
    ('LABEL_E1D10C', 'StrPanRight12',             'Pan position string: Right 12'),
    ('LABEL_E1D116', 'StrPanRight11',             'Pan position string: Right 11'),
    ('LABEL_E1D120', 'StrPanRight10',             'Pan position string: Right 10'),
    ('LABEL_E1D12A', 'StrPanRight09',             'Pan position string: Right  9'),
    ('LABEL_E1D134', 'StrPanRight08',             'Pan position string: Right  8'),
    ('LABEL_E1D13E', 'StrPanRight07',             'Pan position string: Right  7'),
    ('LABEL_E1D148', 'StrPanRight06',             'Pan position string: Right  6'),
    ('LABEL_E1D152', 'StrPanRight05',             'Pan position string: Right  5'),
    ('LABEL_E1D15C', 'StrPanRight04',             'Pan position string: Right  4'),
    ('LABEL_E1D166', 'StrPanRight03',             'Pan position string: Right  3'),
    ('LABEL_E1D170', 'StrPanRight02',             'Pan position string: Right  2'),
    ('LABEL_E1D17A', 'StrPanRight01',             'Pan position string: Right  1'),
    ('LABEL_E1D184', 'StrPanCenter',              'Pan position string: CENTER'),
    ('LABEL_E1D18E', 'StrPanLeft01',              'Pan position string:  Left  1'),
    ('LABEL_E1D198', 'StrPanLeft02',              'Pan position string:  Left  2'),
    ('LABEL_E1D1A2', 'StrPanLeft03',              'Pan position string:  Left  3'),
    ('LABEL_E1D1AC', 'StrPanLeft04',              'Pan position string:  Left  4'),
    ('LABEL_E1D1B6', 'StrPanLeft05',              'Pan position string:  Left  5'),
    ('LABEL_E1D1C0', 'StrPanLeft06',              'Pan position string:  Left  6'),
    ('LABEL_E1D1CA', 'StrPanLeft07',              'Pan position string:  Left  7'),
    ('LABEL_E1D1D4', 'StrPanLeft08',              'Pan position string:  Left  8'),
    ('LABEL_E1D1DE', 'StrPanLeft09',              'Pan position string:  Left  9'),
    ('LABEL_E1D1E8', 'StrPanLeft10',              'Pan position string:  Left 10'),
    ('LABEL_E1D1F2', 'StrPanLeft11',              'Pan position string:  Left 11'),
    ('LABEL_E1D1FC', 'StrPanLeft12',              'Pan position string:  Left 12'),
    ('LABEL_E1D206', 'StrPanLeft13',              'Pan position string:  Left 13'),
    ('LABEL_E1D210', 'StrPanLeft14',              'Pan position string:  Left 14'),
    ('LABEL_E1D21A', 'StrPanLeft15',              'Pan position string:  Left 15'),
    ('LABEL_E1D224', 'StrPanLeft16',              'Pan position string:  Left 16'),
    ('LABEL_E1D22E', 'StrPanLeft17',              'Pan position string:  Left 17'),
    ('LABEL_E1D238', 'StrPanLeft18',              'Pan position string:  Left 18'),
    ('LABEL_E1D242', 'StrPanLeft19',              'Pan position string:  Left 19'),
    ('LABEL_E1D24C', 'StrPanLeft20',              'Pan position string:  Left 20'),
    ('LABEL_E1D256', 'StrPanLeft21',              'Pan position string:  Left 21'),
    ('LABEL_E1D260', 'StrPanLeft22',              'Pan position string:  Left 22'),
    ('LABEL_E1D26A', 'StrPanLeft23',              'Pan position string:  Left 23'),
    ('LABEL_E1D274', 'StrPanLeft24',              'Pan position string:  Left 24'),
    ('LABEL_E1D27E', 'StrPanLeft25',              'Pan position string:  Left 25'),
    ('LABEL_E1D288', 'StrPanLeft26',              'Pan position string:  Left 26'),
    ('LABEL_E1D292', 'StrPanLeft27',              'Pan position string:  Left 27'),
    ('LABEL_E1D29C', 'StrPanLeft28',              'Pan position string:  Left 28'),
    ('LABEL_E1D2A6', 'StrPanLeft29',              'Pan position string:  Left 29'),
    ('LABEL_E1D2B0', 'StrPanLeft30',              'Pan position string:  Left 30'),
    ('LABEL_E1D2BA', 'StrPanLeft31',              'Pan position string:  Left 31'),
    ('LABEL_E1D2C4', 'StrPanLeft32',              'Pan position string:  Left 32'),
    ('LABEL_E1D2CE', 'StrPanLeft33',              'Pan position string:  Left 33'),
    ('LABEL_E1D2D8', 'StrPanLeft34',              'Pan position string:  Left 34'),
    ('LABEL_E1D2E2', 'StrPanLeft35',              'Pan position string:  Left 35'),
    ('LABEL_E1D2EC', 'StrPanLeft36',              'Pan position string:  Left 36'),
    ('LABEL_E1D2F6', 'StrPanLeft37',              'Pan position string:  Left 37'),
    ('LABEL_E1D300', 'StrPanLeft38',              'Pan position string:  Left 38'),
    ('LABEL_E1D30A', 'StrPanLeft39',              'Pan position string:  Left 39'),
    ('LABEL_E1D314', 'StrPanLeft40',              'Pan position string:  Left 40'),
    ('LABEL_E1D31E', 'StrPanLeft41',              'Pan position string:  Left 41'),
    ('LABEL_E1D328', 'StrPanLeft42',              'Pan position string:  Left 42'),
    ('LABEL_E1D332', 'StrPanLeft43',              'Pan position string:  Left 43'),
    ('LABEL_E1D33C', 'StrPanLeft44',              'Pan position string:  Left 44'),
    ('LABEL_E1D346', 'StrPanLeft45',              'Pan position string:  Left 45'),
    ('LABEL_E1D350', 'StrPanLeft46',              'Pan position string:  Left 46'),
    ('LABEL_E1D35A', 'StrPanLeft47',              'Pan position string:  Left 47'),
    ('LABEL_E1D364', 'StrPanLeft48',              'Pan position string:  Left 48'),
    ('LABEL_E1D36E', 'StrPanLeft49',              'Pan position string:  Left 49'),
    ('LABEL_E1D378', 'StrPanLeft40b',             'Pan position string:  Left 40 (duplicate entry)'),
    ('LABEL_E1D382', 'StrPanLeft51',              'Pan position string:  Left 51'),
    ('LABEL_E1D38C', 'StrPanLeft52',              'Pan position string:  Left 52'),
    ('LABEL_E1D396', 'StrPanLeft53',              'Pan position string:  Left 53'),
    ('LABEL_E1D3A0', 'StrPanLeft54',              'Pan position string:  Left 54'),
    ('LABEL_E1D3AA', 'StrPanLeft55',              'Pan position string:  Left 55'),
    ('LABEL_E1D3B4', 'StrPanLeft56',              'Pan position string:  Left 56'),
    ('LABEL_E1D3BE', 'StrPanLeft57',              'Pan position string:  Left 57'),
    ('LABEL_E1D3C8', 'StrPanLeft58',              'Pan position string:  Left 58'),
    ('LABEL_E1D3D2', 'StrPanLeft59',              'Pan position string:  Left 59'),
    ('LABEL_E1D3DC', 'StrPanLeft60',              'Pan position string:  Left 60'),
    ('LABEL_E1D3E6', 'StrPanLeft61',              'Pan position string:  Left 61'),
    ('LABEL_E1D3F0', 'StrPanLeft62',              'Pan position string:  Left 62'),
    ('LABEL_E1D3FA', 'StrPanLeft63',              'Pan position string:  Left 63'),
    ('LABEL_E1D404', 'StrPanLeft64',              'Pan position string:  Left 64'),

    # --- Style section short name pointer table (compact: A/B/C-vari1..4, INT, FILL, END) ---
    ('LABEL_E1D420', 'PtrTbl_StyleSectShortNames', 'Pointer table: style section short name strings'),
    ('LABEL_E1D494', 'StrStyleSect_C_End2',        'Style section short name: C-END2'),
    ('LABEL_E1D49C', 'StrStyleSect_C_End1',        'Style section short name: C-END1'),
    ('LABEL_E1D4A4', 'StrStyleSect_C_Fill2',       'Style section short name: C-FILL2'),
    ('LABEL_E1D4AC', 'StrStyleSect_C_Fill1',       'Style section short name: C-FILL1'),
    ('LABEL_E1D4B4', 'StrStyleSect_C_Int2',        'Style section short name: C-INT2'),
    ('LABEL_E1D4BC', 'StrStyleSect_C_Int1',        'Style section short name: C-INT1'),
    ('LABEL_E1D4C4', 'StrStyleSect_B_End2',        'Style section short name: B-END2'),
    ('LABEL_E1D4CC', 'StrStyleSect_B_End1',        'Style section short name: B-END1'),
    ('LABEL_E1D4D4', 'StrStyleSect_B_Fill2',       'Style section short name: B-FILL2'),
    ('LABEL_E1D4DC', 'StrStyleSect_B_Fill1',       'Style section short name: B-FILL1'),
    ('LABEL_E1D4E4', 'StrStyleSect_B_Int2',        'Style section short name: B-INT2'),
    ('LABEL_E1D4EC', 'StrStyleSect_B_Int1',        'Style section short name: B-INT1'),
    ('LABEL_E1D4F4', 'StrStyleSect_A_End2',        'Style section short name: A-END2'),
    ('LABEL_E1D4FC', 'StrStyleSect_A_End1',        'Style section short name: A-END1'),
    ('LABEL_E1D504', 'StrStyleSect_A_Fill2',       'Style section short name: A-FILL2'),
    ('LABEL_E1D50C', 'StrStyleSect_A_Fill1',       'Style section short name: A-FILL1'),
    ('LABEL_E1D514', 'StrStyleSect_A_Int2',        'Style section short name: A-INT2'),
    ('LABEL_E1D51C', 'StrStyleSect_A_Int1',        'Style section short name: A-INT1'),
    ('LABEL_E1D524', 'StrStyleSect_C_Vari4',       'Style section short name: C-vari4'),
    ('LABEL_E1D52C', 'StrStyleSect_C_Vari3',       'Style section short name: C-vari3'),
    ('LABEL_E1D534', 'StrStyleSect_C_Vari2',       'Style section short name: C-vari2'),
    ('LABEL_E1D53C', 'StrStyleSect_C_Vari1',       'Style section short name: C-vari1'),
    ('LABEL_E1D544', 'StrStyleSect_B_Vari4',       'Style section short name: B-vari4'),
    ('LABEL_E1D54C', 'StrStyleSect_B_Vari3',       'Style section short name: B-vari3'),
    ('LABEL_E1D554', 'StrStyleSect_B_Vari2',       'Style section short name: B-vari2'),
    ('LABEL_E1D55C', 'StrStyleSect_B_Vari1',       'Style section short name: B-vari1'),
    ('LABEL_E1D564', 'StrStyleSect_A_Vari4',       'Style section short name: A-vari4'),
    ('LABEL_E1D56C', 'StrStyleSect_A_Vari3',       'Style section short name: A-vari3'),
    ('LABEL_E1D574', 'StrStyleSect_A_Vari2',       'Style section short name: A-vari2'),
    ('LABEL_E1D57C', 'StrStyleSect_A_Vari1',       'Style section short name: A-vari1'),

    # --- Transpose value string pointer table (+24 to -25) ---
    ('LABEL_E1D598', 'PtrTbl_TransposeStrs',      'Pointer table: transpose value display strings'),
    # Strings: "+24" down to "+1", "  0", "-1" down to "-25"
    ('LABEL_E1D660', 'StrTranspose_Plus24',        'Transpose string: +24'),
    ('LABEL_E1D664', 'StrTranspose_Plus23',        'Transpose string: +23'),
    ('LABEL_E1D668', 'StrTranspose_Plus22',        'Transpose string: +22'),
    ('LABEL_E1D66C', 'StrTranspose_Plus21',        'Transpose string: +21'),
    ('LABEL_E1D670', 'StrTranspose_Plus20',        'Transpose string: +20'),
    ('LABEL_E1D674', 'StrTranspose_Plus19',        'Transpose string: +19'),
    ('LABEL_E1D678', 'StrTranspose_Plus18',        'Transpose string: +18'),
    ('LABEL_E1D67C', 'StrTranspose_Plus17',        'Transpose string: +17'),
    ('LABEL_E1D680', 'StrTranspose_Plus16',        'Transpose string: +16'),
    ('LABEL_E1D684', 'StrTranspose_Plus15',        'Transpose string: +15'),
    ('LABEL_E1D688', 'StrTranspose_Plus14',        'Transpose string: +14'),
    ('LABEL_E1D68C', 'StrTranspose_Plus13',        'Transpose string: +13'),
    ('LABEL_E1D690', 'StrTranspose_Plus12',        'Transpose string: +12'),
    ('LABEL_E1D694', 'StrTranspose_Plus11',        'Transpose string: +11'),
    ('LABEL_E1D698', 'StrTranspose_Plus10',        'Transpose string: +10'),
    ('LABEL_E1D69C', 'StrTranspose_Plus09',        'Transpose string: + 9'),
    ('LABEL_E1D6A0', 'StrTranspose_Plus08',        'Transpose string: + 8'),
    ('LABEL_E1D6A4', 'StrTranspose_Plus07',        'Transpose string: + 7'),
    ('LABEL_E1D6A8', 'StrTranspose_Plus06',        'Transpose string: + 6'),
    ('LABEL_E1D6AC', 'StrTranspose_Plus05',        'Transpose string: + 5'),
    ('LABEL_E1D6B0', 'StrTranspose_Plus04',        'Transpose string: + 4'),
    ('LABEL_E1D6B4', 'StrTranspose_Plus03',        'Transpose string: + 3'),
    ('LABEL_E1D6B8', 'StrTranspose_Plus02',        'Transpose string: + 2'),
    ('LABEL_E1D6BC', 'StrTranspose_Plus01',        'Transpose string: + 1'),
    ('LABEL_E1D6C0', 'StrTranspose_Zero',          'Transpose string:   0'),
    ('LABEL_E1D6C4', 'StrTranspose_Minus01',       'Transpose string: - 1'),
    ('LABEL_E1D6C8', 'StrTranspose_Minus02',       'Transpose string: - 2'),
    ('LABEL_E1D6CC', 'StrTranspose_Minus03',       'Transpose string: - 3'),
    ('LABEL_E1D6D0', 'StrTranspose_Minus04',       'Transpose string: - 4'),
    ('LABEL_E1D6D4', 'StrTranspose_Minus05',       'Transpose string: - 5'),
    ('LABEL_E1D6D8', 'StrTranspose_Minus06',       'Transpose string: - 6'),
    ('LABEL_E1D6DC', 'StrTranspose_Minus07',       'Transpose string: - 7'),
    ('LABEL_E1D6E0', 'StrTranspose_Minus08',       'Transpose string: - 8'),
    ('LABEL_E1D6E4', 'StrTranspose_Minus09',       'Transpose string: - 9'),
    ('LABEL_E1D6E8', 'StrTranspose_Minus10',       'Transpose string: -10'),
    ('LABEL_E1D6EC', 'StrTranspose_Minus11',       'Transpose string: -11'),
    ('LABEL_E1D6F0', 'StrTranspose_Minus12',       'Transpose string: -12'),
    ('LABEL_E1D6F4', 'StrTranspose_Minus13',       'Transpose string: -13'),
    ('LABEL_E1D6F8', 'StrTranspose_Minus14',       'Transpose string: -14'),
    ('LABEL_E1D6FC', 'StrTranspose_Minus15',       'Transpose string: -15'),
    ('LABEL_E1D700', 'StrTranspose_Minus16',       'Transpose string: -16'),
    ('LABEL_E1D704', 'StrTranspose_Minus17',       'Transpose string: -17'),
    ('LABEL_E1D708', 'StrTranspose_Minus18',       'Transpose string: -18'),
    ('LABEL_E1D70C', 'StrTranspose_Minus19',       'Transpose string: -19'),
    ('LABEL_E1D710', 'StrTranspose_Minus20',       'Transpose string: -20'),
    ('LABEL_E1D714', 'StrTranspose_Minus21',       'Transpose string: -21'),
    ('LABEL_E1D718', 'StrTranspose_Minus22',       'Transpose string: -22'),
    ('LABEL_E1D71C', 'StrTranspose_Minus23',       'Transpose string: -23'),
    ('LABEL_E1D720', 'StrTranspose_Minus24',       'Transpose string: -24'),
    ('LABEL_E1D724', 'StrTranspose_Minus25',       'Transpose string: -25'),

    # --- Beat quantize display strings (16, 15 ... 1, OFF) ---
    # These are used for quantize/beat grid display, e.g. "16 ", "15 ", ..., " 1 ", "OFF"
    ('LABEL_E1D74A', 'StrBeat16',                  'Beat quantize string: 16'),
    ('LABEL_E1D74E', 'StrBeat15',                  'Beat quantize string: 15'),
    ('LABEL_E1D752', 'StrBeat14',                  'Beat quantize string: 14'),
    ('LABEL_E1D756', 'StrBeat13',                  'Beat quantize string: 13'),
    ('LABEL_E1D75A', 'StrBeat12',                  'Beat quantize string: 12'),
    ('LABEL_E1D75E', 'StrBeat11',                  'Beat quantize string: 11'),
    ('LABEL_E1D762', 'StrBeat10',                  'Beat quantize string: 10'),
    ('LABEL_E1D766', 'StrBeat09',                  'Beat quantize string:  9'),
    ('LABEL_E1D76A', 'StrBeat08',                  'Beat quantize string:  8'),
    ('LABEL_E1D76E', 'StrBeat07',                  'Beat quantize string:  7'),
    ('LABEL_E1D772', 'StrBeat06',                  'Beat quantize string:  6'),
    ('LABEL_E1D776', 'StrBeat05',                  'Beat quantize string:  5'),
    ('LABEL_E1D77A', 'StrBeat04',                  'Beat quantize string:  4'),
    ('LABEL_E1D77E', 'StrBeat03',                  'Beat quantize string:  3'),
    ('LABEL_E1D782', 'StrBeat02',                  'Beat quantize string:  2'),
    ('LABEL_E1D786', 'StrBeat01',                  'Beat quantize string:  1'),
    ('LABEL_E1D78A', 'StrBeatOff',                 'Beat quantize string: OFF'),

    # --- Style pattern long name pointer table (ALL, ENDING1/2, FILL IN 1/2, INTRO1/2, Vari1-4) ---
    ('LABEL_E1D7A0', 'PtrTbl_StylePatternLongNames', 'Pointer table: style pattern long name strings'),
    ('LABEL_E1D808', 'StrStylePatt_All',            'Style pattern long name:      ALL'),
    ('LABEL_E1D818', 'StrStylePatt_Ending2',        'Style pattern long name:   ENDING2'),
    ('LABEL_E1D828', 'StrStylePatt_Ending1',        'Style pattern long name:   ENDING1'),
    ('LABEL_E1D838', 'StrStylePatt_FillIn2',        'Style pattern long name:   FILL IN 2'),
    ('LABEL_E1D848', 'StrStylePatt_FillIn1',        'Style pattern long name:   FILL IN 1'),
    ('LABEL_E1D858', 'StrStylePatt_Intro2',         'Style pattern long name:    INTRO2'),
    ('LABEL_E1D868', 'StrStylePatt_Intro1',         'Style pattern long name:    INTRO1'),
    ('LABEL_E1D878', 'StrStylePatt_Vari4',          'Style pattern long name:    Vari4'),
    ('LABEL_E1D888', 'StrStylePatt_Vari3',          'Style pattern long name:    Vari3'),
    ('LABEL_E1D898', 'StrStylePatt_Vari2',          'Style pattern long name:    Vari2'),
    ('LABEL_E1D8A8', 'StrStylePatt_Vari1',          'Style pattern long name:    Vari1'),
    ('LABEL_E1D8B8', 'StrStylePatt_V4FillIn2',      'Style pattern long name: Vari4 FILL IN2'),
    ('LABEL_E1D8C8', 'StrStylePatt_V4FillIn1',      'Style pattern long name: Vari4 FILL IN1'),
    ('LABEL_E1D8D8', 'StrStylePatt_V3FillIn2',      'Style pattern long name: Vari3 FILL IN2'),
    ('LABEL_E1D8E8', 'StrStylePatt_V3FillIn1',      'Style pattern long name: Vari3 FILL IN1'),
    ('LABEL_E1D8F8', 'StrStylePatt_V2FillIn2',      'Style pattern long name: Vari2 FILL IN2'),
    ('LABEL_E1D908', 'StrStylePatt_V2FillIn1',      'Style pattern long name: Vari2 FILL IN1'),
    ('LABEL_E1D918', 'StrStylePatt_V1FillIn2',      'Style pattern long name: Vari1 FILL IN2'),
    ('LABEL_E1D928', 'StrStylePatt_V1FillIn1',      'Style pattern long name: Vari1 FILL IN1'),
    ('LABEL_E1D938', 'StrStylePatt_Ending2b',       'Style pattern long name:   ENDING2 (second set)'),
    ('LABEL_E1D948', 'StrStylePatt_Ending1b',       'Style pattern long name:   ENDING1 (second set)'),
    ('LABEL_E1D958', 'StrStylePatt_Intro2b',        'Style pattern long name:    INTRO2 (second set)'),
    ('LABEL_E1D968', 'StrStylePatt_Intro1b',        'Style pattern long name:    INTRO1 (second set)'),
    ('LABEL_E1D978', 'StrStylePatt_Vari4b',         'Style pattern long name:    Vari4 (second set)'),
    ('LABEL_E1D988', 'StrStylePatt_Vari3b',         'Style pattern long name:    Vari3 (second set)'),
    ('LABEL_E1D998', 'StrStylePatt_Vari2b',         'Style pattern long name:    Vari2 (second set)'),
    ('LABEL_E1D9A8', 'StrStylePatt_Vari1b',         'Style pattern long name:    Vari1 (second set)'),

    # --- Rhythm memory / custom slot name pointer table ---
    ('LABEL_E1D9B8', 'PtrTbl_RhySlotLongNames',    'Pointer table: rhythm memory/custom slot long names'),
    ('LABEL_E1DA30', 'StrRhySlot_Custom20',         'Rhythm slot name: CUSTOM:20'),
    ('LABEL_E1DA3A', 'StrRhySlot_Custom19',         'Rhythm slot name: CUSTOM:19'),
    ('LABEL_E1DA44', 'StrRhySlot_Custom18',         'Rhythm slot name: CUSTOM:18'),
    ('LABEL_E1DA4E', 'StrRhySlot_Custom17',         'Rhythm slot name: CUSTOM:17'),
    ('LABEL_E1DA58', 'StrRhySlot_Custom16',         'Rhythm slot name: CUSTOM:16'),
    ('LABEL_E1DA62', 'StrRhySlot_Custom15',         'Rhythm slot name: CUSTOM:15'),
    ('LABEL_E1DA6C', 'StrRhySlot_Custom14',         'Rhythm slot name: CUSTOM:14'),
    ('LABEL_E1DA76', 'StrRhySlot_Custom13',         'Rhythm slot name: CUSTOM:13'),
    ('LABEL_E1DA80', 'StrRhySlot_Custom12',         'Rhythm slot name: CUSTOM:12'),
    ('LABEL_E1DA8A', 'StrRhySlot_Custom11',         'Rhythm slot name: CUSTOM:11'),
    ('LABEL_E1DA94', 'StrRhySlot_Custom10',         'Rhythm slot name: CUSTOM:10'),
    ('LABEL_E1DA9E', 'StrRhySlot_Custom09',         'Rhythm slot name: CUSTOM: 9'),
    ('LABEL_E1DAA8', 'StrRhySlot_Custom08',         'Rhythm slot name: CUSTOM: 8'),
    ('LABEL_E1DAB2', 'StrRhySlot_Custom07',         'Rhythm slot name: CUSTOM: 7'),
    ('LABEL_E1DABC', 'StrRhySlot_Custom06',         'Rhythm slot name: CUSTOM: 6'),
    ('LABEL_E1DAC6', 'StrRhySlot_Custom05',         'Rhythm slot name: CUSTOM: 5'),
    ('LABEL_E1DAD0', 'StrRhySlot_Custom04',         'Rhythm slot name: CUSTOM: 4'),
    ('LABEL_E1DADA', 'StrRhySlot_Custom03',         'Rhythm slot name: CUSTOM: 3'),
    ('LABEL_E1DAE4', 'StrRhySlot_Custom02',         'Rhythm slot name: CUSTOM: 2'),
    ('LABEL_E1DAEE', 'StrRhySlot_Custom01',         'Rhythm slot name: CUSTOM: 1'),
    # aki = placeholder/debug name in developer's native language
    ('LABEL_E1DAF8', 'StrRhySlot_AkiPlaceholder6',  'Rhythm slot placeholder name (aki = developer name)'),
    ('LABEL_E1DB02', 'StrRhySlot_AkiPlaceholder5',  'Rhythm slot placeholder name'),
    ('LABEL_E1DB0C', 'StrRhySlot_AkiPlaceholder4',  'Rhythm slot placeholder name'),
    ('LABEL_E1DB16', 'StrRhySlot_AkiPlaceholder3',  'Rhythm slot placeholder name'),
    ('LABEL_E1DB20', 'StrRhySlot_AkiPlaceholder2',  'Rhythm slot placeholder name'),
    ('LABEL_E1DB2A', 'StrRhySlot_AkiPlaceholder1',  'Rhythm slot placeholder name'),
    ('LABEL_E1DB34', 'StrRhySlot_AkiPlaceholderX',  'Rhythm slot placeholder name'),
    ('LABEL_E1DB3E', 'StrRhySlot_MemoryC',          'Rhythm slot name: MEMORY C'),
    ('LABEL_E1DB48', 'StrRhySlot_MemoryB',          'Rhythm slot name: MEMORY B'),
    ('LABEL_E1DB52', 'StrRhySlot_MemoryA',          'Rhythm slot name: MEMORY A'),

    # --- Style section short name table (second set, 7-char, for different display context) ---
    ('LABEL_E1DB80', 'PtrTbl_StyleSectShortNames2', 'Pointer table: style section short names (set 2)'),
    ('LABEL_E1DC00', 'StrStyleSect2_C_All',         'Style section short name (set2): C-ALL'),
    ('LABEL_E1DC08', 'StrStyleSect2_B_All',         'Style section short name (set2): B-ALL'),
    ('LABEL_E1DC10', 'StrStyleSect2_A_All',         'Style section short name (set2): A-ALL'),
    ('LABEL_E1DC18', 'StrStyleSect2_C_End2',        'Style section short name (set2): C-END2'),
    ('LABEL_E1DC20', 'StrStyleSect2_C_End1',        'Style section short name (set2): C-END1'),
    ('LABEL_E1DC28', 'StrStyleSect2_C_Fill2',       'Style section short name (set2): C-FILL2'),
    ('LABEL_E1DC30', 'StrStyleSect2_C_Fill1',       'Style section short name (set2): C-FILL1'),
    ('LABEL_E1DC38', 'StrStyleSect2_C_Int2',        'Style section short name (set2): C-INT2'),
    ('LABEL_E1DC40', 'StrStyleSect2_C_Int1',        'Style section short name (set2): C-INT1'),
    ('LABEL_E1DC48', 'StrStyleSect2_B_End2',        'Style section short name (set2): B-END2'),
    ('LABEL_E1DC50', 'StrStyleSect2_B_End1',        'Style section short name (set2): B-END1'),
    ('LABEL_E1DC58', 'StrStyleSect2_B_Fill2',       'Style section short name (set2): B-FILL2'),
    ('LABEL_E1DC60', 'StrStyleSect2_B_Fill1',       'Style section short name (set2): B-FILL1'),
    ('LABEL_E1DC68', 'StrStyleSect2_B_Int2',        'Style section short name (set2): B-INT2'),
    ('LABEL_E1DC70', 'StrStyleSect2_B_Int1',        'Style section short name (set2): B-INT1'),
    ('LABEL_E1DC78', 'StrStyleSect2_A_End2',        'Style section short name (set2): A-END2'),
    ('LABEL_E1DC80', 'StrStyleSect2_A_End1',        'Style section short name (set2): A-END1'),
    ('LABEL_E1DC88', 'StrStyleSect2_A_Fill2',       'Style section short name (set2): A-FILL2'),
    ('LABEL_E1DC90', 'StrStyleSect2_A_Fill1',       'Style section short name (set2): A-FILL1'),
    ('LABEL_E1DC98', 'StrStyleSect2_A_Int2',        'Style section short name (set2): A-INT2'),
    ('LABEL_E1DCA0', 'StrStyleSect2_A_Int1',        'Style section short name (set2): A-INT1'),
    ('LABEL_E1DCA8', 'StrStyleSect2_C_Vari4',       'Style section short name (set2): C-vari4'),
    ('LABEL_E1DCB0', 'StrStyleSect2_C_Vari3',       'Style section short name (set2): C-vari3'),
    ('LABEL_E1DCB8', 'StrStyleSect2_C_Vari2',       'Style section short name (set2): C-vari2'),
    ('LABEL_E1DCC0', 'StrStyleSect2_C_Vari1',       'Style section short name (set2): C-vari1'),
    ('LABEL_E1DCC8', 'StrStyleSect2_B_Vari4',       'Style section short name (set2): B-vari4'),
    ('LABEL_E1DCD0', 'StrStyleSect2_B_Vari3',       'Style section short name (set2): B-vari3'),
    ('LABEL_E1DCD8', 'StrStyleSect2_B_Vari2',       'Style section short name (set2): B-vari2'),
    ('LABEL_E1DCE0', 'StrStyleSect2_B_Vari1',       'Style section short name (set2): B-vari1'),
    ('LABEL_E1DCE8', 'StrStyleSect2_A_Vari4',       'Style section short name (set2): A-vari4'),
    ('LABEL_E1DCF0', 'StrStyleSect2_A_Vari3',       'Style section short name (set2): A-vari3'),
    ('LABEL_E1DCF8', 'StrStyleSect2_A_Vari2',       'Style section short name (set2): A-vari2'),
    ('LABEL_E1DD00', 'StrStyleSect2_A_Vari1',       'Style section short name (set2): A-vari1'),

    # --- Track status display strings ---
    ('LABEL_E1DD14', 'StrTrackMute',               'Track status string: MUTE'),
    ('LABEL_E1DD1A', 'StrTrackRec',                'Track status string: REC '),
    ('LABEL_E1DD20', 'StrTrackBlank',              'Track status string: blank (spaces)'),

    # --- Note name/position pointer table (flat-note display: ~ab, ~ac, ~ad etc.) ---
    ('LABEL_E1DD26', 'PtrTbl_NotePositionStrs',    'Pointer table: note position / accidental strings'),
    # Strings use ~ escape sequences for special characters (ab=flat, b8=symbol)
    ('LABEL_E1DD46', 'StrNotePos_Natural',         'Note position: natural (no accidental)'),
    ('LABEL_E1DD4C', 'StrNotePos_FlatAlt',         'Note position: ~ab (flat alternate)'),
    ('LABEL_E1DD52', 'StrNotePos_FlatAltB8',       'Note position: ~ab~b8 (flat+symbol)'),
    ('LABEL_E1DD5A', 'StrNotePos_AcNatural',       'Note position: ~ac natural'),
    ('LABEL_E1DD60', 'StrNotePos_AcFlatB8',        'Note position: ~ac~b8'),
    ('LABEL_E1DD68', 'StrNotePos_AdNatural',       'Note position: ~ad natural'),
    ('LABEL_E1DD6E', 'StrNotePos_AdFlatB8',        'Note position: ~ad~b8'),
    ('LABEL_E1DD76', 'StrNotePos_Off',             'Note position: OFF'),

    # --- Style variation group code table (A/B/C single-character codes, indexed by pattern) ---
    ('LABEL_E1DD86', 'PtrTbl_StyleVarGroupCodes',  'Pointer table: style variation group code bytes (A/B/C)'),
    # These entries are 2-byte records: (group_letter, 0x00) for A/B/C grouping
    ('LABEL_E1DE0A', 'StyleVarGrp_CEnd2',          'Style variation group code: C (END2)'),
    ('LABEL_E1DE0C', 'StyleVarGrp_BEnd2',          'Style variation group code: B (END2)'),
    ('LABEL_E1DE0E', 'StyleVarGrp_AEnd2',          'Style variation group code: A (END2)'),
    ('LABEL_E1DE10', 'StyleVarGrp_CEnd1',          'Style variation group code: C (END1)'),
    ('LABEL_E1DE12', 'StyleVarGrp_CInt2',          'Style variation group code: C (INT2)'),
    ('LABEL_E1DE14', 'StyleVarGrp_CInt1',          'Style variation group code: C (INT1)'),
    ('LABEL_E1DE16', 'StyleVarGrp_CFill2',         'Style variation group code: C (FILL2)'),
    ('LABEL_E1DE18', 'StyleVarGrp_CFill1',         'Style variation group code: C (FILL1)'),
    ('LABEL_E1DE1A', 'StyleVarGrp_CVari4',         'Style variation group code: C (Vari4)'),
    ('LABEL_E1DE1C', 'StyleVarGrp_BEnd1',          'Style variation group code: B (END1)'),
    ('LABEL_E1DE1E', 'StyleVarGrp_BInt2',          'Style variation group code: B (INT2)'),
    ('LABEL_E1DE20', 'StyleVarGrp_BInt1',          'Style variation group code: B (INT1)'),
    ('LABEL_E1DE22', 'StyleVarGrp_BFill2',         'Style variation group code: B (FILL2)'),
    ('LABEL_E1DE24', 'StyleVarGrp_BFill1',         'Style variation group code: B (FILL1)'),
    ('LABEL_E1DE26', 'StyleVarGrp_BVari4',         'Style variation group code: B (Vari4)'),
    ('LABEL_E1DE28', 'StyleVarGrp_AVari4',         'Style variation group code: A (Vari4)'),
    ('LABEL_E1DE2A', 'StyleVarGrp_AInt2',          'Style variation group code: A (INT2)'),
    ('LABEL_E1DE2C', 'StyleVarGrp_AInt1',          'Style variation group code: A (INT1)'),
    ('LABEL_E1DE2E', 'StyleVarGrp_AFill2',         'Style variation group code: A (FILL2)'),
    ('LABEL_E1DE30', 'StyleVarGrp_AFill1',         'Style variation group code: A (FILL1)'),
    ('LABEL_E1DE32', 'StyleVarGrp_AVari3',         'Style variation group code: A (Vari3)'),
    ('LABEL_E1DE34', 'StyleVarGrp_CVari3',         'Style variation group code: C (Vari3)'),
    ('LABEL_E1DE36', 'StyleVarGrp_CVari2',         'Style variation group code: C (Vari2)'),
    ('LABEL_E1DE38', 'StyleVarGrp_CVari1',         'Style variation group code: C (Vari1)'),
    ('LABEL_E1DE3A', 'StyleVarGrp_BEnd1b',         'Style variation group code: C (extra)'),
    ('LABEL_E1DE3C', 'StyleVarGrp_BVari3',         'Style variation group code: B (Vari3)'),
    ('LABEL_E1DE3E', 'StyleVarGrp_BVari2',         'Style variation group code: B (Vari2)'),
    ('LABEL_E1DE40', 'StyleVarGrp_BVari1',         'Style variation group code: B (Vari1)'),
    ('LABEL_E1DE42', 'StyleVarGrp_BEnd1c',         'Style variation group code: B (extra)'),
    ('LABEL_E1DE44', 'StyleVarGrp_AVari2',         'Style variation group code: A (Vari2)'),
    ('LABEL_E1DE46', 'StyleVarGrp_AVari1',         'Style variation group code: A (Vari1)'),
    ('LABEL_E1DE48', 'StyleVarGrp_AEnd1',          'Style variation group code: A (END1)'),
    ('LABEL_E1DE4A', 'StyleVarGrp_AEnd2',          'Style variation group code: A (END2) + layout data'),

    # --- Style genre name strings (14-char, centered) ---
    ('LABEL_E1DE5A', 'StrGenre_Waltz',             'Style genre name: Waltz'),
    ('LABEL_E1DE6C', 'StrGenre_RockBallad',        'Style genre name: Rock Ballad'),
    ('LABEL_E1DE7E', 'StrGenre_Country',           'Style genre name: Country'),
    ('LABEL_E1DE90', 'StrGenre_Latin',             'Style genre name: Latin'),
    ('LABEL_E1DEA2', 'StrGenre_Swing',             'Style genre name: Swing'),
    ('LABEL_E1DEB4', 'StrGenre_MarchPolka',        'Style genre name: March/Polka'),
    ('LABEL_E1DEC6', 'StrGenre_JazzFusion',        'Style genre name: Jazz Fusion'),
    ('LABEL_E1DED8', 'StrGenre_DancePop',          'Style genre name: Dance Pop'),
    ('LABEL_E1DEEA', 'StrGenre_16Beat',            'Style genre name: 16 Beat'),
    ('LABEL_E1DEFC', 'StrGenre_8Beat',             'Style genre name: 8 Beat'),

    # --- Bank short name strings (Compile2, Compile1, User2, User1) ---
    ('LABEL_E1DF34', 'StrBankShort_Compile2',      'Bank short name: COMPILE2'),
    ('LABEL_E1DF3E', 'StrBankShort_Compile1',      'Bank short name: COMPILE1'),
    ('LABEL_E1DF48', 'StrBankShort_User2',         'Bank short name: User2   '),
    ('LABEL_E1DF52', 'StrBankShort_User1',         'Bank short name: User1   '),

    # --- MSP compile bank label strings (used in MSP backslot compile display) ---
    ('LABEL_E1DF70', 'PtrTbl_MspCompileBankLabels', 'Pointer table: MSP compile bank label strings'),
    ('LABEL_E1DF80', 'StrMspCmpBank2Label',         'MSP compile bank label: COMPILE Bank2'),
    ('LABEL_E1DF94', 'StrMspCmpBank1Label',         'MSP compile bank label: COMPILE Bank1'),
    ('LABEL_E1DFA8', 'StrMspUserBank2Label',        'MSP user bank label: User Bank 2'),
    ('LABEL_E1DFBC', 'StrMspUserBank1Label',        'MSP user bank label: User Bank 1'),

    # --- Music style bank name pointer table (long form, 16-char, for selection display) ---
    ('LABEL_E1DFD0', 'PtrTbl_MusicStyleBankNames',  'Pointer table: music style bank long name strings'),
    ('LABEL_E1E01C', 'StrMsBankLong_CtrlPreset2',   'Music style bank long name: Control Preset 2'),
    ('LABEL_E1E02E', 'StrMsBankLong_CtrlPreset1',   'Music style bank long name: Control Preset 1'),
    ('LABEL_E1E040', 'StrMsBankLong_CompileBank2',  'Music style bank long name: Compile bank 2'),
    ('LABEL_E1E052', 'StrMsBankLong_CompileBank1',  'Music style bank long name: Compile bank 1'),
    ('LABEL_E1E064', 'StrMsBankLong_UserBank2',     'Music style bank long name: User Bank 2'),
    ('LABEL_E1E076', 'StrMsBankLong_UserBank1',     'Music style bank long name: User Bank 1'),
    ('LABEL_E1E088', 'StrMsBankLong_HitCrescendo',  'Music style bank long name: Hit & Crescendo'),
    ('LABEL_E1E09A', 'StrMsBankLong_Latin',         'Music style bank long name: Latin'),
    ('LABEL_E1E0AC', 'StrMsBankLong_Jazz',          'Music style bank long name: Jazz'),
    ('LABEL_E1E0BE', 'StrMsBankLong_Funk',          'Music style bank long name: Funk'),
    ('LABEL_E1E0D0', 'StrMsBankLong_Dance',         'Music style bank long name: Dance'),
    ('LABEL_E1E0E2', 'StrMsBankLong_Rock2',         'Music style bank long name: Rock 2'),
    ('LABEL_E1E0F4', 'StrMsBankLong_Rock1',         'Music style bank long name: Rock 1'),
    ('LABEL_E1E106', 'StrMsBankLong_Arpeggio',      'Music style bank long name: Arpeggio'),
    ('LABEL_E1E118', 'StrMsBankLong_Entertainer',   'Music style bank long name: Entertainer'),
    ('LABEL_E1E12A', 'StrMsBankLong_Movie',         'Music style bank long name: Movie'),
    ('LABEL_E1E13C', 'StrMsBankLong_Comical',       'Music style bank long name: Comical'),
    ('LABEL_E1E14E', 'StrMsBankLong_Effect2',       'Music style bank long name: Effect 2'),
    ('LABEL_E1E160', 'StrMsBankLong_Effect1',       'Music style bank long name: Effect 1'),

    # --- Music style bank name pointer table (second set, same content) ---
    ('LABEL_E1E172', 'PtrTbl_MusicStyleBankNames2', 'Pointer table: music style bank long name strings (set 2)'),
    ('LABEL_E1E1AE', 'StrMsBankLong2_User2',        'Music style bank long name (set2): User 2'),
    ('LABEL_E1E1C0', 'StrMsBankLong2_User1',        'Music style bank long name (set2): User 1'),
    ('LABEL_E1E1D2', 'StrMsBankLong2_HitCrescendo', 'Music style bank long name (set2): Hit & Crescendo'),
    ('LABEL_E1E1E4', 'StrMsBankLong2_Latin',        'Music style bank long name (set2): Latin'),
    ('LABEL_E1E1F6', 'StrMsBankLong2_Jazz',         'Music style bank long name (set2): Jazz'),
    ('LABEL_E1E208', 'StrMsBankLong2_Funk',         'Music style bank long name (set2): Funk'),
    ('LABEL_E1E21A', 'StrMsBankLong2_Dance',        'Music style bank long name (set2): Dance'),
    ('LABEL_E1E22C', 'StrMsBankLong2_Rock2',        'Music style bank long name (set2): Rock 2'),
    ('LABEL_E1E23E', 'StrMsBankLong2_Rock1',        'Music style bank long name (set2): Rock 1'),
    ('LABEL_E1E250', 'StrMsBankLong2_Arpeggio',     'Music style bank long name (set2): Arpeggio'),
    ('LABEL_E1E262', 'StrMsBankLong2_Entertainer',  'Music style bank long name (set2): Entertainer'),
    ('LABEL_E1E274', 'StrMsBankLong2_Movie',        'Music style bank long name (set2): Movie'),
    ('LABEL_E1E286', 'StrMsBankLong2_Comical',      'Music style bank long name (set2): Comical'),
    ('LABEL_E1E298', 'StrMsBankLong2_Effect2',      'Music style bank long name (set2): Effect 2'),
    ('LABEL_E1E2AA', 'StrMsBankLong2_Effect1',      'Music style bank long name (set2): Effect 1'),

    # --- Compile bank display strings ---
    ('LABEL_E1E2D8', 'StrCompileBank2',            'Compile bank display string: COMPILE BANK:2'),
    ('LABEL_E1E2E8', 'StrCompileBank1',            'Compile bank display string: COMPILE BANK:1'),

    # --- Sync-to-rhythm mode strings ---
    ('LABEL_E1E320', 'StrSyncToRhythm',            'Sync mode string: SYNC TO RHYTHM'),
    ('LABEL_E1E332', 'StrInstantStart',            'Sync mode string: INSTANT START'),
]


def main():
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(base, 'maincpu', 'kn5000_v10_program.s')
    with open(src, 'rb') as f:
        content = f.read().decode('latin-1')
    renamed = 0
    for old_label, new_label, comment in RENAMES:
        if old_label not in content:
            print(f'  WARNING: {old_label} not found, skipping')
            continue
        refs = len(re.findall(r'\b' + re.escape(old_label) + r'\b', content))
        new_content = re.sub(r'\b' + re.escape(old_label) + r'\b', new_label, content)
        if new_content != content:
            content = new_content
            renamed += 1
            print(f'  {old_label:25s} -> {new_label:40s} ({refs} refs)')
    with open(src, 'wb') as f:
        f.write(content.encode('latin-1'))
    print(f'\nRenamed {renamed} labels in maincpu')


if __name__ == '__main__':
    main()
