# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FBB800\b/PartParam_StepFieldById/g
s/\bsub_FBB93C\b/PartParam_EnterFieldById/g
s/\bsub_FBAC00\b/SeqFile_Load/g
s/\bsub_FBB199\b/SeqFile_ProbeSqfHeader/g
s/\bsub_FBB20B\b/SeqFile_LoadAllBanks/g
s/\bsub_FBAD07\b/SeqFile_LoadSongBlocks/g
s/\bsub_FBAD82\b/BStore_RebuildFreeChain/g
s/\bsub_FBAE10\b/BStore_InitFreeBlock/g
s/\bsub_FBAE2A\b/BStore_FreeHeadBlockAddr/g
s/\bsub_FBAE3B\b/BStore_FreeHeadIndex/g
s/\bsub_FBAE49\b/BStore_RelocateBlockNumber/g
s/\bsub_FBADEA\b/BStore_StashFreeChain/g
s/\bsub_FBADFD\b/BStore_UnstashFreeChain/g
s/\bsub_FBB135\b/BStore_BlockAddr/g
s/\bsub_FBB0C3\b/BStore_CurrentBankCopyAddr/g
s/\bsub_FBB0D6\b/BStore_DiskBankCopyAddr/g
s/\bsub_FBAE5A\b/SeqFile_Save/g
s/\bsub_FBB2D5\b/SeqFile_SaveAllBanks/g
s/\bsub_FBAF42\b/SeqFile_WriteSeqCompacted/g
s/\bsub_FBB04F\b/SeqFile_FlushStagingBlocks/g
s/\bsub_FBB07E\b/SeqFile_WriteEmptySeq/g
s/\bsub_FBB0A1\b/SeqFile_SetSeqStagingWindow/g
s/\bsub_FBB0E9\b/SeqFile_ClearStagingBlockFlags/g
s/\bsub_FBB0FF\b/SeqFile_LinkStagingBlocks/g
s/\bsub_FBB11F\b/SeqFile_StageBlock/g
s/\bsub_FBB146\b/SeqFile_StagingSlotAddr/g
s/\bsub_FBB159\b/SeqFile_RelinkStagedBlock/g
s/\bsub_FE237B\b/Disk_LoadSqfToWorkspace/g
s/\bsub_FE233A\b/Disk_LoadSeqToHeap/g
s/\bsub_FE2CC7\b/Disk_SaveSqfFromStaging/g
s/\bsub_FE2C64\b/Disk_SaveSeqFile/g
s/\bsub_FE1BEB\b/Disk_LoadSqfToWorkspace_Entry/g
s/\bsub_FE1BF3\b/Disk_LoadSeqToHeap_Entry/g
s/\bsub_FE1BFB\b/Disk_SaveSqfFromStaging_Entry/g
s/\bsub_FE1C03\b/Disk_SaveSeqFile_Entry/g
s/\bsub_FE2D30\b/Disk_SetWindowStartToWorkspace/g
s/\bsub_FE2D9D\b/Disk_SetWindowEndToWorkspaceEnd/g
s/\bsub_FE2D1D\b/Disk_SetWindowStartToHeap/g
s/\bsub_FE2DC6\b/Disk_SetSeqLengthFromWorkspace/g
s/\bsub_FE2DA7\b/Disk_SetWindowEndToHeapPlusSeqLength/g
s/\bsub_FE2D26\b/Disk_SetWindowStartToSqfStaging/g
s/\bsub_FE2D93\b/Disk_SetWindowEndToSqfStagingEnd/g
