# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F7B4BF\b/MeasureInsert_InitFields/g
s/\bsub_F7B852\b/MeasureInsert_LoadSavedFields/g
s/\bsub_F7B53D\b/MeasureInsert_StepFieldUp/g
s/\bsub_F7B58C\b/MeasureInsert_StepFieldDown/g
s/\bsub_F7B5F5\b/MeasureInsert_StepFromTrack/g
s/\bsub_F7B65E\b/MeasureInsert_StepFirstMeasure/g
s/\bsub_F7B694\b/MeasureInsert_StepLastMeasure/g
s/\bsub_F7B6CE\b/MeasureInsert_StepToTrack/g
s/\bsub_F7B737\b/MeasureInsert_StepStartMeasure/g
s/\bsub_F7B74C\b/MeasureInsert_StepRepeat/g
s/\bsub_F7B8DC\b/MeasureC0py_InitFields/g
s/\bsub_F7BC73\b/MeasureC0py_LoadSavedFields/g
s/\bsub_F7B95A\b/MeasureC0py_StepFieldUp/g
s/\bsub_F7B9AB\b/MeasureC0py_StepFieldDown/g
s/\bsub_F7BA16\b/MeasureC0py_StepFromTrack/g
s/\bsub_F7BA7F\b/MeasureC0py_StepFirstMeasure/g
s/\bsub_F7BAB5\b/MeasureC0py_StepLastMeasure/g
s/\bsub_F7BAEF\b/MeasureC0py_StepToTrack/g
s/\bsub_F7BB58\b/MeasureC0py_StepStartMeasure/g
s/\bsub_F7BB6D\b/MeasureC0py_StepRepeat/g
s/\bsub_F7BFEA\b/Quantize_InitFields/g
s/\bsub_F7C0F1\b/Quantize_StepFieldUp/g
s/\bsub_F7C17D\b/Quantize_StepFieldDown/g
s/\bsub_F7C13E\b/Quantize_ReturnToStageZero/g
s/\bsub_F7C1C1\b/Quantize_StepTrack/g
s/\bsub_F7C20B\b/Quantize_StepFirstMeasure/g
s/\bsub_F7C242\b/Quantize_StepLastMeasure/g
s/\bsub_F7C27C\b/Quantize_StepValue/g
s/\bsub_F7C2AB\b/Quantize_StepStrength/g
s/\bsub_F7C2D3\b/Quantize_StepWindow/g
s/\bsub_F7CAD2\b/AdvanceDelay_InitFields/g
s/\bsub_F7CB4A\b/AdvanceDelay_StepFieldUp/g
s/\bsub_F7CB90\b/AdvanceDelay_StepFieldDown/g
s/\bT_F429A8\b/T_MeasureInsert_InitFields/g
s/\bT_F429C8\b/T_MeasureInsert_StepFieldUp/g
s/\bT_F429CC\b/T_MeasureInsert_StepFieldDown/g
s/\bT_F429D8\b/T_MeasureC0py_InitFields/g
s/\bT_F429F8\b/T_MeasureC0py_StepFieldUp/g
s/\bT_F429FC\b/T_MeasureC0py_StepFieldDown/g
s/\bT_F42908\b/T_Quantize_InitFields/g
s/\bT_F42928\b/T_Quantize_StepFieldUp/g
s/\bT_F4292C\b/T_Quantize_StepFieldDown/g
s/\bT_F42934\b/T_Quantize_ReturnToStageZero/g
s/\bT_F42A60\b/T_AdvanceDelay_InitFields/g
s/\bT_F42A78\b/T_AdvanceDelay_StepFieldUp/g
s/\bT_F42A7C\b/T_AdvanceDelay_StepFieldDown/g
