# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F7A404\b/BStore_FreeChain_Veneer/g
s/\bsub_F4A7FE\b/CycleRecord_AbortMemoryFull/g
s/\bsub_F4C85A\b/BStore_LatchBlockCount/g
s/\bsub_F4C89E\b/BStore_FindFreeBlockUp/g
s/\bsub_F4C9B4\b/BStore_ThreadFreeListFrom/g
s/\bsub_F6B50C\b/BStore_WriteBytesAtSongPosition/g
s/\bsub_FAB5EB\b/ParamB0_PublishPendingFields/g
s/\bsub_FC1E68\b/CreatorSelect_ReadSlotLabelIds/g
s/\bsub_F36B2F\b/SysExThirdRegion_LocateDrumModellingChunk/g
s/\bsub_F44C37\b/Seq_LocateNowIfPending/g
s/\bsub_F45263\b/SeqRecord_ResetSlotLists/g
s/\bsub_F45812\b/SeqRecord_AllocTakeChains/g
s/\bsub_F48707\b/CycleRecord_CaptureStartCursors/g
s/\bsub_F487A7\b/CycleRecord_CaptureEndCursors/g
s/\bsub_F4980D\b/SeqRecord_LoadTakeCursor/g
s/\bsub_F49838\b/SeqRecord_SaveTakeCursor/g
s/\bsub_F4A813\b/CycleRecord_FillTakeChain2WithBeatMarks/g
s/\bsub_F4A976\b/CycleRecord_CopyPaddedRangeToTakeChain2/g
s/\bsub_F4AA88\b/CycleRecord_CopyRangeToTakeChain2/g
s/\bsub_F4B160\b/CycleRecord_PadTrackPastCycleEnd/g
s/\bsub_F4B2AB\b/CycleRecord_SaveTrackEndCursor/g
s/\bsub_F4B2D5\b/CycleRecord_AppendUnplayedRest/g
s/\bsub_F4B36E\b/CycleRecord_SetUpSplice/g
s/\bsub_F4C863\b/BStore_FindUsedBlockDown/g
s/\bsub_F4C8DD\b/BStore_RelocateBlock/g
s/\bsub_F4D000\b/BStore_AdvanceCursorForWrite_B/g
s/\bsub_F4D011\b/BStore_ClearTrackIfInRange/g
s/\bsub_F4D014\b/BStore_SpliceChainIntoTrack/g
s/\bsub_F4D01D\b/BStore_BlockAddrFromHL/g
s/\bsub_F4E4C8\b/StepRecordPartSelect_ChooseTrack/g
s/\bsub_F4E50B\b/TrackClear_ToggleTrackSelection/g
s/\bsub_F55FB3\b/CycleRecordScreen_BlinkStartAndEndMeasureReadouts/g
s/\bsub_F55FD1\b/CyclePlayScreen_BlinkStartAndEndMeasureReadouts/g
s/\bsub_F5DBD0\b/Quantize_ApplyRoundMapToTrack/g
s/\bsub_F5EBD4\b/BStore_WriteCursorAdvance/g
s/\bsub_F5F9C1\b/SongEdit_RestoreDestTrackEnd/g
s/\bsub_F60267\b/TrackMerge_CopySource1ToMark/g
s/\bsub_F60272\b/TrackMerge_CopySource2ToMark/g
s/\bsub_F6027D\b/TrackMerge_EmitCommonMark/g
s/\bsub_F602F0\b/TrackMerge_FetchSource2Event/g
s/\bsub_F60338\b/TrackMerge_FetchSource1Event/g
s/\bsub_F60380\b/TrackMerge_CopySource2Event/g
s/\bsub_F603E9\b/TrackMerge_CopySource1Event/g
s/\bsub_F60514\b/TrackMerge_LoadAndFreeBlock/g
s/\bsub_F60548\b/TrackMerge_DetachSourceTrack/g
s/\bsub_F6068D\b/Vel0cityChange_ApplyToTrack/g
s/\bsub_F60C2C\b/Transp0se_ApplyToTrack/g
s/\bsub_F60E40\b/N0teChange_ApplyToTrack/g
s/\bsub_F615C2\b/S0ngC0py_CopyAllTracks/g
s/\bsub_F61880\b/S0ngC0py_AllocDestHeadBlock/g
s/\bsub_F61AF7\b/AdvanceDelay_ApplyToTrack/g
s/\bsub_F62C0C\b/BStore_CopyRangeForward_Call/g
s/\bsub_F63280\b/BStore_CopyAcrossBlocksBackward/g
s/\bsub_F632A9\b/BStore_CopySrcToPrevBlock/g
s/\bsub_F632E0\b/BStore_CopyDestToPrevBlock/g
s/\bsub_F63C06\b/TrackMerge_RewriteSource2ForPart/g
s/\bsub_F63CE0\b/BStore_RewriteTrackForPart/g
s/\bsub_F6487D\b/SongEdit_PadDestTrackToMeasure/g
s/\bsub_F64B7A\b/SongGmFlag_ApplyAndRebuildRouting/g
s/\bsub_F6682C\b/TrackAssignPresets_ApplyToAllSongs/g
s/\bsub_F68271\b/StepRecordKind3Sub12_ButtonDispatch/g
s/\bsub_F68575\b/StepRecord_BlankPrevRowText/g
s/\bsub_F68587\b/StepRecord_BlankNextRowText/g
s/\bsub_F6859F\b/StepRecordKind3Sub13_ButtonDispatch/g
s/\bsub_F68951\b/StepRecord_MainLoopService/g
s/\bsub_F68B40\b/StepRecord_CursorForward/g
s/\bsub_F69019\b/StepRecord_EraseTimeSig/g
s/\bsub_F6908B\b/StepRecord_ApplyTimeSigChange/g
s/\bsub_F6940B\b/StepRecord_CursorToPrevMeasure/g
s/\bsub_F69442\b/StepRecord_CursorToNextMeasure/g
s/\bsub_F69811\b/StepRecord_CursorForwardByStepLength/g
s/\bsub_F6987E\b/StepRecord_NoteNumberDown/g
s/\bsub_F69887\b/StepRecord_StepNoteNumber/g
s/\bsub_F6997C\b/StepRecord_TempoDown/g
s/\bsub_F69998\b/StepRecord_StepTempo/g
s/\bsub_F69A67\b/StepRecord_ControlValueDown/g
s/\bsub_F69AFF\b/StepRecord_VelocityDown/g
s/\bsub_F69B76\b/StepRecord_AdjustEvent14BitValue/g
s/\bsub_F6A1F1\b/StepRecord_CursorBackToMeasureStart/g
s/\bsub_F6A7C5\b/StepRecord_AppendBeatMarks/g
s/\bsub_F6A7EB\b/StepRecord_CalcStepAndNoteLength/g
s/\bsub_F6A8AD\b/StepLength_AddToTick/g
s/\bsub_F6A908\b/StepRecord_AppendLatchedParamEvents/g
s/\bsub_F6A9E3\b/StepRecord_BeginSession/g
s/\bsub_F6ACF5\b/StepRecord_SelectUiPart/g
s/\bsub_F6AF58\b/StepRecord_Tick/g
s/\bsub_F6B77C\b/TrackCursor_StepOneEvent/g
s/\bsub_F6B905\b/BStore_ReadByteAtSongPositionPlusN/g
s/\bsub_F6BAFA\b/BStore_FreeChain_C/g
s/\bsub_F6C30A\b/StepRecord_RestoreSongPositionFromSlot/g
s/\bsub_F6C340\b/StepRecord_RestoreBeatPositionsFromSlot/g
s/\bsub_F6D40C\b/StepRecord_RepaintThenMsgLineControl/g
s/\bsub_F6D5BA\b/MsgLine_PutMeasureDigits/g
s/\bsub_F6D6D6\b/StepRecord_PaintPositionMarker_Call/g
s/\bsub_F6D963\b/MsgLine_PutPitchBendValue/g
s/\bsub_F6E9BB\b/StepRecord_ReadScanEvent/g
s/\bsub_F6F408\b/MidiFileL0ad_SelectSeqBankAndReadSmf/g
s/\bsub_F6F440\b/MidiFileSave_SelectSeqBankAndWriteSmf/g
s/\bsub_F6F8A5\b/BStore_SetGmFlagInCurrentBankCopy/g
s/\bsub_F6F8C7\b/SmfPart_ResetFineTuneAndBendRange/g
s/\bsub_F6F90C\b/Smf_ResetRpnState/g
s/\bsub_F6F9DE\b/Smf_AllocFirstBlockForAllTracks/g
s/\bsub_F6FA70\b/Smf_PutDefaultTimeSigOnMasterTrack/g
s/\bsub_F6FAB7\b/Smf_TerminateUsedTracks/g
s/\bsub_F6FAE8\b/Smf_ClearUnusedTracks/g
s/\bsub_F7083B\b/SmfCC_PutSustainParamEvent/g
s/\bsub_F70B22\b/SmfCC_PutRpnParamEvent/g
s/\bsub_F71203\b/Smf_PutBeatMarks/g
s/\bsub_F72822\b/Smf_AllocFirstBlockForTrackSlot/g
s/\bsub_F728A3\b/Smf_TerminateTrackSlot/g
s/\bsub_F72918\b/SmfExport_MergeUsedTracksIntoFirst/g
s/\bsub_F72A2B\b/Smf_MergeTracks/g
s/\bsub_F72F5C\b/Smf_SplitTrack1ByChannel/g
s/\bsub_F74885\b/MidiFileList_CheckSelectedEntryBlank/g
s/\bsub_F748AD\b/MidiFileList_FindFileName/g
