# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bScreenDispatch_FE9A4A\b/NoteEdit_ButtonTable/g
s/\bScreenDispatch_FE9BA4\b/DrumEdit_ButtonTable/g
s/\bScreenDispatch_FE857C\b/EditPartSelect_ButtonTable/g
s/\bScreenButton_Code25\b/ScreenButton_NoteEdit/g
s/\bScreenButton_Code28\b/ScreenButton_DrumEdit/g
s/\bScreenLeave_Code25\b/ScreenLeave_NoteEdit/g
s/\bScreenLeave_Code28\b/ScreenLeave_DrumEdit/g
s/\bsub_FE8565\b/ScreenButton_EditPartSelect/g
s/\bsub_FE9ACA\b/SoftKeyCol1_NoteEdit/g
s/\bsub_FE9AD8\b/SoftKeyCol2_NoteEdit/g
s/\bsub_FE9AE6\b/SoftKeyCol3_NoteEdit/g
s/\bsub_FE9AF4\b/SoftKeyCol4_NoteEdit/g
s/\bsub_FE9B02\b/SoftKeyCol5_NoteEdit/g
s/\bsub_FE9B10\b/SoftKeyCol6_NoteEdit/g
s/\bsub_FE9B1E\b/SoftKeyCol7_NoteEdit/g
s/\bsub_FE9B2C\b/SoftKeyCol8_NoteEdit/g
s/\bsub_FE9B3A\b/LcdKeyRow1_NoteEdit/g
s/\bsub_FE9B3E\b/LcdKeyRow2_NoteEdit/g
s/\bsub_FE9B4C\b/LcdKeyRow3_NoteEdit/g
s/\bsub_FE9B5A\b/LcdKeyRow4_NoteEdit/g
s/\bsub_FE9B5F\b/ExitKey_NoteEdit/g
s/\bsub_FE9B6C\b/NoteEdit_Button17/g
s/\bsub_FE9B70\b/NoteEdit_Button18/g
s/\bsub_FE9B74\b/NoteEdit_Button19/g
s/\bsub_FE9B78\b/NoteEdit_Button20/g
s/\bsub_FE9B7C\b/NoteEdit_Button21/g
s/\bsub_FE9B80\b/NoteEdit_Button22/g
s/\bsub_FE9B84\b/NoteEdit_Button23/g
s/\bsub_FE9B88\b/NoteEdit_Button24/g
s/\bsub_FE9C24\b/SoftKeyCol1_DrumEdit/g
s/\bsub_FE9C32\b/SoftKeyCol2_DrumEdit/g
s/\bsub_FE9C40\b/SoftKeyCol3_DrumEdit/g
s/\bsub_FE9C4E\b/SoftKeyCol4_DrumEdit/g
s/\bsub_FE9C5C\b/SoftKeyCol5_DrumEdit/g
s/\bsub_FE9C6A\b/SoftKeyCol6_DrumEdit/g
s/\bsub_FE9C78\b/SoftKeyCol7_DrumEdit/g
s/\bsub_FE9C86\b/SoftKeyCol8_DrumEdit/g
s/\bsub_FE9C8A\b/LcdKeyRow1_DrumEdit/g
s/\bsub_FE9C8E\b/LcdKeyRow2_DrumEdit/g
s/\bsub_FE9C9C\b/LcdKeyRow3_DrumEdit/g
s/\bsub_FE9CAA\b/LcdKeyRow4_DrumEdit/g
s/\bsub_FE9CAF\b/ExitKey_DrumEdit/g
s/\bsub_FE9CBC\b/DrumEdit_Button17/g
s/\bsub_FE9CC0\b/DrumEdit_Button18/g
s/\bsub_FE9CC4\b/DrumEdit_Button19/g
s/\bsub_FE9CC8\b/DrumEdit_Button20/g
s/\bsub_FE9CCC\b/DrumEdit_Button21/g
s/\bsub_FE9CD0\b/DrumEdit_Button22/g
s/\bsub_FE9CD4\b/DrumEdit_Button23/g
s/\bsub_FE8649\b/SoftKeyCol2_EditPartSelect/g
s/\bsub_FE8671\b/SoftKeyCol3_EditPartSelect/g
s/\bsub_FE8699\b/SoftKeyCol4_EditPartSelect/g
s/\bsub_FE86C1\b/SoftKeyCol5_EditPartSelect/g
s/\bsub_FE86E9\b/SoftKeyCol6_EditPartSelect/g
s/\bsub_FE8711\b/SoftKeyCol7_EditPartSelect/g
s/\bsub_FE8739\b/SoftKeyCol8_EditPartSelect/g
s/\bsub_FE8762\b/ExitKey_EditPartSelect/g
