# v142 sub-CPU floating-point library: labels renamed to the libm / runtime functions their
# own headers in subcpu_fp_math.s already identify ("NOTE: the name is wrong; it is pow()" etc.).
# Generated 2026-09-25 from the label list; one full-name rule per label, longest first.
# APPLIED ONCE -- do not re-run: the `; RENAMED 2026-09-25: was <old>` notes quote the old
# names on purpose, and a second pass would rewrite that history.  The same pairs, as
# old=new lines for assert_comments_preserved.py --rename-map, are in
# notes/subcpu-fp-libm-renames.map.
s/\bVoiceFloat_IterationLoop_LargeStep_NegPath\b/FP_pow_IntPower_LargeStep_NegPath/g
s/\bVoiceFloat_CompareAndConvert_AfterRange\b/FP_pow_AfterRange/g
s/\bVoiceFloat_IterationLoop_LargeStep_Copy\b/FP_pow_IntPower_LargeStep_Copy/g
s/\bVoiceFloat_ConvergenceLoop_StoreResult\b/FP_pow_ExpLog_StoreResult/g
s/\bVoiceFloat_IterationLoop_CheckContinue\b/FP_pow_IntPower_CheckContinue/g
s/\bVoiceFloat_IterationLoop_DifferentPath\b/FP_pow_IntPower_DifferentPath/g
s/\bVoiceFloat_IterationLoop_SmallStep_Add\b/FP_pow_IntPower_SmallStep_Add/g
s/\bVoiceFloat_CompareAndConvert_AltPath2\b/FP_pow_AltPath2/g
s/\bVoiceFloat_ConvergenceLoop_RangeCheck\b/FP_pow_ExpLog_RangeCheck/g
s/\bVoiceFloat_CompareAndConvert_AltPath\b/FP_pow_AltPath/g
s/\bVoiceFloat_CompareAndConvert_Invalid\b/FP_pow_Invalid/g
s/\bVoiceFloat_ConvergenceLoop_CrossZero\b/FP_pow_ExpLog_CrossZero/g
s/\bVoiceFloat_ConvergenceLoop_NegResult\b/FP_pow_ExpLog_NegResult/g
s/\bVoiceFloat_IterationLoop_GreaterPath\b/FP_pow_IntPower_GreaterPath/g
s/\bVoiceFreq_EnvelopeStep_IncClamp_Copy\b/FP_ldexp_IncClamp_Copy/g
s/\bVoiceFloat_BlendAndMerge_FinalCheck\b/FP_SinCos_Kernel_FinalCheck/g
s/\bVoiceFloat_CompareAndConvert_Epilog\b/FP_pow_Epilog/g
s/\bVoiceFloat_ConvergenceLoop_SumCheck\b/FP_pow_ExpLog_SumCheck/g
s/\bVoiceFloat_IterationLoop_CopyResult\b/FP_pow_IntPower_CopyResult/g
s/\bVoiceFreq_EnvelopeStep_NibbleAdjust\b/FP_ldexp_NibbleAdjust/g
s/\bVoiceFloat_BlendAndMerge_FinalCopy\b/FP_SinCos_Kernel_FinalCopy/g
s/\bVoiceFloat_IterationLoop_LargeStep\b/FP_pow_IntPower_LargeStep/g
s/\bVoiceFloat_IterationLoop_SmallStep\b/FP_pow_IntPower_SmallStep/g
s/\bVoiceFreq_EnvelopeStep_StoreResult\b/FP_ldexp_StoreResult/g
s/\bVoiceFloat_IterationLoop_LessPath\b/FP_pow_IntPower_LessPath/g
s/\bVoiceFloat_MulAddDispatch_InRange\b/FP_tan_InRange/g
s/\bVoiceFloat_MulAddVariant2_AltPath\b/FP_sin_AltPath/g
s/\bVoiceFreq_EnvelopeStep_SetHighBit\b/FP_ldexp_SetHighBit/g
s/\bVoiceAmp_ConvergeEngine_IterLoop\b/FP_log_IterLoop/g
s/\bVoiceFloat_BlendAndMerge_InRange\b/FP_SinCos_Kernel_InRange/g
s/\bVoiceFloat_ConvergenceLoop_Clamp\b/FP_pow_ExpLog_Clamp/g
s/\bVoiceFloat_MulAddDispatch_Epilog\b/FP_tan_Epilog/g
s/\bVoiceFloat_MulAddVariant2_Epilog\b/FP_sin_Epilog/g
s/\bVoiceFreq_EnvelopeStep_ClampHigh\b/FP_ldexp_ClampHigh/g
s/\bVoicePitch_SlideEngine_StartIter\b/FP_exp_StartIter/g
s/\bDSP_VoiceRegUpdate_BackScanLoop\b/FP_trunc_BackScanLoop/g
s/\bFP_DP_NormalizeMantissa_StoreHL\b/FP_dtof_StoreHL/g
s/\bVoiceAmp_ConvergeEngine_InRange\b/FP_log_InRange/g
s/\bVoiceFloat_BlendAndMerge_Epilog\b/FP_SinCos_Kernel_Epilog/g
s/\bVoiceFloat_BlendAndMerge_Phase2\b/FP_SinCos_Kernel_Phase2/g
s/\bVoiceFloat_BlendAndMerge_Phase3\b/FP_SinCos_Kernel_Phase3/g
s/\bVoiceFloat_BlendAndMerge_Phase4\b/FP_SinCos_Kernel_Phase4/g
s/\bVoiceFloat_ConvergenceLoop_Body\b/FP_pow_ExpLog_Body/g
s/\bVoiceFloat_SignedDelta_Positive\b/FP_pow_IntPower_Seed/g
s/\bVoiceFreq_EnvelopeStep_ClampLow\b/FP_ldexp_ClampLow/g
s/\bVoiceFreq_EnvelopeStep_DecCheck\b/FP_ldexp_DecCheck/g
s/\bVoicePitch_SlideEngine_IterLoop\b/FP_exp_IterLoop/g
s/\bVoicePitch_SlideEngine_LessPath\b/FP_exp_LessPath/g
s/\bDSP_VoiceRegUpdate_ForwardScan\b/FP_trunc_ForwardScan/g
s/\bDSP_VoiceRegUpdate_LargeOffset\b/FP_trunc_LargeOffset/g
s/\bFP_DP_NormalizeMantissa_Encode\b/FP_dtof_Encode/g
s/\bVoiceAmp_ConvergeEngine_Epilog\b/FP_log_Epilog/g
s/\bVoiceFreq_EnvelopeStep_DecLoop\b/FP_ldexp_DecLoop/g
s/\bVoiceFreq_EnvelopeStep_DecStep\b/FP_ldexp_DecStep/g
s/\bVoiceFreq_EnvelopeStep_InRange\b/FP_ldexp_InRange/g
s/\bVoiceFreq_EnvelopeStep_IncLoop\b/FP_ldexp_IncLoop/g
s/\bVoiceFreq_EnvelopeStep_IncStep\b/FP_ldexp_IncStep/g
s/\bVoicePitch_SlideEngine_NonZero\b/FP_exp_NonZero/g
s/\bVoiceFreq_EnvelopeStep_Epilog\b/FP_ldexp_Epilog/g
s/\bVoicePitch_SlideEngine_Epilog\b/FP_exp_Epilog/g
s/\bDSP_VoiceRegUpdate_BackScan2\b/FP_trunc_BackScan2/g
s/\bDSP_VoiceRegUpdate_BlendLoop\b/FP_trunc_BlendLoop/g
s/\bDSP_VoiceRegUpdate_NegOffset\b/FP_trunc_NegOffset/g
s/\bDSP_VoiceRegUpdate_ZeroOrMax\b/FP_trunc_ZeroOrMax/g
s/\bFP_DP_FreqAdjust_StoreResult\b/FP_frexp_StoreResult/g
s/\bVoiceFloat_CompareAndConvert\b/FP_pow/g
s/\bDSP_VoiceRegUpdate_BackScan\b/FP_trunc_BackScan/g
s/\bFP_DP_FreqAdjust_NonZeroExp\b/FP_frexp_NonZeroExp/g
s/\bVoicePitch_SlideEngine_Done\b/FP_exp_Done/g
s/\bDSP_VoiceRegUpdate_FillPad\b/FP_trunc_FillPad/g
s/\bDSP_VoiceRegUpdate_InRange\b/FP_trunc_InRange/g
s/\bDSP_VoiceRegUpdate_MaskLow\b/FP_trunc_MaskLow/g
s/\bDSP_VoiceRegUpdate_ZeroLow\b/FP_trunc_ZeroLow/g
s/\bVoiceFloat_ConvergenceLoop\b/FP_pow_ExpLog/g
s/\bDSP_VoiceRegUpdate_Return\b/FP_trunc_Return/g
s/\bFP_DP_FreqAdjust_DecCheck\b/FP_frexp_DecCheck/g
s/\bFP_DP_FreqAdjust_IncCheck\b/FP_frexp_IncCheck/g
s/\bFP_DP_NegMantissaLS_Store\b/FP_ftod_Store/g
s/\bFP_SP_Decode_ReadSign_Pad\b/FP_ftoi_Pad/g
s/\bVoiceFloat_DispatchMulAdd\b/FP_cos/g
s/\bVoiceFloat_MulAddDispatch\b/FP_tan/g
s/\bVoiceFloat_MulAddVariant2\b/FP_sin/g
s/\bFP_DP_FreqAdjust_Combine\b/FP_frexp_Combine/g
s/\bFP_DP_FreqAdjust_DecLoop\b/FP_frexp_DecLoop/g
s/\bFP_DP_FreqAdjust_IncLoop\b/FP_frexp_IncLoop/g
s/\bVoiceFloat_BlendAndMerge\b/FP_SinCos_Kernel/g
s/\bVoiceFloat_IterationLoop\b/FP_pow_IntPower/g
s/\bFP_DP_CmpAndCopy_Negate\b/FP_fabs_Negate/g
s/\bFP_DP_FreqAdjust_Return\b/FP_frexp_Return/g
s/\bFP_DP_NormalizeMantissa\b/FP_dtof/g
s/\bVoiceAmp_ConvergeEngine\b/FP_log/g
s/\bVoiceFreq_EnvelopeStep\b/FP_ldexp/g
s/\bVoicePitch_SlideEngine\b/FP_exp/g
s/\bFP_SP_Decode_ReadSign\b/FP_ftoi/g
s/\bFP_DP_CmpAndCopy_Pad\b/FP_fabs_Pad/g
s/\bFP_DP_Add_Outer_Pad\b/FP_dmul_Pad/g
s/\bFP_DP_NegMantissaLS\b/FP_ftod/g
s/\bFP_SP_Mul_Outer_Pad\b/FP_SP_DivCore_Pad/g
s/\bDSP_VoiceRegUpdate\b/FP_trunc/g
s/\bFP_DP_Mul_DiffSign\b/FP_dadd_DiffSign/g
s/\bFP_DP_Mul_SameSign\b/FP_dadd_SameSign/g
s/\bFP_SP_Mul_DiffSign\b/FP_fadd_DiffSign/g
s/\bFP_SP_Mul_SameSign\b/FP_fadd_SameSign/g
s/\bFP_DP_CmpAndCopy\b/FP_fabs/g
s/\bFP_DP_FreqAdjust\b/FP_frexp/g
s/\bFP_DP_Mul_Encode\b/FP_dadd_Encode/g
s/\bFP_SP_Mul_Encode\b/FP_fadd_Encode/g
s/\bVoiceFloat_SubDP\b/FP_ddiv/g
s/\bVoiceFloat_SubSP\b/FP_fdiv/g
s/\bFP_DP_Add_Outer\b/FP_dmul/g
s/\bFP_DP_Mul_Outer\b/FP_DP_DivCore/g
s/\bFP_SP_Add_Outer\b/FP_fmul/g
s/\bFP_SP_Mul_Outer\b/FP_SP_DivCore/g
s/\bDSP_VoiceBlend\b/FP_modf/g
s/\bFP_SP_Mul_Pad\b/FP_fadd_Pad/g
s/\bFP_DP_Mul\b/FP_dadd/g
s/\bFP_SP_Mul\b/FP_fadd/g
