# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F74D99\b/SmfWrite_EncodeVlq/g
s/\bsub_F7647A\b/SmfSize_EncodeVlq/g
s/\bsub_F76D38\b/SmfWriteCopy_EncodeVlq/g
s/\bsub_F77BDF\b/SmfSizeCopy_EncodeVlq/g
s/\bsub_F74A74\b/SmfWrite_EncodeDeltaTime/g
s/\bsub_F76219\b/SmfSize_EncodeDeltaTime/g
s/\bsub_F76A25\b/SmfWriteCopy_EncodeDeltaTime/g
s/\bsub_F77990\b/SmfSizeCopy_EncodeDeltaTime/g
s/\bsub_F74AC5\b/SmfWrite_WriteChannelEvent/g
s/\bsub_F7626A\b/SmfSize_WriteChannelEvent/g
s/\bsub_F76A6A\b/SmfWriteCopy_WriteChannelEvent/g
s/\bsub_F779D5\b/SmfSizeCopy_WriteChannelEvent/g
s/\bsub_F74A66\b/SmfWrite_WriteControlChange/g
s/\bsub_F7620B\b/SmfSize_WriteControlChange/g
s/\bsub_F77982\b/SmfSizeCopy_WriteControlChange/g
s/\bsub_F74B3A\b/SmfWrite_CommitOutputByte/g
s/\bsub_F762BD\b/SmfSize_CommitOutputByte/g
s/\bsub_F76ADF\b/SmfWriteCopy_CommitOutputByte/g
s/\bsub_F77A28\b/SmfSizeCopy_CommitOutputByte/g
s/\bsub_F74BF6\b/SmfWrite_AgePendingNoteOffs/g
s/\bsub_F762DF\b/SmfSize_AgePendingNoteOffs/g
s/\bsub_F76B9B\b/SmfWriteCopy_AgePendingNoteOffs/g
s/\bsub_F77A4A\b/SmfSizeCopy_AgePendingNoteOffs/g
s/\bsub_F74C87\b/SmfWrite_SortDueNoteOffs/g
s/\bsub_F7636C\b/SmfSize_SortDueNoteOffs/g
s/\bsub_F76C2C\b/SmfWriteCopy_SortDueNoteOffs/g
s/\bsub_F77AD7\b/SmfSizeCopy_SortDueNoteOffs/g
s/\bsub_F74CF2\b/SmfWrite_WriteDueNoteOffs/g
s/\bsub_F763D7\b/SmfSize_WriteDueNoteOffs/g
s/\bsub_F76C97\b/SmfWriteCopy_WriteDueNoteOffs/g
s/\bsub_F77B42\b/SmfSizeCopy_WriteDueNoteOffs/g
s/\bsub_F74E4C\b/SmfWrite_ClearDueList/g
s/\bsub_F7652D\b/SmfSize_ClearDueList/g
s/\bsub_F76DEB\b/SmfWriteCopy_ClearDueList/g
s/\bsub_F77C92\b/SmfSizeCopy_ClearDueList/g
s/\bsub_F74E60\b/SmfWrite_ClearEventFields/g
s/\bsub_F76541\b/SmfSize_ClearEventFields/g
s/\bsub_F77CA6\b/SmfSizeCopy_ClearEventFields/g
s/\bsub_F74EAE\b/SmfWrite_ClearPendingNoteOffs/g
s/\bsub_F749A2\b/SmfWrite_StageTempoFromBpm/g
s/\bsub_F76953\b/SmfWriteCopy_StageTempoFromBpm/g
s/\bsub_F7615B\b/SmfSize_StageTempo/g
s/\bsub_F778D2\b/SmfSizeCopy_StageTempo/g
s/\bsub_F761A1\b/SmfSize_WriteTempoEvent/g
s/\bsub_F77918\b/SmfSizeCopy_WriteTempoEvent/g
s/\bsub_F76123\b/SmfSize_StoreTrackLength/g
s/\bsub_F7789A\b/SmfSizeCopy_StoreTrackLength/g
s/\bsub_F76552\b/SmfSize_ReadSongByte/g
s/\bsub_F77CB7\b/SmfSizeCopy_ReadSongByte/g
s/\bsub_F74E86\b/SmfWrite_AdvanceSongCursor/g
s/\bsub_F76567\b/SmfSize_AdvanceSongCursor/g
s/\bsub_F77CCC\b/SmfSizeCopy_AdvanceSongCursor/g
s/\bsub_F7492F\b/SmfWrite_SaveFileName/g
s/\bsub_F768E0\b/SmfSize_SaveFileName/g
s/\bsub_F7491F\b/SmfWrite_RestoreFileName/g
s/\bsub_F768D0\b/SmfSize_RestoreFileName/g
s/\bsub_F75685\b/SmfSize_Pass/g
s/\bsub_F76E74\b/SmfSizeCopy_Pass/g
