# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F0AAB3\b/ScreenButton_CodeCA/g
s/\bsub_F4C46A\b/ScreenCodeAD_Handler/g
s/\bsub_F4C4B5\b/ScreenButton_CodeAD/g
s/\bsub_F53025\b/ScreenCodeA3_Handler/g
s/\bsub_F7D2B4\b/ScreenCode0E_Handler/g
s/\bsub_F7D2B9\b/ScreenLeave_Code0E/g
s/\bsub_F7D2BE\b/ScreenButton_Code0E/g
s/\bsub_F7D2C6\b/ScreenCode15_Handler/g
s/\bsub_F7D2CB\b/ScreenLeave_Code15/g
s/\bsub_F7D2D0\b/ScreenButton_Code15/g
s/\bsub_FA0689\b/ScreenCode64_Handler/g
s/\bsub_FA07A2\b/ScreenButton_Code64/g
s/\bsub_FA0DF3\b/ScreenCode65_Handler/g
s/\bsub_FA0E4D\b/ScreenLeave_Code65/g
s/\bsub_FA0EEA\b/ScreenButton_Code65/g
s/\bsub_FA129D\b/ScreenCode6A_Handler/g
s/\bsub_FA12CE\b/ScreenLeave_Code6A/g
s/\bsub_FA12DD\b/ScreenButton_Code6A/g
s/\bsub_FBC56B\b/ScreenCodeB2_Handler/g
s/\bsub_FBC56F\b/ScreenLeave_CodeB2/g
s/\bsub_FBC573\b/ScreenButton_CodeB2/g
s/\bsub_FBC585\b/ScreenCode35_Handler/g
s/\bsub_FBC589\b/ScreenLeave_Code35/g
s/\bsub_FBC58D\b/ScreenButton_Code35/g
s/\bsub_FBC59F\b/ScreenCode36_Handler/g
s/\bsub_FBC5A3\b/ScreenLeave_Code36/g
s/\bsub_FBC5A7\b/ScreenButton_Code36/g
s/\bsub_FBC5BD\b/ScreenCodeB3_Handler/g
s/\bsub_FBC5C5\b/ScreenButton_CodeB3/g
s/\bsub_FBC5D7\b/ScreenCodeB6_Handler/g
s/\bsub_FBC5DB\b/ScreenLeave_CodeB6/g
s/\bsub_FBC5DF\b/ScreenButton_CodeB6/g
s/\bsub_FBCB40\b/ScreenCodeB0_Handler/g
s/\bsub_FBCB82\b/ScreenButton_CodeB0/g
s/\bsub_FBCDEC\b/ScreenCodeB4_Handler/g
s/\bsub_FBCDF0\b/ScreenCodeB5_Handler/g
s/\bsub_FBCDF4\b/ScreenCode37_Handler/g
s/\bsub_FBCDF8\b/ScreenCode38_Handler/g
s/\bsub_FBCDFC\b/ScreenCodeB1_Handler/g
s/\bsub_FBCEE7\b/ScreenLeave_CodeB4/g
s/\bsub_FBCEEB\b/ScreenLeave_CodeB5/g
s/\bsub_FBCEEF\b/ScreenLeave_Code37/g
s/\bsub_FBCEF3\b/ScreenLeave_Code38/g
s/\bsub_FBCEF8\b/ScreenButton_CodeB4/g
s/\bsub_FBCF09\b/ScreenButton_CodeB5/g
s/\bsub_FBCF1A\b/ScreenButton_Code37/g
s/\bsub_FBCF2B\b/ScreenButton_Code38/g
s/\bsub_FBCF3C\b/ScreenButton_CodeB1/g
s/\bsub_FBDB91\b/ScreenCode3A_Handler/g
s/\bsub_FBDD0D\b/ScreenLeave_Code3A/g
s/\bsub_FBDD80\b/ScreenButton_Code3A/g
s/\bsub_FBEED9\b/ScreenCode33_Handler/g
s/\bsub_FBEEE6\b/ScreenCode39_Handler/g
s/\bsub_FBEEEC\b/ScreenButton_Code39/g
s/\bsub_FBFAB0\b/ScreenCode34_Handler/g
s/\bsub_FBFAF2\b/ScreenButton_Code34/g
s/\bsub_FDD02D\b/ScreenCode9A_Handler/g
s/\bsub_FDE2EC\b/ScreenLeave_Code9A/g
s/\bsub_FDE324\b/ScreenLeave_CodeCC/g
s/\bsub_FDE340\b/ScreenLeave_CodeC1/g
s/\bsub_FDE34E\b/ScreenLeave_CodeC2/g
s/\bsub_FDE3B0\b/ScreenLeave_CodeCE/g
s/\bsub_FE8C1F\b/ScreenLeave_Code28/g
s/\bsub_FE8C3A\b/ScreenLeave_Code25/g
s/\bsub_FE9A33\b/ScreenButton_Code25/g
s/\bsub_FE9B8D\b/ScreenButton_Code28/g
