# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FAE872\b/SeqBuf_PickRecordPartMask/g
s/\bsub_FB311E\b/ParamImage_WriteHeadersAndSanitize/g
s/\bsub_FB3149\b/Queue2C00_DrainPassBAndPublish/g
s/\bsub_FB31BF\b/Msg0716_PostRestageAllParts_SaveRegs/g
s/\bsub_FB5774\b/ParamApply_ResetPairTablesForGmOff/g
s/\bsub_FB9D07\b/Medley_ReassertGmModeIfOn/g
s/\bsub_FB9D5A\b/MidiFileDirectPlay_ApplyPlayAsGm/g
s/\bsub_FBD0EE\b/CombiEditSound_SetRowFieldBlink/g
s/\bsub_FBE106\b/CombiEditMixer_ShowOtherParts/g
s/\bsub_FBE5CA\b/CombiEditMixer_DrawCurrentPartSound/g
s/\bsub_FBF03A\b/CombinationNaming_WriteToUserMemory/g
s/\bsub_FBF10A\b/CombinationNaming_DrawNamesAndNumber/g
s/\bsub_FC019B\b/MapBlocks_ResetDirectory/g
s/\bsub_FC01F3\b/Msg0716_PostOp17AndRestageAllParts/g
s/\bsub_FC0206\b/Msg0716_PostRestageAllParts/g
s/\bsub_FC0430\b/Msg0716_DispatchIndex_Msg0716_ObjectRecords_240_Msg0716_HandlerTables_13/g
s/\bsub_FC0450\b/Msg0716_DispatchIndex_Msg0716_ObjectRecords_Msg0716_HandlerTables_56_26/g
s/\bsub_FC0460\b/Msg0716_DispatchIndex_Msg0716_ObjectRecords_8_Msg0716_HandlerTables_56_26/g
s/\bsub_FC06CC\b/UiListB_Class9A_Nop/g
s/\bsub_FC0DE7\b/Msg0716_HandlerTables_Nop74/g
s/\bsub_FC1042\b/Msg0716_SustainOffParts0to7/g
s/\bsub_FC1119\b/PartSound_GetBankAndToneFlag/g
s/\bsub_FC11FB\b/Cpu2Query_RefreshPartSoundRecord/g
s/\bsub_FC120C\b/Cpu2Query_RequestPartSoundRecord/g
s/\bsub_FC14C6\b/SoundMode_ResetLvl/g
s/\bsub_FC14DF\b/SoundMode_ResetPan/g
s/\bsub_FC14F8\b/ModeScreen_ResetOct/g
s/\bsub_FC1859\b/Msg0716_AllPartsPostVolume/g
s/\bsub_FC18AA\b/Msg0716_PostSysEx50_87_StackArg/g
s/\bsub_FC1D92\b/Cpu2Query_DrainRecordReplies/g
s/\bsub_FC25A2\b/DrumMap_MapNoteForPart_StackArgs/g
s/\bsub_FC25A8\b/DrumMap_MapNoteForPart/g
s/\bsub_FC80AC\b/SeqRecord_StartOnFirstEvent_SaveRegs/g
s/\bsub_FC8E7B\b/PartNoteList_NextHeldNote/g
s/\bsub_FD2014\b/Cpu2Reply_HandleNext/g
s/\bsub_FD68AD\b/SoundEditMemoryWrite_PostWrittenSoundSel/g
s/\bsub_FD7043\b/SoundEditLfo_StepSelectedLfo/g
s/\bsub_FD7095\b/SoundEditControllerPage2_GetRecordParam/g
s/\bsub_FD71B9\b/SoundEditController_StepDepth/g
s/\bsub_FD724B\b/SoundEditControllerPage1_UnpackReply/g
s/\bsub_FD759A\b/SoundEditController_StepSwitch/g
s/\bsub_FD7A24\b/SoundEditMemoryWrite_GetTargetSlot/g
s/\bsub_FD8D21\b/SoundEditEnvelope_DrawGraphSegment/g
s/\bsub_FD9242\b/SoundEditEnvelope1_ScaleLevel/g
s/\bsub_FD9F42\b/ModelingPage_StoreDrumSourceReply/g
s/\bsub_FDA160\b/SoundEditDrum_GetSelectedKey/g
s/\bsub_FDA1D5\b/DrumSoundNames_StoreName/g
s/\bsub_FDA504\b/DspEffect_CopyRecordBytes/g
s/\bsub_FDA5D4\b/ToneEditPage_A0_DeriveGroupBrackets/g
s/\bsub_FDA6A3\b/PartRecord0_CopyBytes/g
s/\bsub_FDA742\b/Part0SecondRecord_StoreBytes/g
s/\bsub_FDA777\b/SoundEditPitchTune_KeyScalingPosToParam/g
s/\bsub_FDA7C6\b/SoundEditController_FieldCodeToShortListPos/g
s/\bsub_FDA7DC\b/SoundEditController_FieldCodeFromListPos/g
s/\bsub_FDA7F2\b/SoundEditController_FieldCodeFromShortListPos/g
s/\bsub_FDAC6B\b/ModeEnter_SoundEdit/g
s/\bsub_FDAE1F\b/SoundEditMenu_ReadBackTone/g
s/\bsub_FDAF07\b/SoundEditMenu_ReadBackDrum/g
s/\bsub_FDB7F3\b/SoundEditAmpLevel1_RequestToneFields/g
s/\bsub_FDB81F\b/SoundEditAmpLevel1_RequestDrumFields/g
s/\bsub_FDBA51\b/SoundEditAmpEnvelope1_RequestToneFields/g
s/\bsub_FDBA8B\b/SoundEditAmpEnvelope1_RequestDrumFields/g
s/\bsub_FDCD22\b/SoundEditModelingDriverWaveform_DeriveRangeStarts/g
s/\bsub_FDE74C\b/ScreenButton_SoundEditFilterLfo_AfterOp/g
s/\bsub_FE011B\b/BStore_ClearSongStore_SaveRegs/g
s/\bsub_FE01BD\b/SC1_Cmd_EF_SaveRegs/g
s/\bsub_FE0599\b/DiskLoadFile_SendSongSelectAndLoad/g
s/\bsub_FE05AE\b/DiskLoad_LoadAndReportResult/g
s/\bsub_FE09BE\b/DiskFormat_Execute/g
s/\bsub_FE0AF8\b/DiskFile_CopyFileBufferToWindow/g
s/\bsub_FE0F6B\b/Disk_ScanDirectory_MarkFileType/g
s/\bsub_FE10AA\b/Disk_ScanDirectory_StoreEntryName/g
s/\bsub_FE16F3\b/Playback_StopAllBlockingMidiStart/g
s/\bsub_FE1C75\b/Disk_TickCountdowns/g
s/\bsub_FE2610\b/MidiFileSave_DeleteFile/g
s/\bsub_FE2667\b/DiskSaveFile_DeleteEntryFiles/g
s/\bsub_FE2D13\b/Disk_SetWindowStartForSeqFile/g
s/\bsub_FE2E96\b/Playback_SilenceAll/g
s/\bsub_FE2F6A\b/DiskProgress_NextDotPosition/g
s/\bsub_FE306B\b/Disk_CommandDispatch_RestoreRegs/g
s/\bsub_FE30B6\b/Fdc_Request_RestoreRegs/g
s/\bsub_FE8005\b/PowerFail_PrepareSongWorkspace/g
s/\bsub_FE81E7\b/Sequencer_DrawTitleIcon/g
s/\bsub_FE81F6\b/Sequencer_DrawRealtimeIcon/g
s/\bsub_FE8205\b/Sequencer_DrawMasterRecordIcon/g
s/\bsub_FE8214\b/Sequencer_DrawStepIcon/g
s/\bsub_FE8223\b/Sequencer_DrawSongSelectIcon/g
s/\bsub_FE8241\b/Sequencer_DrawEditIcon/g
s/\bsub_FE8250\b/Sequencer_DrawTrackAssignIcon/g
s/\bsub_FE825F\b/Sequencer_DrawMedleyIcon/g
s/\bsub_FE826E\b/Sequencer_DrawAfterTouchSetIcon/g
s/\bsub_FE827D\b/NoteEditPartSelect_DrawTitleIcon/g
s/\bsub_FE828C\b/DrumEditPartSelect_DrawTitleIcon/g
s/\bsub_FE8CA7\b/NoteEdit_RestorePlayingTrackMask/g
s/\bsub_FE938E\b/EditScreen_AppendTwoBeatsIfNoneAfterMark/g
s/\bsub_FE9430\b/EditScreen_AppendBeatsUpToCursorMeasure/g
s/\bsub_FE9830\b/EditScreen_ReadNoteLengthBeats/g
s/\bsub_FEA037\b/EditCursor_SetLastBeatOfPrevMeasure/g
s/\bsub_FEA6B1\b/EditScreen_CountBeatMarkersFromMeasureMark/g
s/\bsub_FEF74F\b/EditScreen_ClearLayer1/g
s/\bsub_FEF758\b/EditScreen_ClearLayer2/g
s/\bsub_FF793F\b/MidiFileDirectPlay_SaveTrackToPartMap/g
s/\bsub_FF794C\b/MidiFileDirectPlay_RestoreTrackToPartMap/g
s/\bsub_FF79DB\b/Mode_SwitchToSound_SaveRegs2/g
s/\bsub_F4840E\b/BStore_ReadCursorByte_Call/g
s/\bsub_F4842F\b/BStore_StepCursorOneByte_Call/g
s/\bsub_F498A0\b/SeqRecord_WriteRingEventsToTracks/g
s/\bsub_F4B771\b/CycleRecord_BeatsBeforeMeasureFromTimeSigs/g
s/\bsub_F4CA64\b/SysExDump_RestoreSavedCurrentBank/g
s/\bsub_F5E2B9\b/BStore_CursorStepBack/g
s/\bsub_F6220D\b/AdvanceDelay_InsertBeatMarkBeforeEndTag/g
s/\bsub_F622AA\b/AdvanceDelay_ReadByteBeforeCursor/g
s/\bsub_F65DD3\b/TrackAssign_IsLocalControlDashed/g
s/\bsub_F68E48\b/BStore_DeleteByteAtSongPosition/g
s/\bsub_F69327\b/StepRecord_FindSongTracksEndBeat/g
s/\bsub_F6AD5F\b/StepRecord_AppendMasterTimeSigAndTempo/g
s/\bsub_F6ADC2\b/StepRecord_ResetSessionState/g
s/\bsub_F6B01E\b/StepRecord_OpenExistingEntry/g
s/\bsub_F6C786\b/StepRecord_FindMasterTrack/g
s/\bsub_F6B96F\b/BStore_ReadByteAtSongPositionPlus1_SaveRegs/g
s/\bsub_F6B97B\b/BStore_ReadByteAtSongPositionForEntryE/g
s/\bsub_F6B9B9\b/BStore_ReadByteAtSongPositionAndAdvance_SaveRegs/g
s/\bsub_F7348E\b/SmfSplit_ExtendChainAtCursor/g
s/\bsub_F768A1\b/SmfSize_RestoreSongFromTempFile/g
s/\bsub_F77D4B\b/SmfOut_CreateFileWithFirstWindow/g
s/\bsub_F77DC6\b/SmfOut_WriteNextWindow/g
