# rename_accomp_wrappers_v7.sed -- generated by scripts/renaming/lane_accomp_name_wrappers.py
# image v7, sequencer/accompaniment_engine.s.  One rule per XIZ-preserving wrapper; the body each
# rule was matched on is the comment above it.
# push xiz / ld xiy, xwa / call AccTuning_CopyAllPartsFromStyle / pop xiz / ret
s/\bAccVoice_BarCounterBytecodeData_Helper10\b/AccTuning_CopyAllPartsFromStyle_Wrap/g
# push xiz / ld xiy, xwa / ld xhl, xbc / and xhl, 65535 / call AccVoice_LoadTuningBlock / pop xiz / ret
s/\bAccVoice_BarCounterBytecodeData_Helper11\b/AccVoice_LoadTuningBlock_Wrap/g
# push xiz / and xwa, 255 / call AccVoice_ComputeParamAddr / and xhl, 65535 / pop xiz / ret
s/\bAccVoice_BarCounterBytecodeData_Helper12\b/AccVoice_ComputeParamAddr_Wrap/g
# push xiz / ld xiy, xwa / call AccInit_AllPartPositions / pop xiz / ret
s/\bAccVoice_BarCounterBytecodeData_Helper13\b/AccInit_AllPartPositions_Wrap/g
# push xiz / ld xiy, xwa / ld xhl, xbc / and xhl, 65535 / call AccVoice_LoadAllParts / pop xiz / ret
s/\bAccVoice_BarCounterBytecodeData_Helper14\b/AccVoice_LoadAllParts_Wrap/g
# push xiz / call AccPedal_DirectionA / and xhl, 65535 / pop xiz / ret
s/\bAccTuning_ComplexBytecodeData_Helper2\b/AccPedal_DirectionA_Wrap/g
# push xiz / call DrumKit_ValidateBank / pop xiz / ret
s/\bCmEsyTtlFunc_Helper\b/DrumKit_ValidateBank_Wrap/g
