# rename_event_arms_v7.sed -- written by scripts/renaming/gen_event_arm_names.py
# generic `cp xbc, EVT_X / jr z, <arm>` targets -> <dispatcher>_On<Event>
s/\bSqedtVal2_HandleUpScrollInner\b/SqedtVal2Proc_OnIndexswDown/g
s/\bAcLswEdit_HandleScrollUpEvt\b/AcLswFuncEditBoxProc_OnIndexswDownAic/g
s/\bAcLswBox_HandleScrollUpEvt\b/AcLswFuncBoxProc_OnIndexswDownAic/g
s/\bAcLswEdit_HandleDialDecEvt\b/AcLswFuncEditBoxProc_OnIndexswUp/g
s/\bAcLswBox_HandleDialDecEvt\b/AcLswFuncBoxProc_OnIndexswUp/g
s/\bAcLswBox_HandleScrollDown\b/AcLswBoxProc_OnIndexswUp/g
s/\bAcRamBox_HandleScrollDown\b/AcRamBoxProc_OnIndexswUp/g
s/\bAcTempoBox_HandleShowHide\b/AcTempoBoxProc_OnPaintOrRepaint/g
s/\bPsFileNameBox_HandleShow\b/PsFileNameBoxProc_OnPaint/g
s/\bVwUserBitmap_HandlePaint\b/VwUserBitmapProc_OnDraw/g
s/\bAcListBox_ScrollDownInc\b/AcListBoxProc_OnIndexswDownAny/g
s/\bAcLswBox_HandleShowHide\b/AcLswBoxProc_OnPaintOrRepaint/g
s/\bAcRamBox_HandleShowHide\b/AcRamBoxProc_OnPaintOrRepaint/g
s/\bAcListBox_ScrollUpDown\b/AcListBoxProc_OnIndexswUpAny/g
s/\bAcPmBkEdit_AutoIncDown\b/AcPmBkEditBoxProc_OnIndexswDown/g
s/\bVariScreen_HandlePaint\b/VariScreenProc_OnDraw/g
s/\bAcLswBox_HandlePageUp\b/AcLswBoxProc_OnIndexswDownAic/g
s/\bAcLswEdit_AutoIncDown\b/AcLswEditBoxProc_OnIndexswDownAic/g
s/\bAcNumEdit_AutoIncDown\b/AcNumEditBoxProc_OnIndexswDownAic/g
s/\bAcRamBox_HandlePageUp\b/AcRamBoxProc_OnIndexswDownAic/g
s/\bAcRamEdit_AutoIncDown\b/AcRamEditBoxProc_OnIndexswDownAic/g
s/\bLoadFilter_HandleShow\b/FmmLoadFilterFunc_OnPaint/g
s/\bSaveFilter_HandleShow\b/FmmSaveFilterFunc_OnPaint/g
s/\bStringBox_HandlePaint\b/StringBoxProc_OnDraw/g
s/\bTitleEdit_HandlePaint\b/TitleEditProc_OnDraw/g
s/\bVariScreen_HandleShow\b/VariScreenProc_OnPaint/g
s/\bModeEdit_HandlePaint\b/ModeEditProc_OnDraw/g
s/\bSLDstBank_HandleShow\b/SingleLoadDstBankFunc_OnPaint/g
s/\bSLSrcBank_HandleShow\b/SingleLoadSrcBankFunc_OnPaint/g
s/\bCompLoad_HandleShow\b/FmmComposerLoadFunc_OnPaint/g
s/\bFileName_HandleShow\b/FmmFileNameFunc_OnPaint/g
s/\bSLDstMem_HandleShow\b/SingleLoadDstMemFunc_OnPaint/g
s/\bSLSrcMem_HandleShow\b/SingleLoadSrcMemFunc_OnPaint/g
s/\bTextBox_HandlePaint\b/TextBoxProc_OnDraw/g
s/\bBitmap_HandlePaint\b/BitmapProc_OnDraw/g
s/\bCmpFile_HandleShow\b/CmpSingleLoadFileFunc_OnPaint/g
s/\bSdtecd1_ScrollDown\b/IvSdtecd1Proc_OnIndexswUpAny/g
s/\bCmpDst_HandleShow\b/CmpSingleLoadDstFunc_OnPaint/g
s/\bFrame_HandlePaint\b/FrameProc_OnDraw/g
s/\bLabel_HandlePaint\b/LabelProc_OnDraw/g
s/\bSLMode_HandleShow\b/SingleLoadModeFunc_OnPaint/g
s/\bIcon_HandlePaint\b/IconProc_OnDraw/g
s/\bLine_HandlePaint\b/LineProc_OnDraw/g
s/\bSLDst_HandleShow\b/SingleLoadDstFunc_OnPaint/g
s/\bSLSrc_HandleShow\b/SingleLoadSrcFunc_OnPaint/g
s/\bSdtecd1_ScrollUp\b/IvSdtecd1Proc_OnIndexswDownAny/g
