# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bT_F40784\b/T_Seq_PublishPendingParamB0/g
s/\bT_F409D0\b/T_SeqRecord_RewindForTake/g
s/\bT_F409D4\b/T_SeqTrack_CompletePlayOff/g
s/\bT_F409E8\b/T_Seq_StopAll_Call/g
s/\bT_F40A7C\b/T_Seq_StopAll_Veneer/g
s/\bT_F40A88\b/T_MidiOut_SendSongPosition_Veneer/g
s/\bT_F40A94\b/T_Seq_LocateNowIfPending_Veneer/g
s/\bT_F40AA4\b/T_SeqCycle_CheckOn/g
s/\bT_F40AAC\b/T_Seq_ResetPositionOnRequest/g
s/\bT_F40B6C\b/T_BStore_StepCursorBackToLeadByte/g
s/\bT_F40BC0\b/T_SeqRecord_LoadTakeCursor_Veneer/g
s/\bT_F40BC4\b/T_SeqRecord_SaveTakeCursor_Veneer/g
s/\bT_F40BCC\b/T_SeqRecord_DrainEventRingAtTakeEnd/g
s/\bT_F40BF0\b/T_CycleRecord_CommitTake/g
s/\bT_F40C68\b/T_BStore_ExtendChainAtCursor_B/g
s/\bT_F40C94\b/T_BStore_FreeChain_B_Veneer/g
s/\bT_F40D60\b/T_SeqTrack_PlayOnWhileStopped/g
s/\bT_F40D68\b/T_SeqTrack_SwitchPlayOnWhileRunning/g
s/\bT_F426E4\b/T_SongEdit_ClearTrack_Call/g
s/\bT_F426E8\b/T_TrackMerge_Execute/g
s/\bT_F426FC\b/T_Vel0cityChange_Execute/g
s/\bT_F42714\b/T_Transp0se_Execute/g
s/\bT_F42718\b/T_N0teChange_Execute/g
s/\bT_F4271C\b/T_S0ngC0py_Execute/g
s/\bT_F42720\b/T_AdvanceDelay_Execute/g
s/\bT_F4277C\b/T_BStore_CopyRangeBackward/g
s/\bT_F42780\b/T_BStore_MovePosForward/g
s/\bT_F42784\b/T_BStore_MovePosBackward/g
s/\bT_F427CC\b/T_BStore_ApplyTrackPartChange/g
s/\bT_F427D0\b/T_SongEdit_CheckAllTracksToStartMeasure/g
s/\bT_F427D4\b/T_SongEdit_CheckFreeBlocksForInsert/g
s/\bT_F427D8\b/T_SongEdit_CheckFreeBlocksForCopy/g
s/\bT_F427DC\b/T_BStore_BlocksNeededToGrow/g
s/\bT_F427E0\b/T_BStore_BlocksFreedByShrink/g
s/\bT_F42828\b/T_SongGmFlag_OnEventPassB_Veneer/g
s/\bT_F4282C\b/T_BStore_LoadSongFromCurrentBank/g
s/\bT_F42BEC\b/T_AfterT0uchSetting_SetRecordEnable/g
s/\bT_F42EFC\b/T_BStore_WriteBytesAtSongPosition_Call/g
s/\bT_F432C0\b/T_SongEdit_SaveTimeSigOfDeletedMeasures/g
s/\bT_F432C4\b/T_SongEdit_InsertTimeSigsForMeasureInsert/g
s/\bT_F432C8\b/T_SongEdit_InsertTimeSigsForMeasureCopy/g
s/\bT_F432CC\b/T_SongEdit_ReinsertTimeSigAfterDelete/g
