# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bT_F4078C\b/T_SoundSel_ClampToProgramAndBankRegs/g
s/\bT_F40808\b/T_CombiSel_GroupMemberFromNumberAndBank/g
s/\bT_F409C8\b/T_Seq_MainLoopService/g
s/\bT_F409DC\b/T_Seq_LocateToCurrentMeasure/g
s/\bT_F409E4\b/T_Seq_RewindOnMidiStart/g
s/\bT_F409F4\b/T_Seq_RestoreTrackMaskAndRewind/g
s/\bT_F409F8\b/T_Seq_SaveTrackMaskAndStopAll/g
s/\bT_F40A0C\b/T_TimedEvents_ClearEndedTrackBits/g
s/\bT_F40A24\b/T_SeqRecord_StartOnFirstEvent/g
s/\bT_F40A28\b/T_SeqRecord_TerminateTracksIfRecording/g
s/\bT_F40A9C\b/T_SeqTrackCursors_LocateAllToCurrentMeasure/g
s/\bT_F40AA8\b/T_SeqMasterTrack_UpdateActive/g
s/\bT_F40AB0\b/T_SeqCycle_LocateTracksToCurrentMeasure/g
s/\bT_F40BD8\b/T_SeqRecord_SaveCursorBaseline/g
s/\bT_F40CCC\b/T_CycleRecord_CheckOn/g
s/\bT_F40CEC\b/T_RealtimeRecord_Disarm/g
s/\bT_F41250\b/T_SysExThirdRegion_FetchNextChunk/g
s/\bT_F41254\b/T_SysExThirdRegion_AcceptRequest/g
s/\bT_F41258\b/T_SysExToneImage_WriteByte/g
s/\bT_F4125C\b/T_SysExParam_ExecSoundWriteRequest/g
s/\bT_F42410\b/T_MidiFilePlay_SnapshotRecordBytes/g
s/\bT_F42414\b/T_PartRecords_RestoreShadowedField/g
s/\bT_F425B8\b/T_DiskSaveScreen_MountAndScanDirectory/g
s/\bT_F425DC\b/T_Playback_AcceptMidiStartAgain/g
s/\bT_F425E8\b/T_DiskSave_CheckFreeSpace/g
s/\bT_F42660\b/T_ParamImage_CopyToSongWorkspace/g
s/\bT_F427F0\b/T_BStore_LoadStartBeatsPerBar/g
s/\bT_F427F4\b/T_BStore_TimeSigNextMeasure_Call/g
s/\bT_F42884\b/T_BStore_AllocBlock_Veneer/g
s/\bT_F42A50\b/T_Transp0se_StepFieldUp/g
s/\bT_F42A54\b/T_Transp0se_StepSelectedFieldDown/g
s/\bT_F42AA4\b/T_N0teChange_StepSelectedFieldUp/g
s/\bT_F42AA8\b/T_N0teChange_StepFieldDown/g
s/\bT_F42E90\b/T_Medley_ToggleMidiFileStream/g
s/\bT_F42FAC\b/T_DrumSoundNames_FetchNext/g
s/\bT_F43384\b/T_MidiFileSave_WriteSeqBankSmf/g
s/\bT_F43450\b/T_Mode_InitSavedPartBlocks/g
