# rename_case_tables_v7.sed -- written by scripts/renaming/gen_case_table_names.py
# `X_Data` switch case-offset tables -> <routine that reads them>_CaseTable
s/\bExtData_VoiceParam_DispatchBytecode_Data\b/ExtData_VoiceParam_DispatchBytecode_CaseTable/g
s/\bExtData_ToneParam_DispatchHandler_Data\b/ExtData_ToneParam_DispatchHandler_CaseTable/g
s/\bFDemoText_ByteData_VoiceProbeC_Data_3\b/FDemoText_ByteData_VoiceProbeC_CaseTable/g
s/\bExtData_ToneParam_AltDispatch_Data\b/ExtData_ToneParam_AltDispatch_CaseTable/g
s/\bCtrlPanel_IndicatorJumpTable_Data\b/CtrlPanel_IndicatorJumpTable_CaseTable/g
s/\bDrawPartGroup_DispatchByType_Data\b/DrawPartGroup_DispatchByType_CaseTable/g
s/\bCmpSetP1_GridCheck_EventEnc_Data\b/CmpSetP1_GridCheck_CaseTable/g
s/\bFDC_CommandEntry_CopyParams_Data\b/FDC_CommandEntry_CopyParams_CaseTable/g
s/\bPanelDisplay_DispatchByMode_Data\b/PanelDisplay_DispatchByMode_CaseTable/g
s/\bTitleFunc_LifecycleDispatch_Data\b/TitleFunc_LifecycleDispatch_CaseTable/g
s/\bUIState_ProcessExtendedMode_Data\b/UIState_ProcessExtendedMode_CaseTable/g
s/\bDisplayMode_DispatchEvents_Data\b/DisplayMode_DispatchEvents_CaseTable/g
s/\bWndEvt_DispatchByEventCode_Data\b/WndEvt_DispatchByEventCode_CaseTable/g
s/\bAcIndexEdit_DispatchDSP_Data_2\b/AcIndexEdit_DispatchDSP_CaseTable/g
s/\bAcPresentationControlProc_Data\b/AcPresentationControlProc_CaseTable/g
s/\bCtrlPanel_DispatchByIndex_Data\b/CtrlPanel_DispatchByIndex_CaseTable/g
s/\bExtData_ToneParam_AltBody_Data\b/ExtData_ToneParam_AltBody_CaseTable/g
s/\bToneGen_WriteParamByIndex_Data\b/ToneGen_WriteParamByIndex_CaseTable/g
s/\bCtrlPanel_FuncDispatch_Data_2\b/CtrlPanel_FuncDispatch_CaseTable/g
s/\bSeqData_ReadFieldByIndex_Data\b/SeqData_ReadFieldByIndex_CaseTable/g
s/\bButtonState_DispatchDSP_Data\b/ButtonState_DispatchDSP_CaseTable/g
s/\bDemoMenu_DescriptorFunc_Data\b/DemoMenu_DescriptorFunc_CaseTable/g
s/\bDraw_DispatchByPartType_Data\b/Draw_DispatchByPartType_CaseTable/g
s/\bDemoMenu_WorkspaceFunc_Data\b/DemoMenu_WorkspaceFunc_CaseTable/g
s/\bFDC_COMMAND_DISPATCHER_Data\b/FDC_COMMAND_DISPATCHER_CaseTable/g
s/\bPlayMode_SendStopEvent_Data\b/SqTrSel_CaseG_CaseTable/g
s/\bAcPmemOutLGridBoxProc_Data\b/AcPmemOutLGridBoxProc_CaseTable/g
s/\bAcSndArgGridBoxProc_Data_2\b/AcSndArgGridBoxProc_CaseTable/g
s/\bAcWelcomScreen_Select_Data\b/AcWelcomScreen_Select_CaseTable/g
s/\bAudio_DispatchCommand_Data\b/Audio_DispatchCommand_CaseTable/g
s/\bMIDI_ReadChannelParam_Data\b/MIDI_ReadChannelParam_CaseTable/g
s/\bAcEasyCmpGridBoxProc_Data\b/AcEasyCmpGridBoxProc_CaseTable/g
s/\bSetWall_ReturnZero_Data_2\b/SqTrAsPsTtl_CaseF_CaseTable/g
s/\bAcCmpSetGridBoxProc_Data\b/AcCmpSetGridBoxProc_CaseTable/g
s/\bDpMdlySmfLyrTtlFunc_Data\b/DpMdlySmfLyrTtlFunc_CaseTable/g
s/\bMspRGrpSetGridCheck_Data\b/MspRGrpSetGridCheck_CaseTable/g
s/\bFmmSmfFileNameFunc_Data\b/FmmSmfFileNameFunc_CaseTable/g
s/\bPsMixerControlProc_Data\b/PsMixerControlProc_CaseTable/g
s/\bCmpSetP1GridCheck_Data\b/CmpSetP1GridCheck_CaseTable/g
s/\bDpDocTtl_Dispatch_Data\b/DpDoc_CaseA_CaseTable/g
s/\bDpSmfTtl_Dispatch_Data\b/DpSmf_CaseA_CaseTable/g
s/\bMspPlayModeFunc_Data_2\b/MspPlayModeFunc_CaseTable/g
s/\bWallHomeEditCheck_Data\b/WallHomeEditCheck_CaseTable/g
s/\bWallMenuEditCheck_Data\b/WallMenuEditCheck_CaseTable/g
s/\bDemoSoundTtlFunc_Data\b/DemoSoundTtlFunc_CaseTable/g
s/\bDemoStyleTtlFunc_Data\b/DemoStyleTtlFunc_CaseTable/g
s/\bDkMdlyPlyTtlFunc_Data\b/DkMdlyPlyTtlFunc_CaseTable/g
s/\bDpMdlyDocTtlFunc_Data\b/DpMdlyDocTtlFunc_CaseTable/g
s/\bDpMdlySmfTtlFunc_Data\b/DpMdlySmfTtlFunc_CaseTable/g
s/\bDpPdTtl_Dispatch_Data\b/DpPd_CaseA_CaseTable/g
s/\bEasyCmpGridCheck_Data\b/EasyCmpGridCheck_CaseTable/g
s/\bFDTestDialogProc_Data\b/FDTestDialogProc_CaseTable/g
s/\bMspNameBnkFunc_Data_2\b/MspNameBnkFunc_CaseTable/g
s/\bSqMdlyPlyTtlFunc_Data\b/SqMdlyPlyTtlFunc_CaseTable/g
s/\bSqSngNameTtlFunc_Data\b/SqSngNameTtlFunc_CaseTable/g
s/\bWallOthEditCheck_Data\b/WallOthEditCheck_CaseTable/g
s/\bCmpSetGridCheck_Data\b/CmpSetGridCheck_CaseTable/g
s/\bDpMdlyPdTtlFunc_Data\b/DpMdlyPdTtlFunc_CaseTable/g
s/\bDpSmfLyrTtlFunc_Data\b/DpSmfLyrTtlFunc_CaseTable/g
s/\bMainPmanControl_Data\b/MainPmanControl_CaseTable/g
s/\bNameGetFuncCall_Data\b/NameGetFuncCall_CaseTable/g
s/\bSndArgGridCheck_Data\b/SndArgGridCheck_CaseTable/g
s/\bSqSngSelTtlFunc_Data\b/SqSngSelTtlFunc_CaseTable/g
s/\bSqTrAsPsTtlFunc_Data\b/SqTrAsPsTtlFunc_CaseTable/g
s/\bDemoRhyTtlFunc_Data\b/DemoRhyTtlFunc_CaseTable/g
s/\bGetEditSwPoint_Data\b/GetEditSwPoint_CaseTable/g
s/\bJumpInsertFunc_Data\b/JumpInsertFunc_CaseTable/g
s/\bMainPreControl_Data\b/MainPreControl_CaseTable/g
s/\bMainSysControl_Data\b/MainSysControl_CaseTable/g
s/\bMiddleFuncCall_Data\b/MiddleFuncCall_CaseTable/g
s/\bS2cGridBoxProc_Data\b/S2cGridBoxProc_CaseTable/g
s/\bSqTrSelTtlFunc_Data\b/SqTrSelTtlFunc_CaseTable/g
s/\bAcGridBoxProc_Data\b/AcGridBoxProc_CaseTable/g
s/\bDirmdEmulator_Data\b/DirmdEmulator_CaseTable/g
s/\bFDC_WaitReady_Data\b/FDC_WaitReady_CaseTable/g
s/\bPsGridBoxProc_Data\b/PsGridBoxProc_CaseTable/g
s/\bSqTrAsTtlFunc_Data\b/SqTrAsTtlFunc_CaseTable/g
s/\bTestTitleFunc_Data\b/TestTitleFunc_CaseTable/g
s/\bApPreControl_Data\b/ApPreControl_CaseTable/g
s/\bCommonIDProc_Data\b/CommonIDProc_CaseTable/g
s/\bDpDocTtlFunc_Data\b/DpDocTtlFunc_CaseTable/g
s/\bDpSmfTtlFunc_Data\b/DpSmfTtlFunc_CaseTable/g
s/\bIvSdpartProc_Data\b/IvSdpartProc_CaseTable/g
s/\bPmBkNameFunc_Data\b/PmBkNameFunc_CaseTable/g
s/\bRamEditCheck_Data\b/RamEditCheck_CaseTable/g
s/\bS2cGridCheck_Data\b/S2cGridCheck_CaseTable/g
s/\bSetWallPaper_Data\b/SetWallPaper_CaseTable/g
s/\bViewableProc_Data\b/ViewableProc_CaseTable/g
s/\bDpPdTtlFunc_Data\b/DpPdTtlFunc_CaseTable/g
s/\bMssNameFunc_Data\b/MssNameFunc_CaseTable/g
s/\bCntIniFunc_Data\b/CntIniFunc_CaseTable/g
s/\bObjectProc_Data\b/ObjectProc_CaseTable/g
s/\bOneTchFUNC_Data\b/OneTchFUNC_CaseTable/g
s/\bWindowProc_Data\b/WindowProc_CaseTable/g
s/\bClassProc_Data\b/ClassProc_CaseTable/g
s/\bGridCheck_Data\b/GridCheck_CaseTable/g
s/\bTEST2FUNC_Data\b/TEST2FUNC_CaseTable/g
s/\bTEST3FUNC_Data\b/TEST3FUNC_CaseTable/g
s/\bTEST4FUNC_Data\b/TEST4FUNC_CaseTable/g
s/\bTEST6FUNC_Data\b/TEST6FUNC_CaseTable/g
s/\bModeProc_Data\b/ModeProc_CaseTable/g
