# v10: part sound-parameter descriptors named by part tag and field (gen_sndparam_desc_names.py;
# basis: analysis/disk-format-probes/README-lsw-param-namespace-map.md section 5).
s/\bVoiceParamEx_Entry_001\b/SndParam_Part00_Drawbar2/g
s/\bVoiceParamEx_Entry_002\b/SndParam_Part00_Drawbar1_3_5/g
s/\bVoiceParamEx_Entry_003\b/SndParam_Part00_Drawbar1_1_3/g
s/\bVoiceParamEx_Entry_004\b/SndParam_Part00_Drawbar1/g
s/\bVoiceParamEx_Entry_007\b/SndParam_Part01_Sound/g
s/\bVoiceParamEx_Entry_008\b/SndParam_Part01_Modulation/g
s/\bVoiceParamEx_Entry_009\b/SndParam_Part01_Volume/g
s/\bVoiceParamEx_Entry_011\b/SndParam_Part01_Pan/g
s/\bVoiceParamEx_Entry_012\b/SndParam_Part01_Expression/g
s/\bVoiceParamEx_Entry_013\b/SndParam_Part01_Bank/g
s/\bVoiceParamEx_Entry_014\b/SndParam_Part01_Sustain/g
s/\bVoiceParamEx_Entry_015\b/SndParam_Part01_ReverbSend/g
s/\bVoiceParamEx_Entry_016\b/SndParam_Part01_ChorusSend/g
s/\bVoiceParamEx_Entry_017\b/SndParam_Part01_DigitalEffect/g
s/\bVoiceParamEx_Entry_029\b/SndParam_Part01_Drawbar16/g
s/\bVoiceParamEx_Entry_030\b/SndParam_Part01_Drawbar8/g
s/\bVoiceParamEx_Entry_031\b/SndParam_Part01_Drawbar5_1_3/g
s/\bVoiceParamEx_Entry_032\b/SndParam_Part01_Drawbar4/g
s/\bVoiceParamEx_Entry_033\b/SndParam_Part01_Drawbar2_2_3/g
s/\bVoiceParamEx_Entry_034\b/SndParam_Part01_Drawbar2/g
s/\bVoiceParamEx_Entry_035\b/SndParam_Part01_Drawbar1_3_5/g
s/\bVoiceParamEx_Entry_036\b/SndParam_Part01_Drawbar1_1_3/g
s/\bVoiceParamEx_Entry_037\b/SndParam_Part01_Drawbar1/g
s/\bVoiceParamEx_Entry_040\b/SndParam_Part02_Sound/g
s/\bVoiceParamEx_Entry_041\b/SndParam_Part02_Modulation/g
s/\bVoiceParamEx_Entry_042\b/SndParam_Part02_Volume/g
s/\bVoiceParamEx_Entry_044\b/SndParam_Part02_Pan/g
s/\bVoiceParamEx_Entry_045\b/SndParam_Part02_Expression/g
s/\bVoiceParamEx_Entry_046\b/SndParam_Part02_Bank/g
s/\bVoiceParamEx_Entry_047\b/SndParam_Part02_Sustain/g
s/\bVoiceParamEx_Entry_048\b/SndParam_Part02_ReverbSend/g
s/\bVoiceParamEx_Entry_049\b/SndParam_Part02_ChorusSend/g
s/\bVoiceParamEx_Entry_050\b/SndParam_Part02_DigitalEffect/g
s/\bVoiceParamEx_Entry_062\b/SndParam_Part02_Drawbar16/g
s/\bVoiceParamEx_Entry_063\b/SndParam_Part02_Drawbar8/g
s/\bVoiceParamEx_Entry_064\b/SndParam_Part02_Drawbar5_1_3/g
s/\bVoiceParamEx_Entry_065\b/SndParam_Part02_Drawbar4/g
s/\bVoiceParamEx_Entry_066\b/SndParam_Part02_Drawbar2_2_3/g
s/\bVoiceParamEx_Entry_067\b/SndParam_Part02_Drawbar2/g
s/\bVoiceParamEx_Entry_068\b/SndParam_Part02_Drawbar1_3_5/g
s/\bVoiceParamEx_Entry_069\b/SndParam_Part02_Drawbar1_1_3/g
s/\bVoiceParamEx_Entry_070\b/SndParam_Part02_Drawbar1/g
s/\bVoiceParamEx_Entry_073\b/SndParam_Part03_Sound/g
s/\bVoiceParamEx_Entry_074\b/SndParam_Part03_Modulation/g
s/\bVoiceParamEx_Entry_075\b/SndParam_Part03_Volume/g
s/\bVoiceParamEx_Entry_077\b/SndParam_Part03_Pan/g
s/\bVoiceParamEx_Entry_078\b/SndParam_Part03_Expression/g
s/\bVoiceParamEx_Entry_079\b/SndParam_Part03_Bank/g
s/\bVoiceParamEx_Entry_080\b/SndParam_Part03_Sustain/g
s/\bVoiceParamEx_Entry_081\b/SndParam_Part03_ReverbSend/g
s/\bVoiceParamEx_Entry_082\b/SndParam_Part03_ChorusSend/g
s/\bVoiceParamEx_Entry_083\b/SndParam_Part03_DigitalEffect/g
s/\bExtPartParam_Entry_228\b/SndParam_Part11_Volume/g
s/\bExtPartParam_Entry_230\b/SndParam_Part11_Pan/g
s/\bExtPartParam_Entry_231\b/SndParam_Part11_Expression/g
s/\bExtPartParam_Entry_232\b/SndParam_Part11_Bank/g
s/\bExtPartParam_Entry_233\b/SndParam_Part11_Sustain/g
s/\bExtPartParam_Entry_234\b/SndParam_Part11_ReverbSend/g
s/\bExtPartParam_Entry_235\b/SndParam_Part11_ChorusSend/g
s/\bExtPartParam_Entry_236\b/SndParam_Part11_DigitalEffect/g
s/\bExtPartParam_Entry_243\b/SndParam_Part12_Sound/g
s/\bExtPartParam_Entry_244\b/SndParam_Part12_Modulation/g
s/\bExtPartParam_Entry_245\b/SndParam_Part12_Volume/g
s/\bExtPartParam_Entry_247\b/SndParam_Part12_Pan/g
s/\bExtPartParam_Entry_248\b/SndParam_Part12_Expression/g
s/\bExtPartParam_Entry_249\b/SndParam_Part12_Bank/g
s/\bExtPartParam_Entry_250\b/SndParam_Part12_Sustain/g
s/\bExtPartParam_Entry_251\b/SndParam_Part12_ReverbSend/g
s/\bExtPartParam_Entry_252\b/SndParam_Part12_ChorusSend/g
s/\bExtPartParam_Entry_253\b/SndParam_Part12_DigitalEffect/g
s/\bExtPartParam_Entry_260\b/SndParam_Part13_Sound/g
s/\bExtPartParam_Entry_261\b/SndParam_Part13_Modulation/g
s/\bExtPartParam_Entry_262\b/SndParam_Part13_Volume/g
s/\bExtPartParam_Entry_264\b/SndParam_Part13_Pan/g
s/\bExtPartParam_Entry_265\b/SndParam_Part13_Expression/g
s/\bExtPartParam_Entry_266\b/SndParam_Part13_Bank/g
s/\bExtPartParam_Entry_267\b/SndParam_Part13_Sustain/g
s/\bExtPartParam_Entry_268\b/SndParam_Part13_ReverbSend/g
s/\bExtPartParam_Entry_269\b/SndParam_Part13_ChorusSend/g
s/\bExtPartParam_Entry_270\b/SndParam_Part13_DigitalEffect/g
s/\bExtPartParam_Entry_277\b/SndParam_Part14_Sound/g
s/\bExtPartParam_Entry_278\b/SndParam_Part14_Modulation/g
s/\bExtPartParam_Entry_279\b/SndParam_Part14_Volume/g
s/\bExtPartParam_Entry_281\b/SndParam_Part14_Pan/g
s/\bExtPartParam_Entry_282\b/SndParam_Part14_Expression/g
s/\bExtPartParam_Entry_283\b/SndParam_Part14_Bank/g
s/\bExtPartParam_Entry_284\b/SndParam_Part14_Sustain/g
s/\bExtPartParam_Entry_285\b/SndParam_Part14_ReverbSend/g
s/\bExtPartParam_Entry_286\b/SndParam_Part14_ChorusSend/g
s/\bExtPartParam_Entry_287\b/SndParam_Part14_DigitalEffect/g
s/\bExtPartParam_Entry_294\b/SndParam_Part15_Sound/g
s/\bExtPartParam_Entry_295\b/SndParam_Part15_Modulation/g
s/\bExtPartParam_Entry_296\b/SndParam_Part15_Volume/g
s/\bExtPartParam_Entry_298\b/SndParam_Part15_Pan/g
s/\bExtPartParam_Entry_299\b/SndParam_Part15_Expression/g
s/\bExtPartParam_Entry_300\b/SndParam_Part15_Bank/g
s/\bExtPartParam_Entry_301\b/SndParam_Part15_Sustain/g
s/\bExtPartParam_Entry_302\b/SndParam_Part15_ReverbSend/g
s/\bExtPartParam_Entry_303\b/SndParam_Part15_ChorusSend/g
s/\bExtPartParam_Entry_304\b/SndParam_Part15_DigitalEffect/g
s/\bExtPartParam_Entry_311\b/SndParam_Part16_Sound/g
s/\bExtPartParam_Entry_312\b/SndParam_Part16_Modulation/g
s/\bExtPartParam_Entry_313\b/SndParam_Part16_Volume/g
s/\bExtPartParam_Entry_315\b/SndParam_Part16_Pan/g
s/\bExtPartParam_Entry_316\b/SndParam_Part16_Expression/g
s/\bExtPartParam_Entry_317\b/SndParam_Part16_Bank/g
s/\bExtPartParam_Entry_318\b/SndParam_Part16_Sustain/g
s/\bExtPartParam_Entry_319\b/SndParam_Part16_ReverbSend/g
s/\bExtPartParam_Entry_320\b/SndParam_Part16_ChorusSend/g
s/\bExtPartParam_Entry_321\b/SndParam_Part16_DigitalEffect/g
s/\bExtPartParam_Entry_328\b/SndParam_Part17_Sound/g
s/\bExtPartParam_Entry_329\b/SndParam_Part17_Modulation/g
s/\bExtPartParam_Entry_330\b/SndParam_Part17_Volume/g
s/\bExtPartParam_Entry_332\b/SndParam_Part17_Pan/g
s/\bExtPartParam_Entry_333\b/SndParam_Part17_Expression/g
s/\bExtPartParam_Entry_334\b/SndParam_Part17_Bank/g
s/\bExtPartParam_Entry_335\b/SndParam_Part17_Sustain/g
s/\bExtPartParam_Entry_336\b/SndParam_Part17_ReverbSend/g
s/\bExtPartParam_Entry_337\b/SndParam_Part17_ChorusSend/g
s/\bExtPartParam_Entry_338\b/SndParam_Part17_DigitalEffect/g
s/\bExtPartParam_Entry_345\b/SndParam_Part18_Sound/g
s/\bExtPartParam_Entry_346\b/SndParam_Part18_Modulation/g
s/\bExtPartParam_Entry_347\b/SndParam_Part18_Volume/g
s/\bExtPartParam_Entry_349\b/SndParam_Part18_Pan/g
s/\bExtPartParam_Entry_350\b/SndParam_Part18_Expression/g
s/\bExtPartParam_Entry_351\b/SndParam_Part18_Bank/g
s/\bExtPartParam_Entry_352\b/SndParam_Part18_Sustain/g
s/\bExtPartParam_Entry_353\b/SndParam_Part18_ReverbSend/g
s/\bExtPartParam_Entry_354\b/SndParam_Part18_ChorusSend/g
s/\bExtPartParam_Entry_355\b/SndParam_Part18_DigitalEffect/g
s/\bMidiChParam_Entry_086\b/SndParam_Part00_Sound/g
s/\bMidiChParam_Entry_087\b/SndParam_Part00_Modulation/g
s/\bMidiChParam_Entry_088\b/SndParam_Part00_Volume/g
s/\bMidiChParam_Entry_090\b/SndParam_Part00_Pan/g
s/\bMidiChParam_Entry_091\b/SndParam_Part00_Expression/g
s/\bMidiChParam_Entry_092\b/SndParam_Part00_Bank/g
s/\bMidiChParam_Entry_093\b/SndParam_Part00_Sustain/g
s/\bMidiChParam_Entry_094\b/SndParam_Part00_ReverbSend/g
s/\bMidiChParam_Entry_095\b/SndParam_Part00_ChorusSend/g
s/\bMidiChParam_Entry_096\b/SndParam_Part00_DigitalEffect/g
s/\bMidiChParam_Entry_108\b/SndParam_Part00_Drawbar16/g
s/\bMidiChParam_Entry_109\b/SndParam_Part00_Drawbar8/g
s/\bMidiChParam_Entry_110\b/SndParam_Part00_Drawbar5_1_3/g
s/\bMidiChParam_Entry_111\b/SndParam_Part00_Drawbar4/g
s/\bMidiChParam_Entry_112\b/SndParam_Part00_Drawbar2_2_3/g
s/\bPartParam_Entry_005\b/SndParam_Part04_Sound/g
s/\bPartParam_Entry_006\b/SndParam_Part04_Modulation/g
s/\bPartParam_Entry_007\b/SndParam_Part04_Volume/g
s/\bPartParam_Entry_009\b/SndParam_Part04_Pan/g
s/\bPartParam_Entry_010\b/SndParam_Part04_Expression/g
s/\bPartParam_Entry_011\b/SndParam_Part04_Bank/g
s/\bPartParam_Entry_012\b/SndParam_Part04_Sustain/g
s/\bPartParam_Entry_013\b/SndParam_Part04_ReverbSend/g
s/\bPartParam_Entry_014\b/SndParam_Part04_ChorusSend/g
s/\bPartParam_Entry_015\b/SndParam_Part04_DigitalEffect/g
s/\bPartParam_Entry_022\b/SndParam_Part05_Sound/g
s/\bPartParam_Entry_023\b/SndParam_Part05_Modulation/g
s/\bPartParam_Entry_024\b/SndParam_Part05_Volume/g
s/\bPartParam_Entry_026\b/SndParam_Part05_Pan/g
s/\bPartParam_Entry_027\b/SndParam_Part05_Expression/g
s/\bPartParam_Entry_028\b/SndParam_Part05_Bank/g
s/\bPartParam_Entry_029\b/SndParam_Part05_Sustain/g
s/\bPartParam_Entry_030\b/SndParam_Part05_ReverbSend/g
s/\bPartParam_Entry_031\b/SndParam_Part05_ChorusSend/g
s/\bPartParam_Entry_032\b/SndParam_Part05_DigitalEffect/g
s/\bPartParam_Entry_039\b/SndParam_Part06_Sound/g
s/\bPartParam_Entry_040\b/SndParam_Part06_Modulation/g
s/\bPartParam_Entry_041\b/SndParam_Part06_Volume/g
s/\bPartParam_Entry_043\b/SndParam_Part06_Pan/g
s/\bPartParam_Entry_044\b/SndParam_Part06_Expression/g
s/\bPartParam_Entry_045\b/SndParam_Part06_Bank/g
s/\bPartParam_Entry_046\b/SndParam_Part06_Sustain/g
s/\bPartParam_Entry_047\b/SndParam_Part06_ReverbSend/g
s/\bPartParam_Entry_048\b/SndParam_Part06_ChorusSend/g
s/\bPartParam_Entry_049\b/SndParam_Part06_DigitalEffect/g
s/\bPartParam_Entry_056\b/SndParam_Part07_Sound/g
s/\bPartParam_Entry_057\b/SndParam_Part07_Modulation/g
s/\bPartParam_Entry_058\b/SndParam_Part07_Volume/g
s/\bPartParam_Entry_060\b/SndParam_Part07_Pan/g
s/\bPartParam_Entry_061\b/SndParam_Part07_Expression/g
s/\bPartParam_Entry_062\b/SndParam_Part07_Bank/g
s/\bPartParam_Entry_063\b/SndParam_Part07_Sustain/g
s/\bPartParam_Entry_064\b/SndParam_Part07_ReverbSend/g
s/\bPartParam_Entry_065\b/SndParam_Part07_ChorusSend/g
s/\bPartParam_Entry_066\b/SndParam_Part07_DigitalEffect/g
s/\bPartParam_Entry_073\b/SndParam_Part08_Sound/g
s/\bPartParam_Entry_074\b/SndParam_Part08_Modulation/g
s/\bPartParam_Entry_075\b/SndParam_Part08_Volume/g
s/\bPartParam_Entry_077\b/SndParam_Part08_Pan/g
s/\bPartParam_Entry_078\b/SndParam_Part08_Expression/g
s/\bPartParam_Entry_079\b/SndParam_Part08_Bank/g
s/\bPartParam_Entry_080\b/SndParam_Part08_Sustain/g
s/\bPartParam_Entry_081\b/SndParam_Part08_ReverbSend/g
s/\bPartParam_Entry_082\b/SndParam_Part08_ChorusSend/g
s/\bPartParam_Entry_083\b/SndParam_Part08_DigitalEffect/g
s/\bPartParam_Entry_090\b/SndParam_Part09_Sound/g
s/\bPartParam_Entry_091\b/SndParam_Part09_Modulation/g
s/\bPartParam_Entry_092\b/SndParam_Part09_Volume/g
s/\bPartParam_Entry_094\b/SndParam_Part09_Pan/g
s/\bPartParam_Entry_095\b/SndParam_Part09_Expression/g
s/\bPartParam_Entry_096\b/SndParam_Part09_Bank/g
s/\bPartParam_Entry_097\b/SndParam_Part09_Sustain/g
s/\bPartParam_Entry_098\b/SndParam_Part09_ReverbSend/g
s/\bPartParam_Entry_099\b/SndParam_Part09_ChorusSend/g
s/\bPartParam_Entry_100\b/SndParam_Part09_DigitalEffect/g
s/\bPartParam_Entry_107\b/SndParam_Part0A_Sound/g
s/\bPartParam_Entry_108\b/SndParam_Part0A_Modulation/g
s/\bPartParam_Entry_109\b/SndParam_Part0A_Volume/g
s/\bPartParam_Entry_111\b/SndParam_Part0A_Pan/g
s/\bPartParam_Entry_112\b/SndParam_Part0A_Expression/g
s/\bPartParam_Entry_113\b/SndParam_Part0A_Bank/g
s/\bPartParam_Entry_114\b/SndParam_Part0A_Sustain/g
s/\bPartParam_Entry_115\b/SndParam_Part0A_ReverbSend/g
s/\bPartParam_Entry_116\b/SndParam_Part0A_ChorusSend/g
s/\bPartParam_Entry_117\b/SndParam_Part0A_DigitalEffect/g
s/\bPartParam_Entry_124\b/SndParam_Part0B_Sound/g
s/\bPartParam_Entry_125\b/SndParam_Part0B_Modulation/g
s/\bPartParam_Entry_126\b/SndParam_Part0B_Volume/g
s/\bPartParam_Entry_128\b/SndParam_Part0B_Pan/g
s/\bPartParam_Entry_129\b/SndParam_Part0B_Expression/g
s/\bPartParam_Entry_130\b/SndParam_Part0B_Bank/g
s/\bPartParam_Entry_131\b/SndParam_Part0B_Sustain/g
s/\bPartParam_Entry_132\b/SndParam_Part0B_ReverbSend/g
s/\bPartParam_Entry_133\b/SndParam_Part0B_ChorusSend/g
s/\bPartParam_Entry_134\b/SndParam_Part0B_DigitalEffect/g
s/\bPartParam_Entry_141\b/SndParam_Part0C_Sound/g
s/\bPartParam_Entry_142\b/SndParam_Part0C_Modulation/g
s/\bPartParam_Entry_143\b/SndParam_Part0C_Volume/g
s/\bPartParam_Entry_145\b/SndParam_Part0C_Pan/g
s/\bPartParam_Entry_146\b/SndParam_Part0C_Expression/g
s/\bPartParam_Entry_147\b/SndParam_Part0C_Bank/g
s/\bPartParam_Entry_148\b/SndParam_Part0C_Sustain/g
s/\bPartParam_Entry_149\b/SndParam_Part0C_ReverbSend/g
s/\bPartParam_Entry_150\b/SndParam_Part0C_ChorusSend/g
s/\bPartParam_Entry_151\b/SndParam_Part0C_DigitalEffect/g
s/\bPartParam_Entry_158\b/SndParam_Part0D_Sound/g
s/\bPartParam_Entry_159\b/SndParam_Part0D_Modulation/g
s/\bPartParam_Entry_160\b/SndParam_Part0D_Volume/g
s/\bPartParam_Entry_162\b/SndParam_Part0D_Pan/g
s/\bPartParam_Entry_163\b/SndParam_Part0D_Expression/g
s/\bPartParam_Entry_164\b/SndParam_Part0D_Bank/g
s/\bPartParam_Entry_165\b/SndParam_Part0D_Sustain/g
s/\bPartParam_Entry_166\b/SndParam_Part0D_ReverbSend/g
s/\bPartParam_Entry_167\b/SndParam_Part0D_ChorusSend/g
s/\bPartParam_Entry_168\b/SndParam_Part0D_DigitalEffect/g
s/\bPartParam_Entry_175\b/SndParam_Part0E_Sound/g
s/\bPartParam_Entry_176\b/SndParam_Part0E_Modulation/g
s/\bPartParam_Entry_177\b/SndParam_Part0E_Volume/g
s/\bPartParam_Entry_179\b/SndParam_Part0E_Pan/g
s/\bPartParam_Entry_180\b/SndParam_Part0E_Expression/g
s/\bPartParam_Entry_181\b/SndParam_Part0E_Bank/g
s/\bPartParam_Entry_182\b/SndParam_Part0E_Sustain/g
s/\bPartParam_Entry_183\b/SndParam_Part0E_ReverbSend/g
s/\bPartParam_Entry_184\b/SndParam_Part0E_ChorusSend/g
s/\bPartParam_Entry_185\b/SndParam_Part0E_DigitalEffect/g
s/\bPartParam_Entry_192\b/SndParam_Part0F_Sound/g
s/\bPartParam_Entry_193\b/SndParam_Part0F_Modulation/g
s/\bPartParam_Entry_194\b/SndParam_Part0F_Volume/g
s/\bPartParam_Entry_196\b/SndParam_Part0F_Pan/g
s/\bPartParam_Entry_197\b/SndParam_Part0F_Expression/g
s/\bPartParam_Entry_198\b/SndParam_Part0F_Bank/g
s/\bPartParam_Entry_199\b/SndParam_Part0F_Sustain/g
s/\bPartParam_Entry_200\b/SndParam_Part0F_ReverbSend/g
s/\bPartParam_Entry_201\b/SndParam_Part0F_ChorusSend/g
s/\bPartParam_Entry_202\b/SndParam_Part0F_DigitalEffect/g
s/\bPartParam_Entry_209\b/SndParam_Part10_Sound/g
s/\bPartParam_Entry_210\b/SndParam_Part10_Modulation/g
s/\bPartParam_Entry_211\b/SndParam_Part10_Volume/g
s/\bPartParam_Entry_213\b/SndParam_Part10_Pan/g
s/\bPartParam_Entry_214\b/SndParam_Part10_Expression/g
s/\bPartParam_Entry_215\b/SndParam_Part10_Bank/g
s/\bPartParam_Entry_216\b/SndParam_Part10_Sustain/g
s/\bPartParam_Entry_217\b/SndParam_Part10_ReverbSend/g
s/\bPartParam_Entry_218\b/SndParam_Part10_ChorusSend/g
s/\bPartParam_Entry_219\b/SndParam_Part10_DigitalEffect/g
s/\bPartParam_Entry_226\b/SndParam_Part11_Sound/g
s/\bPartParam_Entry_227\b/SndParam_Part11_Modulation/g
