# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bDispatchTable_F0F152\b/ScreenEnterBody_DspEffect_BySection/g
s/\bsub_F0F16A\b/ScreenEnterBody_DspEffect_Section0/g
s/\bsub_F0F16F\b/ScreenEnterBody_DspEffect_ParamSections/g
s/\bsub_F0F174\b/ScreenEnterBody_DspEffect_EqSections/g
s/\bDispatchTable_F0F1E8\b/ExitKey_DspEffect_BySection/g
s/\bsub_F0F200\b/ExitKey_DspEffect_Section0/g
s/\bsub_F0F26D\b/ExitKey_DspEffect_ParamSections/g
s/\bsub_F0F272\b/ExitKey_DspEffect_Section4/g
s/\bsub_F0F277\b/ExitKey_DspEffect_Section5/g
s/\bDispatchTable_F0F29A\b/SoftKeyCol1_DspEffect_BySection/g
s/\bsub_F0F2B2\b/SoftKeyCol1_DspEffect_Section0/g
s/\bsub_F0F2DB\b/SoftKeyCol1_DspEffect_ParamSections/g
s/\bDispatchTable_F0F2F8\b/SoftKeyCol2_DspEffect_BySection/g
s/\bsub_F0F310\b/SoftKeyCol2_DspEffect_ParamSections/g
s/\bsub_F0F315\b/SoftKeyCol2_DspEffect_EqSections/g
s/\bDispatchTable_F0F347\b/SoftKeyCol3_DspEffect_BySection/g
s/\bsub_F0F35F\b/SoftKeyCol3_DspEffect_Section0/g
s/\bsub_F0F377\b/SoftKeyCol3_DspEffect_ParamSections/g
s/\bsub_F0F37C\b/SoftKeyCol3_DspEffect_EqSections/g
s/\bDispatchTable_F0F3AE\b/SoftKeyCol4_DspEffect_BySection/g
s/\bsub_F0F3C6\b/SoftKeyCol4_DspEffect_Section0/g
s/\bsub_F0F3E8\b/SoftKeyCol4_DspEffect_ParamSections/g
s/\bDispatchTable_F0F40A\b/SoftKeyCol5_DspEffect_BySection/g
s/\bsub_F0F441\b/SoftKeyCol5_DspEffect_Exit/g
s/\bsub_F0F422\b/SoftKeyCol5_DspEffect_ParamSections/g
s/\bsub_F0F42A\b/SoftKeyCol5_DspEffect_EqSections/g
s/\bDispatchTable_F0F461\b/SoftKeyCol6_DspEffect_BySection/g
s/\bsub_F0F479\b/SoftKeyCol6_DspEffect_Section0/g
s/\bsub_F0F485\b/SoftKeyCol6_DspEffect_ParamSections/g
s/\bsub_F0F48D\b/SoftKeyCol6_DspEffect_EqSections/g
s/\bDispatchTable_F0F4C4\b/SoftKeyCol7_DspEffect_BySection/g
s/\bsub_F0F4DC\b/SoftKeyCol7_DspEffect_Section0/g
s/\bsub_F0F4F5\b/SoftKeyCol7_DspEffect_ParamSections/g
s/\bsub_F0F4FB\b/SoftKeyCol7_DspEffect_Exit/g
s/\bDispatchTable_F0F516\b/SoftKeyCol8_DspEffect_BySection/g
s/\bsub_F0F52E\b/SoftKeyCol8_DspEffect_ParamSections/g
s/\bDispatchTable_F0F558\b/LcdKeyRow1_DspEffect_BySection/g
s/\bsub_F0F570\b/LcdKeyRow1_DspEffect_Section0/g
s/\bsub_F0F579\b/LcdKeyRow1_DspEffect_ParamSections/g
s/\bDispatchTable_F0F5BE\b/LcdKeyRow2_DspEffect_BySection/g
s/\bsub_F0F5D6\b/LcdKeyRow2_DspEffect_Section0/g
s/\bsub_F0F5ED\b/LcdKeyRow2_DspEffect_Section1/g
s/\bsub_F0F5F6\b/LcdKeyRow2_DspEffect_Section2/g
s/\bsub_F0F5FF\b/LcdKeyRow2_DspEffect_Section3/g
s/\bsub_F0F61E\b/LcdKeyRow2_DspEffect_Exit/g
s/\bsub_F0F610\b/LcdKeyRow2_DspEffect_Section5/g
s/\bDispatchTable_F0F63E\b/LcdKeyRow3_DspEffect_BySection/g
s/\bsub_F0F656\b/LcdKeyRow3_DspEffect_Section0/g
s/\bsub_F0F66D\b/LcdKeyRow3_DspEffect_Section1/g
s/\bsub_F0F684\b/LcdKeyRow3_DspEffect_Exit/g
s/\bsub_F0F676\b/LcdKeyRow3_DspEffect_Section3/g
s/\bDispatchTable_F0F6A4\b/LcdKeyRow4_DspEffect_BySection/g
s/\bsub_F0F6BC\b/LcdKeyRow4_DspEffect_Section0/g
s/\bsub_F0F6D3\b/LcdKeyRow4_DspEffect_Sections12/g
s/\bsub_F0F6ED\b/LcdKeyRow4_DspEffect_Exit/g
s/\bsub_F0F6DF\b/LcdKeyRow4_DspEffect_Section4/g
s/\bDispatchTable_F0F708\b/LcdKeyRow5_DspEffect_BySection/g
s/\bsub_F0F720\b/LcdKeyRow5_DspEffect_Section0/g
s/\bsub_F0F74A\b/LcdKeyRow5_DspEffect_ParamSections/g
s/\bsub_F0F018\b/DspEffect_SetSection/g
s/\bsub_F0F02B\b/DspEffect_SetSectionAndRepaint/g
s/\bsub_F0F042\b/DspEffect_GetSection/g
s/\bsub_F0F047\b/DspEffect_SelectSectionBlock/g
s/\bsub_F10252\b/DspEffect_StepEqBandFc/g
s/\bT_F42F40\b/T_DspEffect_SetSection/g
s/\bT_F42F44\b/T_DspEffect_SetSectionAndRepaint/g
s/\bT_F42F48\b/T_DspEffect_GetSection/g
