# generated by scripts/renaming/uiproc_misc_names.py --image v7; applied to CODE only
s/\bPsEditSwBoxProc_Epilogue\b/PsEditSwBox_CalcEdgeSwitchRect_Epilogue/g
s/\bPsEditSwBox_InlineData\b/PsEditSwBox_CalcEdgeSwitchRect/g
s/\bPsTrackSwitchProc_Skip\b/PsTrackSwitch_SetBoxFromIndex_Skip/g
s/\bPsTrackSwitchProc_Join\b/PsTrackSwitch_SetBoxFromIndex_Join/g
s/\bPsEditSwBoxProc_Skip2\b/PsEditSwBox_CalcEdgeSwitchRect_Skip2/g
s/\bPsEditSwBoxProc_Skip3\b/PsEditSwBox_CalcEdgeSwitchRect_Skip3/g
s/\bPsEditSwBoxProc_Skip\b/PsEditSwBox_CalcEdgeSwitchRect_Skip/g
s/\bPsEditSwBoxProc_Join\b/PsEditSwBox_CalcEdgeSwitchRect_Join/g
s/\bPsTrkSw_TrailingData\b/PsTrackSwitch_SetBoxFromIndex/g
s/\bDbMemo_TrailingData\b/DbMemo_LoneRet/g
