# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bT_F40774\b/T_ParamImage_PostAllAsChangeEvents_Call/g
s/\bT_F40790\b/T_SoundSel_FromProgramAndBankRegs/g
s/\bT_F407AC\b/T_ParamImage_LoadFactoryDefaults/g
s/\bT_F407EC\b/T_ParamB0_PublishField0IfPending/g
s/\bT_F40984\b/T_TransportA_ResetCountersAndPattern/g
s/\bT_F409CC\b/T_Seq_RewindAfterSongLoad/g
s/\bT_F40A40\b/T_CountIn_SetMeasureToFirstBar/g
s/\bT_F40AB8\b/T_BStore_CopyWorkspaceToAllBanks/g
s/\bT_F40AC8\b/T_Seq_ApplySongBeatsPerBar/g
s/\bT_F40BDC\b/T_CycleRecord_SetUpRecordTrack/g
s/\bT_F40C5C\b/T_BStore_SeekChainToMeasure/g
s/\bT_F40D00\b/T_SongMemory_UpdateFreePercent/g
s/\bT_F40E10\b/T_SeqScreen_QueueTrackRecPlayLabels/g
s/\bT_F40E18\b/T_Transport_StopWhileRecording/g
s/\bT_F42418\b/T_DiskLoad_SetContentTypeFromSelectedEntry/g
s/\bT_F42574\b/T_BStore_Workspace_StoreParamImage/g
s/\bT_F4257C\b/T_Medley_NormFileCommand/g
s/\bT_F425B4\b/T_DiskLoadScreen_MountAndScanDirectory/g
s/\bT_F4270C\b/T_BStore_ReadCursorAdvance_Call/g
s/\bT_F42774\b/T_BStore_SeekMeasure/g
s/\bT_F42794\b/T_BStore_TruncateChainAfterBlock/g
s/\bT_F427A0\b/T_Seq_FindMasterTrack/g
s/\bT_F427B8\b/T_SongEdit_ResetJobFields/g
s/\bT_F42C7C\b/T_EditValue_SetBit/g
s/\bT_F42CA0\b/T_PartSound_CopyNameToDrawScratch/g
s/\bT_F42E68\b/T_Drawbar_EnterScreenIfMarked/g
s/\bT_F43484\b/T_DspEffect_SendAllToCpu2/g
