# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F604B7\b/TrackMerge_AdvanceReadCursor/g
s/\bsub_F4A82C\b/CycleRecord_AllocTakeChain2/g
s/\bsub_F4A90A\b/CycleRecord_AppendBeatMarks/g
s/\bsub_F60457\b/TrackMerge_AdvanceWriteCursor/g
s/\bsub_F6B95F\b/BStore_ReadByteAtSongPositionAndAdvance/g
s/\bsub_F4A88A\b/CycleRecord_CountCycleRangeBeats/g
s/\bsub_F4B462\b/CycleRecord_CopyRangeIntoGrowingChain/g
s/\bsub_F68B70\b/StepRecord_CursorBack/g
s/\bsub_F6B253\b/StepRecord_AppendCountedBeatMark/g
s/\bsub_F6F4A3\b/MidiFile_LoadWorkspaceFromBank/g
s/\bsub_F7A400\b/BStore_FreeList_Init_Veneer/g
s/\bsub_F49804\b/SeqRecord_SoundAlert_Veneer/g
s/\bsub_F4A91E\b/CycleRecord_AppendBeatMark/g
s/\bsub_F4A9D3\b/CycleRecord_CopyFromCycleStartToTakeChain2/g
s/\bsub_F4AA59\b/CycleRecord_CountTakeChain2BeatMarks/g
s/\bsub_F4AADA\b/CycleRecord_TerminateTakeChain2AtCopyEnd/g
s/\bsub_F4AB0C\b/CycleRecord_SetEndCursorAtCopiedEndTag/g
s/\bsub_F4AEDD\b/CycleRecord_StepCursorOneEvent/g
s/\bsub_F4B20D\b/CycleRecord_CountTrackBeatMarks/g
s/\bsub_F4B258\b/CycleRecord_CountBeatsToCycleEnd/g
s/\bsub_F4B342\b/CycleRecord_SetCopySourceEndAtEndTag/g
s/\bsub_F4C8F0\b/BStore_RelocateGetBlockAddrs/g
s/\bsub_F4C901\b/BStore_RelocateCopyBlock/g
s/\bsub_F4C911\b/BStore_RelocateRepointPrevLink/g
s/\bsub_F4C96B\b/BStore_RelocateRepointNextLink/g
s/\bsub_F4CA0A\b/BStore_ThreadFreeBlock/g
s/\bsub_F5DDB2\b/Quantize_ComputeWindowBounds/g
s/\bsub_F5E01D\b/Quantize_CarryRoundedUpEventsToNextBeat/g
s/\bsub_F5E0BD\b/SongEdit_SortBeatEventsByTiming/g
s/\bsub_F620AF\b/AdvanceDelay_ClampTimingsAtTrackEnd/g
s/\bsub_F648F2\b/SongEdit_CountDestTrackMeasures/g
s/\bsub_F6498D\b/SongEdit_SizeDestTrackPadding/g
s/\bsub_F64A34\b/SongEdit_WriteDestTrackPadding/g
s/\bsub_F66950\b/BStore_ResetAllDirectoriesAndCursors/g
s/\bsub_F67414\b/StepRecord_ShortenMeasures_Veneer/g
s/\bsub_F68B91\b/StepRecord_CursorStep/g
s/\bsub_F690B5\b/StepRecord_ReplaceTimeSigAtCursor/g
s/\bsub_F69116\b/StepRecord_RebarForInsertedTimeSig/g
s/\bsub_F69162\b/StepRecord_FindPrevTimeSigBeats/g
s/\bsub_F69183\b/StepRecord_FindTimeSigInCursorBeat/g
s/\bsub_F69203\b/StepRecord_ReadTimeSigBeatsAtCursor/g
s/\bsub_F6922B\b/StepRecord_CheckCursorAtSongStart/g
s/\bsub_F69240\b/StepRecord_LengthenMeasures/g
s/\bsub_F69814\b/StepRecord_CursorForwardBeatsToTick/g
s/\bsub_F6A8A1\b/StepLength_SetCursorTarget/g
s/\bsub_F6AC4D\b/StepRecord_ResetCursorIfEntryUnused/g
s/\bsub_F6AC7E\b/StepRecord_SetEntryAndTrackKind/g
s/\bsub_F6ACC8\b/StepRecord_SelectTrackPart/g
s/\bsub_F6AD30\b/StepRecord_FlushSeqBufRing/g
s/\bsub_F6AD40\b/StepRecord_SetSubScreenForTrackKind/g
s/\bsub_F6B229\b/StepRecord_AppendBeatMarkKeepCursor/g
s/\bsub_F6B2EE\b/StepRecord_Queue2E00AppendRegs/g
s/\bsub_F6B8AD\b/TrackCursor_DecBeatPosition/g
s/\bsub_F6B8FB\b/BStore_ReadByteAtSongPositionPlus2/g
s/\bsub_F6BC89\b/TrackCursor_IsEventLeadByte/g
s/\bsub_F6CE77\b/StepRecord_AppendLatchedModulation2Event/g
s/\bsub_F6CF21\b/StepRecord_AppendLatchedCtrlPedalEvent/g
s/\bsub_F6CFCB\b/StepRecord_AppendLatchedHoldEvent/g
s/\bsub_F6D075\b/StepRecord_AppendLatchedRtCreateX/g
s/\bsub_F6D11F\b/StepRecord_AppendLatchedRtCreateY/g
s/\bsub_F6D1C9\b/StepRecord_AppendLatchedRtCtrlX/g
s/\bsub_F6D273\b/StepRecord_AppendLatchedRtCtrlY/g
s/\bsub_F6D320\b/StepRecord_AppendLatchedReverb/g
s/\bsub_F6D3C0\b/StepRecord_AppendLatchedEffect1/g
s/\bsub_F6E9E6\b/StepRecord_ReadScanByte/g
s/\bsub_F6EA15\b/StepRecord_AdvanceScanPosition/g
s/\bsub_F6F4F2\b/Seq_RewindAndApplySongGmAndParams/g
s/\bsub_F6FB16\b/Smf_SaveTrackEndCursor/g
s/\bsub_F728D5\b/Smf_SaveSlotEndCursor/g
s/\bsub_F72BB3\b/SmfMerge_CopySource1ToMark/g
s/\bsub_F72BBD\b/SmfMerge_CopySource2ToMark/g
s/\bsub_F72BC7\b/SmfMerge_EmitCommonMark/g
s/\bsub_F72C74\b/SmfMerge_FetchSource2Event/g
s/\bsub_F72CBC\b/SmfMerge_FetchSource1Event/g
s/\bsub_F72D04\b/SmfMerge_CopySource2Event/g
s/\bsub_F72D66\b/SmfMerge_CopySource1Event/g
s/\bsub_F72EBA\b/SmfMerge_DetachSourceTrack/g
s/\bsub_F731FB\b/SmfSplit_ClearUnusedTracks/g
s/\bsub_F73236\b/SmfSplit_MarkTrackUsed/g
s/\bsub_F73261\b/SmfSplit_PutEventBytes/g
s/\bsub_F7328F\b/SmfSplit_PutMarkOnAllTracks/g
s/\bsub_F7330A\b/SmfSplit_DetachTrack/g
s/\bsub_F7335A\b/SmfSplit_LoadAndFreeSourceBlock/g
s/\bsub_F7339C\b/SmfSplit_FetchSourceEvent/g
s/\bsub_F73440\b/SmfSplit_LoadTrackCursor/g
s/\bsub_F73469\b/SmfSplit_SaveTrackCursor/g
s/\bsub_F734C6\b/SmfSplit_SaveTrackEndCursor/g
s/\bsub_F734FB\b/SmfSplit_RewindUsedTracks/g
s/\bsub_F73566\b/Smf_AllocFirstBlockForAllTracks_B/g
s/\bsub_F748F0\b/SmfWrite_RestoreSongFromTempFile/g
s/\bsub_F749C5\b/SmfWrite_WriteTempoEvent/g
s/\bsub_F74E71\b/SmfWrite_ReadSongByte/g
s/\bsub_F7664E\b/SmfWrite_WriteFirstWindow/g
s/\bsub_F76661\b/SmfWrite_WriteNextWindow/g
s/\bsub_F7666F\b/SmfWrite_WriteLastWindowAndClose/g
s/\bsub_F7668A\b/SmfWrite_SetOutputWindow/g
s/\bsub_F77D39\b/InputStream_Refill_Copy/g
s/\bsub_F77D43\b/InputStream_RefillDone_Copy/g
s/\bsub_F7AA29\b/SongClear_InitFields/g
s/\bsub_F7AB3F\b/SongClear_ClearBankTrackMask/g
s/\bsub_F7AB9C\b/TrackClear_ResetSelectionOnEntry/g
s/\bsub_F7AC9D\b/TrackMerge_InitFields/g
s/\bsub_F7ACE6\b/TrackMerge_StepSelectedFieldUp/g
s/\bsub_F7AD42\b/TrackMerge_StepSourceTrack1/g
s/\bsub_F7AD8F\b/TrackMerge_StepSourceTrack2/g
s/\bsub_F7ADDC\b/TrackMerge_StepDestTrack/g
s/\bsub_F7C30B\b/Quantize_StepWindow_StoreDisplayValue/g
s/\bsub_F7C3B2\b/S0ngC0py_InitFields/g
s/\bsub_F7C5CB\b/PanelWrite_OnEnter/g
s/\bsub_F7C5F6\b/PanelWrite_Execute/g
s/\bsub_F7C606\b/Transp0se_InitFields/g
s/\bsub_F7C853\b/N0teChange_InitFields/g
s/\bsub_F7CDA0\b/MeasureInsert_RepeatInsert/g
s/\bsub_F7CE04\b/MeasureC0py_RepeatCopy/g
s/\bsub_F7E39F\b/TrackClear_DrawTrackSelection/g
s/\bsub_F7E430\b/AfterT0uchSetting_EraseRecordValue/g
