# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bDLRec_F2C9C2\b/Paint_SineWaveCheckMode_DL1/g
s/\bDLRec_F2CA15\b/Paint_SineWaveCheckMode_DL2/g
s/\bDLRec_F2CA26\b/Paint_SineWaveCheckMode_DL4/g
s/\bDLRec_F2CA37\b/Paint_SineWaveCheckMode_DL5/g
s/\bDLRec_FC40D2\b/SoundEditDigitalEffect_Paint_DL2/g
s/\bDLRec_FC410F\b/SoundEditDigitalEffect_Paint_DL1/g
s/\bDLRec_FC45A1\b/SoundEditDigitalEffect_RepaintField_DL/g
s/\bDLRec_FC51B1\b/SoundEditMenu_RepaintField_DL3/g
s/\bDLRec_FC51F9\b/SoundEditMenu_RepaintField_DL4/g
s/\bDLRec_FC524D\b/SoundEditMenu_RepaintField_DL1/g
s/\bDL_F02064\b/ToneEditPage_A0_Paint_DL1/g
s/\bDL_F022F7\b/Draw_ToneTemplateLevelKeyTune_DL2/g
s/\bDL_F0245F\b/Draw_ToneTemplateLevelKeyTune_DL1/g
s/\bDL_F02F22\b/UiPaint_Ordinals_DL1/g
s/\bDL_F02FD9\b/UiPaint_Solo_DL1/g
s/\bDL_F02FE3\b/UiPaint_Solo_DL2/g
s/\bDL_F02FED\b/UiPaint_Ordinals_DL2/g
s/\bDL_F02FF7\b/UiPaint_Ordinals_DL3/g
s/\bDL_F0306E\b/ToneEditPage_A0_Paint_DL2/g
s/\bDL_F031BF\b/ToneEditPage_A0_RepaintField_DL/g
s/\bDL_F03455\b/ToneEditPage_A3_RepaintField_DL/g
s/\bDL_F03498\b/ToneEditPage_A4_Paint_DL/g
s/\bDL_F034AD\b/ToneEditPage_A4_RepaintField_DL/g
s/\bDL_F034DE\b/ToneEditPage_A5_Paint_DL/g
s/\bDL_F034E8\b/ToneEditPage_A5_RepaintField_DL1/g
s/\bDL_F03522\b/ToneEditPage_A5_RepaintField_DL2/g
s/\bDL_F035CA\b/ToneEditPage_A6_Paint_DL/g
s/\bDL_F03633\b/ToneEditPage_A7_Paint_DL1/g
s/\bDL_F036A3\b/ToneEditPage_A7_Paint_DL2/g
s/\bDL_F0402E\b/TouchCurve_DrawCurrentSlot_DL2/g
s/\bDL_F04038\b/TouchCurve_DrawCurrentSlot_DL1/g
s/\bDL_F04560\b/Draw_Page22KeyFollowEnvelopeKeyFollowTouchAtk_DL1/g
s/\bDL_F049D3\b/Draw_Page12EnvelopeKeyoffCurSor_DL1/g
s/\bDL_F049F3\b/Draw_Keyoff_DL3/g
s/\bDL_F04CA9\b/Draw_Page22KeyFollowEnvelopeKeyFollowTouchAttack_DL1/g
s/\bDL_F04CDE\b/SoundEditModelingToneTemplate_RepaintField_DL/g
s/\bDL_F04E42\b/Draw_FilterBandPassLowHighCutoff_DL/g
s/\bDL_F04EAB\b/Draw_Page12EnvelopeKeyoffCurSor_DL2/g
s/\bDL_F04F32\b/SoundEditEnvelope1_RepaintField_DL/g
s/\bDL_F04F72\b/Draw_Page12LevelTouchCurveLevel_DL/g
s/\bDL_F050AB\b/SoundEditAmpEnvelope1_Paint_DL1/g
s/\bDL_F0510D\b/Draw_Page22KeyFollowEnvelopeKeyFollowTouchAtk_DL2/g
s/\bDL_F051C2\b/Draw_KeyDeToneKeyScalingShift_DL/g
s/\bDL_F0535E\b/SoundEditPitchTune_RepaintField_DL1/g
s/\bDL_F05368\b/SoundEditPitchTune_RepaintField_DL2/g
s/\bDL_F053E3\b/SoundEditLfo_RepaintField_DL2/g
s/\bDL_F0549D\b/SoundEditLfo_RepaintField_DL1/g
s/\bDL_F05A2E\b/Draw_Write_DL2/g
s/\bDL_F05A38\b/Draw_Write_DL1/g
s/\bDL_F05A42\b/Draw_Write_DL3/g
s/\bDL_F05AA0\b/SoundEditNaming_RepaintField_DL2/g
s/\bDL_F05AAA\b/SoundEditNaming_RepaintField_DL1/g
s/\bDL_F060E4\b/SoundEditToneLayerKeyLayer_Paint_DL1/g
s/\bDL_F06154\b/SoundEditToneLayerVelocityLayer_Paint_DL1/g
s/\bDL_F064E5\b/Draw_Serial_DL2/g
s/\bDL_F064F9\b/ToneEditPage_A8_RepaintField_DL1/g
s/\bDL_F06517\b/ToneEditPage_A8_RepaintField_DL2/g
s/\bDL_F06544\b/ToneEditPage_A8_RepaintField_DL3/g
s/\bDL_F06576\b/Draw_Serial_DL1/g
s/\bDL_F0CA5C\b/MidiTotalMode_PaintSingleChannel_DL/g
s/\bDL_F0D023\b/MidiOutProgramChange_PaintBankLsb_DL/g
s/\bDL_F0D02D\b/MidiOutProgramChange_PaintBankSelect_DL/g
s/\bDL_F0D7E2\b/Paint_SysPartMidiSoundCombination_DL/g
s/\bDL_F0D99C\b/SysexProgressBar_DrawDots_DL/g
s/\bDL_F13F3C\b/EffectEditor_PaintJob0_DL1/g
s/\bDL_F140B2\b/EffectEditor_PaintJob2_DL3/g
s/\bDL_F1417C\b/EffectEditor_PaintJob5_Common_DL1/g
s/\bDL_F14186\b/EffectEditor_PaintJob5_Common_DL2/g
s/\bDL_F14297\b/EqGraph_Draw_DL/g
s/\bDL_F142A1\b/EffectEditor_PaintJob0_DL3/g
s/\bDL_F142AB\b/EffectEditor_PaintJob0_DL2/g
s/\bDL_F1435B\b/EffectEditor_PaintJob1_DL3/g
s/\bDL_F143E0\b/EffectEditor_PaintJob2_DL2/g
s/\bDL_F143EF\b/EffectEditor_PaintJob1_DL4/g
s/\bDL_F1441C\b/EffectEditor_PaintJob1_DL2/g
s/\bDL_F14427\b/EffectEditor_PaintJob1_DL1/g
s/\bDL_F14432\b/EffectEditor_PaintJob2_DL1/g
s/\bDL_F1449F\b/EffectEditor_PaintJob2_DL11/g
s/\bDL_F14562\b/EffectEditor_PaintJob2_DL12/g
s/\bDL_F1459C\b/EffectEditor_PaintJob2_DL5/g
s/\bDL_F145A6\b/EffectEditor_PaintJob2_DL7/g
s/\bDL_F145B5\b/EffectEditor_PaintJob2_DL10/g
s/\bDL_F145D9\b/EffectEditor_PaintJob1_DL5/g
s/\bDL_F145EA\b/EffectEditor_PaintJob2_DL4/g
s/\bDL_F145F9\b/EffectEditor_PaintJob2_DL9/g
s/\bDL_F14608\b/EffectEditor_PaintJob2_DL8/g
s/\bDL_F14617\b/EffectEditor_PaintJob2_DL6/g
s/\bDL_F146E1\b/EffectEditor_PaintJob6_DL/g
s/\bDL_F18C1C\b/CombiEditSound_PageIndex_DL/g
s/\bDL_F19781\b/CombiEditSound_PaintLevelsPage_DL3/g
s/\bDL_F19790\b/CombiEditSound_PaintLevelsPage_DL8/g
s/\bDL_F197AE\b/CombiEditSound_PaintLevelsPage_DL1/g
s/\bDL_F197B8\b/CombiEditSound_PaintLevelsPage_DL2/g
s/\bDL_F197C2\b/CombiEditSound_PaintLevelsPage_DL4/g
s/\bDL_F197CC\b/CombiEditSound_PaintLevelsPage_DL5/g
s/\bDL_F197D7\b/CombiEditSound_PaintLevelsPage_DL6/g
s/\bDL_F197E2\b/CombiEditSound_PaintLevelsPage_DL7/g
s/\bDL_F19818\b/CombiEditSound_PaintControllerFilterPage_DL/g
s/\bDL_F198BD\b/CombiEditSound_PaintAssignAndInputFilterPage_DL1/g
s/\bDL_F198CC\b/CombiEditSound_PaintAssignAndInputFilterPage_DL2/g
s/\bDL_F198D7\b/CombiEditSound_PaintAssignAndInputFilterPage_DL3/g
s/\bDL_F198E6\b/CombiEditSound_PaintAssignAndInputFilterPage_DL4/g
s/\bDL_F198F5\b/CombiEditSound_PaintAssignAndInputFilterPage_DL5/g
s/\bDL_F19904\b/CombiEditSound_PaintMidiOutPage_DL1/g
s/\bDL_F19913\b/CombiEditSound_PaintMidiOutPage_DL3/g
s/\bDL_F19922\b/CombiEditSound_PaintMidiOutPage_DL5/g
s/\bDL_F19931\b/CombiEditSound_PaintMidiOutPage_DL2/g
s/\bDL_F19940\b/CombiEditSound_PaintMidiOutPage_DL4/g
s/\bDL_F1994F\b/CombiEditSound_PaintMidiOutPage_DL6/g
s/\bDL_F1995A\b/CombiEditSound_PaintMidiOutFilterPage_DL/g
s/\bDL_F199FF\b/CombiEditSound_PaintMultipleMessagesPage_DL1/g
s/\bDL_F19A09\b/CombiEditSound_PaintMultipleMessagesPage_DL5/g
s/\bDL_F19A18\b/CombiEditSound_PaintMultipleMessagesPage_DL4/g
s/\bDL_F19A22\b/CombiEditSound_PaintMultipleMessagesPage_DL3/g
s/\bDL_F19A31\b/CombiEditSound_PaintMultipleMessagesPage_DL2/g
s/\bDL_F19A3B\b/CombiEditSound_PaintMultipleMessagesPage_DL6/g
s/\bDL_F19A4A\b/CombiEditSound_PaintMultipleMessagesPage_DL8/g
s/\bDL_F19A59\b/CombiEditSound_PaintMultipleMessagesPage_DL7/g
s/\bDL_F19A63\b/CombiEditSound_PaintMultipleMessagesPage_DL9/g
s/\bDL_F19A72\b/CombiEditSound_PaintMultipleMessagesPage_DL10/g
s/\bDL_F19A81\b/CombiEditSound_PaintMultipleMessagesPage_DL12/g
s/\bDL_F19A90\b/CombiEditSound_PaintMultipleMessagesPage_DL11/g
s/\bDL_F19A9A\b/CombiEditSound_PaintMultipleMessagesPage_DL14/g
s/\bDL_F19AA9\b/CombiEditSound_PaintMultipleMessagesPage_DL13/g
s/\bDL_F1A019\b/ExitKey_CombiEditConfigure_DL2/g
s/\bDL_F1A02D\b/ExitKey_CombiEditConfigure_DL1/g
s/\bDL_F1A137\b/CombiEditConfigure_RepaintMarkedSounds_DL4/g
s/\bDL_F1A14D\b/CombiEditConfigure_RepaintMarkedSounds_DL3/g
s/\bDL_F1A158\b/ExitKey_CombiEditConfigure_DL3/g
s/\bDL_F1A163\b/CombiEditConfigure_RepaintMarkedSounds_DL2/g
s/\bDL_F1A179\b/CombiEditConfigure_RepaintMarkedSounds_DL1/g
s/\bDL_F1A183\b/CombiEditConfigure_RepaintMarkedSounds_DL5/g
s/\bDL_F1A2AD\b/CombiEditConfigure_DrawMidiSettings_DL/g
s/\bDL_F1A53F\b/CombiEditConfigure_DrawKeyLayers_DL/g
s/\bDL_F1A7AF\b/CombiEditConfigure_DrawVelocityLayers_DL/g
s/\bDL_F1A8EF\b/ExitKey_Effect2OutputConflict_DL/g
s/\bDL_F28331\b/Paint_SoundMode_DeadCopy_DL/g
s/\bDL_F2833B\b/Paint_SoundMode_DL/g
s/\bDL_F28373\b/Paint_Drawbar_DL1/g
s/\bDL_F2837D\b/Paint_Drawbar_DL2/g
s/\bDL_F286A2\b/C0mbinati0nM0de_RepaintPage1Fields_DL/g
s/\bDL_F28938\b/Paint_C0mbinati0nM0dePage1_DL1/g
s/\bDL_F28DF3\b/Paint_C0mbinati0nM0dePage1_DL2/g
s/\bDL_F28E1B\b/Paint_C0mbinati0nM0dePage1_DL3/g
s/\bDL_F29121\b/Paint_C0mbinati0nM0dePage1_DL4/g
s/\bDL_F296AE\b/C0mbinati0nM0de_HighlightSoundRow_DL/g
s/\bDL_F296B8\b/C0mbinati0nM0de_HighlightIntRow_DL/g
s/\bDL_F296C2\b/C0mbinati0nM0de_HighlightPanRow_DL/g
s/\bDL_F29783\b/Paint_C0mbinati0nM0dePage2Sound1_DL/g
s/\bDL_F29863\b/Paint_C0mbinati0nM0dePage2Sound2_DL/g
s/\bDL_F29880\b/Paint_C0mbinati0nM0dePage2Sound3_DL/g
s/\bDL_F2989D\b/Paint_C0mbinati0nM0dePage2Sound4_DL/g
s/\bDL_F298BA\b/Paint_C0mbinati0nM0dePage2Sound5_DL/g
s/\bDL_F298D7\b/Paint_C0mbinati0nM0dePage2Sound6_DL/g
s/\bDL_F298F4\b/Paint_C0mbinati0nM0dePage2Sound7_DL/g
s/\bDL_F29911\b/C0mbinati0nM0de_DrawPart8Sound_DL/g
s/\bDL_F2992E\b/C0mbinati0nM0de_DrawPart1Int_DL/g
s/\bDL_F29964\b/C0mbinati0nM0de_DrawPart2Int_DL/g
s/\bDL_F2999A\b/C0mbinati0nM0de_DrawPart3Int_DL/g
s/\bDL_F299D0\b/C0mbinati0nM0de_DrawPart4Int_DL/g
s/\bDL_F29A06\b/C0mbinati0nM0de_DrawPart5Int_DL/g
s/\bDL_F29A3C\b/C0mbinati0nM0de_DrawPart6Int_DL/g
s/\bDL_F29A72\b/C0mbinati0nM0de_DrawPart7Int_DL/g
s/\bDL_F29AA8\b/C0mbinati0nM0de_DrawPart8Int_DL/g
s/\bDL_F29ADE\b/C0mbinati0nM0de_DrawPart1Pan_DL/g
s/\bDL_F29AEF\b/C0mbinati0nM0de_DrawPart2Pan_DL/g
s/\bDL_F29B00\b/C0mbinati0nM0de_DrawPart3Pan_DL/g
s/\bDL_F29B11\b/C0mbinati0nM0de_DrawPart4Pan_DL/g
s/\bDL_F29B22\b/C0mbinati0nM0de_DrawPart5Pan_DL/g
s/\bDL_F29B33\b/C0mbinati0nM0de_DrawPart6Pan_DL/g
s/\bDL_F29B44\b/C0mbinati0nM0de_DrawPart7Pan_DL/g
s/\bDL_F29B55\b/C0mbinati0nM0de_DrawPart8Pan_DL/g
s/\bDL_F29B66\b/C0mbinati0nM0de_DrawPart1Vol_DL/g
s/\bDL_F29B72\b/C0mbinati0nM0de_DrawPart2Vol_DL/g
s/\bDL_F29B7E\b/C0mbinati0nM0de_DrawPart3Vol_DL/g
s/\bDL_F29B8A\b/C0mbinati0nM0de_DrawPart4Vol_DL/g
s/\bDL_F29B96\b/C0mbinati0nM0de_DrawPart5Vol_DL/g
s/\bDL_F29BA2\b/C0mbinati0nM0de_DrawPart6Vol_DL/g
s/\bDL_F29BAE\b/C0mbinati0nM0de_DrawPart7Vol_DL/g
s/\bDL_F29BBA\b/C0mbinati0nM0de_DrawPart8Vol_DL/g
s/\bDL_F2AC50\b/Draw_CombinationGroupMenuReMap1_DL/g
s/\bDL_F2AF81\b/Draw_SoundGroupMenuReMap1ReMap2_DL/g
s/\bDL_F2BA0C\b/DisplayHold_DrawHoldHighlight_DL1/g
s/\bDL_F2BA16\b/DisplayHold_DrawHoldHighlight_DL2/g
s/\bDL_F2BA50\b/Paint_Drum_DL1/g
s/\bDL_F2BA5A\b/Paint_Drum_DL2/g
s/\bDL_F2BD48\b/BankLegend_DrawUser_DL3/g
s/\bDL_F2BD52\b/BankLegend_DrawUser_DL2/g
s/\bDL_F2BD96\b/BankLegend_DrawUser_DL1/g
s/\bDL_F2BDA0\b/BankLegend_DrawUser_DL4/g
s/\bDL_F2BDB4\b/GroupCombiDisplayHold_DrawNumberRange_DL2/g
s/\bDL_F2BDC3\b/GroupCombiDisplayHold_DrawNumberRange_DL1/g
s/\bDL_F2BDD2\b/GroupCombiDisplayHold_DrawNumberRange_DL3/g
s/\bDL_F2BDF5\b/GroupDisplayHold_ClearNameSlots_DL/g
s/\bDL_F2CA0D\b/Paint_SineWaveCheckMode_DL3/g
s/\bDL_F32987\b/SoundEditToneLayerPanning_RepaintField_DL2/g
s/\bDL_F32A7D\b/SoundEditToneLayerPanning_RepaintField_DL1/g
s/\bDL_F32AD7\b/SoundEditToneLayerKeyLayer_Paint_DL2/g
s/\bDL_F32B64\b/SoundEditToneLayerVelocityLayer_Paint_DL2/g
s/\bDL_F32BAB\b/Draw_Page22KeyFollowEnvelopeKeyFollowTouchAttack_DL2/g
s/\bDL_F32D2C\b/SoundEditController_PaintPage1_DL/g
s/\bDL_F33362\b/SoundEditController_RepaintFieldPage1_DL1/g
s/\bDL_F3338A\b/SoundEditController_RepaintFieldPage1_DL2/g
s/\bDL_F334FE\b/SoundEditController_RepaintFieldPage2_DL/g
s/\bDL_F33836\b/SoundEditAmpLevel1_RepaintField_DL/g
s/\bDL_F33858\b/SoundEditAmpEnvelope1_Paint_DL2/g
s/\bDL_F338C9\b/Draw_Keyoff_DL1/g
s/\bDL_F338DD\b/Draw_Keyoff_DL2/g
s/\bDL_F33A3F\b/SoundEditModelingDriverWaveform_RepaintField_DL/g
s/\bDL_F33A71\b/Draw_ToneTemplateLevelKeyTune_DL3/g
s/\bDL_F33B09\b/Draw_ToneTemplateLevelKeyTune_DL4/g
s/\bDL_F33B81\b/Draw_ToneTemplateLevelKeyTune_DL5/g
s/\bDL_F3998E\b/Paint_SongClear_DL3/g
s/\bDL_F39A73\b/Paint_SongClear_DL1/g
s/\bDL_F39BF8\b/Paint_SongClear_DL4/g
s/\bDL_F39C02\b/Paint_SongClear_DL6/g
s/\bDL_F3A40D\b/Paint_TrackAssignPresets_DL2/g
s/\bDL_F3A429\b/Paint_TrackAssignPresets_DL1/g
s/\bDL_F3A5AA\b/Paint_TrackMerge_DL/g
s/\bDL_F3A66E\b/Paint_MeasureDelete_DL/g
s/\bDL_F3A99D\b/Paint_MeasureErase_DL/g
s/\bDL_F3ACB3\b/Paint_Quantize_DL/g
s/\bDL_F3AFAF\b/Paint_N0teChange_DL1/g
s/\bDL_F3B0C3\b/Paint_N0teChange_DL2/g
s/\bDL_F3B244\b/Paint_SongClear_DL2/g
s/\bDL_F3B26C\b/Paint_SongClear_DL5/g
s/\bDL_F3B33C\b/Paint_AdvanceDelay_DL/g
s/\bDL_F3B3DA\b/Paint_TrackAssign_DL1/g
s/\bDL_F3B5A9\b/Paint_TrackAssign_DL2/g
s/\bDL_F3B5D1\b/Paint_TrackLabels1To8_DL/g
s/\bDL_F3B611\b/Paint_TrackLabels9To16_DL/g
s/\bDL_F3BA91\b/Paint_TrackAssign_DL3/g
s/\bDL_F3BC93\b/Paint_MeasureC0py_DL/g
s/\bDL_F3BEBF\b/Paint_MeasureInsert_DL/g
s/\bDL_F3C15D\b/S0ngC0py_DrawFromSong_DL2/g
s/\bDL_F3C16C\b/S0ngC0py_DrawToSong_DL/g
s/\bDL_F3C17B\b/S0ngC0py_DrawTracks_DL/g
s/\bDL_F3C199\b/S0ngC0py_DrawFromSong_DL1/g
s/\bDL_F3C31E\b/S0ngSelectName_DrawValues_DL/g
s/\bDL_F3C530\b/Paint_S0ngC0py_DL/g
s/\bDL_F3C7AD\b/SequencerMedley_DrawPlayState_DL4/g
s/\bDL_F3C7C3\b/SequencerMedley_DrawSourceBox_DL/g
s/\bDL_F3C7CD\b/SequencerMedley_DrawFileTypeBox_DL/g
s/\bDL_F3C86B\b/SequencerMedley_DrawPlayState_DL1/g
s/\bDL_F3C873\b/SequencerMedley_DrawPlayState_DL2/g
s/\bDL_F3C89D\b/SequencerMedley_DrawPlayState_DL3/g
s/\bDL_F3CF09\b/Paint_StepRecord_DL2/g
s/\bDL_F3CFC6\b/Paint_StepRecord_DL1/g
s/\bDL_F3DE26\b/Paint_StepRecord_DL3/g
s/\bDL_F543B0\b/Paint_DrawbarScreenLayout_DL2/g
s/\bDL_F543C4\b/Paint_DrawbarScreenLayout_DL1/g
s/\bDL_F546FA\b/Paint_DrawbarScreenLayout_Unchanged_DL2/g
s/\bDL_F54705\b/Paint_DrawbarScreenLayout_Unchanged_DL1/g
s/\bDL_F58A41\b/ScreenEnter_MidiFileSave_Page0_DL/g
s/\bDL_F58C49\b/ScreenEnter_L0adSingleS0und_Page1_DL/g
s/\bDL_F58DF0\b/ScreenEnter_L0adSingleS0und_Page0_DL/g
s/\bDL_F590C9\b/ScreenEnter_L0adSingleC0mbination_Page0_DL/g
s/\bDL_F59218\b/ScreenEnter_MidiFileSave_Page1_DL1/g
s/\bDL_F59301\b/ScreenEnter_MidiFileSave_Page1_DL2/g
s/\bDL_F593E9\b/Paint_MidiFileL0ad_DL/g
s/\bDL_F5950D\b/Paint_MidiFileDirectPlay_DL/g
s/\bDL_F59915\b/ScreenEnter_MidiFileSave_Page1_DL3/g
s/\bDisplayList_FA22C0\b/TuneScale_LoadFields_DL1/g
s/\bDisplayList_FA230B\b/TuneScale_LoadFields_DL4/g
s/\bDisplayList_FA2315\b/TuneScale_AdjustSelectedItem_Cases_DL/g
s/\bDisplayList_FA2479\b/TuneScale_LoadFields_DL2/g
s/\bDisplayList_FA2522\b/TuneScale_LoadFields_DL3/g
s/\bDisplayList_FA2F57\b/ExitKey_Initial_DL/g
s/\bDisplayList_FA3221\b/Paint_ReMapEdit_DL/g
s/\bDisplayList_FA3230\b/ReMapEdit_DrawFields_DL/g
s/\bDisplayList_FA33A3\b/ReMapEdit_DrawSoundSourceCursor_DL/g
s/\bDisplayList_FA33AE\b/ReMapEdit_DrawSoundReMapCursor_DL/g
s/\bDisplayList_FA33B9\b/ReMapEdit_DrawCombiSourceCursor_DL/g
s/\bDisplayList_FA33C4\b/ReMapEdit_DrawCombiReMapCursor_DL/g
s/\bDisplayList_FA349D\b/ReMapEdit_DrawSoundCombiSelector_DL/g
s/\bDisplayList_FA3CC9\b/SoundCopy_DrawDestGroupCursor_DL/g
s/\bDisplayList_FA3D4F\b/SoundCopy_DrawSourceGroupList_DL/g
s/\bDisplayList_FA406A\b/SoundCopy_DrawDestSoundCursor_DL/g
s/\bDisplayList_FA408D\b/Paint_CombinationCopy_DL/g
s/\bDisplayList_FA414C\b/CombinationCopy_DrawDestGroupCursor_DL/g
s/\bDisplayList_FA4157\b/CombinationCopy_DrawSourceGroupList_DL/g
s/\bDisplayList_FA4270\b/CombinationCopy_DrawDestCombiCursor_DL/g
s/\bDisplayList_FA43C9\b/ExitKey_DataLoadFilter_DL1/g
s/\bDisplayList_FA4432\b/ExitKey_DataLoadFilter_DL2/g
s/\bDisplayList_FA447D\b/ExitKey_DataLoadFilter_DL3/g
s/\bDisplayList_FA458F\b/ExitKey_MemoryProtect_DL1/g
s/\bDisplayList_FA45AD\b/ExitKey_MemoryProtect_DL2/g
s/\bDisplayList_FA45C8\b/ExitKey_MemoryProtect_DL3/g
s/\bDisplayList_FA46B4\b/ExitKey_SoundMute_DL/g
s/\bDisplayList_FA4B9F\b/DrumsMap_DrawRowCursor_DL2/g
s/\bDisplayList_FA4C2A\b/DrumsMap_DrawRowCursor_DL1/g
s/\bDisplayList_FC52AA\b/SoundEditMenu_RepaintField_DL2/g
s/\bDisplayList_FE8405\b/EditPartSelect_DrawPartLabels_DL/g
s/\bDisplayList_FE8E31\b/KeyboardRuler_DrawStrip0_DL/g
s/\bDisplayList_FE8E3D\b/KeyboardRuler_DrawStrip1_DL/g
s/\bDisplayList_FE8E49\b/KeyboardRuler_DrawStrip2_DL/g
s/\bDisplayList_FE8E55\b/KeyboardRuler_DrawStrip3_DL/g
s/\bDisplayList_FE8E61\b/KeyboardRuler_DrawStrip4_DL/g
s/\bDisplayList_FE8E6D\b/KeyboardRuler_DrawStrip5_DL/g
s/\bDisplayList_FE8E79\b/KeyboardRuler_DrawStrip6_DL/g
s/\bDisplayList_FE8E85\b/KeyboardRuler_DrawStrip7_DL/g
s/\bDisplayList_FE8E91\b/KeyboardRuler_DrawStrip8_DL/g
s/\bDisplayList_FE8E9D\b/KeyboardRuler_DrawStrip9_DL/g
s/\bDisplayList_FEB0BC\b/DrumEdit_DrawRowNote0_DL/g
s/\bDisplayList_FEB0E4\b/DrumEdit_DrawRowNote1_DL/g
s/\bDisplayList_FEB10C\b/DrumEdit_DrawRowNote2_DL/g
s/\bDisplayList_FEB134\b/DrumEdit_DrawRowNote3_DL/g
s/\bDisplayList_FEB15C\b/DrumEdit_DrawRowNote4_DL/g
s/\bDisplayList_FEB184\b/DrumEdit_DrawRowNote5_DL/g
s/\bDisplayList_FEB1AC\b/DrumEdit_DrawRowNote6_DL/g
s/\bDisplayList_FEB1D4\b/DrumEdit_DrawRowNote7_DL/g
s/\bDisplayList_FEB1FC\b/DrumEdit_DrawRowNote8_DL/g
s/\bDisplayList_FEB224\b/DrumEdit_DrawRowNote9_DL/g
s/\bDisplayList_FEB24C\b/DrumEdit_DrawRowNote10_DL/g
s/\bDisplayList_FEB274\b/DrumEdit_DrawRowNote11_DL/g
s/\bDisplayList_FEF78C\b/EditScreen_EraseFieldRow_DL/g
s/\bDisplayList_FEF7AA\b/EditScreen_EraseMarkerStrip_DL/g
s/\bDisplayList_FEF7C8\b/EditScreen_EraseHeaderRow_DL/g
s/\bDisplayList_FEF7F5\b/NoteEdit_EraseEditArea_DL/g
s/\bDisplayList_FEF813\b/DrumEdit_EraseEditArea_DL/g
s/\bDisplayList_FEF84F\b/EditScreen_EraseLengthCell_DL/g
s/\bDisplayList_FEF881\b/EditScreen_EraseLeftColumn_Layer1_DL/g
s/\bDisplayList_FEF89F\b/EditScreen_EraseRowLabelArea_DL/g
s/\bDisplayList_FEFA7A\b/EditScreen_MeasureNumberAt0_DL1/g
s/\bDisplayList_FEFA89\b/EditScreen_MeasureNumberAt0_DL2/g
s/\bDisplayList_FEFABF\b/EditScreen_MeasureNumberAt1_DL1/g
s/\bDisplayList_FEFACE\b/EditScreen_MeasureNumberAt1_DL2/g
s/\bDisplayList_FEFB04\b/EditScreen_MeasureNumberAt2_DL1/g
s/\bDisplayList_FEFB13\b/EditScreen_MeasureNumberAt2_DL2/g
s/\bDisplayList_FEFB49\b/EditScreen_MeasureNumberAt3_DL1/g
s/\bDisplayList_FEFB58\b/EditScreen_MeasureNumberAt3_DL2/g
s/\bDisplayList_FEFB8E\b/EditScreen_MeasureNumberAt4_DL1/g
s/\bDisplayList_FEFB9D\b/EditScreen_MeasureNumberAt4_DL2/g
s/\bDisplayList_FEFBD3\b/EditScreen_MeasureNumberAt5_DL1/g
s/\bDisplayList_FEFBE2\b/EditScreen_MeasureNumberAt5_DL2/g
s/\bDisplayList_FEFC18\b/EditScreen_MeasureNumberAt6_DL1/g
s/\bDisplayList_FEFC27\b/EditScreen_MeasureNumberAt6_DL2/g
s/\bDisplayList_FEFC5D\b/EditScreen_MeasureNumberAt7_DL1/g
s/\bDisplayList_FEFC6C\b/EditScreen_MeasureNumberAt7_DL2/g
s/\bDisplayList_FEFCA2\b/EditScreen_MeasureNumberAt8_DL1/g
s/\bDisplayList_FEFCB1\b/EditScreen_MeasureNumberAt8_DL2/g
s/\bDisplayList_FEFCE7\b/EditScreen_MeasureNumberAt9_DL1/g
s/\bDisplayList_FEFCF6\b/EditScreen_MeasureNumberAt9_DL2/g
s/\bDisplayList_FEFD2C\b/EditScreen_MeasureNumberAt10_DL1/g
s/\bDisplayList_FEFD3B\b/EditScreen_MeasureNumberAt10_DL2/g
s/\bDisplayList_FEFD71\b/EditScreen_MeasureNumberAt11_DL1/g
s/\bDisplayList_FEFD80\b/EditScreen_MeasureNumberAt11_DL2/g
s/\bDisplayList_FF037F\b/EditScreen_DrawTrackNumber_DL/g
s/\bDisplayList_FF03A9\b/EditScreen_DrawSongNumber_DL/g
s/\bDisplayList_FF09D8\b/EditScreen_DrawMeasure_DL1/g
s/\bDisplayList_FF09EB\b/EditScreen_DrawMeasure_DL2/g
s/\bDisplayList_FF09F5\b/EditScreen_DrawMeasure_DL3/g
s/\bDisplayList_FF0A39\b/EditScreen_DrawBeat_DL1/g
s/\bDisplayList_FF0A43\b/EditScreen_DrawBeat_DL2/g
s/\bDisplayList_FF0A71\b/EditScreen_DrawTick_DL/g
s/\bDisplayList_FF0AA9\b/DrumEdit_DrawCursorNoteNumber_DL/g
s/\bDisplayList_FF0AEA\b/NoteEdit_DrawCursorNoteName_DL1/g
s/\bDisplayList_FF0AF9\b/NoteEdit_DrawCursorNoteName_DL2/g
s/\bDisplayList_FF0BBE\b/EditScreen_DrawEventVelocity_DL2/g
s/\bDisplayList_FF0BC8\b/EditScreen_DrawEventVelocity_DL4/g
s/\bDisplayList_FF0BD2\b/EditScreen_DrawEventVelocity_DL1/g
s/\bDisplayList_FF0BE1\b/EditScreen_DrawEventVelocity_DL3/g
s/\bDisplayList_FF0D2F\b/NoteEdit_DrawIncNumber_DL/g
s/\bDisplayList_FF0D56\b/DrumEdit_DrawIncLabel_DL/g
