# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F7B000\b/MeasureDelete_InitFields/g
s/\bsub_F7B1D1\b/MeasureDelete_LoadSavedFields/g
s/\bsub_F7B045\b/MeasureDelete_StepFieldUp/g
s/\bsub_F7B08B\b/MeasureDelete_StepFieldDown/g
s/\bsub_F7B07A\b/MeasureDelete_ReturnToStageZero/g
s/\bsub_F7B0B7\b/MeasureDelete_StepTrack/g
s/\bsub_F7B0F2\b/MeasureDelete_StepFirstMeasure/g
s/\bsub_F7B128\b/MeasureDelete_StepLastMeasure/g
s/\bT_F4295C\b/T_MeasureDelete_InitFields/g
s/\bT_F42970\b/T_MeasureDelete_StepFieldUp/g
s/\bT_F42974\b/T_MeasureDelete_StepFieldDown/g
s/\bT_F4297C\b/T_MeasureDelete_ReturnToStageZero/g
s/\bsub_F7B22C\b/MeasureErase_InitFields/g
s/\bsub_F7B457\b/MeasureErase_LoadSavedFields/g
s/\bsub_F7B27C\b/MeasureErase_StepFieldUp/g
s/\bsub_F7B2CE\b/MeasureErase_StepFieldDown/g
s/\bsub_F7B2BD\b/MeasureErase_ReturnToStageZero/g
s/\bsub_F7B306\b/MeasureErase_StepTrack/g
s/\bsub_F7B341\b/MeasureErase_StepFirstMeasure/g
s/\bsub_F7B377\b/MeasureErase_StepLastMeasure/g
s/\bsub_F7B3B1\b/MeasureErase_StepEraseData/g
s/\bT_F42980\b/T_MeasureErase_InitFields/g
s/\bT_F42998\b/T_MeasureErase_StepFieldUp/g
s/\bT_F4299C\b/T_MeasureErase_StepFieldDown/g
s/\bT_F429A4\b/T_MeasureErase_ReturnToStageZero/g
s/\bsub_F7CD30\b/SeqJob_StepTrack/g
s/\bsub_F7CD5F\b/SeqJob_StepMeasure/g
