# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FBE26B\b/CombiEditMixer_DrawPartIconRow/g
s/\bsub_FBE2A4\b/CombiEditMixer_DrawPartBoxRow/g
s/\bsub_FC01FA\b/Msg0716_PostClearSoundRamBanks/g
s/\bsub_FC0215\b/PartSound_RequeuePart0IfUserBank/g
s/\bsub_FC1143\b/PartSound_GetProgramBankPtr/g
s/\bsub_FC1220\b/Cpu2Query_ApplyPartRecordEffects/g
s/\bsub_FC1331\b/Cpu2Query_ApplyToneRecordEffects/g
s/\bsub_FC1475\b/Cpu2Query_ApplyCreatorSelectBits/g
s/\bsub_FC1CD4\b/Cpu2Query_RequestPartRecordEffects/g
s/\bsub_FC1D22\b/Cpu2Query_RequestToneRecordEffects/g
s/\bsub_FD2512\b/ModelingPage_OnPercSource1Reply/g
s/\bsub_FD2569\b/ModelingPage_OnPercSource2Reply/g
s/\bsub_FD25AC\b/SoundEditCopy_OnDrumSoundNameReply/g
s/\bsub_FD25E0\b/SoundEdit_OnStagingFlagsReply/g
s/\bsub_FD26D3\b/ToneEditPage_A0_OnResonatorTypeReply/g
s/\bsub_FD9EB7\b/ModelingPage_StorePercSource1Reply/g
s/\bsub_FD92B7\b/SoundEditEnvelope_DrawSegmentLine/g
s/\bsub_FDA43D\b/Playback_SetMidiStartBlocked/g
s/\bsub_FE019E\b/SeqEvt_ResetPlayingSlotControllers_SaveRegs/g
s/\bsub_FE1522\b/DiskLoadFile_SendSongSelect/g
s/\bsub_FE2642\b/MidiFileSave_ReturnToPage0/g
s/\bsub_FE264C\b/DiskFileDelete_ReportDriveError/g
s/\bsub_FE2EF9\b/Disk_DecrementCountdowns/g
s/\bsub_FEF761\b/EditScreen_ClearCurrentLayer/g
s/\bsub_F37DAE\b/SysExThirdRegion_GetReplyDataBuffer/g
s/\bsub_F4545F\b/BStore_TrackToPart_SaveBackup/g
s/\bsub_F45474\b/BStore_TrackToPart_RestoreBackup/g
s/\bsub_F5B81C\b/List2030_PostSoundSelection/g
s/\bsub_F6B039\b/BStore_SetSongPositionToChainHead/g
s/\bsub_F6B657\b/BStore_DeleteBytesAtSongPosition/g
s/\bsub_F77DB3\b/SmfWriteCopy_WriteFirstWindow/g
s/\bsub_F77DEF\b/SmfWriteCopy_SetOutputWindow/g
s/\bsub_F49ADE\b/SeqRecord_CloseHeldNotesAtCycleWrap/g
s/\bsub_F49AFD\b/SeqRecord_ResetControllersAfterRingOverflow/g
s/\bsub_F49C7D\b/SeqRecord_SkipUnhandledRingEvent/g
s/\bsub_F49CA9\b/SeqRecord_ReadRingEvent/g
s/\bsub_F49CC2\b/CycleRecord_WriteNoteOnToRecordTrack/g
s/\bsub_F49CE6\b/CycleRecord_WriteEventToRecordTrack/g
s/\bsub_F49D00\b/SeqRecord_WriteBeatMarkAndAgeHeldNotes/g
s/\bsub_F49F6D\b/SeqRecord_WriteNoteOn/g
s/\bsub_F4A0FF\b/SeqRecord_CloseHeldNote/g
s/\bsub_F4A26D\b/SeqRecord_WriteParamEvent/g
s/\bsub_F4A2A4\b/SeqRecord_WritePitchBendToTakeTrack/g
s/\bsub_F4A2B6\b/SeqRecord_WriteCtrlEventToTakeTrack/g
s/\bsub_F4A2C8\b/SeqRecord_WriteEventToTakeTrack/g
s/\bMsg0716_PostOp17AndRestageAllParts\b/Msg0716_PostClearSoundRamAndRestageAllParts/g
s/\bMsg0716_PostOp17AndRestageAllParts_SaveRegs\b/Msg0716_PostClearSoundRamAndRestageAllParts_SaveRegs/g
s/\bT_Msg0716_PostOp17AndRestageAllParts\b/T_Msg0716_PostClearSoundRamAndRestageAllParts/g
