#!/usr/bin/env python3
"""Rename LABEL_* to semantic names in region EB0704-EB27E0.
Uses binary I/O to handle encoding safely.

This region is entirely data — string tables and pointer tables
used by the HDAE5000 UI framework (view/object system).

Sub-regions:
  EB0704-EB192A  Function/method name strings (aligned_string entries)
  EB1940         IconNameTable (pointer table -> iN name strings)
  EB1D3C-EB208A  IconName string entries (iN, i0..i173 + Default/None)
  EB2098         IconBitmapNameTable (pointer table -> iN.bmp strings)
  EB2498-EB27E0  IconBitmapName string entries (iN.bmp, i0.bmp..i173.bmp)
"""
import os, re

RENAMES = [
    # ---- Aligned string entries: function/proc/method name strings ----
    # These are the debug/reflection name strings for the HDAE5000 UI framework.
    # Each label holds the string for the corresponding API entry.
    ('LABEL_EB0704', 'Str_DrawBitmapSPFast',       'Name string: DrawBitmapSPFast'),
    ('LABEL_EB0716', 'Str_GetNamingWindowID',       'Name string: GetNamingWindowID'),
    ('LABEL_EB0728', 'Str_IvScreenProc',            'Name string: IvScreenProc'),
    ('LABEL_EB0736', 'Str_CaptureLcd',              'Name string: CaptureLcd'),
    ('LABEL_EB0742', 'Str_VwUserBitmapProc',        'Name string: VwUserBitmapProc'),
    ('LABEL_EB0754', 'Str_DrawBitmapSP',            'Name string: DrawBitmapSP'),
    ('LABEL_EB0762', 'Str_GetPartSelect',           'Name string: GetPartSelect'),
    ('LABEL_EB0770', 'Str_TrChordBoxProc',          'Name string: TrChordBoxProc'),
    ('LABEL_EB0780', 'Str_TrTransposeBoxProc',      'Name string: TrTransposeBoxProc'),
    ('LABEL_EB0794', 'Str_AcLanguageTextProc',      'Name string: AcLanguageTextProc'),
    ('LABEL_EB07A8', 'Str_PsTextBoxProc',           'Name string: PsTextBoxProc'),
    ('LABEL_EB07B6', 'Str_IvShowHideProc',          'Name string: IvShowHideProc'),
    ('LABEL_EB07C6', 'Str_SetNotDrawFlag',          'Name string: SetNotDrawFlag'),
    ('LABEL_EB07D6', 'Str_ConvertStringsEx',        'Name string: ConvertStringsEx'),
    ('LABEL_EB07E8', 'Str_SetVariFlag',             'Name string: SetVariFlag'),
    ('LABEL_EB07F4', 'Str_IvIntEasySetProc',        'Name string: IvIntEasySetProc'),
    ('LABEL_EB0806', 'Str_IvIntVariProc',           'Name string: IvIntVariProc'),
    ('LABEL_EB0814', 'Str_IvIntCompleteProc',       'Name string: IvIntCompleteProc'),
    ('LABEL_EB0826', 'Str_IvIntErrorProc',          'Name string: IvIntErrorProc'),
    ('LABEL_EB0836', 'Str_IvIntReminderProc',       'Name string: IvIntReminderProc'),
    ('LABEL_EB0848', 'Str_CheckNotDrawFlag',        'Name string: CheckNotDrawFlag'),
    ('LABEL_EB085A', 'Str_SetInterruptTime',        'Name string: SetInterruptTime'),
    ('LABEL_EB086C', 'Str_IvInterruptProc',         'Name string: IvInterruptProc'),
    ('LABEL_EB087C', 'Str_IntTimeIDProc',           'Name string: IntTimeIDProc'),
    ('LABEL_EB088A', 'Str_DbMemoryDumpProc',        'Name string: DbMemoryDumpProc'),
    ('LABEL_EB089C', 'Str_IvExitWindowProc',        'Name string: IvExitWindowProc'),
    ('LABEL_EB08AE', 'Str_IvTrackSwitchProc',       'Name string: IvTrackSwitchProc'),
    ('LABEL_EB08C0', 'Str_GetDirmdFlag',            'Name string: GetDirmdFlag'),
    ('LABEL_EB08CE', 'Str_DirmdEmulator',           'Name string: DirmdEmulator'),
    ('LABEL_EB08DC', 'Str_IvDirmdScreenProc',       'Name string: IvDirmdScreenProc'),
    ('LABEL_EB08EE', 'Str_AcTrackSwitchProc',       'Name string: AcTrackSwitchProc'),
    ('LABEL_EB0900', 'Str_PsTrackSwitchProc',       'Name string: PsTrackSwitchProc'),
    ('LABEL_EB0912', 'Str_DbDebugMenuProc',         'Name string: DbDebugMenuProc'),
    ('LABEL_EB0922', 'Str_AcGridBoxProc',           'Name string: AcGridBoxProc'),
    ('LABEL_EB0930', 'Str_AcListBoxProc',           'Name string: AcListBoxProc'),
    ('LABEL_EB093E', 'Str_PsGridBoxProc',           'Name string: PsGridBoxProc'),
    ('LABEL_EB094C', 'Str_PsListBoxProc',           'Name string: PsListBoxProc'),
    ('LABEL_EB095A', 'Str_GetDialFocus',            'Name string: GetDialFocus'),
    ('LABEL_EB0968', 'Str_SetDialFocus',            'Name string: SetDialFocus'),
    ('LABEL_EB0976', 'Str_IvCatchEventProc',        'Name string: IvCatchEventProc'),
    ('LABEL_EB0988', 'Str_AcStrRadioBoxProc',       'Name string: AcStrRadioBoxProc'),
    ('LABEL_EB099A', 'Str_PsRadioBoxProc',          'Name string: PsRadioBoxProc'),
    ('LABEL_EB09AA', 'Str_AcRamBoxProc',            'Name string: AcRamBoxProc'),
    ('LABEL_EB09B8', 'Str_AcIndexToggleProc',       'Name string: AcIndexToggleProc'),
    ('LABEL_EB09CA', 'Str_IvNamingProc',            'Name string: IvNamingProc'),
    ('LABEL_EB09D8', 'Str_PsCursorBoxProc',         'Name string: PsCursorBoxProc'),
    ('LABEL_EB09E8', 'Str_AcNamingWindowProc',      'Name string: AcNamingWindowProc'),
    ('LABEL_EB09FC', 'Str_IvFixWinProc',            'Name string: IvFixWinProc'),
    ('LABEL_EB0A0A', 'Str_GetBoxCenter',            'Name string: GetBoxCenter'),
    ('LABEL_EB0A18', 'Str_DrawStringReverse',       'Name string: DrawStringReverse'),
    ('LABEL_EB0A2A', 'Str_IvExitScreenProc',        'Name string: IvExitScreenProc'),
    ('LABEL_EB0A3C', 'Str_IvExitModeProc',          'Name string: IvExitModeProc'),
    ('LABEL_EB0A4C', 'Str_IvExitProc',              'Name string: IvExitProc'),
    ('LABEL_EB0A58', 'Str_GetFocusParam',           'Name string: GetFocusParam'),
    ('LABEL_EB0A66', 'Str_GetFocusEvent',           'Name string: GetFocusEvent'),
    ('LABEL_EB0A74', 'Str_GetFocusObject',          'Name string: GetFocusObject'),
    ('LABEL_EB0A84', 'Str_SetRootObject',           'Name string: SetRootObject'),
    ('LABEL_EB0A92', 'Str_SetAutoInc',              'Name string: SetAutoInc'),
    ('LABEL_EB0A9E', 'Str_SetAutoIncDefault',       'Name string: SetAutoIncDefault'),
    ('LABEL_EB0AB0', 'Str_GetRootParam',            'Name string: GetRootParam'),
    ('LABEL_EB0ABE', 'Str_GetRootEvent',            'Name string: GetRootEvent'),
    ('LABEL_EB0ACC', 'Str_GetRootObject',           'Name string: GetRootObject'),
    ('LABEL_EB0ADA', 'Str_KillApTimer',             'Name string: KillApTimer'),
    ('LABEL_EB0AE6', 'Str_ResetApTimer',            'Name string: ResetApTimer'),
    ('LABEL_EB0AF4', 'Str_SetApTimer',              'Name string: SetApTimer'),
    ('LABEL_EB0B00', 'Str_ApTimer',                 'Name string: ApTimer'),
    ('LABEL_EB0B08', 'Str_InitializeTimer',         'Name string: InitializeTimer'),
    ('LABEL_EB0B18', 'Str_DbMemoProc',              'Name string: DbMemoProc'),
    ('LABEL_EB0B24', 'Str_PsWideToggleProc',        'Name string: PsWideToggleProc'),
    ('LABEL_EB0B36', 'Str_AcFuncToggleProc',        'Name string: AcFuncToggleProc'),
    ('LABEL_EB0B48', 'Str_MainBitGet',              'Name string: MainBitGet'),
    ('LABEL_EB0B54', 'Str_MainBitPut',              'Name string: MainBitPut'),
    ('LABEL_EB0B60', 'Str_AcBitEditBoxProc',        'Name string: AcBitEditBoxProc'),
    ('LABEL_EB0B72', 'Str_VwEditSwBoxProc',         'Name string: VwEditSwBoxProc'),
    ('LABEL_EB0B82', 'Str_VwMenuBoxProc',           'Name string: VwMenuBoxProc'),
    ('LABEL_EB0B90', 'Str_AcMixerVolProc',          'Name string: AcMixerVolProc'),
    ('LABEL_EB0BA0', 'Str_AcPmemNameProc',          'Name string: AcPmemNameProc'),
    ('LABEL_EB0BB0', 'Str_AcRhythmNameProc',        'Name string: AcRhythmNameProc'),
    ('LABEL_EB0BC2', 'Str_AcSoundNameProc',         'Name string: AcSoundNameProc'),
    ('LABEL_EB0BD2', 'Str_GetWallPaletteRGB',       'Name string: GetWallPaletteRGB'),
    ('LABEL_EB0BE4', 'Str_ChangeWallPalette',       'Name string: ChangeWallPalette'),
    ('LABEL_EB0BF6', 'Str_SetDialDown',             'Name string: SetDialDown'),
    ('LABEL_EB0C02', 'Str_SetDialUp',               'Name string: SetDialUp'),
    ('LABEL_EB0C0C', 'Str_SetDialEnable',           'Name string: SetDialEnable'),
    ('LABEL_EB0C1A', 'Str_IvMainEditSwProc',        'Name string: IvMainEditSwProc'),
    ('LABEL_EB0C2C', 'Str_IvPageControlProc',       'Name string: IvPageControlProc'),
    ('LABEL_EB0C3E', 'Str_PsInvisibleBoxProc',      'Name string: PsInvisibleBoxProc'),
    ('LABEL_EB0C52', 'Str_PsToggleBoxProc',         'Name string: PsToggleBoxProc'),
    ('LABEL_EB0C62', 'Str_AcWindowPageProc',        'Name string: AcWindowPageProc'),
    ('LABEL_EB0C74', 'Str_PsPageBoxProc',           'Name string: PsPageBoxProc'),
    ('LABEL_EB0C82', 'Str_AcFuncEditSwProc',        'Name string: AcFuncEditSwProc'),
    ('LABEL_EB0C94', 'Str_AcIndexEditSwProc',       'Name string: AcIndexEditSwProc'),
    ('LABEL_EB0CA6', 'Str_PsWideESBoxProc',         'Name string: PsWideESBoxProc'),
    ('LABEL_EB0CB6', 'Str_PsEditSwBoxProc',         'Name string: PsEditSwBoxProc'),
    ('LABEL_EB0CC6', 'Str_AcTitleMenuProc',         'Name string: AcTitleMenuProc'),
    ('LABEL_EB0CD6', 'Str_PsMenuBoxProc',           'Name string: PsMenuBoxProc'),
    ('LABEL_EB0CE4', 'Str_AcRamEditBoxProc',        'Name string: AcRamEditBoxProc'),
    ('LABEL_EB0CF6', 'Str_AcLswEditBoxProc',        'Name string: AcLswEditBoxProc'),
    ('LABEL_EB0D08', 'Str_AcNumEditBoxProc',        'Name string: AcNumEditBoxProc'),
    ('LABEL_EB0D1A', 'Str_AcOnOffBoxProc',          'Name string: AcOnOffBoxProc'),
    ('LABEL_EB0D2A', 'Str_PsTblEditBoxProc',        'Name string: PsTblEditBoxProc'),
    ('LABEL_EB0D3C', 'Str_PsNumEditBoxProc',        'Name string: PsNumEditBoxProc'),
    ('LABEL_EB0D4E', 'Str_PsEditBoxProc',           'Name string: PsEditBoxProc'),
    ('LABEL_EB0D5C', 'Str_AcTempoBoxProc',          'Name string: AcTempoBoxProc'),
    ('LABEL_EB0D6C', 'Str_AcLswBoxProc',            'Name string: AcLswBoxProc'),
    ('LABEL_EB0D7A', 'Str_PsParaBoxProc',           'Name string: PsParaBoxProc'),
    ('LABEL_EB0D88', 'Str_VwBoxProc',               'Name string: VwBoxProc'),
    ('LABEL_EB0D92', 'Str_TextBoxProc',             'Name string: TextBoxProc'),
    ('LABEL_EB0D9E', 'Str_LineProc',                'Name string: LineProc'),
    ('LABEL_EB0DA8', 'Str_IconProc',                'Name string: IconProc'),
    ('LABEL_EB0DB2', 'Str_BitmapProc',              'Name string: BitmapProc'),
    ('LABEL_EB0DBE', 'Str_LabelProc',               'Name string: LabelProc'),
    ('LABEL_EB0DC8', 'Str_StringBoxProc',           'Name string: StringBoxProc'),
    ('LABEL_EB0DD6', 'Str_WindowProc',              'Name string: WindowProc'),
    ('LABEL_EB0DE2', 'Str_GroupBoxProc',            'Name string: GroupBoxProc'),
    ('LABEL_EB0DF0', 'Str_TitleEditProc',           'Name string: TitleEditProc'),
    ('LABEL_EB0DFE', 'Str_ModeEditProc',            'Name string: ModeEditProc'),
    ('LABEL_EB0E0C', 'Str_MainRamGet',              'Name string: MainRamGet'),
    ('LABEL_EB0E18', 'Str_MainRamAdd',              'Name string: MainRamAdd'),
    ('LABEL_EB0E24', 'Str_MainRamPut',              'Name string: MainRamPut'),
    ('LABEL_EB0E30', 'Str_ResetLswFilter',          'Name string: ResetLswFilter'),
    ('LABEL_EB0E40', 'Str_SetLswFilter',            'Name string: SetLswFilter'),
    ('LABEL_EB0E4E', 'Str_MainLswPartGet',          'Name string: MainLswPartGet'),
    ('LABEL_EB0E5E', 'Str_MainLswGet',              'Name string: MainLswGet'),
    ('LABEL_EB0E6A', 'Str_MainLswPartAdd',          'Name string: MainLswPartAdd'),
    ('LABEL_EB0E7A', 'Str_MainLswAdd',              'Name string: MainLswAdd'),
    ('LABEL_EB0E86', 'Str_MainLswPartPut',          'Name string: MainLswPartPut'),
    ('LABEL_EB0E96', 'Str_MainLswPut',              'Name string: MainLswPut'),
    ('LABEL_EB0EA2', 'Str_DrawEditSw',              'Name string: DrawEditSw'),
    ('LABEL_EB0EAE', 'Str_EditSwProc',              'Name string: EditSwProc'),
    ('LABEL_EB0EBA', 'Str_DrawTitleBar',            'Name string: DrawTitleBar'),
    ('LABEL_EB0EC8', 'Str_TtlScreenProc',           'Name string: TtlScreenProc'),
    ('LABEL_EB0ED6', 'Str_DrawDesignFrame',         'Name string: DrawDesignFrame'),
    ('LABEL_EB0EE6', 'Str_GetClientFrame2',         'Name string: GetClientFrame2'),
    ('LABEL_EB0EF6', 'Str_GetClientFrame',          'Name string: GetClientFrame'),
    ('LABEL_EB0F06', 'Str_FrameProc',               'Name string: FrameProc'),
    ('LABEL_EB0F10', 'Str_GetEditSwPoint',          'Name string: GetEditSwPoint'),
    ('LABEL_EB0F20', 'Str_ScreenProc',              'Name string: ScreenProc'),
    ('LABEL_EB0F2C', 'Str_BoxRightCheck',           'Name string: BoxRightCheck'),
    ('LABEL_EB0F3A', 'Str_BoxLeftCheck',            'Name string: BoxLeftCheck'),
    ('LABEL_EB0F48', 'Str_GetFrameColor',           'Name string: GetFrameColor'),
    ('LABEL_EB0F56', 'Str_DrawDesignBox',           'Name string: DrawDesignBox'),
    ('LABEL_EB0F64', 'Str_GetClientBox2',           'Name string: GetClientBox2'),
    ('LABEL_EB0F72', 'Str_GetClientBox',            'Name string: GetClientBox'),
    ('LABEL_EB0F80', 'Str_BoxProc',                 'Name string: BoxProc'),
    ('LABEL_EB0F88', 'Str_SetBox',                  'Name string: SetBox'),
    ('LABEL_EB0F90', 'Str_GetBox',                  'Name string: GetBox'),
    ('LABEL_EB0F98', 'Str_GetViewInstance',         'Name string: GetViewInstance'),
    ('LABEL_EB0FA8', 'Str_GetLinkView',             'Name string: GetLinkView'),
    ('LABEL_EB0FB4', 'Str_SetSuperView',            'Name string: SetSuperView'),
    ('LABEL_EB0FC2', 'Str_Unlink',                  'Name string: Unlink'),
    ('LABEL_EB0FCA', 'Str_Link',                    'Name string: Link'),
    ('LABEL_EB0FD0', 'Str_SubView',                 'Name string: SubView'),
    ('LABEL_EB0FD8', 'Str_SuperView',               'Name string: SuperView'),
    ('LABEL_EB0FE2', 'Str_PrevView',                'Name string: PrevView'),
    ('LABEL_EB0FEC', 'Str_NextView',                'Name string: NextView'),
    ('LABEL_EB0FF6', 'Str_GetMovable',              'Name string: GetMovable'),
    ('LABEL_EB1002', 'Str_SetMovable',              'Name string: SetMovable'),
    ('LABEL_EB100E', 'Str_GetVisible',              'Name string: GetVisible'),
    ('LABEL_EB101A', 'Str_SetVisible',              'Name string: SetVisible'),
    ('LABEL_EB1026', 'Str_GetChange',               'Name string: GetChange'),
    ('LABEL_EB1030', 'Str_SetChange',               'Name string: SetChange'),
    ('LABEL_EB103A', 'Str_GetConst',                'Name string: GetConst'),
    ('LABEL_EB1044', 'Str_SetConst',                'Name string: SetConst'),
    ('LABEL_EB104E', 'Str_ViewableProc',            'Name string: ViewableProc'),
    ('LABEL_EB105C', 'Str_GetTitleOld',             'Name string: GetTitleOld'),
    ('LABEL_EB1068', 'Str_GetTitleNow',             'Name string: GetTitleNow'),
    ('LABEL_EB1074', 'Str_UnregisteredTitle',       'Name string: UnregisteredTitle'),
    ('LABEL_EB1086', 'Str_RegisterTitle',           'Name string: RegisterTitle'),
    ('LABEL_EB1094', 'Str_TitleProc',               'Name string: TitleProc'),
    ('LABEL_EB109E', 'Str_GetModeOld',              'Name string: GetModeOld'),
    ('LABEL_EB10AA', 'Str_GetModeNow',              'Name string: GetModeNow'),
    ('LABEL_EB10B6', 'Str_UnregisteredMode',        'Name string: UnregisteredMode'),
    ('LABEL_EB10C8', 'Str_RegisterMode',            'Name string: RegisterMode'),
    ('LABEL_EB10D6', 'Str_ModeProc',                'Name string: ModeProc'),
    ('LABEL_EB10E0', 'Str_MainFuncCall',            'Name string: MainFuncCall'),
    ('LABEL_EB10EE', 'Str_ApFuncCall',              'Name string: ApFuncCall'),
    ('LABEL_EB10FA', 'Str_MainFunctionProc',        'Name string: MainFunctionProc'),
    ('LABEL_EB110C', 'Str_ApFunctionProc',          'Name string: ApFunctionProc'),
    ('LABEL_EB111C', 'Str_FunctionProc',            'Name string: FunctionProc'),
    ('LABEL_EB112A', 'Str_TrackIDProc',             'Name string: TrackIDProc'),
    ('LABEL_EB1136', 'Str_PartIDProc',              'Name string: PartIDProc'),
    ('LABEL_EB1142', 'Str_UserIDProc',              'Name string: UserIDProc'),
    ('LABEL_EB114E', 'Str_MainFuncIDProc',          'Name string: MainFuncIDProc'),
    ('LABEL_EB115E', 'Str_ApFuncIDProc',            'Name string: ApFuncIDProc'),
    ('LABEL_EB116C', 'Str_BitmapIDProc',            'Name string: BitmapIDProc'),
    ('LABEL_EB117A', 'Str_FrameIDProc',             'Name string: FrameIDProc'),
    ('LABEL_EB1186', 'Str_LineModeIDProc',          'Name string: LineModeIDProc'),
    ('LABEL_EB1196', 'Str_EditSwStyleIDProc',       'Name string: EditSwStyleIDProc'),
    ('LABEL_EB11A8', 'Str_EditSwIDProc',            'Name string: EditSwIDProc'),
    ('LABEL_EB11B6', 'Str_AlignmentIDProc',         'Name string: AlignmentIDProc'),
    ('LABEL_EB11C6', 'Str_FontIDProc',              'Name string: FontIDProc'),
    ('LABEL_EB11D2', 'Str_IconIDProc',              'Name string: IconIDProc'),
    ('LABEL_EB11DE', 'Str_TitleIDProc',             'Name string: TitleIDProc'),
    ('LABEL_EB11EA', 'Str_ModeIDProc',              'Name string: ModeIDProc'),
    ('LABEL_EB11F6', 'Str_BorderIDProc',            'Name string: BorderIDProc'),
    ('LABEL_EB1204', 'Str_ColorIDProc',             'Name string: ColorIDProc'),
    ('LABEL_EB1210', 'Str_ViewFlagProc',            'Name string: ViewFlagProc'),
    ('LABEL_EB121E', 'Str_ViewIDProc',              'Name string: ViewIDProc'),
    ('LABEL_EB122A', 'Str_ConstFlagProc',           'Name string: ConstFlagProc'),
    ('LABEL_EB1238', 'Str_NameProc',                'Name string: NameProc'),
    ('LABEL_EB1242', 'Str_StringProc',              'Name string: StringProc'),
    ('LABEL_EB124E', 'Str_PointYProc',              'Name string: PointYProc'),
    ('LABEL_EB125A', 'Str_PointXProc',              'Name string: PointXProc'),
    ('LABEL_EB1266', 'Str_POINTWProc',              'Name string: POINTWProc'),
    ('LABEL_EB1272', 'Str_RectY2Proc',              'Name string: RectY2Proc'),
    ('LABEL_EB127E', 'Str_RectX2Proc',              'Name string: RectX2Proc'),
    ('LABEL_EB128A', 'Str_RectY1Proc',              'Name string: RectY1Proc'),
    ('LABEL_EB1296', 'Str_RectX1Proc',              'Name string: RectX1Proc'),
    ('LABEL_EB12A2', 'Str_RECTWProc',               'Name string: RECTWProc'),
    ('LABEL_EB12AC', 'Str_EventIDProc',             'Name string: EventIDProc'),
    ('LABEL_EB12B8', 'Str_WindowIDProc',            'Name string: WindowIDProc'),
    ('LABEL_EB12C6', 'Str_ScreenIDProc',            'Name string: ScreenIDProc'),
    ('LABEL_EB12D4', 'Str_ClassIDProc',             'Name string: ClassIDProc'),
    ('LABEL_EB12E0', 'Str_pStringProc',             'Name string: pStringProc'),
    ('LABEL_EB12EC', 'Str_pPropProc',               'Name string: pPropProc'),
    ('LABEL_EB12F6', 'Str_pProcProc',               'Name string: pProcProc'),
    ('LABEL_EB1300', 'Str_pFuncProc',               'Name string: pFuncProc'),
    ('LABEL_EB130A', 'Str_ObjectIDProc',            'Name string: ObjectIDProc'),
    ('LABEL_EB1318', 'Str_pUlongProc',              'Name string: pUlongProc'),
    ('LABEL_EB1324', 'Str_pSlongProc',              'Name string: pSlongProc'),
    ('LABEL_EB1330', 'Str_pUcharProc',              'Name string: pUcharProc'),
    ('LABEL_EB133C', 'Str_pScharProc',              'Name string: pScharProc'),
    ('LABEL_EB1348', 'Str_pUwordProc',              'Name string: pUwordProc'),
    ('LABEL_EB1354', 'Str_pSwordProc',              'Name string: pSwordProc'),
    ('LABEL_EB1360', 'Str_pBoolProc',               'Name string: pBoolProc'),
    ('LABEL_EB136A', 'Str_boolProc',                'Name string: boolProc'),
    ('LABEL_EB1374', 'Str_ulongProc',               'Name string: ulongProc'),
    ('LABEL_EB137E', 'Str_slongProc',               'Name string: slongProc'),
    ('LABEL_EB1388', 'Str_scharProc',               'Name string: scharProc'),
    ('LABEL_EB1392', 'Str_ucharProc',               'Name string: ucharProc'),
    ('LABEL_EB139C', 'Str_uwordProc',               'Name string: uwordProc'),
    ('LABEL_EB13A6', 'Str_swordProc',               'Name string: swordProc'),
    ('LABEL_EB13B0', 'Str_SupportClassProc',        'Name string: SupportClassProc'),
    ('LABEL_EB13C2', 'Str_ClassProc',               'Name string: ClassProc'),
    ('LABEL_EB13CC', 'Str_WordwrapStrings',         'Name string: WordwrapStrings'),
    ('LABEL_EB13DC', 'Str_CalcTotalWidth',          'Name string: CalcTotalWidth'),
    ('LABEL_EB13EC', 'Str_ConvertStrings',          'Name string: ConvertStrings'),
    ('LABEL_EB13FC', 'Str_GetCenteredDelta',        'Name string: GetCenteredDelta'),
    ('LABEL_EB140E', 'Str_GetCharDescent',          'Name string: GetCharDescent'),
    ('LABEL_EB141E', 'Str_GetCharHeight',           'Name string: GetCharHeight'),
    ('LABEL_EB142C', 'Str_GetFrameSPSize',          'Name string: GetFrameSPSize'),
    ('LABEL_EB143C', 'Str_ResNameProc',             'Name string: ResNameProc'),
    ('LABEL_EB1448', 'Str_ResStringProc',           'Name string: ResStringProc'),
    ('LABEL_EB1456', 'Str_ResMethodProc',           'Name string: ResMethodProc'),
    ('LABEL_EB1464', 'Str_ResEventProc',            'Name string: ResEventProc'),
    ('LABEL_EB1472', 'Str_ResFontProc',             'Name string: ResFontProc'),
    ('LABEL_EB147E', 'Str_ResIconProc',             'Name string: ResIconProc'),
    ('LABEL_EB148A', 'Str_ResFrameProc',            'Name string: ResFrameProc'),
    ('LABEL_EB1498', 'Str_ResBitmapProc',           'Name string: ResBitmapProc'),
    ('LABEL_EB14A6', 'Str_ResourceProc',            'Name string: ResourceProc'),
    ('LABEL_EB14B4', 'Str_ApPostEvent',             'Name string: ApPostEvent'),
    ('LABEL_EB14C0', 'Str_MainGetEvent',            'Name string: MainGetEvent'),
    ('LABEL_EB14CE', 'Str_MainPostEvent',           'Name string: MainPostEvent'),
    ('LABEL_EB14DC', 'Str_MainSendEvent',           'Name string: MainSendEvent'),
    ('LABEL_EB14EA', 'Str_MainDispatchEvent',       'Name string: MainDispatchEvent'),
    ('LABEL_EB14FC', 'Str_SetCurrentTarget',        'Name string: SetCurrentTarget'),
    ('LABEL_EB150E', 'Str_GetCurrentTarget',        'Name string: GetCurrentTarget'),
    ('LABEL_EB1520', 'Str_GetEvent',                'Name string: GetEvent'),
    ('LABEL_EB152A', 'Str_PostEvent',               'Name string: PostEvent'),
    ('LABEL_EB1534', 'Str_SendEvent',               'Name string: SendEvent'),
    ('LABEL_EB153E', 'Str_DispatchEvent',           'Name string: DispatchEvent'),
    ('LABEL_EB154C', 'Str_InitializeEventQueue',    'Name string: InitializeEventQueue'),
    ('LABEL_EB1562', 'Str_CheckViewObject',         'Name string: CheckViewObject'),
    ('LABEL_EB1572', 'Str_CountObject',             'Name string: CountObject'),
    ('LABEL_EB157E', 'Str_UnRegisterObject',        'Name string: UnRegisterObject'),
    ('LABEL_EB1590', 'Str_RegisterObject',          'Name string: RegisterObject'),
    ('LABEL_EB15A0', 'Str_RegisterObjectTable',     'Name string: RegisterObjectTable'),
    ('LABEL_EB15B4', 'Str_InitializeObjectTable',   'Name string: InitializeObjectTable'),
    ('LABEL_EB15CA', 'Str_InheritedProc',           'Name string: InheritedProc'),
    ('LABEL_EB15D8', 'Str_ObjectProc',              'Name string: ObjectProc'),
    ('LABEL_EB15E4', 'Str_DrawStringAlignment',     'Name string: DrawStringAlignment'),
    ('LABEL_EB15F8', 'Str_DrawStringRightJustify',  'Name string: DrawStringRightJustify'),
    ('LABEL_EB1610', 'Str_DrawStringLeftJustify',   'Name string: DrawStringLeftJustify'),
    ('LABEL_EB1626', 'Str_DrawStringCentered',      'Name string: DrawStringCentered'),
    ('LABEL_EB163A', 'Str_DrawString',              'Name string: DrawString'),
    ('LABEL_EB1646', 'Str_DrawFrameSP',             'Name string: DrawFrameSP'),
    ('LABEL_EB1652', 'Str_DrawIcons',               'Name string: DrawIcons'),
    ('LABEL_EB165C', 'Str_DrawBitmap',              'Name string: DrawBitmap'),
    ('LABEL_EB1668', 'Str_DrawWall',                'Name string: DrawWall'),
    ('LABEL_EB1672', 'Str_MovePixels',              'Name string: MovePixels'),
    ('LABEL_EB167E', 'Str_DrawFrameEx',             'Name string: DrawFrameEx'),
    ('LABEL_EB168A', 'Str_DrawFrame',               'Name string: DrawFrame'),
    ('LABEL_EB1694', 'Str_DrawBox',                 'Name string: DrawBox'),
    ('LABEL_EB169C', 'Str_DrawLineEx',              'Name string: DrawLineEx'),
    ('LABEL_EB16A8', 'Str_DrawLine',                'Name string: DrawLine'),
    ('LABEL_EB16B2', 'Str_ModifyPixelEx',           'Name string: ModifyPixelEx'),
    ('LABEL_EB16C0', 'Str_ModifyPixel',             'Name string: ModifyPixel'),
    ('LABEL_EB16CC', 'Str_ReadPixel',               'Name string: ReadPixel'),
    ('LABEL_EB16D6', 'Str_SetChangeRect',           'Name string: SetChangeRect'),
    ('LABEL_EB16E4', 'Str_SetNeedUpdate',           'Name string: SetNeedUpdate'),
    ('LABEL_EB16F2', 'Str_UpdateScreen',            'Name string: UpdateScreen'),
    ('LABEL_EB1700', 'Str_InitializeGraphics',      'Name string: InitializeGraphics'),
    # InitializeUserN strings (user slot initializers)
    ('LABEL_EB1714', 'Str_InitializeUser31',        'Name string: InitializeUser31'),
    ('LABEL_EB1726', 'Str_InitializeUser30',        'Name string: InitializeUser30'),
    ('LABEL_EB1738', 'Str_InitializeUser29',        'Name string: InitializeUser29'),
    ('LABEL_EB174A', 'Str_InitializeUser28',        'Name string: InitializeUser28'),
    ('LABEL_EB175C', 'Str_InitializeUser27',        'Name string: InitializeUser27'),
    ('LABEL_EB176E', 'Str_InitializeUser26',        'Name string: InitializeUser26'),
    ('LABEL_EB1780', 'Str_InitializeUser25',        'Name string: InitializeUser25'),
    ('LABEL_EB1792', 'Str_InitializeUser24',        'Name string: InitializeUser24'),
    ('LABEL_EB17A4', 'Str_InitializeUser23',        'Name string: InitializeUser23'),
    ('LABEL_EB17B6', 'Str_InitializeUser22',        'Name string: InitializeUser22'),
    ('LABEL_EB17C8', 'Str_InitializeUser21',        'Name string: InitializeUser21'),
    ('LABEL_EB17DA', 'Str_InitializeUser20',        'Name string: InitializeUser20'),
    ('LABEL_EB17EC', 'Str_InitializeUser19',        'Name string: InitializeUser19'),
    ('LABEL_EB17FE', 'Str_InitializeUser18',        'Name string: InitializeUser18'),
    ('LABEL_EB1810', 'Str_InitializeUser17',        'Name string: InitializeUser17'),
    ('LABEL_EB1822', 'Str_InitializeUser16',        'Name string: InitializeUser16'),
    ('LABEL_EB1834', 'Str_InitializeUser15',        'Name string: InitializeUser15'),
    ('LABEL_EB1846', 'Str_InitializeUser14',        'Name string: InitializeUser14'),
    ('LABEL_EB1858', 'Str_InitializeUser13',        'Name string: InitializeUser13'),
    ('LABEL_EB186A', 'Str_InitializeUser12',        'Name string: InitializeUser12'),
    # Developer name initializer strings (staff names embedded in ROM)
    ('LABEL_EB187C', 'Str_InitializeNaka',          'Name string: InitializeNaka (staff)'),
    ('LABEL_EB188C', 'Str_InitializeKSS',           'Name string: InitializeKSS (staff)'),
    ('LABEL_EB189A', 'Str_InitializeHama',          'Name string: InitializeHama (staff)'),
    ('LABEL_EB18AA', 'Str_InitializeKubo',          'Name string: InitializeKubo (staff)'),
    ('LABEL_EB18BA', 'Str_InitializeYoko',          'Name string: InitializeYoko (staff)'),
    ('LABEL_EB18CA', 'Str_InitializeScoop',         'Name string: InitializeScoop (staff)'),
    ('LABEL_EB18DA', 'Str_InitializeCheap',         'Name string: InitializeCheap (staff)'),
    ('LABEL_EB18EA', 'Str_InitializeSuna',          'Name string: InitializeSuna (staff)'),
    ('LABEL_EB18FA', 'Str_InitializeEast',          'Name string: InitializeEast (staff)'),
    ('LABEL_EB190A', 'Str_InitializeToshi',         'Name string: InitializeToshi (staff)'),
    ('LABEL_EB191A', 'Str_InitializeMurai',         'Name string: InitializeMurai (staff)'),
    ('LABEL_EB192A', 'Str_InitializeRoot',          'Name string: InitializeRoot'),
    # ---- Pointer table: icon name strings (iN -> string pointer array) ----
    # Points from highest index (i173) down to i0, Default, None
    ('LABEL_EB1940', 'IconNamePtrTable',            'Pointer table: icon name strings iN'),
    # ---- Icon name string entries: "iN" identifiers ----
    # These are symbolic names for icon slots (i0..i173).
    # The pointer table at EB1940 references them in reverse order.
    ('LABEL_EB1D3C', 'IconName_Empty',              'Icon name string: "" (empty/none)'),
    ('LABEL_EB1D3E', 'IconName_i173',               'Icon name string: "i173"'),
    ('LABEL_EB1D44', 'IconName_i172',               'Icon name string: "i172"'),
    ('LABEL_EB1D4A', 'IconName_i171',               'Icon name string: "i171"'),
    ('LABEL_EB1D50', 'IconName_i170',               'Icon name string: "i170"'),
    ('LABEL_EB1D56', 'IconName_i169',               'Icon name string: "i169"'),
    ('LABEL_EB1D5C', 'IconName_i168',               'Icon name string: "i168"'),
    ('LABEL_EB1D62', 'IconName_i167',               'Icon name string: "i167"'),
    ('LABEL_EB1D68', 'IconName_i166',               'Icon name string: "i166"'),
    ('LABEL_EB1D6E', 'IconName_i165',               'Icon name string: "i165"'),
    ('LABEL_EB1D74', 'IconName_i164',               'Icon name string: "i164"'),
    ('LABEL_EB1D7A', 'IconName_i163',               'Icon name string: "i163"'),
    ('LABEL_EB1D80', 'IconName_i162',               'Icon name string: "i162"'),
    ('LABEL_EB1D86', 'IconName_i161',               'Icon name string: "i161"'),
    ('LABEL_EB1D8C', 'IconName_i160',               'Icon name string: "i160"'),
    ('LABEL_EB1D92', 'IconName_i159',               'Icon name string: "i159"'),
    ('LABEL_EB1D98', 'IconName_i158',               'Icon name string: "i158"'),
    ('LABEL_EB1D9E', 'IconName_i157',               'Icon name string: "i157"'),
    ('LABEL_EB1DA4', 'IconName_i156',               'Icon name string: "i156"'),
    ('LABEL_EB1DAA', 'IconName_i155',               'Icon name string: "i155"'),
    ('LABEL_EB1DB0', 'IconName_i154',               'Icon name string: "i154"'),
    ('LABEL_EB1DB6', 'IconName_i153',               'Icon name string: "i153"'),
    ('LABEL_EB1DBC', 'IconName_i152',               'Icon name string: "i152"'),
    ('LABEL_EB1DC2', 'IconName_i151',               'Icon name string: "i151"'),
    ('LABEL_EB1DC8', 'IconName_i150',               'Icon name string: "i150"'),
    ('LABEL_EB1DCE', 'IconName_i149',               'Icon name string: "i149"'),
    ('LABEL_EB1DD4', 'IconName_i148',               'Icon name string: "i148"'),
    ('LABEL_EB1DDA', 'IconName_i147',               'Icon name string: "i147"'),
    ('LABEL_EB1DE0', 'IconName_i146',               'Icon name string: "i146"'),
    ('LABEL_EB1DE6', 'IconName_i145',               'Icon name string: "i145"'),
    ('LABEL_EB1DEC', 'IconName_i144',               'Icon name string: "i144"'),
    ('LABEL_EB1DF2', 'IconName_i143',               'Icon name string: "i143"'),
    ('LABEL_EB1DF8', 'IconName_i142',               'Icon name string: "i142"'),
    ('LABEL_EB1DFE', 'IconName_i141',               'Icon name string: "i141"'),
    ('LABEL_EB1E04', 'IconName_i140',               'Icon name string: "i140"'),
    ('LABEL_EB1E0A', 'IconName_i139',               'Icon name string: "i139"'),
    ('LABEL_EB1E10', 'IconName_i138',               'Icon name string: "i138"'),
    ('LABEL_EB1E16', 'IconName_i137',               'Icon name string: "i137"'),
    ('LABEL_EB1E1C', 'IconName_i136',               'Icon name string: "i136"'),
    ('LABEL_EB1E22', 'IconName_i135',               'Icon name string: "i135"'),
    ('LABEL_EB1E28', 'IconName_i134',               'Icon name string: "i134"'),
    ('LABEL_EB1E2E', 'IconName_i133',               'Icon name string: "i133"'),
    ('LABEL_EB1E34', 'IconName_i132',               'Icon name string: "i132"'),
    ('LABEL_EB1E3A', 'IconName_i131',               'Icon name string: "i131"'),
    ('LABEL_EB1E40', 'IconName_i130',               'Icon name string: "i130"'),
    ('LABEL_EB1E46', 'IconName_i129',               'Icon name string: "i129"'),
    ('LABEL_EB1E4C', 'IconName_i128',               'Icon name string: "i128"'),
    ('LABEL_EB1E52', 'IconName_i127',               'Icon name string: "i127"'),
    ('LABEL_EB1E58', 'IconName_i126',               'Icon name string: "i126"'),
    ('LABEL_EB1E5E', 'IconName_i125',               'Icon name string: "i125"'),
    ('LABEL_EB1E64', 'IconName_i124',               'Icon name string: "i124"'),
    ('LABEL_EB1E6A', 'IconName_i123',               'Icon name string: "i123"'),
    ('LABEL_EB1E70', 'IconName_i122',               'Icon name string: "i122"'),
    ('LABEL_EB1E76', 'IconName_i121',               'Icon name string: "i121"'),
    ('LABEL_EB1E7C', 'IconName_i120',               'Icon name string: "i120"'),
    ('LABEL_EB1E82', 'IconName_i119',               'Icon name string: "i119"'),
    ('LABEL_EB1E88', 'IconName_i118',               'Icon name string: "i118"'),
    ('LABEL_EB1E8E', 'IconName_i117',               'Icon name string: "i117"'),
    ('LABEL_EB1E94', 'IconName_i116',               'Icon name string: "i116"'),
    ('LABEL_EB1E9A', 'IconName_i115',               'Icon name string: "i115"'),
    ('LABEL_EB1EA0', 'IconName_i114',               'Icon name string: "i114"'),
    ('LABEL_EB1EA6', 'IconName_i113',               'Icon name string: "i113"'),
    ('LABEL_EB1EAC', 'IconName_i112',               'Icon name string: "i112"'),
    ('LABEL_EB1EB2', 'IconName_i111',               'Icon name string: "i111"'),
    ('LABEL_EB1EB8', 'IconName_i110',               'Icon name string: "i110"'),
    ('LABEL_EB1EBE', 'IconName_i109',               'Icon name string: "i109"'),
    ('LABEL_EB1EC4', 'IconName_i108',               'Icon name string: "i108"'),
    ('LABEL_EB1ECA', 'IconName_i107',               'Icon name string: "i107"'),
    ('LABEL_EB1ED0', 'IconName_i106',               'Icon name string: "i106"'),
    ('LABEL_EB1ED6', 'IconName_i105',               'Icon name string: "i105"'),
    ('LABEL_EB1EDC', 'IconName_i104',               'Icon name string: "i104"'),
    ('LABEL_EB1EE2', 'IconName_i103',               'Icon name string: "i103"'),
    ('LABEL_EB1EE8', 'IconName_i102',               'Icon name string: "i102"'),
    ('LABEL_EB1EEE', 'IconName_i101',               'Icon name string: "i101"'),
    ('LABEL_EB1EF4', 'IconName_i100',               'Icon name string: "i100"'),
    ('LABEL_EB1EFA', 'IconName_i99',                'Icon name string: "i99"'),
    ('LABEL_EB1EFE', 'IconName_i98',                'Icon name string: "i98"'),
    ('LABEL_EB1F02', 'IconName_i97',                'Icon name string: "i97"'),
    ('LABEL_EB1F06', 'IconName_i96',                'Icon name string: "i96"'),
    ('LABEL_EB1F0A', 'IconName_i95',                'Icon name string: "i95"'),
    ('LABEL_EB1F0E', 'IconName_i94',                'Icon name string: "i94"'),
    ('LABEL_EB1F12', 'IconName_i93',                'Icon name string: "i93"'),
    ('LABEL_EB1F16', 'IconName_i92',                'Icon name string: "i92"'),
    ('LABEL_EB1F1A', 'IconName_i91',                'Icon name string: "i91"'),
    ('LABEL_EB1F1E', 'IconName_i90',                'Icon name string: "i90"'),
    ('LABEL_EB1F22', 'IconName_i89',                'Icon name string: "i89"'),
    ('LABEL_EB1F26', 'IconName_i88',                'Icon name string: "i88"'),
    ('LABEL_EB1F2A', 'IconName_i87',                'Icon name string: "i87"'),
    ('LABEL_EB1F2E', 'IconName_i86',                'Icon name string: "i86"'),
    ('LABEL_EB1F32', 'IconName_i85',                'Icon name string: "i85"'),
    ('LABEL_EB1F36', 'IconName_i84',                'Icon name string: "i84"'),
    ('LABEL_EB1F3A', 'IconName_i83',                'Icon name string: "i83"'),
    ('LABEL_EB1F3E', 'IconName_i82',                'Icon name string: "i82"'),
    ('LABEL_EB1F42', 'IconName_i81',                'Icon name string: "i81"'),
    ('LABEL_EB1F46', 'IconName_i80',                'Icon name string: "i80"'),
    ('LABEL_EB1F4A', 'IconName_i79',                'Icon name string: "i79"'),
    ('LABEL_EB1F4E', 'IconName_i78',                'Icon name string: "i78"'),
    ('LABEL_EB1F52', 'IconName_i77',                'Icon name string: "i77"'),
    ('LABEL_EB1F56', 'IconName_i76',                'Icon name string: "i76"'),
    ('LABEL_EB1F5A', 'IconName_i75',                'Icon name string: "i75"'),
    ('LABEL_EB1F5E', 'IconName_i74',                'Icon name string: "i74"'),
    ('LABEL_EB1F62', 'IconName_i73',                'Icon name string: "i73"'),
    ('LABEL_EB1F66', 'IconName_i72',                'Icon name string: "i72"'),
    ('LABEL_EB1F6A', 'IconName_i71',                'Icon name string: "i71"'),
    ('LABEL_EB1F6E', 'IconName_i70',                'Icon name string: "i70"'),
    ('LABEL_EB1F72', 'IconName_i69',                'Icon name string: "i69"'),
    ('LABEL_EB1F76', 'IconName_i68',                'Icon name string: "i68"'),
    ('LABEL_EB1F7A', 'IconName_i67',                'Icon name string: "i67"'),
    ('LABEL_EB1F7E', 'IconName_i66',                'Icon name string: "i66"'),
    ('LABEL_EB1F82', 'IconName_i65',                'Icon name string: "i65"'),
    ('LABEL_EB1F86', 'IconName_i64',                'Icon name string: "i64"'),
    ('LABEL_EB1F8A', 'IconName_i63',                'Icon name string: "i63"'),
    ('LABEL_EB1F8E', 'IconName_i62',                'Icon name string: "i62"'),
    ('LABEL_EB1F92', 'IconName_i61',                'Icon name string: "i61"'),
    ('LABEL_EB1F96', 'IconName_i60',                'Icon name string: "i60"'),
    ('LABEL_EB1F9A', 'IconName_i59',                'Icon name string: "i59"'),
    ('LABEL_EB1F9E', 'IconName_i58',                'Icon name string: "i58"'),
    ('LABEL_EB1FA2', 'IconName_i57',                'Icon name string: "i57"'),
    ('LABEL_EB1FA6', 'IconName_i56',                'Icon name string: "i56"'),
    ('LABEL_EB1FAA', 'IconName_i55',                'Icon name string: "i55"'),
    ('LABEL_EB1FAE', 'IconName_i54',                'Icon name string: "i54"'),
    ('LABEL_EB1FB2', 'IconName_i53',                'Icon name string: "i53"'),
    ('LABEL_EB1FB6', 'IconName_i52',                'Icon name string: "i52"'),
    ('LABEL_EB1FBA', 'IconName_i51',                'Icon name string: "i51"'),
    ('LABEL_EB1FBE', 'IconName_i50',                'Icon name string: "i50"'),
    ('LABEL_EB1FC2', 'IconName_i49',                'Icon name string: "i49"'),
    ('LABEL_EB1FC6', 'IconName_i48',                'Icon name string: "i48"'),
    ('LABEL_EB1FCA', 'IconName_i47',                'Icon name string: "i47"'),
    ('LABEL_EB1FCE', 'IconName_i46',                'Icon name string: "i46"'),
    ('LABEL_EB1FD2', 'IconName_i45',                'Icon name string: "i45"'),
    ('LABEL_EB1FD6', 'IconName_i44',                'Icon name string: "i44"'),
    ('LABEL_EB1FDA', 'IconName_i43',                'Icon name string: "i43"'),
    ('LABEL_EB1FDE', 'IconName_i42',                'Icon name string: "i42"'),
    ('LABEL_EB1FE2', 'IconName_i41',                'Icon name string: "i41"'),
    ('LABEL_EB1FE6', 'IconName_i40',                'Icon name string: "i40"'),
    ('LABEL_EB1FEA', 'IconName_i39',                'Icon name string: "i39"'),
    ('LABEL_EB1FEE', 'IconName_i38',                'Icon name string: "i38"'),
    ('LABEL_EB1FF2', 'IconName_i37',                'Icon name string: "i37"'),
    ('LABEL_EB1FF6', 'IconName_i36',                'Icon name string: "i36"'),
    ('LABEL_EB1FFA', 'IconName_i35',                'Icon name string: "i35"'),
    ('LABEL_EB1FFE', 'IconName_i34',                'Icon name string: "i34"'),
    ('LABEL_EB2002', 'IconName_i33',                'Icon name string: "i33"'),
    ('LABEL_EB2006', 'IconName_i32',                'Icon name string: "i32"'),
    ('LABEL_EB200A', 'IconName_i31',                'Icon name string: "i31"'),
    ('LABEL_EB200E', 'IconName_i30',                'Icon name string: "i30"'),
    ('LABEL_EB2012', 'IconName_i29',                'Icon name string: "i29"'),
    ('LABEL_EB2016', 'IconName_i28',                'Icon name string: "i28"'),
    ('LABEL_EB201A', 'IconName_i27',                'Icon name string: "i27"'),
    ('LABEL_EB201E', 'IconName_i26',                'Icon name string: "i26"'),
    ('LABEL_EB2022', 'IconName_i25',                'Icon name string: "i25"'),
    ('LABEL_EB2026', 'IconName_i24',                'Icon name string: "i24"'),
    ('LABEL_EB202A', 'IconName_i23',                'Icon name string: "i23"'),
    ('LABEL_EB202E', 'IconName_i22',                'Icon name string: "i22"'),
    ('LABEL_EB2032', 'IconName_i21',                'Icon name string: "i21"'),
    ('LABEL_EB2036', 'IconName_i20',                'Icon name string: "i20"'),
    ('LABEL_EB203A', 'IconName_i19',                'Icon name string: "i19"'),
    ('LABEL_EB203E', 'IconName_i18',                'Icon name string: "i18"'),
    ('LABEL_EB2042', 'IconName_i17',                'Icon name string: "i17"'),
    ('LABEL_EB2046', 'IconName_i16',                'Icon name string: "i16"'),
    ('LABEL_EB204A', 'IconName_i15',                'Icon name string: "i15"'),
    ('LABEL_EB204E', 'IconName_i14',                'Icon name string: "i14"'),
    ('LABEL_EB2052', 'IconName_i13',                'Icon name string: "i13"'),
    ('LABEL_EB2056', 'IconName_i12',                'Icon name string: "i12"'),
    ('LABEL_EB205A', 'IconName_i11',                'Icon name string: "i11"'),
    ('LABEL_EB205E', 'IconName_i10',                'Icon name string: "i10"'),
    ('LABEL_EB2062', 'IconName_i9',                 'Icon name string: "i9"'),
    ('LABEL_EB2066', 'IconName_i8',                 'Icon name string: "i8"'),
    ('LABEL_EB206A', 'IconName_i7',                 'Icon name string: "i7"'),
    ('LABEL_EB206E', 'IconName_i6',                 'Icon name string: "i6"'),
    ('LABEL_EB2072', 'IconName_i5',                 'Icon name string: "i5"'),
    ('LABEL_EB2076', 'IconName_i4',                 'Icon name string: "i4"'),
    ('LABEL_EB207A', 'IconName_i3',                 'Icon name string: "i3"'),
    ('LABEL_EB207E', 'IconName_i2',                 'Icon name string: "i2"'),
    ('LABEL_EB2082', 'IconName_i1',                 'Icon name string: "i1"'),
    ('LABEL_EB2086', 'IconName_i0',                 'Icon name string: "i0"'),
    ('LABEL_EB208A', 'IconName_Default',            'Icon name string: "Default"'),
    # ---- Pointer table: icon bitmap filename strings (iN.bmp) ----
    ('LABEL_EB2098', 'IconBitmapNamePtrTable',      'Pointer table: icon bitmap filenames iN.bmp'),
    # ---- Icon bitmap filename string entries: "iN.bmp" ----
    # These are BMP image filenames for icon slots (i0.bmp..i173.bmp).
    # The pointer table at EB2098 references them in reverse order.
    ('LABEL_EB2498', 'IconBitmapName_Empty',        'Bitmap name string: "" (empty/none)'),
    ('LABEL_EB249A', 'IconBitmapName_i173',         'Bitmap name string: "i173.bmp"'),
    ('LABEL_EB24A4', 'IconBitmapName_i172',         'Bitmap name string: "i172.bmp"'),
    ('LABEL_EB24AE', 'IconBitmapName_i171',         'Bitmap name string: "i171.bmp"'),
    ('LABEL_EB24B8', 'IconBitmapName_i170',         'Bitmap name string: "i170.bmp"'),
    ('LABEL_EB24C2', 'IconBitmapName_i169',         'Bitmap name string: "i169.bmp"'),
    ('LABEL_EB24CC', 'IconBitmapName_i168',         'Bitmap name string: "i168.bmp"'),
    ('LABEL_EB24D6', 'IconBitmapName_i167',         'Bitmap name string: "i167.bmp"'),
    ('LABEL_EB24E0', 'IconBitmapName_i166',         'Bitmap name string: "i166.bmp"'),
    ('LABEL_EB24EA', 'IconBitmapName_i165',         'Bitmap name string: "i165.bmp"'),
    ('LABEL_EB24F4', 'IconBitmapName_i164',         'Bitmap name string: "i164.bmp"'),
    ('LABEL_EB24FE', 'IconBitmapName_i163',         'Bitmap name string: "i163.bmp"'),
    ('LABEL_EB2508', 'IconBitmapName_i162',         'Bitmap name string: "i162.bmp"'),
    ('LABEL_EB2512', 'IconBitmapName_i161',         'Bitmap name string: "i161.bmp"'),
    ('LABEL_EB251C', 'IconBitmapName_i160',         'Bitmap name string: "i160.bmp"'),
    ('LABEL_EB2526', 'IconBitmapName_i159',         'Bitmap name string: "i159.bmp"'),
    ('LABEL_EB2530', 'IconBitmapName_i158',         'Bitmap name string: "i158.bmp"'),
    ('LABEL_EB253A', 'IconBitmapName_i157',         'Bitmap name string: "i157.bmp"'),
    ('LABEL_EB2544', 'IconBitmapName_i156',         'Bitmap name string: "i156.bmp"'),
    ('LABEL_EB254E', 'IconBitmapName_i155',         'Bitmap name string: "i155.bmp"'),
    ('LABEL_EB2558', 'IconBitmapName_i154',         'Bitmap name string: "i154.bmp"'),
    ('LABEL_EB2562', 'IconBitmapName_i153',         'Bitmap name string: "i153.bmp"'),
    ('LABEL_EB256C', 'IconBitmapName_i152',         'Bitmap name string: "i152.bmp"'),
    ('LABEL_EB2576', 'IconBitmapName_i151',         'Bitmap name string: "i151.bmp"'),
    ('LABEL_EB2580', 'IconBitmapName_i150',         'Bitmap name string: "i150.bmp"'),
    ('LABEL_EB258A', 'IconBitmapName_i149',         'Bitmap name string: "i149.bmp"'),
    ('LABEL_EB2594', 'IconBitmapName_i148',         'Bitmap name string: "i148.bmp"'),
    ('LABEL_EB259E', 'IconBitmapName_i147',         'Bitmap name string: "i147.bmp"'),
    ('LABEL_EB25A8', 'IconBitmapName_i146',         'Bitmap name string: "i146.bmp"'),
    ('LABEL_EB25B2', 'IconBitmapName_i145',         'Bitmap name string: "i145.bmp"'),
    ('LABEL_EB25BC', 'IconBitmapName_i144',         'Bitmap name string: "i144.bmp"'),
    ('LABEL_EB25C6', 'IconBitmapName_i143',         'Bitmap name string: "i143.bmp"'),
    ('LABEL_EB25D0', 'IconBitmapName_i142',         'Bitmap name string: "i142.bmp"'),
    ('LABEL_EB25DA', 'IconBitmapName_i141',         'Bitmap name string: "i141.bmp"'),
    ('LABEL_EB25E4', 'IconBitmapName_i140',         'Bitmap name string: "i140.bmp"'),
    ('LABEL_EB25EE', 'IconBitmapName_i139',         'Bitmap name string: "i139.bmp"'),
    ('LABEL_EB25F8', 'IconBitmapName_i138',         'Bitmap name string: "i138.bmp"'),
    ('LABEL_EB2602', 'IconBitmapName_i137',         'Bitmap name string: "i137.bmp"'),
    ('LABEL_EB260C', 'IconBitmapName_i136',         'Bitmap name string: "i136.bmp"'),
    ('LABEL_EB2616', 'IconBitmapName_i135',         'Bitmap name string: "i135.bmp"'),
    ('LABEL_EB2620', 'IconBitmapName_i134',         'Bitmap name string: "i134.bmp"'),
    ('LABEL_EB262A', 'IconBitmapName_i133',         'Bitmap name string: "i133.bmp"'),
    ('LABEL_EB2634', 'IconBitmapName_i132',         'Bitmap name string: "i132.bmp"'),
    ('LABEL_EB263E', 'IconBitmapName_i131',         'Bitmap name string: "i131.bmp"'),
    ('LABEL_EB2648', 'IconBitmapName_i130',         'Bitmap name string: "i130.bmp"'),
    ('LABEL_EB2652', 'IconBitmapName_i129',         'Bitmap name string: "i129.bmp"'),
    ('LABEL_EB265C', 'IconBitmapName_i128',         'Bitmap name string: "i128.bmp"'),
    ('LABEL_EB2666', 'IconBitmapName_i127',         'Bitmap name string: "i127.bmp"'),
    ('LABEL_EB2670', 'IconBitmapName_i126',         'Bitmap name string: "i126.bmp"'),
    ('LABEL_EB267A', 'IconBitmapName_i125',         'Bitmap name string: "i125.bmp"'),
    ('LABEL_EB2684', 'IconBitmapName_i124',         'Bitmap name string: "i124.bmp"'),
    ('LABEL_EB268E', 'IconBitmapName_i123',         'Bitmap name string: "i123.bmp"'),
    ('LABEL_EB2698', 'IconBitmapName_i122',         'Bitmap name string: "i122.bmp"'),
    ('LABEL_EB26A2', 'IconBitmapName_i121',         'Bitmap name string: "i121.bmp"'),
    ('LABEL_EB26AC', 'IconBitmapName_i120',         'Bitmap name string: "i120.bmp"'),
    ('LABEL_EB26B6', 'IconBitmapName_i119',         'Bitmap name string: "i119.bmp"'),
    ('LABEL_EB26C0', 'IconBitmapName_i118',         'Bitmap name string: "i118.bmp"'),
    ('LABEL_EB26CA', 'IconBitmapName_i117',         'Bitmap name string: "i117.bmp"'),
    ('LABEL_EB26D4', 'IconBitmapName_i116',         'Bitmap name string: "i116.bmp"'),
    ('LABEL_EB26DE', 'IconBitmapName_i115',         'Bitmap name string: "i115.bmp"'),
    ('LABEL_EB26E8', 'IconBitmapName_i114',         'Bitmap name string: "i114.bmp"'),
    ('LABEL_EB26F2', 'IconBitmapName_i113',         'Bitmap name string: "i113.bmp"'),
    ('LABEL_EB26FC', 'IconBitmapName_i112',         'Bitmap name string: "i112.bmp"'),
    ('LABEL_EB2706', 'IconBitmapName_i111',         'Bitmap name string: "i111.bmp"'),
    ('LABEL_EB2710', 'IconBitmapName_i110',         'Bitmap name string: "i110.bmp"'),
    ('LABEL_EB271A', 'IconBitmapName_i109',         'Bitmap name string: "i109.bmp"'),
    ('LABEL_EB2724', 'IconBitmapName_i108',         'Bitmap name string: "i108.bmp"'),
    ('LABEL_EB272E', 'IconBitmapName_i107o',        'Bitmap name string: "i107o.bmp" (outline variant)'),
    ('LABEL_EB2738', 'IconBitmapName_i106',         'Bitmap name string: "i106.bmp"'),
    ('LABEL_EB2742', 'IconBitmapName_i105',         'Bitmap name string: "i105.bmp"'),
    ('LABEL_EB274C', 'IconBitmapName_i104',         'Bitmap name string: "i104.bmp"'),
    ('LABEL_EB2756', 'IconBitmapName_i103',         'Bitmap name string: "i103.bmp"'),
    ('LABEL_EB2760', 'IconBitmapName_i102',         'Bitmap name string: "i102.bmp"'),
    ('LABEL_EB276A', 'IconBitmapName_i101',         'Bitmap name string: "i101.bmp"'),
    ('LABEL_EB2774', 'IconBitmapName_i100',         'Bitmap name string: "i100.bmp"'),
    ('LABEL_EB277E', 'IconBitmapName_i99',          'Bitmap name string: "i99.bmp"'),
    ('LABEL_EB2786', 'IconBitmapName_i98',          'Bitmap name string: "i98.bmp"'),
    ('LABEL_EB278E', 'IconBitmapName_i97',          'Bitmap name string: "i97.bmp" (split across lines)'),
    ('LABEL_EB2796', 'IconBitmapName_i96o',         'Bitmap name string: "i96o.bmp" (outline variant)'),
    ('LABEL_EB27A0', 'IconBitmapName_i95',          'Bitmap name string: "i95.bmp"'),
    ('LABEL_EB27A8', 'IconBitmapName_i94',          'Bitmap name string: "i94.bmp"'),
    ('LABEL_EB27B0', 'IconBitmapName_i93o',         'Bitmap name string: "i93o.bmp" (outline variant)'),
    ('LABEL_EB27BA', 'IconBitmapName_i92o',         'Bitmap name string: "i92o.bmp" (outline variant)'),
    ('LABEL_EB27C4', 'IconBitmapName_i91o',         'Bitmap name string: "i91o.bmp" (outline variant)'),
    ('LABEL_EB27CE', 'IconBitmapName_i90o',         'Bitmap name string: "i90o.bmp" (outline variant)'),
    ('LABEL_EB27D8', 'IconBitmapName_i89',          'Bitmap name string: "i89.bmp"'),
    ('LABEL_EB27E0', 'IconBitmapName_i88',          'Bitmap name string: "i88.bmp"'),
]

def main():
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(base, 'maincpu', 'kn5000_v10_program.s')
    with open(src, 'rb') as f:
        content = f.read().decode('latin-1')
    renamed = 0
    for old_label, new_label, comment in RENAMES:
        if old_label not in content:
            print(f'  WARNING: {old_label} not found, skipping')
            continue
        refs = len(re.findall(r'\b' + re.escape(old_label) + r'\b', content))
        new_content = re.sub(r'\b' + re.escape(old_label) + r'\b', new_label, content)
        if new_content != content:
            content = new_content
            renamed += 1
            print(f'  {old_label:25s} -> {new_label:40s} ({refs} refs)')
    with open(src, 'wb') as f:
        f.write(content.encode('latin-1'))
    print(f'\nRenamed {renamed} labels in maincpu')

if __name__ == '__main__':
    main()
