# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F00DA6\b/OldCopy_SoftKeyCol2_SoundEditPitchTune/g
s/\bsub_F00E84\b/OldCopy_SoftKeyCol4_SoundEditPitchTune/g
s/\bsub_F00F81\b/OldCopy_LcdKeyRow1_SoundEditPitchTune/g
s/\bsub_F00F9F\b/OldCopy_LcdKeyRow2_SoundEditPitchTune/g
s/\bsub_F00FBB\b/OldCopy_LcdKeyRow3_SoundEditPitchTune/g
s/\bsub_F00FE4\b/OldCopy_LcdKeyRow4_SoundEditPitchTune/g
s/\bsub_F01031\b/OldCopy_LcdKeyRow5_SoundEditPitchTune/g
s/\bsub_F0107E\b/OldCopy_ExitKey_SoundEditPitchTune/g
s/\bsub_F0109E\b/OldCopy_SoftKeyCol1_SoundEditPitchEnvelope1/g
s/\bsub_F010B7\b/OldCopy_SoftKeyCol2_SoundEditPitchEnvelope1/g
s/\bsub_F010D0\b/OldCopy_SoftKeyCol3_SoundEditPitchEnvelope1/g
s/\bsub_F010E9\b/OldCopy_SoftKeyCol4_SoundEditPitchEnvelope1/g
s/\bsub_F01102\b/OldCopy_SoftKeyCol5_SoundEditPitchEnvelope1/g
s/\bsub_F0111B\b/OldCopy_SoftKeyCol6_SoundEditPitchEnvelope1/g
s/\bsub_F01134\b/OldCopy_SoftKeyCol7_SoundEditPitchEnvelope1/g
s/\bsub_F0114D\b/OldCopy_LcdKeyRow1_SoundEditPitchEnvelope1/g
s/\bsub_F0115E\b/OldCopy_LcdKeyRow2_SoundEditPitchEnvelope1/g
s/\bsub_F0118A\b/OldCopy_LcdKeyRow3_SoundEditPitchEnvelope1/g
s/\bsub_F011B6\b/OldCopy_LcdKeyRow4_SoundEditPitchEnvelope1/g
s/\bsub_F011E4\b/OldCopy_LcdKeyRow5_SoundEditPitchEnvelope1/g
s/\bsub_F01212\b/OldCopy_PageKey_SoundEditPitchEnvelope1/g
s/\bsub_F0122A\b/OldCopy_ExitKey_SoundEditPitchEnvelope1/g
s/\bsub_F0124A\b/OldCopy_SoftKeyCol2_SoundEditPitchEnvelope2/g
s/\bsub_F0125F\b/OldCopy_SoftKeyCol3_SoundEditPitchEnvelope2/g
s/\bsub_F01274\b/OldCopy_SoftKeyCol4_SoundEditPitchEnvelope2/g
s/\bsub_F01289\b/OldCopy_SoftKeyCol5_SoundEditPitchEnvelope2/g
s/\bsub_F0129E\b/OldCopy_SoftKeyCol7_SoundEditPitchEnvelope2/g
s/\bsub_F012B3\b/OldCopy_SoftKeyCol8_SoundEditPitchEnvelope2/g
s/\bsub_F012C8\b/OldCopy_LcdKeyRow1_SoundEditPitchEnvelope2/g
s/\bsub_F012D9\b/OldCopy_LcdKeyRow2_SoundEditPitchEnvelope2/g
s/\bsub_F01305\b/OldCopy_LcdKeyRow3_SoundEditPitchEnvelope2/g
s/\bsub_F01331\b/OldCopy_LcdKeyRow4_SoundEditPitchEnvelope2/g
s/\bsub_F01355\b/OldCopy_LcdKeyRow5_SoundEditPitchEnvelope2/g
s/\bsub_F01379\b/OldCopy_PageKey_SoundEditPitchEnvelope2/g
s/\bsub_F01391\b/OldCopy_ExitKey_SoundEditPitchEnvelope2/g
s/\bsub_F013B1\b/OldCopy_SoftKeyCol2_SoundEditPitchLfo/g
s/\bsub_F013C6\b/OldCopy_SoftKeyCol3_SoundEditPitchLfo/g
s/\bsub_F013DB\b/OldCopy_SoftKeyCol4_SoundEditPitchLfo/g
s/\bsub_F013F0\b/OldCopy_SoftKeyCol5_SoundEditPitchLfo/g
s/\bsub_F01405\b/OldCopy_SoftKeyCol6_SoundEditPitchLfo/g
s/\bsub_F0141A\b/OldCopy_SoftKeyCol7_SoundEditPitchLfo/g
s/\bsub_F0142F\b/OldCopy_SoftKeyCol8_SoundEditPitchLfo/g
s/\bsub_F01444\b/OldCopy_LcdKeyRow1_SoundEditPitchLfo/g
s/\bsub_F01462\b/OldCopy_LcdKeyRow2_SoundEditPitchLfo/g
s/\bsub_F01486\b/OldCopy_LcdKeyRow3_SoundEditPitchLfo/g
s/\bsub_F0149E\b/OldCopy_LcdKeyRow4_SoundEditPitchLfo/g
s/\bsub_F014B6\b/OldCopy_LcdKeyRow5_SoundEditPitchLfo/g
s/\bsub_F014CE\b/OldCopy_ExitKey_SoundEditPitchLfo/g
