# v10: NAKA object tables named <Owner>_<Class>Table_<object id> from their RegObjTabl
# registration (gen_naka_regobj_table_names.py).
s/\bInitializeCheap_PtrTable_2\b/Cheap_ResNameTable_365/g
s/\bInitializeCheap_PtrTable_3\b/Cheap_ResNameTable_367/g
s/\bInitializeCheap_PtrTable_4\b/Cheap_ResNameTable_36B/g
s/\bInitializeCheap_PtrTable_5\b/Cheap_ResNameTable_36C/g
s/\bInitializeCheap_PtrTable_6\b/Cheap_ResNameTable_377/g
s/\bInitializeCheap_PtrTable_7\b/Cheap_ResNameTable_37B/g
s/\bInitializeKubo_PtrTable_72\b/Kubo_MainFunctionTable_448/g
s/\bInitializeKubo_PtrTable_35\b/Kubo_ResNameTable_30A/g
s/\bInitializeKubo_PtrTable_36\b/Kubo_ResNameTable_30B/g
s/\bInitializeKubo_PtrTable_37\b/Kubo_ResNameTable_30C/g
s/\bInitializeKubo_PtrTable_38\b/Kubo_ResNameTable_30E/g
s/\bInitializeKubo_PtrTable_39\b/Kubo_ResNameTable_380/g
s/\bInitializeKubo_PtrTable_40\b/Kubo_ResNameTable_381/g
s/\bInitializeKubo_PtrTable_41\b/Kubo_ResNameTable_382/g
s/\bInitializeKubo_PtrTable_42\b/Kubo_ResNameTable_383/g
s/\bInitializeKubo_PtrTable_43\b/Kubo_ResNameTable_384/g
s/\bInitializeKubo_PtrTable_44\b/Kubo_ResNameTable_385/g
s/\bInitializeKubo_PtrTable_45\b/Kubo_ResNameTable_386/g
s/\bInitializeKubo_PtrTable_46\b/Kubo_ResNameTable_387/g
s/\bInitializeKubo_PtrTable_10\b/Kubo_ViewableTable_088/g
s/\bInitializeKubo_PtrTable_47\b/Kubo_ResNameTable_388/g
s/\bInitializeKubo_PtrTable_11\b/Kubo_ViewableTable_08D/g
s/\bInitializeKubo_PtrTable_48\b/Kubo_ResNameTable_38D/g
s/\bInitializeKubo_PtrTable_12\b/Kubo_ViewableTable_090/g
s/\bInitializeKubo_PtrTable_49\b/Kubo_ResNameTable_390/g
s/\bInitializeKubo_PtrTable_13\b/Kubo_ViewableTable_091/g
s/\bInitializeKubo_PtrTable_50\b/Kubo_ResNameTable_391/g
s/\bInitializeKubo_PtrTable_14\b/Kubo_ViewableTable_093/g
s/\bInitializeKubo_PtrTable_51\b/Kubo_ResNameTable_393/g
s/\bInitializeKubo_PtrTable_15\b/Kubo_ViewableTable_094/g
s/\bInitializeKubo_PtrTable_52\b/Kubo_ResNameTable_394/g
s/\bInitializeKubo_PtrTable_16\b/Kubo_ViewableTable_095/g
s/\bInitializeKubo_PtrTable_53\b/Kubo_ResNameTable_395/g
s/\bInitializeKubo_PtrTable_17\b/Kubo_ViewableTable_096/g
s/\bInitializeKubo_PtrTable_54\b/Kubo_ResNameTable_396/g
s/\bInitializeKubo_PtrTable_18\b/Kubo_ViewableTable_097/g
s/\bInitializeKubo_PtrTable_55\b/Kubo_ResNameTable_397/g
s/\bInitializeKubo_PtrTable_19\b/Kubo_ViewableTable_098/g
s/\bInitializeKubo_PtrTable_56\b/Kubo_ResNameTable_398/g
s/\bInitializeKubo_PtrTable_20\b/Kubo_ViewableTable_099/g
s/\bInitializeKubo_PtrTable_57\b/Kubo_ResNameTable_399/g
s/\bInitializeKubo_PtrTable_21\b/Kubo_ViewableTable_09A/g
s/\bInitializeKubo_PtrTable_58\b/Kubo_ResNameTable_39A/g
s/\bInitializeKubo_PtrTable_22\b/Kubo_ViewableTable_09B/g
s/\bInitializeKubo_PtrTable_59\b/Kubo_ResNameTable_39B/g
s/\bInitializeKubo_PtrTable_23\b/Kubo_ViewableTable_09C/g
s/\bInitializeKubo_PtrTable_60\b/Kubo_ResNameTable_39C/g
s/\bInitializeKubo_PtrTable_24\b/Kubo_ViewableTable_09D/g
s/\bInitializeKubo_PtrTable_61\b/Kubo_ResNameTable_39D/g
s/\bInitializeKubo_PtrTable_25\b/Kubo_ViewableTable_09E/g
s/\bInitializeKubo_PtrTable_62\b/Kubo_ResNameTable_39E/g
s/\bInitializeKubo_PtrTable_26\b/Kubo_ViewableTable_09F/g
s/\bInitializeKubo_PtrTable_63\b/Kubo_ResNameTable_39F/g
s/\bInitializeKubo_PtrTable_27\b/Kubo_ViewableTable_0A0/g
s/\bInitializeKubo_PtrTable_64\b/Kubo_ResNameTable_3A0/g
s/\bInitializeKubo_PtrTable_28\b/Kubo_ViewableTable_0A1/g
s/\bInitializeKubo_PtrTable_65\b/Kubo_ResNameTable_3A1/g
s/\bInitializeKubo_PtrTable_29\b/Kubo_ViewableTable_0A2/g
s/\bInitializeKubo_PtrTable_66\b/Kubo_ResNameTable_3A2/g
s/\bInitializeKubo_PtrTable_30\b/Kubo_ViewableTable_0A3/g
s/\bInitializeKubo_PtrTable_67\b/Kubo_ResNameTable_3A3/g
s/\bInitializeKubo_PtrTable_31\b/Kubo_ViewableTable_0A4/g
s/\bInitializeKubo_PtrTable_68\b/Kubo_ResNameTable_3A4/g
s/\bInitializeKubo_PtrTable_32\b/Kubo_ViewableTable_0AB/g
s/\bInitializeKubo_PtrTable_69\b/Kubo_ResNameTable_3AB/g
s/\bInitializeKubo_PtrTable_33\b/Kubo_ViewableTable_0D6/g
s/\bInitializeKubo_PtrTable_70\b/Kubo_ResNameTable_3D6/g
s/\bInitializeKubo_PtrTable_34\b/Kubo_ViewableTable_0E7/g
s/\bInitializeKubo_PtrTable_71\b/Kubo_ResNameTable_3E7/g
s/\bInitializeMurai_PtrTable_2\b/Murai_ResNameTable_305/g
s/\bInitializeMurai_PtrTable_3\b/Murai_ResNameTable_307/g
s/\bInitializeMurai_PtrTable_4\b/Murai_ResNameTable_308/g
s/\bInitializeKubo_PtrTable_2\b/Kubo_ViewableTable_080/g
s/\bInitializeKubo_PtrTable_3\b/Kubo_ViewableTable_081/g
s/\bInitializeKubo_PtrTable_4\b/Kubo_ViewableTable_082/g
s/\bInitializeKubo_PtrTable_5\b/Kubo_ViewableTable_083/g
s/\bInitializeKubo_PtrTable_6\b/Kubo_ViewableTable_084/g
s/\bInitializeKubo_PtrTable_7\b/Kubo_ViewableTable_085/g
s/\bInitializeKubo_PtrTable_8\b/Kubo_ViewableTable_086/g
s/\bInitializeKubo_PtrTable_9\b/Kubo_ViewableTable_087/g
s/\bInitializeCheap_PtrTable\b/Cheap_ApFuncTable_125/g
s/\bInitializeMurai_PtrTable\b/Murai_ResNameTable_304/g
s/\bInitializeKubo_PtrTable\b/Kubo_ViewableTable_00E/g
s/\bHamaObj_169_Data\b/Hama_ClassTable_169/g
s/\bHamaObj_1C9_Data\b/Hama_ResEventTable_1C9/g
s/\bHamaObj_1E9_Data\b/Hama_ResMethodTable_1E9/g
s/\bHamaObj_129_Data\b/Hama_ApFuncTable_129/g
s/\bHamaObj_429_Data\b/Hama_ApFuncTable_429/g
s/\bHamaObj_109_Data\b/Hama_FunctionTable_109/g
