# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_F72E27\b/SmfMerge_AdvanceReadCursor/g
s/\bsub_F72DC8\b/SmfMerge_AdvanceWriteCursor/g
s/\bsub_F72C36\b/SmfMerge_SaveDestEndCursor/g
s/\bsub_F732DF\b/SmfSplit_AdvanceWriteCursor/g
s/\bsub_F733EB\b/SmfSplit_AdvanceReadCursor/g
s/\bsub_FE1C79\b/DiskLoadFile_Execute/g
s/\bsub_F6B770\b/TrackCursor_StepBackKeepBeatPosition/g
s/\bsub_F6B75E\b/TrackCursor_StepForwardKeepBeatPosition/g
s/\bsub_F6B257\b/StepRecord_AppendBeatMark/g
s/\bsub_F6B243\b/StepRecord_AppendBeatMarkAtTrackEnd/g
s/\bsub_F68DBE\b/StepRecord_ReadEventTickAtCursor/g
s/\bsub_F68D8A\b/StepRecord_NextGridTick/g
s/\bsub_F68D9D\b/StepRecord_PrevGridTick/g
s/\bsub_F6929C\b/StepRecord_ShortenMeasures/g
s/\bsub_F6C230\b/BStore_SkipTickReadFirstDataByte/g
s/\bsub_F48107\b/BStore_StepCursorToNextLeadByte/g
s/\bsub_F49861\b/SeqRecord_SoundAlert/g
s/\bsub_F4A8A1\b/CycleRecord_CountCycleRangeBeatsFromTimeSigs/g
s/\bsub_F4A8F0\b/CycleRecord_CountCycleRangeBeatsFromBeatsPerBar/g
s/\bsub_F4B26F\b/CycleRecord_CountBeatsToCycleEndFromTimeSigs/g
s/\bsub_F4B295\b/CycleRecord_CountBeatsToCycleEndFromBeatsPerBar/g
s/\bsub_F4A93C\b/CycleRecord_MoveSongPositionToTrackEnd/g
s/\bsub_F4ADCC\b/CycleRecord_SetEndCursorAtTakeChain2EndTag/g
s/\bsub_F4B69F\b/CycleRecord_StepCopyDestToNextBlockOrAlloc/g
s/\bsub_F4B726\b/CycleRecord_StepCopySrcToNextBlock/g
s/\bsub_F5E1A1\b/SongEdit_SortBeatMoveEventToAnchor/g
s/\bsub_F5E306\b/SongEdit_SortBeatAdvanceAnchor/g
s/\bsub_F5E370\b/SongEdit_SortBeatAdvanceScan/g
s/\bsub_F62201\b/AdvanceDelay_EnsureBeatMarkBeforeEndTag/g
s/\bsub_F734E8\b/SmfSplit_ClearEventBuffer/g
s/\bsub_F7AFD8\b/TrackMerge_LoadSavedFields/g
s/\bsub_F7C62D\b/Transp0se_StageDisplayFields/g
s/\bsub_F7E81F\b/TrackAssign_DrawOutChannelColumn/g
s/\bsub_F7E852\b/TrackAssign_DrawLocalControlColumn/g
s/\bsub_F7E8CD\b/TrackAssign_DrawParts1To8/g
s/\bsub_F7E8F3\b/TrackAssign_DrawParts9To16/g
s/\bsub_F7E919\b/TrackAssign_DrawTrackGroupHighlight/g
s/\bsub_F7E941\b/TrackAssign_DrawTrackRowHighlight/g
s/\bsub_F7E971\b/ModeEnterBody_Edit/g
s/\bsub_F7F144\b/MeasureDelete_KeypadCommit/g
s/\bsub_F7F1C8\b/MeasureDelete_BlinkSelectedField/g
s/\bsub_F7F470\b/MeasureErase_KeypadCommit/g
s/\bsub_F7F4F4\b/MeasureErase_BlinkSelectedField/g
s/\bsub_F7F574\b/ExitKey_PanelWrite/g
s/\bsub_F7F7DC\b/Quantize_KeypadCommit/g
s/\bsub_F7F860\b/Quantize_BlinkSelectedField/g
s/\bsub_F7FAD2\b/Vel0cityChange_KeypadCommit/g
s/\bsub_F7FBA4\b/Vel0cityChange_KeypadSign/g
s/\bsub_F7FBB7\b/Vel0cityChange_BlinkSelectedField/g
s/\bsub_F7FE19\b/Transp0se_KeypadCommit/g
s/\bsub_F7FED3\b/Transp0se_KeypadSign/g
s/\bsub_F7FEE6\b/Transp0se_BlinkSelectedField/g
s/\bsub_F80F3A\b/ModeEnterBody_StepRecord/g
s/\bsub_F81948\b/Str_SongNameBlank/g
s/\bsub_F82CE8\b/Variant_SendPortBToCpu2/g
s/\bsub_F90B8E\b/ModeScreen_PaintDirtyFields2_DeadCopy/g
s/\bsub_F93BDA\b/GroupCombiDisplayHold_ShowFirstOfTwoPages/g
s/\bsub_F93BE6\b/GroupCombiDisplayHold_ShowSecondOfTwoPages/g
s/\bsub_F93BF2\b/GroupCombiDisplayHold_ShowFirstOfManyPages/g
s/\bsub_F93BFE\b/GroupCombiDisplayHold_ShowNextOfManyPages/g
s/\bsub_F9C058\b/SystemMenu_InitRam/g
s/\bsub_FA0BA4\b/SystemTest_SplitNotesForDisplay/g
s/\bsub_FA0C64\b/SystemTest_BuildNoteLists/g
s/\bsub_FA0D10\b/SystemTest_PlayNotesOnPanelKey/g
s/\bsub_FA0DCC\b/SystemTest_ResetToDefaults/g
s/\bsub_FA102D\b/ControllerAssign_StoreCursorRowChoice/g
s/\bsub_FA10CD\b/ControllerAssign_LoadChoiceIndices/g
s/\bsub_FA5926\b/MIDI_SetRealtimeIgnoreFromVariant/g
s/\bsub_FA7DA3\b/MidiOut_RunPeriodicTimeouts/g
s/\bsub_FA7E0C\b/MidiOut_ResyncChangedParts/g
s/\bsub_FAA03A\b/SoundSel_FromProgramAndBankRegs_StaleCopy/g
s/\bsub_FAA45C\b/CombiSel_ClampToNumberAndBankRegs/g
s/\bsub_FAA7C4\b/ParamChange_NotifyStagedClearSource/g
s/\bsub_FAA7E7\b/SoundSel_StoreRequestGroupMaxMember/g
s/\bsub_FAA808\b/CombiSel_StoreRequestGroupMaxMember/g
s/\bsub_FAB233\b/Queue2C00_AppendStagedDrainPassB/g
s/\bsub_FAB6D7\b/SoundSel_GroupMemberFromProgramAndBank/g
s/\bsub_FAB7E6\b/List2030_ProcessEvents/g
s/\bsub_FAED76\b/SeqEvt_PlayRun/g
s/\bsub_FAF772\b/DspEffect_RepostRotarySpeakerAlgorithm/g
s/\bsub_FB317E\b/SysExSession_OnEnd_SystemPartMidi/g
s/\bsub_FB31CC\b/SysExSession_OnEnd_Sound/g
s/\bsub_FB3202\b/SysExSession_OnEnd_Sequencer/g
s/\bsub_FB3234\b/SysExSession_AbortIfFailed/g
s/\bsub_FB346B\b/Queue2C00_RecordAndDrainPassB/g
s/\bsub_FB3542\b/SysExParam_Set_Group4/g
s/\bsub_FB42FC\b/SysExParam_Request_Group4/g
s/\bsub_FB4E20\b/SysExTx_SendWordFieldParamValue/g
s/\bsub_FB536D\b/SysExTx_CombinationNumberAndBank/g
s/\bsub_FB556D\b/GmReset_SwitchToSoundMode/g
s/\bsub_FB558F\b/GmReset_FieldTablesAndEffectAlgorithms/g
s/\bsub_FB567E\b/GmMode_SaveEffectOutputLoadFilter/g
s/\bsub_FB568D\b/GmMode_RestoreEffectOutputLoadFilter/g
s/\bsub_FB57ED\b/SysExRx_ApplyTempo/g
s/\bsub_FB585E\b/BStore_Workspace_StoreGmModeDefaults/g
s/\bsub_FB5903\b/GmMode_ResetForGmOff/g
s/\bsub_FB5A01\b/ParamImage_SnapshotMarkPart0ProgramChanged/g
s/\bsub_FB5A17\b/GmReset_PartProgramAndBank/g
s/\bsub_FB5BC3\b/GmReset_PartByte4Bit6/g
s/\bsub_FB5CF7\b/GmReset_ApplyPatchLists/g
s/\bsub_FB5D02\b/Tempo_RestoreFromSmfPlay/g
s/\bsub_FB5D38\b/GmReset_PartByte12Bit4/g
s/\bsub_FB5EC3\b/GmReset_AllPartsRpnNull/g
s/\bsub_FB7B79\b/SysExSession_SelectProgressScreen/g
s/\bsub_FB7BA3\b/SysExSession_RequestLabelBlockPaint/g
s/\bsub_FB7BDF\b/SysExSession_SaveProgressFields/g
s/\bsub_FB7C57\b/SysExSession_UpdateSectionStatus/g
s/\bsub_FB7CBD\b/SysExSession_InitProgressBarScale/g
s/\bsub_FB7D09\b/SysExSession_UpdateProgressBarFill/g
s/\bsub_FB7D91\b/SysExSession_DetectProgressChange/g
s/\bsub_FB8117\b/SysExXfer_ClearJobRecords/g
s/\bsub_FB9BA4\b/MidiFilePlay_ApplyGmOnPartSetup/g
s/\bsub_FB9C52\b/MidiFilePlay_ApplyGmOffPartSetup/g
