# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FE1D52\b/DiskLoad_ByContentType/g
s/\bsub_FE2531\b/DiskSave_ByContentType/g
s/\bsub_FE2368\b/DiskLoad_Sequencer/g
s/\bsub_FE2CBF\b/DiskSave_Sequencer/g
s/\bsub_FE202F\b/DiskLoad_Sound/g
s/\bsub_FE2092\b/DiskLoad_Combination/g
s/\bsub_FE1EF1\b/DiskLoad_MidiSetting/g
s/\bsub_FE23BD\b/DiskLoad_SoundRemap/g
s/\bsub_FE23EA\b/DiskLoad_CombiRemap/g
s/\bsub_FE2417\b/DiskLoad_DrumMap/g
s/\bsub_FE2484\b/DiskLoad_ReadRemapFile/g
s/\bsub_FE24BE\b/DiskLoad_CopyBufferWords/g
s/\bsub_FE292D\b/DiskSave_CopyWordsToBuffer/g
s/\bsub_FE1E3C\b/DiskLoad_PanelLswFile/g
s/\bsub_FE2430\b/DiskLoad_PanelSlsFile/g
s/\bsub_FE26E2\b/DiskSave_PanelLswFile/g
s/\bsub_FE28D5\b/DiskSave_PanelSlsFile/g
s/\bsub_FE2993\b/DiskSave_Sound/g
s/\bsub_FE2A21\b/DiskSave_Combination/g
s/\bsub_FE2736\b/DiskSave_MidiSetting/g
s/\bsub_FE2863\b/DiskSave_SoundRemap/g
s/\bsub_FE288B\b/DiskSave_CombiRemap/g
s/\bsub_FE28B3\b/DiskSave_DrumMap/g
s/\bsub_FE2916\b/DiskSave_WriteRemapFile/g
s/\bsub_FE1E29\b/DiskLoad_ReadFileIntoWindow/g
s/\bsub_FE2980\b/DiskSave_WriteWindowToFile/g
s/\bsub_FE1FFF\b/DiskLoad_ApplyPanelImage/g
