# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FB6F24\b/SysExTx_Append/g
s/\bsub_FB6E7F\b/SysExTx_AppendAndSendOnF7/g
s/\bsub_FB6EE9\b/SysExTx_AppendRemainingSize/g
s/\bsub_FB7025\b/SysExTx_AppendContHeaderIfCont/g
s/\bsub_FB7040\b/SysExTx_AppendNibbles/g
s/\bsub_FB70AE\b/SysExTx_AppendContFlag/g
s/\bsub_FB70E6\b/SysExTx_AppendContFlagOne/g
s/\bsub_FB7111\b/SysExTx_AppendChecksumF7/g
s/\bsub_FB7165\b/SysExTx_SendFrameMidi1/g
s/\bsub_FB71BB\b/SysExTx_SendFrameBothPorts/g
s/\bsub_FB5F65\b/SysExTx_PatchModelByteVariant2/g
s/\bsub_FB8081\b/SysExTx_SwapBuffers/g
s/\bsub_FB8105\b/SysExTx_ResetBuffer/g
s/\bsub_FB8028\b/SysExRx_SwapBuffers/g
s/\bsub_FB80F3\b/SysExRx_ResetBuffer/g
s/\bsub_FB7FEB\b/SysExBuf_Reset/g
s/\bsub_FB7F42\b/SysExBuf_InitAll/g
s/\bsub_FB6165\b/SysExRx_AppendByte/g
s/\bsub_FB61B1\b/SysExBuf_ReadByte/g
s/\bsub_FB20CE\b/SysExRx_PollRing601646/g
s/\bsub_FB21CB\b/SysExRx_PollRing601C6E/g
s/\bsub_FB2160\b/SysExRx_ParseDispatch_Ring601646/g
s/\bsub_FB225D\b/SysExRx_ParseDispatch_Ring601C6E/g
s/\bsub_FB63AF\b/SysExRx_ParseMessage/g
s/\bsub_FB63D1\b/SysExRx_MatchTrie/g
s/\bsub_FB6B87\b/SysExRx_CheckCommandClass/g
s/\bsub_FB6BF4\b/SysExRx_CheckAddress/g
s/\bsub_FB6CFC\b/SysExRx_CheckBodyLength/g
s/\bsub_FB6DBD\b/SysExRx_VerifyChecksum/g
s/\bsub_FB6098\b/SysExRx_ReceiveBlocking/g
s/\bsub_FB6072\b/SysExRx_AwaitReply/g
s/\bsub_FB775F\b/SysExRx_CheckMidiErrors/g
s/\bsub_FB7785\b/SysExRx_CheckReplyTimeout/g
s/\bsub_FB77C7\b/SysEx_Wait25Ticks/g
s/\bsub_FB6026\b/SysExDump_AwaitFrameAck/g
s/\bsub_FB6F6B\b/SysExDump_SendFrames/g
s/\bsub_FB6FB2\b/SysExDump_SendFramesStreamed/g
s/\bsub_FB2323\b/SysExDump_Handshake/g
s/\bsub_FB277E\b/SysExDump_SendCategoryDone/g
s/\bsub_FB27AD\b/SysExDump_SendJobDone/g
