# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FD665C\b/ToneMsg88_Id13/g
s/\bsub_F6364D\b/BStore_TimeSigFirstMeasure/g
s/\bsub_FD7782\b/Rec2330_CopyData25/g
s/\bsub_F36A06\b/SysExThirdRegion_MapMelodicOffset/g
s/\bsub_F44516\b/SeqTrackCursors_RewindPlaying/g
s/\bsub_F4491C\b/Seq_RestoreSongParamsOnRequest/g
s/\bsub_F45348\b/SeqRecord_EndTake/g
s/\bsub_F456F0\b/SeqRecord_StartIfEventQueued/g
s/\bsub_F45D9B\b/Seq_ResetTrackExpressionToFull/g
s/\bsub_F45ED2\b/SeqCycle_OnEndMeasureChanged/g
s/\bsub_F47804\b/BStore_DirEntryHeadAtIY/g
s/\bsub_F48F19\b/DiskFile_ReadFirstBlock/g
s/\bsub_F49033\b/DiskFile_BuildLinkCopyRecords/g
s/\bsub_F4A5B5\b/CycleRecord_RestartPass/g
s/\bsub_F4C684\b/CreatorSelectController_LoadNames/g
s/\bsub_F4CA92\b/SeqFile_PrepareSaveAllBanks/g
s/\bsub_F4D00E\b/BStore_ClearSongStore/g
s/\bsub_F4D1B8\b/BStore_CopyWorkspaceRangesToAllBanks/g
s/\bsub_F4D758\b/BStore_CursorAdvanceXHL/g
s/\bsub_F4E05B\b/SeqTrackKey_UpdateTrackState/g
s/\bsub_F4E525\b/Seq_RequestRewindOnEvent/g
s/\bsub_F4ED0C\b/Seq_DelayedLocateToMeasure_Call/g
s/\bsub_F53823\b/Paint_DrawbarScreenValues/g
s/\bsub_F55EEA\b/CyclePlayScreen_DrawValues/g
s/\bsub_F5687D\b/CycleRecordScreen_BlinkEndMeasure/g
s/\bsub_F56F7B\b/CyclePlayScreen_BlinkStartMeasure/g
s/\bsub_F5D47A\b/SoundEditToneLayerPanning_DrawFieldChordTrigger/g
s/\bsub_F5E708\b/MeasureErase_Execute/g
s/\bsub_F483B2\b/SeqTrackCursors_SaveTrack/g
s/\bsub_F67481\b/StepRecord_PostSysEx50_87FromW/g
s/\bsub_FE1705\b/Playback_AcceptMidiStartAndRequestPositionReset/g
s/\bsub_F36C5D\b/SysExThirdRegion_MapOffsetToDspParamRun/g
s/\bsub_F44623\b/CountIn_RebuildRoutingOnLastBeat/g
s/\bsub_F4493E\b/Seq_CountDownMidiStartIgnore/g
s/\bsub_F44CA7\b/MidiOut_SendSongPosition/g
s/\bsub_F453E9\b/SeqRecord_TerminateTakeTracks/g
s/\bsub_F45B48\b/SeqCycle_RewindToStart/g
s/\bsub_F45EF2\b/SeqCycle_RelocateStartAndEnd/g
s/\bsub_F485D7\b/SeqTrackCursors_StepAllBack/g
s/\bsub_F48F75\b/DiskFile_ReadNextWindow/g
s/\bsub_F49808\b/SeqRecord_DrainEventRing/g
s/\bsub_F4A6CF\b/CycleRecord_FreeRecordChain/g
s/\bsub_F4C800\b/BStore_CompactBlocks_Veneer/g
s/\bsub_F4CADA\b/SeqFile_RestoreSavedCurrentBank/g
s/\bsub_F4D017\b/BStore_SeekChainToBeat/g
s/\bsub_F4D238\b/BStore_CopyChainStateToAllBanks/g
s/\bsub_F4D7BD\b/BStore_FormatHeap/g
s/\bsub_F4E151\b/SeqRecord_DisarmTrack/g
s/\bsub_F4EC2B\b/RealtimeRecord_Arm/g
s/\bsub_F4EE73\b/CountIn_ToggleEnable/g
s/\bsub_F5418E\b/Drawbar_SendSettingBytes/g
s/\bsub_F55F45\b/CycleRecordScreen_DrawValues/g
s/\bsub_F569AF\b/CycleRecordScreen_OnStartMeasureChanged/g
s/\bsub_F56FA8\b/CyclePlayScreen_BlinkEndMeasure/g
s/\bsub_F5D4A7\b/SoundEditToneLayerPanning_PaintPanAmountField/g
s/\bsub_F5EB9C\b/BStore_ReadCursorAdvance/g
s/\bsub_F45FE5\b/SeqScreen_RepaintIfPlayOrRecord/g
s/\bsub_FB7E6C\b/SysExSession_RepaintProgressIfChanged/g
s/\bsub_F36CED\b/SysExThirdRegion_LocateDrumChunk/g
s/\bsub_F44809\b/Seq_RewindOnRequest/g
s/\bsub_F44D94\b/Seq_StopWhenTracksEnded/g
s/\bsub_F455CC\b/Seq_StopAll/g
s/\bsub_F45D19\b/BStore_LoadGmTrackDefaults/g
s/\bsub_F45E58\b/SeqCycle_TickDeferredAction/g
s/\bsub_F45FCA\b/Seq_ShowMemoryFullOnRequest/g
s/\bsub_F4869B\b/SeqTrackCursors_Save/g
s/\bsub_F49A3D\b/CycleRecord_CheckIsRecordTrack/g
s/\bsub_F4A6E7\b/SeqRecord_FreeTakeChain2/g
s/\bsub_F4C802\b/BStore_RebuildFreeListAfterLoad_Veneer/g
s/\bsub_F4D005\b/TimedEventRing_ReadNext_Veneer/g
s/\bsub_F4D023\b/BStore_AllocBlock_B_Veneer/g
s/\bsub_F4D651\b/BStore_SkipBeatMarks/g
s/\bsub_F4D89D\b/BStore_FreeChain_B/g
s/\bsub_F4E32A\b/SeqTrack_PlayOffWhileStopped/g
s/\bsub_F4EC8A\b/RealtimeRecord_InitOnModeEnter/g
s/\bsub_F4EEAD\b/SeqPlayScreen_EnsureMeasureNonZero/g
s/\bsub_F55DBE\b/SeqScreen_PaintTrackRecPlayLabels/g
s/\bsub_F566E0\b/CycleRecordScreen_UpdateFieldBlink/g
s/\bsub_F56B14\b/CycleRecordScreen_ApplyEndMeasure/g
s/\bsub_F570DC\b/CyclePlayScreen_ApplyStartMeasure/g
s/\bsub_F5BF9F\b/ModelingPage_PaintFieldReadout/g
s/\bsub_F5DAA2\b/Quantize_Execute/g
s/\bsub_F5EC12\b/MeasureInsert_Execute/g
s/\bsub_F4D861\b/BStore_AllocBlock_B/g
s/\bsub_F62C10\b/BStore_CopyRangeBackward_Call/g
s/\bsub_FB906D\b/Medley_ScheduleNextMidiFile_SaveRegs/g
s/\bsub_F36938\b/SysExThirdRegion_MapMelodicDspParams/g
s/\bsub_F37E1C\b/SysExThirdRegion_SendReplyChunk/g
s/\bsub_F448A3\b/Seq_ApplyStoredSongTempo/g
s/\bsub_F44964\b/SeqRecord_HandleTransportBStartStop/g
s/\bsub_F44E8E\b/SeqTrack_QueueSwitchOffEvents/g
s/\bsub_F4566A\b/SeqMasterTrack_UpdateActiveFromSavedMask/g
s/\bsub_F45D80\b/BStore_LoadNonGmTrackDefaults/g
s/\bsub_F45EAF\b/SeqCycle_ApplyStartMeasureChange/g
s/\bsub_F46015\b/UiScreenFlags_SetRepaintInPlace/g
s/\bsub_F486BA\b/SeqTrackCursors_RestoreSaved/g
s/\bsub_F48FD8\b/PartRecords_RepostMatchingProgramBank/g
s/\bsub_F4A58E\b/SeqRecord_CopyTrackCursorsToBaseline/g
s/\bsub_F4B414\b/SeqRecord_RestoreCursorBaseline/g
s/\bsub_F4CA2A\b/SysExDump_PrepareSequencerData/g
s/\bsub_F4D008\b/TimedEventRing_SkipByte_Veneer/g
s/\bsub_F4D02C\b/BStore_StepCursorOneByte/g
s/\bsub_F4D6F6\b/Seq_BeatsToMeasureAndBeat/g
s/\bsub_F4E390\b/SeqTrack_SwitchPlayOffWhileRunning/g
s/\bsub_F4F2DE\b/PartSound_InitRam/g
s/\bsub_F55E8F\b/CyclePlayEditScreen_DrawValues/g
s/\bsub_F56850\b/CycleRecordScreen_BlinkStartMeasure/g
s/\bsub_F56D7E\b/SeqMasterTrack_SwitchOn/g
s/\bsub_F5723B\b/CyclePlayScreen_QueueEndMeasureChange/g
s/\bsub_F5C772\b/SoundEditFilterKeyFollow_PaintKeyboardAndValues/g
s/\bsub_F5E3DA\b/SongEdit_DeleteMeasures/g
s/\bsub_F5F221\b/SongEdit_CopyMeasures/g
