# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bScreenCode0E_Handler\b/ScreenEnter_StepRecord/g
s/\bScreenLeave_Code0E\b/ScreenLeave_StepRecord/g
s/\bScreenButton_Code0E\b/ScreenButton_StepRecord/g
s/\bsub_F8101E\b/ScreenEnterBody_StepRecord/g
s/\bsub_F81039\b/ScreenLeaveBody_StepRecord/g
s/\bsub_F6A9CA\b/StepRecord_OnEnter/g
s/\bsub_F6AE4B\b/StepRecord_OnLeave/g
s/\bsub_F81ACB\b/Paint_StepRecord/g
s/\bsub_F675CC\b/StepRecord_ButtonByTrackKind/g
s/\bDispatchTable_F675F3\b/StepRecord_TrackKindButtonTable/g
s/\bDispatchTable_F675F3_Nop0\b/StepRecord_TrackKindButtonTable_Nop0/g
s/\bsub_F676B6\b/StepRecord_ButtonBySubScreen/g
s/\bDispatchTable_F67723\b/StepRecord_SubScreenButtonTable/g
s/\bsub_F6776F\b/StepRecord_ButtonBySubScreen_Kind3/g
s/\bDispatchTable_F67789\b/StepRecord_SubScreenButtonTable_Kind3/g
s/\bExitKey_Screen0E\b/ExitKey_StepRecord/g
s/\bLcdKeyRow1_Screen0E\b/LcdKeyRow1_StepRecord/g
s/\bLcdKeyRow2_Screen0ESub16\b/LcdKeyRow2_StepRecordSub16/g
s/\bLcdKeyRow2_Screen0ESub17\b/LcdKeyRow2_StepRecordSub17/g
s/\bLcdKeyRow2_Screen0ESub18\b/LcdKeyRow2_StepRecordSub18/g
s/\bLcdKeyRow3_Screen0E\b/LcdKeyRow3_StepRecord/g
s/\bLcdKeyRow3_Screen0ESub02\b/LcdKeyRow3_StepRecordSub02/g
s/\bLcdKeyRow3_Screen0ESub05\b/LcdKeyRow3_StepRecordSub05/g
s/\bLcdKeyRow3_Screen0ESub11\b/LcdKeyRow3_StepRecordSub11/g
s/\bLcdKeyRow3_Screen0ESub16\b/LcdKeyRow3_StepRecordSub16/g
s/\bLcdKeyRow3_Screen0ESub18\b/LcdKeyRow3_StepRecordSub18/g
s/\bLcdKeyRow4_Screen0E\b/LcdKeyRow4_StepRecord/g
s/\bLcdKeyRow4_Screen0ESub00\b/LcdKeyRow4_StepRecordSub00/g
s/\bLcdKeyRow4_Screen0ESub02\b/LcdKeyRow4_StepRecordSub02/g
s/\bScreen0ESub00_ButtonDispatch\b/StepRecordSub00_ButtonDispatch/g
s/\bScreen0ESub00_ButtonTable\b/StepRecordSub00_ButtonTable/g
s/\bScreen0ESub00_SoftKeyCol1\b/StepRecordSub00_SoftKeyCol1/g
s/\bScreen0ESub00_SoftKeyCol2\b/StepRecordSub00_SoftKeyCol2/g
s/\bScreen0ESub00_SoftKeyCol3\b/StepRecordSub00_SoftKeyCol3/g
s/\bScreen0ESub01_ButtonDispatch\b/StepRecordSub01_ButtonDispatch/g
s/\bScreen0ESub01_ButtonTable\b/StepRecordSub01_ButtonTable/g
s/\bScreen0ESub02_ButtonDispatch\b/StepRecordSub02_ButtonDispatch/g
s/\bScreen0ESub02_ButtonTable\b/StepRecordSub02_ButtonTable/g
s/\bScreen0ESub03_ButtonDispatch\b/StepRecordSub03_ButtonDispatch/g
s/\bScreen0ESub03_ButtonTable\b/StepRecordSub03_ButtonTable/g
s/\bScreen0ESub03_SoftKeyCol5\b/StepRecordSub03_SoftKeyCol5/g
s/\bScreen0ESub04_ButtonDispatch\b/StepRecordSub04_ButtonDispatch/g
s/\bScreen0ESub04_ButtonTable\b/StepRecordSub04_ButtonTable/g
s/\bScreen0ESub05_ButtonDispatch\b/StepRecordSub05_ButtonDispatch/g
s/\bScreen0ESub05_ButtonTable\b/StepRecordSub05_ButtonTable/g
s/\bScreen0ESub07_ButtonDispatch\b/StepRecordSub07_ButtonDispatch/g
s/\bScreen0ESub07_ButtonTable\b/StepRecordSub07_ButtonTable/g
s/\bScreen0ESub08_ButtonDispatch\b/StepRecordSub08_ButtonDispatch/g
s/\bScreen0ESub08_ButtonTable\b/StepRecordSub08_ButtonTable/g
s/\bScreen0ESub09_ButtonDispatch\b/StepRecordSub09_ButtonDispatch/g
s/\bScreen0ESub09_ButtonTable\b/StepRecordSub09_ButtonTable/g
s/\bScreen0ESub10_ButtonDispatch\b/StepRecordSub10_ButtonDispatch/g
s/\bScreen0ESub10_ButtonTable\b/StepRecordSub10_ButtonTable/g
s/\bScreen0ESub11_ButtonDispatch\b/StepRecordSub11_ButtonDispatch/g
s/\bScreen0ESub11_ButtonTable\b/StepRecordSub11_ButtonTable/g
s/\bScreen0ESub16_ButtonDispatch\b/StepRecordSub16_ButtonDispatch/g
s/\bScreen0ESub16_ButtonTable\b/StepRecordSub16_ButtonTable/g
s/\bScreen0ESub16_SoftKeyCol1\b/StepRecordSub16_SoftKeyCol1/g
s/\bScreen0ESub17_ButtonDispatch\b/StepRecordSub17_ButtonDispatch/g
s/\bScreen0ESub17_ButtonTable\b/StepRecordSub17_ButtonTable/g
s/\bScreen0ESub17_SoftKeyCol6\b/StepRecordSub17_SoftKeyCol6/g
s/\bScreen0ESub17_SoftKeyCol7\b/StepRecordSub17_SoftKeyCol7/g
s/\bScreen0ESub18_ButtonDispatch\b/StepRecordSub18_ButtonDispatch/g
s/\bScreen0ESub18_ButtonTable\b/StepRecordSub18_ButtonTable/g
s/\bScreen0ESub18_LcdKeyRow2\b/StepRecordSub18_LcdKeyRow2/g
s/\bScreen0ESub18_LcdKeyRow3\b/StepRecordSub18_LcdKeyRow3/g
s/\bScreen0E_LcdKeyRow4\b/StepRecord_LcdKeyRow4/g
s/\bScreen0E_SoftKeyCol3\b/StepRecord_SoftKeyCol3/g
s/\bScreen0E_SoftKeyCol4\b/StepRecord_SoftKeyCol4/g
s/\bSoftKeyCol1_Screen0ESub00\b/SoftKeyCol1_StepRecordSub00/g
s/\bSoftKeyCol1_Screen0ESub16\b/SoftKeyCol1_StepRecordSub16/g
s/\bSoftKeyCol2_Screen0ESub00\b/SoftKeyCol2_StepRecordSub00/g
s/\bSoftKeyCol2_Screen0ESub11\b/SoftKeyCol2_StepRecordSub11/g
s/\bSoftKeyCol3_Screen0ESub00\b/SoftKeyCol3_StepRecordSub00/g
s/\bSoftKeyCol3_Screen0ESub05\b/SoftKeyCol3_StepRecordSub05/g
s/\bSoftKeyCol3_Screen0ESub08\b/SoftKeyCol3_StepRecordSub08/g
s/\bSoftKeyCol4_Screen0E\b/SoftKeyCol4_StepRecord/g
s/\bSoftKeyCol4_Screen0ESub00\b/SoftKeyCol4_StepRecordSub00/g
s/\bSoftKeyCol4_Screen0ESub11\b/SoftKeyCol4_StepRecordSub11/g
s/\bSoftKeyCol5_Screen0ESub00\b/SoftKeyCol5_StepRecordSub00/g
s/\bSoftKeyCol5_Screen0ESub03\b/SoftKeyCol5_StepRecordSub03/g
s/\bSoftKeyCol5_Screen0ESub09\b/SoftKeyCol5_StepRecordSub09/g
s/\bSoftKeyCol5_Screen0ESub10\b/SoftKeyCol5_StepRecordSub10/g
s/\bSoftKeyCol6_Screen0ESub00\b/SoftKeyCol6_StepRecordSub00/g
s/\bSoftKeyCol6_Screen0ESub17\b/SoftKeyCol6_StepRecordSub17/g
s/\bSoftKeyCol7_Screen0E\b/SoftKeyCol7_StepRecord/g
s/\bSoftKeyCol7_Screen0ESub17\b/SoftKeyCol7_StepRecordSub17/g
s/\bSoftKeyCol8_Screen0E\b/SoftKeyCol8_StepRecord/g
