# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FD6EC4\b/SoundEditFilter_LcdKeyRow4/g
s/\bsub_FD7CB5\b/SoundEditMenu_LcdKeyRow5/g
s/\bsub_FD7E1A\b/SoundEditLfo_SoftKeyCol2/g
s/\bsub_FD7E66\b/SoundEditLfo_SoftKeyCol3/g
s/\bsub_FD7ED9\b/SoundEditLfo_SoftKeyCol4/g
s/\bsub_FD7F4C\b/SoundEditLfo_SoftKeyCol5/g
s/\bsub_FD7FBF\b/SoundEditLfo_SoftKeyCol6/g
s/\bsub_FD8030\b/SoundEditLfo_SoftKeyCol7/g
s/\bsub_FD80A3\b/SoundEditLfo_SoftKeyCol8/g
s/\bsub_FD8155\b/SoundEditEnvelope1_SoftKeyCol1/g
s/\bsub_FD81C8\b/SoundEditEnvelope1_SoftKeyCol2/g
s/\bsub_FD823B\b/SoundEditEnvelope1_SoftKeyCol3/g
s/\bsub_FD82D8\b/SoundEditEnvelope1_SoftKeyCol4/g
s/\bsub_FD834B\b/SoundEditEnvelope1_SoftKeyCol5/g
s/\bsub_FD83E8\b/SoundEditEnvelope1_SoftKeyCol6/g
s/\bsub_FD845B\b/SoundEditEnvelope1_SoftKeyCol7/g
s/\bsub_FD84F8\b/SoundEditEnvelope2_SoftKeyCol2/g
s/\bsub_FD859B\b/SoundEditEnvelope2_SoftKeyCol3/g
s/\bsub_FD863E\b/SoundEditEnvelope2_SoftKeyCol4/g
s/\bsub_FD86E1\b/SoundEditEnvelope2_SoftKeyCol5/g
s/\bsub_FD8747\b/SoundEditEnvelope2_SoftKeyCol7/g
s/\bsub_FD87A5\b/SoundEditEnvelope2_SoftKeyCol8/g
s/\bsub_FD8803\b/SoundEditController_SoftKeyCol2/g
s/\bsub_FD895A\b/SoundEditController_SoftKeyCol4/g
s/\bsub_FE9CDA\b/EditScreen_SoftKeyCol1/g
s/\bsub_FE9D92\b/EditScreen_SoftKeyCol2/g
s/\bsub_FEA097\b/EditScreen_SoftKeyCol3/g
s/\bsub_FEA14E\b/EditScreen_SoftKeyCol4/g
s/\bsub_FEA1D5\b/NoteEdit_SoftKeyCol5/g
s/\bsub_FEA97F\b/NoteEdit_LcdKeyRow1/g
s/\bsub_FEA9A0\b/NoteEdit_LcdKeyRow2/g
s/\bsub_FEA9E0\b/NoteEdit_LcdKeyRow3/g
s/\bsub_FEAA20\b/EditScreen_LcdKeyRow4/g
s/\bsub_FEAE9B\b/DrumEdit_LcdKeyRow3/g
s/\bsub_FEAF29\b/DrumEdit_LcdKeyRow2/g
s/\bsub_FEAFD0\b/DrumEdit_LcdKeyRow1/g
s/\bsub_FEAFFE\b/DrumEdit_SoftKeyCol8/g
s/\bsub_FF5A2D\b/DiskSaveFile_Page1_LcdKeyRow1/g
s/\bsub_FF6388\b/MidiFile_LcdKeyRow4/g
s/\bsub_FF63C8\b/MidiFile_LcdKeyRow5/g
s/\bsub_FF7564\b/DiskL0adFile_LcdKeyRow1/g
s/\bsub_FF78C9\b/DiskSaveFile_Page3_LcdKeyRow1/g
s/\bsub_FF79B1\b/DiskSaveFile_Page4_LcdKeyRow1/g
