# v7: cases of switches on CURRENT_TITLE named by their title (gen_title_switch_case_names.py)
s/\bAppEvent_InlineHandler_Switch2_Case156\b/AppEvent_InlineHandler_Switch2_OnTitleSqqtz/g
s/\bAppEvent_InlineHandler_Switch2_Case157\b/AppEvent_InlineHandler_Switch2_OnTitleSqtrns/g
s/\bAppEvent_InlineHandler_Switch2_Case158\b/AppEvent_InlineHandler_Switch2_OnTitleSqvelocng/g
s/\bAppEvent_InlineHandler_Switch2_Case161\b/AppEvent_InlineHandler_Switch2_OnTitleSqmers/g
s/\bAppEvent_InlineHandler_Switch2_Case163\b/AppEvent_InlineHandler_Switch2_OnTitleSqmdel/g
s/\bAppEvent_InlineHandler_Switch3_Case156\b/AppEvent_InlineHandler_Switch3_OnTitleSqqtz/g
s/\bAppEvent_InlineHandler_Switch3_Case157\b/AppEvent_InlineHandler_Switch3_OnTitleSqtrns/g
s/\bAppEvent_InlineHandler_Switch3_Case158\b/AppEvent_InlineHandler_Switch3_OnTitleSqvelocng/g
s/\bAppEvent_InlineHandler_Switch3_Case161\b/AppEvent_InlineHandler_Switch3_OnTitleSqmers/g
s/\bAppEvent_InlineHandler_Switch3_Case163\b/AppEvent_InlineHandler_Switch3_OnTitleSqmdel/g
s/\bAppEvtHandler_Branch_006_Case156\b/AppEvtHandler_Branch_006_OnTitleSqqtz/g
s/\bAppEvtHandler_Branch_006_Case157\b/AppEvtHandler_Branch_006_OnTitleSqtrns/g
s/\bAppEvtHandler_Branch_006_Case158\b/AppEvtHandler_Branch_006_OnTitleSqvelocng/g
s/\bAppEvtHandler_Branch_006_Case161\b/AppEvtHandler_Branch_006_OnTitleSqmers/g
s/\bAppEvtHandler_Branch_006_Case163\b/AppEvtHandler_Branch_006_OnTitleSqmdel/g
s/\bSqTrSel_CaseG_Case112\b/SqTrSel_CaseG_OnTitleDpdoc/g
s/\bSqTrSel_CaseG_Case113\b/SqTrSel_CaseG_OnTitleDppd/g
