# rename_accomp_wrappers_v10.sed -- generated by scripts/renaming/lane_accomp_name_wrappers.py
# image v10, sequencer/accompaniment_engine.s.  One rule per XIZ-preserving wrapper; the body each
# rule was matched on is the comment above it.
# push xiz / ld xiy, xwa / call Rhythm_UpdateTuningConfig / pop xiz / ret
s/\bAccTone_InlineBytecodeData_Code_Helper4\b/Rhythm_UpdateTuningConfig_Wrap/g
# push xiz / ld w, a / call AccPatch_SetByChordIndex / pop xiz / ret
s/\bAccTone_InlineBytecodeData_Code_Helper5\b/AccPatch_SetByChordIndex_Wrap/g
# push xiz / ld xiy, xwa / call AccTuning_CopyAllPartsFromStyle / pop xiz / ret
s/\bAccTone_InlineBytecodeData_Code_Helper6\b/AccTuning_CopyAllPartsFromStyle_Wrap/g
# push xiz / ld xiy, xwa / ld xhl, xbc / and xhl, 0xffff / call AccVoice_LoadTuningBlock / pop xiz / ret
s/\bAccVoice_BarCounterBytecodeData_Helper4\b/AccVoice_LoadTuningBlock_Wrap/g
# push xiz / and xwa, 255 / call AccVoice_ComputeParamAddr / and xhl, 0xffff / pop xiz / ret
s/\bAccVoice_BarCounterBytecodeData_Helper5\b/AccVoice_ComputeParamAddr_Wrap/g
# push xiz / ld xiy, xwa / call AccPart_InitPositionsAndBase / pop xiz / ret
s/\bAccTone_InlineBytecodeData_Code_Helper3_Helper4\b/AccPart_InitPositionsAndBase_Wrap/g
# push xiz / ld xiy, xwa / call AccInit_AllPartPositions / pop xiz / ret
s/\bAccVoice_BarCounterBytecodeData_Helper6\b/AccInit_AllPartPositions_Wrap/g
# push xiz / ld xiy, xwa / ld xhl, xbc / and xhl, 0xffff / call AccStyle_SetupPartAddressesByHL / pop xiz / ret
s/\bAccTone_InlineBytecodeData_Code_Helper3_Helper5\b/AccStyle_SetupPartAddressesByHL_Wrap/g
# push xiz / ld xiy, xwa / ld xhl, xbc / and xhl, 0xffff / call AccVoice_LoadAllParts / pop xiz / ret
s/\bAccVoice_BarCounterBytecodeData_Helper7\b/AccVoice_LoadAllParts_Wrap/g
# push xiz / call Rhythm_SendChanPressure / pop xiz / ret
s/\bAccTone_InlineBytecodeData_Code_Helper7\b/Rhythm_SendChanPressure_Wrap/g
# push xiz / call AccBuf_ResetAll4 / pop xiz / ret
s/\bAccTone_InlineBytecodeData_Code_Helper8\b/AccBuf_ResetAll4_Wrap/g
# push xiz / call AccSeq_DualPartScan / pop xiz / ret
s/\bAccTone_InlineBytecodeData_Code_Helper9\b/AccSeq_DualPartScan_Wrap/g
# push xiz / call AccSeq_FourChannelScan / pop xiz / ret
s/\bAccTone_InlineBytecodeData_Code_Helper10\b/AccSeq_FourChannelScan_Wrap/g
# push xiz / call AccPedal_DirectionA / and xhl, 0xffff / pop xiz / ret
s/\bAccTuning_ComplexBytecodeData_Code_Helper2\b/AccPedal_DirectionA_Wrap/g
