# rename_idproc_v9.sed -- written by scripts/renaming/gen_idproc_names.py
s/\bFrameVariant_B_CalcHeight\b/ColorIDProc_OnSetPropertyEx/g
s/\bFrameVariant_C_CalcHeight\b/BorderIDProc_OnSetPropertyEx/g
s/\bFrameVariant_D_CalcHeight\b/AlignmentIDProc_OnSetPropertyEx/g
s/\bFrameVariant_E_CalcHeight\b/EditSwStyleIDProc_OnSetPropertyEx/g
s/\bFrameVariant_F_CalcHeight\b/EditSwIDProc_OnSetPropertyEx/g
s/\bFrameVariant_G_CalcHeight\b/LineModeIDProc_OnSetPropertyEx/g
s/\bFrameVariant_H_CalcHeight\b/FrameIDProc_OnSetPropertyEx/g
s/\bFrameVariant_I_CalcHeight\b/UserIDProc_OnSetPropertyEx/g
s/\bFrameVariant_J_CalcHeight\b/PartIDProc_OnSetPropertyEx/g
s/\bFrameVariant_K_CalcHeight\b/TrackIDProc_OnSetPropertyEx/g
s/\bFrameVariant_L_CalcHeight\b/IntTimeIDProc_OnSetPropertyEx/g
s/\bFrameVariant_B_CalcWidth\b/ColorIDProc_ForwardToCommon/g
s/\bFrameVariant_C_CalcWidth\b/BorderIDProc_ForwardToCommon/g
s/\bFrameVariant_D_CalcWidth\b/AlignmentIDProc_ForwardToCommon/g
s/\bFrameVariant_E_CalcWidth\b/EditSwStyleIDProc_ForwardToCommon/g
s/\bFrameVariant_F_CalcWidth\b/EditSwIDProc_ForwardToCommon/g
s/\bFrameVariant_G_CalcWidth\b/LineModeIDProc_ForwardToCommon/g
s/\bFrameVariant_H_CalcWidth\b/FrameIDProc_ForwardToCommon/g
s/\bFrameVariant_I_CalcWidth\b/UserIDProc_ForwardToCommon/g
s/\bFrameVariant_J_CalcWidth\b/PartIDProc_ForwardToCommon/g
s/\bFrameVariant_K_CalcWidth\b/TrackIDProc_ForwardToCommon/g
s/\bFrameVariant_L_CalcWidth\b/IntTimeIDProc_ForwardToCommon/g
s/\bFrameVariant_F_CheckAlt\b/EditSwIDProc_OnMakeEditSwId/g
s/\bFrameVariant_F_DoneAlt2\b/EditSwIDProc_Join3/g
s/\bFrameVariant_B_Execute\b/ColorIDProc_ReturnResult/g
s/\bFrameVariant_C_Execute\b/BorderIDProc_ReturnResult/g
s/\bFrameVariant_D_Execute\b/AlignmentIDProc_ReturnResult/g
s/\bFrameVariant_E_Execute\b/EditSwStyleIDProc_ReturnResult/g
s/\bFrameVariant_F_Execute\b/EditSwIDProc_ReturnResult/g
s/\bFrameVariant_F_DrawAlt\b/EditSwIDProc_Skip/g
s/\bFrameVariant_F_DoneAlt\b/EditSwIDProc_Join2/g
s/\bFrameVariant_G_Execute\b/LineModeIDProc_ReturnResult/g
s/\bFrameVariant_H_Execute\b/FrameIDProc_ReturnResult/g
s/\bFrameVariant_I_Execute\b/UserIDProc_ReturnResult/g
s/\bFrameVariant_J_Execute\b/PartIDProc_ReturnResult/g
s/\bFrameVariant_K_Execute\b/TrackIDProc_ReturnResult/g
s/\bFrameVariant_L_Execute\b/IntTimeIDProc_ReturnResult/g
s/\bFrameVariant_F_Return\b/EditSwIDProc_Epilogue/g
s/\bFrameVariant_B_Setup\b/ColorIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_C_Setup\b/BorderIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_D_Setup\b/AlignmentIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_E_Setup\b/EditSwStyleIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_F_Setup\b/EditSwIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_G_Setup\b/LineModeIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_H_Setup\b/FrameIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_I_Setup\b/UserIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_J_Setup\b/PartIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_K_Setup\b/TrackIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_L_Setup\b/IntTimeIDProc_OnGetOrDumpPropertyEx/g
s/\bFrameVariant_B_Done\b/ColorIDProc_Epilogue/g
s/\bFrameVariant_C_Done\b/BorderIDProc_Epilogue/g
s/\bFrameVariant_D_Done\b/AlignmentIDProc_Epilogue/g
s/\bFrameVariant_E_Done\b/EditSwStyleIDProc_Epilogue/g
s/\bFrameVariant_F_Done\b/EditSwIDProc_Join/g
s/\bFrameVariant_G_Done\b/LineModeIDProc_Epilogue/g
s/\bFrameVariant_H_Done\b/FrameIDProc_Epilogue/g
s/\bFrameVariant_I_Done\b/UserIDProc_Epilogue/g
s/\bFrameVariant_J_Done\b/PartIDProc_Epilogue/g
s/\bFrameVariant_K_Done\b/TrackIDProc_Epilogue/g
s/\bFrameVariant_L_Done\b/IntTimeIDProc_Epilogue/g
