# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bsub_FE1C23\b/Playback_StopAllAndIgnoreMidiStart/g
s/\bsub_FE8BD4\b/EditScreen_FlagMemoryFull/g
s/\bsub_FE2F86\b/DiskProgress_PrintDot/g
s/\bsub_FE1CD8\b/DiskProgress_PrintDotForSmf/g
s/\bsub_F918E5\b/C0mbinati0nM0de_ShowSelectedPartSoundName/g
s/\bsub_FD7159\b/SoundEditController_SaveField0/g
s/\bsub_FD6FC9\b/SoundEditLfo_GetSelectedLfo/g
s/\bsub_FD6F22\b/SoundEditLfo_GetLfoFieldBase/g
s/\bsub_FD8993\b/SoundEditController_SoftKeyCols5to8/g
s/\bsub_FD8DAF\b/SoundEditEnvelope1_DrawGraph/g
s/\bsub_FAB658\b/SoundSel_ClampToProgramAndBank/g
s/\bsub_FAB779\b/CombiSel_ClampToNumberAndBank/g
s/\bsub_FB4D20\b/SysExParamDesc_FindForEvent/g
s/\bsub_FDA002\b/ModelingPage_GroupStartIndex/g
s/\bsub_FDA05E\b/ModelingPage_GetItemGroup/g
s/\bsub_FD9D16\b/ModelingPage_GetItemIndex/g
s/\bsub_FE1C0B\b/Disk_MountAndScanMidiFilesResetRings/g
s/\bsub_FE93CA\b/EditScreen_ExtendChainToCursorMeasure/g
s/\bsub_FF5118\b/MidiFile_DrawFileList/g
s/\bsub_FF7959\b/SC1_CmdEFAndClearHeldButtons/g
s/\bsub_FAAAB5\b/ParamImage_PostAllAsChangeEvents/g
s/\bsub_FAE84D\b/SeqBuf_RecordQueuedEvents/g
s/\bsub_FB7BB9\b/SysExSession_RefreshProgressScreen/g
s/\bsub_FBCCB1\b/CombiEdit_TakePartIndex/g
s/\bsub_FD65D3\b/ToneMsg88_Id16/g
s/\bsub_FD77B3\b/SoundEditText_SetSlot/g
s/\bsub_FD8116\b/SoundEditEnvelope1_SetField0AndRedraw/g
s/\bsub_FD9A7A\b/FilterPage_DrawEqualizerGraph/g
s/\bsub_FF4936\b/DiskEntry_GetContentType/g
