# WSA1 naming step (session 53b889a2, wsa1_rename.py)
s/\bT_F409D8\b/T_SeqRecord_EndTake/g
s/\bT_F40A2C\b/T_BStore_LoadGmTrackDefaults/g
s/\bT_F40A30\b/T_BStore_LoadNonGmTrackDefaults/g
s/\bT_F40A3C\b/T_SeqCycle_TickDeferredAction/g
s/\bT_F40A54\b/T_UiScreenFlags_SetRepaintInPlace/g
s/\bT_F40A70\b/T_SeqMasterTrack_UpdateActiveFromSavedMask/g
s/\bT_F40AA0\b/T_SeqTrack_QueueSwitchOffEvents/g
s/\bT_F40AB4\b/T_SeqScreen_RepaintIfPlayOrRecord/g
s/\bT_F40B4C\b/T_BStore_DirEntryHeadAtIY/g
s/\bT_F40B54\b/T_SeqTrackCursors_SaveTrack/g
s/\bT_F40B64\b/T_SeqTrackCursors_RestoreSaved/g
s/\bT_F40B68\b/T_SeqTrackCursors_Save/g
s/\bT_F40BD0\b/T_SeqRecord_DrainEventRing/g
s/\bT_F40BE4\b/T_CycleRecord_CheckIsRecordTrack/g
s/\bT_F40BF4\b/T_CycleRecord_FreeRecordChain/g
s/\bT_F40BF8\b/T_SeqRecord_FreeTakeChain2/g
s/\bT_F40C00\b/T_CycleRecord_RestartPass/g
s/\bT_F40C04\b/T_SeqRecord_RestoreCursorBaseline/g
s/\bT_F40C50\b/T_BStore_StepCursorOneByte/g
s/\bT_F40C60\b/T_Seq_BeatsToMeasureAndBeat/g
s/\bT_F40C70\b/T_BStore_ClearSongStore/g
s/\bT_F40C7C\b/T_TimedEventRing_ReadNext_Veneer/g
s/\bT_F40C80\b/T_TimedEventRing_SkipByte_Veneer/g
s/\bT_F40C88\b/T_BStore_AllocBlock_B_Veneer/g
s/\bT_F40C90\b/T_BStore_SeekChainToBeat/g
s/\bT_F40C98\b/T_BStore_SkipBeatMarks/g
s/\bT_F40CBC\b/T_Seq_RequestRewindOnEvent/g
s/\bT_F40CE8\b/T_RealtimeRecord_Arm/g
s/\bT_F40CF0\b/T_RealtimeRecord_InitOnModeEnter/g
s/\bT_F40D04\b/T_SeqPlayScreen_EnsureMeasureNonZero/g
s/\bT_F40D14\b/T_Seq_DelayedLocateToMeasure_Call/g
s/\bT_F40D64\b/T_SeqTrack_PlayOffWhileStopped/g
s/\bT_F40D6C\b/T_SeqTrack_SwitchPlayOffWhileRunning/g
s/\bT_F41264\b/T_SysExThirdRegion_SendReplyChunk/g
s/\bT_F414B0\b/T_BStore_CompactBlocks_Veneer/g
s/\bT_F414B4\b/T_BStore_RebuildFreeListAfterLoad_Veneer/g
s/\bT_F414BC\b/T_SysExDump_PrepareSequencerData/g
s/\bT_F414C0\b/T_SeqFile_RestoreSavedCurrentBank/g
s/\bT_F414C4\b/T_SeqFile_PrepareSaveAllBanks/g
s/\bT_F426EC\b/T_SongEdit_DeleteMeasures/g
s/\bT_F426F0\b/T_MeasureErase_Execute/g
s/\bT_F426F4\b/T_MeasureInsert_Execute/g
s/\bT_F426F8\b/T_SongEdit_CopyMeasures/g
s/\bT_F42700\b/T_Quantize_Execute/g
s/\bT_F427A4\b/T_BStore_TimeSigFirstMeasure/g
s/\bT_F427EC\b/T_BStore_CopyRangeBackward_Call/g
s/\bT_F43488\b/T_ToneMsg88_Id13/g
