# v9 labels renamed to v10's name for the same unmoved bytes (scripts/renaming/sync_names_from_v10.py)
s/\bScoopDisp_DispatchTable_Small_Target11_Helper2\b/UIState_EventTable_Target11_Helper2/g	# 0xEFF483
s/\bScoopDisp_DispatchTable_Small_Target11_Return\b/UIState_EventTable_Target11_Return/g	# 0xEF7796
s/\bScoopDisp_DispatchTable_Small_Target11_Helper\b/UIState_EventTable_Target11_Helper/g	# 0xEFA4EC
s/\bExtData_ToneParam_DispatchHandler_Loop_Helper\b/ExtData_Voice_CheckMode3_Helper_Helper/g	# 0xFC98D8
s/\bExtDev_SndParam_BlockA9_Var02_Code_Epilogue5\b/NakaData_WidgetInit1_Code_Epilogue5/g	# 0xFC670C
s/\bExtDev_SndParam_BlockA9_Var02_Code_Epilogue2\b/NakaData_WidgetInit1_Code_Epilogue2/g	# 0xFC6769
s/\bExtDev_SndParam_BlockA9_Var02_Code_Epilogue3\b/NakaData_WidgetInit1_Code_Epilogue3/g	# 0xFC6813
s/\bExtDev_SndParam_BlockA9_Var02_Code_Epilogue4\b/NakaData_WidgetInit1_Code_Epilogue4/g	# 0xFC686C
s/\bExtDev_SndParam_BlockA9_Var02_Code_Epilogue6\b/NakaData_WidgetInit1_Code_Epilogue6/g	# 0xFC68F2
s/\bExtData_ToneParam_DispatchHandler_Loop_Skip2\b/ExtData_Voice_CheckMode3_Helper_Skip2/g	# 0xFC8682
s/\bExtData_ToneParam_DispatchHandler_Loop_Skip3\b/ExtData_Voice_CheckMode3_Helper_Skip3/g	# 0xFC8693
s/\bExtData_ToneParam_DispatchHandler_Loop_Join2\b/ExtData_Voice_CheckMode3_Helper_Join2/g	# 0xFC86F8
s/\bExtData_ToneParam_DispatchHandler_Loop_Join3\b/ExtData_Voice_CheckMode3_Helper_Join3/g	# 0xFC8707
s/\bExtData_ToneParam_DispatchHandler_Loop_Join4\b/ExtData_Voice_CheckMode3_Helper_Join4/g	# 0xFC8710
s/\bExtData_ToneParam_DispatchHandler_Loop_Join5\b/ExtData_Voice_CheckMode3_Helper_Join5/g	# 0xFC8719
s/\bExtData_ToneParam_DispatchHandler_Loop_Join6\b/ExtData_Voice_CheckMode3_Helper_Join6/g	# 0xFC8722
s/\bExtData_ToneParam_DispatchHandler_Loop_Join7\b/ExtData_Voice_CheckMode3_Helper_Join7/g	# 0xFC872B
s/\bExtDev_SndParam_BlockA9_Var02_Code_Epilogue\b/FileIO_BytecodeData_Code_Epilogue36/g	# 0xFC693B
s/\bExtData_ToneParam_DispatchHandler_Loop_Skip\b/ExtData_Voice_CheckMode3_Helper_Skip/g	# 0xFC8675
s/\bExtData_ToneParam_DispatchHandler_Loop_Join\b/ExtData_Voice_CheckMode3_Helper_Join/g	# 0xFC8696
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip10\b/NakaData_WidgetInit1_Code_Skip5/g	# 0xFC66B8
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip11\b/NakaData_WidgetInit1_Code_Skip6/g	# 0xFC6700
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip12\b/NakaData_WidgetInit1_Code_Skip7/g	# 0xFC68B7
s/\bParam_SignExtendReturn_Entry_Code_Helper2\b/Param_SignExtendReturn_Helper3_Helper2/g	# 0xFD7306
s/\bExtDev_SndParam_BlockA9_Var02_Code_Join6\b/NakaData_WidgetInit1_Code_Join4/g	# 0xFC66BB
s/\bExtDev_SndParam_BlockA9_Var02_Code_Join2\b/FileIO_BytecodeData_Code_Join24/g	# 0xFC6703
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip7\b/NakaData_WidgetInit1_Code_Skip2/g	# 0xFC675E
s/\bExtDev_SndParam_BlockA9_Var02_Code_Join5\b/NakaData_WidgetInit1_Code_Join3/g	# 0xFC6761
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip2\b/FileIO_BytecodeData_Code_Skip80/g	# 0xFC678E
s/\bExtDev_SndParam_BlockA9_Var02_Code_Join3\b/FileIO_BytecodeData_Code_Join25/g	# 0xFC6791
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip3\b/FileIO_BytecodeData_Code_Skip81/g	# 0xFC67B3
s/\bExtDev_SndParam_BlockA9_Var02_Code_Join4\b/FileIO_BytecodeData_Code_Join26/g	# 0xFC67B6
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip4\b/FileIO_BytecodeData_Code_Skip82/g	# 0xFC67E0
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip8\b/NakaData_WidgetInit1_Code_Skip3/g	# 0xFC67E2
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip5\b/FileIO_BytecodeData_Code_Skip83/g	# 0xFC6839
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip9\b/NakaData_WidgetInit1_Code_Skip4/g	# 0xFC683B
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip6\b/FileIO_BytecodeData_Code_Skip84/g	# 0xFC68B5
s/\bParam_SignExtendReturn_Entry_Code_Helper\b/Param_SignExtendReturn_Helper3_Helper/g	# 0xFD72E7
s/\bSeqData_FormatOutput_Default_Helper_Join\b/Param_SignExtendReturn_Join5/g	# 0xFEF23B
s/\bExtDev_SndParam_BlockA9_Var02_Code_Skip\b/FileIO_BytecodeData_Code_Skip79/g	# 0xFC6693
s/\bExtDev_SndParam_BlockA9_Var02_Code_Join\b/FileIO_BytecodeData_Code_Join23/g	# 0xFC6696
s/\bScoopDisp_DispatchTable_Small_Target11\b/UIState_EventTable_Target11/g	# 0xEF7779
s/\bExtData_ToneParam_DispatchHandler_Loop\b/ExtData_Voice_CheckMode3_Helper/g	# 0xFC8628
s/\bMidiPartCC_WriteAndDispatch_Return2\b/MidiVoice_DataBlockHandler_Return2/g	# 0xFCB325
s/\bMidiPartCC_WriteAndDispatch_Return3\b/MidiVoice_DataBlockHandler_Return3/g	# 0xFCB368
s/\bMidiPartCC_WriteAndDispatch_Return\b/MidiVoice_DataBlockHandler_Return/g	# 0xFCB2D5
s/\bMidiPartCC_WriteAndDispatch_Skip3\b/MidiVoice_DataBlockHandler_Skip2/g	# 0xFCB2FD
s/\bMidiPartCC_WriteAndDispatch_Skip4\b/MidiVoice_DataBlockHandler_Skip3/g	# 0xFCB340
s/\bColorBlit_Variant_ByteData_Skip2\b/ColorBlit_WithPaletteSave_Skip2/g	# 0xFB25C1
s/\bVoiceMode_ParamHandler_3_Return2\b/VoiceMode3_DispatchTable_Code_Return2/g	# 0xFCB18A
s/\bColorBlit_Variant_ByteData_Skip\b/ColorBlit_WithPaletteSave_Skip/g	# 0xFB2556
s/\bVoiceMode_ParamHandler_3_Return\b/VoiceMode3_DispatchTable_Code_Return/g	# 0xFCB0F1
s/\bVoiceMode_ParamHandler_3_Skip2\b/VoiceMode3_DispatchTable_Code_Skip4/g	# 0xFCB149
s/\bVoiceMode_ParamHandler_3_Skip\b/VoiceMode3_DispatchTable_Code_Skip/g	# 0xFCB08F
s/\bParam_SignExtendReturn_Entry2\b/Param_SignExtendReturn_Skip22/g	# 0xFEF246
s/\bVoiceMode3_EvType0_Skip2\b/VoiceMode3_DispatchTable_Code_Skip3/g	# 0xFCB0B0
s/\bVoiceMode3_EvType0_Skip\b/VoiceMode3_DispatchTable_Code_Skip2/g	# 0xFCB09D
s/\bSeScreenData_0x0562\b/SeMenu_WaveformSelect_Apply_Data/g	# 0xF11168
s/\bSeScreenData_0x0E0E\b/SeMenu_PresetBrowser_Navigate_Data/g	# 0xF11A14
s/\bSeScreenData_0x0E31\b/SeMenu_PresetBrowser_Init_Data/g	# 0xF11A37
s/\bSeScreenData_0x1140\b/SeMenu_ShowConfirmDialog_Sub_Data/g	# 0xF11D46
s/\bSeScreenData_0x1780\b/SeMenu_Utility_CompareBlock_Data/g	# 0xF12386
s/\bSeScreenData_0x34F3\b/SeMenu_FxEdit_Init_Data/g	# 0xF140F9
s/\bSeScreenData_0x3C32\b/SeMenu_EqEdit_SetupHelper1_Data/g	# 0xF14838
s/\bSeScreenData_0x3C37\b/SeMenu_FilterEdit_DataBlock5_Data/g	# 0xF1483D
