#!/usr/bin/env python3
r"""Rename three routines of ui/ui_widget_defs.s that carried DATA-shaped names.

QUESTION / JOB
--------------
`PsEditSwBox_InlineData`, `DbMemo_TrailingData` and `PsTrkSw_TrailingData`
label CODE (the last was a verbatim v7 romslice until 2026-09-25).  For each,
this script renames the entry and the structural labels inside it (explicit
lists below, all inside the routine), writes the generated sed record
`scripts/renaming/rename_uiproc_misc_<image>.sed`, inserts a header derived
from the code, and re-links the image (byte-identical required).  It refuses
if any renamed label is used by another file of the image.

Callers: none was found for any of the three -- searched: label uses in all
sources of the image, the entry address as a 32-bit and as a 24-bit
little-endian word anywhere in the v10 ROM, and every numeric
call/calr/jp/jr/jrl in the v10 sources (target computed from the line map).

RUN
    python3 scripts/renaming/uiproc_misc_names.py --image v10 [--apply]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "scripts", "analysis"))
import data_range_census as drc  # noqa: E402
import lane_uiproc_listing as L  # noqa: E402

REL = "ui/ui_widget_defs.s"
ROUTINES = [
    ("PsEditSwBox_InlineData", "PsEditSwBox_CalcEdgeSwitchRect",
     ["PsEditSwBoxProc_Skip", "PsEditSwBoxProc_Skip2", "PsEditSwBoxProc_Skip3",
      "PsEditSwBoxProc_Join", "PsEditSwBoxProc_Epilogue"],
     """\
; -----------------------------------------------------------------------------
; PsEditSwBox_CalcEdgeSwitchRect -- code (was named PsEditSwBox_InlineData)
; WA = edit-switch index, XBC = rect {x0,y0,x1,y1} to fill, DE = value given
; to BoxLeftCheck / BoxRightCheck (ui/ui_control_panel.s: 1 for 0x80-0x88 /
; 0xa0-0xa8).  point = GetEditSwPoint(WA).  A switch on the left edge
; (point.x == 0) gets x0 = 0 if BoxLeftCheck(DE) else 8, x1 = 38; one on the
; right edge (point.x == 319) gets x0 = 281, x1 = 319 if BoxRightCheck(DE)
; else 311; both span y = point.y-9 .. point.y+8.  One on the bottom edge
; (point.y == 239) gets x = point.x-16 .. point.x+15, y = 216 .. 238.
; No caller was found (see scripts/renaming/uiproc_misc_names.py).
; -----------------------------------------------------------------------------"""),
    ("DbMemo_TrailingData", "DbMemo_LoneRet", [],
     """\
; DbMemo_LoneRet -- a single `ret` instruction (was named DbMemo_TrailingData);
; no caller was found (see scripts/renaming/uiproc_misc_names.py)."""),
    ("PsTrkSw_TrailingData", "PsTrackSwitch_SetBoxFromIndex",
     ["PsTrackSwitchProc_Skip", "PsTrackSwitchProc_Join"],
     """\
; -----------------------------------------------------------------------------
; PsTrackSwitch_SetBoxFromIndex -- code (was named PsTrkSw_TrailingData)
; XWA = track-switch widget.  n = word +22 of its view instance
; (GetViewInstance); the widget's box becomes x = (n & 7)*40 + 4 .. +31,
; y = 164 (n < 8) or 196 (n >= 8) .. +28, stored with SetBox: two rows of
; eight switches.  No caller was found (see scripts/renaming/uiproc_misc_names.py).
; -----------------------------------------------------------------------------"""),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=True)
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    img = L.image(a.image)
    srcroot = os.path.join(ROOT, img["mirror"])
    path = os.path.join(srcroot, REL)
    raw = open(path, "rb").read()
    lines = raw.decode("latin-1").split("\n")
    other = []
    for dp, dn, fn in os.walk(srcroot):
        for f in fn:
            p = os.path.join(dp, f)
            if f.endswith(".s") and os.path.relpath(p, srcroot) != REL:
                other.append(open(p, encoding="latin-1").read())
    other = "\n".join(other)
    ren = {}
    for old, new, inner, hdr in ROUTINES:
        for n in [old] + inner:
            if re.search(r'(?<![\w.$])' + re.escape(n) + r'(?![\w.$])', other):
                sys.exit("REFUSED: %s is used by another file" % n)
        ren[old] = new
        for n in inner:
            ren[n] = new + n[n.rindex("_"):]
    for o, n in sorted(ren.items()):
        print("  %-28s -> %s" % (o, n))
    if not a.apply:
        return
    open(os.path.join(ROOT, "scripts", "renaming", "rename_uiproc_misc_%s.sed" % a.image), "w").write(
        "# generated by scripts/renaming/uiproc_misc_names.py --image %s; applied to CODE only\n"
        % a.image + "\n".join("s/\\b%s\\b/%s/g" % (o, n)
                              for o, n in sorted(ren.items(), key=lambda t: -len(t[0]))) + "\n")
    hdrs = {old: hdr for old, new, inner, hdr in ROUTINES}
    out = []
    for l in lines:
        m = re.match(r'^([A-Za-z_]\w*):', l)
        if m and m.group(1) in hdrs:
            out += hdrs[m.group(1)].split("\n")
        code = drc.strip_comment(l)
        com = l[len(code):]
        for o, n in sorted(ren.items(), key=lambda t: -len(t[0])):
            if o in code:
                code = re.sub(r'(?<![\w.$])' + re.escape(o) + r'(?![\w.$])', n, code)
        out.append(code + com)
    open(path, "wb").write("\n".join(out).encode("latin-1"))
    try:
        L.build(img)
    except (SystemExit, RuntimeError):
        open(path, "wb").write(raw)
        raise
    print("APPLIED; image byte-identical")


if __name__ == "__main__":
    main()
