#!/usr/bin/env python3
r"""Retire end-of-routine labels that sit on the NEXT routine's first byte (lane uiproc).

QUESTION / JOB
--------------
CLAUDE.md policy 5: one address, one name.  ui_widget_defs.s and
ui_mode_handlers.s carry ~55 pairs like

    BoxStyle4_Done:
        pop xiz / inc 8,xsp / ret
    BoxStyle4_Return:          <- no byte between these two labels
    ulongProc:
        dec 8, xsp ...

where the first label of the pair is an end-of-routine marker from an older
pass (`*_Return`, `*_Epilogue`, `*_Boundary`, `*_End`, `*_DoneAlt`, ...) and
the second is the routine that actually starts there.  Where code jumps to the
marker, the marker name MISLEADS: `pPropProc: jrl BoxStyle4_Return` is a tail
call of ulongProc, not a return.

For every group of labels with no emitting line between them, in the files
given, this script keeps the LAST label (the one directly above the code),
rewrites every reference to the others -- in the given files only -- to it,
and deletes the other label lines.  A label that any OTHER file of the image
references is kept and reported.  Renames go through a generated sed script
`scripts/renaming/rename_uiproc_aliases_<image>.sed` (CLAUDE.md rename policy).
Groups where one label was kept deliberately for other lanes (the
ui_window_procs.s draw primitives) are skipped because those old names are
referenced from other files.

Byte-safety: every rewrite names a label at the same address, so the image is
unchanged; the script re-links and compares.  A missed reference would fail to
assemble.

RUN
    python3 scripts/renaming/uiproc_alias_cleanup.py --image v10 [--apply]
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "scripts", "analysis"))
import data_range_census as drc  # noqa: E402
import lane_uiproc_listing as L  # noqa: E402

FILES = ["ui/drawbar_panel_ui.s", "ui/ui_widget_defs.s", "ui/ui_mode_handlers.s",
         "ui/ui_window_procs.s"]
LAB = re.compile(r'^([A-Za-z_][\w]*):\s*$')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=True)
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    img = L.image(a.image)
    srcroot = os.path.join(ROOT, img["mirror"])
    texts = {}
    for dp, dn, fn in os.walk(srcroot):
        for f in fn:
            if f.endswith(".s"):
                p = os.path.join(dp, f)
                texts[os.path.relpath(p, srcroot)] = open(p, "rb").read().decode("latin-1")

    def refcount(name, rels):
        n = 0
        for r in rels:
            t = texts[r]
            if name in t:
                n += len(re.findall(r'(?<![\w.$])' + re.escape(name) + r'(?![\w.$])',
                                    "\n".join(drc.strip_comment(x) for x in t.split("\n"))))
        return n
    others = [r for r in texts if r not in FILES]
    renames, deletes, kept = {}, {}, []
    for rel in FILES:
        lines = texts[rel].split("\n")
        group = []
        for i, l in enumerate(lines + ["\tnop"]):
            c = drc.strip_comment(l).strip()
            m = LAB.match(c)
            if m:
                group.append((i, m.group(1)))
                continue
            if not c:
                continue
            if len(group) > 1:
                canon = group[-1][1]
                for li, n in group[:-1]:
                    if refcount(n, others):
                        kept.append((rel, n, canon, "referenced by another file"))
                        continue
                    renames[n] = canon
                    deletes.setdefault(rel, set()).add(li)
            group = []
    sed = ["# generated by scripts/renaming/uiproc_alias_cleanup.py --image %s; applied to CODE only (comments that mention an old name were left verbatim)" % a.image]
    for old, new in sorted(renames.items(), key=lambda t: -len(t[0])):
        sed.append("s/\\b%s\\b/%s/g" % (old, new))
    for old, new in sorted(renames.items()):
        n = refcount(old, FILES) - 1
        print("  %-40s -> %-32s (%d reference%s rewritten)" % (old, new, n, "" if n == 1 else "s"))
    for k in kept:
        print("  KEPT %s %s (canonical %s): %s" % k)
    print("%s: %d alias labels retired" % (a.image, len(renames)))
    if not a.apply:
        return
    sedpath = os.path.join(ROOT, "scripts", "renaming", "rename_uiproc_aliases_%s.sed" % a.image)
    open(sedpath, "w").write("\n".join(sed) + "\n")
    raws = {}
    for rel in FILES:
        path = os.path.join(srcroot, rel)
        raws[rel] = open(path, "rb").read()
        lines = raws[rel].decode("latin-1").split("\n")
        out = []
        for i, l in enumerate(lines):
            if i in deletes.get(rel, ()):
                continue
            code = drc.strip_comment(l)
            com = l[len(code):]
            for old, new in renames.items():
                if old in code:
                    code = re.sub(r'(?<![\w.$])' + re.escape(old) + r'(?![\w.$])', new, code)
            out.append(code + com)
        open(path, "wb").write("\n".join(out).encode("latin-1"))
    try:
        L.build(img)
    except (SystemExit, RuntimeError):
        for rel, raw in raws.items():
            open(os.path.join(srcroot, rel), "wb").write(raw)
        raise
    print("APPLIED; image byte-identical; wrote %s" % os.path.relpath(sedpath, ROOT))


if __name__ == "__main__":
    main()
