; ==============================================================================
; Technics SX-WSA1R -- prom_c (CPU 2, IC28) -- 0xFCC53F-0xFCD0F6  touch / EQ / mixer-gain / descriptor-string zone
; ==============================================================================
;
; 682 lines moved out of prom_c/wsa1_prom_c.s by notes/prom_c_split.py.  The master
; `.include`s this file at the line the block started on, so the assembler
; sees the same token stream in the same order and the ROM is unchanged:
;
;     python3 scripts/analysis/assert_byte_identical.py    <- the bytes
;     python3 notes/prom_c_split.py --verify               <- the text
;
; ★ EVERY LINE BELOW THIS HEADER IS VERBATIM.  Nothing was reworded, and
;   --verify fails on a single changed character.
;
; WHY THIS IS ONE SUBJECT:
; Banner-declared: 15 data objects, including the four ToneGen_ velocity
; curves and the 616-byte floating-point constant pool at 0xFCC81A.
;
; >>> END OF EXTRACTION HEADER -- everything below is verbatim from the master

; ============================================================================
; 0xFCC53F-0xFCD0F6 -- touch / EQ / mixer-gain / descriptor-string zone
; ============================================================================
;
; Generated by notes/gen_prom_c_tables.py (SPEC2); the numbers are read out of the
; ROM, never retyped.  This zone rests on DIFFERENT evidence from the big table
; zone at 0xFDD2AB: only five of its objects have a KN5000 counterpart, so most of
; it is carried by prom_c's own reference sites plus decodes that are
; self-evidently right -- the EQ table comes out as the ISO third-octave series,
; and both mixer curves end exactly on digital full scale, values a wrong base or
; a wrong element size could not produce.
;
; Two objects were left undecoded when this was written: the f32/f64 constant
; pool at 0xFCC81A and three bytes at 0xFCCB6E.  (Corrected 2026-09-25, lane
; promcd: the pool IS decoded now -- see fp_constant_pool_FCC81A, whose element
; starts come from its 154 cited loads and whose elements are labelled by value;
; the three bytes at 0xFCCB6E remain as their own header describes.)

; ----------------------------------------------------------------------------
; Link_ClassHandlerTable -- 0xFCC53F..0xFCC55E  (32 bytes)
;
; 8 x u32.  Every entry is a valid prom_c code address, and four of them
; (0xF98D9A, 0xF98DE6, 0xF98FD6, 0xF9901B) land exactly on a `link XIZ,imm` /
; `push HL` prologue -- this compiler's function entry -- while the remaining
; four are all the SAME address, 0xF9993D, whose first byte is 0x0E = RET.
; A handler table with four real arms and four do-nothing stubs.
;
; ★ ROUND 2: THE TWO OPEN QUESTIONS ARE ANSWERED, and the reason a literal search
; found nothing is that the dispatcher never uses the ROM address.  RESET copies
; ROM 0xFCB4EA.. to RAM 0x00E2DF (notes/prom_c_ram_image.py re-derives the copy
; from the instruction bytes), and 0xFCC53F - 0xFCB4EA = 0x1055, so this table's
; RAM copy begins at 0x00E2DF + 0x1055 = 0x00F334.  That address appears as an
; instruction operand at 0xF99D91, `add xbc, 0x0000F334`, inside
; INTTC3_HANDLER__state1_generic (0xF99D6F, converted in this file): it indexes
; the table with (link command byte >> 5) * 4 and jumps through it.  So the START
; is proven by an operand after all, the dispatcher is traced, and the entry count
; of EIGHT is exactly the range of a 3-bit index.
;     python3 notes/prom_c_ram_image.py 0x00F334:32     # the boot contents
;     python3 notes/prom_c_link_state_machine.py        # the dispatcher
; ⚠ Still not established: what the four real class handlers DO.
; ★ ROUND 5 renamed it from `Handler_PtrTable_FCC53F`: the dispatcher, the index and the
; entry count were all already proved above, so the address in the name was carrying
; nothing the prose did not.  Nothing about the object changed.
; Evidence: the RAM copy at 0x00F334 is the operand of `add xbc,0x0000F334` at 0xF99D91,
;          inside INTTC3_HANDLER__state1_generic, which jumps through it.
; ----------------------------------------------------------------------------
Link_ClassHandlerTable:
	.long	Link_Ch0_AppendToRing, Link_Ch1_WriteParamBlock, Link_Ch2_ForwardBytes, Link_Ch3_SetTouchControl
	.long	Link_ChannelHandler_Ignore, Link_ChannelHandler_Ignore, Link_ChannelHandler_Ignore, Link_ChannelHandler_Ignore

; ----------------------------------------------------------------------------
; P7Module_RamStateImage -- 0xFCC55F..0xFCC575  (23 bytes)
;
; ★ ROUND 5: IT IS A RAM IMAGE, and the RAM it images is the PORT-P7 MODULE'S STATE.
; The RESET copy carries ROM 0xFCB4EA.. to RAM 0x00E2DF (notes/prom_c_ram_image.py), and
; 0xFCC55F - 0xFCB4EA = 0x1075, so these 23 bytes are the power-on contents of
; RAM 0x00F354..0x00F36A -- checked with `python3 notes/prom_c_ram_image.py 0x00F354:23`.
; Every variable in that range belongs to the P7 module:
;       0xF354, 0xF356, 0xF358   u16 x3, per unit: the "preamble already sent" latch.
;                                P7Unit_SendPreambleOnce tests it at 0xFA35E0 and writes
;                                0xFFFF at 0xFA361B; boot value 0, so nothing is skipped
;                                on a cold start.
;       0xF35A                   u16, the MIDI-OUT hex trace enable read by
;                                P7Byte_SendCmd/SendData/SendArg (0xF9A17A, 0xF9A322,
;                                0xF9A4B8).  ★ Boot value 0, and the ONE literal write in
;                                prom_c stores 0 as well (0xFA56EB) -- see below.
;       0xF35C                   the handshake timeout flag set on an 8000-spin expiry
;                                (notes/FINDINGS-prom_c-p7-byte-stream-pool.md §5).
;       0xF35D, 0xF35E           the stream-pointer GROUP selector and its previous value;
;                                0xF35D is loaded from 0xF361 and clamped to 0..1 at
;                                0xFA5715-0xFA571D.
;       0xF364                   u8, boot 0x53.
;       0xF365, 0xF367, 0xF369   u16 x3, per unit, boot 0x006C, written by P7Unit_SelectStreamsForRecord.
; ⚠ NOT ESTABLISHED: what 0xF35F..0xF363 hold (they boot zero and this pass did not trace
; every writer), what 0x53 at 0xF364 means, and what the three 0x006C words scale.
;
; ★★ AND ONE COMMITTED CLAIM IS NOW CLOSED.  FINDINGS-prom_c-p7-byte-stream-pool.md §5
; said "⚠ What sets (0x00F35A) is not established."  NOTHING DOES.  0x00F35A appears
; four times in prom_c: three `cp (0x00f35a),0x0000` tests in the three byte senders and
; ONE write, `ld (0x00f35a),0x0000` at 0xFA56EB -- a clear.  With a boot image of zero,
; the service trace can never run on this firmware.  ⚠ QUALIFIED: a write through a
; register, or one arriving over the inter-processor link, is invisible to a literal scan.
; notes/prom_c_understanding_round5.py --trace.
; Evidence: the boot copy's own operands at 0xF989EF-0xF989F9, and 0xFCC55F - 0xFCB4EA
;          = 0x1075 added to 0x00E2DF; notes/prom_c_ram_image.py 0x00F354:23.
; ----------------------------------------------------------------------------
P7Module_RamStateImage:
	.byte	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
	.byte	0x53, 0x6c, 0x00, 0x6c, 0x00, 0x6c, 0x00

; ----------------------------------------------------------------------------
; P7Unit_StreamPtrsByGroupAndUnit -- 0xFCC576..0xFCC5BD  (72 bytes)
;
; 6 groups x 3 u32 = 18 pointers, all into the byte-stream pool that starts at
; 0xFCD0F7 -- which is now CONVERTED, and every one of the 18 lands exactly on a
; `P7Stream_XXXXXX` label there (⚠ CORRECTED 2026-08-25: this header used to call
; the region "the length-prefixed packet pool", and the round-3 banner over it said
; the framing "desynchronises at 0xFCD119".  It does not: the first byte carries a
; 4-bit OPCODE as well as the top four bits of the length.  See the pool banner).  The grouping is visible in the data itself: every group is
; {X, X, Y} -- the first two entries of each group are always equal.
;    group 0  {0xFCD22D, 0xFCD22D, 0xFCD40F}
;    group 1  {0xFCD97D, 0xFCD97D, 0xFCD40F}
;    group 2  {0xFCD0FE, 0xFCD0FE, 0xFCD0F7}
;    group 3  {0xFCD105, 0xFCD105, 0xFCD0F7}
;    group 4  {0xFCD119, 0xFCD119, 0xFCD10C}
;    group 5  {0xFCD131, 0xFCD131, 0xFCD10C}
; Five of the six distinct low targets are exactly the packet starts that the
; length walk in the header of the string pool below lands on, which is what ties
; the two structures together.
; ★ ROUND 5: THE TABLE START IS ESTABLISHED, the same way Link_ClassHandlerTable's was --
; through the RAM copy, because the reader never uses the ROM address.  RESET copies ROM
; 0xFCB4EA.. to RAM 0x00E2DF, and 0xFCC576 - 0xFCB4EA = 0x108C, so this table's RAM copy
; begins at 0x00E2DF + 0x108C = 0x00F36B (`python3 notes/prom_c_ram_image.py 0x00F36B:72`).
; 0x00F36B is an instruction operand at three sites in the port-P7 module -- 0xFA2B91,
; 0xFA2CC5 and 0xFA2D78, each `add XBC,0x0000f36b` -- and the index built just above each
; of them is
;       `ld C,0x0c / mul BC,(0x00f35d)`   (0xFA2B86)   12 * group
;       `ld A,0x04 / mul WA,(XIZ+0x08)`   (0xFA2B7D)    4 * unit
; i.e. 12*group + 4*unit.  So the GROUPING THE DATA ALREADY SHOWED IS THE ADDRESSING: six
; groups of three u32, one entry per unit, and the fetched pointer becomes
; P7Stream_StageAndSend's +0x1C argument.
; ★ AND THE {X, X, Y} SHAPE IS CORROBORATED FROM THE OTHER SIDE: units 0 and 1 share a
; stream here, and in P7Stream_Data_FD4B85 the destination byte of records 1, 2 and 3 --
; the records those same three units select -- reads 0, 0, 1.  Two independent structures
; pair unit 0 with unit 1 and leave unit 2 apart.
; ⚠ STILL NOT ESTABLISHED: groups 2..5.  RAM 0xF35D is clamped to 0..1 at 0xFA5715, so the
; three sites found reach only groups 0 and 1 -- 24 of these 72 bytes.  Recorded as a gap.
; ★ But the 18 TARGETS are now established objects, which they were not in round 3.
; Evidence: 0xFCC576 - 0xFCB4EA = 0x108C added to 0x00E2DF gives 0x00F36B, which is an
;          operand at 0xFA2B91, 0xFA2CC5 and 0xFA2D78, indexed 12*group + 4*unit.
; ----------------------------------------------------------------------------
P7Unit_StreamPtrsByGroupAndUnit:
	; group 0
	.long	P7Stream_FCD22D, P7Stream_FCD22D, P7Stream_FCD40F
	; group 1
	.long	P7Stream_FCD97D, P7Stream_FCD97D, P7Stream_FCD40F
	; group 2
	.long	P7Stream_FCD0FE, P7Stream_FCD0FE, P7Stream_FCD0F7
	; group 3
	.long	P7Stream_FCD105, P7Stream_FCD105, P7Stream_FCD0F7
	; group 4
	.long	P7Stream_FCD119, P7Stream_FCD119, P7Stream_FCD10C
	; group 5
	.long	P7Stream_FCD131, P7Stream_FCD131, P7Stream_FCD10C

; ----------------------------------------------------------------------------
; unexplained_FCC5BE -- 0xFCC5BE..0xFCC5C8  (11 bytes)
;
; 11 bytes between the pointer table and the first touch curve.  Four zeros then
; ff fa fb 4d 00 80 00.
;
; ★ FOUR OF THE ELEVEN ARE NOW EXPLAINED (2026-08-24).  The u16 at 0xFCC5C5 is
; 0x004D = 77 and the u16 at 0xFCC5C7 is 0x0080 = 128, and
; ToneGen_VelocityFromTouch (0xF995DF, converted above) reads both:
;       ld DE,(curve output) / sub DE,(0xFCC5C5)      ; subtract 77
;       muls XBC,WA / divs XBC,(0xFCC5C7)             ; times gain, over 128
; 77 is the PIVOT of the touch transfer function -- the input-curve value at
; which the bracket goes to zero and the output equals
; ToneGen_VelCurve_ModeParams[mode].pivot whatever the gain is -- and 128 is the
; fixed-point divisor that makes that record's first column read as gain/128,
; which is exactly how the header below already describes it.
; The input curve holds 77 at index 144 and at NO other index, so the pivot is a
; single point on the curve.
;
; ★★ AND THE THREE BYTES ff fa fb ARE EXPLAINED TOO (2026-08-25).  They are three
; single-byte MIDI messages, each sent with length 1 through Link_SendBuffer,
; which takes a POINTER -- which is why constants that could have been immediates
; have addresses:
;       0xFCC5C2 = 0xFF   MIDI System Reset  -- sent by
;                         MIDI_Watchdogs_And_TransportSwitch when active sensing
;                         stops arriving (165 ticks after the last received byte)
;       0xFCC5C3 = 0xFA   MIDI Start         -- sent when P8 bit 2 goes HIGH
;       0xFCC5C4 = 0xFB   MIDI Continue      -- sent when P8 bit 2 goes LOW
; All three go up LINK CHANNEL 6, the same channel the raw MIDI IN bytes use.
; See notes/FINDINGS-prom_c-serial-midi.md.
;
; ⚠ Still unexplained: the four leading zeros.  They are inside the boot RAM image
; copied to 0x00F3B3, and that RAM address IS written at runtime (0xFA2DD4) -- see
; notes/FINDINGS-prom_c-ram-image.md.  So this object is not homogeneous: its head
; is a RAM initialiser and its tail is five constants read in place.
; ----------------------------------------------------------------------------
unexplained_FCC5BE:
	.byte	0x00, 0x00, 0x00, 0x00, 0xff, 0xfa, 0xfb, 0x4d, 0x00, 0x80, 0x00

; ----------------------------------------------------------------------------
; ToneGen_VelCurve_Trim51 -- 0xFCC5C9..0xFCC5FB  (51 bytes)
;
; 51 signed bytes rising monotonically from 0xF4 (-12) to 0x0A (+10).
; ⚠ TWO CORRECTIONS, 2026-08-25.
;   * "a symmetric +-12 trim curve" is wrong: the range is -12..+10, not -12..+12,
;     and the zero run is five entries wide (indices 22..26), not a crossing.
;   * "Referenced once, from 0xF99872" cites the LITERAL, not the instruction.
;     The instruction is `add XBC,0x00FCC5C9` and it starts at 0xF99872.  (This
;     tree has made that off-by-two systematically; the xref tool prints the
;     literal's address and the instruction begins one or two bytes earlier.)
; ★ AND ITS CONSUMER IS NOW CONVERTED.  NoteTrim_BuildFromCalibration (0xF997FA)
; indexes this curve with `clamp(calibration_byte - 0x4B, 0, 0x32)` and stores the
; result in the signed per-note velocity trim table at 0x0084DA, which
; ToneGen_VelocityFromTouch adds into every velocity.  The clamp's upper bound
; 0x32 gives 51 entries -- the same 51 the object chain gave, from a completely
; different argument.
; No KN5000 counterpart at the corresponding address.
; ----------------------------------------------------------------------------
ToneGen_VelCurve_Trim51:
	.byte	0xf4, 0xf4, 0xf5, 0xf6, 0xf6, 0xf7, 0xf7, 0xf8, 0xf8, 0xf9, 0xf9, 0xfa, 0xfb, 0xfb, 0xfc, 0xfc
	.byte	0xfd, 0xfd, 0xfe, 0xfe, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x02, 0x02, 0x03
	.byte	0x03, 0x04, 0x04, 0x04, 0x05, 0x05, 0x06, 0x06, 0x06, 0x07, 0x07, 0x08, 0x08, 0x08, 0x09, 0x09
	.byte	0x0a, 0x0a, 0x0a

; ----------------------------------------------------------------------------
; ToneGen_VelCurve_ModeParams -- 0xFCC5FC..0xFCC619  (30 bytes)
;
; 10 records x 3 bytes: {gain/128, output level at the pivot, trim subtracted for
; the black keys}.  This is the TOUCH SENSITIVITY table.
; ★ The table SELF-DESCRIBES: the first column steps 0x00, 0x10, 0x20 ... 0x90,
;   so the record size and the row count are both readable off the data.
; ★ It also sits at exactly the address the KN5000 offset predicts.  The 256-byte
;   curve that follows it here is byte-identical to the KN5000's, and under that
;   alignment this table lands on kn5000 0x01F420 -- the address the sibling
;   documents as the touch-mode parameter table (v142/subcpu/subcpu_data_tables.s:11302).
; The VALUES are re-tuned for this instrument; they are NOT the KN5000's:
;      curve  gain  pivot out   black trim      (KN5000, for comparison)
;        0     0/128    208         0             208   0
;        1    16/128    199         2             199   3
;        2    32/128    190         5             189   6
;        3    48/128    181         8             180   8
;        4    64/128    171        11             171  11
;        5    80/128    162        13             161  14
;        6    96/128    153        16             152  16
;        7   112/128    144        19             143  19
;        8   128/128    134        22             134  22
;        9   144/128    125        24             130  24
; Referenced three times: 0xF9962D, 0xF9966F, 0xF99698.
; ----------------------------------------------------------------------------
ToneGen_VelCurve_ModeParams:
	; curve 0
	.byte	0x00, 0xd0, 0x00
	; curve 1
	.byte	0x10, 0xc7, 0x02
	; curve 2
	.byte	0x20, 0xbe, 0x05
	; curve 3
	.byte	0x30, 0xb5, 0x08
	; curve 4
	.byte	0x40, 0xab, 0x0b
	; curve 5
	.byte	0x50, 0xa2, 0x0d
	; curve 6
	.byte	0x60, 0x99, 0x10
	; curve 7
	.byte	0x70, 0x90, 0x13
	; curve 8
	.byte	0x80, 0x86, 0x16
	; curve 9
	.byte	0x90, 0x7d, 0x18

; ----------------------------------------------------------------------------
; ToneGen_Velocity_Input_Curve -- 0xFCC61A..0xFCC719  (256 bytes)
;
; 256 bytes, monotonically DECREASING (0xFF for the first nine inputs, down to
; 0x00 at the top).  Maps the raw keybed touch reading to the curve domain.
; The sibling argues [INFERENCE] that the decreasing sense means the raw reading
; behaves like a key-travel TIME -- a small reading is a hard strike.
; Referenced from 0xF99608.  Byte-identical to v142/subcpu/subcpu_data_tables.s:11337 (kn5000 0x01F43E).
; ----------------------------------------------------------------------------
ToneGen_Velocity_Input_Curve:
	.byte	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfb, 0xf6, 0xf1, 0xed, 0xea, 0xe6, 0xe3
	.byte	0xe0, 0xdd, 0xdb, 0xd8, 0xd6, 0xd3, 0xd1, 0xcf, 0xcd, 0xcb, 0xca, 0xc8, 0xc6, 0xc5, 0xc3, 0xc1
	.byte	0xc0, 0xbf, 0xbd, 0xbc, 0xbb, 0xb9, 0xb8, 0xb7, 0xb6, 0xb5, 0xb3, 0xb2, 0xb1, 0xb0, 0xaf, 0xae
	.byte	0xad, 0xac, 0xab, 0xaa, 0xaa, 0xa9, 0xa8, 0xa7, 0xa6, 0xa5, 0xa5, 0xa4, 0xa3, 0xa2, 0xa1, 0xa1
	.byte	0xa0, 0x9f, 0x9d, 0x9c, 0x9b, 0x99, 0x98, 0x97, 0x96, 0x95, 0x93, 0x92, 0x91, 0x90, 0x8f, 0x8e
	.byte	0x8d, 0x8c, 0x8b, 0x8a, 0x8a, 0x89, 0x88, 0x87, 0x86, 0x85, 0x85, 0x84, 0x83, 0x82, 0x81, 0x81
	.byte	0x80, 0x7f, 0x7d, 0x7c, 0x7b, 0x79, 0x78, 0x77, 0x76, 0x75, 0x73, 0x72, 0x71, 0x70, 0x6f, 0x6e
	.byte	0x6d, 0x6c, 0x6b, 0x6a, 0x6a, 0x69, 0x68, 0x67, 0x66, 0x65, 0x65, 0x64, 0x63, 0x62, 0x61, 0x61
	.byte	0x60, 0x5f, 0x5d, 0x5c, 0x5b, 0x59, 0x58, 0x57, 0x56, 0x55, 0x53, 0x52, 0x51, 0x50, 0x4f, 0x4e
	.byte	0x4d, 0x4c, 0x4b, 0x4a, 0x4a, 0x49, 0x48, 0x47, 0x46, 0x45, 0x45, 0x44, 0x43, 0x42, 0x41, 0x41
	.byte	0x40, 0x3f, 0x3d, 0x3c, 0x3b, 0x39, 0x38, 0x37, 0x36, 0x35, 0x33, 0x32, 0x31, 0x30, 0x2f, 0x2e
	.byte	0x2d, 0x2c, 0x2b, 0x2a, 0x2a, 0x29, 0x28, 0x27, 0x26, 0x25, 0x25, 0x24, 0x23, 0x22, 0x21, 0x21
	.byte	0x20, 0x1f, 0x1d, 0x1c, 0x1b, 0x19, 0x18, 0x17, 0x16, 0x15, 0x13, 0x12, 0x11, 0x10, 0x0f, 0x0e
	.byte	0x0d, 0x0c, 0x0b, 0x0a, 0x0a, 0x09, 0x08, 0x07, 0x06, 0x05, 0x05, 0x04, 0x03, 0x02, 0x01, 0x01
	.byte	0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01
	.byte	0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00

; ----------------------------------------------------------------------------
; ToneGen_Velocity_Output_Curve -- 0xFCC71A..0xFCC819  (256 bytes)
;
; 256 bytes, the second half of the touch mapping: starts 0x01 then a long run of
; 0x02 -- a compressive, roughly logarithmic response.  This is the end that
; produces the delivered MIDI velocity, so it RISES with strike strength.
; Referenced from 0xF99721 (24-bit form).  Byte-identical to kn5000 0x01F53E
; (v142/subcpu/subcpu_data_tables.s:11361).
; ----------------------------------------------------------------------------
ToneGen_Velocity_Output_Curve:
	.byte	0x01, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02
	.byte	0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02
	.byte	0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02
	.byte	0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02
	.byte	0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02
	.byte	0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02
	.byte	0x03, 0x03, 0x03, 0x04, 0x04, 0x04, 0x04, 0x05, 0x05, 0x05, 0x05, 0x06, 0x06, 0x06, 0x07, 0x07
	.byte	0x07, 0x07, 0x08, 0x08, 0x08, 0x08, 0x09, 0x09, 0x09, 0x0a, 0x0a, 0x0a, 0x0a, 0x0b, 0x0b, 0x0b
	.byte	0x0c, 0x0c, 0x0c, 0x0c, 0x0d, 0x0d, 0x0d, 0x0d, 0x0e, 0x0e, 0x0e, 0x0f, 0x0f, 0x0f, 0x0f, 0x10
	.byte	0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f
	.byte	0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f
	.byte	0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f
	.byte	0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f
	.byte	0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f
	.byte	0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f
	.byte	0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f

; ----------------------------------------------------------------------------
; fp_constant_pool_FCC81A -- 0xFCC81A-0xFCCA81  (616 bytes, 78 elements)
;
; Generated by notes/gen_prom_c_fp_pool.py --emit; --verify re-proves all of it.
; ⚠ THIS WAS LEFT AS A DELIBERATE `.incbin` UNTIL ROUND 3, because decoding it on a
; fixed 8-byte grid produced denormal garbage.  It is not on a fixed grid: TWO of its
; 78 elements are four bytes wide, at 0xFCC81A and 0xFCC8FE, and they shift every
; double after them by 4.  The element starts are not inferred -- all 154 four-byte
; slots are cited by literal-addressed loads, and a double is recognised by the
; instruction pair that pushes it HIGH HALF FIRST, six bytes apart:
;     F9C2DE  ld XBC,(0xFCC9EE) / push XBC     <- high
;     F9C2E4  ld XBC,(0xFCC9EA) / push XBC     <- low = the double's address
; 76 doubles + 2 longs = 616 bytes, and 48 of the 76 are exact integers.
;
; ★ 44100 IS IN HERE, cited from eighteen sites, with 1/44100, 1/220500 and 1/441000.
; The pool's heaviest user is sub_F9BE3A (8,573 bytes), which cites 64 of the 154 slots.
; ⚠ What any constant is FOR is NOT established; the comments give values only.
; (2026-09-25, lane promcd: each element's header now also gives its loading sites and
; the double-library call it is pushed for -- pool_element_readers.py,
; pool_element_consumers.py.  What the constants are FOR is still the open question.)
; ★ The KN5000 has a pool of the same kind (v142/subcpu/subcpu_data_tables.s:2695);
; its contents do NOT match, so the sibling could not have supplied the boundaries
; either -- prom_c's own load instructions did.
; ----------------------------------------------------------------------------
fp_constant_pool_FCC81A:
	.long	0x0000FFF0               ; 0xFCC81A  32-bit element: address 0x0000FFF0
; Pool element at 0xFCC81E: f64 56. Read at 2 sites: sub_FA000B 0xFA1FD3, 0xFA1FD9.
; Each load is pushed as an argument of: Double_Subtract (call at 0xFA1FEA; under the other
; operand).
F64_56:
	.long	0x00000000, 0x404C0000   ; 0xFCC81E  f64 56
; Pool element at 0xFCC826: f64 16. Read at 2 sites: sub_FA000B 0xFA1D4D, 0xFA1D53.
; Each load is pushed as an argument of: Double_Subtract (call at 0xFA1D64; under the other
; operand).
F64_16:
	.long	0x00000000, 0x40300000   ; 0xFCC826  f64 16
; Pool element at 0xFCC82E: f64 0.005050505051. Read at 2 sites: sub_FA000B 0xFA1BAD,
; 0xFA1BB3.
; Each load is pushed as an argument of: Double_Multiply (call at 0xFA1BBE; on top).
F64_0p005050505051:
	.long	0xA052BF5B, 0x3F74AFD6   ; 0xFCC82E  f64 0.005050505051
; Pool element at 0xFCC836: f64 1100. Read at 2 sites: sub_FA000B 0xFA1724, 0xFA172A.
; Each load is pushed as an argument of: Double_Add (call at 0xFA173D; under the other
; operand).
F64_1100:
	.long	0x00000000, 0x40913000   ; 0xFCC836  f64 1100
; Pool element at 0xFCC83E: f64 81. Read at 2 sites: sub_FA000B 0xFA16EE, 0xFA16F4.
; Each load is pushed as an argument of: Double_Subtract (call at 0xFA1705; under the other
; operand).
F64_81:
	.long	0x00000000, 0x40544000   ; 0xFCC83E  f64 81
; Pool element at 0xFCC846: f64 550. Read at 2 sites: sub_FA000B 0xFA1667, 0xFA166D.
; Each load is pushed as an argument of: Double_Add (call at 0xFA1680; under the other
; operand).
F64_550:
	.long	0x00000000, 0x40813000   ; 0xFCC846  f64 550
; Pool element at 0xFCC84E: f64 50. Read at 2 sites: sub_FA000B 0xFA1654, 0xFA165A.
; Each load is pushed as an argument of: Double_Multiply (call at 0xFA1663; on top).
F64_50:
	.long	0x00000000, 0x40490000   ; 0xFCC84E  f64 50
; Pool element at 0xFCC856: f64 71. Read at 2 sites: sub_FA000B 0xFA1631, 0xFA1637.
; Each load is pushed as an argument of: Double_Subtract (call at 0xFA1648; under the other
; operand).
F64_71:
	.long	0x00000000, 0x4051C000   ; 0xFCC856  f64 71
; Pool element at 0xFCC85E: f64 110. Read at 2 sites: sub_FA000B 0xFA15A3, 0xFA15A9.
; Each load is pushed as an argument of: Double_Add (call at 0xFA15BC; under the other
; operand).
F64_110:
	.long	0x00000000, 0x405B8000   ; 0xFCC85E  f64 110
; Pool element at 0xFCC866: f64 55. Read at 2 sites: sub_FA000B 0xFA14DF, 0xFA14E5.
; Each load is pushed as an argument of: Double_Add (call at 0xFA14F8; under the other
; operand).
F64_55:
	.long	0x00000000, 0x404B8000   ; 0xFCC866  f64 55
; Pool element at 0xFCC86E: f64 5. Read at 2 sites: sub_FA000B 0xFA14CC, 0xFA14D2.
; Each load is pushed as an argument of: Double_Multiply (call at 0xFA14DB; on top).
F64_5:
	.long	0x00000000, 0x40140000   ; 0xFCC86E  f64 5
; Pool element at 0xFCC876: f64 21. Read at 2 sites: sub_FA000B 0xFA14A9, 0xFA14AF.
; Each load is pushed as an argument of: Double_Subtract (call at 0xFA14C0; under the other
; operand).
F64_21:
	.long	0x00000000, 0x40350000   ; 0xFCC876  f64 21
; Pool element at 0xFCC87E: f64 2376. Read at 2 sites: sub_FA000B 0xFA1396, 0xFA139C.
; Each load is pushed as an argument of: Double_Divide (call at 0xFA13A7; on top).
F64_2376:
	.long	0x00000000, 0x40A29000   ; 0xFCC87E  f64 2376
; Pool element at 0xFCC886: f64 10800. Read at 2 sites: sub_FA000B 0xFA0EFA, 0xFA0F00.
; Each load is pushed as an argument of: Double_Add (call at 0xFA0F17; under the other
; operand).
F64_10800:
	.long	0x00000000, 0x40C51800   ; 0xFCC886  f64 10800
; Pool element at 0xFCC88E: f64 800. Read at 2 sites: sub_FA000B 0xFA0EE5, 0xFA0EEB.
; Each load is pushed as an argument of: Double_Multiply (call at 0xFA0EF6; on top).
F64_800:
	.long	0x00000000, 0x40890000   ; 0xFCC88E  f64 800
; Pool element at 0xFCC896: f64 88. Read at 2 sites: sub_FA000B 0xFA0EAE, 0xFA0EB4.
; Each load is pushed as an argument of: Double_Subtract (call at 0xFA0EC5; under the other
; operand).
F64_88:
	.long	0x00000000, 0x40560000   ; 0xFCC896  f64 88
; Pool element at 0xFCC89E: f64 1200. Read at 2 sites: sub_FA000B 0xFA0E49, 0xFA0E4F.
; Each load is pushed as an argument of: Double_Add (call at 0xFA0E66; under the other
; operand).
F64_1200:
	.long	0x00000000, 0x4092C000   ; 0xFCC89E  f64 1200
; Pool element at 0xFCC8A6: f64 400. Read at 2 sites: sub_FA000B 0xFA0E34, 0xFA0E3A.
; Each load is pushed as an argument of: Double_Multiply (call at 0xFA0E45; on top).
F64_400:
	.long	0x00000000, 0x40790000   ; 0xFCC8A6  f64 400
; Pool element at 0xFCC8AE: f64 65. Read at 2 sites: sub_FA000B 0xFA0DFD, 0xFA0E03.
; Each load is pushed as an argument of: Double_Subtract (call at 0xFA0E14; under the other
; operand).
F64_65:
	.long	0x00000000, 0x40504000   ; 0xFCC8AE  f64 65
; Pool element at 0xFCC8B6: f64 120. Read at 2 sites: sub_FA000B 0xFA0D91, 0xFA0D97.
; Each load is pushed as an argument of: Double_Add (call at 0xFA0DAE; under the other
; operand).
F64_120:
	.long	0x00000000, 0x405E0000   ; 0xFCC8B6  f64 120
; Pool element at 0xFCC8BE: f64 11. Read at 2 sites: sub_FA000B 0xFA0C8D, 0xFA0C93.
; Each load is pushed as an argument of: Double_Subtract (call at 0xFA0CA4; under the other
; operand).
F64_11:
	.long	0x00000000, 0x40260000   ; 0xFCC8BE  f64 11
; Pool element at 0xFCC8C6: f64 111. Read at 2 sites: sub_FA000B 0xFA0BDC, 0xFA0BE2.
; Each load is pushed as an argument of: Double_Add (call at 0xFA0BF9; under the other
; operand).
F64_111:
	.long	0x00000000, 0x405BC000   ; 0xFCC8C6  f64 111
; Pool element at 0xFCC8CE: f64 4. Read at 2 sites: sub_FA000B 0xFA0B16, 0xFA0B1C.
; Each load is pushed as an argument of: Double_Multiply (call at 0xFA0B27; on top).
F64_4:
	.long	0x00000000, 0x40100000   ; 0xFCC8CE  f64 4
; Pool element at 0xFCC8D6: f64 76. Read at 4 sites: sub_FA000B 0xFA0ADF, 0xFA0AE5,
; 0xFA210F, 0xFA2115.
; Each load is pushed as an argument of: Double_Subtract x2 (calls at 0xFA0AF6, 0xFA2126;
; under the other operand).
F64_76:
	.long	0x00000000, 0x40530000   ; 0xFCC8D6  f64 76
; Pool element at 0xFCC8DE: f64 26. Read at 2 sites: sub_FA000B 0xFA0A77, 0xFA0A7D.
; Each load is pushed as an argument of: Double_Add (call at 0xFA0A90; under the other
; operand).
F64_26:
	.long	0x00000000, 0x403A0000   ; 0xFCC8DE  f64 26
; Pool element at 0xFCC8E6: f64 51. Read at 2 sites: sub_FA000B 0xFA0A48, 0xFA0A4E.
; Each load is pushed as an argument of: Double_Subtract (call at 0xFA0A5F; under the other
; operand).
F64_51:
	.long	0x00000000, 0x40498000   ; 0xFCC8E6  f64 51
; Pool element at 0xFCC8EE: f64 54. Read at 6 sites: sub_FA000B 0xFA0443, 0xFA0449,
; 0xFA075C, 0xFA0762 +2 more.
; Each load is pushed as an argument of: Double_Subtract x2 (calls at 0xFA0452, 0xFA076B; on
; top); Double_Add (call at 0xFA0B48; under the other operand).
F64_54:
	.long	0x00000000, 0x404B0000   ; 0xFCC8EE  f64 54
; Pool element at 0xFCC8F6: f64 84. Read at 4 sites: sub_FA000B 0xFA0345, 0xFA034B,
; 0xFA065E, 0xFA0664.
; Each load is pushed as an argument of: Double_Subtract x2 (calls at 0xFA0354, 0xFA066D; on
; top).
F64_84:
	.long	0x00000000, 0x40550000   ; 0xFCC8F6  f64 84
; Pool element at 0xFCC8FE: 32-bit element: f32 0.980392158. Read at 1 site: sub_F9ECF1
; 0xF9F745.
F32_0p980392158:
	.long	0x3F7AFAFB               ; 0xFCC8FE  32-bit element: f32 0.980392158
; Pool element at 0xFCC902: f64 0.0001424758573. Read at 16 sites: sub_F9ECF1 0xF9EE2C,
; 0xF9EE32, 0xF9EE63, 0xF9EE69 +12 more.
; Each load is pushed as an argument of: Double_Multiply x8 (calls at 0xF9EE3B, 0xF9EE72,
; 0xF9EFC4, 0xF9EFFB +4 more; on top).
F64_0p0001424758573:
	.long	0x4B8EB24E, 0x3F22ACB2   ; 0xFCC902  f64 0.0001424758573
; Pool element at 0xFCC90A: f64 0.51. Read at 2 sites: sub_F9ECF1 0xF9ECF6, 0xF9ECFC.
; Each load is pushed as an argument of: Double_ToFloat32 (call at 0xF9ED02; on top).
F64_0p51:
	.long	0x851EB852, 0x3FE051EB   ; 0xFCC90A  f64 0.51
; Pool element at 0xFCC912: f64 -2. Read at 4 sites: sub_F9E1ED 0xF9E39B, 0xF9E3A1,
; 0xF9EAC2, 0xF9EAC8.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9E3AA, 0xF9EAD1; on
; top).
F64_neg2:
	.long	0x00000000, 0xC0000000   ; 0xFCC912  f64 -2
; Pool element at 0xFCC91A: f64 7.123792865e-05. Read at 4 sites: sub_F9E1ED 0xF9E2C3,
; 0xF9E2C9, 0xF9E9EA, 0xF9E9F0.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9E2D2, 0xF9E9F9; on
; top).
F64_7p123792865em05:
	.long	0x4B8EB24E, 0x3F12ACB2   ; 0xFCC91A  f64 7.123792865e-05
; Pool element at 0xFCC922: f64 12. Read at 2 sites: sub_F9E1ED 0xF9E253, 0xF9E259.
; Each load is pushed as an argument of: Double_Subtract (call at 0xF9E26C; under the other
; operand).
F64_12:
	.long	0x00000000, 0x40280000   ; 0xFCC922  f64 12
; Pool element at 0xFCC92A: f64 0.001. Read at 12 sites: sub_F9BE3A 0xF9DEAF, 0xF9DEB5;
; sub_FA000B 0xFA1444, 0xFA144A, 0xFA1508, 0xFA150E +6 more.
; Each load is pushed as an argument of: Double_Multiply x6 (calls at 0xF9DEC0, 0xFA1455,
; 0xFA1519, 0xFA15DD +2 more; on top).
F64_0p001:
	.long	0xD2F1A9FC, 0x3F50624D   ; 0xFCC92A  f64 0.001
; Pool element at 0xFCC932: f64 9. Read at 6 sites: sub_F9BE3A 0xF9DB02, 0xF9DB08;
; sub_FA000B 0xFA0BC7, 0xFA0BCD, 0xFA213E, 0xFA2144.
; Each load is pushed as an argument of: Double_Add x2 (calls at 0xF9DB1F, 0xFA2157; under
; the other operand); Double_Multiply (call at 0xFA0BD8; on top).
F64_9:
	.long	0x00000000, 0x40220000   ; 0xFCC932  f64 9
; Pool element at 0xFCC93A: f64 4.2. Read at 4 sites: sub_F9BE3A 0xF9D9E6, 0xF9D9EC;
; sub_FA000B 0xFA201F, 0xFA2025.
; Each load is pushed as an argument of: Double_Add x2 (calls at 0xF9DA03, 0xFA203C; under
; the other operand).
F64_4p2:
	.long	0xCCCCCCCD, 0x4010CCCC   ; 0xFCC93A  f64 4.2
; Pool element at 0xFCC942: f64 0.9. Read at 4 sites: sub_F9BE3A 0xF9D8C1, 0xF9D8C7;
; sub_FA000B 0xFA1EDC, 0xFA1EE2.
; Each load is pushed as an argument of: Double_Add x2 (calls at 0xF9D8DE, 0xFA1EF9; under
; the other operand).
F64_0p9:
	.long	0xCCCCCCCD, 0x3FECCCCC   ; 0xFCC942  f64 0.9
; Pool element at 0xFCC94A: f64 0.45. Read at 4 sites: sub_F9BE3A 0xF9D79C, 0xF9D7A2;
; sub_FA000B 0xFA1D99, 0xFA1D9F.
; Each load is pushed as an argument of: Double_Add x2 (calls at 0xF9D7B9, 0xFA1DB6; under
; the other operand).
F64_0p45:
	.long	0xCCCCCCCD, 0x3FDCCCCC   ; 0xFCC94A  f64 0.45
; Pool element at 0xFCC952: f64 -4.816. Read at 20 sites: sub_F9BE3A 0xF9D6B5, 0xF9D6BB,
; 0xF9D7D8, 0xF9D7DE +6 more; sub_FA000B 0xFA1C96, 0xFA1C9C, 0xFA1DD5, 0xFA1DDB +6 more.
; Each load is pushed as an argument of: Double_Multiply x10 (calls at 0xF9D6C6, 0xF9D7E9,
; 0xF9D90E, 0xF9DA33 +6 more; on top).
F64_neg4p816:
	.long	0x810624DD, 0xC0134395   ; 0xFCC952  f64 -4.816
; Pool element at 0xFCC95A: f64 0.1. Read at 10 sites: sub_F9BE3A 0xF9D679, 0xF9D67F,
; 0xF9D8AC, 0xF9D8B2; sub_F9E1ED 0xF9E9AF, 0xF9E9B5; sub_FA000B 0xFA1C60, 0xFA1C66,
; 0xFA1EC7, 0xFA1ECD.
; Each load is pushed as an argument of: Double_Add x2 (calls at 0xF9D696, 0xFA1C77; under
; the other operand); Double_Multiply x2 (calls at 0xF9D8BD, 0xFA1ED8; on top);
; Double_ToFloat32 (call at 0xF9E9BB; on top).
F64_0p1:
	.long	0x9999999A, 0x3FB99999   ; 0xFCC95A  f64 0.1
; Pool element at 0xFCC962: f64 0.02. Read at 4 sites: sub_F9BE3A 0xF9D664, 0xF9D66A;
; sub_FA000B 0xFA1C4D, 0xFA1C53.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9D675, 0xFA1C5C; on
; top).
F64_0p02:
	.long	0x47AE147B, 0x3F947AE1   ; 0xFCC962  f64 0.02
; Pool element at 0xFCC96A: f64 0.9999. Read at 4 sites: sub_F9BE3A 0xF9D3B1, 0xF9D3B7,
; 0xF9D45D, 0xF9D463.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9D3C2, 0xF9D46E; on
; top).
F64_0p9999:
	.long	0x48E8A71E, 0x3FEFFF2E   ; 0xFCC96A  f64 0.9999
; Pool element at 0xFCC972: f64 -0.0697. Read at 4 sites: sub_F9BE3A 0xF9D36F, 0xF9D375,
; 0xF9D417, 0xF9D41D.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9D380, 0xF9D428; on
; top).
F64_neg0p0697:
	.long	0xF487FCB9, 0xBFB1D7DB   ; 0xFCC972  f64 -0.0697
; Pool element at 0xFCC97A: f64 0.0004166666667. Read at 8 sites: sub_F9BE3A 0xF9D281,
; 0xF9D287, 0xF9D2E4, 0xF9D2EA; sub_FA000B 0xFA1A82, 0xFA1A88, 0xFA1AE5, 0xFA1AEB.
; Each load is pushed as an argument of: Double_Multiply x4 (calls at 0xF9D292, 0xF9D2F5,
; 0xFA1A91, 0xFA1AF6; on top).
F64_0p0004166666667:
	.long	0xB4E81B4F, 0x3F3B4E81   ; 0xFCC97A  f64 0.0004166666667
; Pool element at 0xFCC982: f64 1400. Read at 4 sites: sub_F9BE3A 0xF9D21A, 0xF9D220;
; sub_FA000B 0xFA1A25, 0xFA1A2B.
; Each load is pushed as an argument of: Double_Add x2 (calls at 0xF9D237, 0xFA1A3E; under
; the other operand).
F64_1400:
	.long	0x00000000, 0x4095E000   ; 0xFCC982  f64 1400
; Pool element at 0xFCC98A: f64 31. Read at 6 sites: sub_F9BE3A 0xF9D1D8, 0xF9D1DE;
; sub_FA000B 0xFA156D, 0xFA1573, 0xFA19EF, 0xFA19F5.
; Each load is pushed as an argument of: Double_Subtract x3 (calls at 0xF9D1F5, 0xFA1584,
; 0xFA1A06; under the other operand).
F64_31:
	.long	0x00000000, 0x403F0000   ; 0xFCC98A  f64 31
; Pool element at 0xFCC992: f64 200. Read at 8 sites: sub_F9BE3A 0xF9D16B, 0xF9D171,
; 0xF9D205, 0xF9D20B; sub_FA000B 0xFA198A, 0xFA1990, 0xFA1A12, 0xFA1A18.
; Each load is pushed as an argument of: Double_Add x2 (calls at 0xF9D188, 0xFA19A3; under
; the other operand); Double_Multiply x2 (calls at 0xF9D216, 0xFA1A21; on top).
F64_200:
	.long	0x00000000, 0x40690000   ; 0xFCC992  f64 200
; Pool element at 0xFCC99A: f64 100. Read at 6 sites: sub_F9BE3A 0xF9D156, 0xF9D15C;
; sub_FA000B 0xFA1711, 0xFA1717, 0xFA1977, 0xFA197D.
; Each load is pushed as an argument of: Double_Multiply x3 (calls at 0xF9D167, 0xFA1720,
; 0xFA1986; on top).
F64_100:
	.long	0x00000000, 0x40590000   ; 0xFCC99A  f64 100
; Pool element at 0xFCC9A2: f64 19. Read at 4 sites: sub_F9BE3A 0xF9D129, 0xF9D12F;
; sub_FA000B 0xFA1954, 0xFA195A.
; Each load is pushed as an argument of: Double_Subtract x2 (calls at 0xF9D146, 0xFA196B;
; under the other operand).
F64_19:
	.long	0x00000000, 0x40330000   ; 0xFCC9A2  f64 19
; Pool element at 0xFCC9AA: f64 20. Read at 14 sites: sub_F9BE3A 0xF9D07D, 0xF9D083,
; 0xF9D092, 0xF9D098; sub_FA000B 0xFA0CD9, 0xFA0CDF, 0xFA0D45, 0xFA0D4B +6 more.
; Each load is pushed as an argument of: Double_Multiply x3 (calls at 0xF9D08E, 0xFA0D8D,
; 0xFA18BF; on top); Double_Add x3 (calls at 0xF9D0AF, 0xFA0CF6, 0xFA18DC; under the other
; operand); Double_Subtract (call at 0xFA0D5C; under the other operand).
F64_20:
	.long	0x00000000, 0x40340000   ; 0xFCC9AA  f64 20
; Pool element at 0xFCC9B2: f64 99. Read at 24 sites: sub_F9BE3A 0xF9CB04, 0xF9CB0A,
; 0xF9CB67, 0xF9CB6D +4 more; sub_FA000B 0xFA0061, 0xFA0067, 0xFA0143, 0xFA0149 +12 more.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9CB15, 0xFA132B; on
; top); Double_Subtract x9 (calls at 0xF9CB78, 0xF9D35F, 0xF9D407, 0xFA0070 +5 more; on
; top); Double_Add (call at 0xFA1B75; under the other operand).
F64_99:
	.long	0x00000000, 0x4058C000   ; 0xFCC9B2  f64 99
; Pool element at 0xFCC9BA: f64 89. Read at 6 sites: sub_F9BE3A 0xF9C9C4, 0xF9C9CA;
; sub_FA000B 0xFA0B90, 0xFA0B96, 0xFA11F8, 0xFA11FE.
; Each load is pushed as an argument of: Double_Subtract x3 (calls at 0xF9C9E1, 0xFA0BA7,
; 0xFA120F; under the other operand).
F64_89:
	.long	0x00000000, 0x40564000   ; 0xFCC9BA  f64 89
; Pool element at 0xFCC9C2: f64 0.4270422. Read at 8 sites: sub_F9BE3A 0xF9C960, 0xF9C966,
; 0xF9CA33, 0xF9CA39; sub_FA000B 0xFA1196, 0xFA119C, 0xFA1257, 0xFA125D.
; Each load is pushed as an argument of: Double_Pow x4 (calls at 0xF9C971, 0xF9CA44,
; 0xFA11A7, 0xFA1268; on top).
F64_0p4270422:
	.long	0xCEC0C2D3, 0x3FDB54A8   ; 0xFCC9C2  f64 0.4270422
; Pool element at 0xFCC9CA: f64 441. Read at 4 sites: sub_F9BE3A 0xF9C91E, 0xF9C924;
; sub_FA000B 0xFA115A, 0xFA1160.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9C92F, 0xFA1169; on
; top).
F64_441:
	.long	0x00000000, 0x407B9000   ; 0xFCC9CA  f64 441
; Pool element at 0xFCC9D2: f64 1. Read at 82 sites: sub_F9BE3A 0xF9C8F1, 0xF9C8F7,
; 0xF9C981, 0xF9C987 +6 more; sub_F9E1ED 0xF9E29B, 0xF9E2A1, 0xF9E347, 0xF9E34D +18 more;
; sub_F9ECF1 0xF9EE87, 0xF9EE8D, 0xF9EED8, 0xF9EEDE +40 more; sub_FA000B 0xFA1137, 0xFA113D,
; 0xFA11B7, 0xFA11BD +2 more.
; Each load is pushed as an argument of: Double_Add x14 (calls at 0xF9C90E, 0xF9E362,
; 0xF9E512, 0xF9EA89 +10 more; under the other operand); Double_Subtract x16 (calls at
; 0xF9C992, 0xF9CA65, 0xF9D2D4, 0xF9E3E1 +12 more; on top); Double_Multiply (call at
; 0xF9DAFE; on top); Double_ToFloat32 x3 (calls at 0xF9E2A7, 0xF9E816, 0xF9E9CE; on top);
; Double_Compare (call at 0xF9E802; under the other operand); Double_Subtract x6 (calls at
; 0xF9EE9E, 0xF9F027, 0xF9F0C6, 0xF9F359 +2 more; under the other operand).
F64_1:
	.long	0x00000000, 0x3FF00000   ; 0xFCC9D2  f64 1
; Pool element at 0xFCC9DA: f64 2. Read at 18 sites: sub_F9BE3A 0xF9C518, 0xF9C51E,
; 0xF9C60C, 0xF9C612 +6 more; sub_FA000B 0xFA13B9, 0xFA13BF, 0xFA140E, 0xFA1414 +4 more.
; Each load is pushed as an argument of: Double_Pow x6 (calls at 0xF9C529, 0xF9C61D,
; 0xF9CBC8, 0xF9D2B3 +2 more; on top); Double_Multiply x3 (calls at 0xF9CFD6, 0xFA141D,
; 0xFA1819; on top).
F64_2:
	.long	0x00000000, 0x40000000   ; 0xFCC9DA  f64 2
; Pool element at 0xFCC9E2: f64 44100. Read at 36 sites: sub_F9BE3A 0xF9C36B, 0xF9C371,
; 0xF9C49D, 0xF9C4A3 +18 more; sub_FA000B 0xFA121B, 0xFA1221, 0xFA1354, 0xFA135A +10 more.
; Each load is pushed as an argument of: Double_Multiply x18 (calls at 0xF9C37C, 0xF9C4AE,
; 0xF9C5A2, 0xF9CA02 +14 more; on top).
F64_44100:
	.long	0x00000000, 0x40E58880   ; 0xFCC9E2  f64 44100
; Pool element at 0xFCC9EA: f64 0.0101010101. Read at 6 sites: sub_F9BE3A 0xF9C2DE,
; 0xF9C2E4; sub_FA000B 0xFA0FC1, 0xFA0FC7, 0xFA10A9, 0xFA10AF.
; Each load is pushed as an argument of: Double_Multiply x3 (calls at 0xF9C2EF, 0xFA0FD0,
; 0xFA10B8; on top).
F64_0p0101010101:
	.long	0xA052BF5B, 0x3F84AFD6   ; 0xFCC9EA  f64 0.0101010101
; Pool element at 0xFCC9F2: f64 2.267573696e-05. Read at 20 sites: sub_F9BE3A 0xF9C029,
; 0xF9C02F, 0xF9C0A8, 0xF9C0AE +6 more; sub_FA000B 0xFA0C54, 0xFA0C5A, 0xFA0D06, 0xFA0D0C +6
; more.
; Each load is pushed as an argument of: Double_Multiply x10 (calls at 0xF9C03A, 0xF9C0B9,
; 0xF9C13A, 0xF9C1BB +6 more; on top).
F64_2p267573696em05:
	.long	0xC751F177, 0x3EF7C6F8   ; 0xFCC9F2  f64 2.267573696e-05
; Pool element at 0xFCC9FA: f64 4.535147392e-06. Read at 12 sites: sub_F9BE3A 0xF9BEDF,
; 0xF9BEE5, 0xF9BF60, 0xF9BF66 +2 more; sub_FA000B 0xFA0AA0, 0xFA0AA6, 0xFA0B58, 0xFA0B5E +2
; more.
; Each load is pushed as an argument of: Double_Multiply x6 (calls at 0xF9BEF0, 0xF9BF71,
; 0xF9BFE9, 0xFA0AB1 +2 more; on top).
F64_4p535147392em06:
	.long	0xD2A7F45F, 0x3ED30593   ; 0xFCC9FA  f64 4.535147392e-06
; Pool element at 0xFCCA02: f64 2.267573696e-06. Read at 4 sites: sub_F9BE3A 0xF9BE79,
; 0xF9BE7F; sub_FA000B 0xFA0A0F, 0xFA0A15.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9BE8A, 0xFA0A1E; on
; top).
F64_2p267573696em06:
	.long	0xD2A7F45F, 0x3EC30593   ; 0xFCCA02  f64 2.267573696e-06
; Pool element at 0xFCCA0A: f64 0.999999. Read at 4 sites: sub_F9B887 0xF9BE09, 0xF9BE0F;
; sub_FA000B 0xFA09AF, 0xFA09B5.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9BE1A, 0xFA09BE; on
; top).
F64_0p999999:
	.long	0xE7210BE9, 0x3FEFFFFD   ; 0xFCCA0A  f64 0.999999
; Pool element at 0xFCCA12: f64 0.516. Read at 4 sites: sub_F9B887 0xF9BCEE, 0xF9BCF4;
; sub_FA000B 0xFA089E, 0xFA08A4.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9BCFF, 0xFA08AF; on
; top).
F64_0p516:
	.long	0x6E978D50, 0x3FE08312   ; 0xFCCA12  f64 0.516
; Pool element at 0xFCCA1A: f64 0.025. Read at 16 sites: sub_F9B887 0xF9BA78, 0xF9BA7E,
; 0xF9BB59, 0xF9BB5F +4 more; sub_FA000B 0xFA05D1, 0xFA05D7, 0xFA06CF, 0xFA06D5 +4 more.
; Each load is pushed as an argument of: Double_Multiply x8 (calls at 0xF9BA89, 0xF9BB6A,
; 0xF9BC4B, 0xF9BD41 +4 more; on top).
F64_0p025:
	.long	0x9999999A, 0x3F999999   ; 0xFCCA1A  f64 0.025
; Pool element at 0xFCCA22: f64 -12. Read at 8 sites: sub_F9B887 0xF9B957, 0xF9B95D,
; 0xF9BC19, 0xF9BC1F; sub_FA000B 0xFA0493, 0xFA0499, 0xFA07AC, 0xFA07B2.
; Each load is pushed as an argument of: Double_Subtract x4 (calls at 0xF9B968, 0xF9BC2A,
; 0xFA04A4, 0xFA07BD; on top).
F64_neg12:
	.long	0x00000000, 0xC0280000   ; 0xFCCA22  f64 -12
; Pool element at 0xFCCA2A: f64 0.6. Read at 6 sites: sub_F9B887 0xF9B936, 0xF9B93C;
; sub_FA000B 0xFA0472, 0xFA0478, 0xFA078B, 0xFA0791.
; Each load is pushed as an argument of: Double_Multiply x3 (calls at 0xF9B947, 0xFA0483,
; 0xFA079C; on top).
F64_0p6:
	.long	0x33333333, 0x3FE33333   ; 0xFCCA2A  f64 0.6
; Pool element at 0xFCCA32: f64 0.4. Read at 8 sites: sub_F9B5A5 0xF9B855, 0xF9B85B;
; sub_F9B887 0xF9BB17, 0xF9BB1D; sub_FA000B 0xFA0374, 0xFA037A, 0xFA068D, 0xFA0693.
; Each load is pushed as an argument of: Double_Multiply x4 (calls at 0xF9B866, 0xF9BB28,
; 0xFA0385, 0xFA069E; on top).
F64_0p4:
	.long	0x9999999A, 0x3FD99999   ; 0xFCCA32  f64 0.4
; Pool element at 0xFCCA3A: f64 0.2. Read at 14 sites: sub_F9B5A5 0xF9B774, 0xF9B77A;
; sub_F9B887 0xF9BA36, 0xF9BA3C, 0xF9BBF8, 0xF9BBFE; sub_F9BE3A 0xF9D9D1, 0xF9D9D7;
; sub_FA000B 0xFA0276, 0xFA027C, 0xFA058F, 0xFA0595 +2 more.
; Each load is pushed as an argument of: Double_Multiply x7 (calls at 0xF9B785, 0xF9BA47,
; 0xF9BC09, 0xF9D9E2 +3 more; on top).
F64_0p2:
	.long	0x9999999A, 0x3FC99999   ; 0xFCCA3A  f64 0.2
; Pool element at 0xFCCA42: f64 0. Read at 32 sites: sub_F9B5A5 0xF9B71A, 0xF9B720,
; 0xF9B876, 0xF9B87C; sub_F9B887 0xF9B9E8, 0xF9B9EE, 0xF9BB38, 0xF9BB3E +4 more; sub_F9E1ED
; 0xF9E649, 0xF9E64F, 0xF9EB5C, 0xF9EB62; sub_F9ECF1 0xF9EDFA, 0xF9EE00, 0xF9F2B5, 0xF9F2BB;
; sub_FA000B 0xFA0203, 0xFA0209, 0xFA0395, 0xFA039B +8 more.
; Each load is pushed as an argument of: Double_ToFloat32 x9 (calls at 0xF9B726, 0xF9B9F4,
; 0xF9BCB6, 0xF9BDAC +5 more; on top); Double_Subtract x3 (calls at 0xF9BB49, 0xFA03A6,
; 0xFA06BF; on top); Double_Compare x3 (calls at 0xF9E65D, 0xF9EE0E, 0xF9F2C9; under the
; other operand). 2 of its 32 loads are not a push-and-call and are not described here.
F64_0:
	.long	0x00000000, 0x00000000   ; 0xFCCA42  f64 0
; Pool element at 0xFCCA4A: f64 0.05. Read at 28 sites: sub_F9B5A5 0xF9B6AA, 0xF9B6B0,
; 0xF9B7B6, 0xF9B7BC; sub_F9B887 0xF9B897, 0xF9B89D, 0xF9B978, 0xF9B97E; sub_F9BE3A
; 0xF9D787, 0xF9D78D; sub_F9E1ED 0xF9E467, 0xF9E46D, 0xF9E576, 0xF9E57C; sub_F9ECF1
; 0xF9EDAC, 0xF9EDB2, 0xF9F267, 0xF9F26D; sub_FA000B 0xFA0193, 0xFA0199, 0xFA02B8, 0xFA02BE
; +6 more.
; Each load is pushed as an argument of: Double_Multiply x14 (calls at 0xF9B6BB, 0xF9B7C7,
; 0xF9B8A8, 0xF9B989 +10 more; on top).
F64_0p05:
	.long	0x9999999A, 0x3FA99999   ; 0xFCCA4A  f64 0.05
; Pool element at 0xFCCA52: f64 3. Read at 16 sites: sub_F9B5A5 0xF9B689, 0xF9B68F,
; 0xF9B795, 0xF9B79B; sub_F9B887 0xF9BA57, 0xF9BA5D, 0xF9BD0F, 0xF9BD15; sub_FA000B
; 0xFA0172, 0xFA0178, 0xFA0297, 0xFA029D +4 more.
; Each load is pushed as an argument of: Double_Subtract x8 (calls at 0xF9B69A, 0xF9B7A6,
; 0xF9BA68, 0xF9BD20 +4 more; on top).
F64_3:
	.long	0x00000000, 0x40080000   ; 0xFCCA52  f64 3
; Pool element at 0xFCCA5A: f64 0.5. Read at 94 sites: sub_F9B5A5 0xF9B623, 0xF9B629,
; 0xF9B6EC, 0xF9B6F2 +2 more; sub_F9B887 0xF9B8D9, 0xF9B8DF, 0xF9B9BA, 0xF9B9C0 +8 more;
; sub_F9BE3A 0xF9D72D, 0xF9D733, 0xF9D850, 0xF9D856 +8 more; sub_F9E1ED 0xF9E240, 0xF9E246,
; 0xF9E87E, 0xF9E884 +18 more; sub_F9ECF1 0xF9ED42, 0xF9ED48, 0xF9F198, 0xF9F19E +10 more;
; sub_FA000B 0xFA00F3, 0xFA00F9, 0xFA01D5, 0xFA01DB +24 more.
; Each load is pushed as an argument of: Double_Multiply x46 (calls at 0xF9B634, 0xF9B6FD,
; 0xF9B809, 0xF9B8EA +42 more; on top); Double_ToFloat32 (call at 0xF9DC7B; on top).
F64_0p5:
	.long	0x00000000, 0x3FE00000   ; 0xFCCA5A  f64 0.5
; Pool element at 0xFCCA62: f64 10. Read at 86 sites: sub_F9B5A5 0xF9B602, 0xF9B608,
; 0xF9B6CB, 0xF9B6D1 +2 more; sub_F9B887 0xF9B8B8, 0xF9B8BE, 0xF9B999, 0xF9B99F +8 more;
; sub_F9BE3A 0xF9C93F, 0xF9C945, 0xF9CA12, 0xF9CA18 +16 more; sub_F9E1ED 0xF9E482, 0xF9E488,
; 0xF9E591, 0xF9E597; sub_F9ECF1 0xF9EDC7, 0xF9EDCD, 0xF9F282, 0xF9F288; sub_FA000B
; 0xFA00D2, 0xFA00D8, 0xFA01B4, 0xFA01BA +36 more.
; Each load is pushed as an argument of: Double_Pow x34 (calls at 0xF9B613, 0xF9B6DC,
; 0xF9B7E8, 0xF9B8C9 +30 more; on top); Double_Divide x4 (calls at 0xF9C950, 0xF9CA23,
; 0xFA1186, 0xFA1247; on top); Double_Subtract x2 (calls at 0xF9D06D, 0xFA18A4; under the
; other operand); Double_Multiply x2 (calls at 0xFA0CD5, 0xFA159F; on top); Double_Add (call
; at 0xFA1438; under the other operand).
F64_10:
	.long	0x00000000, 0x40240000   ; 0xFCCA62  f64 10
; Pool element at 0xFCCA6A: f64 0.0125. Read at 4 sites: sub_F9B5A5 0xF9B5E1, 0xF9B5E7;
; sub_FA000B 0xFA00B1, 0xFA00B7.
; Each load is pushed as an argument of: Double_Multiply x2 (calls at 0xF9B5F2, 0xFA00C2; on
; top).
F64_0p0125:
	.long	0x9999999A, 0x3F899999   ; 0xFCCA6A  f64 0.0125
; Pool element at 0xFCCA72: f64 24. Read at 8 sites: sub_F9B5A5 0xF9B5C0, 0xF9B5C6;
; sub_F9ECF1 0xF9ED1F, 0xF9ED25; sub_FA000B 0xFA0090, 0xFA0096, 0xFA1E90, 0xFA1E96.
; Each load is pushed as an argument of: Double_Subtract x2 (calls at 0xF9B5D1, 0xFA00A1; on
; top); Double_Subtract x2 (calls at 0xF9ED36, 0xFA1EA7; under the other operand).
F64_24:
	.long	0x00000000, 0x40380000   ; 0xFCCA72  f64 24
; Pool element at 0xFCCA7A: f64 2147483648. Read at 8 sites: P7Group_SendOp0AddrValueScaled
; 0xF9AF2D, 0xF9AF33; P7Group_SendOp1AddrValueScaled 0xF9B1DC, 0xF9B1E2;
; P7Group_SendValueScaled 0xF9B397, 0xF9B39D; sub_F9FD0E 0xF9FDE9, 0xF9FDEF.
; Each load is pushed as an argument of: Double_Multiply x4 (calls at 0xF9AF3C, 0xF9B1EB,
; 0xF9B3A6, 0xF9FDF8; on top).
F64_2147483648:
	.long	0x00000000, 0x41E00000   ; 0xFCCA7A  f64 2147483648

; ----------------------------------------------------------------------------
; DSP_EQ_FreqHz_Table -- 0xFCCA82..0xFCCAED  (108 bytes)
;
; 27 x f32: parametric-EQ centre frequencies in Hz.
; ★ SELF-PROVING: decoded as little-endian f32 from this address the 27 values
;   come out as exactly the ISO third-octave series 40, 50, 63, 80 ... 12500,
;   16000.  A one-byte error in the base, or a wrong element size, turns that
;   into denormals.  The decoded value is written beside every entry below.
; Referenced four times: 0xF9E290, 0xF9E9A4, 0xF9ED89, 0xF9F244.
; Byte-identical to kn5000 0x012397 (v142/subcpu/subcpu_data_tables.s:2510).
; ----------------------------------------------------------------------------
DSP_EQ_FreqHz_Table:
	.long	0x42200000	; [ 0] = 40
	.long	0x42480000	; [ 1] = 50
	.long	0x427c0000	; [ 2] = 63
	.long	0x42a00000	; [ 3] = 80
	.long	0x42c80000	; [ 4] = 100
	.long	0x42fa0000	; [ 5] = 125
	.long	0x43200000	; [ 6] = 160
	.long	0x43480000	; [ 7] = 200
	.long	0x437a0000	; [ 8] = 250
	.long	0x439d8000	; [ 9] = 315
	.long	0x43c80000	; [10] = 400
	.long	0x43fa0000	; [11] = 500
	.long	0x441d8000	; [12] = 630
	.long	0x44480000	; [13] = 800
	.long	0x447a0000	; [14] = 1000
	.long	0x449c4000	; [15] = 1250
	.long	0x44c80000	; [16] = 1600
	.long	0x44fa0000	; [17] = 2000
	.long	0x451c4000	; [18] = 2500
	.long	0x4544e000	; [19] = 3150
	.long	0x457a0000	; [20] = 4000
	.long	0x459c4000	; [21] = 5000
	.long	0x45c4e000	; [22] = 6300
	.long	0x45fa0000	; [23] = 8000
	.long	0x461c4000	; [24] = 10000
	.long	0x46435000	; [25] = 12500
	.long	0x467a0000	; [26] = 16000

; ----------------------------------------------------------------------------
; DSP_EQ_Q_Table -- 0xFCCAEE..0xFCCB6D  (128 bytes)
;
; 32 x f32: parametric-EQ Q / bandwidth values -- 0.1..0.9 by 0.1, then 1.0..4.0
; by 0.5, then 5..20 by 1.  Same self-proving decode as the frequency table.
; Referenced from 0xF9E201.  Byte-identical to kn5000 0x012403 (v142/subcpu/subcpu_data_tables.s:2520).
; ----------------------------------------------------------------------------
DSP_EQ_Q_Table:
	.long	0x3dcccccd	; [ 0] = 0.1
	.long	0x3e4ccccd	; [ 1] = 0.2
	.long	0x3e99999a	; [ 2] = 0.3
	.long	0x3ecccccd	; [ 3] = 0.4
	.long	0x3f000000	; [ 4] = 0.5
	.long	0x3f19999a	; [ 5] = 0.6
	.long	0x3f333333	; [ 6] = 0.7
	.long	0x3f4ccccd	; [ 7] = 0.8
	.long	0x3f666666	; [ 8] = 0.9
	.long	0x3f800000	; [ 9] = 1
	.long	0x3fc00000	; [10] = 1.5
	.long	0x40000000	; [11] = 2
	.long	0x40200000	; [12] = 2.5
	.long	0x40400000	; [13] = 3
	.long	0x40600000	; [14] = 3.5
	.long	0x40800000	; [15] = 4
	.long	0x40a00000	; [16] = 5
	.long	0x40c00000	; [17] = 6
	.long	0x40e00000	; [18] = 7
	.long	0x41000000	; [19] = 8
	.long	0x41100000	; [20] = 9
	.long	0x41200000	; [21] = 10
	.long	0x41300000	; [22] = 11
	.long	0x41400000	; [23] = 12
	.long	0x41500000	; [24] = 13
	.long	0x41600000	; [25] = 14
	.long	0x41700000	; [26] = 15
	.long	0x41800000	; [27] = 16
	.long	0x41880000	; [28] = 17
	.long	0x41900000	; [29] = 18
	.long	0x41980000	; [30] = 19
	.long	0x41a00000	; [31] = 20

; ----------------------------------------------------------------------------
; unexplained_FCCB6E -- 0xFCCB6E..0xFCCB70  (3 bytes)
;
; 3 bytes, 00 01 00, sitting between the Q table and the gain curve.
; ★ ROUND 5 TRACED THE READERS (the round-3 header said they were not traced) -- and it
; is still not named, because tracing them does not reach a meaning.
; All three sites are in the port-P7 unit module and all three index it with the UNIT
; index, 0..2, so the object is three bytes because there are three units:
;       0xFA2C1F  add XWA,0x00fccb6e   in P7Unit_LoadProgramStreams   (index (XIZ+0x08))
;       0xFA2CD7  add XWA,0x00fccb6e   in P7Unit_LoadProgramStreams
;       0xFA2D8A  add XWA,0x00fccb6e   in P7Unit_SendParamValue
; ⚠ The citation addresses in the round-3 header (0xFA2C21, 0xFA2CD9, 0xFA2D8C) were each
; TWO BYTES PAST the instruction -- they named the imm32 inside `add <X..>,#imm32`
; (`e9 c8 <addr24> 00`), which is the defect class FINDINGS-prom_c-tail-data-zone.md §8
; records.  Corrected above.
; The fetched byte becomes P7Stream_StageAndSend's +0x22 argument and is stored to the
; global 0x00863E (0xF9F908), which sub_F9F9FA passes to sub_F9E0B7 at 0xF9FA15 beside the
; constant 0x0078.  So it is a per-unit selector inside the byte emitter.
; ⚠ NOT ESTABLISHED: what it selects.  Values 0, 1, 0 for units 0, 1, 2 -- the same
; pairing of units 0 and 1 that P7Unit_StreamPtrsByGroupAndUnit and P7Stream_Data_FD4B85
; both show -- but nothing here reads sub_F9E0B7's meaning, so it keeps its address.
; Evidence: the three reader sites 0xFA2C1F, 0xFA2CD7 and 0xFA2D8A, each an
;          `add <X..>,#imm32` whose index is the unit argument (XIZ+0x08).
; ----------------------------------------------------------------------------
unexplained_FCCB6E:
	.byte	0x00, 0x01, 0x00

; ----------------------------------------------------------------------------
; DSP_MixerGain_Curve_B -- 0xFCCB71..0xFCCD70  (512 bytes)
;
; 128 x u32, strictly monotonic, ending EXACTLY at 0x7FFFFF00 = digital full
; scale.  The wide-range curve of the pair: it spans 0x00002068 to 0x7FFFFF00,
; about 108 dB, with a steep bottom (ratio up to 3.16 per step) flattening to
; 1.017 per step at the top.
; ★ ELEMENT SIZE AND COUNT PROVEN BY THE CONSUMER at 0xFA30D8:
;       ld WA,0x0004 / muls XWA,(XIZ+0x08)   ; index * 4
;       add XWA,0x00FCCB71 / ld XWA,(XWA)    ; 32-bit load
;       sra 0x00,XWA                         ; used unshifted
;   and the same routine seeds a register with the literal 0x7FFFFF00, the value
;   this curve ends on.  The 128 entries are the space to its neighbour.
; WSA1-only: it matches none of the KN5000's five u32 ladders (best 32/512 bytes).
; ----------------------------------------------------------------------------
DSP_MixerGain_Curve_B:
	.long	0x00002068, 0x0000667e, 0x00014427, 0x0004012e
	.long	0x000caa46, 0x00280e26, 0x007eae30, 0x0190a508
	.long	0x04f31850, 0x05367a60, 0x057d71c0, 0x05c82f40
	.long	0x0616e648, 0x0669cce8, 0x06c11c28, 0x071d1000
	.long	0x077de7b0, 0x07e3e5c8, 0x084f5060, 0x08c07150
	.long	0x09379660, 0x09b51170, 0x0a3938d0, 0x0ac46750
	.long	0x0b56fc90, 0x0bf15d60, 0x0c93f3e0, 0x0d3f2fd0
	.long	0x0df386f0, 0x0eb17530, 0x0f797d20, 0x104c2840
	.long	0x112a0760, 0x11aa5980, 0x122e6b00, 0x12b657e0
	.long	0x13423ce0, 0x13d237c0, 0x14666700, 0x14feea20
	.long	0x159be180, 0x163d6e60, 0x16e3b300, 0x178ed2a0
	.long	0x183ef1a0, 0x18f43540, 0x19aec420, 0x1a6ec5a0
	.long	0x1b3462a0, 0x1bffc500, 0x1cd117e0, 0x1da887c0
	.long	0x1e864240, 0x1f6a7660, 0x20555480, 0x21470e80
	.long	0x223fd7c0, 0x233fe500, 0x24476c80, 0x2556a600
	.long	0x266dcb40, 0x278d1780, 0x28b4c780, 0x29e51a40
	.long	0x2b1e5000, 0x2bde9cc0, 0x2ca24300, 0x2d695200
	.long	0x2e33d8c0, 0x2f01e6c0, 0x2fd38b80, 0x30a8d740
	.long	0x3181da40, 0x325ea540, 0x333f48c0, 0x3423d640
	.long	0x350c5f00, 0x35f8f4c0, 0x36e9a9c0, 0x37de9040
	.long	0x38d7bb00, 0x39d53d00, 0x3ad72980, 0x3bdd9440
	.long	0x3ce89140, 0x3df83500, 0x3f0c9440, 0x4025c400
	.long	0x4143da00, 0x4266ec00, 0x438f1000, 0x44bc5c80
	.long	0x45eee900, 0x4726cc80, 0x48641f00, 0x49a6f880
	.long	0x4aef7200, 0x4c3da480, 0x4d91a980, 0x4eeb9b00
	.long	0x504b9300, 0x51b1ad00, 0x531e0400, 0x5490b400
	.long	0x5609d900, 0x57899000, 0x590ff680, 0x5a9d2a00
	.long	0x5c314900, 0x5dcc7200, 0x5f6ec500, 0x61186180
	.long	0x62c96800, 0x6481fa00, 0x66423880, 0x680a4680
	.long	0x69da4600, 0x6bb25b00, 0x6d92a980, 0x6f7b5600
	.long	0x716c8600, 0x73665f80, 0x75690900, 0x7774a980
	.long	0x79896980, 0x7ba77180, 0x7dceea80, 0x7fffff00

; ----------------------------------------------------------------------------
; DSP_MixerGain_Curve_A -- 0xFCCD71..0xFCCF70  (512 bytes)
;
; 128 x u32, strictly monotonic, also ending exactly at 0x7FFFFF00.  The narrow
; companion of curve B: 0x00451EB3..0x7FFFFF00, about 53.5 dB.
; ★ Same consumer, four instructions earlier (0xFA30C5):
;       ld WA,0x0004 / muls XWA,(XIZ+0x0a) / add XWA,0x00FCCD71 / ld XWA,(XWA)
;       ld XIX,XWA / sra 0x0f,XIX           ; >> 15
;   and the two looked-up values are then pushed together into 0xFCB0D3 -- a
;   two-stage product.  The `>> 15` is exactly what the sibling documents for its
;   copy of this curve (v142/subcpu/subcpu_data_tables.s:2926), which is byte-identical to this one
;   (kn5000 0x0131CF).  53.5 dB total span there and here.
; ----------------------------------------------------------------------------
DSP_MixerGain_Curve_A:
	.long	0x00451eb3, 0x004fa2d0, 0x005bc083, 0x0069b61b
	.long	0x0079cb66, 0x008c531b, 0x00a1ac88, 0x00ba457a
	.long	0x00d69c75, 0x00f7433a, 0x011ce1b8, 0x0148396a
	.long	0x017a293c, 0x01b3b204, 0x01f5fbac, 0x02425b20
	.long	0x029a5930, 0x02ffba6c, 0x0374883c, 0x03fb1b60
	.long	0x04962800, 0x0548cb88, 0x06169cc8, 0x0703be48
	.long	0x0814f3b0, 0x094fba20, 0x099c6990, 0x09eb9090
	.long	0x0a3d4370, 0x0a919720, 0x0ae8a150, 0x0b427850
	.long	0x0b9f3330, 0x0bfee9c0, 0x0c61b490, 0x0cc7ad00
	.long	0x0d30ed40, 0x0d9d9050, 0x0e0db210, 0x0e816f40
	.long	0x0ef8e5a0, 0x0f7433e0, 0x0ff379a0, 0x1076d780
	.long	0x10fe6f40, 0x118a63c0, 0x121ad8e0, 0x12aff3a0
	.long	0x1349da60, 0x13e8b4a0, 0x148cab20, 0x1535e7e0
	.long	0x15e49660, 0x1698e380, 0x1752fd80, 0x18131440
	.long	0x18d958e0, 0x19a5fe60, 0x1a793940, 0x1b533fc0
	.long	0x1c3449e0, 0x1d1c9160, 0x1e0c51c0, 0x1f03c8a0
	.long	0x20033580, 0x210ada00, 0x221af9c0, 0x2333da80
	.long	0x2455c480, 0x25810240, 0x26b5e040, 0x27f4ae00
	.long	0x293dbd40, 0x2a916280, 0x2beff500, 0x2d59cec0
	.long	0x2ecf4c80, 0x3050ce40, 0x31deb6c0, 0x33796c40
	.long	0x35215840, 0x36d6e780, 0x389a8a40, 0x3a6cb480
	.long	0x3c4dde00, 0x3e3e8240, 0x403f2080, 0x42503c80
	.long	0x44725e00, 0x46a61180, 0x48ebe700, 0x4b447480
	.long	0x4db05400, 0x50302480, 0x52c48a00, 0x556e2e80
	.long	0x582dc080, 0x5b03f500, 0x5df18600, 0x60f73480
	.long	0x6415c680, 0x674e0980, 0x6aa0d080, 0x6e0ef680
	.long	0x6f45d380, 0x70801e80, 0x71bde180, 0x72ff2600
	.long	0x7443f600, 0x758c5b80, 0x76d86080, 0x78280f00
	.long	0x797b7200, 0x7ad29380, 0x7c2d7e00, 0x7d8c3c80
	.long	0x7dc01680, 0x7df40580, 0x7e280a00, 0x7e5c2400
	.long	0x7e905380, 0x7ec49880, 0x7ef8f380, 0x7f2d6400
	.long	0x7f61ea00, 0x7f968600, 0x7fcb3780, 0x7fffff00

; ----------------------------------------------------------------------------
; DescriptorStrings -- 0xFCCF71..0xFCD0F6  (390 bytes)
;
; A pool of 44 NUL-terminated ASCII strings in two interleaved families:
;   * FIELD-TYPE strings over the alphabet {b, w, v, s, h, c, B} -- 'bbbvb',
;     'bwwbbv', 'wwcbbbbbv', ... ;
;   * INDEX strings '0', '01234', '0123456789abc' -- a run of consecutive
;     base-36 digits whose length matches the type string it is paired with.
; The pairing is not a guess: the pointer records at 0xFDBFE9 onward load the two
; members of a pair four bytes apart (0xFDBFE9 -> 'bbbvb'-family, 0xFDBFED ->
; the digit string), and 0xFCCF77 alone is loaded 21 times.
; ★ THOSE RECORDS ARE NOW A NAMED OBJECT: `PoolDir_Records`, 56 records of 25 bytes
; at 0xFDBFD9, whose stride is the instruction operand `mul A,0x19` at 0xFA2B44.
; 0xFDBFE9 and 0xFDBFED are its fields +16 and +20 -- so "four bytes apart" was the
; record layout showing through.
; [INFERENCE, stated as such] this is a field-layout descriptor: one letter per
; field giving its width or kind, and the digit string giving each field an index.
; ★ THE LETTERS ARE DECODED FROM THEIR READER (2026-09-25, lane promcd; notes/lanes/promcd-2026-09-25/p7_descriptor_letters.py).
; P7Unit_EmitChangedParams walks a record's type string and digit string in lockstep
; and reads each field of the unit block by its letter (switch at 0xFA4735):
;     'b'  one byte                          'B'  one byte, sign-extended
;     'w'  two bytes, little-endian          'c'  two bytes, BIG-endian
;     'h'  one byte, plus 0x500              any other letter ('v', 's')  one byte
; and the digit, through Base36DigitToValue (0xFA4764), is the field index.  Every digit
; string is '0123...' of its type string's length (56/56), and in the 51 records that
; walker handles every field descriptor's +4 byte offset lies inside the span the letters
; give its index (390/390) -- the widths are confirmed by a second table.  'v' occurs
; exactly once in every record (56/56); 's' only in records 12 and 13 (PEDAL WAH, AUTO
; WAH), which the walker hands to hand-coded paths, so what 'v' and 's' select beyond a
; one-byte width is still open.  (Corrected: the two lines that stood here said the
; letters' individual meaning was unproven and byte/word only the obvious reading.)
; ----------------------------------------------------------------------------
DescriptorStrings:
	.asciz	"bbbvb"	; [ 0] 0xFCCF71
; Pool element at 0xFCCF77: "01234", 5 characters, an INDEX (digit) string. Pointed at by 21
; .long words in PoolDir_Records (x21): PoolDir_Records[0] +20 'DISTORTION',
; PoolDir_Records[1] +20 'OVERDRIVE', PoolDir_Records[2] +20 'FUZZ', PoolDir_Records[5] +20
; 'CHORUS', PoolDir_Records[13] +20 'AUTO WAH', PoolDir_Records[15] +20 'RING MODULATOR',
; PoolDir_Records[17] +20 'SLOW ATTACKER', PoolDir_Records[20] +20 'ENSEMBLE',
; PoolDir_Records[21] +20 'COMPRESSOR', PoolDir_Records[26] +20 'ROOM REVERB 1',
; PoolDir_Records[27] +20 'ROOM REVERB 2', PoolDir_Records[28] +20 'PLATE REVERB 1',
; PoolDir_Records[29] +20 'PLATE REVERB 2', PoolDir_Records[30] +20 'CONCERT REVERB 1',
; PoolDir_Records[31] +20 'CONCERT REVERB 2', PoolDir_Records[32] +20 'DARK REVERB 1',
; PoolDir_Records[33] +20 'DARK REVERB 2', PoolDir_Records[34] +20 'BRIGHT REVERB 1',
; PoolDir_Records[35] +20 'BRIGHT REVERB 2', PoolDir_Records[36] +20 'WAVE REVERB 1',
; PoolDir_Records[37] +20 'WAVE REVERB 2'.
DescStr_01234:
	.asciz	"01234"	; [ 1] 0xFCCF77
; Pool element at 0xFCCF7D: "bbbwbvb", 7 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[3] +16 'EXCITER'.
DescStr_bbbwbvb:
	.asciz	"bbbwbvb"	; [ 2] 0xFCCF7D
; Pool element at 0xFCCF85: "0123456", 7 characters, an INDEX (digit) string. Pointed at by
; 7 .long words in PoolDir_Records (x7): PoolDir_Records[3] +20 'EXCITER',
; PoolDir_Records[4] +20 'PARAMETRIC EQ', PoolDir_Records[6] +20 'MODULATED CHORUS',
; PoolDir_Records[7] +20 'ENHANCER', PoolDir_Records[23] +20 'SINGLE DELAY',
; PoolDir_Records[44] +20 'PEQ+CHORUS', PoolDir_Records[54] +20 'PITCH SHIFTER'.
DescStr_0123456:
	.asciz	"0123456"	; [ 3] 0xFCCF85
; Pool element at 0xFCCF8D: "wwwwwwv", 7 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[4] +16 'PARAMETRIC EQ'.
DescStr_wwwwwwv:
	.asciz	"wwwwwwv"	; [ 4] 0xFCCF8D
; Pool element at 0xFCCF95: "bbbbv", 5 characters, a field-TYPE string. Pointed at by 4
; .long words in PoolDir_Records (x4): PoolDir_Records[5] +16 'CHORUS', PoolDir_Records[15]
; +16 'RING MODULATOR', PoolDir_Records[17] +16 'SLOW ATTACKER', PoolDir_Records[20] +16
; 'ENSEMBLE'.
DescStr_bbbbv:
	.asciz	"bbbbv"	; [ 5] 0xFCCF95
; Pool element at 0xFCCF9B: "bbbbbbv", 7 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[6] +16 'MODULATED CHORUS'.
DescStr_bbbbbbv:
	.asciz	"bbbbbbv"	; [ 6] 0xFCCF9B
; Pool element at 0xFCCFA3: "bbbbwwv", 7 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[7] +16 'ENHANCER'.
DescStr_bbbbwwv:
	.asciz	"bbbbwwv"	; [ 7] 0xFCCFA3
; Pool element at 0xFCCFAB: "bbbbbbbv", 8 characters, a field-TYPE string. Pointed at by 3
; .long words in PoolDir_Records (x3): PoolDir_Records[8] +16 'FLANGER', PoolDir_Records[9]
; +16 'PHASER', PoolDir_Records[22] +16 'MIX UP'.
DescStr_bbbbbbbv:
	.asciz	"bbbbbbbv"	; [ 8] 0xFCCFAB
; Pool element at 0xFCCFB4: "01234567", 8 characters, an INDEX (digit) string. Pointed at by
; 7 .long words in PoolDir_Records (x7): PoolDir_Records[8] +20 'FLANGER',
; PoolDir_Records[9] +20 'PHASER', PoolDir_Records[22] +20 'MIX UP', PoolDir_Records[25] +20
; 'MANUAL DELAY', PoolDir_Records[45] +20 'PEQ+S.DELAY', PoolDir_Records[47] +20
; 'PEQ+VIBRATO', PoolDir_Records[50] +20 'PEQ+COMPR+OVERDR'.
DescStr_01234567:
	.asciz	"01234567"	; [ 9] 0xFCCFB4
; Pool element at 0xFCCFBD: "bbbbbv", 6 characters, a field-TYPE string. Pointed at by 2
; .long words in PoolDir_Records (x2): PoolDir_Records[10] +16 'AUTO PAN',
; PoolDir_Records[11] +16 'VIBRATO'.
DescStr_bbbbbv:
	.asciz	"bbbbbv"	; [10] 0xFCCFBD
; Pool element at 0xFCCFC4: "012345", 6 characters, an INDEX (digit) string. Pointed at by 6
; .long words in PoolDir_Records (x6): PoolDir_Records[10] +20 'AUTO PAN',
; PoolDir_Records[11] +20 'VIBRATO', PoolDir_Records[12] +20 'PEDAL WAH',
; PoolDir_Records[18] +20 'GATED REVERB', PoolDir_Records[19] +20 'HAAS EFFECT',
; PoolDir_Records[48] +20 'PEQ+COMPRESSOR'.
DescStr_012345:
	.asciz	"012345"	; [11] 0xFCCFC4
; Pool element at 0xFCCFCB: "bsssbv", 6 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[12] +16 'PEDAL WAH'.
DescStr_bsssbv:
	.asciz	"bsssbv"	; [12] 0xFCCFCB
; Pool element at 0xFCCFD2: "bsssv", 5 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[13] +16 'AUTO WAH'.
DescStr_bsssv:
	.asciz	"bsssv"	; [13] 0xFCCFD2
; Pool element at 0xFCCFD8: "bbbbbbbbbvb", 11 characters, a field-TYPE string. Pointed at by
; 1 .long word in PoolDir_Records (x1): PoolDir_Records[14] +16 'ROTARY SPEAKER'.
DescStr_bbbbbbbbbvb:
	.asciz	"bbbbbbbbbvb"	; [14] 0xFCCFD8
; Pool element at 0xFCCFE4: "0123456789a", 11 characters, an INDEX (digit) string. Pointed
; at by 6 .long words in PoolDir_Records (x6): PoolDir_Records[14] +20 'ROTARY SPEAKER',
; PoolDir_Records[39] +20 'S.DELAY+S.DELAY', PoolDir_Records[41] +20 'S.DELAY+VIBRATO',
; PoolDir_Records[51] +20 'PEQ+DIST+DELAY', PoolDir_Records[52] +20 'PEQ+OVERDR+DELAY',
; PoolDir_Records[55] +20 'PEDAL WAH+DELAY'.
DescStr_0123456789a:
	.asciz	"0123456789a"	; [15] 0xFCCFE4
; Pool element at 0xFCCFF0: "v", 1 characters, a field-TYPE string. Pointed at by 2 .long
; words in PoolDir_Records (x2): PoolDir_Records[16] +16 'NOISE GENERATOR',
; PoolDir_Records[53] +16 'NO OPERATION'.
DescStr_v:
	.asciz	"v"	; [16] 0xFCCFF0
; Pool element at 0xFCCFF2: "0", 1 characters, an INDEX (digit) string. Pointed at by 2
; .long words in PoolDir_Records (x2): PoolDir_Records[16] +20 'NOISE GENERATOR',
; PoolDir_Records[53] +20 'NO OPERATION'.
DescStr_0:
	.asciz	"0"	; [17] 0xFCCFF2
; Pool element at 0xFCCFF4: "bbhbbv", 6 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[18] +16 'GATED REVERB'.
DescStr_bbhbbv:
	.asciz	"bbhbbv"	; [18] 0xFCCFF4
; Pool element at 0xFCCFFB: "bwwbbv", 6 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[19] +16 'HAAS EFFECT'.
DescStr_bwwbbv:
	.asciz	"bwwbbv"	; [19] 0xFCCFFB
; Pool element at 0xFCD002: "bcbbv", 5 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[21] +16 'COMPRESSOR'.
DescStr_bcbbv:
	.asciz	"bcbbv"	; [20] 0xFCD002
; Pool element at 0xFCD008: "bwwbbbv", 7 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[23] +16 'SINGLE DELAY'.
DescStr_bwwbbbv:
	.asciz	"bwwbbbv"	; [21] 0xFCD008
; Pool element at 0xFCD010: "bwwwwbbbbbbv", 12 characters, a field-TYPE string. Pointed at
; by 1 .long word in PoolDir_Records (x1): PoolDir_Records[24] +16 'MULTI TAP DELAY'.
DescStr_bwwwwbbbbbbv:
	.asciz	"bwwwwbbbbbbv"	; [22] 0xFCD010
; Pool element at 0xFCD01D: "0123456789ab", 12 characters, an INDEX (digit) string. Pointed
; at by 1 .long word in PoolDir_Records (x1): PoolDir_Records[24] +20 'MULTI TAP DELAY'.
DescStr_0123456789ab:
	.asciz	"0123456789ab"	; [23] 0xFCD01D
; Pool element at 0xFCD02A: "bbwwBBbv", 8 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[25] +16 'MANUAL DELAY'.
DescStr_bbwwBBbv:
	.asciz	"bbwwBBbv"	; [24] 0xFCD02A
; Pool element at 0xFCD033: "bbhbv", 5 characters, a field-TYPE string. Pointed at by 12
; .long words in PoolDir_Records (x12): PoolDir_Records[26] +16 'ROOM REVERB 1',
; PoolDir_Records[27] +16 'ROOM REVERB 2', PoolDir_Records[28] +16 'PLATE REVERB 1',
; PoolDir_Records[29] +16 'PLATE REVERB 2', PoolDir_Records[30] +16 'CONCERT REVERB 1',
; PoolDir_Records[31] +16 'CONCERT REVERB 2', PoolDir_Records[32] +16 'DARK REVERB 1',
; PoolDir_Records[33] +16 'DARK REVERB 2', PoolDir_Records[34] +16 'BRIGHT REVERB 1',
; PoolDir_Records[35] +16 'BRIGHT REVERB 2', PoolDir_Records[36] +16 'WAVE REVERB 1',
; PoolDir_Records[37] +16 'WAVE REVERB 2'.
DescStr_bbhbv:
	.asciz	"bbhbv"	; [25] 0xFCD033
; Pool element at 0xFCD039: "bwwbbbbbbv", 10 characters, a field-TYPE string. Pointed at by
; 1 .long word in PoolDir_Records (x1): PoolDir_Records[38] +16 'S.DELAY+CHORUS'.
DescStr_bwwbbbbbbv:
	.asciz	"bwwbbbbbbv"	; [26] 0xFCD039
; Pool element at 0xFCD044: "0123456789", 10 characters, an INDEX (digit) string. Pointed at
; by 3 .long words in PoolDir_Records (x3): PoolDir_Records[38] +20 'S.DELAY+CHORUS',
; PoolDir_Records[43] +20 'AUTO WAH+S.DELAY', PoolDir_Records[46] +20 'PEQ+FLANGER'.
DescStr_0123456789:
	.asciz	"0123456789"	; [27] 0xFCD044
; Pool element at 0xFCD04F: "bwwbbbwwbbv", 11 characters, a field-TYPE string. Pointed at by
; 1 .long word in PoolDir_Records (x1): PoolDir_Records[39] +16 'S.DELAY+S.DELAY'.
DescStr_bwwbbbwwbbv:
	.asciz	"bwwbbbwwbbv"	; [28] 0xFCD04F
; Pool element at 0xFCD05B: "bwwbbbbbbbbbv", 13 characters, a field-TYPE string. Pointed at
; by 2 .long words in PoolDir_Records (x2): PoolDir_Records[40] +16 'S.DELAY+FLANGER',
; PoolDir_Records[42] +16 'S.DELAY+PHASER'.
DescStr_bwwbbbbbbbbbv:
	.asciz	"bwwbbbbbbbbbv"	; [29] 0xFCD05B
; Pool element at 0xFCD069: "0123456789abc", 13 characters, an INDEX (digit) string. Pointed
; at by 2 .long words in PoolDir_Records (x2): PoolDir_Records[40] +20 'S.DELAY+FLANGER',
; PoolDir_Records[42] +20 'S.DELAY+PHASER'.
DescStr_0123456789abc:
	.asciz	"0123456789abc"	; [30] 0xFCD069
; Pool element at 0xFCD077: "bwwbbbbbbbv", 11 characters, a field-TYPE string. Pointed at by
; 1 .long word in PoolDir_Records (x1): PoolDir_Records[41] +16 'S.DELAY+VIBRATO'.
DescStr_bwwbbbbbbbv:
	.asciz	"bwwbbbbbbbv"	; [31] 0xFCD077
; Pool element at 0xFCD083: "bbbbbwwbbv", 10 characters, a field-TYPE string. Pointed at by
; 1 .long word in PoolDir_Records (x1): PoolDir_Records[43] +16 'AUTO WAH+S.DELAY'.
DescStr_bbbbbwwbbv:
	.asciz	"bbbbbwwbbv"	; [32] 0xFCD083
; Pool element at 0xFCD08E: "wwbbbbv", 7 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[44] +16 'PEQ+CHORUS'.
DescStr_wwbbbbv:
	.asciz	"wwbbbbv"	; [33] 0xFCD08E
; Pool element at 0xFCD096: "wwbwwbbv", 8 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[45] +16 'PEQ+S.DELAY'.
DescStr_wwbwwbbv:
	.asciz	"wwbwwbbv"	; [34] 0xFCD096
; Pool element at 0xFCD09F: "wwbbbbbbbv", 10 characters, a field-TYPE string. Pointed at by
; 1 .long word in PoolDir_Records (x1): PoolDir_Records[46] +16 'PEQ+FLANGER'.
DescStr_wwbbbbbbbv:
	.asciz	"wwbbbbbbbv"	; [35] 0xFCD09F
; Pool element at 0xFCD0AA: "wwbbbbbv", 8 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[47] +16 'PEQ+VIBRATO'.
DescStr_wwbbbbbv:
	.asciz	"wwbbbbbv"	; [36] 0xFCD0AA
; Pool element at 0xFCD0B3: "wwcbbv", 6 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[48] +16 'PEQ+COMPRESSOR'.
DescStr_wwcbbv:
	.asciz	"wwcbbv"	; [37] 0xFCD0B3
; Pool element at 0xFCD0BA: "wwcbbbbbv", 9 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[49] +16 'PEQ+COMPR+DIST'.
DescStr_wwcbbbbbv:
	.asciz	"wwcbbbbbv"	; [38] 0xFCD0BA
; Pool element at 0xFCD0C4: "012345678", 9 characters, an INDEX (digit) string. Pointed at
; by 1 .long word in PoolDir_Records (x1): PoolDir_Records[49] +20 'PEQ+COMPR+DIST'.
DescStr_012345678:
	.asciz	"012345678"	; [39] 0xFCD0C4
; Pool element at 0xFCD0CE: "wcbbbbvb", 8 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[50] +16 'PEQ+COMPR+OVERDR'.
DescStr_wcbbbbvb:
	.asciz	"wcbbbbvb"	; [40] 0xFCD0CE
; Pool element at 0xFCD0D7: "wwbbbwwbbvb", 11 characters, a field-TYPE string. Pointed at by
; 2 .long words in PoolDir_Records (x2): PoolDir_Records[51] +16 'PEQ+DIST+DELAY',
; PoolDir_Records[52] +16 'PEQ+OVERDR+DELAY'.
DescStr_wwbbbwwbbvb:
	.asciz	"wwbbbwwbbvb"	; [41] 0xFCD0D7
; Pool element at 0xFCD0E3: "bBBbBvb", 7 characters, a field-TYPE string. Pointed at by 1
; .long word in PoolDir_Records (x1): PoolDir_Records[54] +16 'PITCH SHIFTER'.
DescStr_bBBbBvb:
	.asciz	"bBBbBvb"	; [42] 0xFCD0E3
; Pool element at 0xFCD0EB: "bbbbbbwwbbv", 11 characters, a field-TYPE string. Pointed at by
; 1 .long word in PoolDir_Records (x1): PoolDir_Records[55] +16 'PEDAL WAH+DELAY'.
DescStr_bbbbbbwwbbv:
	.asciz	"bbbbbbwwbbv"	; [43] 0xFCD0EB



