#!/usr/bin/env python3
"""Which KN5000 sub-CPU routine names apply to WSA1 addresses, by byte identity?

Question answered: 28,916 bytes of WSA1 prom_c are byte-identical to runs of the KN5000
sub-CPU payload (kn5000_shared_runs.py; shuffle null 0 B). The sibling project
../kn5000-roms-disasm has 4,790 named labels for that payload. This maps them across, so
routines that are literally the same code carry the same name in both trees instead of
being re-derived from scratch.

The payload is linked at 0x0400, so payload file offset X is KN5000 sub-CPU address
0x400+X. A label at address L inside a shared run [poff, poff+len) transplants to
wsa1_addr = run_base + (L - 0x400 - poff).

⚠ WHAT THIS DOES AND DOES NOT ESTABLISH.

  It establishes: these bytes are the same instructions, so whatever the KN5000 routine
  DOES, the WSA1 routine does too. That is a strong claim and it is what makes the name
  meaningful.

  It does NOT establish: that the surrounding machine is the same. A shared routine may be
  called with different arguments, wired to different peripherals, or be dead code in one
  of the two. Every transplanted name is therefore emitted with the run length that backs
  it, and names landing in runs shorter than MIN_RUN are withheld -- a 16-byte match is a
  common idiom, not an identification.

  It also does NOT rename anything by itself. Output is a proposal file; a human or a
  later pass applies it, and the byte gate is blind to whether a NAME is right (it only
  sees bytes), so a wrong name here would never be caught by the build.

Run:  python3 scripts/analysis/transplant_kn5000_labels.py [--min-run N] [--out FILE]
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SIB = "/home/fsanches/compartilhado/kn5000-roms-disasm"
ELF = os.path.join(SIB, "rebuilt_ROMs", "kn5000_subprogram_v142.llvm.elf")
NM = "/home/fsanches/compartilhado/llvm-project/build/bin/llvm-nm"
PAYLOAD_BASE = 0x0400
MIN_RUN = 48


def payload_symbols():
    out = subprocess.run([NM, "--numeric-sort", "--defined-only", ELF],
                         capture_output=True, text=True).stdout
    syms = []
    for line in out.splitlines():
        parts = line.split()
        if len(parts) != 3:
            continue
        addr, typ, name = parts
        if typ.lower() == 'a':          # absolute = SFR equates, not payload code
            continue
        if name.startswith('.L') or name.startswith('$'):
            continue
        syms.append((int(addr, 16), name))
    return sorted(syms)


def main():
    min_run = MIN_RUN
    if "--min-run" in sys.argv:
        min_run = int(sys.argv[sys.argv.index("--min-run") + 1])
    out_path = os.path.join(ROOT, "notes", "kn5000-label-transplant.md")
    if "--out" in sys.argv:
        out_path = sys.argv[sys.argv.index("--out") + 1]

    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import kn5000_shared_runs as ksr

    payload = open(ksr.PAYLOAD, "rb").read()
    idx = ksr.index(payload, 16)
    syms = payload_symbols()
    print(f"payload symbols usable: {len(syms)}")

    rows = []
    for name, fn, base in ksr.IMAGES:
        buf = open(os.path.join(ROOT, "original_ROMs", fn), "rb").read()
        for off, poff, L in ksr.find_runs(buf, idx, 16):
            if L < min_run or ksr.low_entropy(buf[off:off + L]):
                continue
            lo, hi = PAYLOAD_BASE + poff, PAYLOAD_BASE + poff + L
            for addr, sym in syms:
                if lo <= addr < hi:
                    rows.append((name, base + off + (addr - lo), sym, L, addr))

    rows.sort(key=lambda r: (-r[3], r[1]))
    with open(out_path, "w") as f:
        f.write("# KN5000 sub-CPU labels that transplant onto WSA1 addresses\n\n")
        f.write("Generated by `scripts/analysis/transplant_kn5000_labels.py`. "
                "Read that script's docstring before applying any of these -- in particular, "
                "byte identity establishes that the code is the same, not that the surrounding "
                "machine is.\n\n")
        f.write(f"Runs shorter than {min_run} bytes are withheld; a short match is an idiom, "
                "not an identification.\n\n")
        f.write(f"**{len(rows)} proposals**, longest-backing-run first.\n\n")
        f.write("| WSA1 image | WSA1 addr | proposed name | run len | KN5000 subcpu addr |\n")
        f.write("|---|---|---|---:|---|\n")
        for img, waddr, sym, L, kaddr in rows:
            f.write(f"| {img} | `0x{waddr:06X}` | `{sym}` | {L} | `0x{kaddr:04X}` |\n")
    print(f"wrote {out_path}: {len(rows)} proposals")
    for img, waddr, sym, L, kaddr in rows[:20]:
        print(f"  {img:7s} 0x{waddr:06X}  {sym:<44s} run={L:5d}")


if __name__ == "__main__":
    main()
