#!/usr/bin/env python3
r"""Replace NUMERIC ROM-address operands in wsa1/prom_b with the label already AT that address.

QUESTION THIS ANSWERS / JOB IT DOES
-----------------------------------
After scripts/converters/symbolize_numeric_branches.py (2026-09-25) prom_b still
held ~9,950 operands whose value is a CPU-1 ROM address (0xF00000-0xFFFFFF)
spelled as a number: `.long 0x00F0028D` in pointer tables, `ld xwa, 15728869`,
`lda xiy, (15731935:24)`, `add xbc, 15729324`, and the `jp 0xF83171` /
`call 16629032` sites that land in prom_a -- which the branch tool refuses
because prom_a is a separately linked image (it even reports those targets as
`mid-line-code`; see notes/promb-2026-09-25/FINDINGS-promb-2026-09-25.md).

This tool does ONE conservative thing: where the value is EXACTLY the address
of a label that already exists, it writes the label instead of the number.  It
creates no label and makes no claim about what the target is beyond what the
existing label already says.

  * value in prom_b (0xF00000-0xF7FFFF): the label comes from prom_b's own
    linked ELF.  The assembler/linker resolve it, so a wrong choice changes the
    bytes and the gate goes red: THE BYTE GATE PROTECTS THIS EDIT.
  * value in prom_a (0xF80000-0xFFFFFF): prom_a is linked separately, so prom_b
    cannot reference its labels.  The tool writes one GENERATED block of
    `.set <prom_a label>, <address>` equates into wsa1_prom_b.s (between the
    markers below) and uses those names.  The byte gate protects the VALUE of
    each equate (it is encoded in the operand); it does NOT protect the NAME --
    if prom_a later renames a label, the equate here keeps the old name.
    `--check-equates` re-reads prom_a's ELF and lists every equate whose name
    no longer labels that address: run it after any prom_a rename.
    Names prom_b also defines itself (the shared routines carried in both
    images) are never used, so an equate cannot shadow a prom_b label.

WHICH SITES, AND THE GUARD ON CODE
  `.long N`                           data; replaced whenever N is a label address
  `jp N` / `call N` (absolute)        } code: replaced only when a SECOND decoder
  `ld xRR, N` / `add xRR, N`          } (MAME unidasm, linear over the dump) sees an
  `lda xRR, (N:24)`                   } instruction START at the line's address whose
                                        last operand is N -- the symboliser's R5
                                        rule.  A phantom "instruction" made of another
                                        instruction's or a table's bytes does not get
                                        a symbolic operand that would dignify it.
  EXCEPTION: a 4-byte-aligned `jp` in the routine directory 0xF40000-0xF44017
  whose ROM byte is 0x1B is accepted without the second decoder -- that table
  is a directory of `jp imm24` slots (notes/FINDINGS-prom_b-thunk-table.md) and
  unidasm's linear sweep desynchronises after the `.long` slots mixed into it.
  Macro operands (`m_jp_cc MD24, N, cc`) are left alone: the macros split the
  address into `.byte` fields and a relocatable symbol cannot be masked that way.
  A value that is NOT a label address (e.g. `add XBC, TABLE - 4*k`, the dispatch
  idiom notes/lanes/BRIEF-2026-09-01.md describes) is left numeric.

WHICH LABEL, when several share an address: a descriptive name beats a
  structural one (`_Skip`/`_Join`/...), which beats an address-derived one
  (`Data_F12345`, `sub_F12345`); ties go to the name defined first in the file.

RUN
    python3 scripts/converters/symbolize_wsa1_rom_addresses.py                 # dry run
    python3 scripts/converters/symbolize_wsa1_rom_addresses.py --apply --verify
    python3 scripts/converters/symbolize_wsa1_rom_addresses.py --check-equates
    python3 scripts/converters/symbolize_wsa1_rom_addresses.py --report out.json
Always follow an --apply with the real gate: `make gate-wsa1`.
"""
import argparse
import bisect
import collections
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "scripts", "analysis"))
sys.path.insert(0, HERE)
import data_range_census as drc                 # noqa: E402
import symbolize_numeric_branches as snb        # noqa: E402

WSA1 = os.path.join(ROOT, "wsa1")
REL = "prom_b/wsa1_prom_b.s"
PATH = os.path.join(WSA1, REL)
BEGIN = "; >>> BEGIN prom_a ADDRESS EQUATES (generated by scripts/converters/symbolize_wsa1_rom_addresses.py)"
END = "; <<< END prom_a ADDRESS EQUATES"
ANCHOR = '\t.include "include/tlcs900_mem_ops.inc"\n'
STRUCT = re.compile(r'_(Skip|Join|Loop|Sub|Return|Epilogue|Entry|Helper)\d*$')
NUMTOK = r'(0x[0-9a-fA-F]+|\d+)'
# (kind, regex over the CODE part after any leading labels); group 'num' is the operand
FORMS = [
    ("long", re.compile(r'^(?P<pre>\.long\s+)' + NUMTOK.replace('(', '(?P<num>', 1) + r'(?P<post>\s*)$')),
    ("jp", re.compile(r'^(?P<pre>jp\s+)' + NUMTOK.replace('(', '(?P<num>', 1) + r'(?P<post>\s*)$')),
    ("call", re.compile(r'^(?P<pre>call\s+)' + NUMTOK.replace('(', '(?P<num>', 1) + r'(?P<post>\s*)$')),
    ("ld", re.compile(r'^(?P<pre>ld\s+x(?:wa|bc|de|hl|ix|iy|iz|sp)\s*,\s*)' + NUMTOK.replace('(', '(?P<num>', 1) + r'(?P<post>\s*)$')),
    ("add", re.compile(r'^(?P<pre>add\s+x(?:wa|bc|de|hl|ix|iy|iz|sp)\s*,\s*)' + NUMTOK.replace('(', '(?P<num>', 1) + r'(?P<post>\s*)$')),
    ("lda", re.compile(r'^(?P<pre>lda\s+x(?:wa|bc|de|hl|ix|iy|iz|sp)\s*,\s*\(\s*)' + NUMTOK.replace('(', '(?P<num>', 1) + r'(?P<post>\s*:\s*24\s*\)\s*)$')),
]
CODE_KINDS = {"jp", "call", "ld", "add", "lda"}
THUNK_LO, THUNK_HI = 0xF40000, 0xF44018      # the routine directory's extent


def sh(cmd, **kw):
    r = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if r.returncode != 0:
        sys.exit("FAILED: %s\n%s" % (" ".join(cmd), r.stderr[-3000:]))
    return r.stdout


def elf_labels(elf):
    """-> {addr: [names in nm order]} for .text symbols, and the set of all names."""
    out = collections.defaultdict(list)
    names = set()
    for ln in sh([drc.NM, "--defined-only", "-n", elf]).split("\n"):
        p = ln.split()
        if len(p) != 3:
            continue
        names.add(p[2])
        if p[1] not in ("t", "T"):
            continue
        if p[2].startswith((".L", "__", drc.MARK)):
            continue
        out[int(p[0], 16)].append(p[2])
    return out, names


def rank(name, order):
    if re.search(r'[0-9A-Fa-f]{6}', name):
        r = 3 if name.startswith("sub_") else 2
    elif STRUCT.search(name):
        r = 1
    else:
        r = 0
    return (r, order.get(name, 1 << 30))


def split_code(text):
    """-> (leading-labels text, code text, trailing text incl. comment)."""
    q, cut = None, len(text)
    for i, ch in enumerate(text):
        if q:
            if ch == q:
                q = None
            continue
        if ch in "\"'":
            q = ch
        elif ch == ";":
            cut = i
            break
    body, tail = text[:cut], text[cut:]
    stripped = body.rstrip()
    tail = body[len(stripped):] + tail
    lead = ""
    rest = stripped
    while True:
        m = re.match(r'^(\s*[A-Za-z_.$][\w.$@]*:\s*)', rest)
        if not m:
            break
        lead += m.group(1)
        rest = rest[m.end():]
    ws = re.match(r'^\s*', rest).group(0)
    return lead + ws, rest[len(ws):], tail


def analyse():
    img = snb.image_by_key("prom_b")
    sh(["make", "-C", WSA1, "rebuilt_ROMs/wsa1_prom_a.llvm.elf", "rebuilt_ROMs/wsa1_prom_b.llvm.elf"])
    b_lab, b_names = elf_labels(os.path.join(WSA1, "rebuilt_ROMs/wsa1_prom_b.llvm.elf"))
    a_lab, _ = elf_labels(os.path.join(WSA1, "rebuilt_ROMs/wsa1_prom_a.llvm.elf"))
    marks, addrs, spans, rom_ok, src, macros = snb.build_map(img, WSA1)
    if not rom_ok:
        sys.exit("prom_b mirror is not byte-identical to the dump -- refusing")
    line_addr = {}
    for (a, end, rel, li) in spans:
        if rel == REL:
            line_addr[li] = a
    uni = snb.independent_decode(img)
    rom = open(os.path.join(ROOT, img["rom"]), "rb").read()
    lines = src.lines(REL)
    # definition order of labels in the file, for tie-breaks
    order = {}
    for i, t in enumerate(lines):
        m = drc.LABEL_RE.match(t.strip())
        if m and m.group(1) not in order:
            order[m.group(1)] = i
    # equates currently in the generated block (their names must not be re-counted as prom_b's)
    eq_now = {}
    inblk = False
    for t in lines:
        if t.startswith(BEGIN):
            inblk = True
        elif t.startswith(END):
            inblk = False
        elif inblk:
            m = re.match(r'^\s*\.set\s+([\w.$@]+)\s*,\s*(0x[0-9a-fA-F]+)', t)
            if m:
                eq_now[m.group(1)] = int(m.group(2), 16)
    own_names = b_names - set(eq_now)
    stats = collections.Counter()
    edits, used_a = {}, {}
    rows = []
    for li, t in enumerate(lines):
        lead, code, tail = split_code(t)
        if not code:
            continue
        low = code.lower()
        for kind, rx in FORMS:
            m = rx.match(low)
            if not m:
                continue
            num = m.group("num")
            v = int(num, 16) if num.startswith("0x") else int(num)
            if not (0xF00000 <= v <= 0xFFFFFF):
                break
            side = "b" if v < 0xF80000 else "a"
            key = "%s->%s" % (kind, side)
            stats["seen " + key] += 1
            if kind in CODE_KINDS:
                at = line_addr.get(li)
                d = uni.get(at) if at is not None else None
                ok = False
                if d and d[0] == kind:
                    last = d[1].split(",")[-1].strip().strip("()").split(":")[0]
                    try:
                        ok = int(last, 16) == v
                    except ValueError:
                        ok = False
                if (not ok and kind == "jp" and at is not None and THUNK_LO <= at < THUNK_HI
                        and at % 4 == 0 and rom[at - 0xF00000] == 0x1B):
                    # the routine directory: 4-byte-aligned `jp imm24` slots
                    # (notes/FINDINGS-prom_b-thunk-table.md).  unidasm's linear sweep
                    # desynchronises after the `.long` slots the table also holds.
                    ok = True
                    stats["thunk-slot accepted " + key] += 1
                if not ok:
                    stats["refused-R5 " + key] += 1
                    rows.append(dict(line=li + 1, kind=key, value="0x%06X" % v, why="second decoder disagrees"))
                    break
            if side == "b":
                cands = b_lab.get(v, [])
            else:
                cands = [n for n in a_lab.get(v, []) if n not in own_names]
            if not cands:
                stats["no-label " + key] += 1
                rows.append(dict(line=li + 1, kind=key, value="0x%06X" % v, why="no label at that address"))
                break
            name = sorted(cands, key=lambda n: rank(n, order))[0]
            if side == "a":
                used_a[name] = v
            # rewrite the ORIGINAL-case code: same span as the lowercase match
            s, e = m.span("num")
            newcode = code[:s] + name + code[e:]
            edits[li] = lead + newcode + tail
            stats["convert " + key] += 1
            break
    return dict(img=img, src=src, lines=lines, edits=edits, used_a=used_a, eq_now=eq_now,
                stats=stats, rows=rows, a_lab=a_lab)


def equate_block(used_a, a_lab):
    out = [BEGIN,
           "; prom_a is linked separately, so prom_b cannot name its labels directly.  Each",
           "; line below is a prom_a label and the address prom_a's own ELF gives it; prom_b's",
           "; `jp`/`call`/`.long` operands into prom_a use these names instead of numbers.",
           "; The byte gate protects every VALUE (it is encoded in the operand that uses it);",
           "; it does NOT protect a NAME.  After any prom_a rename run",
           ";     python3 scripts/converters/symbolize_wsa1_rom_addresses.py --check-equates",
           "; Never edit by hand: re-run the tool with --apply, which rewrites this block."]
    for name, v in sorted(used_a.items(), key=lambda kv: (kv[1], kv[0])):
        out.append("\t.set\t%s, 0x%06X" % (name, v))
    out.append(END)
    return "\n".join(out) + "\n"


def apply(res):
    path = PATH
    raw = open(path, "rb").read().decode("latin-1")
    lines = raw.split("\n")
    assert lines == res["lines"], "source changed under us"
    for li, new in res["edits"].items():
        lines[li] = new
    text = "\n".join(lines)
    used = dict(res["eq_now"])
    used.update(res["used_a"])
    blk = equate_block(used, res["a_lab"])
    if BEGIN in text:
        s = text.index(BEGIN)
        e = text.index(END, s) + len(END) + 1
        text = text[:s] + blk + text[e:]
    else:
        assert text.count(ANCHOR) == 1, "anchor not unique"
        text = text.replace(ANCHOR, ANCHOR + "\n" + blk, 1)
    open(path, "wb").write(text.encode("latin-1"))
    return len(res["edits"]), len(used)


def check_equates():
    sh(["make", "-C", WSA1, "rebuilt_ROMs/wsa1_prom_a.llvm.elf"])
    a_lab, a_names = elf_labels(os.path.join(WSA1, "rebuilt_ROMs/wsa1_prom_a.llvm.elf"))
    text = open(PATH, "rb").read().decode("latin-1")
    if BEGIN not in text:
        print("no equate block")
        return 0
    blk = text[text.index(BEGIN):text.index(END)]
    bad = 0
    n = 0
    for m in re.finditer(r'^\s*\.set\s+([\w.$@]+)\s*,\s*(0x[0-9a-fA-F]+)', blk, re.M):
        n += 1
        name, v = m.group(1), int(m.group(2), 16)
        if name not in a_lab.get(v, []):
            bad += 1
            print("  STALE  %-40s 0x%06X  prom_a now has: %s" % (name, v, ", ".join(a_lab.get(v, [])) or "(no label)"))
    print("%d equates, %d stale" % (n, bad))
    return 1 if bad else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--report")
    ap.add_argument("--check-equates", action="store_true")
    a = ap.parse_args()
    if a.check_equates:
        sys.exit(check_equates())
    res = analyse()
    for k in sorted(res["stats"]):
        print("  %-28s %6d" % (k, res["stats"][k]))
    print("  %-28s %6d" % ("EDITS", len(res["edits"])))
    print("  %-28s %6d" % ("prom_a equates needed", len(res["used_a"])))
    if a.report:
        json.dump(dict(stats=res["stats"], unconverted=res["rows"]), open(a.report, "w"), indent=1)
        print("wrote", a.report)
    if a.apply:
        n, ne = apply(res)
        print("APPLIED: %d lines rewritten, %d equates in the block" % (n, ne))
        if a.verify:
            ok = snb.verify(res["img"])
            print("VERIFY (re-mirrored modified tree == dump):", "PASS" if ok else "FAIL")
            if not ok:
                sys.exit(1)


if __name__ == "__main__":
    main()
