#!/usr/bin/env python3
"""rom_provenance_poison.py -- does the build READ the ROM it claims to reconstruct?

QUESTION ANSWERED: how many bytes of a rebuilt ROM were COPIED from the original at build
time, rather than reproduced from source?

WHY THIS EXISTS. `make all` reports `Similarity: 100.00%` on every target, and that number
is worth much less than it looks. compare_roms.py is a byte-for-byte comparison with no
provenance awareness at all: a two-line .s file containing a single

    .incbin "original_ROMs/kn5000_v10_program.rom"

assembles, links, and scores 100.00%. A build that copies the ROM into its own inputs cannot
fail the comparison, so for those bytes the gate carries no information.

HOW IT WORKS. Copy the tree, POISON one original ROM (XOR 0xFF into every 8th byte), rebuild
from the poisoned copy, then compare the result against the REAL ROM. Bytes the build derived
from source are unaffected. Bytes it copied carry the poison and now differ. Since one byte in
eight is poisoned:

    copied_bytes ~= differing_bytes * 8

MEASURED 2026-08-21:

    v7  : 122,387 differing, all at addr % 8 == 0  ->  979,096 B (46.69%) copied at build time
    v9  : 0 differing  ->  CLEAN
    v10 : 0 differing  ->  CLEAN

So v7's 100.00% is honest about bytes and misleading about reconstruction: `extract_v7_bins.py`
writes raw v7 ROM slices into v7/maincpu/includes/generated/ (untracked, regenerated by every
`make clean-all && make all`), and 288 of those bins have no C source at all.

    python3 scripts/analysis/rom_provenance_poison.py v7
    python3 scripts/analysis/rom_provenance_poison.py v9 v10 --keep

Runs a FULL BUILD PER TARGET in a temporary copy, so it takes a few minutes each and needs a
few hundred MB of scratch. The repo itself is never modified.
"""
import argparse
import pathlib
import shutil
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parent.parent.parent

# target -> (original ROM, rebuilt ROM)
TARGETS = {
    'v7':  ('original_ROMs/kn5000_v7_program.rom',  'rebuilt_ROMs/kn5000_v7_program.llvm.rom'),
    'v9':  ('original_ROMs/kn5000_v9_program.rom',  'rebuilt_ROMs/kn5000_v9_program.llvm.rom'),
    'v10': ('original_ROMs/kn5000_v10_program.rom', 'rebuilt_ROMs/kn5000_v10_program.llvm.rom'),
    'subcpu':    ('original_ROMs/kn5000_subprogram_v142.rom', 'rebuilt_ROMs/kn5000_subprogram_v142.llvm.rom'),
    'table':     ('original_ROMs/kn5000_table_data.rom',      'rebuilt_ROMs/kn5000_table_data.llvm.rom'),
    'custom':    ('original_ROMs/kn5000_custom_data.ic19',    'rebuilt_ROMs/kn5000_custom_data.llvm.rom'),
    'hdae5000':  ('original_ROMs/hd-ae5000_v2_06i.rom',       'rebuilt_ROMs/hd-ae5000_v2_06i.llvm.rom'),
}
STEP = 8


def poison(data: bytes) -> bytes:
    b = bytearray(data)
    for i in range(0, len(b), STEP):
        b[i] ^= 0xFF
    return bytes(b)


def run_one(name: str, keep: bool) -> int:
    orig_rel, built_rel = TARGETS[name]
    real = (REPO / orig_rel).read_bytes()

    work = pathlib.Path(tempfile.mkdtemp(prefix=f'poison-{name}-'))
    tree = work / 'tree'
    print(f"[{name}] copying tree to {tree} ...", flush=True)
    shutil.copytree(REPO, tree, ignore=shutil.ignore_patterns('.git'), symlinks=True)

    (tree / orig_rel).write_bytes(poison(real))
    print(f"[{name}] poisoned every {STEP}th byte of {orig_rel}; building ...", flush=True)

    log = work / 'build.log'
    with log.open('wb') as fh:
        subprocess.run(['make', 'clean-all'], cwd=tree, stdout=fh, stderr=fh)
        rc = subprocess.run(['make', 'all'], cwd=tree, stdout=fh, stderr=fh).returncode

    built_path = tree / built_rel
    if not built_path.exists():
        print(f"[{name}] *** BUILD PRODUCED NO {built_rel} (rc={rc}); see {log}")
        return 2

    built = built_path.read_bytes()
    if len(built) != len(real):
        print(f"[{name}] *** SIZE MISMATCH: built {len(built)} vs real {len(real)}")
        return 2

    diff = [i for i, (a, b) in enumerate(zip(built, real)) if a != b]
    aligned = sum(1 for i in diff if i % STEP == 0)
    copied = len(diff) * STEP
    pct = 100.0 * copied / len(real)

    print(f"[{name}] differing bytes: {len(diff):,}  ({aligned:,} of them at addr %% {STEP} == 0)")
    if not diff:
        print(f"[{name}] CLEAN -- the build read nothing from this ROM.")
    else:
        print(f"[{name}] ~{copied:,} B ({pct:.2f}%) of the rebuilt ROM is COPIED from the original.")
        print(f"[{name}] Those bytes cannot fail compare_roms.py, so 100.00%% says nothing about them.")

    if keep:
        print(f"[{name}] kept {work}")
    else:
        shutil.rmtree(work, ignore_errors=True)
    return 0 if not diff else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('targets', nargs='+', choices=sorted(TARGETS) + ['all'])
    ap.add_argument('--keep', action='store_true', help='keep the temporary tree and build log')
    a = ap.parse_args()
    names = sorted(TARGETS) if 'all' in a.targets else a.targets
    worst = 0
    for n in names:
        worst = max(worst, run_one(n, a.keep))
    return worst


if __name__ == '__main__':
    sys.exit(main())
