#!/usr/bin/env python3
"""v10dac2_line_probe.py -- ground-truth ROM address of every source line of the v10 maincpu tree

QUESTION ANSWERED: for a given ROM address (or address range), which exact v10/maincpu/*.s file
and line number produced the byte(s) at that address? This is the address-side counterpart of
hdae5000/tools/get_lprobe_addrs.py, generalised from a single .s file to the whole 156-file,
.include-based v10/maincpu tree (that tool's technique adapted per the lane brief's suggestion 2:
"the assembler knows -- label every source line, rebuild, and read the real linked address of
each line out of the ELF symbol table").

WHY THIS EXISTS: lane V10DAC (2026-09-02) converted 120 of 264 data-as-code spans by TEXT
matching the census's cached disassembled instruction sequence against the 407,000-line source
tree, requiring the match be unique. 91 spans (2,536 B) had no unique text match -- the same
short template ("ldb e,115 / nop / swi 7", etc.) repeats identically many times across a file, so
text alone can't tell which occurrence is the one at the ROM address the census flagged. This
tool sidesteps text matching entirely: it inserts a uniquely-named zero-width label before every
source line (except inside `.macro`/`.endm` bodies -- a label inside a macro definition would
redefine the same global symbol at every call site and break the build), rebuilds the exact same
`kn5000_v10_program.llvm.o` -> `.elf` -> `.rom` pipeline the Makefile uses, confirms the rebuild
is BYTE-IDENTICAL to the original dump (i.e. the probes changed nothing), and reads every probe's
real linked address back out of the ELF via llvm-nm. The result is an address -> (file, line)
map with no re-decode and no text comparison anywhere -- exactly the technique the brief points
at, generalised to a multi-file `.include` tree instead of hdae5000's single file.

Only 3 of the 156 files define any `.macro` (factory_test/test_init.s, shared/macros.s,
shared/vga_init.s); none of the 49 base labels the 91 target spans hang off live in those files
(checked by hand before writing this), so skipping macro bodies costs nothing here.

RUN (from this worktree's root, ~/compartilhado/disasm-lanes/v10dac2):
    python3 scripts/analysis/v10dac2_line_probe.py --build            # ~20-30s, writes the cache
    python3 scripts/analysis/v10dac2_line_probe.py --lookup 0xED11EE 0xED1226   # one range
    python3 scripts/analysis/v10dac2_line_probe.py --lookup-file /tmp/addrs.txt # many, one per line

Cache: notes/v10-data-as-code/line_probe_cache.json (gitignored -- see .gitignore entry added by
this lane; regenerated by --build in well under a minute). The committed artefact is this script,
exactly per the reproducibility rule: the number is worthless without the thing that produced it,
but a 16 MB+ address map is exactly the kind of large regenerable output that does not itself need
to be committed.

Requires the pinned LLVM build (TOOLCHAIN_VERSION at the worktree root); reads LLVM_BIN from the
environment if set, else assumes ~/compartilhado/llvm-project/build/bin.
"""
import argparse, json, os, re, shutil, subprocess, sys, tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MAINCPU_DIR = os.path.join(REPO, "v10", "maincpu")
ORIGINAL_ROM = os.path.join(REPO, "original_ROMs", "kn5000_v10_program.rom")
ROM_SIZE = 2097152
LLVM_BIN = os.environ.get("LLVM_BIN", os.path.expanduser("~/compartilhado/llvm-project/build/bin"))
CACHE = os.path.join(REPO, "notes", "v10-data-as-code", "line_probe_cache.json")

MACRO_START = re.compile(r'^\s*\.macro\b', re.IGNORECASE)
MACRO_END = re.compile(r'^\s*\.endm\b', re.IGNORECASE)


def instrument_tree(probe_root):
    """Insert `LPROBE_<idx>:` before every line of every *.s file under probe_root, EXCEPT
    lines inside a .macro/.endm body (those would redefine the same global label at every
    macro-expansion call site). Returns a list of (relpath, lineno) indexed by idx."""
    index = []
    s_files = []
    for dirpath, _, filenames in os.walk(probe_root):
        for fn in filenames:
            if fn.endswith(".s"):
                s_files.append(os.path.join(dirpath, fn))
    for path in sorted(s_files):
        relpath = os.path.relpath(path, probe_root)
        with open(path, encoding="latin-1") as f:
            lines = f.readlines()
        out = []
        in_macro = False
        for i, line in enumerate(lines, 1):
            if in_macro:
                out.append(line)
                if MACRO_END.match(line):
                    in_macro = False
                continue
            if MACRO_START.match(line):
                out.append(line)
                in_macro = True
                continue
            idx = len(index)
            index.append((relpath, i))
            out.append(f"LPROBE_{idx}:\n")
            out.append(line)
        with open(path, "w", encoding="latin-1") as f:
            f.writelines(out)
    return index


def build():
    llvm_mc = os.path.join(LLVM_BIN, "llvm-mc")
    ld_lld = os.path.join(LLVM_BIN, "ld.lld")
    llvm_objcopy = os.path.join(LLVM_BIN, "llvm-objcopy")
    llvm_nm = os.path.join(LLVM_BIN, "llvm-nm")
    for tool in (llvm_mc, ld_lld, llvm_objcopy, llvm_nm):
        if not os.path.exists(tool):
            sys.exit(f"missing tool: {tool} (set LLVM_BIN)")

    with open(ORIGINAL_ROM, "rb") as f:
        original = f.read()
    if len(original) != ROM_SIZE:
        sys.exit(f"original_ROMs/kn5000_v10_program.rom is {len(original)} B, expected "
                 f"{ROM_SIZE} B -- refusing to compare against a wrong/truncated file.")

    with tempfile.TemporaryDirectory(prefix="v10dac2_lineprobe_") as tmp:
        probe_dir = os.path.join(tmp, "maincpu")
        shutil.copytree(MAINCPU_DIR, probe_dir)
        index = instrument_tree(probe_dir)
        print(f"instrumented {len(index):,} lines across the v10/maincpu tree", file=sys.stderr)

        obj = os.path.join(tmp, "probe.o")
        elf = os.path.join(tmp, "probe.elf")
        rom = os.path.join(tmp, "probe.rom")

        r = subprocess.run([llvm_mc, "-triple=tlcs900", "-filetype=obj", "-I", probe_dir,
                             "-o", obj, os.path.join(probe_dir, "kn5000_v10_program.s")],
                            capture_output=True, text=True)
        if r.returncode:
            sys.exit(f"llvm-mc failed:\n{r.stderr[:4000]}")
        r = subprocess.run([ld_lld, "-e", "0", "-T", os.path.join(probe_dir, "maincpu.ld"),
                             "-o", elf, obj], capture_output=True, text=True)
        if r.returncode:
            sys.exit(f"ld.lld failed:\n{r.stderr[:4000]}")
        subprocess.run([llvm_objcopy, "-O", "binary", elf, rom], check=True)

        with open(rom, "rb") as f:
            built = f.read()
        if len(built) != ROM_SIZE:
            sys.exit(f"probe build produced {len(built)} B, expected {ROM_SIZE} B -- broken.")
        if built != original:
            # Find the first differing byte to make a wrong probe insertion diagnosable.
            first_diff = next((i for i in range(ROM_SIZE) if built[i] != original[i]), None)
            sys.exit("PROBE BUILD IS NOT BYTE-IDENTICAL to the original ROM -- the probe labels "
                     f"perturbed the image (first diff at 0x{first_diff:06X}). Aborting without "
                     "writing a cache that would be untrustworthy.")
        print(f"probe build verified byte-identical to original_ROMs/ ({ROM_SIZE:,} B) -- "
              "addresses below are trustworthy.", file=sys.stderr)

        result = subprocess.run([llvm_nm, elf], check=True, capture_output=True, text=True)
        addr_by_idx = {}
        for line in result.stdout.splitlines():
            parts = line.split()
            if len(parts) == 3 and parts[2].startswith("LPROBE_"):
                idx = int(parts[2][len("LPROBE_"):])
                addr_by_idx[idx] = int(parts[0], 16)
        if len(addr_by_idx) != len(index):
            # Not fatal: 17 of the 156 .s files under v10/maincpu are never reached by any
            # .include from kn5000_v10_program.s (dead/orphaned sources -- confirmed by walking
            # the .include graph: audio/sound_data_*.s x15, includes/gui_display_struct_data.s,
            # ui_widgets/block_007.s). Their probe labels are inserted into the copied tree but
            # never assembled, so they never produce an nm symbol. This is expected and does not
            # affect any address actually reported below -- an unreached file simply contributes
            # no addresses. Missing count is checked to stay in that same ballpark, not ignored.
            missing = len(index) - len(addr_by_idx)
            print(f"NOTE: {missing:,} of {len(index):,} probe labels produced no symbol -- "
                  "expected, from .s files never reached via .include (see script docstring). "
                  "Proceeding with the resolved subset only.", file=sys.stderr)

    # Build address -> [(file, line), ...] (a list because zero-emission lines -- comments,
    # blanks, label-only lines, .equ/.set -- share the address of the next real content).
    by_addr = {}
    for idx, (relpath, lineno) in enumerate(index):
        addr = addr_by_idx.get(idx)
        if addr is None:
            continue  # line in a .s file never reached via .include -- see NOTE above
        by_addr.setdefault(addr, []).append([relpath, lineno])

    os.makedirs(os.path.dirname(CACHE), exist_ok=True)
    with open(CACHE, "w") as f:
        json.dump({"rom_size": ROM_SIZE, "num_probes": len(index),
                   "by_addr": {str(k): v for k, v in sorted(by_addr.items())}}, f)
    print(f"wrote {CACHE} ({len(by_addr):,} distinct addresses, {len(index):,} probed lines)",
          file=sys.stderr)


def load_cache():
    if not os.path.exists(CACHE):
        sys.exit(f"{CACHE} does not exist -- run with --build first.")
    with open(CACHE) as f:
        d = json.load(f)
    by_addr = {int(k): v for k, v in d["by_addr"].items()}
    return by_addr


def lookup(by_addr, addr_lo, addr_hi):
    """Return the ordered list of (file, line, addr) probes whose address falls in
    [addr_lo, addr_hi], i.e. the physical source lines that produced this span, plus the
    boundary probe at addr_hi (the next real content after the span, for a sanity check that
    the span ends exactly on a line boundary rather than splitting an instruction)."""
    addrs = sorted(a for a in by_addr if addr_lo <= a <= addr_hi)
    out = []
    for a in addrs:
        for relpath, lineno in by_addr[a]:
            out.append((relpath, lineno, a))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build", action="store_true")
    ap.add_argument("--lookup", nargs=2, metavar=("ADDR_LO", "ADDR_HI"))
    ap.add_argument("--lookup-file", metavar="PATH",
                     help="file with one 'ADDR_LO ADDR_HI' pair per line (hex, 0x-prefixed)")
    args = ap.parse_args()

    if args.build:
        build()
        return

    by_addr = load_cache()

    def do_range(lo_s, hi_s):
        lo, hi = int(lo_s, 16), int(hi_s, 16)
        rows = lookup(by_addr, lo, hi)
        print(f"[{lo_s}, {hi_s}) :")
        for relpath, lineno, a in rows:
            marker = " <-- START" if a == lo else (" <-- END (next content)" if a == hi else "")
            print(f"  0x{a:06X}  {relpath}:{lineno}{marker}")

    if args.lookup:
        do_range(*args.lookup)
    elif args.lookup_file:
        with open(args.lookup_file) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                lo_s, hi_s = line.split()[:2]
                do_range(lo_s, hi_s)
    else:
        ap.print_help()


if __name__ == "__main__":
    main()
