/**
 * naka_msp_recording.c — NAKA widget descriptors (fully decoded)
 *
 * Base ROM address: 0xE1AB58
 * Total size: 3222 bytes
 * Auto-generated by scripts/naka_struct_decode.py
 */

#include "naka_types.h"

/* ── External symbols (resolved by linker script) ── */

extern const char NakaInst_Param_EndFF;
extern const char Naka_PresentationRootState;
extern const char SeqByteBlock_EffectsSeqData;
extern const char SeqByteBlock_EffectsSeqDotExt;
extern const char NakaWidget_CmpMeas;
extern const char NakaWidget_CmpMem;
extern const char NakaWidget_CmpQtz;
extern const char NakaWidget_CmpRealScreen;
extern const char NakaWidget_CmpRealScreen_10_VwEditSwBox;
extern const char NakaWidget_CmpRealScreen_11_VwEditSwBox;
extern const char NakaWidget_CmpRealScreen_12_VwEditSwBox;
extern const char NakaWidget_CmpRealScreen_13_VwEditSwBox;
extern const char NakaWidget_CmpRealScreen_14_VwEditSwBox;
extern const char NakaWidget_CmpRealScreen_15_AcCmpTempoBox;
extern const char NakaWidget_CmpRealScreen_16_AcTitleMenu;
extern const char NakaWidget_CmpRealScreen_17_AcTitleMenu;
extern const char NakaWidget_CmpRealScreen_18_AcMemNoBox;
extern const char NakaWidget_CmpRealScreen_19_VwMenuBox;
extern const char NakaWidget_CmpRealScreen_1_Box;
extern const char NakaWidget_CmpRealScreen_20_VwMenuBox;
extern const char NakaWidget_CmpRealScreen_21_VwMenuBox;
extern const char NakaWidget_CmpRealScreen_22_VwMenuBox;
extern const char NakaWidget_CmpRealScreen_23_VwMenuBox;
extern const char NakaWidget_CmpRealScreen_3_Label;
extern const char NakaWidget_CmpRealScreen_4_Label;
extern const char NakaWidget_CmpRealScreen_5_Label;
extern const char NakaWidget_CmpRealScreen_6_Label;
extern const char NakaWidget_CmpRealScreen_7_Label;
extern const char NakaWidget_CmpRealScreen_8_Label;
extern const char NakaWidget_CmpRealScreen_9_IvMainEditSw;
extern const char NakaWidget_CmSetP1Ctl;
extern const char NakaWidget_CmSetP1Grid;
extern const char NakaWidget_CmSetP2Ctl;
extern const char NakaWidget_CmSetPage;
extern const char NakaWidget_CmSetPage1;
extern const char NakaWidget_CmSetPage2;
extern const char NakaWidget_CmSetPanSw;
extern const char NakaWidget_CmSetPartSw;
extern const char NakaWidget_CmSetRLmtSw;
extern const char NakaWidget_CmpAc1Vol;
extern const char NakaWidget_CmpAc2Vol;
extern const char NakaWidget_CmpAc3Vol;
extern const char NakaWidget_CmpBalScreen;
extern const char NakaWidget_CmpBasVol;
extern const char NakaWidget_CmpBkslSScreen;
extern const char NakaWidget_CmpBkslSScreen_10_AcMemNoBox;
extern const char NakaWidget_CmpBkslSScreen_11_Label;
extern const char NakaWidget_CmpBkslSScreen_12_Line;
extern const char NakaWidget_CmpBkslSScreen_13_Line;
extern const char NakaWidget_CmpBkslSScreen_14_Line;
extern const char NakaWidget_CmpBkslSScreen_15_Line;
extern const char NakaWidget_CmpBkslSScreen_17_VwMenuBox;
extern const char NakaWidget_CmpBkslSScreen_1_Box;
extern const char NakaWidget_CmpBkslSScreen_21_AcLanguageText;
extern const char NakaWidget_CmpBkslSScreen_2_Label;
extern const char NakaWidget_CmpBkslSScreen_3_IvMainEditSw;
extern const char NakaWidget_CmpBkslSScreen_4_VwMenuBox;
extern const char NakaWidget_CmpBkslSScreen_5_VwEditSwBox;
extern const char NakaWidget_CmpBkslSScreen_6_VwEditSwBox;
extern const char NakaWidget_CmpBkslSScreen_7_VwEditSwBox;
extern const char NakaWidget_CmpBkslSScreen_8_VwEditSwBox;
extern const char NakaWidget_CmpBkslSScreen_9_VwEditSwBox;
extern const char NakaWidget_CmpBkslScreen;
extern const char NakaWidget_CmpBkslScreen_10_VwMenuBox;
extern const char NakaWidget_CmpBkslScreen_11_VwMenuBox;
extern const char NakaWidget_CmpBkslScreen_1_IvMainEditSw;
extern const char NakaWidget_CmpBkslScreen_2_VwMenuBox;
extern const char NakaWidget_CmpBkslScreen_3_VwMenuBox;
extern const char NakaWidget_CmpBkslScreen_4_VwMenuBox;
extern const char NakaWidget_CmpBkslScreen_5_VwMenuBox;
extern const char NakaWidget_CmpBkslScreen_6_VwMenuBox;
extern const char NakaWidget_CmpBkslScreen_7_VwMenuBox;
extern const char NakaWidget_CmpBkslScreen_8_VwMenuBox;
extern const char NakaWidget_CmpBkslScreen_9_VwMenuBox;
extern const char NakaWidget_CmpClrNoSw;
extern const char NakaWidget_CmpClrSure;
extern const char NakaWidget_CmpClrYesSw;
extern const char NakaWidget_CmpDrmVol;
extern const char NakaWidget_CmpMenuScreen;
extern const char NakaWidget_CmpMenuScreen_10_Line;
extern const char NakaWidget_CmpMenuScreen_11_Label;
extern const char NakaWidget_CmpMenuScreen_12_Label;
extern const char NakaWidget_CmpMenuScreen_13_IvMainEditSw;
extern const char NakaWidget_CmpMenuScreen_14_VwMenuBox;
extern const char NakaWidget_CmpMenuScreen_15_VwMenuBox;
extern const char NakaWidget_CmpMenuScreen_16_VwMenuBox;
extern const char NakaWidget_CmpMenuScreen_17_IvExitMode;
extern const char NakaWidget_CmpMenuScreen_1_AcTitleMenu;
extern const char NakaWidget_CmpMenuScreen_2_AcTitleMenu;
extern const char NakaWidget_CmpMenuScreen_3_AcTitleMenu;
extern const char NakaWidget_CmpMenuScreen_4_AcTitleMenu;
extern const char NakaWidget_CmpMenuScreen_5_AcTitleMenu;
extern const char NakaWidget_CmpMenuScreen_6_AcTitleMenu;
extern const char NakaWidget_CmpMenuScreen_7_Line;
extern const char NakaWidget_CmpMenuScreen_8_Line;
extern const char NakaWidget_CmpMenuScreen_9_Line;
extern const char NakaWidget_CmpNameMenu;
extern const char NakaWidget_CmpNamingScreen;
extern const char NakaWidget_CmpNamingScreen_1_IvNaming;
extern const char NakaWidget_CmpNamingScreen_2_AcFuncEditSw;
extern const char NakaWidget_CmpNcpFitmSw;
extern const char NakaWidget_CmpNcpScreen;
extern const char NakaWidget_CmpNcpScreen_10_Line;
extern const char NakaWidget_CmpNcpScreen_11_Line;
extern const char NakaWidget_CmpNcpScreen_12_Label;
extern const char NakaWidget_CmpNcpScreen_13_Line;
extern const char NakaWidget_CmpNcpScreen_14_Line;
extern const char NakaWidget_CmpNcpScreen_15_Line;
extern const char NakaWidget_CmpNcpScreen_16_Line;
extern const char NakaWidget_CmpNcpScreen_17_Box;
extern const char NakaWidget_CmpNcpScreen_19_Label;
extern const char NakaWidget_CmpNcpScreen_1_IvMainEditSw;
extern const char NakaWidget_CmpNcpScreen_20_Label;
extern const char NakaWidget_CmpNcpScreen_21_Label;
extern const char NakaWidget_CmpNcpScreen_22_Label;
extern const char NakaWidget_CmpNcpScreen_23_Label;
extern const char NakaWidget_CmpNcpScreen_24_VwEditSwBox;
extern const char NakaWidget_CmpNcpScreen_25_Box;
extern const char NakaWidget_CmpNcpScreen_3_VwWideESBox;
extern const char NakaWidget_CmpNcpScreen_5_VwWideESBox;
extern const char NakaWidget_CmpNcpScreen_6_Label;
extern const char NakaWidget_CmpNcpScreen_7_Label;
extern const char NakaWidget_CmpNcpScreen_8_Line;
extern const char NakaWidget_CmpNcpScreen_9_Line;
extern const char NakaWidget_CmpNcpTitmSw;
extern const char NakaWidget_CmpSetGrid;
extern const char NakaWidget_CmpSetScreen;
extern const char NakaWidget_CmpSetScreen_10_AcIndexWideES;
extern const char NakaWidget_CmpSetScreen_11_Label;
extern const char NakaWidget_CmpSetScreen_12_Label;
extern const char NakaWidget_CmpSetScreen_1_IvMainEditSw;
extern const char NakaWidget_CmpSetScreen_5_IvShowHide;
extern const char NakaWidget_CmpSetScreen_8_Label;
extern const char NakaWidget_CmpSetScreen_9_AcIndexWideES;
extern const char NakaWidget_NameMemLabel;
extern const char NakaWidget_NamingMem;
extern const char NakaWidget_StylCnvCnvtBox;
extern const char NakaWidget_StylCnvCnvtScreen;
extern const char NakaWidget_StylCnvCnvtScreen_1_IvMainEditSw;
extern const char NakaWidget_StylCnvCnvtScreen_3_VwEditSwBox;
extern const char NakaWidget_StylCnvCnvtScreen_4_VwWideESBox;
extern const char NakaWidget_StylCnvCnvtScreen_5_VwEditSwBox;
extern const char NakaWidget_StylCnvCnvtScreen_6_VwEditSwBox;
extern const char NakaWidget_StylCnvContScreen;
extern const char NakaWidget_StylCnvContScreen_1_IvMainEditSw;
extern const char NakaWidget_StylCnvContScreen_2_VwBox;
extern const char NakaWidget_StylCnvContScreen_3_Label;
extern const char NakaWidget_StylCnvContScreen_4_Label;
extern const char NakaWidget_StylCnvContScreen_5_VwEditSwBox;
extern const char NakaWidget_StylCnvContScreen_6_VwEditSwBox;
extern const char NakaWidget_StylCnvModlBox;
extern const char NakaWidget_StylCnvModlScreen;
extern const char NakaWidget_StylCnvModlScreen_1_IvMainEditSw;
extern const char NakaWidget_StylCnvModlScreen_3_VwEditSwBox;
extern const char NakaWidget_StylCnvModlScreen_4_VwWideESBox;
extern const char NakaWidget_StylCnvModlScreen_5_VwEditSwBox;
extern const char NakaWidget_StylCnvModlScreen_6_VwEditSwBox;
extern const char NakaWidget_StylCnvSelBox;
extern const char NakaWidget_StylCnvSelScreen;
extern const char NakaWidget_StylCnvSelScreen_1_IvMainEditSw;
extern const char NakaWidget_StylCnvSelScreen_3_VwEditSwBox;
extern const char NakaWidget_StylCnvSelScreen_4_VwWideESBox;
extern const char NakaWidget_StylCnvSelScreen_5_VwEditSwBox;
extern const char NakaWidget_StylCnvSelScreen_6_VwEditSwBox;
extern const char NakaWidget_StylCnvSelScreen_7_PsSCTxtBox;
extern const char NakaWidget_StylCnvStorScreen;
extern const char NakaWidget_StylCnvStorScreen_1_AcRamEditBox;
extern const char NakaWidget_StylCnvStorScreen_2_AcIndexWideES;
extern const char NakaWidget_StylCnvStorScreen_3_AcFuncEditSw;
extern const char NakaWidget_StylCnvTxtScreen;
extern const char NakaWidget_StylCnvTxtScreen_1_VwBox;
extern const char NakaWidget_StylCnvTxtScreen_2_PSSCTxtBox2;
extern const char NakaWidget_StylCnvTxtScreen_3_IvMainEditSw;
extern const char NakaWidget_StylCnvVer;
extern const char NakaWidget_StylCnvWaitScreen;
extern const char NakaWidget_StylCnvWaitScreen_1_VwBox;
extern const char NakaWidget_StylCnvWaitScreen_2_AcLanguageText;
extern const char NakaWidget_SunaView0B6_0_IvDirmdScreen;

#define BASE  0x00E1AB58u

/* NAKA class TtlScreen -- class id 0x01600034 (Class table slot 0x160, entry 52),
 * parent Screen; allsize 42.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint32_t exit;              /* +26 a */
    uint32_t window;            /* +30 r */
    uint32_t title;             /* +34 X */
    uint32_t icon;              /* +38 b */
} naka_cls_TtlScreen_t;

/* NAKA class VwBox -- class id 0x01600011 (Class table slot 0x160, entry 17),
 * parent Viewable; allsize 28.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
} naka_cls_VwBox_t;

/* NAKA class Label -- class id 0x0160002B (Class table slot 0x160, entry 43),
 * parent Viewable; allsize 32.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint32_t str;               /* +22 X */
    uint32_t font;              /* +26 c */
    uint16_t fontcolor;         /* +30 ^ */
} naka_cls_Label_t;

/* NAKA class PsMspRecPadBox -- class id 0x0164001B (Class table slot 0x164, entry 27),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_PsMspRecPadBox_t;

/* NAKA class PsMspRecBnkBox -- class id 0x0164001C (Class table slot 0x164, entry 28),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_PsMspRecBnkBox_t;

/* NAKA class AcCmpTempoBox -- class id 0x01640011 (Class table slot 0x164, entry 17),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_AcCmpTempoBox_t;

/* NAKA class PsMspMeasBox -- class id 0x01640019 (Class table slot 0x164, entry 25),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_PsMspMeasBox_t;

/* NAKA class PsMspMemBox -- class id 0x0164001A (Class table slot 0x164, entry 26),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_PsMspMemBox_t;

/* NAKA class AcRamEditBox -- class id 0x0160001B (Class table slot 0x160, entry 27),
 * parent PsEditBox; allsize 58.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t caption;           /* +28 X */
    uint32_t font;              /* +32 c */
    uint16_t fontcolor;         /* +36 ^ */
    uint16_t align;             /* +38 d */
    uint16_t length;            /* +40 B */
    uint16_t editsw;            /* +42 e */
    uint16_t dial;              /* +44 G */
    uint32_t selected;          /* +46 m */
    uint32_t func;              /* +50 j */
    uint32_t data;              /* +54 r */
} naka_cls_AcRamEditBox_t;

/* NAKA class AcIndexWideES -- class id 0x01600022 (Class table slot 0x160, entry 34),
 * parent PsWideESBox; allsize 42.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
    uint16_t editsw;            /* +36 e */
    uint16_t editsw2;           /* +38 e */
    uint16_t style;             /* +40 f */
} naka_cls_AcIndexWideES_t;

/* NAKA class IvExitMode -- class id 0x01600048 (Class table slot 0x160, entry 72),
 * parent IvExit; allsize 26.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint32_t mode;              /* +22 ` */
} naka_cls_IvExitMode_t;

/* NAKA class AcTitleMenu -- class id 0x0160001D (Class table slot 0x160, entry 29),
 * parent PsMenuBox; allsize 54.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
    uint16_t editsw;            /* +36 e */
    uint32_t selected;          /* +38 m */
    uint32_t str;               /* +42 X */
    uint32_t title;             /* +46 a */
    uint32_t icon;              /* +50 b */
} naka_cls_AcTitleMenu_t;

/* NAKA class AcFuncEditSw -- class id 0x01600020 (Class table slot 0x160, entry 32),
 * parent PsEditSwBox; allsize 44.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
    uint16_t editsw;            /* +36 e */
    uint16_t style;             /* +38 f */
    uint32_t func;              /* +40 j */
} naka_cls_AcFuncEditSw_t;

/* NAKA class IvNaming -- class id 0x0160004D (Class table slot 0x160, entry 77),
 * parent PsInvisibleBox; allsize 26.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint32_t func;              /* +22 j */
} naka_cls_IvNaming_t;

/* NAKA class PsMspNameBnk -- class id 0x0164001D (Class table slot 0x164, entry 29),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_PsMspNameBnk_t;

/* NAKA class StringBox -- class id 0x01600037 (Class table slot 0x160, entry 55),
 * parent Box; allsize 38.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint32_t str;               /* +26 X */
    uint32_t font;              /* +30 c */
    uint16_t fontcolor;         /* +34 ^ */
    uint16_t alignment;         /* +36 d */
} naka_cls_StringBox_t;

/* NAKA class AcGridBox -- class id 0x01600056 (Class table slot 0x160, entry 86),
 * parent PsGridBox; allsize 74.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
    uint16_t row;               /* +36 B */
    uint16_t col;               /* +38 B */
    uint16_t vertline;          /* +40 G */
    uint32_t selrow;            /* +42 n */
    uint32_t selcol;            /* +46 n */
    uint32_t pcol;              /* +50 s */
    uint32_t prow;              /* +54 s */
    uint32_t crow;              /* +58 s */
    uint32_t fixedcol;          /* +62 X */
    uint32_t fixedrow;          /* +66 X */
    uint32_t func;              /* +70 j */
} naka_cls_AcGridBox_t;

/* NAKA class AcIndexEditSw -- class id 0x0160001F (Class table slot 0x160, entry 31),
 * parent PsEditSwBox; allsize 40.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
    uint16_t editsw;            /* +36 e */
    uint16_t style;             /* +38 f */
} naka_cls_AcIndexEditSw_t;

/* NAKA class PsRgpSetBnkBox -- class id 0x01640017 (Class table slot 0x164, entry 23),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_PsRgpSetBnkBox_t;

/* NAKA class IvShowHide -- class id 0x01600064 (Class table slot 0x160, entry 100),
 * parent PsInvisibleBox; allsize 26.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint32_t func;              /* +22 j */
} naka_cls_IvShowHide_t;

/* NAKA class PsCmpCpFVariBox -- class id 0x01640013 (Class table slot 0x164, entry 19),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_PsCmpCpFVariBox_t;

/* NAKA class AcSndArgGridBox -- class id 0x01640020 (Class table slot 0x164, entry 32),
 * parent PsGridBox; allsize 74.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
    uint16_t row;               /* +36 B */
    uint16_t col;               /* +38 B */
    uint16_t vertline;          /* +40 G */
    uint32_t selrow;            /* +42 n */
    uint32_t selcol;            /* +46 n */
    uint32_t pcol;              /* +50 s */
    uint32_t prow;              /* +54 s */
    uint32_t crow;              /* +58 s */
    uint32_t fixedcol;          /* +62 X */
    uint32_t fixedrow;          /* +66 X */
    uint32_t func;              /* +70 j */
} naka_cls_AcSndArgGridBox_t;

/* NAKA class AcLanguageText -- class id 0x01600066 (Class table slot 0x160, entry 102),
 * parent PsTextBox; allsize 42.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t alignment;         /* +34 d */
    uint16_t lines;             /* +36 B */
    uint32_t func;              /* +38 j */
} naka_cls_AcLanguageText_t;

/* NAKA class AcApcMdBox -- class id 0x0164000E (Class table slot 0x164, entry 14),
 * parent PsEditBox; allsize 52.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t caption;           /* +28 X */
    uint32_t font;              /* +32 c */
    uint16_t fontcolor;         /* +36 ^ */
    uint16_t align;             /* +38 d */
    uint16_t length;            /* +40 B */
    uint16_t editsw;            /* +42 e */
    uint16_t dial;              /* +44 G */
    uint32_t selected;          /* +46 m */
    uint8_t apcdata;           /* +50 C */
    uint8_t _pad_51[1];
} naka_cls_AcApcMdBox_t;

/* NAKA class AcApcToggle -- class id 0x0164001F (Class table slot 0x164, entry 31),
 * parent PsToggleBox; allsize 48.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint32_t font;              /* +22 c */
    uint32_t stron;             /* +26 X */
    uint32_t stroff;            /* +30 X */
    uint32_t onoff;             /* +34 m */
    uint16_t editsw;            /* +38 e */
    uint32_t func;              /* +40 j */
    uint32_t pman_ad;           /* +44 F */
} naka_cls_AcApcToggle_t;

typedef struct __attribute__((packed)) {
    /* element 0 of Viewable slot 0xC9 "MspRecScreen": TtlScreen (class id 0x01600034) */
    naka_cls_TtlScreen_t MspRecScreen;
    char MspPhraseRecording_text[22];
    /* element 1 of Viewable slot 0xC9 "MspRecBox1": VwBox (class id 0x01600011) */
    naka_cls_VwBox_t MspRecBox1;
    /* element 2 of Viewable slot 0xC9: Label (class id 0x0160002B) */
    naka_cls_Label_t RecordingPhrase_Label;
    char RecordingPhrase_text[18];
    /* element 3 of Viewable slot 0xC9 "MspBnkLbl": Label (class id 0x0160002B) */
    naka_cls_Label_t MspBnkLbl;
    char Bank_text[8];
    /* element 4 of Viewable slot 0xC9 "RecPadNo": PsMspRecPadBox (class id 0x0164001B) */
    naka_cls_PsMspRecPadBox_t RecPadNo;
    /* element 5 of Viewable slot 0xC9 "RecBankName": PsMspRecBnkBox (class id 0x0164001C) */
    naka_cls_PsMspRecBnkBox_t RecBankName;
    /* element 6 of Viewable slot 0xC9 "MspRecBox2": VwBox (class id 0x01600011) */
    naka_cls_VwBox_t MspRecBox2;
    /* element 7 of Viewable slot 0xC9: Label (class id 0x0160002B) */
    naka_cls_Label_t Tempo_Label;
    char Tempo_text[10];
    /* element 8 of Viewable slot 0xC9 "MspTempo": AcCmpTempoBox (class id 0x01640011) */
    naka_cls_AcCmpTempoBox_t MspTempo;
    /* element 9 of Viewable slot 0xC9 "MspMeas": PsMspMeasBox (class id 0x01640019) */
    naka_cls_PsMspMeasBox_t MspMeas;
    /* element 10 of Viewable slot 0xC9 "MspMem": PsMspMemBox (class id 0x0164001A) */
    naka_cls_PsMspMemBox_t MspMem;
    /* element 11 of Viewable slot 0xC9: Label (class id 0x0160002B) */
    naka_cls_Label_t MspMem_Label;
    char w6_text[2];
    /* element 12 of Viewable slot 0xC9 "MspPadLbl": Label (class id 0x0160002B) */
    naka_cls_Label_t MspPadLbl;
    char Pad_text[8];
    /* element 13 of Viewable slot 0xC9: AcRamEditBox (class id 0x0160001B) */
    naka_cls_AcRamEditBox_t MspRecScreen_AcRamEditBox;
    char vC9_e13_caption[12];
    /* element 14 of Viewable slot 0xC9: AcIndexWideES (class id 0x01600022) */
    naka_cls_AcIndexWideES_t MspRecScreen_AcIndexWideES;
    /* element 15 of Viewable slot 0xC9: IvExitMode (class id 0x01600048) */
    naka_cls_IvExitMode_t MspRecScreen_IvExitMode;
    /* element 0 of Viewable slot 0xCA "MspMenuScreen": TtlScreen (class id 0x01600034) */
    naka_cls_TtlScreen_t MspMenuScreen;
    char MspMenu_text[10];
    /* element 1 of Viewable slot 0xCA: AcTitleMenu (class id 0x0160001D) */
    naka_cls_AcTitleMenu_t CompileSet_AcTitleMenu;
    char CompileSet_text[12];
    /* element 2 of Viewable slot 0xCA: AcTitleMenu (class id 0x0160001D) */
    naka_cls_AcTitleMenu_t NamingForUserCompile_AcTitleMenu;
    char NamingForUserCompile_text[30];
    /* element 3 of Viewable slot 0xCA: IvExitMode (class id 0x01600048) */
    naka_cls_IvExitMode_t MspMenuScreen_IvExitMode;
    /* element 4 of Viewable slot 0xCA: AcRamEditBox (class id 0x0160001B) */
    naka_cls_AcRamEditBox_t MspMenuScreen_AcRamEditBox;
    char vCA_e4_caption[14];
    /* element 5 of Viewable slot 0xCA: AcIndexWideES (class id 0x01600022) */
    naka_cls_AcIndexWideES_t MspMenuScreen_AcIndexWideES;
    /* element 0 of Viewable slot 0xCB "MspNamingScreen": TtlScreen (class id 0x01600034) */
    naka_cls_TtlScreen_t MspNamingScreen;
    char Naming_text[8];
    /* element 1 of Viewable slot 0xCB: AcFuncEditSw (class id 0x01600020) */
    naka_cls_AcFuncEditSw_t MspNamingScreen_AcFuncEditSw;
    /* element 2 of Viewable slot 0xCB: IvNaming (class id 0x0160004D) */
    naka_cls_IvNaming_t MspNamingScreen_IvNaming;
    /* element 3 of Viewable slot 0xCB: PsMspNameBnk (class id 0x0164001D) */
    naka_cls_PsMspNameBnk_t MspNamingScreen_PsMspNameBnk;
    /* element 0 of Viewable slot 0xCC "MspReGrpScreen": TtlScreen (class id 0x01600034) */
    naka_cls_TtlScreen_t MspReGrpScreen;
    char MspCompileSetting_text[20];
    /* element 1 of Viewable slot 0xCC "RGrpBnkSw": AcFuncEditSw (class id 0x01600020) */
    naka_cls_AcFuncEditSw_t RGrpBnkSw;
    /* element 2 of Viewable slot 0xCC: StringBox (class id 0x01600037) */
    naka_cls_StringBox_t BANK_StringBox;
    char BANK_str[6];
    /* element 3 of Viewable slot 0xCC "MspRGrpGrid": AcGridBox (class id 0x01600056) */
    naka_cls_AcGridBox_t MspRGrpGrid;
    char MspRGrpGrid_fixedrow[34];
    char MspRGrpGrid_fixedcol[28];
    /* element 4 of Viewable slot 0xCC: AcIndexEditSw (class id 0x0160001F) */
    naka_cls_AcIndexEditSw_t MspReGrpScreen_AcIndexEditSw;
    /* element 5 of Viewable slot 0xCC: AcIndexWideES (class id 0x01600022) */
    naka_cls_AcIndexWideES_t MspReGrpScreen_AcIndexWideES;
    /* element 6 of Viewable slot 0xCC: AcIndexWideES (class id 0x01600022) */
    naka_cls_AcIndexWideES_t MspReGrpScreen_AcIndexWideES_2;
    /* element 7 of Viewable slot 0xCC "RgpSetBnk": PsRgpSetBnkBox (class id 0x01640017) */
    naka_cls_PsRgpSetBnkBox_t RgpSetBnk;
    /* element 8 of Viewable slot 0xCC: IvShowHide (class id 0x01600064) */
    naka_cls_IvShowHide_t MspReGrpScreen_IvShowHide;
    /* element 0 of Viewable slot 0xDC "SndArgrScreen": TtlScreen (class id 0x01600034) */
    naka_cls_TtlScreen_t SndArgrScreen;
    char SoundArranger_text[16];
    /* element 1 of Viewable slot 0xDC: StringBox (class id 0x01600037) */
    naka_cls_StringBox_t Pattern_StringBox;
    char Pattern_str[12];
    /* element 2 of Viewable slot 0xDC "SndArgRhyName": PsCmpCpFVariBox (class id 0x01640013) */
    naka_cls_PsCmpCpFVariBox_t SndArgRhyName;
    /* element 3 of Viewable slot 0xDC: IvExitMode (class id 0x01600048) */
    naka_cls_IvExitMode_t SndArgrScreen_IvExitMode;
    /* element 4 of Viewable slot 0xDC: IvShowHide (class id 0x01600064) */
    naka_cls_IvShowHide_t SndArgrScreen_IvShowHide;
    /* element 5 of Viewable slot 0xDC "SndArgrGrid": AcSndArgGridBox (class id 0x01640020) */
    naka_cls_AcSndArgGridBox_t SndArgrGrid;
    char SndArgrGrid_fixedrow[38];
    char SndArgrGrid_fixedcol[40];
    /* element 6 of Viewable slot 0xDC: AcIndexWideES (class id 0x01600022) */
    naka_cls_AcIndexWideES_t SndArgrScreen_AcIndexWideES;
    /* element 7 of Viewable slot 0xDC: AcLanguageText (class id 0x01600066) */
    naka_cls_AcLanguageText_t SndArgrScreen_AcLanguageText;
    /* element 0 of Viewable slot 0xED "ApcSelScreen": TtlScreen (class id 0x01600034) */
    naka_cls_TtlScreen_t ApcSelScreen;
    char AutoPlayChord_text[16];
    /* element 1 of Viewable slot 0xED: AcApcMdBox (class id 0x0164000E) */
    naka_cls_AcApcMdBox_t ApcSelScreen_AcApcMdBox;
    char vED_e1_caption[12];
    /* element 2 of Viewable slot 0xED: AcApcMdBox (class id 0x0164000E) */
    naka_cls_AcApcMdBox_t ApcSelScreen_AcApcMdBox_2;
    char vED_e2_caption[10];
    /* element 3 of Viewable slot 0xED: AcApcMdBox (class id 0x0164000E) */
    naka_cls_AcApcMdBox_t ApcSelScreen_AcApcMdBox_3;
    char vED_e3_caption[8];
    /* element 4 of Viewable slot 0xED "ApcMem": AcApcToggle (class id 0x0164001F) */
    naka_cls_AcApcToggle_t ApcMem;
    char ApcMem_stroff[14];
    char ApcMem_stron[14];
    /* element 5 of Viewable slot 0xED "ApcOnBass": AcApcToggle (class id 0x0164001F) */
    naka_cls_AcApcToggle_t ApcOnBass;
    char ApcOnBass_stroff[14];
    char ApcOnBass_stron[14];
    /* Suna_ViewableTable_010: 4 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_010[4];
    /* Suna_ViewableTable_011: 9 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_011[9];
    /* Suna_ViewableTable_012: 8 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_012[8];
    /* Suna_ViewableTable_013: 5 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_013[5];
    /* Suna_ViewableTable_014: 5 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_014[5];
    /* Suna_ViewableTable_015: 9 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_015[9];
    /* Suna_ViewableTable_016: 8 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_016[8];
    /* Suna_ViewableTable_0B0: 19 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_0B0[19];
    /* Suna_ViewableTable_0B1: 13 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_0B1[13];
    /* Suna_ViewableTable_0B2: 23 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_0B2[23];
    /* Suna_ViewableTable_0B3: 6 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_0B3[6];
    /* Suna_ViewableTable_0B4: 19 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_0B4[19];
    /* Suna_ViewableTable_0B5: 24 pointers (cut from ptrs_1 by split_naka_pointer_arrays.py) */
    /* Viewable table of slot 0xB5 (screen "CmpRealScreen"): 31 view-record pointers + NULL terminator; entries 24-28 are RAM records */
    uint32_t Suna_ViewableTable_0B5[32];
    /* Suna_ViewableTable_0B6: 2 pointers (cut from ptrs_2 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_0B6[2];
    /* Suna_ViewableTable_0B7: 7 pointers (cut from ptrs_2 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_0B7[7];
    /* Suna_ViewableTable_0B8: 18 pointers (cut from ptrs_2 by split_naka_pointer_arrays.py) */
    uint32_t Suna_ViewableTable_0B8[18];
    uint16_t field_0c76;
    uint16_t field_0c78;
    uint32_t ptrs_3[7];  /* 7 pointers */
} naka_msp_recording_t;

#define SELF(field) \
    ((uint32_t)(BASE + __builtin_offsetof(naka_msp_recording_t, field)))

_Static_assert(sizeof(naka_msp_recording_t) == 3222,
    "naka_msp_recording must be exactly 3222 bytes");

const naka_msp_recording_t naka_msp_recording_data
    __attribute__((section(".text"), used)) = {

    .MspRecScreen = {
        .class_ = 0x01600034,
        .super = NAKA_NONE,
        .sub = 1,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x000A,
        .rect = { 0, 0, 319, 239 },
        .color = 0x00F9,
        .border = 0x0000,
        .exit = 0x01A00001,
        .window = 0x0003D762,
        .title = SELF(MspPhraseRecording_text),
        .icon = 0x000000A8,
    },

    .MspPhraseRecording_text = ALIGNED_STRING("MSP PHRASE RECORDING"),

    .MspRecBox1 = {
        .class_ = 0x01600011,
        .super = 0,
        .sub = 2,
        .next = 6,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 21, 38, 290, 103 },
        .color = 0x00F5,
        .border = 0x00C1,
        .index = 0xFFFF,
    },

    .RecordingPhrase_Label = {
        .class_ = 0x0160002B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 3,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 34, 42, 165, 60 },
        .str = SELF(RecordingPhrase_text),
        .font = 0x00000000,
        .fontcolor = 0x00F1,
    },

    .RecordingPhrase_text = ALIGNED_STRING("Recording Phrase"),

    .MspBnkLbl = {
        .class_ = 0x0160002B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 4,
        .prev = 2,
        .flag = 0x0008,
        .rect = { 66, 62, 117, 80 },
        .str = SELF(Bank_text),
        .font = 0x00000001,
        .fontcolor = 0x00FF,
    },

    .Bank_text = ALIGNED_STRING("BANK :"),

    .RecPadNo = {
        .class_ = 0x0164001B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 5,
        .prev = 3,
        .flag = 0x0008,
        .rect = { 120, 82, 139, 97 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000001,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .RecBankName = {
        .class_ = 0x0164001C,
        .super = 1,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 4,
        .flag = 0x0008,
        .rect = { 116, 60, 250, 77 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .MspRecBox2 = {
        .class_ = 0x01600011,
        .super = 0,
        .sub = 7,
        .next = 12,
        .prev = 1,
        .flag = 0x0008,
        .rect = { 21, 108, 290, 173 },
        .color = 0x00F5,
        .border = 0x00C1,
        .index = 0xFFFF,
    },

    .Tempo_Label = {
        .class_ = 0x0160002B,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 8,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 34, 124, 109, 142 },
        .str = SELF(Tempo_text),
        .font = 0x00000001,
        .fontcolor = 0x00FF,
    },

    .Tempo_text = "TEMPO   =",

    .MspTempo = {
        .class_ = 0x01640011,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 9,
        .prev = 7,
        .flag = 0x0008,
        .rect = { 116, 124, 155, 137 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000001,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .MspMeas = {
        .class_ = 0x01640019,
        .super = 6,
        .sub = NAKA_NONE,
        .next = 10,
        .prev = 8,
        .flag = 0x0008,
        .rect = { 32, 150, 156, 163 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000001,
        .fontcolor = 0x00FF,
        .align = 0x0001,
    },

    .MspMem = {
        .class_ = 0x0164001A,
        .super = 6,
        .sub = 11,
        .next = NAKA_NONE,
        .prev = 9,
        .flag = 0x0008,
        .rect = { 170, 150, 289, 163 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000001,
        .fontcolor = 0x00FF,
        .align = 0x0001,
    },

    .MspMem_Label = {
        .class_ = 0x0160002B,
        .super = 10,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 262, 150, 273, 168 },
        .str = SELF(w6_text),
        .font = 0x00000001,
        .fontcolor = 0x00FF,
    },

    .w6_text = "%",

    .MspPadLbl = {
        .class_ = 0x0160002B,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 13,
        .prev = 6,
        .flag = 0x0008,
        .rect = { 66, 83, 117, 101 },
        .str = SELF(Pad_text),
        .font = 0x00000001,
        .fontcolor = 0x00FF,
    },

    .Pad_text = ALIGNED_STRING("PAD  :"),

    .MspRecScreen_AcRamEditBox = {
        .class_ = 0x0160001B,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 14,
        .prev = 12,
        .flag = 0x0008,
        .rect = { 20, 178, 291, 209 },
        .color = 0x00F5,
        .border = 0x00C1,
        .index = 0x0000,
        .caption = SELF(vC9_e13_caption),
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0001,
        .length = 0x0014,
        .editsw = 0x00FF,
        .dial = 0x0001,
        .selected = 0x0003D766,
        .func = 0x0124000D,
        .data = 0x0003D768,
    },

    .vC9_e13_caption = "play mode :",

    .MspRecScreen_AcIndexWideES = {
        .class_ = 0x01600022,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 15,
        .prev = 13,
        .flag = 0x0008,
        .rect = { 244, 216, 315, 238 },
        .color = 0x0007,
        .border = 0x00C9,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0000,
        .editsw = 0x0006,
        .editsw2 = 0x0007,
        .style = 0x0003,
    },

    .MspRecScreen_IvExitMode = {
        .class_ = 0x01600048,
        .super = 0,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 14,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .mode = 0x01800001,
    },

    .MspMenuScreen = {
        .class_ = 0x01600034,
        .super = NAKA_NONE,
        .sub = 1,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x000A,
        .rect = { 0, 0, 319, 239 },
        .color = 0x00F9,
        .border = 0x0002,
        .exit = 0x01A00001,
        .window = 0x0003D76C,
        .title = SELF(MspMenu_text),
        .icon = 0x000000A6,
    },

    .MspMenu_text = ALIGNED_STRING("MSP MENU"),

    .CompileSet_AcTitleMenu = {
        .class_ = 0x0160001D,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 2,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 8, 72, 156, 97 },
        .color = 0x00F7,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .editsw = 0x0089,
        .selected = 0x0003D770,
        .str = SELF(CompileSet_text),
        .title = 0x01A000CC,
        .icon = 0x000000A7,
    },

    .CompileSet_text = "COMPILE SET",

    .NamingForUserCompile_AcTitleMenu = {
        .class_ = 0x0160001D,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 3,
        .prev = 1,
        .flag = 0x0008,
        .rect = { 8, 114, 192, 139 },
        .color = 0x00F7,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .editsw = 0x008A,
        .selected = 0x0003D772,
        .str = SELF(NamingForUserCompile_text),
        .title = 0x01A000CB,
        .icon = 0x00000099,
    },

    .NamingForUserCompile_text = "Naming for User&COMPILE Banks",

    .MspMenuScreen_IvExitMode = {
        .class_ = 0x01600048,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 4,
        .prev = 2,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .mode = 0x01800001,
    },

    .MspMenuScreen_AcRamEditBox = {
        .class_ = 0x0160001B,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 5,
        .prev = 3,
        .flag = 0x0008,
        .rect = { 71, 169, 295, 200 },
        .color = 0x00F5,
        .border = 0x00C1,
        .index = 0x0000,
        .caption = SELF(vCA_e4_caption),
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .length = 0x0008,
        .editsw = 0x00FF,
        .dial = 0x0001,
        .selected = 0x0003D774,
        .func = 0x0124000C,
        .data = 0x0003D776,
    },

    .vCA_e4_caption = "Naming Bank :",

    .MspMenuScreen_AcIndexWideES = {
        .class_ = 0x01600022,
        .super = 0,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 4,
        .flag = 0x0008,
        .rect = { 244, 216, 315, 238 },
        .color = 0x0007,
        .border = 0x00C9,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0000,
        .editsw = 0x0006,
        .editsw2 = 0x0007,
        .style = 0x0003,
    },

    .MspNamingScreen = {
        .class_ = 0x01600034,
        .super = NAKA_NONE,
        .sub = 1,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x000A,
        .rect = { 0, 0, 319, 239 },
        .color = 0x00F9,
        .border = 0x0000,
        .exit = 0x01A000CA,
        .window = 0x0003D77A,
        .title = SELF(Naming_text),
        .icon = 0x00000099,
    },

    .Naming_text = ALIGNED_STRING("NAMING"),

    .MspNamingScreen_AcFuncEditSw = {
        .class_ = 0x01600020,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 2,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 281, 160, 311, 177 },
        .color = 0x0007,
        .border = 0x00C1,
        .index = 0xFFFF,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0000,
        .editsw = 0x000B,
        .style = 0x0006,
        .func = 0x01240004,
    },

    .MspNamingScreen_IvNaming = {
        .class_ = 0x0160004D,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 3,
        .prev = 1,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .func = 0x01240003,
    },

    .MspNamingScreen_PsMspNameBnk = {
        .class_ = 0x0164001D,
        .super = 0,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 2,
        .flag = 0x0008,
        .rect = { 53, 50, 202, 65 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000001,
        .fontcolor = 0x00FF,
        .align = 0x0001,
    },

    .MspReGrpScreen = {
        .class_ = 0x01600034,
        .super = NAKA_NONE,
        .sub = 1,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x000A,
        .rect = { 0, 0, 319, 239 },
        .color = 0x00F9,
        .border = 0x0000,
        .exit = 0x01A000CA,
        .window = 0x0003D77E,
        .title = SELF(MspCompileSetting_text),
        .icon = 0x000000A7,
    },

    .MspCompileSetting_text = "MSP COMPILE SETTING",

    .RGrpBnkSw = {
        .class_ = 0x01600020,
        .super = 0,
        .sub = 2,
        .next = 3,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 8, 34, 38, 51 },
        .color = 0x00F7,
        .border = 0x00C1,
        .index = 0xFFFF,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0000,
        .editsw = 0x0088,
        .style = 0x0000,
        .func = 0x0124000B,
    },

    .BANK_StringBox = {
        .class_ = 0x01600037,
        .super = 1,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 8, 34, 47, 51 },
        .color = 0x0007,
        .border = 0x00C1,
        .str = SELF(BANK_str),
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .alignment = 0x0000,
    },

    .BANK_str = ALIGNED_STRING("BANK"),

    .MspRGrpGrid = {
        .class_ = 0x01600056,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 4,
        .prev = 1,
        .flag = 0x0008,
        .rect = { 36, 65, 315, 238 },
        .color = 0x00F5,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .row = 0x0009,
        .col = 0x0003,
        .vertline = 0x0001,
        .selrow = 0x0003D782,
        .selcol = 0x0003D784,
        .pcol = 0x0003D786,
        .prow = 0x0003D78A,
        .crow = 0x0003D78E,
        .fixedcol = SELF(MspRGrpGrid_fixedcol),
        .fixedrow = SELF(MspRGrpGrid_fixedrow),
        .func = 0x0124000A,
    },

    .MspRGrpGrid_fixedrow = ALIGNED_STRING("|-|PAD1|PAD2|PAD3|PAD4|PAD5|PAD6"),

    .MspRGrpGrid_fixedcol = ALIGNED_STRING("PADS|     BANK     |PHRASE"),

    .MspReGrpScreen_AcIndexEditSw = {
        .class_ = 0x0160001F,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 5,
        .prev = 3,
        .flag = 0x0008,
        .rect = { 44, 216, 75, 238 },
        .color = 0x0007,
        .border = 0x00C9,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0000,
        .editsw = 0x0001,
        .style = 0x000E,
    },

    .MspReGrpScreen_AcIndexWideES = {
        .class_ = 0x01600022,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 6,
        .prev = 4,
        .flag = 0x0008,
        .rect = { 124, 216, 195, 238 },
        .color = 0x0007,
        .border = 0x00C9,
        .index = 0x0001,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0000,
        .editsw = 0x0003,
        .editsw2 = 0x0004,
        .style = 0x0003,
    },

    .MspReGrpScreen_AcIndexWideES_2 = {
        .class_ = 0x01600022,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 7,
        .prev = 5,
        .flag = 0x0008,
        .rect = { 244, 216, 313, 238 },
        .color = 0x0007,
        .border = 0x00C9,
        .index = 0x0002,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0000,
        .editsw = 0x0006,
        .editsw2 = 0x0007,
        .style = 0x0003,
    },

    .RgpSetBnk = {
        .class_ = 0x01640017,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 8,
        .prev = 6,
        .flag = 0x0008,
        .rect = { 52, 34, 171, 49 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .MspReGrpScreen_IvShowHide = {
        .class_ = 0x01600064,
        .super = 0,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 7,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .func = 0x01240018,
    },

    .SndArgrScreen = {
        .class_ = 0x01600034,
        .super = NAKA_NONE,
        .sub = 1,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x000A,
        .rect = { 0, 0, 319, 239 },
        .color = 0x00F9,
        .border = 0x0000,
        .exit = 0x01A00001,
        .window = 0x0003D792,
        .title = SELF(SoundArranger_text),
        .icon = 0x00000058,
    },

    .SoundArranger_text = ALIGNED_STRING("SOUND ARRANGER"),

    .Pattern_StringBox = {
        .class_ = 0x01600037,
        .super = 0,
        .sub = 2,
        .next = 3,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 45, 36, 274, 62 },
        .color = 0x00F5,
        .border = 0x00C1,
        .str = SELF(Pattern_str),
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .alignment = 0x0001,
    },

    .Pattern_str = ALIGNED_STRING(" PATTERN :"),

    .SndArgRhyName = {
        .class_ = 0x01640013,
        .super = 1,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 135, 40, 269, 58 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .SndArgrScreen_IvExitMode = {
        .class_ = 0x01600048,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 4,
        .prev = 1,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .mode = 0x01800001,
    },

    .SndArgrScreen_IvShowHide = {
        .class_ = 0x01600064,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 5,
        .prev = 3,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .func = 0x01240011,
    },

    .SndArgrGrid = {
        .class_ = 0x01640020,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 6,
        .prev = 4,
        .flag = 0x0008,
        .rect = { 4, 94, 313, 239 },
        .color = 0x00F5,
        .border = 0x00C1,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .row = 0x0008,
        .col = 0x0003,
        .vertline = 0x0001,
        .selrow = 0x0003D796,
        .selcol = 0x0003D798,
        .pcol = 0x0003D79A,
        .prow = 0x0003D79E,
        .crow = 0x0003D7A2,
        .fixedcol = SELF(SndArgrGrid_fixedcol),
        .fixedrow = SELF(SndArgrGrid_fixedrow),
        .func = 0x01240012,
    },

    .SndArgrGrid_fixedrow = "|-|DRUMS|BASS|ACCOMP1|ACCOMP2|ACCOMP3",

    .SndArgrGrid_fixedcol = ALIGNED_STRING("   PART  |       SOUND       |D.EFFECT"),

    .SndArgrScreen_AcIndexWideES = {
        .class_ = 0x01600022,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 7,
        .prev = 5,
        .flag = 0x0008,
        .rect = { 8, 216, 79, 238 },
        .color = 0x0007,
        .border = 0x00C9,
        .index = 0x0000,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0000,
        .editsw = 0x0000,
        .editsw2 = 0x0001,
        .style = 0x000E,
    },

    .SndArgrScreen_AcLanguageText = {
        .class_ = 0x01600066,
        .super = 0,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 6,
        .flag = 0x0008,
        .rect = { 20, 68, 299, 91 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000007,
        .fontcolor = 0x00F1,
        .alignment = 0x0001,
        .lines = 0x0001,
        .func = 0x01240047,
    },

    .ApcSelScreen = {
        .class_ = 0x01600034,
        .super = NAKA_NONE,
        .sub = 1,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x000A,
        .rect = { 0, 0, 319, 239 },
        .color = 0x00FF,
        .border = 0x0000,
        .exit = 0x01A00000,
        .window = 0x0003D7A6,
        .title = SELF(AutoPlayChord_text),
        .icon = 0x00000071,
    },

    .AutoPlayChord_text = "AUTO PLAY CHORD",

    .ApcSelScreen_AcApcMdBox = {
        .class_ = 0x0164000E,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 2,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 8, 72, 156, 97 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0x0001,
        .caption = SELF(vED_e1_caption),
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .length = 0x0000,
        .editsw = 0x0089,
        .dial = 0x0001,
        .selected = 0x0003D7AA,
        .apcdata = 0x01,
        ._pad_51 = { 0x00 },
    },

    .vED_e1_caption = ALIGNED_STRING("ONE FINGER"),

    .ApcSelScreen_AcApcMdBox_2 = {
        .class_ = 0x0164000E,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 3,
        .prev = 1,
        .flag = 0x0008,
        .rect = { 8, 114, 156, 139 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0x0001,
        .caption = SELF(vED_e2_caption),
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .length = 0x0000,
        .editsw = 0x008A,
        .dial = 0x0001,
        .selected = 0x0003D7AC,
        .apcdata = 0x02,
        ._pad_51 = { 0x00 },
    },

    .vED_e2_caption = ALIGNED_STRING("FINGERED"),

    .ApcSelScreen_AcApcMdBox_3 = {
        .class_ = 0x0164000E,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 4,
        .prev = 2,
        .flag = 0x0008,
        .rect = { 8, 156, 156, 181 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0x0001,
        .caption = SELF(vED_e3_caption),
        .font = 0x00000000,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .length = 0x0000,
        .editsw = 0x008B,
        .dial = 0x0001,
        .selected = 0x0003D7AE,
        .apcdata = 0x03,
        ._pad_51 = { 0x00 },
    },

    .vED_e3_caption = "PIANIST",

    .ApcMem = {
        .class_ = 0x0164001F,
        .super = 0,
        .sub = NAKA_NONE,
        .next = 5,
        .prev = 3,
        .flag = 0x0008,
        .rect = { 196, 76, 311, 93 },
        .font = 0x00000000,
        .stron = SELF(ApcMem_stron),
        .stroff = SELF(ApcMem_stroff),
        .onoff = 0x0003D7B0,
        .editsw = 0x0009,
        .func = 0x0124000F,
        .pman_ad = 0x00000000,
    },

    .ApcMem_stroff = " MEMORY : OFF",

    .ApcMem_stron = ALIGNED_STRING(" MEMORY : ON"),

    .ApcOnBass = {
        .class_ = 0x0164001F,
        .super = 0,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = 4,
        .flag = 0x0008,
        .rect = { 196, 118, 311, 135 },
        .font = 0x00000000,
        .stron = SELF(ApcOnBass_stron),
        .stroff = SELF(ApcOnBass_stroff),
        .onoff = 0x0003D7B2,
        .editsw = 0x000A,
        .func = 0x01240010,
        .pman_ad = 0x00000001,
    },

    .ApcOnBass_stroff = "ON BASS : OFF",

    .ApcOnBass_stron = ALIGNED_STRING("ON BASS : ON"),

    .Suna_ViewableTable_010 = {
        NAKA_ADDR(NakaWidget_StylCnvWaitScreen),
        NAKA_ADDR(NakaWidget_StylCnvWaitScreen_1_VwBox),
        NAKA_ADDR(NakaWidget_StylCnvWaitScreen_2_AcLanguageText),
        0x00000000,
    },

    .Suna_ViewableTable_011 = {
        NAKA_ADDR(NakaWidget_StylCnvModlScreen),
        NAKA_ADDR(NakaWidget_StylCnvModlScreen_1_IvMainEditSw),
        NAKA_ADDR(NakaWidget_StylCnvModlBox),
        NAKA_ADDR(NakaWidget_StylCnvModlScreen_3_VwEditSwBox),
        NAKA_ADDR(NakaWidget_StylCnvModlScreen_4_VwWideESBox),
        NAKA_ADDR(NakaWidget_StylCnvModlScreen_5_VwEditSwBox),
        NAKA_ADDR(NakaWidget_StylCnvModlScreen_6_VwEditSwBox),
        NAKA_ADDR(NakaWidget_StylCnvVer),
        0x00000000,
    },

    .Suna_ViewableTable_012 = {
        NAKA_ADDR(NakaWidget_StylCnvCnvtScreen),
        NAKA_ADDR(NakaWidget_StylCnvCnvtScreen_1_IvMainEditSw),
        NAKA_ADDR(NakaWidget_StylCnvCnvtBox),
        NAKA_ADDR(NakaWidget_StylCnvCnvtScreen_3_VwEditSwBox),
        NAKA_ADDR(NakaWidget_StylCnvCnvtScreen_4_VwWideESBox),
        NAKA_ADDR(NakaWidget_StylCnvCnvtScreen_5_VwEditSwBox),
        NAKA_ADDR(NakaWidget_StylCnvCnvtScreen_6_VwEditSwBox),
        0x00000000,
    },

    .Suna_ViewableTable_013 = {
        NAKA_ADDR(NakaWidget_StylCnvStorScreen),
        NAKA_ADDR(NakaWidget_StylCnvStorScreen_1_AcRamEditBox),
        NAKA_ADDR(NakaWidget_StylCnvStorScreen_2_AcIndexWideES),
        NAKA_ADDR(NakaWidget_StylCnvStorScreen_3_AcFuncEditSw),
        0x00000000,
    },

    .Suna_ViewableTable_014 = {
        NAKA_ADDR(NakaWidget_StylCnvTxtScreen),
        NAKA_ADDR(NakaWidget_StylCnvTxtScreen_1_VwBox),
        NAKA_ADDR(NakaWidget_StylCnvTxtScreen_2_PSSCTxtBox2),
        NAKA_ADDR(NakaWidget_StylCnvTxtScreen_3_IvMainEditSw),
        0x00000000,
    },

    .Suna_ViewableTable_015 = {
        NAKA_ADDR(NakaWidget_StylCnvSelScreen),
        NAKA_ADDR(NakaWidget_StylCnvSelScreen_1_IvMainEditSw),
        NAKA_ADDR(NakaWidget_StylCnvSelBox),
        NAKA_ADDR(NakaWidget_StylCnvSelScreen_3_VwEditSwBox),
        NAKA_ADDR(NakaWidget_StylCnvSelScreen_4_VwWideESBox),
        NAKA_ADDR(NakaWidget_StylCnvSelScreen_5_VwEditSwBox),
        NAKA_ADDR(NakaWidget_StylCnvSelScreen_6_VwEditSwBox),
        NAKA_ADDR(NakaWidget_StylCnvSelScreen_7_PsSCTxtBox),
        0x00000000,
    },

    .Suna_ViewableTable_016 = {
        NAKA_ADDR(NakaWidget_StylCnvContScreen),
        NAKA_ADDR(NakaWidget_StylCnvContScreen_1_IvMainEditSw),
        NAKA_ADDR(NakaWidget_StylCnvContScreen_2_VwBox),
        NAKA_ADDR(NakaWidget_StylCnvContScreen_3_Label),
        NAKA_ADDR(NakaWidget_StylCnvContScreen_4_Label),
        NAKA_ADDR(NakaWidget_StylCnvContScreen_5_VwEditSwBox),
        NAKA_ADDR(NakaWidget_StylCnvContScreen_6_VwEditSwBox),
        0x00000000,
    },

    .Suna_ViewableTable_0B0 = {
        NAKA_ADDR(NakaWidget_CmpMenuScreen),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_1_AcTitleMenu),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_2_AcTitleMenu),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_3_AcTitleMenu),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_4_AcTitleMenu),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_5_AcTitleMenu),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_6_AcTitleMenu),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_7_Line),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_8_Line),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_9_Line),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_10_Line),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_11_Label),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_12_Label),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_13_IvMainEditSw),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_14_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_15_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_16_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpMenuScreen_17_IvExitMode),
        0x00000000,
    },

    .Suna_ViewableTable_0B1 = {
        NAKA_ADDR(NakaWidget_CmpBkslScreen),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_1_IvMainEditSw),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_2_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_3_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_4_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_5_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_6_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_7_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_8_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_9_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_10_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslScreen_11_VwMenuBox),
        0x00000000,
    },

    .Suna_ViewableTable_0B2 = {
        NAKA_ADDR(NakaWidget_CmpBkslSScreen),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_1_Box),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_2_Label),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_3_IvMainEditSw),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_4_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_5_VwEditSwBox),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_6_VwEditSwBox),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_7_VwEditSwBox),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_8_VwEditSwBox),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_9_VwEditSwBox),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_10_AcMemNoBox),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_11_Label),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_12_Line),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_13_Line),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_14_Line),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_15_Line),
        NAKA_ADDR(NakaWidget_CmpNameMenu),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_17_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpClrSure),
        NAKA_ADDR(NakaWidget_CmpClrYesSw),
        NAKA_ADDR(NakaWidget_CmpClrNoSw),
        NAKA_ADDR(NakaWidget_CmpBkslSScreen_21_AcLanguageText),
        0x00000000,
    },

    .Suna_ViewableTable_0B3 = {
        NAKA_ADDR(NakaWidget_CmpNamingScreen),
        NAKA_ADDR(NakaWidget_CmpNamingScreen_1_IvNaming),
        NAKA_ADDR(NakaWidget_CmpNamingScreen_2_AcFuncEditSw),
        NAKA_ADDR(NakaWidget_NameMemLabel),
        NAKA_ADDR(NakaWidget_NamingMem),
        0x00000000,
    },

    .Suna_ViewableTable_0B4 = {
        NAKA_ADDR(NakaWidget_CmpSetScreen),
        NAKA_ADDR(NakaWidget_CmpSetScreen_1_IvMainEditSw),
        NAKA_ADDR(NakaWidget_CmSetPage),
        NAKA_ADDR(NakaWidget_CmSetP1Ctl),
        NAKA_ADDR(NakaWidget_CmSetP2Ctl),
        NAKA_ADDR(NakaWidget_CmpSetScreen_5_IvShowHide),
        NAKA_ADDR(NakaWidget_CmSetPage1),
        NAKA_ADDR(NakaWidget_CmSetP1Grid),
        NAKA_ADDR(NakaWidget_CmpSetScreen_8_Label),
        NAKA_ADDR(NakaWidget_CmpSetScreen_9_AcIndexWideES),
        NAKA_ADDR(NakaWidget_CmpSetScreen_10_AcIndexWideES),
        NAKA_ADDR(NakaWidget_CmpSetScreen_11_Label),
        NAKA_ADDR(NakaWidget_CmpSetScreen_12_Label),
        NAKA_ADDR(NakaWidget_CmSetPage2),
        NAKA_ADDR(NakaWidget_CmpSetGrid),
        NAKA_ADDR(NakaWidget_CmSetPartSw),
        NAKA_ADDR(NakaWidget_CmSetPanSw),
        NAKA_ADDR(NakaWidget_CmSetRLmtSw),
        0x00000000,
    },

    .Suna_ViewableTable_0B5 = {
        NAKA_ADDR(NakaWidget_CmpRealScreen), NAKA_ADDR(NakaWidget_CmpRealScreen_1_Box), NAKA_ADDR(NakaWidget_CmpMem), NAKA_ADDR(NakaWidget_CmpRealScreen_3_Label),
        NAKA_ADDR(NakaWidget_CmpRealScreen_4_Label), NAKA_ADDR(NakaWidget_CmpRealScreen_5_Label), NAKA_ADDR(NakaWidget_CmpRealScreen_6_Label), NAKA_ADDR(NakaWidget_CmpRealScreen_7_Label),
        NAKA_ADDR(NakaWidget_CmpRealScreen_8_Label), NAKA_ADDR(NakaWidget_CmpRealScreen_9_IvMainEditSw), NAKA_ADDR(NakaWidget_CmpRealScreen_10_VwEditSwBox), NAKA_ADDR(NakaWidget_CmpRealScreen_11_VwEditSwBox),
        NAKA_ADDR(NakaWidget_CmpRealScreen_12_VwEditSwBox), NAKA_ADDR(NakaWidget_CmpRealScreen_13_VwEditSwBox), NAKA_ADDR(NakaWidget_CmpRealScreen_14_VwEditSwBox), NAKA_ADDR(NakaWidget_CmpRealScreen_15_AcCmpTempoBox),
        NAKA_ADDR(NakaWidget_CmpRealScreen_16_AcTitleMenu), NAKA_ADDR(NakaWidget_CmpRealScreen_17_AcTitleMenu), NAKA_ADDR(NakaWidget_CmpRealScreen_18_AcMemNoBox), NAKA_ADDR(NakaWidget_CmpRealScreen_19_VwMenuBox),
        NAKA_ADDR(NakaWidget_CmpRealScreen_20_VwMenuBox), NAKA_ADDR(NakaWidget_CmpRealScreen_21_VwMenuBox), NAKA_ADDR(NakaWidget_CmpRealScreen_22_VwMenuBox), NAKA_ADDR(NakaWidget_CmpRealScreen_23_VwMenuBox),
        0x0003D7B4, 0x0003D7DA, 0x0003D800, 0x0003D826,
        0x0003D84C, NAKA_ADDR(NakaWidget_CmpQtz), NAKA_ADDR(NakaWidget_CmpMeas), 0x00000000,
    },

    .Suna_ViewableTable_0B6 = {
        NAKA_ADDR(NakaWidget_SunaView0B6_0_IvDirmdScreen),
        0x00000000,
    },

    .Suna_ViewableTable_0B7 = {
        NAKA_ADDR(NakaWidget_CmpBalScreen),
        NAKA_ADDR(NakaWidget_CmpDrmVol),
        NAKA_ADDR(NakaWidget_CmpAc3Vol),
        NAKA_ADDR(NakaWidget_CmpAc2Vol),
        NAKA_ADDR(NakaWidget_CmpAc1Vol),
        NAKA_ADDR(NakaWidget_CmpBasVol),
        0x00000000,
    },

    .Suna_ViewableTable_0B8 = {
        NAKA_ADDR(NakaWidget_CmpNcpScreen),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_1_IvMainEditSw),
        NAKA_ADDR(NakaWidget_CmpNcpFitmSw),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_3_VwWideESBox),
        NAKA_ADDR(NakaWidget_CmpNcpTitmSw),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_5_VwWideESBox),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_6_Label),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_7_Label),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_8_Line),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_9_Line),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_10_Line),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_11_Line),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_12_Label),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_13_Line),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_14_Line),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_15_Line),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_16_Line),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_17_Box),
    },

    .field_0c76 = 0xD872,

    .field_0c78 = 0x0003,

    .ptrs_3 = {
        NAKA_ADDR(NakaWidget_CmpNcpScreen_19_Label),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_20_Label),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_21_Label),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_22_Label),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_23_Label),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_24_VwEditSwBox),
        NAKA_ADDR(NakaWidget_CmpNcpScreen_25_Box),
    },

};

#undef SELF
#undef BASE
