/**
 * naka_sequencer_exit.c — Sequencer exit/mode widget descriptors
 *
 * 14 compact dispatch widgets for sequencer exit controls:
 * real-time recording exit, auto-punch, EQ on/off, DSP/reverb modes,
 * panel write, help, play exit, song copy, and more.
 *
 * Base ROM address: 0xE272A4
 * Total size: 692 bytes
 * Auto-generated by scripts/gen_sequencer_exit.py
 */

#include "naka_types.h"

/* ── External symbols (addresses resolved by linker script) ── */

/* Linked widget descriptors */
extern const char NakaDesc_FuncTtlNo_B;
extern const char NakaDesc_Empty_C;
extern const char NakaDesc_Empty_D;
extern const char NakaDesc_FuncIndex;
extern const char NakaDesc_Mode;
extern const char NakaDesc_ColorFontPageFunc;
extern const char NakaDesc_SeqExitWidgets;
extern const char NakaDesc_Empty_E;
extern const char NakaDesc_Empty_F;
extern const char NakaDesc_Empty_G;
extern const char NakaDesc_Empty_H;
extern const char NakaDesc_Empty_I;
extern const char NakaDesc_StyleFunc;
extern const char NakaDesc_Empty_J;

/* Proc handler functions */
extern const char EqOnOffFuncToggleProc;
extern const char MsgToTtlProc;
extern const char AcIndexWideToggleProc;
extern const char IvPlayExitProc;
extern const char HelpTtlProc;
extern const char IvPnlWrExitProc;
extern const char IvSdrevProc;
extern const char IvSddspProc;
extern const char IvSdaccProc;
extern const char IvPunchExitProc;
extern const char IvAutoPunchExitProc;
extern const char AcPanicEditSwProc;
extern const char IvRealRecExitProc;

/* ── Struct layout ──────────────────────────────────────────── */

/* A NAKA class definition (24 bytes).  Its field names are the firmware's
 * own: the root class "Class" (class id 0x01600004) names them in its
 * propname block -- proc, parent, allsize, selfsize, name, propdata,
 * propname -- and ClassProc (ui/ui_widget_defs.s) indexes a registered
 * Class table with 24 * (class id & 0xFFFF).  parent is the parent's class
 * id; allsize the instance size (parent.allsize + selfsize, the root Object
 * contributing nothing); propdata one type character per own field;
 * propname points at len(propdata) + 1 field-name pointers, the last to an
 * empty string (THE CLASS SYSTEM, scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t proc;        /* +0  J  class procedure */
    uint32_t parent;      /* +4  M  parent class id */
    uint16_t allsize;     /* +8  B  instance size */
    uint16_t selfsize;    /* +10 B  size of the own fields */
    uint32_t name;        /* +12 X  class name string */
    uint32_t propdata;    /* +16 X  field type characters */
    uint32_t propname;    /* +20 L  field-name pointer block */
} naka_classdef_t;

typedef struct __attribute__((packed)) {
    /* 14 dispatch widgets (14 × 24 = 336 bytes) */
    /* class definition 0x168:12: NoteEditBox -- the part of the record in this blob (the rest is in the neighbouring blob) */
    uint32_t classdef_168_12_parent;
    uint16_t classdef_168_12_allsize;
    uint16_t classdef_168_12_selfsize;
    uint32_t classdef_168_12_name;
    uint32_t classdef_168_12_propdata;
    uint32_t classdef_168_12_propname;
    /* class definition 0x168:13: EqOnOffFuncToggle (parent AcFuncToggle, allsize 44, fields -) */
    naka_classdef_t classdef_168_13;
    /* class definition 0x168:14: MsgToTtl (parent Viewable, allsize 22, fields -) */
    naka_classdef_t classdef_168_14;
    /* class definition 0x168:15: AcIndexWideToggle (parent PsWideToggle, allsize 50, fields index, tag, func) */
    naka_classdef_t classdef_168_15;
    /* class definition 0x168:16: IvPlayExit (parent IvExit, allsize 26, fields mode) */
    naka_classdef_t classdef_168_16;
    /* class definition 0x168:17: HelpTtl (parent Viewable, allsize 36, fields color, fontcolor, font, page, func) */
    naka_classdef_t classdef_168_17;
    /* class definition 0x168:18: IvPnlWrExit (parent IvExit, allsize 22, fields -) */
    naka_classdef_t classdef_168_18;
    /* class definition 0x168:19: IvSdrev (parent PsInvisibleBox, allsize 22, fields -) */
    naka_classdef_t classdef_168_19;
    /* class definition 0x168:20: IvSddsp (parent PsInvisibleBox, allsize 22, fields -) */
    naka_classdef_t classdef_168_20;
    /* class definition 0x168:21: IvSdacc (parent PsInvisibleBox, allsize 22, fields -) */
    naka_classdef_t classdef_168_21;
    /* class definition 0x168:22: IvPunchExit (parent IvExit, allsize 22, fields -) */
    naka_classdef_t classdef_168_22;
    /* class definition 0x168:23: IvAutoPunchExit (parent IvExit, allsize 22, fields -) */
    naka_classdef_t classdef_168_23;
    /* class definition 0x168:24: AcPanicEditSw (parent PsWideESBox, allsize 46, fields style, func) */
    naka_classdef_t classdef_168_24;
    /* class definition 0x168:25: IvRealRecExit (parent IvExit, allsize 22, fields -) */
    naka_classdef_t classdef_168_25;
    uint32_t classrun_168_x014C;

    /* Zero padding (20 bytes) */
    uint8_t padding[20];

    /* NakaInst_ string blocks: code + name per instance */
    char IvRealRecExit_code[2];
    char IvRealRecExit_name[14];
    char AcPanicEditSw_code[4];
    char AcPanicEditSw_name[14];
    char IvAutoPunchExit_code[2];
    char IvAutoPunchExit_name[16];
    char IvPunchExit_code[2];
    char IvPunchExit_name[12];
    char IvSdacc_code[2];
    char IvSdacc_name[8];
    char IvSddsp_code[2];
    char IvSddsp_name[8];
    char IvSdrev_code[2];
    char IvSdrev_name[8];
    char IvPnlWrExit_code[2];
    char IvPnlWrExit_name[12];
    char HelpTtl_code[6];
    char HelpTtl_name[8];
    char IvPlayExit_code[2];
    char IvPlayExit_name[12];
    char AcIndexWideToggle_code[4];
    char AcIndexWideToggle_name[18];
    char MsgToTtl_code[2];
    char MsgToTtl_name[10];
    char EqOnOffFuncToggle_code[2];
    char EqOnOffFuncToggle_name[18];
    char NoteEditBox_code[4];
    char NoteEditBox_name[12];
    char SngSel2_code[2];
    char SngSel2_name[8];
    char SngSel_code[6];
    char SngSel_name[8];
    char AcEntertainerGridBox_code[4];
    char AcEntertainerGridBox_name[22];
    char AccIll_code[6];
    char AccIll_name[8];
    char SqedtVal3_code[4];
    char SqedtVal3_name[10];
    char SqplyVal_code[6];
    char SqplyVal_name[10];
    char IvSongCopyExit_code[2];
    char IvSongCopyExit_name[16];
    char SqedtFix_code[4];
    char SqedtFix_name[10];
    char SqedtVal2_End_code[2];
} naka_sequencer_exit_t;

#define BASE  0x00E272A4u
#define SELF(field) \
    ((uint32_t)(BASE + __builtin_offsetof(naka_sequencer_exit_t, field)))

_Static_assert(sizeof(naka_sequencer_exit_t) == 692,
    "naka_sequencer_exit must be exactly 692 bytes");

const naka_sequencer_exit_t naka_sequencer_exit_data
    __attribute__((section(".text"), used)) = {

    /* w0: TYPE_GROUP — NoteEditBox */
/* w1: TYPE_0x44 — EqOnOffFuncToggle */
    /* w2: TYPE_0x10 — MsgToTtl */
    /* w3: TYPE_0x45 — AcIndexWideToggle */
    /* w4: TYPE_0x47 — IvPlayExit */
    /* w5: TYPE_0x10 — HelpTtl */
    /* w6: TYPE_0x47 — IvPnlWrExit */
    /* w7: TYPE_0x27 — IvSdrev */
    /* w8: TYPE_0x27 — IvSddsp */
    /* w9: TYPE_0x27 — IvSdacc */
    /* w10: TYPE_0x47 — IvPunchExit */
    /* w11: TYPE_0x47 — IvAutoPunchExit */
    /* w12: TYPE_0x21 — AcPanicEditSw */
    /* w13: TYPE_0x47 — IvRealRecExit */
    .classdef_168_12_parent = 0x01600031,

    .classdef_168_12_allsize = 0x0020,

    .classdef_168_12_selfsize = 0x0006,

    .classdef_168_12_name = SELF(NoteEditBox_name),

    .classdef_168_12_propdata = SELF(NoteEditBox_code),

    .classdef_168_12_propname = NAKA_ADDR(NakaDesc_FuncTtlNo_B),

    .classdef_168_13 = { .proc = NAKA_ADDR(EqOnOffFuncToggleProc), .parent = 0x01600044, .allsize = 44, .selfsize = 0, .name = SELF(EqOnOffFuncToggle_name), .propdata = SELF(EqOnOffFuncToggle_code), .propname = NAKA_ADDR(NakaDesc_Empty_C) },

    .classdef_168_14 = { .proc = NAKA_ADDR(MsgToTtlProc), .parent = 0x01600010, .allsize = 22, .selfsize = 0, .name = SELF(MsgToTtl_name), .propdata = SELF(MsgToTtl_code), .propname = NAKA_ADDR(NakaDesc_Empty_D) },

    .classdef_168_15 = { .proc = NAKA_ADDR(AcIndexWideToggleProc), .parent = 0x01600045, .allsize = 50, .selfsize = 8, .name = SELF(AcIndexWideToggle_name), .propdata = SELF(AcIndexWideToggle_code), .propname = NAKA_ADDR(NakaDesc_FuncIndex) },

    .classdef_168_16 = { .proc = NAKA_ADDR(IvPlayExitProc), .parent = 0x01600047, .allsize = 26, .selfsize = 4, .name = SELF(IvPlayExit_name), .propdata = SELF(IvPlayExit_code), .propname = NAKA_ADDR(NakaDesc_Mode) },

    .classdef_168_17 = { .proc = NAKA_ADDR(HelpTtlProc), .parent = 0x01600010, .allsize = 36, .selfsize = 14, .name = SELF(HelpTtl_name), .propdata = SELF(HelpTtl_code), .propname = NAKA_ADDR(NakaDesc_ColorFontPageFunc) },

    .classdef_168_18 = { .proc = NAKA_ADDR(IvPnlWrExitProc), .parent = 0x01600047, .allsize = 22, .selfsize = 0, .name = SELF(IvPnlWrExit_name), .propdata = SELF(IvPnlWrExit_code), .propname = NAKA_ADDR(NakaDesc_SeqExitWidgets) },

    .classdef_168_19 = { .proc = NAKA_ADDR(IvSdrevProc), .parent = 0x01600027, .allsize = 22, .selfsize = 0, .name = SELF(IvSdrev_name), .propdata = SELF(IvSdrev_code), .propname = NAKA_ADDR(NakaDesc_Empty_E) },

    .classdef_168_20 = { .proc = NAKA_ADDR(IvSddspProc), .parent = 0x01600027, .allsize = 22, .selfsize = 0, .name = SELF(IvSddsp_name), .propdata = SELF(IvSddsp_code), .propname = NAKA_ADDR(NakaDesc_Empty_F) },

    .classdef_168_21 = { .proc = NAKA_ADDR(IvSdaccProc), .parent = 0x01600027, .allsize = 22, .selfsize = 0, .name = SELF(IvSdacc_name), .propdata = SELF(IvSdacc_code), .propname = NAKA_ADDR(NakaDesc_Empty_G) },

    .classdef_168_22 = { .proc = NAKA_ADDR(IvPunchExitProc), .parent = 0x01600047, .allsize = 22, .selfsize = 0, .name = SELF(IvPunchExit_name), .propdata = SELF(IvPunchExit_code), .propname = NAKA_ADDR(NakaDesc_Empty_H) },

    .classdef_168_23 = { .proc = NAKA_ADDR(IvAutoPunchExitProc), .parent = 0x01600047, .allsize = 22, .selfsize = 0, .name = SELF(IvAutoPunchExit_name), .propdata = SELF(IvAutoPunchExit_code), .propname = NAKA_ADDR(NakaDesc_Empty_I) },

    .classdef_168_24 = { .proc = NAKA_ADDR(AcPanicEditSwProc), .parent = 0x01600021, .allsize = 46, .selfsize = 6, .name = SELF(AcPanicEditSw_name), .propdata = SELF(AcPanicEditSw_code), .propname = NAKA_ADDR(NakaDesc_StyleFunc) },

    .classdef_168_25 = { .proc = NAKA_ADDR(IvRealRecExitProc), .parent = 0x01600047, .allsize = 22, .selfsize = 0, .name = SELF(IvRealRecExit_name), .propdata = SELF(IvRealRecExit_code), .propname = NAKA_ADDR(NakaDesc_Empty_J) },

    .classrun_168_x014C = 0x00000000,

    /* Zero padding */
    .padding = { 0 },

    /* ── NakaInst_ string data ────────────────────────────── */

    /* NakaInst_IvRealRecExit */
    .IvRealRecExit_code = ALIGNED_STRING(""),
    .IvRealRecExit_name = "IvRealRecExit",

    /* NakaInst_AcPanicEditSw */
    .AcPanicEditSw_code = ALIGNED_STRING("fj"),
    .AcPanicEditSw_name = "AcPanicEditSw",

    /* NakaInst_IvAutoPunchExit */
    .IvAutoPunchExit_code = ALIGNED_STRING(""),
    .IvAutoPunchExit_name = "IvAutoPunchExit",

    /* NakaInst_IvPunchExit */
    .IvPunchExit_code = ALIGNED_STRING(""),
    .IvPunchExit_name = "IvPunchExit",

    /* NakaInst_IvSdacc */
    .IvSdacc_code = ALIGNED_STRING(""),
    .IvSdacc_name = "IvSdacc",

    /* NakaInst_IvSddsp */
    .IvSddsp_code = ALIGNED_STRING(""),
    .IvSddsp_name = "IvSddsp",

    /* NakaInst_IvSdrev */
    .IvSdrev_code = ALIGNED_STRING(""),
    .IvSdrev_name = "IvSdrev",

    /* NakaInst_IvPnlWrExit */
    .IvPnlWrExit_code = ALIGNED_STRING(""),
    .IvPnlWrExit_name = "IvPnlWrExit",

    /* NakaInst_HelpTtl */
    .HelpTtl_code = "^^cGj",
    .HelpTtl_name = "HelpTtl",

    /* NakaInst_IvPlayExit */
    .IvPlayExit_code = "`",
    .IvPlayExit_name = ALIGNED_STRING("IvPlayExit"),

    /* NakaInst_AcIndexWideToggle */
    .AcIndexWideToggle_code = "AAj",
    .AcIndexWideToggle_name = "AcIndexWideToggle",

    /* NakaInst_MsgToTtl */
    .MsgToTtl_code = ALIGNED_STRING(""),
    .MsgToTtl_name = ALIGNED_STRING("MsgToTtl"),

    /* NakaInst_EqOnOffFuncToggle */
    .EqOnOffFuncToggle_code = ALIGNED_STRING(""),
    .EqOnOffFuncToggle_name = "EqOnOffFuncToggle",

    /* NakaInst_NoteEditBox */
    .NoteEditBox_code = ALIGNED_STRING("jC"),
    .NoteEditBox_name = "NoteEditBox",

    /* NakaInst_SngSel2 */
    .SngSel2_code = ALIGNED_STRING(""),
    .SngSel2_name = "SngSel2",

    /* NakaInst_SngSel */
    .SngSel_code = "c^^jC",
    .SngSel_name = ALIGNED_STRING("SngSel"),

    /* NakaInst_AcEntertainerGridBox */
    .AcEntertainerGridBox_code = "XXj",
    .AcEntertainerGridBox_name = ALIGNED_STRING("AcEntertainerGridBox"),

    /* NakaInst_AccIll */
    .AccIll_code = ALIGNED_STRING("^^jC"),
    .AccIll_name = ALIGNED_STRING("AccIll"),

    /* NakaInst_SqedtVal3 */
    .SqedtVal3_code = "^^j",
    .SqedtVal3_name = "SqedtVal3",

    /* NakaInst_SqplyVal */
    .SqplyVal_code = ALIGNED_STRING("^^jC"),
    .SqplyVal_name = ALIGNED_STRING("SqplyVal"),

    /* NakaInst_IvSongCopyExit */
    .IvSongCopyExit_code = ALIGNED_STRING(""),
    .IvSongCopyExit_name = ALIGNED_STRING("IvSongCopyExit"),

    /* NakaInst_SqedtFix */
    .SqedtFix_code = "^^_",
    .SqedtFix_name = ALIGNED_STRING("SqedtFix"),

    .SqedtVal2_End_code = { 0x5E, 0x5E },

};

#undef SELF
#undef BASE
