# Computer interface routines label renames
s/LABEL_F74B3D/ComputerConnectionTitleExit/g
s/LABEL_F74B86/CmptCnctDrawConnectionDiagram/g
s/LABEL_F74C0A/CmptCnctBitmapDrawComplete/g
s/LABEL_F74C12/CmptCnctInvalidInputReturn/g
s/LABEL_F74C19/CmptCnctBlockingReturn/g
s/LABEL_F74C4E/PcgModeGridEventStart/g
s/LABEL_F74C6A/PcgModeDisplayString_Bank1/g
s/LABEL_F74C7C/PcgModeDefaultCase/g
s/LABEL_F74D50/SetupLoadOptionJumpTable/g
s/LABEL_F74D7A/SetupLoadInvalidIndex/g
s/LABEL_F7743B/PcgOutGridBoxEventDispatch/g
s/LABEL_F775EF/PcgOutGridDialConfirm/g
s/LABEL_F776BD/PcgOutGridCheckJumpTable/g
s/LABEL_F77B46/PcgOutCheckGridDataStructure/g
s/LABEL_F77D83/PcgOutGridCheckComplete/g
