# File I/O routines label renames
s/LABEL_F8CAAC/SelectPasswordMode/g
s/LABEL_F8D4D0/RenderFilterDisplay/g
s/LABEL_F8D784/RenderSaveFilterDisplay/g
s/LABEL_F8DD75/RenderSmfFilename/g
s/LABEL_F8DF96/TrimAndPadSmfFilename/g
s/LABEL_F8E048/ValidateSmfFilename/g
s/LABEL_F8DFD2/DisplaySmfFileList/g
s/LABEL_F8E8B9/DisplaySmfSequenceList/g
s/LABEL_F95448/DrawString_Centered/g
s/LABEL_F8B19C/ResetProgressIndication/g
s/LABEL_F8B204/InitializeOperationState/g
s/LABEL_F8B260/SignalProgressUpdate/g
s/LABEL_F8B244/CancelOperationCleanup/g
s/LABEL_F89605/NotifyUIOfSelectionChange/g
s/LABEL_F8943E/CheckFileSystemStatus/g
s/LABEL_F895EF/GetCurrentFileIndex/g
s/LABEL_F89520/GetDiskSizeInfo/g
s/LABEL_F8987D/GetEncodedFileSizeData/g
s/LABEL_F8953B/GetEncodedFreeSpaceData/g
s/LABEL_F89C78/GetFileCountEncoded/g
