# MIDI encoder routines label renames
s/Encoder_Mode5/Encoder_ConfigureVolumeMode/g
s/Encoder_Mode6/Encoder_ConfigureRangeLimit/g
s/Encoder_ModeSelect/Encoder_ApplySystemModeSettings/g
s/Encoder_Volume_NoChange/Encoder_ProcessVolume_NoChange/g
s/Encoder_Clamp_OK/Encoder_PerformScaling/g
s/Encoder_Breath_Process/Encoder_ProcessBreath_WithModeAdjustment/g
s/Encoder_Breath_Simple/Encoder_ProcessBreath_SimplePassthrough/g
s/Encoder_Breath_Done/Encoder_ProcessBreath_Return/g
s/Encoder_ClampToRange/Encoder_ClampScaleAndNormalize/g
s/Encoder_ReturnValue/Encoder_PassthroughIdentity/g
s/Encoder_ReturnOne/Encoder_ReturnDefaultConstant/g
