# SubCPU boot ROM label renames
s/SUB_8437/TONE_GEN_CHANNEL_INIT/g
s/STUB_8496/OUTPUT_NOP_RET/g
s/SUB_850E/WRITE_TONE_REG_MULTI_CHANNEL/g
s/SUB_853A/WRITE_TONE_REG_SINGLE_CHANNEL/g
s/SUB_8B37/CONTROL_PANEL_BIT_SET_CLEAR/g
s/SUB_8B89/INTER_CPU_LATCH_READ_DISPATCH/g
s/SUB_8BD2/NOTE_VELOCITY_LOOKUP_CALCULATE/g
s/SUB_8C75/AUDIO_HW_WRITE_READ/g
s/SUB_8C80/HARDWARE_CALIBRATION_SEQUENCE/g
s/SUB_8D0A/HARDWARE_PARAM_BLOCK_WRITE/g
s/SUB_8F57/HARDWARE_VERIFY_WRITE/g
s/SUB_FE80/DEBUG_OUTPUT_BYTE_HEX/g
s/SUB_FE86/HEX_BYTE_TO_ASCII/g
s/SUB_FEA1/DEBUG_OUTPUT_STRING/g
s/SUB_FEB4/NIBBLE_TO_HEX_ASCII/g
