#!/usr/bin/env python3
"""name_wsa1_ram.py -- WSA1 CPU-1 RAM variables whose meaning a findings note establishes get a name.

QUESTION THIS ANSWERS / JOB IT DOES
  prom_a and prom_b (one CPU, one RAM) address their variables by number: `ld (0x2540:16), 0`,
  `ld (9536:16), 0` (prom_b spells addresses in decimal), `m_add_rm MW16, 0x2555, r4`.  Where a
  wsa1/notes FINDINGS table establishes what an address holds -- with the routine or service that
  establishes it -- the address gets a name in wsa1/include/wsa1_ram.inc (generated here from NAMES),
  and the memory operands and the macro address arguments that spell it become the name.
  Only memory operands `(N)` / `(N:16)` and the address argument of the m_* macros
  (`MB16|MW16|MD16, N`) change: an immediate equal to the number may be a value, and data
  (`.byte` / `.short`) is left alone.  Comments keep the numbers -- the WSA1 tools read
  `; F8E85F  f1 58 25 41` and the evidence headers cite `(0x2540)`.
  prom_c is another CPU with its own RAM: its sources are not touched, and it does not include
  wsa1_ram.inc.  Same bytes: `make gate-all`.

USAGE
  python3 scripts/tools/name_wsa1_ram.py [--apply]
"""
import argparse
import glob
import os
import re
import subprocess
import sys

REPO = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True,
                      text=True).stdout.strip() or "."
INC = "wsa1/include/wsa1_ram.inc"
SOURCES = ["wsa1/prom_a/wsa1_prom_a.s", "wsa1/prom_b/wsa1_prom_b.s"] + \
    sorted(glob.glob(os.path.join(REPO, "wsa1/maincpu/shared/*.s")))

# address: (name, what it holds, where established).  Source of every row:
# wsa1/notes/FINDINGS-display-controller.md, "The drawing state, as it now stands".
DISPLAY = "wsa1/notes/FINDINGS-display-controller.md"
NAMES = {
    0x2530: ("LCD_X0", "box / line X0; clamped to 319", "the clamp"),
    0x2532: ("LCD_Y0", "box / line Y0; clamped to 239", "the clamp"),
    0x2534: ("LCD_X1", "box / line X1", "the clamp"),
    0x2536: ("LCD_Y1", "box / line Y1", "the clamp"),
    0x2540: ("LCD_CurrentLayer", "the layer being drawn into, 0..2", "LCD_SelectCurrentLayer"),
    0x2541: ("LCD_Layer0_SAD", "layer 0's SED1330 screen start address", "LCD_Init_SED1330 writes it"),
    0x2543: ("LCD_Layer1_SAD", "layer 1's SED1330 screen start address", "LCD_Init_SED1330 writes it"),
    0x2545: ("LCD_Layer2_SAD", "layer 2's SED1330 screen start address", "LCD_Init_SED1330 writes it"),
    0x2547: ("LCD_LineFlags", "bit 0: the line draw's X and Y are swapped", "LCD_Line_ChooseMajorAxis"),
    0x2548: ("LCD_LineSlopeX100", "line slope x 100", "LCD_Line_ComputeSlope"),
    0x254A: ("LCD_LineInterceptX100", "line intercept x 100", "LCD_Line_ComputeIntercept"),
    0x2550: ("LCD_PlotX", "X of the point being plotted", "LCD_PlotPointAt reads it"),
    0x2552: ("LCD_PlotY", "Y of the point being plotted", "LCD_PlotPointAt reads it"),
    0x2554: ("LCD_OvlayShadow", "shadow of the SED1330 OVLAY parameter", "service 0x05 masks it with 0xFC"),
    0x2555: ("LCD_CurrentLayerBase", "display-RAM base of the current layer", "LCD_SelectCurrentLayer writes it"),
    0x2557: ("LCD_BytesPerLine", "SED1330 AP, bytes per line (40); 16-bit, low byte", "the plotter multiplies Y by it"),
    0x2558: ("LCD_BytesPerLine_Hi", "AP's high byte, written on its own by services 0x0F / 0x10", "services 0x0F and 0x10"),
    0x2559: ("LCD_DispOnOffShadow", "the last DISP ON/OFF parameter", "service 0x0C"),
    0x255A: ("LCD_RunAddress", "display address of the run being drawn", "services 0x01, 0x05, 0x11"),
    0x255C: ("LCD_SavedX0", "X0 saved across a shadowed box", "services 0x0A, 0x22"),
    0x255E: ("LCD_SavedY0", "Y0 saved across a shadowed box", "services 0x0A, 0x22"),
    0x2560: ("LCD_SavedX1", "X1 saved across a shadowed box", "services 0x0A, 0x22"),
    0x2562: ("LCD_SavedY1", "Y1 saved across a shadowed box", "services 0x0A, 0x22"),
}
MEM = re.compile(r'\((0x[0-9a-fA-F]+|\d+)(:16)?\)')
MAC = re.compile(r'\b(MB16|MW16|MD16),(\s*)(0x[0-9a-fA-F]+|\d+)\b')


def inc_text():
    out = ["; wsa1_ram.inc -- names of CPU-1 RAM variables (prom_a + prom_b share the CPU and its RAM).",
           "; Generated by scripts/tools/name_wsa1_ram.py from its NAMES table; edit there.",
           "; Every row is established in %s, \"The drawing state," % DISPLAY,
           "; as it now stands\" (CS1 static RAM, 16-bit unless said otherwise); the last column",
           "; names what establishes it.  Not included by prom_c, which is another CPU.", ""]
    col = (len(".equ ") + max(len(n) for n, _, _ in NAMES.values()) + 1) // 8 * 8 + 8

    def tabs(text):
        return text + "\t" * ((col - len(text) + 7) // 8)

    for a, (n, what, by) in sorted(NAMES.items()):
        out.append("\t%s0x%04x\t; %s -- %s" % (tabs(".equ %s," % n), a, what, by))
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    total = 0
    for f in SOURCES:
        p = f if os.path.isabs(f) else os.path.join(REPO, f)
        L = open(p, "rb").read().decode("latin-1").split("\n")
        n = 0
        for i, l in enumerate(L):
            code, sep, cmt = l.partition(";")
            s = code.strip()
            if not s or s.startswith(".") or re.match(r'^[\w.$]+:\s*$', s):
                continue

            def mem(m):
                v = int(m.group(1), 0)
                return "(%s%s)" % (NAMES[v][0], m.group(2) or "") if v in NAMES else m.group(0)

            def mac(m):
                v = int(m.group(3), 0)
                return "%s,%s%s" % (m.group(1), m.group(2), NAMES[v][0]) if v in NAMES else m.group(0)

            new = MAC.sub(mac, MEM.sub(mem, code))
            if new != code:
                n += len([1 for x in MEM.finditer(code) if int(x.group(1), 0) in NAMES]) + \
                    len([1 for x in MAC.finditer(code) if int(x.group(3), 0) in NAMES])
                L[i] = new + sep + cmt
        if n and a.apply:
            if os.path.basename(p) in ("wsa1_prom_a.s", "wsa1_prom_b.s") and \
                    not any('"include/wsa1_ram.inc"' in x for x in L):
                k = next(j for j, x in enumerate(L) if '.include "include/tlcs900_mem_ops.inc"' in x)
                L.insert(k + 1, '\t.include "include/wsa1_ram.inc"')
            open(p, "wb").write("\n".join(L).encode("latin-1"))
        print("%-45s %4d operands" % (os.path.relpath(p, REPO), n))
        total += n
    print("%d operands%s" % (total, "" if a.apply else " (dry run)"))
    if a.apply:
        open(os.path.join(REPO, INC), "w").write(inc_text())
    return 0


if __name__ == "__main__":
    sys.exit(main())
