#!/usr/bin/env python3
"""Decode caches for the refusal-bucket probe.

QUESTION ANSWERED: none on its own. It is the piece `classify.py` needs.

Two caches, both keyed by TARGET ADDRESS and both TOPPED UP rather than
rebuilt, so switching between the seed and the closure target lists costs only
the addresses not seen yet:

  `load()`      what the CONVERTER sees -- `crr.decode_range()`'s output, which
                stops at the first `db` or terminator. Seeded from the class-A
                sweep's committed `../class-a-sweep/decodes.pkl` (687 entries)
                so those are never re-decoded.
  `load_raw()`  the FULL unidasm listing of each target's run, `db` lines
                included, plus the run length. The converter's decode cannot say
                WHY it stopped; this can.

⚠ WHICH TARGET LIST. `analysis/v7-reachability/v7_call_targets.json` (687) is
committed and stable; `v7_branch_closure_targets.json` is REGENERATED by the
reachability pass and moved from 1,131 to 1,109 entries while this probe was
being written. Numbers from the closure list are numbers about one moment in
that file's life, so `classify.py` prints the file's sha256 and entry count with
every run and defaults to the SEED list.

Both pickles are disposable (see `.gitignore`): delete to force a rebuild, about
20 s for the seed list and 40 s for the closure list -- one unidasm per target.
"""
import hashlib, json, os, pickle, sys

REPO = "/home/fsanches/compartilhado/kn5000-roms-disasm"
HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "decodes.pkl")
RAW = os.path.join(HERE, "raw_listings.pkl")
CLASS_A = os.path.join(HERE, os.pardir, "class-a-sweep", "decodes.pkl")
FILES = {"seed": os.path.join(REPO, "analysis/v7-reachability/v7_call_targets.json"),
         "closure": os.path.join(REPO,
                                 "analysis/v7-reachability/v7_branch_closure_targets.json")}


def targets(which="seed"):
    """Return (sorted target list, provenance dict) for "seed" or "closure"."""
    path = FILES[which]
    raw = open(path, "rb").read()
    return (sorted(json.loads(raw)["targets"]),
            {"which": which, "file": os.path.relpath(path, REPO),
             "sha256": hashlib.sha256(raw).hexdigest()[:16],
             "count": len(json.loads(raw)["targets"])})


def _terr(crr):
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "spans", os.path.join(REPO, "scripts/analysis/v7_undisassembled_spans.py"))
    spans = importlib.util.module_from_spec(spec); spec.loader.exec_module(spans)
    return spans.territory(spans.runs("v7/maincpu/kn5000_v7_program.s", "v7/maincpu"))


def load(crr, want, verbose=True):
    """{target: [(addr, nbytes, text), ...]} exactly as the converter decodes it."""
    have = pickle.load(open(CACHE, "rb")) if os.path.exists(CACHE) else {}
    if not have and os.path.exists(CLASS_A):
        have = pickle.load(open(CLASS_A, "rb"))
        if verbose:
            print(f"  seeded from class-a-sweep cache: {len(have)} decodes", file=sys.stderr)
    missing = [t for t in want if t not in have]
    if missing:
        rom = open(os.path.join(REPO, "original_ROMs", "kn5000_v7_program.rom"), "rb").read()
        terr = _terr(crr)
        for i, t in enumerate(missing):
            have[t] = crr.decode_range(rom, terr, t)
            if verbose and i % 200 == 0:
                print(f"  decoding {i}/{len(missing)}", file=sys.stderr)
        pickle.dump(have, open(CACHE, "wb"))
    return have


def load_raw(crr, want, verbose=True):
    """{target: {"run": N, "lines": [(addr, nbytes, text), ...], "raw": str}}.

    `lines` is EVERY line unidasm printed for the run, `db` lines included
    (`nbytes` counts the bytes shown on the line). `run` is the length of the
    undisassembled-territory run starting at the target, capped at the
    converter's own 16,384-byte limit, so `run == 16384` means "capped".
    """
    import re, subprocess, tempfile
    have = pickle.load(open(RAW, "rb")) if os.path.exists(RAW) else {}
    missing = [t for t in want if t not in have]
    if missing:
        rom = open(os.path.join(REPO, "original_ROMs", "kn5000_v7_program.rom"), "rb").read()
        terr = _terr(crr)
        scratch = tempfile.mkdtemp(prefix="kn5000_raw_")
        tmp = os.path.join(scratch, "r.bin")
        LINE = re.compile(r'^([0-9a-f]+):\s+((?:[0-9a-f]{2} )+)\s*(.*)$')
        for i, t in enumerate(missing):
            off = t - crr.BASE
            end = off
            while end < len(terr) and terr[end] == 2 and end - off < 16384:
                end += 1
            open(tmp, "wb").write(rom[off:end])
            txt = subprocess.run([crr.UNIDASM, tmp, "-arch", "tlcs900", "-basepc", hex(t)],
                                 capture_output=True, text=True, timeout=120).stdout
            lines = [(int(m.group(1), 16), len(m.group(2).split()), m.group(3).strip())
                     for m in (LINE.match(ln) for ln in txt.split("\n")) if m]
            have[t] = {"run": end - off, "lines": lines, "raw": txt}
            if verbose and i % 200 == 0:
                print(f"  raw listing {i}/{len(missing)}", file=sys.stderr)
        pickle.dump(have, open(RAW, "wb"))
    return have
