/**
 * se_name_editor — Screen Layout Data
 *
 * Base address: 0xF131E5
 * Size: 218 bytes, 18 commands
 *
 * Auto-generated by screendata_parser.py
 */

#include "screendata_types.h"
#include <stddef.h>

/* Handler data tables (resolved by linker via se_screens_link.ld) */
extern const char SE_TuningSystem_Names;
extern const char SE_NoteDivision_Names;
extern const char SE_NameEditor_CursorCoords_0;
extern const char SE_NameEditor_CursorCoords_1;
extern const char SE_NameEdit_ParamAddr_R1A;
extern const char SE_NameEdit_ParamAddr_R1B;
extern const char SE_NameEdit_ParamAddr_R2A;
extern const char SE_NameEdit_ParamAddr_R2B;
extern const char SE_NameEdit_ParamAddr_R3A;
extern const char SE_NameEdit_ParamAddr_R3B;
extern const char SE_NameEdit_ParamAddr_R4A;
extern const char SE_NameEdit_ParamAddr_R4B;
extern const char SE_NameEdit_TableData_0;
extern const char SE_NameEdit_TableData_1;
extern const char SE_NameEdit_TableData_2;

#define HANDLER_ADDR(sym) ((uint32_t)&(sym))

typedef struct __attribute__((packed)) {
	sd_block_hdr_t                 setup5_0;  /* id=0x0661 DRAM param R1A */
	sd_block_hdr_t                 setup5_1;  /* id=0x0662 DRAM param R1B */
	sd_widget_t                    widget_0;  /* note division names (88,13) */
	sd_block_hdr_t                 setup5_2;  /* id=0x0664 DRAM param R2A */
	sd_block_hdr_t                 setup5_3;  /* id=0x0665 DRAM param R2B */
	sd_widget_t                    widget_1;  /* note division names (88,18) */
	sd_block_hdr_t                 setup5_4;  /* id=0x0667 DRAM param R3A */
	sd_block_hdr_t                 setup5_5;  /* id=0x0668 DRAM param R3B */
	sd_widget_t                    widget_2;  /* note division names (88,23) */
	sd_block_hdr_t                 setup5_6;  /* id=0x066a DRAM param R4A */
	sd_block_hdr_t                 setup5_7;  /* id=0x066b DRAM param R4B */
	sd_widget_t                    widget_3;  /* note division names (88,28) */
	sd_widget_t                    widget_4;  /* tuning system names (223,10) */
	sd_block_hdr_t                 setup5_8;  /* id=0x066f table data ROM 0 */
	sd_block_hdr_t                 setup5_9;  /* id=0x0670 table data ROM 1 */
	sd_block_hdr_t                 setup5_10;  /* id=0x0670 table data ROM 2 */
	sd_block_hdr_t                 setup_0;  /* id=0x0660 cursor coords 0 */
	sd_block_hdr_t                 setup_1;  /* id=0x066d cursor coords 1 */
} screendata_se_name_editor_t;

_Static_assert(sizeof(screendata_se_name_editor_t) == 218,
	"se_name_editor must be exactly 218 bytes");

#define SE_NAME_EDITOR_BASE  0x00F131E5u
#define SD_PTR(field)  (SE_NAME_EDITOR_BASE + offsetof(screendata_se_name_editor_t, field))

const screendata_se_name_editor_t se_name_editor
	__attribute__((section(".text"), used)) = {
	.setup5_0 = { .type = 0x05, .length = 0x0b, .id = 0x0661, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_ParamAddr_R1A) },
	.setup5_1 = { .type = 0x05, .length = 0x0b, .id = 0x0662, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_ParamAddr_R1B) },
	.widget_0 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x0663, .flags = 0x0007, .ref_tag = 0x20, .handler = HANDLER_ADDR(SE_NoteDivision_Names), .param = 4, .x = 88, .y = 13 },
	.setup5_2 = { .type = 0x05, .length = 0x0b, .id = 0x0664, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_ParamAddr_R2A) },
	.setup5_3 = { .type = 0x05, .length = 0x0b, .id = 0x0665, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_ParamAddr_R2B) },
	.widget_1 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x0666, .flags = 0x0007, .ref_tag = 0x20, .handler = HANDLER_ADDR(SE_NoteDivision_Names), .param = 4, .x = 88, .y = 18 },
	.setup5_4 = { .type = 0x05, .length = 0x0b, .id = 0x0667, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_ParamAddr_R3A) },
	.setup5_5 = { .type = 0x05, .length = 0x0b, .id = 0x0668, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_ParamAddr_R3B) },
	.widget_2 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x0669, .flags = 0x0007, .ref_tag = 0x20, .handler = HANDLER_ADDR(SE_NoteDivision_Names), .param = 4, .x = 88, .y = 23 },
	.setup5_6 = { .type = 0x05, .length = 0x0b, .id = 0x066a, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_ParamAddr_R4A) },
	.setup5_7 = { .type = 0x05, .length = 0x0b, .id = 0x066b, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_ParamAddr_R4B) },
	.widget_3 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x066c, .flags = 0x0007, .ref_tag = 0x20, .handler = HANDLER_ADDR(SE_NoteDivision_Names), .param = 4, .x = 88, .y = 28 },
	.widget_4 = { .opcode = 0x02, .subtype = 0x0f, .id = 0x066e, .flags = 0x001f, .ref_tag = 0x20, .handler = HANDLER_ADDR(SE_TuningSystem_Names), .param = 8, .x = 223, .y = 10 },
	.setup5_8 = { .type = 0x05, .length = 0x0b, .id = 0x066f, .flags = 0x000f, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_TableData_0) },
	.setup5_9 = { .type = 0x05, .length = 0x0b, .id = 0x0670, .flags = 0x04f0, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_TableData_1) },
	.setup5_10 = { .type = 0x05, .length = 0x0b, .id = 0x0670, .flags = 0x000f, .tag = 0x20, .handler = HANDLER_ADDR(SE_NameEdit_TableData_2) },
	.setup_0 = { .type = SD_BLOCK_SETUP, .length = 0x0b, .id = 0x0660, .flags = 0x0007, .tag = 0x05, .handler = HANDLER_ADDR(SE_NameEditor_CursorCoords_0) },
	.setup_1 = { .type = SD_BLOCK_SETUP, .length = 0x0b, .id = 0x066d, .flags = 0x000f, .tag = 0x05, .handler = HANDLER_ADDR(SE_NameEditor_CursorCoords_1) },
};
