/**
 * se_setup_env — Screen Layout Data
 *
 * Base address: 0xF11E96
 * Size: 107 bytes, 13 commands
 *
 * Auto-generated by screendata_parser.py
 */

#include "screendata_types.h"
#include <stddef.h>

typedef struct __attribute__((packed)) {
	SD_LABELED_REF_TYPE(7)         labeled_ref_0;  /* "PAGE1/2" */
	SD_UNKNOWN_TYPE(9)             param_label_0;  /* "C>LEVEL" */
	SD_UNKNOWN_TYPE(9)             param_label_1;  /* "s>TOUCH" */
	SD_UNKNOWN_TYPE(9)             param_label_2;  /* ">CURVE" */
	SD_UNKNOWN_TYPE(9)             param_label_3;  /* "NLEVEL" */
	SD_UNKNOWN_TYPE(9)             param_label_4;  /* "|TOUCH" */
	SD_UNKNOWN_TYPE(9)             param_label_5;  /* "CURVE" */
	SD_LABELED_REF_TYPE(1)         labeled_ref_1;
	SD_LABELED_REF_TYPE(1)         labeled_ref_2;
	SD_LABELED_REF_TYPE(1)         labeled_ref_3;
	SD_LABELED_REF_TYPE(1)         labeled_ref_4;
	SD_LABELED_REF_TYPE(1)         labeled_ref_5;
	SD_LABELED_REF_TYPE(1)         labeled_ref_6;
} screendata_se_setup_env_t;

_Static_assert(sizeof(screendata_se_setup_env_t) == 107,
	"se_setup_env must be exactly 107 bytes");

#define SE_SETUP_ENV_BASE  0x00F11E96u
#define SD_PTR(field)  (SE_SETUP_ENV_BASE + offsetof(screendata_se_setup_env_t, field))

const screendata_se_setup_env_t se_setup_env
	__attribute__((section(".text"), used)) = {
	.labeled_ref_0 = { .opcode = SD_OP_LABELED_REF, .length = 11, .addr = 0x0110, .label = { 'P', 'A', 'G', 'E', '1', '/', '2' } },
	.param_label_0 = { .opcode = 0x17, .length = 0x0b, .data = { 0x43, 0x00, 0x3e, 0x00, 0x4c, 0x45, 0x56, 0x45, 0x4c } },
	.param_label_1 = { .opcode = 0x17, .length = 0x0b, .data = { 0x73, 0x00, 0x3e, 0x00, 0x54, 0x4f, 0x55, 0x43, 0x48 } },
	.param_label_2 = { .opcode = 0x17, .length = 0x0b, .data = { 0xa3, 0x00, 0x3e, 0x00, 0x43, 0x55, 0x52, 0x56, 0x45 } },
	.param_label_3 = { .opcode = 0x17, .length = 0x0b, .data = { 0x4e, 0x00, 0xd1, 0x00, 0x4c, 0x45, 0x56, 0x45, 0x4c } },
	.param_label_4 = { .opcode = 0x17, .length = 0x0b, .data = { 0x7c, 0x00, 0xd1, 0x00, 0x54, 0x4f, 0x55, 0x43, 0x48 } },
	.param_label_5 = { .opcode = 0x17, .length = 0x0b, .data = { 0xa5, 0x00, 0xd1, 0x00, 0x43, 0x55, 0x52, 0x56, 0x45 } },
	.labeled_ref_1 = { .opcode = SD_OP_LABELED_REF, .length = 5, .addr = 0x221b, .label = { LCD_CHAR_VBAR } },
	.labeled_ref_2 = { .opcode = SD_OP_LABELED_REF, .length = 5, .addr = 0x2221, .label = { LCD_CHAR_VBAR } },
	.labeled_ref_3 = { .opcode = SD_OP_LABELED_REF, .length = 5, .addr = 0x2226, .label = { LCD_CHAR_VBAR } },
	.labeled_ref_4 = { .opcode = SD_OP_LABELED_REF, .length = 5, .addr = 0x23ab, .label = { LCD_CHAR_DARROW } },
	.labeled_ref_5 = { .opcode = SD_OP_LABELED_REF, .length = 5, .addr = 0x23b1, .label = { LCD_CHAR_DARROW } },
	.labeled_ref_6 = { .opcode = SD_OP_LABELED_REF, .length = 5, .addr = 0x23b6, .label = { LCD_CHAR_DARROW } },
};
