/**
 * se_screen_f140ef — Screen Layout Data
 *
 * Base address: 0xF140EF
 * Size: 180 bytes, 20 commands
 *
 * Auto-generated by screendata_parser.py
 */

#include "screendata_types.h"
#include <stddef.h>

typedef struct __attribute__((packed)) {
	sd_rect_t                      rect_0;  /* (69,204)-(251,233) */
	SD_LABELED_REF_TYPE(9)         labeled_ref_0;  /* "KEY LAYER" */
	SD_UNKNOWN_TYPE(5)             param_label_0;  /* "9*0" */
	SD_UNKNOWN_TYPE(5)             param_label_1;  /* "T*1" */
	SD_UNKNOWN_TYPE(5)             param_label_2;  /* "q*2" */
	SD_UNKNOWN_TYPE(5)             param_label_3;  /* "*3" */
	SD_UNKNOWN_TYPE(5)             param_label_4;  /* "*4" */
	SD_UNKNOWN_TYPE(5)             param_label_5;  /* "*5" */
	SD_UNKNOWN_TYPE(5)             param_label_6;  /* "*6" */
	sd_rect_t                      rect_1;  /* (39,98)-(246,99) */
	sd_rect_t                      rect_2;  /* (39,129)-(246,130) */
	sd_rect_t                      rect_3;  /* (39,160)-(246,161) */
	sd_rect_t                      rect_4;  /* (39,191)-(246,192) */
	sd_boundary_block_t            select_rect_0;  /* (262,68)-(306,94) */
	SD_LABELED_REF_TYPE(14)        labeled_ref_1;  /* "VELOCITY LAYER" */
	SD_UNKNOWN_TYPE(5)             param_label_7;  /* "-20" */
	SD_UNKNOWN_TYPE(6)             param_label_8;  /* "[232" */
	SD_UNKNOWN_TYPE(6)             param_label_9;  /* "264" */
	SD_UNKNOWN_TYPE(6)             param_label_10;  /* "296" */
	SD_UNKNOWN_TYPE(7)             param_label_11;  /* "3127" */
} screendata_se_screen_f140ef_t;

_Static_assert(sizeof(screendata_se_screen_f140ef_t) == 180,
	"se_screen_f140ef must be exactly 180 bytes");

#define SE_SCREEN_F140EF_BASE  0x00F140EFu
#define SD_PTR(field)  (SE_SCREEN_F140EF_BASE + offsetof(screendata_se_screen_f140ef_t, field))

const screendata_se_screen_f140ef_t se_screen_f140ef
	__attribute__((section(".text"), used)) = {
	.rect_0 = { .opcode = SD_OP_RECT, .length = 0x0a, .top_left = { .x = 69, .y = 204 }, .bottom_right = { .x = 251, .y = 233 } },
	.labeled_ref_0 = { .opcode = SD_OP_LABELED_REF, .length = 13, .addr = 0x04bd, .label = { 'K', 'E', 'Y', ' ', 'L', 'A', 'Y', 'E', 'R' } },
	.param_label_0 = { .opcode = 0x17, .length = 0x07, .data = { 0x39, 0x00, 0x2a, 0x00, 0x30 } },
	.param_label_1 = { .opcode = 0x17, .length = 0x07, .data = { 0x54, 0x00, 0x2a, 0x00, 0x31 } },
	.param_label_2 = { .opcode = 0x17, .length = 0x07, .data = { 0x71, 0x00, 0x2a, 0x00, 0x32 } },
	.param_label_3 = { .opcode = 0x17, .length = 0x07, .data = { 0x8d, 0x00, 0x2a, 0x00, 0x33 } },
	.param_label_4 = { .opcode = 0x17, .length = 0x07, .data = { 0xa9, 0x00, 0x2a, 0x00, 0x34 } },
	.param_label_5 = { .opcode = 0x17, .length = 0x07, .data = { 0xc5, 0x00, 0x2a, 0x00, 0x35 } },
	.param_label_6 = { .opcode = 0x17, .length = 0x07, .data = { 0xe1, 0x00, 0x2a, 0x00, 0x36 } },
	.rect_1 = { .opcode = SD_OP_RECT, .length = 0x0a, .top_left = { .x = 39, .y = 98 }, .bottom_right = { .x = 246, .y = 99 } },
	.rect_2 = { .opcode = SD_OP_RECT, .length = 0x0a, .top_left = { .x = 39, .y = 129 }, .bottom_right = { .x = 246, .y = 130 } },
	.rect_3 = { .opcode = SD_OP_RECT, .length = 0x0a, .top_left = { .x = 39, .y = 160 }, .bottom_right = { .x = 246, .y = 161 } },
	.rect_4 = { .opcode = SD_OP_RECT, .length = 0x0a, .top_left = { .x = 39, .y = 191 }, .bottom_right = { .x = 246, .y = 192 } },
	.select_rect_0 = { .type = 0x05, .length = 0x0a, .p1 = { .x = 262, .y = 68 }, .p2 = { .x = 306, .y = 94 } },
	.labeled_ref_1 = { .opcode = SD_OP_LABELED_REF, .length = 18, .addr = 0x055b, .label = { 'V', 'E', 'L', 'O', 'C', 'I', 'T', 'Y', ' ', 'L', 'A', 'Y', 'E', 'R' } },
	.param_label_7 = { .opcode = 0x17, .length = 0x07, .data = { 0x2d, 0x00, 0x32, 0x00, 0x30 } },
	.param_label_8 = { .opcode = 0x17, .length = 0x08, .data = { 0x5b, 0x00, 0x32, 0x00, 0x33, 0x32 } },
	.param_label_9 = { .opcode = 0x17, .length = 0x08, .data = { 0x8a, 0x00, 0x32, 0x00, 0x36, 0x34 } },
	.param_label_10 = { .opcode = 0x17, .length = 0x08, .data = { 0xba, 0x00, 0x32, 0x00, 0x39, 0x36 } },
	.param_label_11 = { .opcode = 0x17, .length = 0x09, .data = { 0xe4, 0x00, 0x33, 0x00, 0x31, 0x32, 0x37 } },
};
