/**
 * se_setup_sel4 — Screen Layout Data
 *
 * Base address: 0xF1659F
 * Size: 10 bytes, 1 commands
 *
 * Auto-generated by screendata_parser.py
 */

#include "screendata_types.h"
#include <stddef.h>

typedef struct __attribute__((packed)) {
	sd_boundary_block_t            boundary_0;  /* (12,59)-(307,208) */
} screendata_se_setup_sel4_t;

_Static_assert(sizeof(screendata_se_setup_sel4_t) == 10,
	"se_setup_sel4 must be exactly 10 bytes");

#define SE_SETUP_SEL4_BASE  0x00F1659Fu
#define SD_PTR(field)  (SE_SETUP_SEL4_BASE + offsetof(screendata_se_setup_sel4_t, field))

const screendata_se_setup_sel4_t se_setup_sel4
	__attribute__((section(".text"), used)) = {
	.boundary_0 = { .type = 0x1b, .length = 0x0a, .p1 = { .x = 12, .y = 59 }, .p2 = { .x = 307, .y = 208 } },
};
