/**
 * naka_sound_menu_drawbar.c — NAKA widget descriptors (fully decoded)
 *
 * Base ROM address: 0xE80FE2
 * Total size: 2314 bytes
 * Auto-generated by scripts/naka_struct_decode.py
 */

#include "naka_types.h"

/* ── External symbols (resolved by linker script) ── */

extern const char AcAccordionTabProc;
extern const char AcDrawEditBoxProc;
extern const char AcDrawSettingProc;
extern const char AcDrawbarNameProc;
extern const char AcFdemoScreenProc;
extern const char AcLswPartEditBoxProc;
extern const char AcLswPartPanProc;
extern const char AcPartMixerProc;
extern const char AcPleaseWaitProc;
extern const char AcPresentationBoxProc;
extern const char AcPresentationControlProc;
extern const char AcResetPageProc;
extern const char AcSndEMenuProc;
extern const char AcTrackMixerProc;
extern const char AcVolPartEditBoxProc;
extern const char AcWelcomScreenProc;
extern const char IvAccordionProc;
extern const char IvAccordionXProc;
extern const char IvDemofeature1Proc;
extern const char IvDemofeature2Proc;
extern const char IvDrawbar1Proc;
extern const char IvDrawbar2Proc;
extern const char IvDrawbarNormProc;
extern const char IvDrawbarProc;
extern const char IvDrawbarSndEProc;
extern const char IvMPverProc;
extern const char IvMesageProc;
extern const char IvPageOverWriteProc;
extern const char IvSdpartProc;
extern const char IvSdscltyp2Proc;
extern const char IvSdtecd1Proc;
extern const char IvSdtecdProc;
extern const char IvSoftverProc;
extern const char Naka_PresentationRootState;
extern const char PsLabelBoxProc;
extern const char PsMixerControlProc;
extern const char PsVariBoxProc;
extern const char VwUserBitmapSpProc;

#define BASE  0x00E80FE2u

typedef struct __attribute__((packed)) {
    naka_dispatch_t w0;  /* NAKA_TYPE_CONTAINER */
    naka_dispatch_t w1;  /* 0x40 */
    naka_dispatch_t w2;  /* 0x12 */
    naka_dispatch_t w3;  /* 0x26 */
    naka_dispatch_t w4;  /* 0x12 */
    naka_dispatch_t w5;  /* 0x27 */
    uint8_t pad_0[21];  /* zero padding */
    uint16_t field_00a5;
    char str_0[7];
    char AcDrawbarName_code[4];
    char AcDrawbarName_name[14];
    char AcDrawSetting_code[4];
    char AcDrawSetting_name[14];
    char AcPleaseWait_code[2];
    char AcPleaseWait_name[14];
    char AcSndEMenu_code[2];
    char AcSndEMenu_name[12];
    char AcFdemoScreen_code[2];
    char AcFdemoScreen_name[14];
    char w11_code[2];
    char w11_name[16];
    char w12_code[6];
    char w12_name[18];
    char w13_code[4];
    char w13_name[14];
    char w14_code[2];
    char w14_name[14];
    char w15_code[2];
    char w15_name[16];
    char w16_code[2];
    char w16_name[16];
    char w17_code[2];
    char w17_name[22];
    char w18_code[6];
    char w18_name[10];
    char w19_code[2];
    char w19_name[12];
    char w20_code[2];
    char w20_name[14];
    char w21_code[2];
    char w21_name[14];
    char w22_code[2];
    char w22_name[12];
    char w23_code[2];
    char w23_name[12];
    char w24_code[2];
    char w24_name[10];
    char w25_code[4];
    char w25_name[16];
    char w26_code[2];
    char w26_name[10];
    char w27_code[2];
    char w27_name[14];
    char w28_code[2];
    char w28_name[12];
    char w29_code[2];
    char w29_name[16];
    char w30_code[2];
    char w30_name[16];
    char w31_code[2];
    char w31_name[12];
    char w32_code[2];
    char w32_name[10];
    char w33_code[2];
    char w33_name[10];
    char w34_code[8];
    char w34_name[12];
    char w35_code[4];
    char w35_name[16];
    char w36_code[2];
    char w36_name[14];
    char w37_code[2];
    char w37_name[12];
    char w38_code[2];
    char w38_name[10];
    char w39_code[4];
    char w39_name[18];
    char w40_code[4];
    char w40_name[18];
    char w41_code[2];
    char w41_name[10];
    char str_1[2];
    uint32_t ptrs_0[11];  /* 11 pointers */
    char str_2[14];
    char str_3[12];
    char str_4[20];
    char str_5[12];
    char str_6[14];
    char str_7[14];
    char str_8[12];
    char str_9[14];
    char str_10[20];
    char str_11[16];
    uint16_t field_03c2;
    uint32_t ptrs_1[16];  /* 16 pointers */
    char str_12[16];
    char str_13[20];
    char str_14[20];
    char str_15[22];
    char str_16[20];
    char str_17[24];
    char str_18[16];
    char str_19[20];
    char str_20[22];
    char str_21[12];
    char str_22[14];
    char str_23[20];
    char str_24[14];
    char str_25[16];
    char str_26[12];
    uint16_t field_0510;
    uint32_t ptrs_2[76];  /* 76 pointers */
    char w42_code[2];
    char w42_name[12];
    char str_27[18];
    char str_28[18];
    char str_29[18];
    char str_30[16];
    char str_31[18];
    char str_32[20];
    char str_33[22];
    char str_34[18];
    char str_35[18];
    char str_36[20];
    char str_37[20];
    char str_38[26];
    char str_39[14];
    char str_40[16];
    char str_41[18];
    char str_42[18];
    char str_43[16];
    char str_44[16];
    char str_45[14];
    char str_46[20];
    char str_47[14];
    char str_48[18];
    char str_49[16];
    char str_50[20];
    char str_51[20];
    char str_52[16];
    char str_53[14];
    char str_54[14];
    char str_55[16];
    char str_56[20];
    char str_57[18];
    char str_58[16];
    char str_59[14];
    char str_60[22];
    char str_61[22];
    char str_62[14];
    naka_container_t w43;  /* NAKA_TYPE_CONTAINER */
    char w43_text[12];
    char str_63[2];
    uint16_t field_0906;
    uint8_t pad_1[2];  /* zero padding */
} naka_sound_menu_drawbar_t;

#define SELF(field) \
    ((uint32_t)(BASE + __builtin_offsetof(naka_sound_menu_drawbar_t, field)))

_Static_assert(sizeof(naka_sound_menu_drawbar_t) == 2314,
    "naka_sound_menu_drawbar must be exactly 2314 bytes");

const naka_sound_menu_drawbar_t naka_sound_menu_drawbar_data
    __attribute__((section(".text"), used)) = {

    .w0 = {
        .header    = NAKA_HDR(NAKA_TYPE_CONTAINER),
        .field_04   = 0x002A,
        .field_06   = 0x0000,
        .name_ptr   = SELF(AcFdemoScreen_name),
        .inst_ptr   = SELF(AcFdemoScreen_code),
        .link_ptr   = 0x00E80CAA,
        .proc_addr  = NAKA_ADDR(AcSndEMenuProc),
    },

    .w1 = {
        .header    = NAKA_HDR(0x40),
        .field_04   = 0x0036,
        .field_06   = 0x0000,
        .name_ptr   = SELF(AcSndEMenu_name),
        .inst_ptr   = SELF(AcSndEMenu_code),
        .link_ptr   = 0x00E80CB0,
        .proc_addr  = NAKA_ADDR(AcPleaseWaitProc),
    },

    .w2 = {
        .header    = NAKA_HDR(0x12),
        .field_04   = 0x0024,
        .field_06   = 0x0000,
        .name_ptr   = SELF(AcPleaseWait_name),
        .inst_ptr   = SELF(AcPleaseWait_code),
        .link_ptr   = 0x00E80CB6,
        .proc_addr  = NAKA_ADDR(AcDrawSettingProc),
    },

    .w3 = {
        .header    = NAKA_HDR(0x26),
        .field_04   = 0x002C,
        .field_06   = 0x0004,
        .name_ptr   = SELF(AcDrawSetting_name),
        .inst_ptr   = SELF(AcDrawSetting_code),
        .link_ptr   = 0x00E80CBC,
        .proc_addr  = NAKA_ADDR(AcDrawbarNameProc),
    },

    .w4 = {
        .header    = NAKA_HDR(0x12),
        .field_04   = 0x0028,
        .field_06   = 0x0004,
        .name_ptr   = SELF(AcDrawbarName_name),
        .inst_ptr   = SELF(AcDrawbarName_code),
        .link_ptr   = 0x00E80CD4,
        .proc_addr  = NAKA_ADDR(IvMPverProc),
    },

    .w5 = {
        .header    = NAKA_HDR(0x27),
        .field_04   = 0x0016,
        .field_06   = 0x0000,
        .name_ptr   = 0x00E81088,
        .inst_ptr   = 0x00E81086,
        .link_ptr   = 0x00E80CF0,
        .proc_addr  = 0x00000000,
    },

    .pad_0 = { 0 },

    .field_00a5 = 0x49FF,

    .str_0 = ALIGNED_STRING("vMPver"),

    .AcDrawbarName_code = ALIGNED_STRING("ue"),

    .AcDrawbarName_name = "AcDrawbarName",

    .AcDrawSetting_code = ALIGNED_STRING("AA"),

    .AcDrawSetting_name = "AcDrawSetting",

    .AcPleaseWait_code = ALIGNED_STRING(""),

    .AcPleaseWait_name = ALIGNED_STRING("AcPleaseWait"),

    .AcSndEMenu_code = ALIGNED_STRING(""),

    .AcSndEMenu_name = ALIGNED_STRING("AcSndEMenu"),

    .AcFdemoScreen_code = ALIGNED_STRING(""),

    .AcFdemoScreen_name = "AcFdemoScreen",

    .w11_code = ALIGNED_STRING(""),

    .w11_name = ALIGNED_STRING("VwUserBitmapSp"),

    .w12_code = ALIGNED_STRING("XemA"),

    .w12_name = "AcPresentationBox",

    .w13_code = ALIGNED_STRING("jn"),

    .w13_name = ALIGNED_STRING("AcLswPartPan"),

    .w14_code = ALIGNED_STRING(""),

    .w14_name = "AcDrawEditBox",

    .w15_code = ALIGNED_STRING(""),

    .w15_name = ALIGNED_STRING("IvDemofeature2"),

    .w16_code = ALIGNED_STRING(""),

    .w16_name = ALIGNED_STRING("IvDemofeature1"),

    .w17_code = ALIGNED_STRING(""),

    .w17_name = "AcPresentationControl",

    .w18_code = "c^dem",

    .w18_name = "PsVariBox",

    .w19_code = ALIGNED_STRING(""),

    .w19_name = "AcResetPage",

    .w20_code = ALIGNED_STRING(""),

    .w20_name = "IvDrawbarSndE",

    .w21_code = ALIGNED_STRING(""),

    .w21_name = "IvDrawbarNorm",

    .w22_code = ALIGNED_STRING(""),

    .w22_name = ALIGNED_STRING("IvDrawbar2"),

    .w23_code = ALIGNED_STRING(""),

    .w23_name = ALIGNED_STRING("IvDrawbar1"),

    .w24_code = ALIGNED_STRING(""),

    .w24_name = "IvDrawbar",

    .w25_code = ALIGNED_STRING("At"),

    .w25_name = "IvPageOverWrite",

    .w26_code = ALIGNED_STRING(""),

    .w26_name = "IvSoftver",

    .w27_code = ALIGNED_STRING(""),

    .w27_name = ALIGNED_STRING("AcTrackMixer"),

    .w28_code = ALIGNED_STRING(""),

    .w28_name = "AcPartMixer",

    .w29_code = ALIGNED_STRING(""),

    .w29_name = ALIGNED_STRING("PsMixerControl"),

    .w30_code = ALIGNED_STRING(""),

    .w30_name = ALIGNED_STRING("AcWelcomScreen"),

    .w31_code = ALIGNED_STRING(""),

    .w31_name = "IvSdscltyp2",

    .w32_code = ALIGNED_STRING(""),

    .w32_name = "IvSdtecd1",

    .w33_code = ALIGNED_STRING(""),

    .w33_name = ALIGNED_STRING("IvSdtecd"),

    .w34_code = ALIGNED_STRING("Xc^dmm"),

    .w34_name = ALIGNED_STRING("PsLabelBox"),

    .w35_code = ALIGNED_STRING("XX"),

    .w35_name = ALIGNED_STRING("AcAccordionTab"),

    .w36_code = ALIGNED_STRING(""),

    .w36_name = ALIGNED_STRING("IvAccordionX"),

    .w37_code = ALIGNED_STRING(""),

    .w37_name = "IvAccordion",

    .w38_code = ALIGNED_STRING(""),

    .w38_name = ALIGNED_STRING("IvMesage"),

    .w39_code = "jjn",

    .w39_name = ALIGNED_STRING("AcVolPartEditBox"),

    .w40_code = ALIGNED_STRING("jn"),

    .w40_name = ALIGNED_STRING("AcLswPartEditBox"),

    .w41_code = ALIGNED_STRING(""),

    .w41_name = ALIGNED_STRING("IvSdpart"),

    .str_1 = "%",

    .ptrs_0 = {
        SELF(str_11),
        SELF(str_10),
        SELF(str_9),
        SELF(str_8),
        SELF(str_7),
        SELF(str_6),
        SELF(str_5),
        SELF(str_4),
        SELF(str_3),
        SELF(str_2),
        0x00000000,
    },

    .str_2 = ALIGNED_STRING("EV_MPVERSION"),

    .str_3 = "EV_TONEMODE",

    .str_4 = "EV_EXECPRESENTATION",

    .str_5 = ALIGNED_STRING("EV_ENDSONG"),

    .str_6 = ALIGNED_STRING("EV_STARTSONG"),

    .str_7 = "EV_ALLINITIAL",

    .str_8 = "EV_READSONG",

    .str_9 = "EV_READACTION",

    .str_10 = "EV_READPRESENTATION",

    .str_11 = "EV_ACCORDIONTAB",

    .field_03c2 = 0x000A,

    .ptrs_1 = {
        SELF(str_26),
        SELF(str_25),
        SELF(str_24),
        SELF(str_23),
        SELF(str_22),
        SELF(str_21),
        SELF(str_20),
        SELF(str_19),
        SELF(str_18),
        SELF(str_17),
        SELF(str_16),
        SELF(str_15),
        SELF(str_14),
        SELF(str_13),
        SELF(str_12),
        0x00000000,
    },

    .str_12 = ALIGNED_STRING("MT_GetToneMode"),

    .str_13 = "MT_ExitPresentation",

    .str_14 = "MT_InitPresentation",

    .str_15 = ALIGNED_STRING("MT_ExistPresentation"),

    .str_16 = "MT_SetMemoryDrawbar",

    .str_17 = "MT_RequestMemoryDrawbar",

    .str_18 = "MT_RefreshParam",

    .str_19 = "MT_ExecPresentation",

    .str_20 = ALIGNED_STRING("MT_StartPresentation"),

    .str_21 = "MT_ReadSong",

    .str_22 = "MT_ReadAction",

    .str_23 = "MT_ReadPresentation",

    .str_24 = ALIGNED_STRING("MT_CheckPart"),

    .str_25 = "MT_GetLswDataNo",

    .str_26 = ALIGNED_STRING("MT_GetPart"),

    .field_0510 = 0x000F,

    .ptrs_2 = {
        NAKA_ADDR(IvSdpartProc),
        NAKA_ADDR(AcLswPartEditBoxProc),
        NAKA_ADDR(AcVolPartEditBoxProc),
        NAKA_ADDR(IvMesageProc),
        NAKA_ADDR(IvAccordionProc),
        NAKA_ADDR(IvAccordionXProc),
        NAKA_ADDR(AcAccordionTabProc),
        NAKA_ADDR(PsLabelBoxProc),
        NAKA_ADDR(IvSdtecdProc),
        NAKA_ADDR(IvSdtecd1Proc),
        NAKA_ADDR(IvSdscltyp2Proc),
        NAKA_ADDR(AcWelcomScreenProc),
        NAKA_ADDR(PsMixerControlProc),
        NAKA_ADDR(AcPartMixerProc),
        NAKA_ADDR(AcTrackMixerProc),
        NAKA_ADDR(IvSoftverProc),
        NAKA_ADDR(IvPageOverWriteProc),
        NAKA_ADDR(IvDrawbarProc),
        NAKA_ADDR(IvDrawbar1Proc),
        NAKA_ADDR(IvDrawbar2Proc),
        NAKA_ADDR(IvDrawbarNormProc),
        NAKA_ADDR(IvDrawbarSndEProc),
        NAKA_ADDR(AcResetPageProc),
        NAKA_ADDR(PsVariBoxProc),
        NAKA_ADDR(AcPresentationControlProc),
        NAKA_ADDR(IvDemofeature1Proc),
        NAKA_ADDR(IvDemofeature2Proc),
        NAKA_ADDR(AcDrawEditBoxProc),
        NAKA_ADDR(AcLswPartPanProc),
        NAKA_ADDR(AcPresentationBoxProc),
        NAKA_ADDR(VwUserBitmapSpProc),
        NAKA_ADDR(AcFdemoScreenProc),
        NAKA_ADDR(AcSndEMenuProc),
        NAKA_ADDR(AcPleaseWaitProc),
        NAKA_ADDR(AcDrawSettingProc),
        NAKA_ADDR(AcDrawbarNameProc),
        NAKA_ADDR(IvMPverProc),
        0x00000000,
        SELF(str_62),
        SELF(str_61),
        SELF(str_60),
        SELF(str_59),
        SELF(str_58),
        SELF(str_57),
        SELF(str_56),
        SELF(str_55),
        SELF(str_54),
        SELF(str_53),
        SELF(str_52),
        SELF(str_51),
        SELF(str_50),
        SELF(str_49),
        SELF(str_48),
        SELF(str_47),
        SELF(str_46),
        SELF(str_45),
        SELF(str_44),
        SELF(str_43),
        SELF(str_42),
        SELF(str_41),
        SELF(str_40),
        SELF(str_39),
        SELF(str_38),
        SELF(str_37),
        SELF(str_36),
        SELF(str_35),
        SELF(str_34),
        SELF(str_33),
        SELF(str_32),
        SELF(str_31),
        SELF(str_30),
        SELF(str_29),
        SELF(str_28),
        SELF(str_27),
        SELF(w42_name),
        SELF(w42_code),
    },

    .w42_code = ALIGNED_STRING(""),

    .w42_name = "IvMPverProc",

    .str_27 = "AcDrawbarNameProc",

    .str_28 = "AcDrawSettingProc",

    .str_29 = ALIGNED_STRING("AcPleaseWaitProc"),

    .str_30 = ALIGNED_STRING("AcSndEMenuProc"),

    .str_31 = "AcFdemoScreenProc",

    .str_32 = ALIGNED_STRING("VwUserBitmapSpProc"),

    .str_33 = "AcPresentationBoxProc",

    .str_34 = ALIGNED_STRING("AcLswPartPanProc"),

    .str_35 = "AcDrawEditBoxProc",

    .str_36 = ALIGNED_STRING("IvDemofeature2Proc"),

    .str_37 = ALIGNED_STRING("IvDemofeature1Proc"),

    .str_38 = "AcPresentationControlProc",

    .str_39 = "PsVariBoxProc",

    .str_40 = "AcResetPageProc",

    .str_41 = "IvDrawbarSndEProc",

    .str_42 = "IvDrawbarNormProc",

    .str_43 = ALIGNED_STRING("IvDrawbar2Proc"),

    .str_44 = ALIGNED_STRING("IvDrawbar1Proc"),

    .str_45 = "IvDrawbarProc",

    .str_46 = "IvPageOverWriteProc",

    .str_47 = "IvSoftverProc",

    .str_48 = ALIGNED_STRING("AcTrackMixerProc"),

    .str_49 = "AcPartMixerProc",

    .str_50 = ALIGNED_STRING("PsMixerControlProc"),

    .str_51 = ALIGNED_STRING("AcWelcomScreenProc"),

    .str_52 = "IvSdscltyp2Proc",

    .str_53 = "IvSdtecd1Proc",

    .str_54 = ALIGNED_STRING("IvSdtecdProc"),

    .str_55 = ALIGNED_STRING("PsLabelBoxProc"),

    .str_56 = ALIGNED_STRING("AcAccordionTabProc"),

    .str_57 = ALIGNED_STRING("IvAccordionXProc"),

    .str_58 = "IvAccordionProc",

    .str_59 = ALIGNED_STRING("IvMesageProc"),

    .str_60 = ALIGNED_STRING("AcVolPartEditBoxProc"),

    .str_61 = ALIGNED_STRING("AcLswPartEditBoxProc"),

    .str_62 = ALIGNED_STRING("IvSdpartProc"),

    .w43 = {
        .header       = NAKA_HDR(NAKA_TYPE_CONTAINER),
        .parent_idx     = NAKA_NONE,
        .self_idx       = 0x0001,
        .next_sibling   = NAKA_NONE,
        .prev_sibling   = NAKA_NONE,
        .child_count    = 0x000A,
        .field_0e       = 0x0000,
        .field_10       = 0x0000,
        .handler        = NAKA_ADDR(Naka_PresentationRootState),
        .style          = 0x00F8,
        .field_18       = 0x0002,
        .field_1a       = 0x0000,
        .screen_id      = 0x01A0,
        .proc_addr      = 0x0003E660,
        .string_ptr     = SELF(w43_text),
        .string_id      = 0x0015,
        .reserved       = 0x0000,
    },

    .w43_text = ALIGNED_STRING("SOUND MENU"),

    .str_63 = "%",

    .field_0906 = 0x0160,

    .pad_1 = { 0 },

};

#undef SELF
#undef BASE
