#!/usr/bin/env python3
"""Generate improved naka_sequencer_exit.c from ROM data."""

import struct

ROM_PATH = "/mnt/shared/kn5000_original_roms/kn5000/kn5000_v10_program.rom"
BASE = 0xE272A4
ROM_BASE = 0xE00000
BLOB_SIZE = 692

with open(ROM_PATH, 'rb') as f:
    rom = f.read()
data = rom[BASE - ROM_BASE : BASE - ROM_BASE + BLOB_SIZE]

# Widget-to-NakaInst mapping (widget index → NakaInst name)
# Derived from ptr_0C values matching NakaInst_ label offsets
widget_inst = {
    0:  'NoteEditBox',
    1:  'EqOnOffFuncToggle',
    2:  'MsgToTtl',
    3:  'AcIndexWideToggle',
    4:  'IvPlayExit',
    5:  'HelpTtl',
    6:  'IvPnlWrExit',
    7:  'IvSdrev',
    8:  'IvSddsp',
    9:  'IvSdacc',
    10: 'IvPunchExit',
    11: 'IvAutoPunchExit',
    12: 'AcPanicEditSw',
    13: 'IvRealRecExit',
}

# NakaInst_ blocks in blob order
naka_inst_offsets = [
    0x0164, 0x0174, 0x0186, 0x0198, 0x01A6, 0x01B0, 0x01BA, 0x01C4,
    0x01D2, 0x01E0, 0x01EE, 0x0204, 0x0210, 0x0224, 0x0234, 0x023E,
    0x024C, 0x0266, 0x0274, 0x0282, 0x0292, 0x02A4, 0x02B2
]
naka_inst_names = [
    'IvRealRecExit', 'AcPanicEditSw', 'IvAutoPunchExit', 'IvPunchExit',
    'IvSdacc', 'IvSddsp', 'IvSdrev', 'IvPnlWrExit',
    'HelpTtl', 'IvPlayExit', 'AcIndexWideToggle', 'MsgToTtl',
    'EqOnOffFuncToggle', 'NoteEditBox', 'SngSel2', 'SngSel',
    'AcEntertainerGridBox', 'AccIll', 'SqedtVal3', 'SqplyVal',
    'IvSongCopyExit', 'SqedtFix', 'SqedtVal2_End'
]

# Parse each NakaInst_ block into (code_bytes, name_bytes)
inst_blocks = []
for i, (off, name) in enumerate(zip(naka_inst_offsets, naka_inst_names)):
    if i + 1 < len(naka_inst_offsets):
        size = naka_inst_offsets[i + 1] - off
    else:
        size = BLOB_SIZE - off
    block = data[off:off + size]

    # Find code string (first aligned_string)
    nul1 = block.find(0)
    if nul1 < 0:
        # No NUL (last partial block)
        inst_blocks.append((name, block, b''))
        continue
    pad1 = 1 if nul1 + 1 < len(block) and block[nul1 + 1] == 0xFF else 0
    code_size = nul1 + 1 + pad1
    code_bytes = block[:code_size]
    name_bytes = block[code_size:]
    inst_blocks.append((name, code_bytes, name_bytes))

# Widget type names
TYPE_NAMES = {
    0x10: '0x10', 0x21: '0x21', 0x27: '0x27',
    0x31: 'GROUP', 0x44: '0x44', 0x45: '0x45', 0x47: '0x47',
}


def format_string_field(raw_bytes):
    """Convert raw bytes to a C initializer using ALIGNED_STRING or bare string."""
    if not raw_bytes:
        return None

    nul = raw_bytes.find(0)
    if nul < 0:
        # No NUL — raw bytes (partial block at end)
        return '{ ' + ', '.join(f"0x{b:02X}" for b in raw_bytes) + ' }'

    text_part = raw_bytes[:nul]
    has_pad = nul + 1 < len(raw_bytes) and raw_bytes[nul + 1] == 0xFF

    if all(0x20 <= b <= 0x7E for b in text_part):
        text = text_part.decode('ascii')
        escaped = text.replace('\\', '\\\\').replace('"', '\\"')
        if has_pad:
            return f'ALIGNED_STRING("{escaped}")'
        else:
            return f'"{escaped}"'
    elif len(text_part) == 0:
        if has_pad:
            return '{ 0, 0xFF }'
        else:
            return '""'
    else:
        return '{ ' + ', '.join(f"0x{b:02X}" for b in raw_bytes) + ' }'


# ── Generate C file ──

lines = []
lines.append('/**')
lines.append(' * naka_sequencer_exit.c — Sequencer exit/mode widget descriptors')
lines.append(' *')
lines.append(' * 14 compact dispatch widgets for sequencer exit controls:')
lines.append(' * real-time recording exit, auto-punch, EQ on/off, DSP/reverb modes,')
lines.append(' * panel write, help, play exit, song copy, and more.')
lines.append(' *')
lines.append(f' * Base ROM address: 0x{BASE:06X}')
lines.append(f' * Total size: {BLOB_SIZE} bytes')
lines.append(' * Auto-generated by scripts/gen_sequencer_exit.py')
lines.append(' */')
lines.append('')
lines.append('#include "naka_types.h"')
lines.append('')

# Define the compact dispatch widget type
lines.append('/* ── Compact dispatch widget (24 bytes) ─────────────────────── */')
lines.append('')
lines.append('typedef struct __attribute__((packed)) {')
lines.append('    naka_header_t header;      /*  +0: widget type + marker */')
lines.append('    uint16_t field_04;         /*  +4: screen/widget index */')
lines.append('    uint16_t field_06;         /*  +6: child count or flags */')
lines.append('    uint32_t name_ptr;         /*  +8: → instance name string */')
lines.append('    uint32_t inst_ptr;         /* +12: → instance block (code string) */')
lines.append('    uint32_t link_ptr;         /* +16: → linked widget (external) */')
lines.append('    uint32_t proc_addr;        /* +20: → Proc handler function */')
lines.append('} naka_dispatch_t;             /* 24 bytes */')
lines.append('')

# Build struct typedef
lines.append('/* ── Struct layout ──────────────────────────────────────────── */')
lines.append('')
lines.append('typedef struct __attribute__((packed)) {')
lines.append('    /* 14 dispatch widgets (14 × 24 = 336 bytes) */')
for i in range(14):
    name = widget_inst[i]
    off_w = i * 24
    t = data[off_w]
    tname = TYPE_NAMES.get(t, f'0x{t:02X}')
    lines.append(f'    naka_dispatch_t w{i};{" " * (8 - len(str(i)))}/* {tname}: {name} */')

lines.append('')
lines.append('    /* Zero padding (20 bytes) */')
lines.append('    uint8_t padding[20];')
lines.append('')

lines.append('    /* NakaInst_ string blocks: code + name per instance */')
for iname, code_b, name_b in inst_blocks:
    code_size = len(code_b)
    name_size = len(name_b)
    total = code_size + name_size
    if code_size > 0:
        lines.append(f'    char {iname}_code[{code_size}];')
    if name_size > 0:
        lines.append(f'    char {iname}_name[{name_size}];')

lines.append('} naka_sequencer_exit_t;')
lines.append('')
lines.append(f'#define BASE  0x{BASE:08X}u')
lines.append('#define SELF(field) \\')
lines.append('    ((uint32_t)(BASE + __builtin_offsetof(naka_sequencer_exit_t, field)))')
lines.append('')
lines.append(f'_Static_assert(sizeof(naka_sequencer_exit_t) == {BLOB_SIZE},')
lines.append(f'    "naka_sequencer_exit must be exactly {BLOB_SIZE} bytes");')
lines.append('')

# Data initializer
lines.append('const naka_sequencer_exit_t naka_sequencer_exit_data')
lines.append('    __attribute__((section(".text"), used)) = {')
lines.append('')

# Widget initializers
for i in range(14):
    off_w = i * 24
    t = data[off_w]
    tname = TYPE_NAMES.get(t, f'0x{t:02X}')
    f04 = struct.unpack_from('<H', data, off_w + 4)[0]
    f06 = struct.unpack_from('<H', data, off_w + 6)[0]
    p08 = struct.unpack_from('<I', data, off_w + 8)[0]
    p0c = struct.unpack_from('<I', data, off_w + 12)[0]
    p10 = struct.unpack_from('<I', data, off_w + 16)[0]
    p14 = struct.unpack_from('<I', data, off_w + 20)[0]

    inst_name = widget_inst[i]

    # Format type code
    if t == 0x31:
        hdr = 'NAKA_TYPE_GROUP'
    else:
        hdr = f'0x{t:02X}'

    lines.append(f'    /* w{i}: TYPE_{tname} — {inst_name} */')
    lines.append(f'    .w{i} = {{')
    lines.append(f'        .header    = NAKA_HDR({hdr}),')
    lines.append(f'        .field_04  = 0x{f04:04X},')
    lines.append(f'        .field_06  = 0x{f06:04X},')
    lines.append(f'        .name_ptr  = SELF({inst_name}_name),')
    lines.append(f'        .inst_ptr  = SELF({inst_name}_code),')
    lines.append(f'        .link_ptr  = 0x{p10:08X},')
    if p14 == 0:
        lines.append(f'        .proc_addr = 0x00000000,')
    else:
        lines.append(f'        .proc_addr = 0x{p14:08X},')
    lines.append(f'    }},')
    lines.append('')

# Padding
lines.append('    /* Zero padding */')
lines.append('    .padding = { 0 },')
lines.append('')

# String blocks
lines.append('    /* ── NakaInst_ string data ────────────────────────────── */')
lines.append('')
for iname, code_b, name_b in inst_blocks:
    code_init = format_string_field(code_b)
    name_init = format_string_field(name_b)

    if code_init and name_init:
        lines.append(f'    /* NakaInst_{iname} */')
        lines.append(f'    .{iname}_code = {code_init},')
        lines.append(f'    .{iname}_name = {name_init},')
    elif code_init:
        lines.append(f'    .{iname}_code = {code_init},')
    elif name_init:
        lines.append(f'    /* NakaInst_{iname} */')
        lines.append(f'    .{iname}_name = {name_init},')
    lines.append('')

lines.append('};')
lines.append('')
lines.append('#undef SELF')
lines.append('#undef BASE')
lines.append('')

output = '\n'.join(lines)
with open('maincpu/ui_widgets/naka_sequencer_exit.c', 'w') as f:
    f.write(output)

print(f'Generated {len(lines)} lines')

# Verify total size
total = 14 * 24 + 20  # widgets + padding
for iname, code_b, name_b in inst_blocks:
    total += len(code_b) + len(name_b)
print(f'Computed size: {total} (expected {BLOB_SIZE})')
