#!/usr/bin/env python3
"""Generate maincpu/ssf_gate_states.s from the original ROM binary.

Reads SSF_PresentationGateTable (256 x 4-byte LE pointers at 0xE01F80) and
all referenced gate-state arrays (16-bit LE values terminated by 0xFFFF) from
the original maincpu ROM. Produces a structured assembly source file with:
  - All unique arrays as SSF_GateStates_ModeXX labels with .short directives
  - The 256-entry SSF_PresentationGateTable with .long references
"""

import struct
import sys
from pathlib import Path
from collections import OrderedDict

ROM_PATH = Path(__file__).resolve().parent.parent / "original_ROMs" / "kn5000_v10_program.rom"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "maincpu" / "ssf_gate_states.s"

ROM_BASE = 0xE00000
TABLE_ADDR = 0xE01F80
TABLE_ENTRIES = 256


def rom_offset(addr: int) -> int:
    """Convert a ROM address to file offset."""
    return addr - ROM_BASE


def read_gate_array(rom: bytes, addr: int) -> list[int]:
    """Read a 16-bit LE array from ROM, returning values including the 0xFFFF terminator."""
    values = []
    off = rom_offset(addr)
    while True:
        val = struct.unpack_from("<H", rom, off)[0]
        values.append(val)
        off += 2
        if val == 0xFFFF:
            break
    return values


def describe_array(values: list[int]) -> str:
    """Generate a comment describing the array content."""
    # Remove terminator for analysis
    data = [v for v in values if v != 0xFFFF]

    if not data:
        return "disabled"

    if len(data) == 1 and data[0] == 0xFFFE:
        return "unconditional"

    # Analyze chains (high byte) and params (low byte)
    chains = {}
    for v in data:
        chain = (v >> 8) & 0xFF
        param = v & 0xFF
        chains.setdefault(chain, []).append(param)

    parts = []
    for chain in sorted(chains.keys()):
        params = sorted(chains[chain])
        if len(params) == 1:
            parts.append(f"0x{chain:02X}:{len(params)}")
        else:
            parts.append(f"0x{chain:02X}:{len(params)}")

    chain_str = ", ".join(f"chain {p}" for p in parts)
    return f"{len(data)} entries, {chain_str}"


def format_short_line(values: list[int], max_per_line: int = 8) -> list[str]:
    """Format a list of 16-bit values as .short lines, up to max_per_line per line."""
    lines = []
    for i in range(0, len(values), max_per_line):
        chunk = values[i:i + max_per_line]
        vals_str = ", ".join(f"0x{v:04X}" for v in chunk)
        lines.append(f"\t.short {vals_str}")
    return lines


def main():
    if not ROM_PATH.exists():
        print(f"Error: ROM not found at {ROM_PATH}", file=sys.stderr)
        sys.exit(1)

    rom = ROM_PATH.read_bytes()
    print(f"ROM size: {len(rom)} bytes")

    # Read the 256-entry pointer table
    table_off = rom_offset(TABLE_ADDR)
    table_ptrs = []
    for i in range(TABLE_ENTRIES):
        ptr = struct.unpack_from("<I", rom, table_off + i * 4)[0]
        table_ptrs.append(ptr)

    # Build mapping: address -> (first table index, array data)
    # Track all unique addresses in ROM order
    addr_to_first_idx = {}  # addr -> lowest table index
    for idx, ptr in enumerate(table_ptrs):
        if ptr not in addr_to_first_idx:
            addr_to_first_idx[ptr] = idx

    # Sort unique addresses by ROM position (ascending)
    unique_addrs = sorted(addr_to_first_idx.keys())

    # Read all arrays
    addr_to_data = {}
    for addr in unique_addrs:
        addr_to_data[addr] = read_gate_array(rom, addr)

    # Build addr -> label name mapping
    addr_to_label = {}
    for addr in unique_addrs:
        first_idx = addr_to_first_idx[addr]
        addr_to_label[addr] = f"SSF_GateStates_Mode{first_idx:02X}"

    # Also build table index -> label name for the .long table
    idx_to_label = {}
    for idx, ptr in enumerate(table_ptrs):
        idx_to_label[idx] = addr_to_label[ptr]

    # Generate output
    lines = []

    # File header
    lines.append("; =============================================================================")
    lines.append("; SSF Gate State Arrays and Presentation Gate Table")
    lines.append("; =============================================================================")
    lines.append("; Auto-generated by scripts/generate_ssf_gate_states.py from original ROM.")
    lines.append(";")
    lines.append("; Contains 256 gate-state arrays (16-bit LE value lists terminated by 0xFFFF)")
    lines.append("; and the SSF_PresentationGateTable (256 x .long pointers).")
    lines.append(";")
    lines.append("; Each array lists the (chain_index << 8 | param) panel-selection states")
    lines.append("; that permit the Feature Demo button to fire event 0x1C00038.")
    lines.append("; Special values: 0xFFFE = unconditional, 0xFFFF = terminator/disabled.")
    lines.append("; =============================================================================")
    lines.append("")

    # Emit all arrays in ROM address order
    for addr in unique_addrs:
        data = addr_to_data[addr]
        label = addr_to_label[addr]
        desc = describe_array(data)

        lines.append(f"; {label} (0x{addr:06X}) -- {desc}")
        lines.append(f"{label}:")

        # Split: data values on .short lines (up to 8 per line), terminator on its own line
        data_vals = [v for v in data if v != 0xFFFF]
        if data_vals:
            for line in format_short_line(data_vals):
                lines.append(line)
        lines.append("\t.short 0xFFFF\t; terminator")
        lines.append("")

    # Pad to table address if needed
    lines.append("")

    # SSF_PresentationGateTable comment block
    lines.append("; =============================================================================")
    lines.append("; SSF_PresentationGateTable (0xE01F80) -- 256-entry pointer lookup table")
    lines.append("; =============================================================================")
    lines.append("; Gates the SSF (Feature Demo) presentation system. Each entry is a .long")
    lines.append("; pointer to a 16-bit value array (terminated by 0xFFFF) that lists the panel")
    lines.append("; states in which the Feature Demo button should trigger event 0x1C00038.")
    lines.append(";")
    lines.append("; Index: DRAM byte at 0x8D38, loaded by LABEL_F0618F. Represents the current")
    lines.append("; UI mode (e.g., 0x00 = boot/init, 0x01 = normal operation, 0xE0 = demo menu,")
    lines.append("; 0xE4 = Feature Presentation sub-menu).")
    lines.append(";")
    lines.append("; Lookup: GroupBoxNotify_SendSSFEvent (0xF98697) reads table[index] to get a")
    lines.append("; pointer P. If P points to {0xFFFE}, the event fires unconditionally. If P")
    lines.append("; points to {0xFFFF}, the entry is disabled (no event). Otherwise, the array")
    lines.append("; at P is scanned for a match against the current panel selection state")
    lines.append("; (packed from DRAM bytes 0xC07D and 0xC080).")
    lines.append(";")
    lines.append("; Structure: 256 x .long entries (1024 bytes), addresses 0xE01F80-0xE02380.")
    lines.append("; Targets: arrays of 16-bit values in ROM range 0xE014CE-0xE01F7E.")
    lines.append("; =============================================================================")
    lines.append("SSF_PresentationGateTable:")

    for idx in range(TABLE_ENTRIES):
        label = idx_to_label[idx]
        lines.append(f"\t.long {label}")

    # Write output
    output = "\n".join(lines) + "\n"
    OUTPUT_PATH.write_text(output)

    # Stats
    num_unique = len(unique_addrs)
    total_entries = sum(len(addr_to_data[a]) for a in unique_addrs)
    print(f"Generated {OUTPUT_PATH}")
    print(f"  {num_unique} unique arrays ({TABLE_ENTRIES} table entries)")
    print(f"  {total_entries} total .short values (including terminators)")
    print(f"  ROM range: 0x{min(unique_addrs):06X}-0x{max(unique_addrs):06X}")


if __name__ == "__main__":
    main()
