#!/usr/bin/env python3
"""
generate_naka_linker_scripts.py — Auto-generate NAKA widget linker scripts

Reads extern symbol declarations from each NAKA .c file, looks up their
addresses in the main ELF symbol table, and generates the corresponding
*_link.ld linker script.

Usage:
    python scripts/generate_naka_linker_scripts.py [--check] [--apply]

    --check: Compare generated scripts with existing ones (report differences)
    --apply: Overwrite existing linker scripts with generated versions

Without flags: dry-run mode (print what would be generated)
"""

import sys
import os
import re
import subprocess
from pathlib import Path

ROMS_DIR = Path(__file__).parent.parent
ELF_PATH = ROMS_DIR / "rebuilt_ROMs" / "kn5000_v10_program.llvm.elf"
LLVM_NM = Path("/mnt/shared/llvm-project/build/bin/llvm-nm")
WIDGETS_DIR = ROMS_DIR / "maincpu" / "ui_widgets"


def load_elf_symbols():
    """Load all symbols from the main ELF."""
    result = subprocess.run(
        [str(LLVM_NM), "--no-sort", str(ELF_PATH)],
        capture_output=True, text=True
    )
    symbols = {}
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3:
            symbols[parts[2]] = int(parts[0], 16)
    return symbols


def extract_externs(c_path):
    """Extract extern symbol names from a .c file."""
    with open(c_path, 'rb') as f:
        content = f.read().decode('latin-1')

    externs = []
    for m in re.finditer(r'extern\s+const\s+char\s+(\w+)\s*;', content):
        externs.append(m.group(1))
    return sorted(set(externs))


def generate_linker_script(c_stem, externs, symbols):
    """Generate a linker script for the given extern symbols."""
    lines = []
    lines.append(f'/* {c_stem}_link.ld — Linker script for {c_stem}.c')
    lines.append(f' * Auto-generated by scripts/generate_naka_linker_scripts.py')
    lines.append(f' */')
    lines.append(f'')
    lines.append(f'ENTRY(0)')
    lines.append(f'')
    lines.append(f'SECTIONS {{')
    lines.append(f'    .text : {{ *(.text*) *(.rodata*) }}')
    lines.append(f'    /DISCARD/ : {{ *(.comment) *(.note*) *(.eh_frame*) }}')
    lines.append(f'}}')
    lines.append(f'')

    missing = []
    for sym in externs:
        if sym in symbols:
            lines.append(f'{sym} = 0x{symbols[sym]:08X};')
        else:
            missing.append(sym)
            lines.append(f'/* WARNING: {sym} not found in ELF */')

    lines.append(f'')
    return '\n'.join(lines), missing


def main():
    import argparse
    parser = argparse.ArgumentParser(description='Auto-generate NAKA linker scripts')
    parser.add_argument('--check', action='store_true', help='Compare with existing')
    parser.add_argument('--apply', action='store_true', help='Overwrite existing')
    args = parser.parse_args()

    print("Loading ELF symbols...")
    symbols = load_elf_symbols()
    print(f"  {len(symbols)} symbols loaded")

    # Find all NAKA .c files that have corresponding _link.ld files
    c_files = sorted(WIDGETS_DIR.glob("naka_*.c"))
    # Also control_menu_header.c (uses shared naka_ctrl_menu_link.ld)

    total_updated = 0
    total_missing = 0

    for c_path in c_files:
        c_stem = c_path.stem
        ld_name = f"{c_stem}_link.ld"
        ld_path = WIDGETS_DIR / ld_name

        externs = extract_externs(str(c_path))
        if not externs:
            continue

        content, missing = generate_linker_script(c_stem, externs, symbols)

        if missing:
            total_missing += len(missing)
            print(f"  {c_stem}: {len(externs)} externs, {len(missing)} MISSING: {', '.join(missing[:3])}")

        if args.check and ld_path.exists():
            with open(ld_path, 'r') as f:
                existing = f.read()
            if existing.strip() != content.strip():
                print(f"  DIFFERS: {ld_name}")
                total_updated += 1
            # else: matches
        elif args.apply:
            with open(ld_path, 'w') as f:
                f.write(content)
            total_updated += 1
        else:
            if not ld_path.exists():
                print(f"  NEW: {ld_name} ({len(externs)} symbols)")

    if args.check:
        print(f"\n{total_updated} linker scripts differ from generated version")
    elif args.apply:
        print(f"\n{total_updated} linker scripts written")

    if total_missing:
        print(f"WARNING: {total_missing} symbols not found in ELF")


if __name__ == '__main__':
    main()
