#!/usr/bin/env python3
"""Rename LABEL_* to semantic names for DSP subsystem routines in subcpu (032-037 range).

Based on analysis of the 0x032000-0x037FFF address range in the SubCPU
audio DSP subsystem. Each rename was verified by analyzing the routine's
code, register usage, called functions, and callers.

Uses binary I/O to handle encoding safely.
"""

import os
import re

# Renames: (old_label, new_label, brief_comment)
RENAMES = [

    # -------------------------------------------------------------------------
    # 035xxx - CmdHandler_2D / CmdHandler_2C continuation branches
    # -------------------------------------------------------------------------
    ('LABEL_036001', 'CmdHandler2D_MsgSizeMatch',
     'CmdHandler_2D: body after ring-buf size match (3rd case)'),
    ('LABEL_036009', 'CmdHandler2D_EnqueueOrReturn',
     'CmdHandler_2D: enqueue cmd to ring buffer or early return'),
    ('LABEL_036025', 'CmdHandler2D_QueuedPath',
     'CmdHandler_2D: queued-command path, advance read ptr'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP algo preset / slot-state / EFF slot buffer helpers
    # -------------------------------------------------------------------------
    ('LABEL_036064', 'DSP_WriteAlgoInitPreset_PresetPath',
     'DSP_WriteAlgoInitPreset: preset present, write init data'),
    ('LABEL_036079', 'DSP_WriteAlgoInitPreset_DefaultPath',
     'DSP_WriteAlgoInitPreset: no preset, use default algo init'),
    ('LABEL_036088', 'DSP_WriteAlgoInitPreset_Epilogue',
     'DSP_WriteAlgoInitPreset: common epilogue'),
    ('LABEL_036098', 'DSP_ApplyAlgoForVoiceType_TypeF',
     'DSP_ApplyAlgoForVoiceType: algo type 0xF / 0x35 path'),
    ('LABEL_03611D', 'DSP_ApplyAlgoForVoiceType_Data',
     'DSP_ApplyAlgoForVoiceType: 1-byte constant data block'),
    ('LABEL_03613B', 'DSP_SlotState_DisplayRestore_ActivePath',
     'DSP_SlotState_DisplayRestore: active slot path, copy state'),
    ('LABEL_036152', 'DSP_SlotState_DisplayRestore_Epilogue',
     'DSP_SlotState_DisplayRestore: epilogue (pop + ret)'),
    ('LABEL_036177', 'DSP_ApplyConfig_ActivePath',
     'DSP_ApplyConfig: voice active, write config params'),
    ('LABEL_03617D', 'DSP_ApplyConfig_InactivePath',
     'DSP_ApplyConfig: voice inactive, skip param write'),
    ('LABEL_0361A0', 'DSP_ApplyConfig_BufSelectA',
     'DSP_ApplyConfig: buffer-select branch A'),
    ('LABEL_0361A8', 'DSP_ApplyConfig_BufSelectB',
     'DSP_ApplyConfig: buffer-select branch B'),
    ('LABEL_0361BA', 'DSP_ApplyConfig_Epilogue',
     'DSP_ApplyConfig: epilogue (pop + ret)'),
    ('LABEL_0361EF', 'EFF_GetSlotBuffer_NoSlot',
     'EFF_GetSlotBuffer: no matching slot found, return NULL'),
    ('LABEL_0361FF', 'EFF_GetSlotBuffer_LoopBody',
     'EFF_GetSlotBuffer: inner loop body scanning EFF slots'),
    ('LABEL_036204', 'EFF_GetSlotBuffer_Epilogue',
     'EFF_GetSlotBuffer: matched slot epilogue, return pointer'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP state table constant data block
    # -------------------------------------------------------------------------
    ('LABEL_036205', 'DSP_StateTable_DefaultData',
     'Default DSP state table values (written by DMA preset load)'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP command queue / task wake helper
    # -------------------------------------------------------------------------
    ('LABEL_036319', 'DSP_WaitForTaskSlot_Loop',
     'Poll task queue until slot available (timeout via LABEL_0200C0)'),
    ('LABEL_036325', 'DSP_WaitForTaskSlot_Epilogue',
     'DSP task slot wait: success epilogue (pop iz + ret)'),
    ('LABEL_036327', 'DSP_WaitForTaskSlot_Data',
     '4-byte data block after DSP task wait routine'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP2 SPI bit-bang timing NOP chains
    # (DSP2_SPI_ClockPulseHigh body: NOP delay steps 1..36)
    # -------------------------------------------------------------------------
    ('LABEL_03640F', 'DSP2_ClkHigh_Nop01',  'SPI clock-high NOP delay step 1'),
    ('LABEL_036412', 'DSP2_ClkHigh_Nop02',  'SPI clock-high NOP delay step 2'),
    ('LABEL_036415', 'DSP2_ClkHigh_Nop03',  'SPI clock-high NOP delay step 3'),
    ('LABEL_036418', 'DSP2_ClkHigh_Nop04',  'SPI clock-high NOP delay step 4'),
    ('LABEL_03641B', 'DSP2_ClkHigh_Nop05',  'SPI clock-high NOP delay step 5'),
    ('LABEL_03641E', 'DSP2_ClkHigh_Nop06',  'SPI clock-high NOP delay step 6'),
    ('LABEL_036421', 'DSP2_ClkHigh_Nop07',  'SPI clock-high NOP delay step 7'),
    ('LABEL_036424', 'DSP2_ClkHigh_Nop08',  'SPI clock-high NOP delay step 8'),
    ('LABEL_036427', 'DSP2_ClkHigh_Nop09',  'SPI clock-high NOP delay step 9'),
    ('LABEL_03642A', 'DSP2_ClkHigh_Nop10',  'SPI clock-high NOP delay step 10'),
    ('LABEL_03642D', 'DSP2_ClkHigh_Nop11',  'SPI clock-high NOP delay step 11'),
    ('LABEL_036430', 'DSP2_ClkHigh_Nop12',  'SPI clock-high NOP delay step 12'),
    ('LABEL_036433', 'DSP2_ClkHigh_Nop13',  'SPI clock-high NOP delay step 13'),
    ('LABEL_036436', 'DSP2_ClkHigh_Nop14',  'SPI clock-high NOP delay step 14'),
    ('LABEL_036439', 'DSP2_ClkHigh_Nop15',  'SPI clock-high NOP delay step 15'),
    ('LABEL_03643C', 'DSP2_ClkHigh_Nop16',  'SPI clock-high NOP delay step 16'),
    ('LABEL_03643F', 'DSP2_ClkHigh_Nop17',  'SPI clock-high NOP delay step 17'),
    ('LABEL_036442', 'DSP2_ClkHigh_Nop18',  'SPI clock-high NOP delay step 18'),
    ('LABEL_036445', 'DSP2_ClkHigh_Nop19',  'SPI clock-high NOP delay step 19'),
    ('LABEL_03644B', 'DSP2_ClkHigh_Nop20',  'SPI clock-high NOP delay step 20'),
    ('LABEL_036451', 'DSP2_ClkHigh_Nop21',  'SPI clock-high NOP delay step 21'),
    ('LABEL_036454', 'DSP2_ClkHigh_Nop22',  'SPI clock-high NOP delay step 22'),
    ('LABEL_036457', 'DSP2_ClkHigh_Nop23',  'SPI clock-high NOP delay step 23'),
    ('LABEL_03645A', 'DSP2_ClkHigh_Nop24',  'SPI clock-high NOP delay step 24'),
    ('LABEL_03645D', 'DSP2_ClkHigh_Nop25',  'SPI clock-high NOP delay step 25'),
    ('LABEL_036460', 'DSP2_ClkHigh_Nop26',  'SPI clock-high NOP delay step 26'),
    ('LABEL_036463', 'DSP2_ClkHigh_Nop27',  'SPI clock-high NOP delay step 27'),
    ('LABEL_036466', 'DSP2_ClkHigh_Nop28',  'SPI clock-high NOP delay step 28'),
    ('LABEL_036469', 'DSP2_ClkHigh_Nop29',  'SPI clock-high NOP delay step 29'),
    ('LABEL_03646C', 'DSP2_ClkHigh_Nop30',  'SPI clock-high NOP delay step 30'),
    ('LABEL_03646F', 'DSP2_ClkHigh_Nop31',  'SPI clock-high NOP delay step 31'),
    ('LABEL_036472', 'DSP2_ClkHigh_Nop32',  'SPI clock-high NOP delay step 32'),
    ('LABEL_036475', 'DSP2_ClkHigh_Nop33',  'SPI clock-high NOP delay step 33'),
    ('LABEL_036478', 'DSP2_ClkHigh_Nop34',  'SPI clock-high NOP delay step 34'),
    ('LABEL_03647B', 'DSP2_ClkHigh_Nop35',  'SPI clock-high NOP delay step 35'),
    ('LABEL_03647E', 'DSP2_ClkHigh_Nop36',  'SPI clock-high NOP delay step 36'),
    ('LABEL_036484', 'DSP2_ClkHigh_Nop37',  'SPI clock-high NOP delay step 37'),
    ('LABEL_036487', 'DSP2_ClkHigh_Nop38',  'SPI clock-high NOP delay step 38'),
    ('LABEL_03648A', 'DSP2_ClkHigh_Nop39',  'SPI clock-high NOP delay step 39'),
    ('LABEL_03648D', 'DSP2_ClkHigh_Nop40',  'SPI clock-high NOP delay step 40'),
    ('LABEL_036490', 'DSP2_ClkHigh_Nop41',  'SPI clock-high NOP delay step 41'),
    ('LABEL_036493', 'DSP2_ClkHigh_Nop42',  'SPI clock-high NOP delay step 42'),
    ('LABEL_036496', 'DSP2_ClkHigh_Nop43',  'SPI clock-high NOP delay step 43'),
    ('LABEL_036499', 'DSP2_ClkHigh_Nop44',  'SPI clock-high NOP delay step 44'),
    ('LABEL_03649C', 'DSP2_ClkHigh_Nop45',  'SPI clock-high NOP delay step 45'),
    ('LABEL_03649F', 'DSP2_ClkHigh_Nop46',  'SPI clock-high NOP delay step 46'),
    ('LABEL_0364A2', 'DSP2_ClkHigh_Nop47',  'SPI clock-high NOP delay step 47'),
    ('LABEL_0364A5', 'DSP2_ClkHigh_Nop48',  'SPI clock-high NOP delay step 48'),
    ('LABEL_0364A8', 'DSP2_ClkHigh_Nop49',  'SPI clock-high NOP delay step 49'),
    ('LABEL_0364AB', 'DSP2_ClkHigh_Nop50',  'SPI clock-high NOP delay step 50'),
    ('LABEL_0364AE', 'DSP2_ClkHigh_Nop51',  'SPI clock-high NOP delay step 51'),
    ('LABEL_0364B1', 'DSP2_ClkHigh_Nop52',  'SPI clock-high NOP delay step 52'),
    ('LABEL_0364B4', 'DSP2_ClkHigh_Nop53',  'SPI clock-high NOP delay step 53'),
    ('LABEL_0364B7', 'DSP2_ClkHigh_Nop54',  'SPI clock-high NOP delay step 54'),
    ('LABEL_0364BA', 'DSP2_ClkHigh_Nop55',  'SPI clock-high NOP delay step 55 (last; jp to debug log)'),

    # DSP2_SPI_BusIdle body: NOP delay steps for clock-low (1..18) then clock-raise (19..36) then data-set (37..56)
    ('LABEL_0364CC', 'DSP2_BusIdle_Nop01',   'SPI bus-idle NOP delay step 1'),
    ('LABEL_0364CF', 'DSP2_BusIdle_Nop02',   'SPI bus-idle NOP delay step 2'),
    ('LABEL_0364D2', 'DSP2_BusIdle_Nop03',   'SPI bus-idle NOP delay step 3'),
    ('LABEL_0364D5', 'DSP2_BusIdle_Nop04',   'SPI bus-idle NOP delay step 4'),
    ('LABEL_0364D8', 'DSP2_BusIdle_Nop05',   'SPI bus-idle NOP delay step 5'),
    ('LABEL_0364DB', 'DSP2_BusIdle_Nop06',   'SPI bus-idle NOP delay step 6'),
    ('LABEL_0364DE', 'DSP2_BusIdle_Nop07',   'SPI bus-idle NOP delay step 7'),
    ('LABEL_0364E1', 'DSP2_BusIdle_Nop08',   'SPI bus-idle NOP delay step 8'),
    ('LABEL_0364E4', 'DSP2_BusIdle_Nop09',   'SPI bus-idle NOP delay step 9'),
    ('LABEL_0364E7', 'DSP2_BusIdle_Nop10',   'SPI bus-idle NOP delay step 10'),
    ('LABEL_0364EA', 'DSP2_BusIdle_Nop11',   'SPI bus-idle NOP delay step 11'),
    ('LABEL_0364ED', 'DSP2_BusIdle_Nop12',   'SPI bus-idle NOP delay step 12'),
    ('LABEL_0364F0', 'DSP2_BusIdle_Nop13',   'SPI bus-idle NOP delay step 13'),
    ('LABEL_0364F3', 'DSP2_BusIdle_Nop14',   'SPI bus-idle NOP delay step 14'),
    ('LABEL_0364F6', 'DSP2_BusIdle_Nop15',   'SPI bus-idle NOP delay step 15'),
    ('LABEL_0364F9', 'DSP2_BusIdle_Nop16',   'SPI bus-idle NOP delay step 16'),
    ('LABEL_0364FC', 'DSP2_BusIdle_Nop17',   'SPI bus-idle NOP delay step 17'),
    ('LABEL_0364FF', 'DSP2_BusIdle_Nop18',   'SPI bus-idle NOP delay step 18'),
    # clock raised (set_dd8 2, 0x3C) then more NOPs
    ('LABEL_036502', 'DSP2_BusIdle_Nop19',   'SPI bus-idle NOP delay step 19 (after clk raise)'),
    ('LABEL_036508', 'DSP2_BusIdle_Nop20',   'SPI bus-idle NOP delay step 20'),
    ('LABEL_03650B', 'DSP2_BusIdle_Nop21',   'SPI bus-idle NOP delay step 21'),
    ('LABEL_03650E', 'DSP2_BusIdle_Nop22',   'SPI bus-idle NOP delay step 22'),
    ('LABEL_036511', 'DSP2_BusIdle_Nop23',   'SPI bus-idle NOP delay step 23'),
    ('LABEL_036514', 'DSP2_BusIdle_Nop24',   'SPI bus-idle NOP delay step 24'),
    ('LABEL_036517', 'DSP2_BusIdle_Nop25',   'SPI bus-idle NOP delay step 25'),
    ('LABEL_03651A', 'DSP2_BusIdle_Nop26',   'SPI bus-idle NOP delay step 26'),
    ('LABEL_03651D', 'DSP2_BusIdle_Nop27',   'SPI bus-idle NOP delay step 27'),
    ('LABEL_036520', 'DSP2_BusIdle_Nop28',   'SPI bus-idle NOP delay step 28'),
    ('LABEL_036523', 'DSP2_BusIdle_Nop29',   'SPI bus-idle NOP delay step 29'),
    ('LABEL_036526', 'DSP2_BusIdle_Nop30',   'SPI bus-idle NOP delay step 30'),
    ('LABEL_036529', 'DSP2_BusIdle_Nop31',   'SPI bus-idle NOP delay step 31'),
    ('LABEL_03652C', 'DSP2_BusIdle_Nop32',   'SPI bus-idle NOP delay step 32'),
    ('LABEL_03652F', 'DSP2_BusIdle_Nop33',   'SPI bus-idle NOP delay step 33'),
    ('LABEL_036532', 'DSP2_BusIdle_Nop34',   'SPI bus-idle NOP delay step 34'),
    ('LABEL_036535', 'DSP2_BusIdle_Nop35',   'SPI bus-idle NOP delay step 35'),
    ('LABEL_036538', 'DSP2_BusIdle_Nop36',   'SPI bus-idle NOP delay step 36'),
    # data pin set (set_dd8 0, 0x3C) then more NOPs
    ('LABEL_03653B', 'DSP2_BusIdle_Nop37',   'SPI bus-idle NOP delay step 37'),
    ('LABEL_03653E', 'DSP2_BusIdle_Nop38',   'SPI bus-idle NOP delay step 38 (after data set)'),
    ('LABEL_036544', 'DSP2_BusIdle_Nop39',   'SPI bus-idle NOP delay step 39'),
    ('LABEL_036547', 'DSP2_BusIdle_Nop40',   'SPI bus-idle NOP delay step 40'),
    ('LABEL_03654A', 'DSP2_BusIdle_Nop41',   'SPI bus-idle NOP delay step 41'),
    ('LABEL_03654D', 'DSP2_BusIdle_Nop42',   'SPI bus-idle NOP delay step 42'),
    ('LABEL_036550', 'DSP2_BusIdle_Nop43',   'SPI bus-idle NOP delay step 43'),
    ('LABEL_036553', 'DSP2_BusIdle_Nop44',   'SPI bus-idle NOP delay step 44'),
    ('LABEL_036556', 'DSP2_BusIdle_Nop45',   'SPI bus-idle NOP delay step 45'),
    ('LABEL_036559', 'DSP2_BusIdle_Nop46',   'SPI bus-idle NOP delay step 46'),
    ('LABEL_03655C', 'DSP2_BusIdle_Nop47',   'SPI bus-idle NOP delay step 47'),
    ('LABEL_03655F', 'DSP2_BusIdle_Nop48',   'SPI bus-idle NOP delay step 48'),
    ('LABEL_036562', 'DSP2_BusIdle_Nop49',   'SPI bus-idle NOP delay step 49'),
    ('LABEL_036565', 'DSP2_BusIdle_Nop50',   'SPI bus-idle NOP delay step 50'),
    ('LABEL_036568', 'DSP2_BusIdle_Nop51',   'SPI bus-idle NOP delay step 51'),
    ('LABEL_03656B', 'DSP2_BusIdle_Nop52',   'SPI bus-idle NOP delay step 52'),
    ('LABEL_03656E', 'DSP2_BusIdle_Nop53',   'SPI bus-idle NOP delay step 53'),
    ('LABEL_036571', 'DSP2_BusIdle_Nop54',   'SPI bus-idle NOP delay step 54'),
    ('LABEL_036574', 'DSP2_BusIdle_Nop55',   'SPI bus-idle NOP delay step 55'),
    ('LABEL_036577', 'DSP2_BusIdle_Nop56',   'SPI bus-idle NOP delay step 56'),
    ('LABEL_03657A', 'DSP2_BusIdle_Nop57',   'SPI bus-idle NOP delay step 57'),
    ('LABEL_03657D', 'DSP2_BusIdle_Nop58',   'SPI bus-idle NOP delay step 58'),
    ('LABEL_036580', 'DSP2_BusIdle_Nop59',   'SPI bus-idle NOP delay step 59'),
    ('LABEL_036583', 'DSP2_BusIdle_Nop60',   'SPI bus-idle NOP delay step 60'),
    ('LABEL_036586', 'DSP2_BusIdle_Nop61',   'SPI bus-idle NOP delay step 61'),
    ('LABEL_036589', 'DSP2_BusIdle_Nop62',   'SPI bus-idle NOP delay step 62'),
    ('LABEL_03658C', 'DSP2_BusIdle_Nop63',   'SPI bus-idle NOP delay step 63'),
    ('LABEL_03658F', 'DSP2_BusIdle_Nop64',   'SPI bus-idle NOP delay step 64'),
    ('LABEL_036592', 'DSP2_BusIdle_Nop65',   'SPI bus-idle NOP delay step 65'),
    ('LABEL_036595', 'DSP2_BusIdle_Nop66',   'SPI bus-idle NOP delay step 66'),
    ('LABEL_036598', 'DSP2_BusIdle_Nop67',   'SPI bus-idle NOP delay step 67'),
    ('LABEL_03659B', 'DSP2_BusIdle_Nop68',   'SPI bus-idle NOP delay step 68'),
    ('LABEL_03659E', 'DSP2_BusIdle_Nop69',   'SPI bus-idle NOP delay step 69'),
    ('LABEL_0365A1', 'DSP2_BusIdle_Nop70',   'SPI bus-idle NOP delay step 70'),
    ('LABEL_0365A4', 'DSP2_BusIdle_Nop71',   'SPI bus-idle NOP delay step 71'),
    ('LABEL_0365A7', 'DSP2_BusIdle_Nop72',   'SPI bus-idle NOP delay step 72'),
    ('LABEL_0365AA', 'DSP2_BusIdle_Nop73',   'SPI bus-idle NOP delay step 73'),
    ('LABEL_0365AD', 'DSP2_BusIdle_Nop74',   'SPI bus-idle NOP delay step 74'),
    ('LABEL_0365B0', 'DSP2_BusIdle_Nop75',   'SPI bus-idle NOP delay step 75'),
    ('LABEL_0365B3', 'DSP2_BusIdle_Nop76',   'SPI bus-idle NOP delay step 76'),
    ('LABEL_0365B6', 'DSP2_BusIdle_Nop77',   'SPI bus-idle NOP delay step 77'),
    ('LABEL_0365B9', 'DSP2_BusIdle_Nop78',   'SPI bus-idle NOP delay step 78'),
    ('LABEL_0365BC', 'DSP2_BusIdle_Nop79',   'SPI bus-idle NOP delay step 79'),
    ('LABEL_0365BF', 'DSP2_BusIdle_Nop80',   'SPI bus-idle NOP delay step 80'),
    ('LABEL_0365C2', 'DSP2_BusIdle_Nop81',   'SPI bus-idle NOP delay step 81'),
    ('LABEL_0365C5', 'DSP2_BusIdle_Nop82',   'SPI bus-idle NOP delay step 82'),
    ('LABEL_0365C8', 'DSP2_BusIdle_Nop83',   'SPI bus-idle NOP delay step 83'),
    ('LABEL_0365CB', 'DSP2_BusIdle_Nop84',   'SPI bus-idle NOP delay step 84'),
    ('LABEL_0365CE', 'DSP2_BusIdle_Nop85',   'SPI bus-idle NOP delay step 85'),
    ('LABEL_0365D1', 'DSP2_BusIdle_Nop86',   'SPI bus-idle NOP delay step 86'),
    ('LABEL_0365D4', 'DSP2_BusIdle_Nop87',   'SPI bus-idle NOP delay step 87'),
    ('LABEL_0365D7', 'DSP2_BusIdle_Nop88',   'SPI bus-idle NOP delay step 88'),
    ('LABEL_0365DA', 'DSP2_BusIdle_Nop89',   'SPI bus-idle NOP delay step 89'),
    ('LABEL_0365DD', 'DSP2_BusIdle_Nop90',   'SPI bus-idle NOP delay step 90'),
    ('LABEL_0365E0', 'DSP2_BusIdle_Nop91',   'SPI bus-idle NOP delay step 91'),
    ('LABEL_0365E3', 'DSP2_BusIdle_Nop92',   'SPI bus-idle NOP delay step 92'),
    ('LABEL_0365E6', 'DSP2_BusIdle_Nop93',   'SPI bus-idle NOP delay step 93'),
    ('LABEL_0365E9', 'DSP2_BusIdle_Nop94',   'SPI bus-idle NOP delay step 94'),
    ('LABEL_0365EC', 'DSP2_BusIdle_Nop95',   'SPI bus-idle NOP delay step 95'),
    ('LABEL_0365EF', 'DSP2_BusIdle_Nop96',   'SPI bus-idle NOP delay step 96'),
    ('LABEL_0365F2', 'DSP2_BusIdle_Nop97',   'SPI bus-idle NOP delay step 97'),
    ('LABEL_0365F5', 'DSP2_BusIdle_Nop98',   'SPI bus-idle NOP delay step 98'),
    ('LABEL_0365F8', 'DSP2_BusIdle_Nop99',   'SPI bus-idle NOP delay step 99'),
    ('LABEL_0365FB', 'DSP2_BusIdle_Nop100',  'SPI bus-idle NOP delay step 100'),
    ('LABEL_0365FE', 'DSP2_BusIdle_Nop101',  'SPI bus-idle NOP delay step 101'),
    ('LABEL_036601', 'DSP2_BusIdle_Nop102',  'SPI bus-idle NOP delay step 102'),
    ('LABEL_036604', 'DSP2_BusIdle_Nop103',  'SPI bus-idle NOP delay step 103'),
    ('LABEL_036607', 'DSP2_BusIdle_Nop104',  'SPI bus-idle NOP delay step 104'),
    ('LABEL_03660A', 'DSP2_BusIdle_Nop105',  'SPI bus-idle NOP delay step 105'),
    ('LABEL_03660D', 'DSP2_BusIdle_Nop106',  'SPI bus-idle NOP delay step 106'),
    ('LABEL_036610', 'DSP2_BusIdle_Nop107',  'SPI bus-idle NOP delay step 107'),
    ('LABEL_036613', 'DSP2_BusIdle_Nop108',  'SPI bus-idle NOP delay step 108'),
    ('LABEL_036616', 'DSP2_BusIdle_Nop109',  'SPI bus-idle NOP delay step 109'),
    ('LABEL_036619', 'DSP2_BusIdle_Nop110',  'SPI bus-idle NOP delay step 110'),
    ('LABEL_03661C', 'DSP2_BusIdle_Nop111',  'SPI bus-idle NOP delay step 111'),
    ('LABEL_03661F', 'DSP2_BusIdle_Nop112',  'SPI bus-idle NOP delay step 112'),
    ('LABEL_036622', 'DSP2_BusIdle_Nop113',  'SPI bus-idle NOP delay step 113'),
    ('LABEL_036625', 'DSP2_BusIdle_Nop114',  'SPI bus-idle NOP delay step 114'),
    ('LABEL_036628', 'DSP2_BusIdle_Nop115',  'SPI bus-idle NOP delay step 115'),
    ('LABEL_03662B', 'DSP2_BusIdle_Nop116',  'SPI bus-idle NOP delay step 116'),
    ('LABEL_03662E', 'DSP2_BusIdle_Nop117',  'SPI bus-idle NOP delay step 117'),
    ('LABEL_036631', 'DSP2_BusIdle_Nop118',  'SPI bus-idle NOP delay step 118'),
    ('LABEL_036634', 'DSP2_BusIdle_Nop119',  'SPI bus-idle NOP delay step 119'),
    ('LABEL_036637', 'DSP2_BusIdle_Nop120',  'SPI bus-idle NOP delay step 120'),
    ('LABEL_03663A', 'DSP2_BusIdle_Nop121',  'SPI bus-idle NOP delay step 121'),
    ('LABEL_03663D', 'DSP2_BusIdle_Nop122',  'SPI bus-idle NOP delay step 122'),
    ('LABEL_036640', 'DSP2_BusIdle_Nop123',  'SPI bus-idle NOP delay step 123'),
    ('LABEL_036643', 'DSP2_BusIdle_Nop124',  'SPI bus-idle NOP delay step 124'),
    ('LABEL_036646', 'DSP2_BusIdle_Nop125',  'SPI bus-idle NOP delay step 125'),
    ('LABEL_036649', 'DSP2_BusIdle_Nop126',  'SPI bus-idle NOP delay step 126'),
    ('LABEL_03664C', 'DSP2_BusIdle_Nop127',  'SPI bus-idle NOP delay step 127'),
    ('LABEL_03664F', 'DSP2_BusIdle_Nop128',  'SPI bus-idle NOP delay step 128'),
    ('LABEL_036652', 'DSP2_BusIdle_Nop129',  'SPI bus-idle NOP delay step 129'),
    ('LABEL_036655', 'DSP2_BusIdle_Nop130',  'SPI bus-idle NOP delay step 130'),
    ('LABEL_036658', 'DSP2_BusIdle_Nop131',  'SPI bus-idle NOP delay step 131'),
    ('LABEL_03665B', 'DSP2_BusIdle_Nop132',  'SPI bus-idle NOP delay step 132'),
    ('LABEL_03665E', 'DSP2_BusIdle_Nop133',  'SPI bus-idle NOP delay step 133'),
    ('LABEL_036661', 'DSP2_BusIdle_Nop134',  'SPI bus-idle NOP delay step 134 (last; jp to debug log)'),

    # -------------------------------------------------------------------------
    # DSP2_Send_Command bit-bang loop control and NOP chains
    # -------------------------------------------------------------------------
    ('LABEL_036696', 'DSP2_SendCmd_BitLoop',
     'DSP2_Send_Command: bit-bang loop body, test and set/clear MOSI'),
    ('LABEL_0366A1', 'DSP2_SendCmd_BitClear',
     'DSP2_Send_Command: MOSI bit = 0 path (res data pin)'),
    ('LABEL_0366A4', 'DSP2_SendCmd_BitSet_Done',
     'DSP2_Send_Command: after MOSI write, fall into clock-high NOPs'),
    ('LABEL_0366A6', 'DSP2_SendCmd_ClkHigh_Nop01',
     'DSP2_Send_Command: clock-high NOP step 1 (after MOSI set, before shift)'),
    # Clock-high NOP delay steps 2..16 (0x0366B0 through 0x0366DD)
    ('LABEL_0366B0', 'DSP2_SendCmd_ClkHigh_Nop02',  'DSP2_Send_Command: clock-high NOP step 2'),
    ('LABEL_0366B3', 'DSP2_SendCmd_ClkHigh_Nop03',  'DSP2_Send_Command: clock-high NOP step 3'),
    ('LABEL_0366B6', 'DSP2_SendCmd_ClkHigh_Nop04',  'DSP2_Send_Command: clock-high NOP step 4'),
    ('LABEL_0366B9', 'DSP2_SendCmd_ClkHigh_Nop05',  'DSP2_Send_Command: clock-high NOP step 5'),
    ('LABEL_0366BC', 'DSP2_SendCmd_ClkHigh_Nop06',  'DSP2_Send_Command: clock-high NOP step 6'),
    ('LABEL_0366BF', 'DSP2_SendCmd_ClkHigh_Nop07',  'DSP2_Send_Command: clock-high NOP step 7'),
    ('LABEL_0366C2', 'DSP2_SendCmd_ClkHigh_Nop08',  'DSP2_Send_Command: clock-high NOP step 8'),
    ('LABEL_0366C5', 'DSP2_SendCmd_ClkHigh_Nop09',  'DSP2_Send_Command: clock-high NOP step 9'),
    ('LABEL_0366C8', 'DSP2_SendCmd_ClkHigh_Nop10',  'DSP2_Send_Command: clock-high NOP step 10'),
    ('LABEL_0366CB', 'DSP2_SendCmd_ClkHigh_Nop11',  'DSP2_Send_Command: clock-high NOP step 11'),
    ('LABEL_0366CE', 'DSP2_SendCmd_ClkHigh_Nop12',  'DSP2_Send_Command: clock-high NOP step 12'),
    ('LABEL_0366D1', 'DSP2_SendCmd_ClkHigh_Nop13',  'DSP2_Send_Command: clock-high NOP step 13'),
    ('LABEL_0366D4', 'DSP2_SendCmd_ClkHigh_Nop14',  'DSP2_Send_Command: clock-high NOP step 14'),
    ('LABEL_0366D7', 'DSP2_SendCmd_ClkHigh_Nop15',  'DSP2_Send_Command: clock-high NOP step 15'),
    ('LABEL_0366DA', 'DSP2_SendCmd_ClkHigh_Nop16',  'DSP2_Send_Command: clock-high NOP step 16'),
    # Clock goes low (res_dd8 2) then clock-low NOP delay steps
    ('LABEL_0366DD', 'DSP2_SendCmd_ClkLow_Nop01',   'DSP2_Send_Command: clock-low NOP step 1 (after clk deassert)'),
    ('LABEL_0366E3', 'DSP2_SendCmd_ClkLow_Nop02',   'DSP2_Send_Command: clock-low NOP step 2'),
    ('LABEL_0366E6', 'DSP2_SendCmd_ClkLow_Nop03',   'DSP2_Send_Command: clock-low NOP step 3'),
    ('LABEL_0366E9', 'DSP2_SendCmd_ClkLow_Nop04',   'DSP2_Send_Command: clock-low NOP step 4'),
    ('LABEL_0366EC', 'DSP2_SendCmd_ClkLow_Nop05',   'DSP2_Send_Command: clock-low NOP step 5'),
    ('LABEL_0366EF', 'DSP2_SendCmd_ClkLow_Nop06',   'DSP2_Send_Command: clock-low NOP step 6'),
    ('LABEL_0366F2', 'DSP2_SendCmd_ClkLow_Nop07',   'DSP2_Send_Command: clock-low NOP step 7'),
    ('LABEL_0366F5', 'DSP2_SendCmd_ClkLow_Nop08',   'DSP2_Send_Command: clock-low NOP step 8'),
    ('LABEL_0366F8', 'DSP2_SendCmd_ClkLow_Nop09',   'DSP2_Send_Command: clock-low NOP step 9'),
    ('LABEL_0366FB', 'DSP2_SendCmd_ClkLow_Nop10',   'DSP2_Send_Command: clock-low NOP step 10'),
    ('LABEL_0366FE', 'DSP2_SendCmd_ClkLow_Nop11',   'DSP2_Send_Command: clock-low NOP step 11'),
    ('LABEL_036701', 'DSP2_SendCmd_ClkLow_Nop12',   'DSP2_Send_Command: clock-low NOP step 12'),
    ('LABEL_036704', 'DSP2_SendCmd_ClkLow_Nop13',   'DSP2_Send_Command: clock-low NOP step 13'),
    ('LABEL_036707', 'DSP2_SendCmd_ClkLow_Nop14',   'DSP2_Send_Command: clock-low NOP step 14'),
    ('LABEL_03670A', 'DSP2_SendCmd_ClkLow_Nop15',   'DSP2_Send_Command: clock-low NOP step 15'),
    ('LABEL_03670D', 'DSP2_SendCmd_ClkLow_Nop16',   'DSP2_Send_Command: clock-low NOP step 16'),
    ('LABEL_036710', 'DSP2_SendCmd_ClkLow_Nop17',   'DSP2_Send_Command: clock-low NOP step 17'),
    ('LABEL_036713', 'DSP2_SendCmd_ClkLow_Nop18',   'DSP2_Send_Command: clock-low NOP step 18'),
    ('LABEL_036716', 'DSP2_SendCmd_ClkLow_Nop19',   'DSP2_Send_Command: clock-low NOP step 19'),
    ('LABEL_036719', 'DSP2_SendCmd_ClkLow_Nop20',   'DSP2_Send_Command: clock-low NOP step 20 (loop branch)'),
    # Post-bit-loop: final clock-high pulse and epilogue NOPs
    ('LABEL_036721', 'DSP2_SendCmd_PostLoop_Entry',
     'DSP2_Send_Command: post-bit-loop entry (all 8 bits sent)'),
    ('LABEL_036723', 'DSP2_SendCmd_PostLoop_Nop01',
     'DSP2_Send_Command: post-loop NOP step 1 (after final clk-high)'),
    ('LABEL_036729', 'DSP2_SendCmd_PostLoop_Nop02',  'DSP2_Send_Command: post-loop NOP step 2'),
    ('LABEL_03672C', 'DSP2_SendCmd_PostLoop_Nop03',  'DSP2_Send_Command: post-loop NOP step 3'),
    ('LABEL_03672F', 'DSP2_SendCmd_PostLoop_Nop04',  'DSP2_Send_Command: post-loop NOP step 4'),
    ('LABEL_036732', 'DSP2_SendCmd_PostLoop_Nop05',  'DSP2_Send_Command: post-loop NOP step 5'),
    ('LABEL_036735', 'DSP2_SendCmd_PostLoop_Nop06',  'DSP2_Send_Command: post-loop NOP step 6'),
    ('LABEL_036738', 'DSP2_SendCmd_PostLoop_Nop07',  'DSP2_Send_Command: post-loop NOP step 7'),
    ('LABEL_03673B', 'DSP2_SendCmd_PostLoop_Nop08',  'DSP2_Send_Command: post-loop NOP step 8'),
    ('LABEL_03673E', 'DSP2_SendCmd_PostLoop_Nop09',  'DSP2_Send_Command: post-loop NOP step 9'),
    ('LABEL_036741', 'DSP2_SendCmd_PostLoop_Nop10',  'DSP2_Send_Command: post-loop NOP step 10'),
    ('LABEL_036744', 'DSP2_SendCmd_PostLoop_Nop11',  'DSP2_Send_Command: post-loop NOP step 11'),
    ('LABEL_036747', 'DSP2_SendCmd_PostLoop_Nop12',  'DSP2_Send_Command: post-loop NOP step 12'),
    ('LABEL_03674A', 'DSP2_SendCmd_PostLoop_Nop13',  'DSP2_Send_Command: post-loop NOP step 13'),
    ('LABEL_03674D', 'DSP2_SendCmd_PostLoop_Nop14',  'DSP2_Send_Command: post-loop NOP step 14'),
    ('LABEL_036750', 'DSP2_SendCmd_PostLoop_Nop15',  'DSP2_Send_Command: post-loop NOP step 15'),
    ('LABEL_036753', 'DSP2_SendCmd_PostLoop_Nop16',  'DSP2_Send_Command: post-loop NOP step 16'),
    ('LABEL_036756', 'DSP2_SendCmd_PostLoop_Nop17',  'DSP2_Send_Command: post-loop NOP step 17 (before clk-low)'),
    # Clock goes low after post-loop NOPs, then more delay NOPs
    ('LABEL_03675C', 'DSP2_SendCmd_PostClkLow_Nop01', 'DSP2_Send_Command: post-clk-low NOP step 1'),
    ('LABEL_03675F', 'DSP2_SendCmd_PostClkLow_Nop02', 'DSP2_Send_Command: post-clk-low NOP step 2'),
    ('LABEL_036762', 'DSP2_SendCmd_PostClkLow_Nop03', 'DSP2_Send_Command: post-clk-low NOP step 3'),
    ('LABEL_036765', 'DSP2_SendCmd_PostClkLow_Nop04', 'DSP2_Send_Command: post-clk-low NOP step 4'),
    ('LABEL_036768', 'DSP2_SendCmd_PostClkLow_Nop05', 'DSP2_Send_Command: post-clk-low NOP step 5'),
    ('LABEL_03676B', 'DSP2_SendCmd_PostClkLow_Nop06', 'DSP2_Send_Command: post-clk-low NOP step 6'),
    ('LABEL_03676E', 'DSP2_SendCmd_PostClkLow_Nop07', 'DSP2_Send_Command: post-clk-low NOP step 7'),
    ('LABEL_036771', 'DSP2_SendCmd_PostClkLow_Nop08', 'DSP2_Send_Command: post-clk-low NOP step 8'),
    ('LABEL_036774', 'DSP2_SendCmd_PostClkLow_Nop09', 'DSP2_Send_Command: post-clk-low NOP step 9'),
    ('LABEL_036777', 'DSP2_SendCmd_PostClkLow_Nop10', 'DSP2_Send_Command: post-clk-low NOP step 10'),
    ('LABEL_03677A', 'DSP2_SendCmd_PostClkLow_Nop11', 'DSP2_Send_Command: post-clk-low NOP step 11'),
    ('LABEL_03677D', 'DSP2_SendCmd_PostClkLow_Nop12', 'DSP2_Send_Command: post-clk-low NOP step 12'),
    ('LABEL_036780', 'DSP2_SendCmd_PostClkLow_Nop13', 'DSP2_Send_Command: post-clk-low NOP step 13'),
    ('LABEL_036783', 'DSP2_SendCmd_PostClkLow_Nop14', 'DSP2_Send_Command: post-clk-low NOP step 14'),
    ('LABEL_036786', 'DSP2_SendCmd_PostClkLow_Nop15', 'DSP2_Send_Command: post-clk-low NOP step 15'),
    ('LABEL_036789', 'DSP2_SendCmd_PostClkLow_Nop16', 'DSP2_Send_Command: post-clk-low NOP step 16'),
    ('LABEL_03678C', 'DSP2_SendCmd_PostClkLow_Nop17', 'DSP2_Send_Command: post-clk-low NOP step 17'),
    ('LABEL_03678F', 'DSP2_SendCmd_PostClkLow_Nop18', 'DSP2_Send_Command: post-clk-low NOP step 18'),
    ('LABEL_036792', 'DSP2_SendCmd_PostClkLow_Nop19', 'DSP2_Send_Command: post-clk-low NOP step 19 (then chip select restore)'),
    ('LABEL_03679C', 'DSP2_SendCmd_Epilogue_Nop01',   'DSP2_Send_Command: epilogue NOP step 1'),
    ('LABEL_03679F', 'DSP2_SendCmd_Epilogue_Nop02',   'DSP2_Send_Command: epilogue NOP step 2'),
    ('LABEL_0367A2', 'DSP2_SendCmd_Epilogue_Nop03',   'DSP2_Send_Command: epilogue NOP step 3'),
    ('LABEL_0367A5', 'DSP2_SendCmd_Epilogue_Nop04',   'DSP2_Send_Command: epilogue NOP step 4'),
    ('LABEL_0367A8', 'DSP2_SendCmd_Epilogue_Nop05',   'DSP2_Send_Command: epilogue NOP step 5'),
    ('LABEL_0367AB', 'DSP2_SendCmd_Epilogue_Nop06',   'DSP2_Send_Command: epilogue NOP step 6'),
    ('LABEL_0367AE', 'DSP2_SendCmd_Epilogue_Nop07',   'DSP2_Send_Command: epilogue NOP step 7'),
    ('LABEL_0367B1', 'DSP2_SendCmd_Epilogue_Nop08',   'DSP2_Send_Command: epilogue NOP step 8'),
    ('LABEL_0367B4', 'DSP2_SendCmd_Epilogue_Nop09',   'DSP2_Send_Command: epilogue NOP step 9'),
    ('LABEL_0367B7', 'DSP2_SendCmd_Epilogue_Nop10',   'DSP2_Send_Command: epilogue NOP step 10'),
    ('LABEL_0367BA', 'DSP2_SendCmd_Epilogue_Nop11',   'DSP2_Send_Command: epilogue NOP step 11'),
    ('LABEL_0367BD', 'DSP2_SendCmd_Epilogue_Nop12',   'DSP2_Send_Command: epilogue NOP step 12'),
    ('LABEL_0367C0', 'DSP2_SendCmd_Epilogue_Nop13',   'DSP2_Send_Command: epilogue NOP step 13'),
    ('LABEL_0367C3', 'DSP2_SendCmd_Epilogue_Nop14',   'DSP2_Send_Command: epilogue NOP step 14'),
    ('LABEL_0367C6', 'DSP2_SendCmd_Epilogue_Nop15',   'DSP2_Send_Command: epilogue NOP step 15'),
    ('LABEL_0367C9', 'DSP2_SendCmd_Epilogue_Nop16',   'DSP2_Send_Command: epilogue NOP step 16 (last; ei 0 + ret)'),

    # -------------------------------------------------------------------------
    # DSP2_Send_Data bit-bang loop control and NOP chains (mirror of Send_Command)
    # -------------------------------------------------------------------------
    ('LABEL_0368DF', 'DSP2_SendData_BitLoop',
     'DSP2_Send_Data: bit-bang loop body, test and set/clear MOSI'),
    ('LABEL_0368EA', 'DSP2_SendData_BitClear',
     'DSP2_Send_Data: MOSI bit = 0 path (res data pin)'),
    ('LABEL_0368ED', 'DSP2_SendData_BitSet_Done',
     'DSP2_Send_Data: after MOSI write, fall into clock-high NOPs'),
    ('LABEL_0368EF', 'DSP2_SendData_ClkHigh_Nop01',  'DSP2_Send_Data: clock-high NOP step 1'),
    ('LABEL_0368F9', 'DSP2_SendData_ClkHigh_Nop02',  'DSP2_Send_Data: clock-high NOP step 2'),
    ('LABEL_0368FC', 'DSP2_SendData_ClkHigh_Nop03',  'DSP2_Send_Data: clock-high NOP step 3'),
    ('LABEL_0368FF', 'DSP2_SendData_ClkHigh_Nop04',  'DSP2_Send_Data: clock-high NOP step 4'),
    ('LABEL_036902', 'DSP2_SendData_ClkHigh_Nop05',  'DSP2_Send_Data: clock-high NOP step 5'),
    ('LABEL_036905', 'DSP2_SendData_ClkHigh_Nop06',  'DSP2_Send_Data: clock-high NOP step 6'),
    ('LABEL_036908', 'DSP2_SendData_ClkHigh_Nop07',  'DSP2_Send_Data: clock-high NOP step 7'),
    ('LABEL_03690B', 'DSP2_SendData_ClkHigh_Nop08',  'DSP2_Send_Data: clock-high NOP step 8'),
    ('LABEL_03690E', 'DSP2_SendData_ClkHigh_Nop09',  'DSP2_Send_Data: clock-high NOP step 9'),
    ('LABEL_036911', 'DSP2_SendData_ClkHigh_Nop10',  'DSP2_Send_Data: clock-high NOP step 10'),
    ('LABEL_036914', 'DSP2_SendData_ClkHigh_Nop11',  'DSP2_Send_Data: clock-high NOP step 11'),
    ('LABEL_036917', 'DSP2_SendData_ClkHigh_Nop12',  'DSP2_Send_Data: clock-high NOP step 12'),
    ('LABEL_03691A', 'DSP2_SendData_ClkHigh_Nop13',  'DSP2_Send_Data: clock-high NOP step 13'),
    ('LABEL_03691D', 'DSP2_SendData_ClkHigh_Nop14',  'DSP2_Send_Data: clock-high NOP step 14'),
    ('LABEL_036920', 'DSP2_SendData_ClkHigh_Nop15',  'DSP2_Send_Data: clock-high NOP step 15'),
    ('LABEL_036923', 'DSP2_SendData_ClkHigh_Nop16',  'DSP2_Send_Data: clock-high NOP step 16'),
    ('LABEL_036926', 'DSP2_SendData_ClkHigh_Nop17',  'DSP2_Send_Data: clock-high NOP step 17 (before clk-low)'),
    ('LABEL_03692C', 'DSP2_SendData_ClkLow_Nop01',   'DSP2_Send_Data: clock-low NOP step 1'),
    ('LABEL_03692F', 'DSP2_SendData_ClkLow_Nop02',   'DSP2_Send_Data: clock-low NOP step 2'),
    ('LABEL_036932', 'DSP2_SendData_ClkLow_Nop03',   'DSP2_Send_Data: clock-low NOP step 3'),
    ('LABEL_036935', 'DSP2_SendData_ClkLow_Nop04',   'DSP2_Send_Data: clock-low NOP step 4'),
    ('LABEL_036938', 'DSP2_SendData_ClkLow_Nop05',   'DSP2_Send_Data: clock-low NOP step 5'),
    ('LABEL_03693B', 'DSP2_SendData_ClkLow_Nop06',   'DSP2_Send_Data: clock-low NOP step 6'),
    ('LABEL_03693E', 'DSP2_SendData_ClkLow_Nop07',   'DSP2_Send_Data: clock-low NOP step 7'),
    ('LABEL_036941', 'DSP2_SendData_ClkLow_Nop08',   'DSP2_Send_Data: clock-low NOP step 8'),
    ('LABEL_036944', 'DSP2_SendData_ClkLow_Nop09',   'DSP2_Send_Data: clock-low NOP step 9'),
    ('LABEL_036947', 'DSP2_SendData_ClkLow_Nop10',   'DSP2_Send_Data: clock-low NOP step 10'),
    ('LABEL_03694A', 'DSP2_SendData_ClkLow_Nop11',   'DSP2_Send_Data: clock-low NOP step 11'),
    ('LABEL_03694D', 'DSP2_SendData_ClkLow_Nop12',   'DSP2_Send_Data: clock-low NOP step 12'),
    ('LABEL_036950', 'DSP2_SendData_ClkLow_Nop13',   'DSP2_Send_Data: clock-low NOP step 13'),
    ('LABEL_036953', 'DSP2_SendData_ClkLow_Nop14',   'DSP2_Send_Data: clock-low NOP step 14'),
    ('LABEL_036956', 'DSP2_SendData_ClkLow_Nop15',   'DSP2_Send_Data: clock-low NOP step 15'),
    ('LABEL_036959', 'DSP2_SendData_ClkLow_Nop16',   'DSP2_Send_Data: clock-low NOP step 16'),
    ('LABEL_03695C', 'DSP2_SendData_ClkLow_Nop17',   'DSP2_Send_Data: clock-low NOP step 17'),
    ('LABEL_03695F', 'DSP2_SendData_ClkLow_Nop18',   'DSP2_Send_Data: clock-low NOP step 18'),
    ('LABEL_036962', 'DSP2_SendData_ClkLow_Nop19',   'DSP2_Send_Data: clock-low NOP step 19 (loop branch)'),
    ('LABEL_03696A', 'DSP2_SendData_PostLoop_Entry',
     'DSP2_Send_Data: post-bit-loop entry (all 8 bits sent)'),
    ('LABEL_03696C', 'DSP2_SendData_PostLoop_Nop01',  'DSP2_Send_Data: post-loop NOP step 1'),
    ('LABEL_036972', 'DSP2_SendData_PostLoop_Nop02',  'DSP2_Send_Data: post-loop NOP step 2'),
    ('LABEL_036975', 'DSP2_SendData_PostLoop_Nop03',  'DSP2_Send_Data: post-loop NOP step 3'),
    ('LABEL_036978', 'DSP2_SendData_PostLoop_Nop04',  'DSP2_Send_Data: post-loop NOP step 4'),
    ('LABEL_03697B', 'DSP2_SendData_PostLoop_Nop05',  'DSP2_Send_Data: post-loop NOP step 5'),
    ('LABEL_03697E', 'DSP2_SendData_PostLoop_Nop06',  'DSP2_Send_Data: post-loop NOP step 6'),
    ('LABEL_036981', 'DSP2_SendData_PostLoop_Nop07',  'DSP2_Send_Data: post-loop NOP step 7'),
    ('LABEL_036984', 'DSP2_SendData_PostLoop_Nop08',  'DSP2_Send_Data: post-loop NOP step 8'),
    ('LABEL_036987', 'DSP2_SendData_PostLoop_Nop09',  'DSP2_Send_Data: post-loop NOP step 9'),
    ('LABEL_03698A', 'DSP2_SendData_PostLoop_Nop10',  'DSP2_Send_Data: post-loop NOP step 10'),
    ('LABEL_03698D', 'DSP2_SendData_PostLoop_Nop11',  'DSP2_Send_Data: post-loop NOP step 11'),
    ('LABEL_036990', 'DSP2_SendData_PostLoop_Nop12',  'DSP2_Send_Data: post-loop NOP step 12'),
    ('LABEL_036993', 'DSP2_SendData_PostLoop_Nop13',  'DSP2_Send_Data: post-loop NOP step 13'),
    ('LABEL_036996', 'DSP2_SendData_PostLoop_Nop14',  'DSP2_Send_Data: post-loop NOP step 14'),
    ('LABEL_036999', 'DSP2_SendData_PostLoop_Nop15',  'DSP2_Send_Data: post-loop NOP step 15'),
    ('LABEL_03699C', 'DSP2_SendData_PostLoop_Nop16',  'DSP2_Send_Data: post-loop NOP step 16'),
    ('LABEL_03699F', 'DSP2_SendData_PostLoop_Nop17',  'DSP2_Send_Data: post-loop NOP step 17 (before clk-low)'),
    ('LABEL_0369A5', 'DSP2_SendData_PostClkLow_Nop01', 'DSP2_Send_Data: post-clk-low NOP step 1'),
    ('LABEL_0369A8', 'DSP2_SendData_PostClkLow_Nop02', 'DSP2_Send_Data: post-clk-low NOP step 2'),
    ('LABEL_0369AB', 'DSP2_SendData_PostClkLow_Nop03', 'DSP2_Send_Data: post-clk-low NOP step 3'),
    ('LABEL_0369AE', 'DSP2_SendData_PostClkLow_Nop04', 'DSP2_Send_Data: post-clk-low NOP step 4'),
    ('LABEL_0369B1', 'DSP2_SendData_PostClkLow_Nop05', 'DSP2_Send_Data: post-clk-low NOP step 5'),
    ('LABEL_0369B4', 'DSP2_SendData_PostClkLow_Nop06', 'DSP2_Send_Data: post-clk-low NOP step 6'),
    ('LABEL_0369B7', 'DSP2_SendData_PostClkLow_Nop07', 'DSP2_Send_Data: post-clk-low NOP step 7'),
    ('LABEL_0369BA', 'DSP2_SendData_PostClkLow_Nop08', 'DSP2_Send_Data: post-clk-low NOP step 8'),
    ('LABEL_0369BD', 'DSP2_SendData_PostClkLow_Nop09', 'DSP2_Send_Data: post-clk-low NOP step 9'),
    ('LABEL_0369C0', 'DSP2_SendData_PostClkLow_Nop10', 'DSP2_Send_Data: post-clk-low NOP step 10'),
    ('LABEL_0369C3', 'DSP2_SendData_PostClkLow_Nop11', 'DSP2_Send_Data: post-clk-low NOP step 11'),
    ('LABEL_0369C6', 'DSP2_SendData_PostClkLow_Nop12', 'DSP2_Send_Data: post-clk-low NOP step 12'),
    ('LABEL_0369C9', 'DSP2_SendData_PostClkLow_Nop13', 'DSP2_Send_Data: post-clk-low NOP step 13'),
    ('LABEL_0369CC', 'DSP2_SendData_PostClkLow_Nop14', 'DSP2_Send_Data: post-clk-low NOP step 14'),
    ('LABEL_0369CF', 'DSP2_SendData_PostClkLow_Nop15', 'DSP2_Send_Data: post-clk-low NOP step 15'),
    ('LABEL_0369D2', 'DSP2_SendData_PostClkLow_Nop16', 'DSP2_Send_Data: post-clk-low NOP step 16'),
    ('LABEL_0369D5', 'DSP2_SendData_PostClkLow_Nop17', 'DSP2_Send_Data: post-clk-low NOP step 17'),
    ('LABEL_0369D8', 'DSP2_SendData_PostClkLow_Nop18', 'DSP2_Send_Data: post-clk-low NOP step 18'),
    ('LABEL_0369DB', 'DSP2_SendData_PostClkLow_Nop19', 'DSP2_Send_Data: post-clk-low NOP step 19 (then chip-select restore)'),
    ('LABEL_0369E5', 'DSP2_SendData_Epilogue_Nop01',   'DSP2_Send_Data: epilogue NOP step 1'),
    ('LABEL_0369E8', 'DSP2_SendData_Epilogue_Nop02',   'DSP2_Send_Data: epilogue NOP step 2'),
    ('LABEL_0369EB', 'DSP2_SendData_Epilogue_Nop03',   'DSP2_Send_Data: epilogue NOP step 3'),
    ('LABEL_0369EE', 'DSP2_SendData_Epilogue_Nop04',   'DSP2_Send_Data: epilogue NOP step 4'),
    ('LABEL_0369F1', 'DSP2_SendData_Epilogue_Nop05',   'DSP2_Send_Data: epilogue NOP step 5'),
    ('LABEL_0369F4', 'DSP2_SendData_Epilogue_Nop06',   'DSP2_Send_Data: epilogue NOP step 6'),
    ('LABEL_0369F7', 'DSP2_SendData_Epilogue_Nop07',   'DSP2_Send_Data: epilogue NOP step 7'),
    ('LABEL_0369FA', 'DSP2_SendData_Epilogue_Nop08',   'DSP2_Send_Data: epilogue NOP step 8'),
    ('LABEL_0369FD', 'DSP2_SendData_Epilogue_Nop09',   'DSP2_Send_Data: epilogue NOP step 9'),
    ('LABEL_036A00', 'DSP2_SendData_Epilogue_Nop10',   'DSP2_Send_Data: epilogue NOP step 10'),
    ('LABEL_036A03', 'DSP2_SendData_Epilogue_Nop11',   'DSP2_Send_Data: epilogue NOP step 11'),
    ('LABEL_036A06', 'DSP2_SendData_Epilogue_Nop12',   'DSP2_Send_Data: epilogue NOP step 12'),
    ('LABEL_036A09', 'DSP2_SendData_Epilogue_Nop13',   'DSP2_Send_Data: epilogue NOP step 13'),
    ('LABEL_036A0C', 'DSP2_SendData_Epilogue_Nop14',   'DSP2_Send_Data: epilogue NOP step 14'),
    ('LABEL_036A0F', 'DSP2_SendData_Epilogue_Nop15',   'DSP2_Send_Data: epilogue NOP step 15'),
    ('LABEL_036A12', 'DSP2_SendData_Epilogue_Nop16',   'DSP2_Send_Data: epilogue NOP step 16 (last; ei 0 + ret)'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP dispatch and diff helpers
    # -------------------------------------------------------------------------
    ('LABEL_036A42', 'DSP_DispatchCommand_DSP2Path',
     'DSP_DispatchCommand: chip=1, route to DSP2_Send_Command'),
    ('LABEL_036A49', 'DSP_DispatchCommand_InvalidChip',
     'DSP_DispatchCommand: unknown chip number, set error flag'),
    ('LABEL_036A4B', 'DSP_DispatchCommand_Epilogue',
     'DSP_DispatchCommand: common epilogue, return HL=error'),
    ('LABEL_036A63', 'DSP_DispatchData_DSP2Path',
     'DSP_DispatchData: chip=1, route to DSP2_Send_Data'),
    ('LABEL_036A6A', 'DSP_DispatchData_InvalidChip',
     'DSP_DispatchData: unknown chip number, set error flag'),
    ('LABEL_036A6C', 'DSP_DispatchData_Epilogue',
     'DSP_DispatchData: common epilogue, return HL=error'),

    ('LABEL_036A94', 'DSP_AlgoChange_NoChange',
     'DSP_AlgoChange_CheckAndFlag: algo unchanged, skip flag'),
    ('LABEL_036A9B', 'DSP_AlgoChange_FlagAndClear',
     'DSP_AlgoChange_CheckAndFlag: algo changed, set dirty flag'),

    ('LABEL_036AA8', 'DSP_SlotParam_DiffLoop',
     'DSP_SlotParam_DiffAndFlag: inner loop comparing slot param bytes'),
    ('LABEL_036AE4', 'DSP_SlotParam_DiffMatch',
     'DSP_SlotParam_DiffAndFlag: byte matches, continue loop'),
    ('LABEL_036AF6', 'DSP_SlotParam_DiffMismatch',
     'DSP_SlotParam_DiffAndFlag: mismatch found, set dirty flag'),

    ('LABEL_036B05', 'DSP_EFFParam_DiffOuter',
     'DSP_EFFParam_DiffAllAndFlag: outer EFF slot loop start'),
    ('LABEL_036B22', 'DSP_EFFParam_DiffMid',
     'DSP_EFFParam_DiffAllAndFlag: mid-level loop (2 entries per EFF slot)'),
    ('LABEL_036B89', 'DSP_EFFParam_DiffMidMatch',
     'DSP_EFFParam_DiffAllAndFlag: mid-level match path, next entry'),
    ('LABEL_036BA1', 'DSP_EFFParam_DiffMidNext',
     'DSP_EFFParam_DiffAllAndFlag: mid-level loop increment'),
    ('LABEL_036BA8', 'DSP_EFFParam_DiffInner',
     'DSP_EFFParam_DiffAllAndFlag: inner loop (0x11 param bytes per entry)'),
    ('LABEL_036BB1', 'DSP_EFFParam_DiffInnerBody',
     'DSP_EFFParam_DiffAllAndFlag: inner loop body comparing single byte'),
    ('LABEL_036C18', 'DSP_EFFParam_DiffInnerMatch',
     'DSP_EFFParam_DiffAllAndFlag: inner byte match, continue'),
    ('LABEL_036C30', 'DSP_EFFParam_DiffInnerNext',
     'DSP_EFFParam_DiffAllAndFlag: inner loop increment'),
    ('LABEL_036C39', 'DSP_EFFParam_DiffLevel4',
     'DSP_EFFParam_DiffAllAndFlag: 4th level loop (2-entry sub-block)'),
    ('LABEL_036C40', 'DSP_EFFParam_DiffLevel4Body',
     'DSP_EFFParam_DiffAllAndFlag: 4th level loop body'),
    ('LABEL_036CA7', 'DSP_EFFParam_DiffLevel4Match',
     'DSP_EFFParam_DiffAllAndFlag: 4th level match path'),
    ('LABEL_036CBF', 'DSP_EFFParam_DiffLevel4Next',
     'DSP_EFFParam_DiffAllAndFlag: 4th level loop increment'),
    ('LABEL_036CC6', 'DSP_EFFParam_DiffAlgoSection',
     'DSP_EFFParam_DiffAllAndFlag: algo-change diff section within loop'),
    ('LABEL_036D1F', 'DSP_EFFParam_AlgoChangePath',
     'DSP_EFFParam_DiffAllAndFlag: algo changed sub-path'),
    ('LABEL_036D35', 'DSP_EFFParam_DiffOuterNext',
     'DSP_EFFParam_DiffAllAndFlag: outer loop increment'),
    ('LABEL_036D7E', 'DSP_EFFParam_DiffEpilogue',
     'DSP_EFFParam_DiffAllAndFlag: epilogue (pop + ret)'),

    ('LABEL_036DAF', 'DSP_Config_ClampLoop',
     'DSP_Config_ClampLimits: loop body iterating param bytes'),
    ('LABEL_036DB5', 'DSP_Config_ClampApply',
     'DSP_Config_ClampLimits: apply clamp (copy limit value)'),
    ('LABEL_036DE3', 'DSP_Config_ClampNext',
     'DSP_Config_ClampLimits: loop increment and branch'),
    ('LABEL_036DEA', 'DSP_Config_ClampData',
     'DSP_Config_ClampLimits: 11-byte clamp limit table'),

    ('LABEL_036E12', 'CalcSampleAddr',
     'Calculate sample ROM address from voice waveform index'),

    ('LABEL_036E70', 'EFF_SlotActive_CheckSlot',
     'EFF_SlotActive_UpdateFlags: inner loop checking slot active condition'),
    ('LABEL_036E87', 'EFF_SlotActive_SlotActive',
     'EFF_SlotActive_UpdateFlags: slot is active, update flag word'),
    ('LABEL_036E8D', 'EFF_SlotActive_SlotInactive',
     'EFF_SlotActive_UpdateFlags: slot is inactive, clear flag'),
    ('LABEL_036EB9', 'EFF_SlotActive_VoiceCheck',
     'EFF_SlotActive_UpdateFlags: voice active check'),
    ('LABEL_036EBB', 'EFF_SlotActive_VoiceInactive',
     'EFF_SlotActive_UpdateFlags: voice not active, clear entry'),
    ('LABEL_036EED', 'EFF_SlotActive_AlgoCheck',
     'EFF_SlotActive_UpdateFlags: check algo index for slot match'),
    ('LABEL_036F0B', 'EFF_SlotActive_LoopNext',
     'EFF_SlotActive_UpdateFlags: advance outer loop counter'),
    ('LABEL_036FBA', 'EFF_SlotActive_InnerLoopNext',
     'EFF_SlotActive_UpdateFlags: advance inner sub-slot loop'),
    ('LABEL_036FCA', 'EFF_SlotActive_Epilogue',
     'EFF_SlotActive_UpdateFlags: epilogue (pop + ret)'),

    ('LABEL_036FE6', 'EFF_DSPLink_ResetFlags_ZeroPath',
     'EFF_DSPLink_ResetFlags: algo-link index is 0, skip reset'),
    ('LABEL_036FFD', 'EFF_DSPLink_ResetFlags_LoopNext',
     'EFF_DSPLink_ResetFlags: outer loop increment'),

    # -------------------------------------------------------------------------
    # 037xxx - EFF_DspChannel_InitFlags inner loop labels
    # -------------------------------------------------------------------------
    ('LABEL_037003', 'EFF_DSPLink_ResetFlags_InnerBody',
     'EFF_DSPLink_ResetFlags: inner loop body clearing link-reset flags'),
    ('LABEL_037020', 'EFF_DspChannel_Init_AlgoCheck',
     'EFF_DspChannel_InitFlags: algo-change check for this EFF slot'),
    ('LABEL_03703A', 'EFF_DspChannel_Init_SlotNext',
     'EFF_DspChannel_InitFlags: advance outer EFF slot loop counter'),
    ('LABEL_037057', 'EFF_DspChannel_Init_FreqLoop',
     'EFF_DspChannel_InitFlags: freq-param dirty-flag loop (0x11 entries)'),
    ('LABEL_037077', 'EFF_DspChannel_Init_CoeffLoop',
     'EFF_DspChannel_InitFlags: coeff-param dirty-flag loop (2 entries)'),
    ('LABEL_03707D', 'EFF_DspChannel_Init_CoeffNext',
     'EFF_DspChannel_InitFlags: coeff loop increment and branch'),
    ('LABEL_03709B', 'EFF_DspChannel_Init_Coeff2Loop',
     'EFF_DspChannel_InitFlags: second coeff dirty-flag loop'),
    ('LABEL_0370A1', 'EFF_DspChannel_Init_Coeff2Next',
     'EFF_DspChannel_InitFlags: second coeff loop increment and branch'),
    ('LABEL_0370BF', 'EFF_DspChannel_Init_MultiTableDirty',
     'EFF_DspChannel_InitFlags: set dirty flags across multiple state tables'),
    ('LABEL_037159', 'EFF_DspChannel_Init_AlgoTypePath',
     'EFF_DspChannel_InitFlags: algo-type-specific dirty flag propagation'),
    ('LABEL_03716D', 'EFF_DspChannel_Init_OuterNext',
     'EFF_DspChannel_InitFlags: outer slot loop increment'),

    # Per-algo-type dirty-flag sub-paths (37 algo types, each sets different state words)
    ('LABEL_0371CE', 'EFF_DspChanInit_AlgoType0_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x00 dirty flag table entry'),
    ('LABEL_037210', 'EFF_DspChanInit_AlgoType1_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x01 dirty flag table entry'),
    ('LABEL_037258', 'EFF_DspChanInit_AlgoType2_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x02 dirty flag table entry'),
    ('LABEL_03729A', 'EFF_DspChanInit_AlgoType3_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x03 dirty flag table entry'),
    ('LABEL_0372E2', 'EFF_DspChanInit_AlgoType4_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x04 dirty flag table entry'),
    ('LABEL_037324', 'EFF_DspChanInit_AlgoType5_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x05 dirty flag table entry'),
    ('LABEL_03736C', 'EFF_DspChanInit_AlgoType6_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x06 dirty flag table entry'),
    ('LABEL_0373AE', 'EFF_DspChanInit_AlgoType7_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x07 dirty flag table entry'),
    ('LABEL_0373F6', 'EFF_DspChanInit_AlgoType8_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x08 dirty flag table entry'),
    ('LABEL_037438', 'EFF_DspChanInit_AlgoType9_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x09 dirty flag table entry'),
    ('LABEL_037495', 'EFF_DspChanInit_AlgoType4F_SubA',
     'EFF_DspChannel_InitFlags: algo type 0x4F dirty sub-path A'),
    ('LABEL_0374D9', 'EFF_DspChanInit_AlgoType4F_SubB',
     'EFF_DspChannel_InitFlags: algo type 0x4F dirty sub-path B'),
    ('LABEL_03751D', 'EFF_DspChanInit_AlgoType4F_SubC',
     'EFF_DspChannel_InitFlags: algo type 0x4F dirty sub-path C'),
    ('LABEL_037561', 'EFF_DspChanInit_AlgoType4F_Epilogue',
     'EFF_DspChannel_InitFlags: algo type 0x4F dirty epilogue'),
    ('LABEL_037592', 'EFF_DspChanInit_AlgoType35_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x35/0x0F dirty flag path'),
    ('LABEL_03761E', 'EFF_DspChanInit_AlgoType35_SubA',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path A'),
    ('LABEL_037676', 'EFF_DspChanInit_AlgoType35_SubB',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path B'),
    ('LABEL_03768E', 'EFF_DspChanInit_AlgoType35_SubC',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path C'),
    ('LABEL_0376D6', 'EFF_DspChanInit_AlgoType35_SubD',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path D'),
    ('LABEL_0376EC', 'EFF_DspChanInit_AlgoType35_SubE',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path E'),
    ('LABEL_037702', 'EFF_DspChanInit_AlgoType35_SubF',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path F'),
    ('LABEL_037746', 'EFF_DspChanInit_AlgoType35_Epilogue',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty epilogue'),

    # EFF_MuteLoop inner labels
    ('LABEL_037769', 'EFF_MuteLoop_SlotBody',
     'EFF_MuteLoop: inner loop body checking slot active and voice link'),
    ('LABEL_0377BD', 'EFF_MuteLoop_NoMute',
     'EFF_MuteLoop: slot not active or not mutable, call mute helper'),
    ('LABEL_0377C5', 'EFF_MuteLoop_SlotNext',
     'EFF_MuteLoop: advance slot counter and branch'),
    ('LABEL_0377CB', 'EFF_MuteLoop_Epilogue',
     'EFF_MuteLoop: epilogue, optionally flush mute (pop iz + ret)'),
    ('LABEL_0377D6', 'EFF_MuteLoop_NoFlush',
     'EFF_MuteLoop: no mute action taken, return without flush'),

    # DSP_ResetLoop inner labels
    ('LABEL_0377DF', 'DSP_ResetLoop_Body',
     'DSP_ResetLoop: loop body calling chip reset for each DSP (0..1)'),
    ('LABEL_0377EB', 'DSP_ResetLoop_Epilogue',
     'DSP_ResetLoop: epilogue (popw iz + ret)'),

    # DSP_MuteLoop inner labels
    ('LABEL_0377F4', 'DSP_MuteLoop_Body',
     'DSP_MuteLoop: loop body; mute DSP chip if state flag set'),
    ('LABEL_03780C', 'DSP_MuteLoop_Next',
     'DSP_MuteLoop: advance chip counter and branch'),
    ('LABEL_037812', 'DSP_MuteLoop_Epilogue',
     'DSP_MuteLoop: epilogue (popw iz + ret)'),

    # DSP_UnmuteLoop inner labels
    ('LABEL_03781B', 'DSP_UnmuteLoop_Body',
     'DSP_UnmuteLoop: loop body; unmute DSP chip if state flag set'),
    ('LABEL_037833', 'DSP_UnmuteLoop_Next',
     'DSP_UnmuteLoop: advance chip counter and branch'),
    ('LABEL_037839', 'DSP_UnmuteLoop_Epilogue',
     'DSP_UnmuteLoop: epilogue (popw iz + ret)'),

    # Unsigned_Max_Select body
    ('LABEL_03784E', 'Unsigned_Max_Select_Return',
     'Unsigned_Max_Select: BC <= WA path, return WA as max in HL'),

    # EFF_ParamIterator_Process inner labels
    ('LABEL_0378A4', 'EFF_ParamIter_CountClamp',
     'EFF_ParamIterator_Process: clamp iteration count to 0x11 max'),
    ('LABEL_0378AC', 'EFF_ParamIter_StdLoop',
     'EFF_ParamIterator_Process: standard loop body (non-0x35/0xF algo)'),
    ('LABEL_037903', 'EFF_ParamIter_StdLoopNext',
     'EFF_ParamIterator_Process: standard loop increment and branch'),
    ('LABEL_03790C', 'EFF_ParamIter_SpecialAlgoPath',
     'EFF_ParamIterator_Process: special path for algo 0x35 / 0xF'),
    ('LABEL_03793A', 'EFF_ParamIter_SpecialLoop',
     'EFF_ParamIterator_Process: special algo loop body over param table'),
    ('LABEL_037980', 'EFF_ParamIter_SpecialLoopNext',
     'EFF_ParamIterator_Process: special loop advance (inc xiz) and branch'),
    ('LABEL_037987', 'EFF_ParamIter_Epilogue',
     'EFF_ParamIterator_Process: epilogue (pop xiz + inc 6,xsp + ret)'),

    # EFF_Change_Handler dispatch labels
    ('LABEL_0379E2', 'EFF_Change_Handler_NonSlot2',
     'EFF_Change_Handler: iz != 2, call generic EFF change path'),
    ('LABEL_0379EE', 'EFF_Change_Handler_SlotDispatch',
     'EFF_Change_Handler: dispatch on slot index (2/3/4 vs other)'),
    ('LABEL_037A19', 'EFF_Change_Handler_Slot234_AlgoPath',
     'EFF_Change_Handler: slots 2/3/4, check preset type for algo path'),
    ('LABEL_037A40', 'EFF_Change_Handler_Slot234_AltPath',
     'EFF_Change_Handler: slots 2/3/4, alternate preset type (call 0x381BC)'),
    ('LABEL_037A5B', 'EFF_Change_Handler_Epilogue',
     'EFF_Change_Handler: common epilogue (volume check + ret)'),

    # EFF_HeaderChangeDataLoop inner labels
    ('LABEL_037A78', 'EFF_HeaderChangeLoop_Body',
     'EFF_HeaderChangeDataLoop: main loop body per EFF slot'),
    ('LABEL_037A8C', 'EFF_HeaderChangeLoop_CallAlgo',
     'EFF_HeaderChangeDataLoop: algo-applicable path, call 0x380AB'),
    ('LABEL_037A92', 'EFF_HeaderChangeLoop_PostAlgo',
     'EFF_HeaderChangeDataLoop: check active state table entry'),
    ('LABEL_037AAF', 'EFF_HeaderChangeLoop_ActiveSlot',
     'EFF_HeaderChangeDataLoop: slot active, compute max volume'),
    ('LABEL_037AC6', 'EFF_HeaderChangeLoop_CallChange',
     'EFF_HeaderChangeDataLoop: call EFF_Change_Handler for this slot'),
    ('LABEL_037AD6', 'EFF_HeaderChangeLoop_Epilogue',
     'EFF_HeaderChangeDataLoop: epilogue, optional state-apply call'),

    # EFF_LinkLoop inner labels
    ('LABEL_037AF4', 'EFF_LinkLoop_Body',
     'EFF_LinkLoop: main loop body per EFF slot (check link active)'),
    ('LABEL_037B31', 'EFF_LinkLoop_Next',
     'EFF_LinkLoop: advance slot counter and branch'),
    ('LABEL_037B39', 'EFF_LinkLoop_Epilogue',
     'EFF_LinkLoop: epilogue (popw iz + inc 4,xsp + ret)'),

    # EFF_SecondaryLinkPath inner labels
    ('LABEL_037B4F', 'EFF_SecLinkPath_Pass1Body',
     'EFF_SecondaryLinkPath: pass-1 loop body (find max disconnect volume)'),
    ('LABEL_037B8C', 'EFF_SecLinkPath_Pass1Next',
     'EFF_SecondaryLinkPath: pass-1 loop decrement and branch'),
    ('LABEL_037B96', 'EFF_SecLinkPath_Pass1Epilogue',
     'EFF_SecondaryLinkPath: pass-1 done, call flush if iz > 0'),
    ('LABEL_037BA0', 'EFF_SecLinkPath_Pass2Start',
     'EFF_SecondaryLinkPath: pass-2 loop start'),
    ('LABEL_037BAC', 'EFF_SecLinkPath_Pass2Body',
     'EFF_SecondaryLinkPath: pass-2 loop body (apply link disconnect)'),
    ('LABEL_037BF6', 'EFF_SecLinkPath_Pass2MaxVol',
     'EFF_SecondaryLinkPath: pass-2 max-volume accumulate step'),
    ('LABEL_037C0D', 'EFF_SecLinkPath_Pass2Next',
     'EFF_SecondaryLinkPath: pass-2 loop decrement and branch'),
    ('LABEL_037C17', 'EFF_SecLinkPath_Pass2Epilogue',
     'EFF_SecondaryLinkPath: pass-2 done, call flush if iz > 0'),
    ('LABEL_037C21', 'EFF_SecLinkPath_Epilogue',
     'EFF_SecondaryLinkPath: full epilogue (pop xiz + inc 4,xsp + ret)'),

    # EFF_VolumeLoop inner labels
    ('LABEL_037C32', 'EFF_VolumeLoop_Body',
     'EFF_VolumeLoop: main loop body (check dirty vol flag, compute delta)'),
    ('LABEL_037D16', 'EFF_VolumeLoop_ApplyDelta',
     'EFF_VolumeLoop: apply computed volume delta, call write helper'),
    ('LABEL_037D35', 'EFF_VolumeLoop_Next',
     'EFF_VolumeLoop: advance slot counter and branch'),
    ('LABEL_037D3C', 'EFF_VolumeLoop_Epilogue',
     'EFF_VolumeLoop: epilogue (popw iz + inc 4,xsp + ret)'),

    # EFF_DisconnectLoop inner labels
    ('LABEL_037D4E', 'EFF_DisconnectLoop_Body',
     'EFF_DisconnectLoop: main loop body (skip slots 2 and 3, call disconnect)'),
    ('LABEL_037D62', 'EFF_DisconnectLoop_Next',
     'EFF_DisconnectLoop: advance slot counter and branch'),
    ('LABEL_037D6A', 'EFF_DisconnectLoop_Epilogue',
     'EFF_DisconnectLoop: epilogue (popw iz + inc 4,xsp + ret)'),

    # DSP_State_Dispatcher inner labels
    ('LABEL_037D7D', 'DSP_StateDispatcher_MutePath',
     'DSP_State_Dispatcher: no reset flag, call EFF_MuteLoop instead'),
    ('LABEL_037D82', 'DSP_StateDispatcher_PostMute',
     'DSP_State_Dispatcher: after mute/reset, call DSP_MuteLoop'),
    ('LABEL_037D98', 'DSP_StateDispatcher_DisconnectPath',
     'DSP_State_Dispatcher: reset or preset change, call EFF_DisconnectLoop'),
    ('LABEL_037DA3', 'DSP_StateDispatcher_UnmutePath',
     'DSP_State_Dispatcher: call DSP_UnmuteLoop then chain all EFF loops'),
    ('LABEL_037DC2', 'DSP_StateDispatcher_AlgoLoop',
     'DSP_State_Dispatcher: algo index update loop (EFF slots 4..0)'),
    ('LABEL_037E16', 'DSP_StateDispatcher_AlgoClear',
     'DSP_State_Dispatcher: clear algo index entry (voice not mapped)'),
    ('LABEL_037E26', 'DSP_StateDispatcher_AlgoNext',
     'DSP_State_Dispatcher: advance algo loop counter and branch'),
    ('LABEL_037E2E', 'DSP_StateDispatcher_Epilogue',
     'DSP_State_Dispatcher: epilogue (pop xiz + ret)'),
]


def main():
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(base, 'subcpu', 'kn5000_subprogram_v142.s')

    with open(src, 'rb') as f:
        content = f.read().decode('latin-1')

    renamed = 0
    for old_label, new_label, comment in RENAMES:
        if old_label + ':' not in content:
            print(f'  WARNING: {old_label} not found, skipping')
            continue

        refs = len(re.findall(r'\b' + re.escape(old_label) + r'\b', content))
        new_content = re.sub(r'\b' + re.escape(old_label) + r'\b', new_label, content)

        if new_content != content:
            content = new_content
            renamed += 1
            print(f'  {old_label:25s} -> {new_label:45s} ({refs} refs)')

    # Check maincpu for cross-references
    maincpu_src = os.path.join(base, 'maincpu', 'kn5000_v10_program.s')
    with open(maincpu_src, 'rb') as f:
        maincpu_content = f.read().decode('latin-1')

    maincpu_renames = 0
    for old_label, new_label, _ in RENAMES:
        if old_label in maincpu_content:
            maincpu_content = re.sub(r'\b' + re.escape(old_label) + r'\b', new_label, maincpu_content)
            maincpu_renames += 1

    with open(src, 'wb') as f:
        f.write(content.encode('latin-1'))

    if maincpu_renames > 0:
        with open(maincpu_src, 'wb') as f:
            f.write(maincpu_content.encode('latin-1'))

    print(f'\nRenamed {renamed} labels in subcpu ({maincpu_renames} cross-refs in maincpu)')


if __name__ == '__main__':
    main()
