#!/usr/bin/env python3
"""Rename LABEL_* to semantic names in region EE6E54-EE8CF8.

This region contains the sound/style index system: a multi-tier structure
of pointer tables, sound parameter data blocks, voice configuration lists,
tone data entries, and empty (0xFF-filled) reservation slots.

Structure overview:
  EE6E54-EE75F9  Sound parameter data blocks (tone gen config for styles)
  EE75FA-EE7755  Tier-1 pointer tables (SndIndex) pointing to data blocks
  EE7756-EE7A86  Tier-1 pointer tables continued (extended style slots)
  EE7A87-EE7C9F  Empty/reserved style slots (0xFF fill blocks)
  EE7CA7-EE7D26  Tier-2 pointer table (voice config list pointers)
  EE7D27-EE86AF  Tier-2 dispatch table (voice config + empty slots)
  EE7FA8-EE837F  Voice configuration lists (function pointer chains)
  EE8380-EE83FC  Empty voice config entries (0xFFFFFFFF terminators)
  EE8400-EE86AC  Voice config entries (mixed populated/empty)
  EE86B0-EE86CF  Default/fallback voice config entry
  EE86D0-EE89D0  Tier-3 pointer table (tone data entry pointers)
  EE89D1-EE8AC9  Tone reference data entries (FB40xx references)
  EE8AD1-EE8C74  Empty/reserved tone slots (0xFF fill blocks)
  EE8C75         Default/fallback tone entry
  EE8C7E-EE8CF7  System cross-reference table (Seq/MIDI/DiskOp pointers)
  EE8CF8         Style dispatch pointer table (FDExxx handler refs)

Uses binary I/O to handle Latin-1 encoding safely.
NEVER use the Edit tool on kn5000_v10_program.s -- it corrupts Latin-1.
"""

import os
import re

# ---------------------------------------------------------------------------
# Rename table: (old_label, new_label, brief_comment)
# ---------------------------------------------------------------------------

RENAMES = [
    # ==================================================================
    # Region 1: Sound parameter data blocks (EE6E54-EE75F9)
    # Each block contains tone generator parameters for a style/sound
    # configuration. Blocks end with 0xF0, 0xFF terminators or similar.
    # These are referenced by the pointer tables at EE75FA+.
    # ==================================================================

    ('LABEL_EE6E54', 'SndParam_MultiOsc_6E54',
     'Sound param block: multi-oscillator tone config (6-osc + volume)'),
    ('LABEL_EE6F08', 'SndParam_EnvCurve_6F08',
     'Sound param block: envelope curve data with amplitude ramp points'),
    ('LABEL_EE6FB0', 'SndParam_BaseInit_6FB0',
     'Sound param block: base initialization (oscillator enable + volume reset)'),
    ('LABEL_EE7010', 'SndParam_FilterCfg_7010',
     'Sound param block: filter config with cutoff/resonance coefficients'),
    ('LABEL_EE7076', 'SndParam_ModRoute_7076',
     'Sound param block: modulation routing with LFO depth/frequency curves'),
    ('LABEL_EE710C', 'SndParam_VolPan_710C',
     'Sound param block: volume/pan basic setup with amplitude envelope'),
    ('LABEL_EE7168', 'SndParam_Detune_7168',
     'Sound param block: detuning parameters (pitch offset + chorus depth)'),
    ('LABEL_EE71B6', 'SndParam_PitchEnv_71B6',
     'Sound param block: pitch envelope with jump-table-like dispatch entries'),
    ('LABEL_EE7218', 'SndParam_ChorusWide_7218',
     'Sound param block: wide chorus (detune + pan spread + modulation)'),
    ('LABEL_EE727A', 'SndParam_FilterEnv_727A',
     'Sound param block: filter envelope with cutoff sweep coefficients'),
    ('LABEL_EE72F4', 'SndParam_FilterBase_72F4',
     'Sound param block: filter base (cutoff + resonance, no envelope)'),
    ('LABEL_EE736E', 'SndParam_Tremolo_736E',
     'Sound param block: tremolo with LFO depth + volume modulation'),
    ('LABEL_EE73A4', 'SndParam_TremLow_73A4',
     'Sound param block: low tremolo variant (reduced depth)'),
    ('LABEL_EE73DA', 'SndParam_TremHigh_73DA',
     'Sound param block: high tremolo variant (increased depth)'),
    ('LABEL_EE7410', 'SndParam_TremAlt_7410',
     'Sound param block: alternate tremolo curve'),
    ('LABEL_EE7446', 'SndParam_TremSlow_7446',
     'Sound param block: slow tremolo variant'),
    ('LABEL_EE747C', 'SndParam_TremMed_747C',
     'Sound param block: medium tremolo variant'),
    ('LABEL_EE74B2', 'SndParam_Vibrato_74B2',
     'Sound param block: vibrato with pitch modulation depth'),
    ('LABEL_EE74E8', 'SndParam_VibratoB_74E8',
     'Sound param block: vibrato variant B'),
    ('LABEL_EE751E', 'SndParam_VibratoC_751E',
     'Sound param block: vibrato variant C (different rate)'),
    ('LABEL_EE7554', 'SndParam_VibratoD_7554',
     'Sound param block: vibrato variant D'),
    ('LABEL_EE758A', 'SndParam_Growl_758A',
     'Sound param block: growl effect (aggressive modulation)'),
    ('LABEL_EE75C0', 'SndParam_GrowlB_75C0',
     'Sound param block: growl variant B, followed by 4-byte zero padding'),

    # ==================================================================
    # Region 2: Tier-1 pointer tables (EE75FA-EE7755)
    # These tables index the sound param blocks above, organized by
    # sound category. Each is a list of .long pointers.
    # ==================================================================

    ('LABEL_EE75FA', 'SndIndex_StyleMainPtrs',
     'Pointer table: main style sound params (10 entries + zero padding)'),
    ('LABEL_EE7632', 'SndIndex_TremVibrPtrs',
     'Pointer table: tremolo/vibrato sound params (13 entries + zero pad)'),
    ('LABEL_EE7676', 'SndIndex_BaseFiltPtrs',
     'Pointer table: base/filter sound params (16 entries with gaps)'),
    ('LABEL_EE76D6', 'SndIndex_EnvelopePtrs',
     'Pointer table: envelope category params (5 entries + zero padding)'),
    ('LABEL_EE76F6', 'SndIndex_MultiOscPtrs',
     'Pointer table: multi-oscillator category params (5 entries + null)'),
    ('LABEL_EE770E', 'SndIndex_EnvCurvePtrs',
     'Pointer table: envelope curve params (6 entries + zero + 1 + zero)'),
    ('LABEL_EE7756', 'SndIndex_ShortFiltPtrs',
     'Pointer table: short filter params (4 entries + zero padding)'),

    # ==================================================================
    # Region 3: Extended style dispatch table (EE7776-EE7A86)
    # Large pointer table with 160+ entries dispatching to both sound
    # param blocks and empty (0xFF) style slot entries. This is the
    # main style-number-to-data lookup table.
    # ==================================================================

    ('LABEL_EE7776', 'SndIndex_StyleDispatch',
     'Main style dispatch table: 160+ entries mapping style IDs to data'),

    # ==================================================================
    # Region 4: Empty/reserved style slots (EE7A87-EE7C9F)
    # Each is a 4-byte 0xFF fill block representing an unused slot in
    # the style dispatch system. Referenced from SndIndex_StyleDispatch.
    # ==================================================================

    ('LABEL_EE7A87', 'StyleSlot_Empty_00',
     'Empty style slot 0 (0xFF padding, unused)'),
    ('LABEL_EE7A8B', 'StyleSlot_Empty_01',
     'Empty style slot 1'),
    ('LABEL_EE7A8F', 'StyleSlot_Empty_02',
     'Empty style slot 2'),
    ('LABEL_EE7A93', 'StyleSlot_Empty_03',
     'Empty style slot 3'),
    ('LABEL_EE7A97', 'StyleSlot_Empty_04',
     'Empty style slot 4'),
    ('LABEL_EE7A9B', 'StyleSlot_Empty_05',
     'Empty style slot 5'),
    ('LABEL_EE7A9F', 'StyleSlot_Empty_06',
     'Empty style slot 6'),
    ('LABEL_EE7AA3', 'StyleSlot_Empty_07',
     'Empty style slot 7'),
    ('LABEL_EE7AA7', 'StyleSlot_Empty_08',
     'Empty style slot 8'),
    ('LABEL_EE7AAB', 'StyleSlot_Empty_09',
     'Empty style slot 9'),
    ('LABEL_EE7AAF', 'StyleSlot_Empty_10',
     'Empty style slot 10'),
    ('LABEL_EE7AB3', 'StyleSlot_Empty_11',
     'Empty style slot 11'),
    ('LABEL_EE7AB7', 'StyleSlot_Empty_12',
     'Empty style slot 12'),
    ('LABEL_EE7ABB', 'StyleSlot_Empty_13',
     'Empty style slot 13'),
    ('LABEL_EE7ABF', 'StyleSlot_Empty_14',
     'Empty style slot 14'),
    ('LABEL_EE7AC3', 'StyleSlot_Empty_15',
     'Empty style slot 15'),
    ('LABEL_EE7AC7', 'StyleSlot_Empty_16',
     'Empty style slot 16'),
    ('LABEL_EE7ACB', 'StyleSlot_Empty_17',
     'Empty style slot 17'),
    ('LABEL_EE7ACF', 'StyleSlot_Empty_18',
     'Empty style slot 18'),
    ('LABEL_EE7AD3', 'StyleSlot_Empty_19',
     'Empty style slot 19'),
    ('LABEL_EE7AD7', 'StyleSlot_Empty_20',
     'Empty style slot 20'),
    ('LABEL_EE7ADB', 'StyleSlot_Empty_21',
     'Empty style slot 21'),
    ('LABEL_EE7ADF', 'StyleSlot_Empty_22',
     'Empty style slot 22'),
    ('LABEL_EE7AE3', 'StyleSlot_Empty_23',
     'Empty style slot 23'),
    ('LABEL_EE7AE7', 'StyleSlot_Empty_24',
     'Empty style slot 24'),
    ('LABEL_EE7AEB', 'StyleSlot_Empty_25',
     'Empty style slot 25'),
    ('LABEL_EE7AEF', 'StyleSlot_Empty_26',
     'Empty style slot 26'),
    ('LABEL_EE7AF3', 'StyleSlot_Empty_27',
     'Empty style slot 27'),
    ('LABEL_EE7AF7', 'StyleSlot_Empty_28',
     'Empty style slot 28'),
    ('LABEL_EE7AFB', 'StyleSlot_Empty_29',
     'Empty style slot 29'),
    ('LABEL_EE7AFF', 'StyleSlot_Empty_30',
     'Empty style slot 30'),
    ('LABEL_EE7B03', 'StyleSlot_Empty_31',
     'Empty style slot 31'),
    ('LABEL_EE7B07', 'StyleSlot_Empty_32',
     'Empty style slot 32'),
    ('LABEL_EE7B0B', 'StyleSlot_Empty_33',
     'Empty style slot 33'),
    ('LABEL_EE7B0F', 'StyleSlot_Empty_34',
     'Empty style slot 34'),
    ('LABEL_EE7B13', 'StyleSlot_Empty_35',
     'Empty style slot 35'),
    ('LABEL_EE7B17', 'StyleSlot_Empty_36',
     'Empty style slot 36'),
    ('LABEL_EE7B1B', 'StyleSlot_Empty_37',
     'Empty style slot 37'),
    ('LABEL_EE7B1F', 'StyleSlot_Empty_38',
     'Empty style slot 38'),
    ('LABEL_EE7B23', 'StyleSlot_Empty_39',
     'Empty style slot 39'),
    ('LABEL_EE7B27', 'StyleSlot_Empty_40',
     'Empty style slot 40'),
    ('LABEL_EE7B2B', 'StyleSlot_Empty_41',
     'Empty style slot 41'),
    ('LABEL_EE7B2F', 'StyleSlot_Empty_42',
     'Empty style slot 42'),
    ('LABEL_EE7B33', 'StyleSlot_Empty_43',
     'Empty style slot 43'),
    ('LABEL_EE7B37', 'StyleSlot_Empty_44',
     'Empty style slot 44'),
    ('LABEL_EE7B3B', 'StyleSlot_Empty_45',
     'Empty style slot 45'),
    ('LABEL_EE7B3F', 'StyleSlot_Empty_46',
     'Empty style slot 46'),
    ('LABEL_EE7B43', 'StyleSlot_Empty_47',
     'Empty style slot 47'),
    ('LABEL_EE7B47', 'StyleSlot_Empty_48',
     'Empty style slot 48'),
    ('LABEL_EE7B4B', 'StyleSlot_Empty_49',
     'Empty style slot 49'),
    ('LABEL_EE7B4F', 'StyleSlot_Empty_50',
     'Empty style slot 50'),
    ('LABEL_EE7B53', 'StyleSlot_Empty_51',
     'Empty style slot 51'),
    ('LABEL_EE7B57', 'StyleSlot_Empty_52',
     'Empty style slot 52'),
    ('LABEL_EE7B5B', 'StyleSlot_Empty_53',
     'Empty style slot 53'),
    ('LABEL_EE7B5F', 'StyleSlot_Empty_54',
     'Empty style slot 54'),
    ('LABEL_EE7B63', 'StyleSlot_Empty_55',
     'Empty style slot 55'),
    ('LABEL_EE7B67', 'StyleSlot_Empty_56',
     'Empty style slot 56'),
    ('LABEL_EE7B6B', 'StyleSlot_Empty_57',
     'Empty style slot 57'),
    ('LABEL_EE7B6F', 'StyleSlot_Empty_58',
     'Empty style slot 58'),
    ('LABEL_EE7B73', 'StyleSlot_Empty_59',
     'Empty style slot 59'),
    ('LABEL_EE7B77', 'StyleSlot_Empty_60',
     'Empty style slot 60'),
    ('LABEL_EE7B7B', 'StyleSlot_Empty_61',
     'Empty style slot 61'),
    ('LABEL_EE7B7F', 'StyleSlot_Empty_62',
     'Empty style slot 62'),
    ('LABEL_EE7B83', 'StyleSlot_Empty_63',
     'Empty style slot 63'),
    ('LABEL_EE7B87', 'StyleSlot_Empty_64',
     'Empty style slot 64'),
    ('LABEL_EE7B8B', 'StyleSlot_Empty_65',
     'Empty style slot 65'),
    ('LABEL_EE7B8F', 'StyleSlot_Empty_66',
     'Empty style slot 66'),
    ('LABEL_EE7B93', 'StyleSlot_Empty_67',
     'Empty style slot 67'),
    ('LABEL_EE7B97', 'StyleSlot_Empty_68',
     'Empty style slot 68'),
    ('LABEL_EE7B9B', 'StyleSlot_Empty_69',
     'Empty style slot 69'),
    ('LABEL_EE7B9F', 'StyleSlot_Empty_70',
     'Empty style slot 70'),
    ('LABEL_EE7BA3', 'StyleSlot_Empty_71',
     'Empty style slot 71'),
    ('LABEL_EE7BA7', 'StyleSlot_Ref_FB6B2D',
     'Style slot with cross-ref to LABEL_FB6B2D (populated entry)'),
    ('LABEL_EE7BAF', 'StyleSlot_Empty_73',
     'Empty style slot 73'),
    ('LABEL_EE7BB3', 'StyleSlot_Empty_74',
     'Empty style slot 74'),
    ('LABEL_EE7BB7', 'StyleSlot_Empty_75',
     'Empty style slot 75'),
    ('LABEL_EE7BBB', 'StyleSlot_Empty_76',
     'Empty style slot 76'),
    ('LABEL_EE7BBF', 'StyleSlot_Empty_77',
     'Empty style slot 77'),
    ('LABEL_EE7BC3', 'StyleSlot_Empty_78',
     'Empty style slot 78'),
    ('LABEL_EE7BC7', 'StyleSlot_Empty_79',
     'Empty style slot 79'),
    ('LABEL_EE7BCB', 'StyleSlot_Empty_80',
     'Empty style slot 80'),
    ('LABEL_EE7BCF', 'StyleSlot_Empty_81',
     'Empty style slot 81'),
    ('LABEL_EE7BD3', 'StyleSlot_Empty_82',
     'Empty style slot 82'),
    ('LABEL_EE7BD7', 'StyleSlot_Empty_83',
     'Empty style slot 83'),
    ('LABEL_EE7BDB', 'StyleSlot_Empty_84',
     'Empty style slot 84'),
    ('LABEL_EE7BDF', 'StyleSlot_Empty_85',
     'Empty style slot 85'),
    ('LABEL_EE7BE3', 'StyleSlot_Empty_86',
     'Empty style slot 86'),
    ('LABEL_EE7BE7', 'StyleSlot_Empty_87',
     'Empty style slot 87'),
    ('LABEL_EE7BEB', 'StyleSlot_Empty_88',
     'Empty style slot 88'),
    ('LABEL_EE7BEF', 'StyleSlot_Empty_89',
     'Empty style slot 89'),
    ('LABEL_EE7BF3', 'StyleSlot_Empty_90',
     'Empty style slot 90'),
    ('LABEL_EE7BF7', 'StyleSlot_Empty_91',
     'Empty style slot 91'),
    ('LABEL_EE7BFB', 'StyleSlot_Empty_92',
     'Empty style slot 92'),
    ('LABEL_EE7BFF', 'StyleSlot_Empty_93',
     'Empty style slot 93'),
    ('LABEL_EE7C03', 'StyleSlot_Empty_94',
     'Empty style slot 94'),
    ('LABEL_EE7C07', 'StyleSlot_Empty_95',
     'Empty style slot 95'),
    ('LABEL_EE7C0B', 'StyleSlot_Empty_96',
     'Empty style slot 96'),
    ('LABEL_EE7C0F', 'StyleSlot_Empty_97',
     'Empty style slot 97'),
    ('LABEL_EE7C13', 'StyleSlot_Empty_98',
     'Empty style slot 98'),
    ('LABEL_EE7C17', 'StyleSlot_Empty_99',
     'Empty style slot 99'),
    ('LABEL_EE7C1B', 'StyleSlot_Empty_100',
     'Empty style slot 100'),
    ('LABEL_EE7C1F', 'StyleSlot_Empty_101',
     'Empty style slot 101'),
    ('LABEL_EE7C23', 'StyleSlot_Ref_FD86AC',
     'Style slot with cross-ref to LABEL_FD86AC (populated entry)'),
    ('LABEL_EE7C2B', 'StyleSlot_Empty_103',
     'Empty style slot 103'),
    ('LABEL_EE7C2F', 'StyleSlot_Empty_104',
     'Empty style slot 104'),
    ('LABEL_EE7C33', 'StyleSlot_BitMap_PresetCopy',
     'Style slot with BitMapOut_ByteData_PresetCopy + FB6BD9 + VoiceProbeB'),
    ('LABEL_EE7C43', 'StyleSlot_Empty_106',
     'Empty style slot 106'),
    ('LABEL_EE7C47', 'StyleSlot_Empty_107',
     'Empty style slot 107'),
    ('LABEL_EE7C4B', 'StyleSlot_Ref_FB6A63',
     'Style slot with cross-ref to LABEL_FB6A63 (populated entry)'),
    ('LABEL_EE7C53', 'StyleSlot_Empty_109',
     'Empty style slot 109'),
    ('LABEL_EE7C57', 'StyleSlot_Empty_110',
     'Empty style slot 110'),
    ('LABEL_EE7C5B', 'StyleSlot_Empty_111',
     'Empty style slot 111'),
    ('LABEL_EE7C5F', 'StyleSlot_Empty_112',
     'Empty style slot 112'),
    ('LABEL_EE7C63', 'StyleSlot_Empty_113',
     'Empty style slot 113'),
    ('LABEL_EE7C67', 'StyleSlot_Empty_114',
     'Empty style slot 114'),
    ('LABEL_EE7C6B', 'StyleSlot_Empty_115',
     'Empty style slot 115'),
    ('LABEL_EE7C6F', 'StyleSlot_Empty_116',
     'Empty style slot 116'),
    ('LABEL_EE7C73', 'StyleSlot_Empty_117',
     'Empty style slot 117'),
    ('LABEL_EE7C77', 'StyleSlot_Empty_118',
     'Empty style slot 118'),
    ('LABEL_EE7C7B', 'StyleSlot_Empty_119',
     'Empty style slot 119'),
    ('LABEL_EE7C7F', 'StyleSlot_Empty_120',
     'Empty style slot 120'),
    ('LABEL_EE7C83', 'StyleSlot_Empty_121',
     'Empty style slot 121'),
    ('LABEL_EE7C87', 'StyleSlot_Empty_122',
     'Empty style slot 122'),
    ('LABEL_EE7C8B', 'StyleSlot_Empty_123',
     'Empty style slot 123'),
    ('LABEL_EE7C8F', 'StyleSlot_Empty_124',
     'Empty style slot 124'),
    ('LABEL_EE7C93', 'StyleSlot_Empty_125',
     'Empty style slot 125'),
    ('LABEL_EE7C97', 'StyleSlot_Empty_126',
     'Empty style slot 126'),
    ('LABEL_EE7C9B', 'StyleSlot_Empty_127',
     'Empty style slot 127'),
    ('LABEL_EE7C9F', 'StyleSlot_Default',
     'Default/fallback style slot (0xFF fill, terminates table)'),

    # ==================================================================
    # Region 5: Tier-2 voice config pointer table (EE7CA7-EE7D26)
    # Points to the voice configuration lists below (EE7FA8-EE8364).
    # 32 entries mapping style categories to voice config lists.
    # ==================================================================

    ('LABEL_EE7CA7', 'VoiceCfg_IndexTable',
     'Tier-2 pointer table: 32 style categories -> voice config lists'),

    # ==================================================================
    # Region 6: Tier-2 extended dispatch table (EE7D27-EE86CF)
    # Similar to StyleDispatch but for voice configurations.
    # Mixes populated entries with references to VoiceCfgSlot_Default.
    # ==================================================================

    ('LABEL_EE7D27', 'VoiceCfg_DispatchTable',
     'Extended dispatch table: voice config slot pointers (160+ entries)'),

    # ==================================================================
    # Region 7: Voice configuration lists (EE7FA8-EE837F)
    # Each label defines a list of .long function/data pointers
    # terminated by 0xFFFFFFFF. These configure which voice processing
    # functions are active for a given style category.
    # EE7FA8 has 11 entries (the fullest), subsequent ones have fewer.
    # ==================================================================

    ('LABEL_EE7FA8', 'VoiceCfgList_Full_00',
     'Voice config list 0: full set (FEA812+FC7B07+FDE084+FD0452+FC9554+NameEditor+Render+F98697+VoiceProbeA+FB7E14)'),
    ('LABEL_EE7FD4', 'VoiceCfgList_Full_01',
     'Voice config list 1: like list 0 minus FB7E14'),
    ('LABEL_EE7FFC', 'VoiceCfgList_NoName_02',
     'Voice config list 2: no NameEditor entry'),
    ('LABEL_EE8020', 'VoiceCfgList_Basic_03',
     'Voice config list 3: basic set (FEA812+FC7B07+FDE084+FD0452+FC9554+Render+F98697)'),
    ('LABEL_EE8040', 'VoiceCfgList_Basic_04',
     'Voice config list 4: same as basic set 3'),
    ('LABEL_EE8060', 'VoiceCfgList_Basic_05',
     'Voice config list 5: same as basic set 3'),
    ('LABEL_EE8080', 'VoiceCfgList_Basic_06',
     'Voice config list 6: same as basic set 3'),
    ('LABEL_EE80A0', 'VoiceCfgList_Basic_07',
     'Voice config list 7: same as basic set 3'),
    ('LABEL_EE80C0', 'VoiceCfgList_Basic_08',
     'Voice config list 8: same as basic set 3'),
    ('LABEL_EE80E0', 'VoiceCfgList_Basic_09',
     'Voice config list 9: same as basic set 3'),
    ('LABEL_EE8100', 'VoiceCfgList_Basic_10',
     'Voice config list 10: same as basic set 3'),
    ('LABEL_EE8120', 'VoiceCfgList_Basic_11',
     'Voice config list 11: same as basic set 3'),
    ('LABEL_EE8140', 'VoiceCfgList_Basic_12',
     'Voice config list 12: same as basic set 3'),
    ('LABEL_EE8160', 'VoiceCfgList_Basic_13',
     'Voice config list 13: same as basic set 3'),
    ('LABEL_EE8180', 'VoiceCfgList_Basic_14',
     'Voice config list 14: same as basic set 3'),
    ('LABEL_EE81A0', 'VoiceCfgList_Basic_15',
     'Voice config list 15: same as basic set 3'),
    ('LABEL_EE81C0', 'VoiceCfgList_Short_16',
     'Voice config list 16: short (no FC9554)'),
    ('LABEL_EE81DC', 'VoiceCfgList_Short_17',
     'Voice config list 17: short (no FC9554)'),
    ('LABEL_EE81F8', 'VoiceCfgList_Short_18',
     'Voice config list 18: short (no FC9554)'),
    ('LABEL_EE8214', 'VoiceCfgList_Short_19',
     'Voice config list 19: short (no FC9554)'),
    ('LABEL_EE8230', 'VoiceCfgList_Short_20',
     'Voice config list 20: short (no FC9554)'),
    ('LABEL_EE824C', 'VoiceCfgList_Short_21',
     'Voice config list 21: short (no FC9554)'),
    ('LABEL_EE8268', 'VoiceCfgList_Short_22',
     'Voice config list 22: short (no FC9554)'),
    ('LABEL_EE8284', 'VoiceCfgList_Short_23',
     'Voice config list 23: short (no FC9554)'),
    ('LABEL_EE82A0', 'VoiceCfgList_Short_24',
     'Voice config list 24: short (no FC9554)'),
    ('LABEL_EE82BC', 'VoiceCfgList_Short_25',
     'Voice config list 25: short (no FC9554)'),
    ('LABEL_EE82D8', 'VoiceCfgList_Short_26',
     'Voice config list 26: short (no FC9554)'),
    ('LABEL_EE82F4', 'VoiceCfgList_Short_27',
     'Voice config list 27: short (no FC9554)'),
    ('LABEL_EE8310', 'VoiceCfgList_Short_28',
     'Voice config list 28: short (no FC9554)'),
    ('LABEL_EE832C', 'VoiceCfgList_Short_29',
     'Voice config list 29: short (no FC9554)'),
    ('LABEL_EE8348', 'VoiceCfgList_Short_30',
     'Voice config list 30: short (no FC9554)'),
    ('LABEL_EE8364', 'VoiceCfgList_Short_31',
     'Voice config list 31: short (no FC9554)'),

    # ==================================================================
    # Region 8: Empty voice config entries (EE8380-EE83FC)
    # Single 0xFFFFFFFF entries = empty/null voice config (no functions).
    # Referenced from VoiceCfg_DispatchTable.
    # ==================================================================

    ('LABEL_EE8380', 'VoiceCfgSlot_Null_00',
     'Empty voice config entry (0xFFFFFFFF)'),
    ('LABEL_EE8384', 'VoiceCfgSlot_Null_01',
     'Empty voice config entry'),
    ('LABEL_EE8388', 'VoiceCfgSlot_Null_02',
     'Empty voice config entry'),
    ('LABEL_EE838C', 'VoiceCfgSlot_Null_03',
     'Empty voice config entry'),
    ('LABEL_EE8390', 'VoiceCfgSlot_Null_04',
     'Empty voice config entry'),
    ('LABEL_EE8394', 'VoiceCfgSlot_Null_05',
     'Empty voice config entry'),
    ('LABEL_EE8398', 'VoiceCfgSlot_Null_06',
     'Empty voice config entry'),
    ('LABEL_EE839C', 'VoiceCfgSlot_Null_07',
     'Empty voice config entry'),
    ('LABEL_EE83A0', 'VoiceCfgSlot_Null_08',
     'Empty voice config entry'),
    ('LABEL_EE83A4', 'VoiceCfgSlot_Null_09',
     'Empty voice config entry'),
    ('LABEL_EE83A8', 'VoiceCfgSlot_Null_10',
     'Empty voice config entry'),
    ('LABEL_EE83AC', 'VoiceCfgSlot_Null_11',
     'Empty voice config entry'),
    ('LABEL_EE83B0', 'VoiceCfgSlot_Null_12',
     'Empty voice config entry'),
    ('LABEL_EE83B4', 'VoiceCfgSlot_Null_13',
     'Empty voice config entry'),
    ('LABEL_EE83B8', 'VoiceCfgSlot_Null_14',
     'Empty voice config entry'),
    ('LABEL_EE83BC', 'VoiceCfgSlot_Null_15',
     'Empty voice config entry'),
    ('LABEL_EE83C0', 'VoiceCfgSlot_Null_16',
     'Empty voice config entry'),
    ('LABEL_EE83C4', 'VoiceCfgSlot_Null_17',
     'Empty voice config entry'),
    ('LABEL_EE83C8', 'VoiceCfgSlot_Null_18',
     'Empty voice config entry'),
    ('LABEL_EE83CC', 'VoiceCfgSlot_Null_19',
     'Empty voice config entry'),
    ('LABEL_EE83D0', 'VoiceCfgSlot_Null_20',
     'Empty voice config entry'),
    ('LABEL_EE83D4', 'VoiceCfgSlot_Null_21',
     'Empty voice config entry'),
    ('LABEL_EE83D8', 'VoiceCfgSlot_Null_22',
     'Empty voice config entry'),
    ('LABEL_EE83DC', 'VoiceCfgSlot_Null_23',
     'Empty voice config entry'),
    ('LABEL_EE83E0', 'VoiceCfgSlot_Null_24',
     'Empty voice config entry'),
    ('LABEL_EE83E4', 'VoiceCfgSlot_Null_25',
     'Empty voice config entry'),
    ('LABEL_EE83E8', 'VoiceCfgSlot_Null_26',
     'Empty voice config entry'),
    ('LABEL_EE83EC', 'VoiceCfgSlot_Null_27',
     'Empty voice config entry'),
    ('LABEL_EE83F0', 'VoiceCfgSlot_Null_28',
     'Empty voice config entry'),
    ('LABEL_EE83F4', 'VoiceCfgSlot_Null_29',
     'Empty voice config entry'),
    ('LABEL_EE83F8', 'VoiceCfgSlot_Null_30',
     'Empty voice config entry'),
    ('LABEL_EE83FC', 'VoiceCfgSlot_Null_31',
     'Empty voice config entry'),

    # ==================================================================
    # Region 9: Populated voice config entries (EE8400-EE86AC)
    # Mix of populated entries (with real function pointers) and
    # empty entries (0xFF fill). These are specialized style configs
    # for specific instrument categories.
    # ==================================================================

    ('LABEL_EE8400', 'VoiceCfgSlot_FC7B07',
     'Voice config: FC7B07 only (minimal)'),
    ('LABEL_EE8408', 'VoiceCfgSlot_Null_33',
     'Empty voice config entry'),
    ('LABEL_EE840C', 'VoiceCfgSlot_Null_34',
     'Empty voice config entry'),
    ('LABEL_EE8410', 'VoiceCfgSlot_F98_FEB',
     'Voice config: F98697 + FEB010'),
    ('LABEL_EE841C', 'VoiceCfgSlot_F98_VoiceC',
     'Voice config: F98697 + VoiceProbeC'),
    ('LABEL_EE8428', 'VoiceCfgSlot_F98_VoiceC_B',
     'Voice config: F98697 + VoiceProbeC (variant B)'),
    ('LABEL_EE8434', 'VoiceCfgSlot_F98_VoiceC_C',
     'Voice config: F98697 + VoiceProbeC (variant C)'),
    ('LABEL_EE8440', 'VoiceCfgSlot_F98_Only',
     'Voice config: F98697 only'),
    ('LABEL_EE8448', 'VoiceCfgSlot_Replay_DSP',
     'Voice config: FC7B61+ReplayStop+FDE2A8+F3C8BA+F98697+RenderE+DSPCfg'),
    ('LABEL_EE8468', 'VoiceCfgSlot_Empty_40',
     'Empty voice config slot 40'),
    ('LABEL_EE846C', 'VoiceCfgSlot_Empty_41',
     'Empty voice config slot 41'),
    ('LABEL_EE8470', 'VoiceCfgSlot_Empty_42',
     'Empty voice config slot 42'),
    ('LABEL_EE8474', 'VoiceCfgSlot_Empty_43',
     'Empty voice config slot 43'),
    ('LABEL_EE8478', 'VoiceCfgSlot_Empty_44',
     'Empty voice config slot 44'),
    ('LABEL_EE847C', 'VoiceCfgSlot_Empty_45',
     'Empty voice config slot 45'),
    ('LABEL_EE8480', 'VoiceCfgSlot_FEAA18',
     'Voice config: FEAA18 + FC7C14 + F98697'),
    ('LABEL_EE8490', 'VoiceCfgSlot_FEAA80',
     'Voice config: FEAA80 + F98697 + F454F1'),
    ('LABEL_EE84A0', 'VoiceCfgSlot_FEAAC4',
     'Voice config: FEAAC4 + F98697'),
    ('LABEL_EE84AC', 'VoiceCfgSlot_FEAAC5',
     'Voice config: raw ref C5AAFE00 + F98697 + F454F1'),
    ('LABEL_EE84BC', 'VoiceCfgSlot_F454_AB09',
     'Voice config: F454F1 + FEAB09'),
    ('LABEL_EE84C8', 'VoiceCfgSlot_F454_AB4D',
     'Voice config: F454F1 + FEAB4D'),
    ('LABEL_EE84D4', 'VoiceCfgSlot_F454_AB91',
     'Voice config: F454F1 + FEAB91'),
    ('LABEL_EE84E0', 'VoiceCfgSlot_FEABD5',
     'Voice config: FEABD5 + F98697'),
    ('LABEL_EE84EC', 'VoiceCfgSlot_FEABD6',
     'Voice config: raw ref D6ABFE00 + F98697'),
    ('LABEL_EE84F8', 'VoiceCfgSlot_FEABD7',
     'Voice config: FEABD7 + F98697'),
    ('LABEL_EE8504', 'VoiceCfgSlot_FEABD8',
     'Voice config: raw ref D8ABFE00 + F98697'),
    ('LABEL_EE8510', 'VoiceCfgSlot_Empty_56',
     'Empty voice config slot 56'),
    ('LABEL_EE8514', 'VoiceCfgSlot_Empty_57',
     'Empty voice config slot 57'),
    ('LABEL_EE8518', 'VoiceCfgSlot_Empty_58',
     'Empty voice config slot 58 (raw 0xFF)'),
    ('LABEL_EE851C', 'VoiceCfgSlot_FC7BED',
     'Voice config: raw ref ED7BFC00 (FC7BED) -> FEAD62 chain'),
    ('LABEL_EE8520', 'VoiceCfgSlot_FEAD62_Chain',
     'Voice config continuation: FEAD62 + FDE67D + F98697 + DSPCfg'),
    ('LABEL_EE8534', 'VoiceCfgSlot_FDE9AD',
     'Voice config: raw ref ADE9FD00 + F98697'),
    ('LABEL_EE8540', 'VoiceCfgSlot_FEABD9',
     'Voice config: FEABD9 + F98697'),
    ('LABEL_EE854C', 'VoiceCfgSlot_Empty_62',
     'Empty voice config slot 62'),
    ('LABEL_EE8550', 'VoiceCfgSlot_Empty_63',
     'Empty voice config slot 63'),
    ('LABEL_EE8554', 'VoiceCfgSlot_Empty_64',
     'Empty voice config slot 64'),
    ('LABEL_EE8558', 'VoiceCfgSlot_FEAC82',
     'Voice config: FEAC82 + FDE7EB + FC9A40 + F98697'),
    ('LABEL_EE856C', 'VoiceCfgSlot_Empty_66',
     'Empty voice config slot 66'),
    ('LABEL_EE8570', 'VoiceCfgSlot_AccStyle',
     'Voice config: FC7B2C + FDE514 + AccStyle_JumpTable2 + F98697 + F98748 + RenderD'),
    ('LABEL_EE858C', 'VoiceCfgSlot_FD8BCC',
     'Voice config: FD8BCC entry (leads to FEAC83 chain)'),
    ('LABEL_EE8590', 'VoiceCfgSlot_FEAC83_Chain',
     'Voice config continuation: FEAC83 + FDE981 + FC7BBA + F202EC + F98697'),
    ('LABEL_EE85A8', 'VoiceCfgSlot_FEAD01',
     'Voice config: FEAD01 + F98697'),
    ('LABEL_EE85B4', 'VoiceCfgSlot_FDE982',
     'Voice config: raw ref 82E9FD00 + FEE410 + F98697 + Encoder_ApplySystemModeSettings'),
    ('LABEL_EE85C8', 'VoiceCfgSlot_Accomp',
     'Voice config: FC7BEE + FDE7B5 + ReplayStopAlt + FEADC7 + DisplayUpdate + FDBA3A + F98697 + TransitionSeq + DSPCfg'),
    ('LABEL_EE85F0', 'VoiceCfgSlot_F98_FC95',
     'Voice config: F98697 + FC9507'),
    ('LABEL_EE85FC', 'VoiceCfgSlot_FEAE38',
     'Voice config: raw ref 38AEFE00 + F98697'),
    ('LABEL_EE8608', 'VoiceCfgSlot_AccompSeq',
     'Voice config: FC7BBB + AccompSeq_JumpTable + AccStyle_JumpTable + raw ref'),
    ('LABEL_EE8618', 'VoiceCfgSlot_Demo',
     'Voice config continuation: Demo_SelectEntry + FDE983 + F8B4CC + RenderState + F98697 + F69CC2 + F7AD49 + F6D84D + F47667'),
    ('LABEL_EE8640', 'VoiceCfgSlot_Empty_75',
     'Empty voice config slot 75'),
    ('LABEL_EE8644', 'VoiceCfgSlot_Empty_76',
     'Empty voice config slot 76'),
    ('LABEL_EE8648', 'VoiceCfgSlot_Empty_77',
     'Empty voice config slot 77'),
    ('LABEL_EE864C', 'VoiceCfgSlot_Empty_78',
     'Empty voice config slot 78'),
    ('LABEL_EE8650', 'VoiceCfgSlot_FEAE9E',
     'Voice config: FEAE9E'),
    ('LABEL_EE8658', 'VoiceCfgSlot_FEAECA',
     'Voice config: FEAECA'),
    ('LABEL_EE8660', 'VoiceCfgSlot_FEAF26',
     'Voice config: FEAF26'),
    ('LABEL_EE8668', 'VoiceCfgSlot_FEAF52',
     'Voice config: FEAF52'),
    ('LABEL_EE8670', 'VoiceCfgSlot_FEAF7E',
     'Voice config: FEAF7E'),
    ('LABEL_EE8678', 'VoiceCfgSlot_FEAFB6',
     'Voice config: FEAFB6'),
    ('LABEL_EE8680', 'VoiceCfgSlot_FEAFE2',
     'Voice config: FEAFE2'),
    ('LABEL_EE8688', 'VoiceCfgSlot_FEB00E',
     'Voice config: FEB00E'),
    ('LABEL_EE8690', 'VoiceCfgSlot_FEB00F',
     'Voice config: FEB00F'),
    ('LABEL_EE8698', 'VoiceCfgSlot_Empty_88',
     'Empty voice config slot 88'),
    ('LABEL_EE869C', 'VoiceCfgSlot_Empty_89',
     'Empty voice config slot 89'),
    ('LABEL_EE86A0', 'VoiceCfgSlot_Empty_90',
     'Empty voice config slot 90'),
    ('LABEL_EE86A4', 'VoiceCfgSlot_Empty_91',
     'Empty voice config slot 91'),
    ('LABEL_EE86A8', 'VoiceCfgSlot_Empty_92',
     'Empty voice config slot 92'),
    ('LABEL_EE86AC', 'VoiceCfgSlot_Empty_93',
     'Empty voice config slot 93'),

    # ==================================================================
    # Region 10: Default/fallback voice config (EE86B0-EE86CF)
    # Contains the default voice config with FEB932+FDDDED+EF75FD+
    # FD0467+RenderC+ProcessVoiceFlags chain. Heavily referenced as
    # the fallback entry from VoiceCfg_DispatchTable.
    # ==================================================================

    ('LABEL_EE86B0', 'VoiceCfgSlot_Default',
     'Default/fallback voice config: FEB932+FDDDED+EF75FD+FD0467+RenderC+ProcessVoiceFlags'),

    # ==================================================================
    # Region 11: Tier-3 tone data pointer table (EE86D0-EE89D0)
    # Points to tone reference entries below. Same structure as Tier-2
    # but for the tone data layer.
    # ==================================================================

    ('LABEL_EE86D0', 'ToneIndex_DispatchTable',
     'Tier-3 dispatch table: tone data slot pointers (160+ entries)'),

    # ==================================================================
    # Region 12: Tone reference data entries (EE89D1-EE8AC9)
    # Each 8-byte entry starts with a pointer (FB40xx range) followed
    # by 0xFFFFFFFF. These reference tone data in the FB block.
    # ==================================================================

    ('LABEL_EE89D1', 'ToneRef_FB4016_00',
     'Tone reference entry 0: FB4016 + 0xFFFFFFFF'),
    ('LABEL_EE89D9', 'ToneRef_FB4016_01',
     'Tone reference entry 1: FB4016'),
    ('LABEL_EE89E1', 'ToneRef_FB4016_02',
     'Tone reference entry 2: FB4016'),
    ('LABEL_EE89E9', 'ToneRef_FB4016_03',
     'Tone reference entry 3: FB4016'),
    ('LABEL_EE89F1', 'ToneRef_FB4016_04',
     'Tone reference entry 4: FB4016'),
    ('LABEL_EE89F9', 'ToneRef_FB4016_05',
     'Tone reference entry 5: FB4016'),
    ('LABEL_EE8A01', 'ToneRef_FB4016_06',
     'Tone reference entry 6: FB4016'),
    ('LABEL_EE8A09', 'ToneRef_FB4016_07',
     'Tone reference entry 7: FB4016'),
    ('LABEL_EE8A11', 'ToneRef_FB4016_08',
     'Tone reference entry 8: FB4016'),
    ('LABEL_EE8A19', 'ToneRef_FB4016_09',
     'Tone reference entry 9: FB4016'),
    ('LABEL_EE8A21', 'ToneRef_FB4016_10',
     'Tone reference entry 10: FB4016'),
    ('LABEL_EE8A29', 'ToneRef_FB4016_11',
     'Tone reference entry 11: FB4016'),
    ('LABEL_EE8A31', 'ToneRef_FB4016_12',
     'Tone reference entry 12: FB4016'),
    ('LABEL_EE8A39', 'ToneRef_FB4016_13',
     'Tone reference entry 13: FB4016'),
    ('LABEL_EE8A41', 'ToneRef_FB4016_14',
     'Tone reference entry 14: FB4016'),
    ('LABEL_EE8A49', 'ToneRef_FB4016_15',
     'Tone reference entry 15: FB4016'),
    ('LABEL_EE8A51', 'ToneRef_FB4016_16',
     'Tone reference entry 16: FB4016'),
    ('LABEL_EE8A59', 'ToneRef_FB4016_17',
     'Tone reference entry 17: FB4016'),
    ('LABEL_EE8A61', 'ToneRef_FB4016_18',
     'Tone reference entry 18: FB4016'),
    ('LABEL_EE8A69', 'ToneRef_FB4016_19',
     'Tone reference entry 19: FB4016'),
    ('LABEL_EE8A71', 'ToneRef_FB4016_20',
     'Tone reference entry 20: FB4016'),
    ('LABEL_EE8A79', 'ToneRef_FB4016_21',
     'Tone reference entry 21: FB4016'),
    ('LABEL_EE8A81', 'ToneRef_FB4016_22',
     'Tone reference entry 22: FB4016'),
    ('LABEL_EE8A89', 'ToneRef_FB4016_23',
     'Tone reference entry 23: FB4016'),
    ('LABEL_EE8A91', 'ToneRef_FB4016_24',
     'Tone reference entry 24: FB4016'),
    ('LABEL_EE8A99', 'ToneRef_FB4016_25',
     'Tone reference entry 25: FB4016'),
    ('LABEL_EE8AA1', 'ToneRef_FB4016_26',
     'Tone reference entry 26: FB4016'),
    ('LABEL_EE8AA9', 'ToneRef_FB4016_27',
     'Tone reference entry 27: FB4016'),
    ('LABEL_EE8AB1', 'ToneRef_FB4016_28',
     'Tone reference entry 28: FB4016'),
    ('LABEL_EE8AB9', 'ToneRef_FB4016_29',
     'Tone reference entry 29: FB4016'),
    ('LABEL_EE8AC1', 'ToneRef_FB4016_30',
     'Tone reference entry 30: FB4016'),
    ('LABEL_EE8AC9', 'ToneRef_FB4016_31',
     'Tone reference entry 31: FB4016'),

    # ==================================================================
    # Region 13: Empty/reserved tone slots (EE8AD1-EE8C74)
    # 4-byte 0xFF fill blocks representing unused tone slots.
    # Referenced from ToneIndex_DispatchTable.
    # ==================================================================

    ('LABEL_EE8AD1', 'ToneSlot_Empty_00',
     'Empty tone slot 0 (0xFF padding)'),
    ('LABEL_EE8AD5', 'ToneSlot_Empty_01',
     'Empty tone slot 1'),
    ('LABEL_EE8AD9', 'ToneSlot_Empty_02',
     'Empty tone slot 2'),
    ('LABEL_EE8ADD', 'ToneSlot_Empty_03',
     'Empty tone slot 3'),
    ('LABEL_EE8AE1', 'ToneSlot_Empty_04',
     'Empty tone slot 4'),
    ('LABEL_EE8AE5', 'ToneSlot_Empty_05',
     'Empty tone slot 5'),
    ('LABEL_EE8AE9', 'ToneSlot_Empty_06',
     'Empty tone slot 6'),
    ('LABEL_EE8AED', 'ToneSlot_Empty_07',
     'Empty tone slot 7'),
    ('LABEL_EE8AF1', 'ToneSlot_Empty_08',
     'Empty tone slot 8'),
    ('LABEL_EE8AF5', 'ToneSlot_Empty_09',
     'Empty tone slot 9'),
    ('LABEL_EE8AF9', 'ToneSlot_Empty_10',
     'Empty tone slot 10'),
    ('LABEL_EE8AFD', 'ToneSlot_Empty_11',
     'Empty tone slot 11'),
    ('LABEL_EE8B01', 'ToneSlot_Empty_12',
     'Empty tone slot 12'),
    ('LABEL_EE8B05', 'ToneSlot_Empty_13',
     'Empty tone slot 13'),
    ('LABEL_EE8B09', 'ToneSlot_Empty_14',
     'Empty tone slot 14'),
    ('LABEL_EE8B0D', 'ToneSlot_Empty_15',
     'Empty tone slot 15'),
    ('LABEL_EE8B11', 'ToneSlot_Empty_16',
     'Empty tone slot 16'),
    ('LABEL_EE8B15', 'ToneSlot_Empty_17',
     'Empty tone slot 17'),
    ('LABEL_EE8B19', 'ToneSlot_Empty_18',
     'Empty tone slot 18'),
    ('LABEL_EE8B1D', 'ToneSlot_Empty_19',
     'Empty tone slot 19'),
    ('LABEL_EE8B21', 'ToneSlot_Empty_20',
     'Empty tone slot 20'),
    ('LABEL_EE8B25', 'ToneSlot_Empty_21',
     'Empty tone slot 21'),
    ('LABEL_EE8B29', 'ToneSlot_Empty_22',
     'Empty tone slot 22'),
    ('LABEL_EE8B2D', 'ToneSlot_Empty_23',
     'Empty tone slot 23'),
    ('LABEL_EE8B31', 'ToneSlot_Empty_24',
     'Empty tone slot 24'),
    ('LABEL_EE8B35', 'ToneSlot_Empty_25',
     'Empty tone slot 25'),
    ('LABEL_EE8B39', 'ToneSlot_Empty_26',
     'Empty tone slot 26'),
    ('LABEL_EE8B3D', 'ToneSlot_Empty_27',
     'Empty tone slot 27'),
    ('LABEL_EE8B41', 'ToneSlot_Empty_28',
     'Empty tone slot 28'),
    ('LABEL_EE8B45', 'ToneSlot_Empty_29',
     'Empty tone slot 29'),
    ('LABEL_EE8B49', 'ToneSlot_Empty_30',
     'Empty tone slot 30'),
    ('LABEL_EE8B4D', 'ToneSlot_Empty_31',
     'Empty tone slot 31'),
    ('LABEL_EE8B51', 'ToneSlot_Empty_32',
     'Empty tone slot 32'),
    ('LABEL_EE8B55', 'ToneSlot_Empty_33',
     'Empty tone slot 33'),
    ('LABEL_EE8B59', 'ToneSlot_Empty_34',
     'Empty tone slot 34'),
    ('LABEL_EE8B5D', 'ToneSlot_Empty_35',
     'Empty tone slot 35'),
    ('LABEL_EE8B61', 'ToneSlot_Empty_36',
     'Empty tone slot 36'),
    ('LABEL_EE8B65', 'ToneSlot_Empty_37',
     'Empty tone slot 37'),
    ('LABEL_EE8B69', 'ToneSlot_Empty_38',
     'Empty tone slot 38'),
    ('LABEL_EE8B6D', 'ToneSlot_Empty_39',
     'Empty tone slot 39'),
    ('LABEL_EE8B71', 'ToneRef_FB41ED',
     'Tone reference entry: FB41ED + 0xFFFFFFFF'),
    ('LABEL_EE8B79', 'ToneSlot_Empty_41',
     'Empty tone slot 41'),
    ('LABEL_EE8B7D', 'ToneSlot_Empty_42',
     'Empty tone slot 42'),
    ('LABEL_EE8B81', 'ToneSlot_Empty_43',
     'Empty tone slot 43'),
    ('LABEL_EE8B85', 'ToneSlot_Empty_44',
     'Empty tone slot 44'),
    ('LABEL_EE8B89', 'ToneSlot_Empty_45',
     'Empty tone slot 45'),
    ('LABEL_EE8B8D', 'ToneSlot_Empty_46',
     'Empty tone slot 46'),
    ('LABEL_EE8B91', 'ToneSlot_Empty_47',
     'Empty tone slot 47'),
    ('LABEL_EE8B95', 'ToneSlot_Empty_48',
     'Empty tone slot 48'),
    ('LABEL_EE8B99', 'ToneSlot_Empty_49',
     'Empty tone slot 49'),
    ('LABEL_EE8B9D', 'ToneSlot_Empty_50',
     'Empty tone slot 50'),
    ('LABEL_EE8BA1', 'ToneSlot_Empty_51',
     'Empty tone slot 51'),
    ('LABEL_EE8BA5', 'ToneSlot_Empty_52',
     'Empty tone slot 52'),
    ('LABEL_EE8BA9', 'ToneSlot_Empty_53',
     'Empty tone slot 53'),
    ('LABEL_EE8BAD', 'ToneSlot_Empty_54',
     'Empty tone slot 54'),
    ('LABEL_EE8BB1', 'ToneSlot_Empty_55',
     'Empty tone slot 55'),
    ('LABEL_EE8BB5', 'ToneSlot_Empty_56',
     'Empty tone slot 56'),
    ('LABEL_EE8BB9', 'ToneSlot_Empty_57',
     'Empty tone slot 57'),
    ('LABEL_EE8BBD', 'ToneSlot_Empty_58',
     'Empty tone slot 58'),
    ('LABEL_EE8BC1', 'ToneSlot_Empty_59',
     'Empty tone slot 59'),
    ('LABEL_EE8BC5', 'ToneSlot_Empty_60',
     'Empty tone slot 60'),
    ('LABEL_EE8BC9', 'ToneSlot_Empty_61',
     'Empty tone slot 61'),
    ('LABEL_EE8BCD', 'ToneSlot_Empty_62',
     'Empty tone slot 62'),
    ('LABEL_EE8BD1', 'ToneSlot_Empty_63',
     'Empty tone slot 63'),
    ('LABEL_EE8BD5', 'ToneSlot_Empty_64',
     'Empty tone slot 64'),
    ('LABEL_EE8BD9', 'ToneSlot_Empty_65',
     'Empty tone slot 65'),
    ('LABEL_EE8BDD', 'ToneSlot_Empty_66',
     'Empty tone slot 66'),
    ('LABEL_EE8BE1', 'ToneSlot_Empty_67',
     'Empty tone slot 67'),
    ('LABEL_EE8BE5', 'ToneSlot_Empty_68',
     'Empty tone slot 68'),
    ('LABEL_EE8BE9', 'ToneSlot_Empty_69',
     'Empty tone slot 69'),
    ('LABEL_EE8BED', 'ToneSlot_Empty_70',
     'Empty tone slot 70'),
    ('LABEL_EE8BF1', 'ToneSlot_Empty_71',
     'Empty tone slot 71'),
    ('LABEL_EE8BF5', 'ToneSlot_Empty_72',
     'Empty tone slot 72'),
    ('LABEL_EE8BF9', 'ToneSlot_Empty_73',
     'Empty tone slot 73'),
    ('LABEL_EE8BFD', 'ToneSlot_Empty_74',
     'Empty tone slot 74'),
    ('LABEL_EE8C01', 'ToneSlot_Empty_75',
     'Empty tone slot 75 (raw 0xFF)'),
    ('LABEL_EE8C05', 'ToneRef_F5BF44_Chain',
     'Tone ref: F5BF44 + FB622B + F98101 chain'),
    ('LABEL_EE8C15', 'ToneRef_F86A7A_Chain',
     'Tone ref: F86A7A + F6E636 + F98101 + EFE092 chain'),
    ('LABEL_EE8C29', 'ToneRef_F98101_Only',
     'Tone ref: F98101 only'),
    ('LABEL_EE8C31', 'ToneSlot_Empty_79',
     'Empty tone slot 79'),
    ('LABEL_EE8C35', 'ToneSlot_Empty_80',
     'Empty tone slot 80'),
    ('LABEL_EE8C39', 'ToneSlot_Empty_81',
     'Empty tone slot 81'),
    ('LABEL_EE8C3D', 'ToneSlot_Empty_82',
     'Empty tone slot 82'),
    ('LABEL_EE8C41', 'ToneSlot_Empty_83',
     'Empty tone slot 83'),
    ('LABEL_EE8C45', 'ToneSlot_Empty_84',
     'Empty tone slot 84'),
    ('LABEL_EE8C49', 'ToneSlot_Empty_85',
     'Empty tone slot 85'),
    ('LABEL_EE8C4D', 'ToneSlot_Empty_86',
     'Empty tone slot 86'),
    ('LABEL_EE8C51', 'ToneSlot_Empty_87',
     'Empty tone slot 87'),
    ('LABEL_EE8C55', 'ToneSlot_Empty_88',
     'Empty tone slot 88'),
    ('LABEL_EE8C59', 'ToneSlot_Empty_89',
     'Empty tone slot 89'),
    ('LABEL_EE8C5D', 'ToneSlot_Empty_90',
     'Empty tone slot 90'),
    ('LABEL_EE8C61', 'ToneSlot_Empty_91',
     'Empty tone slot 91'),
    ('LABEL_EE8C65', 'ToneSlot_Empty_92',
     'Empty tone slot 92'),
    ('LABEL_EE8C69', 'ToneSlot_Empty_93',
     'Empty tone slot 93'),
    ('LABEL_EE8C6D', 'ToneSlot_Empty_94',
     'Empty tone slot 94'),
    ('LABEL_EE8C71', 'ToneSlot_Empty_95',
     'Empty tone slot 95'),

    # ==================================================================
    # Region 14: Default/fallback tone entry (EE8C75)
    # ==================================================================

    ('LABEL_EE8C75', 'ToneSlot_Default',
     'Default/fallback tone entry (0xFF fill, terminates dispatch)'),

    # ==================================================================
    # Region 15: System cross-reference table (EE8C7E-EE8CF7)
    # Contains pointers to major system tables (Seq_InitFuncTable,
    # MIDI_SC0_DISPATCH_TABLE, DiskOp_ChannelCfgTable, etc.)
    # followed by miscellaneous raw data bytes.
    # ==================================================================

    ('LABEL_EE8C7E', 'SysRef_CrossRefTable',
     'System cross-reference table: Seq/MIDI/DiskOp/misc system pointers'),

    # ==================================================================
    # Region 16: Style dispatch handler table (EE8CF8)
    # Points to FDExxx style handler functions (FDE9AE, FDEB87, etc.)
    # ==================================================================

    ('LABEL_EE8CF8', 'StyleHandler_DispatchTable',
     'Style handler dispatch table: FDExxx style processing function pointers'),
]


# ---------------------------------------------------------------------------
# Engine: read file as binary, apply renames, write back
# ---------------------------------------------------------------------------

SRC = os.path.join(os.path.dirname(__file__), '..', 'maincpu', 'kn5000_v10_program.s')


def main():
    src = os.path.normpath(SRC)
    print(f"Reading {src} ...")
    with open(src, 'rb') as f:
        data = f.read()

    text = data.decode('latin-1')
    total = 0

    # Sort renames by old_label length descending to avoid substring collisions
    # (e.g., LABEL_EE7C9F must not be matched as part of LABEL_EE7C9FB...)
    sorted_renames = sorted(RENAMES, key=lambda r: len(r[0]), reverse=True)

    for old_label, new_label, comment in sorted_renames:
        # Use word-boundary matching to avoid partial replacements
        pattern = re.compile(r'\b' + re.escape(old_label) + r'\b')
        new_text, count = pattern.subn(new_label, text)
        if count > 0:
            text = new_text
            total += count
            print(f"  {old_label:30s} -> {new_label:40s}  ({count} occurrences)")
        else:
            print(f"  WARNING: {old_label} not found in file!")

    print(f"\nTotal replacements: {total}")
    print(f"Writing {src} ...")
    with open(src, 'wb') as f:
        f.write(text.encode('latin-1'))
    print("Done.")


if __name__ == '__main__':
    main()
