#!/usr/bin/env python3
"""Rename LABEL_* to semantic names for DSP subsystem routines in subcpu (032-037 range).

Based on analysis of the 0x032000-0x037FFF address range in the SubCPU
audio DSP subsystem. Each rename was verified by analyzing the routine's
code, register usage, called functions, and callers.

Uses binary I/O to handle encoding safely.
"""

import os
import re

# Renames: (old_label, new_label, brief_comment)
RENAMES = [

    # -------------------------------------------------------------------------
    # 032xxx - Voice buffer type selector (DSP_LookupVoiceBuffer continuation)
    # -------------------------------------------------------------------------
    ('LABEL_032002', 'VoiceBuf_TypeCheck_0x15',
     'DSP_LookupVoiceBuffer: check bc==0x15 (buffer type A)'),
    ('LABEL_032020', 'VoiceBuf_TypeCheck_0x50',
     'DSP_LookupVoiceBuffer: check bc==0x50 (buffer type B)'),
    ('LABEL_032032', 'VoiceBuf_TypeCheck_0x55',
     'DSP_LookupVoiceBuffer: check bc==0x55 (buffer type C)'),
    ('LABEL_032054', 'VoiceBuf_TypeCheck_Default',
     'DSP_LookupVoiceBuffer: default path (unknown buffer type)'),
    ('LABEL_03206E', 'VoiceBuf_TypeSelector_Epilogue',
     'DSP_LookupVoiceBuffer: epilogue (ret)'),
    ('LABEL_03207E', 'VoiceBuf_TypeSelector_EFFMatch',
     'DSP_LookupVoiceBuffer: EFF slot match path'),
    ('LABEL_032081', 'VoiceBuf_TypeSelector_NoMatch',
     'DSP_LookupVoiceBuffer: no EFF slot match, return default'),
    ('LABEL_032082', 'VoiceBuf_TypeSelector_MatchEpilogue',
     'DSP_LookupVoiceBuffer: matched slot epilogue'),

    # 032xxx - Voice channel scan (find EFF slot by voice index)
    ('LABEL_03209B', 'VoiceChanScan_LoopBody',
     'Scan 4 EFF slots for matching voice index: loop body'),
    ('LABEL_0320D2', 'VoiceChanScan_MatchFound',
     'Voice channel scan: matching slot found, load buffer ptr'),
    ('LABEL_0320FF', 'VoiceChanScan_NoMatch',
     'Voice channel scan: no slot matched, return 0'),
    ('LABEL_032109', 'VoiceChanScan_LoopNext',
     'Voice channel scan: increment loop counter'),
    ('LABEL_03210D', 'VoiceChanScan_Epilogue',
     'Voice channel scan: epilogue (ret)'),
    ('LABEL_03210F', 'VoiceChanScan_Data',
     'Voice channel scan: 2-byte data padding'),

    # 032xxx - Voice param update dispatcher (checks active/inactive + mode)
    ('LABEL_032112', 'VoiceParam_Update',
     'Check voice active flags and dispatch param update by mode bits'),
    ('LABEL_032145', 'VoiceParam_Update_ActivePath',
     'VoiceParam_Update: voice is active path'),
    ('LABEL_032167', 'VoiceParam_Update_ActiveEFF',
     'VoiceParam_Update: active voice with EFF routing dispatch'),
    ('LABEL_03218A', 'VoiceParam_Update_ActiveMain',
     'VoiceParam_Update: active voice main param write path'),
    ('LABEL_0321E5', 'VoiceParam_Update_InactivePath',
     'VoiceParam_Update: voice is inactive, sub-mode dispatch'),
    ('LABEL_032220', 'VoiceParam_Update_InactiveSub',
     'VoiceParam_Update: inactive voice sub-mode handler'),
    ('LABEL_03223A', 'VoiceParam_Update_InactiveEpilogue',
     'VoiceParam_Update: inactive voice epilogue'),

    # 032xxx - EFF slot iteration for voice buffer pointer assignment
    ('LABEL_032243', 'EFFSlotScan_LoopBody',
     'Iterate 4 EFF slots checking/assigning voice buffer ptr: loop body'),
    ('LABEL_032295', 'EFFSlotScan_AssignPath',
     'EFF slot scan: assign buffer pointer to matched slot'),
    ('LABEL_0322E4', 'EFFSlotScan_LoopNext',
     'EFF slot scan: advance loop counter'),
    ('LABEL_0322F0', 'EFFSlotScan_AltLoopBody',
     'EFF slot scan (alternate): loop body for secondary buffer route'),
    ('LABEL_032312', 'EFFSlotScan_AltMatchPath',
     'EFF slot scan (alternate): match found path'),
    ('LABEL_03232C', 'EFFSlotScan_AltAssign',
     'EFF slot scan (alternate): assign buffer ptr and continue'),
    ('LABEL_032335', 'EFFSlotScan_AltLoopNext',
     'EFF slot scan (alternate): advance loop counter'),
    ('LABEL_032387', 'EFFSlotScan_AltEpilogue',
     'EFF slot scan (alternate): epilogue (retd)'),
    ('LABEL_0323D6', 'EFFSlotScan_OuterNext',
     'EFF slot scan: outer loop increment'),
    ('LABEL_0323DF', 'EFFSlotScan_Epilogue',
     'EFF slot scan: outer loop epilogue (retd)'),

    # 032xxx - Voice buffer index decode (DE-based table selection)
    ('LABEL_0323E5', 'VoiceBufIdx_Decode',
     'Decode voice buffer index: DE=0/0x40/0x80/0xC0 -> table pointer'),
    ('LABEL_032417', 'VoiceBufIdx_TableA',
     'VoiceBufIdx_Decode: DE=0x00, select table base A'),
    ('LABEL_032433', 'VoiceBufIdx_TableB',
     'VoiceBufIdx_Decode: DE=0x40, select table base B'),
    ('LABEL_03244F', 'VoiceBufIdx_TableC',
     'VoiceBufIdx_Decode: DE=0x80, select table base C'),
    ('LABEL_032469', 'VoiceBufIdx_TableD',
     'VoiceBufIdx_Decode: DE=0xC0, select table base D'),

    # 032xxx - Slot param write with sub-selector dispatch
    ('LABEL_03248B', 'SlotParam_WriteDispatch',
     'Write slot param: read ix field 0x30 bits, dispatch to sub-writer'),
    ('LABEL_0324D1', 'SlotParam_WriteType0',
     'SlotParam_WriteDispatch: type 0 store path'),
    ('LABEL_0324DD', 'SlotParam_WriteType1',
     'SlotParam_WriteDispatch: type 1 store path'),
    ('LABEL_0324F7', 'SlotParam_WriteType2',
     'SlotParam_WriteDispatch: type 2 store path'),
    ('LABEL_032517', 'SlotParam_WriteType3',
     'SlotParam_WriteDispatch: type 3 store path'),
    ('LABEL_032540', 'SlotParam_WriteType4',
     'SlotParam_WriteDispatch: type 4 store path'),
    ('LABEL_032569', 'SlotParam_WriteType5',
     'SlotParam_WriteDispatch: type 5 store path'),
    ('LABEL_032589', 'SlotParam_WriteType6',
     'SlotParam_WriteDispatch: type 6 store path'),
    ('LABEL_0325B1', 'SlotParam_WriteType7',
     'SlotParam_WriteDispatch: type 7 store path'),
    ('LABEL_0325F6', 'SlotParam_WriteDispatch_Epilogue',
     'SlotParam_WriteDispatch: epilogue (popw iz + retd)'),

    # 032xxx - Voice channel copy helper
    ('LABEL_0325FC', 'VoiceChanCopy_Main',
     'Copy voice channel params: reads two entries, calls SlotParam_WriteDispatch'),

    # 032xxx - Extract fields and call write helper
    ('LABEL_032682', 'VoiceField_ExtractAndWrite',
     'Extract fields from buf+1/+2, call SlotParam_WriteDispatch, retd 2'),

    # 032xxx - Voice buffer pointer update
    ('LABEL_0326B6', 'VoiceBufPtr_Update',
     'Update voice buffer ptr: check bit 0 of state flags, two sub-paths'),
    ('LABEL_032713', 'VoiceBufPtr_Update_Path0',
     'VoiceBufPtr_Update: bit-0 clear path'),
    ('LABEL_03274D', 'VoiceBufPtr_Update_Path1',
     'VoiceBufPtr_Update: bit-0 set path'),
    ('LABEL_032750', 'VoiceBufPtr_Update_Common',
     'VoiceBufPtr_Update: common final write path'),

    # 032xxx - Table pointer selectors based on bit 2 of 0x041343
    ('LABEL_032780', 'VoiceTablePtr_Select',
     'Select table pointer based on bit 2 of 0x041343'),
    ('LABEL_032796', 'VoiceTablePtr_SelectA',
     'VoiceTablePtr_Select: bit 2 clear, table base A'),
    ('LABEL_03279E', 'VoiceTablePtr_SelectB',
     'VoiceTablePtr_Select: bit 2 set, table base B'),
    ('LABEL_0327B2', 'VoiceTablePtr_SelectC',
     'VoiceTablePtr_Select: alternate, table base C'),
    ('LABEL_0327C8', 'VoiceTablePtr_SelectD',
     'VoiceTablePtr_Select: alternate, table base D'),
    ('LABEL_0327D0', 'VoiceTablePtr_Common',
     'VoiceTablePtr_Select: common multiply+offset for voice slot address'),
    ('LABEL_0327E4', 'VoiceTablePtr_Epilogue',
     'VoiceTablePtr_Select: epilogue (ret)'),
    ('LABEL_0327FA', 'VoiceTablePtr_Data',
     'VoiceTablePtr_Select: 2-byte data padding'),
    ('LABEL_032802', 'VoiceTablePtr_Select2',
     'Second table pointer selector variant'),

    # 032xxx - Common multiply+offset for voice slot address
    ('LABEL_032814', 'VoiceSlotAddr_Multiply',
     'Compute voice slot address: multiply index + apply table offset'),

    # 032xxx - Composite param-write helpers
    ('LABEL_032839', 'VoiceParam_WriteWithOffset',
     'Write D field, compute iy offset, call VoiceBufPtr_Update_Common'),
    ('LABEL_0328B5', 'VoiceParam_WriteWithOffset_Alt',
     'Alternate voice param write helper variant'),
    ('LABEL_0328E2', 'VoiceParam_WriteWithOffset_3Arg',
     'Save e,c,a on stack, call VoiceParam_WriteWithOffset, store xhl'),

    # 032xxx - Voice init dispatcher
    ('LABEL_032938', 'VoiceInit_Dispatcher',
     'Main voice init: call VoiceParam_Update, dispatch by algo type (0/0x40/0x80/0xC0)'),
    ('LABEL_032983', 'VoiceInit_EFFScanLoop',
     'VoiceInit_Dispatcher: iterate EFF slots checking for match'),
    ('LABEL_03299E', 'VoiceInit_EFFScanMatch',
     'VoiceInit_Dispatcher: EFF slot match found path'),
    ('LABEL_0329C0', 'VoiceInit_EFFScanNext',
     'VoiceInit_Dispatcher: advance EFF scan loop counter'),
    ('LABEL_0329CA', 'VoiceInit_AltPath',
     'VoiceInit_Dispatcher: alternate path calling 0x02AAE7'),
    ('LABEL_0329D2', 'VoiceInit_AltPath2',
     'VoiceInit_Dispatcher: alternate path calling 0x02AB10'),
    ('LABEL_032A02', 'VoiceInit_Epilogue',
     'VoiceInit_Dispatcher: epilogue (ret)'),

    # 032xxx - Voice buffer lookup with 0x20 flag check
    ('LABEL_032A08', 'VoiceBuf_Lookup_0x20Flag',
     'Voice buf lookup: check 0x20 flag in voice state, select buffer path'),
    ('LABEL_032A68', 'VoiceBuf_Lookup_FlagSet',
     'VoiceBuf_Lookup_0x20Flag: flag set path'),
    ('LABEL_032A88', 'VoiceBuf_Lookup_FlagClear',
     'VoiceBuf_Lookup_0x20Flag: flag clear path'),
    ('LABEL_032AA2', 'VoiceBuf_Lookup_Common',
     'VoiceBuf_Lookup_0x20Flag: common read/return path'),
    ('LABEL_032ADA', 'VoiceBuf_Lookup_Epilogue',
     'VoiceBuf_Lookup_0x20Flag: epilogue (ret)'),

    # 032xxx - Param write dispatch helper
    ('LABEL_032AE0', 'VoiceParam_WriteDispatchHelper',
     'Read slot, compute iy, call VoiceBuf_Lookup_0x20Flag; top-level helper'),

    # 032xxx - Voice flags aggregator
    ('LABEL_032B1E', 'VoiceFlags_Aggregate',
     'Aggregate voice state bits into DE flags word (bits 0 and 1)'),
    ('LABEL_032B6B', 'VoiceFlags_Bit0Check',
     'VoiceFlags_Aggregate: test bit for flag bit 0'),
    ('LABEL_032BC0', 'VoiceFlags_Bit0Set',
     'VoiceFlags_Aggregate: set DE bit 0'),
    ('LABEL_032BDF', 'VoiceFlags_Bit1Check',
     'VoiceFlags_Aggregate: test bit for flag bit 1'),
    ('LABEL_032BF3', 'VoiceFlags_Bit1Set',
     'VoiceFlags_Aggregate: set DE bit 1'),
    ('LABEL_032C0F', 'VoiceFlags_Bit2Check',
     'VoiceFlags_Aggregate: test bit for flag bit 2'),
    ('LABEL_032C64', 'VoiceFlags_Bit2Set',
     'VoiceFlags_Aggregate: set DE bit 2'),
    ('LABEL_032C83', 'VoiceFlags_Bit3Check',
     'VoiceFlags_Aggregate: test bit for flag bit 3'),
    ('LABEL_032C97', 'VoiceFlags_Bit3Set',
     'VoiceFlags_Aggregate: set DE bit 3'),
    ('LABEL_032CB1', 'VoiceFlags_Bit4Check',
     'VoiceFlags_Aggregate: test bit for flag bit 4'),
    ('LABEL_032CD1', 'VoiceFlags_Bit4Set',
     'VoiceFlags_Aggregate: set DE bit 4'),
    ('LABEL_032CE5', 'VoiceFlags_Bit5Check',
     'VoiceFlags_Aggregate: test bit for flag bit 5'),
    ('LABEL_032CFF', 'VoiceFlags_Bit5Set',
     'VoiceFlags_Aggregate: set DE bit 5'),
    ('LABEL_032D1F', 'VoiceFlags_Bit6Check',
     'VoiceFlags_Aggregate: test bit for flag bit 6'),
    ('LABEL_032D33', 'VoiceFlags_Bit6Set',
     'VoiceFlags_Aggregate: set DE bit 6'),

    # 032xxx - Signed clamp [0, 0x7F] helper
    ('LABEL_032D44', 'SignedClamp_Zero',
     'Clamp signed value to [0, 0x7F]: value < 0, return 0'),
    ('LABEL_032D4F', 'SignedClamp_Max',
     'Clamp signed value to [0, 0x7F]: value > 0x7F, return 0x7F'),
    ('LABEL_032D55', 'SignedClamp_InRange',
     'Clamp signed value to [0, 0x7F]: value in range, return as-is'),

    # 032xxx - Algo-type-indexed table lookup
    ('LABEL_032D58', 'AlgoType_TableLookup',
     'Lookup from algo-type-indexed table (c=0/1/2/3 selects base)'),
    ('LABEL_032D97', 'AlgoType_Table0',
     'AlgoType_TableLookup: algo type 0 table select'),
    ('LABEL_032DAD', 'AlgoType_Table1',
     'AlgoType_TableLookup: algo type 1 table select'),
    ('LABEL_032DDC', 'AlgoType_Table2',
     'AlgoType_TableLookup: algo type 2 table select'),
    ('LABEL_032DF2', 'AlgoType_Table3',
     'AlgoType_TableLookup: algo type 3 table select'),
    ('LABEL_032E08', 'AlgoType_TableCommon',
     'AlgoType_TableLookup: common index+read epilogue'),

    # 032xxx - Envelope/transpose update loop
    ('LABEL_032E1E', 'EnvTranspose_UpdateLoop',
     'Iterate 4 EFF slots: call AlgoType_TableLookup, apply envelope/transpose to state'),
    ('LABEL_032E5E', 'EnvTranspose_ApplyPath',
     'EnvTranspose_UpdateLoop: apply result to state table'),
    ('LABEL_032EAA', 'EnvTranspose_LoopNext',
     'EnvTranspose_UpdateLoop: advance slot counter'),
    ('LABEL_032F09', 'EnvTranspose_SubPath1',
     'EnvTranspose_UpdateLoop: sub-path 1 for secondary param update'),
    ('LABEL_032F69', 'EnvTranspose_SubPath2',
     'EnvTranspose_UpdateLoop: sub-path 2'),
    ('LABEL_032F7D', 'EnvTranspose_SubPath3',
     'EnvTranspose_UpdateLoop: sub-path 3'),
    ('LABEL_032FB2', 'EnvTranspose_SubPath4',
     'EnvTranspose_UpdateLoop: sub-path 4'),
    ('LABEL_032FD0', 'EnvTranspose_Epilogue',
     'EnvTranspose_UpdateLoop: epilogue (ret)'),

    # 032xxx - Algo-flag writer
    ('LABEL_032FD5', 'AlgoFlag_Write',
     'Write ix field, set active-channel bit in state; outer loop over EFF slots'),

    # -------------------------------------------------------------------------
    # 033xxx - AlgoFlag_Write inner loop and routing flag helpers
    # -------------------------------------------------------------------------
    ('LABEL_03302B', 'AlgoFlag_Write_OuterStart',
     'AlgoFlag_Write: outer EFF slot loop start (checks bit 5, compares channel)'),
    ('LABEL_033032', 'AlgoFlag_Write_InnerLoop',
     'AlgoFlag_Write: inner loop body (reads buf+6/+38/+56 based on c)'),
    ('LABEL_033069', 'AlgoFlag_Write_InnerMatch',
     'AlgoFlag_Write: inner loop channel match path'),
    ('LABEL_033092', 'AlgoFlag_Write_InnerNext',
     'AlgoFlag_Write: inner loop increment'),
    ('LABEL_0330B9', 'AlgoFlag_Write_OuterMatch',
     'AlgoFlag_Write: outer slot match, write bit 1 to state'),
    ('LABEL_0330CC', 'AlgoFlag_Write_OuterNext',
     'AlgoFlag_Write: outer loop increment'),
    ('LABEL_0330D3', 'AlgoFlag_Write_Epilogue',
     'AlgoFlag_Write: epilogue (popw iz + ret)'),

    # 033xxx - Parallel routine writing bit 3 instead of bit 1
    ('LABEL_0330D5', 'AlgoFlag_Write_Bit3',
     'Write ix field with bit 3 (parallel to AlgoFlag_Write but different bit)'),
    ('LABEL_03312B', 'AlgoFlag_Write_Bit3_OuterStart',
     'AlgoFlag_Write_Bit3: outer loop start'),
    ('LABEL_033132', 'AlgoFlag_Write_Bit3_InnerLoop',
     'AlgoFlag_Write_Bit3: inner loop body'),
    ('LABEL_033169', 'AlgoFlag_Write_Bit3_InnerMatch',
     'AlgoFlag_Write_Bit3: inner match path'),
    ('LABEL_033192', 'AlgoFlag_Write_Bit3_InnerNext',
     'AlgoFlag_Write_Bit3: inner loop increment'),
    ('LABEL_0331B9', 'AlgoFlag_Write_Bit3_OuterMatch',
     'AlgoFlag_Write_Bit3: outer match, write bit 3'),
    ('LABEL_0331CC', 'AlgoFlag_Write_Bit3_OuterNext',
     'AlgoFlag_Write_Bit3: outer loop increment'),
    ('LABEL_0331D3', 'AlgoFlag_Write_Bit3_Epilogue',
     'AlgoFlag_Write_Bit3: epilogue (ret)'),

    # 033xxx - Routing flag encoder
    ('LABEL_0331D5', 'RoutingFlag_Encode',
     'Encode channel index + flag into DE word from IY/IX fields'),
    ('LABEL_033240', 'RoutingFlag_Chan0',
     'RoutingFlag_Encode: channel count = 0 path'),
    ('LABEL_03325C', 'RoutingFlag_Chan1',
     'RoutingFlag_Encode: channel count = 1 path'),
    ('LABEL_033278', 'RoutingFlag_Chan2',
     'RoutingFlag_Encode: channel count = 2 path'),
    ('LABEL_0332A1', 'RoutingFlag_Chan0B',
     'RoutingFlag_Encode: channel 0 alternate path (0xC000 mask)'),
    ('LABEL_0332BC', 'RoutingFlag_Chan1B',
     'RoutingFlag_Encode: channel 1 alternate path (0x3300 mask)'),
    ('LABEL_0332D6', 'RoutingFlag_Epilogue',
     'RoutingFlag_Encode: epilogue (ret)'),

    # 033xxx - Single-slot routing flag writer
    ('LABEL_0332DC', 'SlotRouting_WriteSingle',
     'Write routing flags for a single EFF slot from stack param byte'),
    ('LABEL_03330E', 'SlotRouting_Chan0',
     'SlotRouting_WriteSingle: channel 0 write path'),
    ('LABEL_033324', 'SlotRouting_Chan1PreWrite',
     'SlotRouting_WriteSingle: channel 1 pre-write'),
    ('LABEL_033327', 'SlotRouting_Chan1',
     'SlotRouting_WriteSingle: channel 1 write path'),
    ('LABEL_033359', 'SlotRouting_Chan2',
     'SlotRouting_WriteSingle: channel 2 write path'),
    ('LABEL_03336F', 'SlotRouting_Chan3PreWrite',
     'SlotRouting_WriteSingle: channel 3 pre-write'),
    ('LABEL_033372', 'SlotRouting_Chan3',
     'SlotRouting_WriteSingle: channel 3 write path'),
    ('LABEL_0333A4', 'SlotRouting_Chan4',
     'SlotRouting_WriteSingle: channel 4 write path'),
    ('LABEL_0333BB', 'SlotRouting_Epilogue',
     'SlotRouting_WriteSingle: epilogue (ret)'),

    # 033xxx - EFF routing init (main loop)
    ('LABEL_0333BE', 'EFF_RoutingInit',
     'EFF routing init: write slot 0 base, iterate 4 EFF slots calling routing helpers'),
    ('LABEL_033416', 'EFF_RoutingInit_LoopBody',
     'EFF_RoutingInit: per-slot loop body'),
    ('LABEL_033469', 'EFF_RoutingInit_SlotPath',
     'EFF_RoutingInit: routing data write for this slot'),
    ('LABEL_0334C5', 'EFF_RoutingInit_LoopNext',
     'EFF_RoutingInit: advance slot loop counter'),
    ('LABEL_033507', 'EFF_RoutingInit_SubLoop',
     'EFF_RoutingInit: sub-loop for secondary routing entries'),
    ('LABEL_033547', 'EFF_RoutingInit_SubLoopNext',
     'EFF_RoutingInit: sub-loop increment'),
    ('LABEL_033550', 'EFF_RoutingInit_Epilogue',
     'EFF_RoutingInit: epilogue (ret)'),

    # 033xxx - Algo-type state writer
    ('LABEL_033557', 'AlgoType_StateWrite',
     'Write algo-type state: check type 7, set/clear bit 1 of 0x041372, call state refresh'),
    ('LABEL_0335ED', 'AlgoType_StateWrite_Type7',
     'AlgoType_StateWrite: algo type 7 path'),
    ('LABEL_033629', 'AlgoType_StateWrite_NonType7',
     'AlgoType_StateWrite: non-type-7 path'),
    ('LABEL_033663', 'AlgoType_StateWrite_RefreshA',
     'AlgoType_StateWrite: call state refresh function A'),
    ('LABEL_0336A4', 'AlgoType_StateWrite_RefreshB',
     'AlgoType_StateWrite: call state refresh function B'),
    ('LABEL_0336B8', 'AlgoType_StateWrite_RefreshC',
     'AlgoType_StateWrite: call state refresh function C'),
    ('LABEL_0336D0', 'AlgoType_StateWrite_RefreshD',
     'AlgoType_StateWrite: call state refresh function D'),
    ('LABEL_033752', 'AlgoType_StateWrite_RefreshE',
     'AlgoType_StateWrite: call state refresh function E'),
    ('LABEL_033769', 'AlgoType_StateWrite_RefreshF',
     'AlgoType_StateWrite: call state refresh function F'),
    ('LABEL_033793', 'AlgoType_StateWrite_RefreshG',
     'AlgoType_StateWrite: call state refresh function G'),
    ('LABEL_0337CF', 'AlgoType_StateWrite_Epilogue',
     'AlgoType_StateWrite: epilogue (ret)'),

    # 033xxx - DSP algo type dispatch tables
    ('LABEL_0337D2', 'DSP_AlgoType_Dispatch1',
     'DSP algo type dispatch via jump table 1 at 0x00fb66 (12 entries)'),
    ('LABEL_033812', 'DSP_AlgoType_Dispatch1_TableData',
     'Jump table 1 data block (DSP chip command dispatch entries)'),
    ('LABEL_03397E', 'DSP_AlgoType_Dispatch1_Store',
     'DSP algo type dispatch 1: store HL result (bc*4+0x57 offset) into state'),
    ('LABEL_03399E', 'DSP_AlgoType_Dispatch2',
     'DSP algo type dispatch via jump table 2 at 0x00fb7e'),
    ('LABEL_0339DE', 'DSP_AlgoType_Dispatch2_TableData',
     'Jump table 2 data block'),
    ('LABEL_033B29', 'DSP_AlgoType_Dispatch2_Store',
     'DSP algo type dispatch 2: store W+HL result (2-word store)'),

    # 033xxx - Algo type A/B checker
    ('LABEL_033B4C', 'AlgoType_AB_Checker',
     'Check algo type 0xA or 0xB; return voice index at +95 masked to 0x3F'),
    ('LABEL_033B70', 'AlgoType_AB_LoadIndex',
     'AlgoType_AB_Checker: load (xwa+95) & 0x3F into hl'),

    # 033xxx - DSP channel freq packet writers
    ('LABEL_033B8B', 'DSP_ChanFreq_WritePacket1',
     'DSP channel freq packet writer (algo 6/7 path), write to 0x0413c7'),
    ('LABEL_033C16', 'DSP_ChanFreq_WritePacket1_Algo7',
     'DSP_ChanFreq_WritePacket1: algo 7 specific sub-path'),
    ('LABEL_033C58', 'DSP_ChanFreq_WritePacket1_Zero',
     'DSP_ChanFreq_WritePacket1: zero path (HL = 0)'),
    ('LABEL_033C5A', 'DSP_ChanFreq_WritePacket1_Epilogue',
     'DSP_ChanFreq_WritePacket1: common epilogue (write HL to 0x0413c7)'),
    ('LABEL_033C6B', 'DSP_ChanFreq_WritePacket2',
     'DSP channel second freq packet writer (writes to 0x0413c9)'),
    ('LABEL_033C8D', 'DSP_ChanFreq_WritePacket2_PathA',
     'DSP_ChanFreq_WritePacket2: path A'),
    ('LABEL_033CD2', 'DSP_ChanFreq_WritePacket2_PathB',
     'DSP_ChanFreq_WritePacket2: path B'),
    ('LABEL_033CD4', 'DSP_ChanFreq_WritePacket2_Epilogue',
     'DSP_ChanFreq_WritePacket2: epilogue'),

    # 033xxx - Voice secondary param fetch (bit 15 of 0x041372)
    ('LABEL_033CE5', 'Voice_SecondaryParam_Fetch',
     'Check bit 15 of 0x041372, dispatch to algo-9 lookup via 0x012038'),
    ('LABEL_033D3C', 'Voice_SecondaryParam_FallbackA',
     'Voice_SecondaryParam_Fetch: fallback path A (return 0xFF)'),
    ('LABEL_033D40', 'Voice_SecondaryParam_FallbackB',
     'Voice_SecondaryParam_Fetch: fallback path B (return 0xFF)'),
    ('LABEL_033D42', 'Voice_SecondaryParam_FallbackC',
     'Voice_SecondaryParam_Fetch: fallback path C (return 0xFF)'),
    ('LABEL_033D43', 'Voice_SecondaryParam_Fetch2',
     'Voice secondary param fetch with bit-15 guard check'),
    ('LABEL_033D82', 'Voice_SecondaryParam_AlgoAB',
     'Voice_SecondaryParam_Fetch2: algo A/B specific path'),
    ('LABEL_033DAA', 'Voice_SecondaryParam_Path2',
     'Voice_SecondaryParam_Fetch2: path 2'),
    ('LABEL_033DBF', 'Voice_SecondaryParam_Path3',
     'Voice_SecondaryParam_Fetch2: path 3'),
    ('LABEL_033DD2', 'Voice_SecondaryParam_Path4',
     'Voice_SecondaryParam_Fetch2: path 4'),
    ('LABEL_033DD3', 'Voice_SecondaryParam_Epilogue',
     'Voice_SecondaryParam_Fetch2: epilogue'),

    # 033xxx - Third algo dispatch
    ('LABEL_033E02', 'DSP_AlgoType_Dispatch3',
     'Third algo type dispatch via jump table at 0x00fb96'),
    ('LABEL_033E44', 'DSP_AlgoType_Dispatch3_TableData',
     'Jump table 3 data block'),

    # 033xxx - Algo 6/7 checker and LUT offset lookup
    ('LABEL_033F74', 'Algo67_LUTOffset_Check',
     'Check algo 6/7, read LUT offset entry'),
    ('LABEL_033F98', 'Algo67_LUTOffset_Read',
     'Algo67_LUTOffset_Check: read from 0x011e16 table'),
    ('LABEL_033FFE', 'Algo67_LUTOffset_Flag4000',
     'Algo67_LUTOffset_Check: return 0x4000'),

    # -------------------------------------------------------------------------
    # 034xxx - Algo sub-table dispatch routines
    # -------------------------------------------------------------------------
    ('LABEL_034003', 'Algo_SubTable_Flag8000',
     'Sub-table dispatch: return 0x8000 bit flag'),
    ('LABEL_034006', 'Algo_SubTable_FlagC000',
     'Sub-table dispatch: return 0xC000 bit flag'),
    ('LABEL_034007', 'Algo_SubTable_DispatchA',
     'Read byte at (xde+2) from algo table row, dispatch via 0x0340CC jump table'),
    ('LABEL_034067', 'Algo_SubTable_DispatchB',
     'Read byte at (xde+2), alternate dispatch route via 0x0340CC'),
    ('LABEL_0340CC', 'Algo_SubTable_JumpTable1',
     'Jump table 1 data block for algo sub-table dispatch (entry 0x0340CC)'),
    ('LABEL_034153', 'Algo_SubTable_DispatchC',
     'Read byte at (xde+3), dispatch via 0x0341be jump table'),
    ('LABEL_0341BE', 'Algo_SubTable_JumpTable2',
     'Jump table 2 data block for algo sub-table dispatch (entry 0x0341BE)'),
    ('LABEL_034217', 'Algo_SubTable_Epilogue',
     'Algo sub-table dispatch epilogue (pop_werp 0xFB + ret)'),
    ('LABEL_03421E', 'Algo_SubTable_Bit15Dispatch',
     'Check bit 15 of 0x041372, dispatch to 0x03429D jump table'),
    ('LABEL_03429D', 'Algo_SubTable_JumpTable3',
     'Jump table 3 data block (bit-15 guard dispatch)'),
    ('LABEL_03430C', 'Algo_SubTable_ZeroReturn',
     'Algo sub-table: return zero (no-op path)'),

    # 034xxx - Voice note-param update loop
    ('LABEL_03430F', 'VoiceNoteParam_UpdateLoop',
     'Iterate 4 EFF slots calling Algo_SubTable_DispatchA/B/C'),
    ('LABEL_03433B', 'VoiceNoteParam_LoopBody',
     'VoiceNoteParam_UpdateLoop: per-slot loop body'),
    ('LABEL_0343FB', 'VoiceNoteParam_FallbackPath',
     'VoiceNoteParam_UpdateLoop: fallback path (no dispatch match)'),
    ('LABEL_034404', 'VoiceNoteParam_LoopNext',
     'VoiceNoteParam_UpdateLoop: advance slot counter'),
    ('LABEL_03448B', 'VoiceNoteParam_Epilogue',
     'VoiceNoteParam_UpdateLoop: epilogue (ret)'),

    # 034xxx - Voice active flag checker and index loader
    ('LABEL_034491', 'Voice_ActiveFlag_CheckAndLoad',
     'Check voice active flag + 0x0451a4 match, load voice coeff index'),
    ('LABEL_0344C5', 'Voice_ActiveFlag_ActivePath',
     'Voice_ActiveFlag_CheckAndLoad: voice active path'),
    ('LABEL_0344E9', 'Voice_ActiveFlag_InactivePath',
     'Voice_ActiveFlag_CheckAndLoad: voice inactive path'),

    # 034xxx - ProgChange jump table data
    ('LABEL_034503', 'Voice_ProgChange_TableData',
     'Jump table data block for Voice_ProgChange dispatch'),

    # 034xxx - DSP slot param write helpers (per slot index 0..4)
    ('LABEL_034606', 'DSP_SlotParam_Write_Slot0',
     'Write DSP param for slot 0 (target 0x0413d0)'),
    ('LABEL_03463F', 'DSP_SlotParam_Write_Slot0_Path',
     'DSP_SlotParam_Write_Slot0: alternate path'),
    ('LABEL_034651', 'DSP_SlotParam_Write_Slot1',
     'Write DSP param for slot 1 (target 0x0413d1)'),
    ('LABEL_03468A', 'DSP_SlotParam_Write_Slot1_Path',
     'DSP_SlotParam_Write_Slot1: alternate path'),
    ('LABEL_03469C', 'DSP_SlotParam_Write_Slot2',
     'Write DSP param for slot 2 (target 0x0413d2)'),
    ('LABEL_0346D5', 'DSP_SlotParam_Write_Slot2_Path',
     'DSP_SlotParam_Write_Slot2: alternate path'),
    ('LABEL_0346E7', 'DSP_SlotParam_Write_Slot3',
     'Write DSP param for slot 3 (target 0x0413d3)'),
    ('LABEL_034720', 'DSP_SlotParam_Write_Slot3_Path',
     'DSP_SlotParam_Write_Slot3: alternate path'),
    ('LABEL_034732', 'DSP_SlotParam_Write_Slot4',
     'Write DSP param for slot 4 (target 0x0413d4)'),
    ('LABEL_03476B', 'DSP_SlotParam_Write_Slot4_Path',
     'DSP_SlotParam_Write_Slot4: alternate path'),

    # 034xxx - Voice active flag setter
    ('LABEL_03477D', 'Voice_ActiveFlag_Set',
     'Set voice active: AND 0xFC, OR 0x04, clear 0x04136c'),

    # 034xxx - Voice note state clear
    ('LABEL_0347B7', 'Voice_NoteState_Clear',
     'Clear voice note state: check 0x041343 bit 0, clear 0x041385-88 / 0x041383-84'),
    ('LABEL_034827', 'Voice_NoteState_InnerLoopA',
     'Voice_NoteState_Clear: inner loop 4x3 clear of (xbc+41)'),
    ('LABEL_03482D', 'Voice_NoteState_InnerLoopB',
     'Voice_NoteState_Clear: inner loop body (xbc+42) clear'),
    ('LABEL_034889', 'Voice_NoteState_Epilogue',
     'Voice_NoteState_Clear: epilogue'),

    # 034xxx - Full voice slot init
    ('LABEL_034890', 'VoiceSlot_FullInit',
     'Full voice slot init: calls routing/flag/envelope/note init in sequence'),
    ('LABEL_0348EC', 'VoiceSlot_FullInit_Loop1',
     'VoiceSlot_FullInit: inner loop 1 (AlgoFlag_Write_Bit3)'),
    ('LABEL_0348F2', 'VoiceSlot_FullInit_Loop1Next',
     'VoiceSlot_FullInit: loop 1 advance'),
    ('LABEL_03492C', 'VoiceSlot_FullInit_Loop2',
     'VoiceSlot_FullInit: inner loop 2 (AlgoFlag_Write)'),
    ('LABEL_034932', 'VoiceSlot_FullInit_Loop2Next',
     'VoiceSlot_FullInit: loop 2 advance'),
    ('LABEL_034952', 'VoiceSlot_FullInit_Loop3',
     'VoiceSlot_FullInit: inner loop 3 (EFF_RoutingInit)'),
    ('LABEL_03495C', 'VoiceSlot_FullInit_Epilogue',
     'VoiceSlot_FullInit: epilogue'),

    # 034xxx - Alternate voice init (with 0x02ADC1 instead of VoiceFlags_Aggregate)
    ('LABEL_034968', 'VoiceSlot_AltInit',
     'Alternate voice slot init: calls 0x02ADC1 instead of VoiceFlags_Aggregate'),
    ('LABEL_0349C5', 'VoiceSlot_AltInit_Loop1',
     'VoiceSlot_AltInit: inner loop 1'),
    ('LABEL_0349CD', 'VoiceSlot_AltInit_Loop1Next',
     'VoiceSlot_AltInit: loop 1 advance'),
    ('LABEL_034A09', 'VoiceSlot_AltInit_Loop2',
     'VoiceSlot_AltInit: inner loop 2'),
    ('LABEL_034A11', 'VoiceSlot_AltInit_Loop2Next',
     'VoiceSlot_AltInit: loop 2 advance'),
    ('LABEL_034A33', 'VoiceSlot_AltInit_Loop3',
     'VoiceSlot_AltInit: inner loop 3'),
    ('LABEL_034A3C', 'VoiceSlot_AltInit_Epilogue',
     'VoiceSlot_AltInit: epilogue'),

    # 034xxx - Voice_ProgChange helper labels
    ('LABEL_034AB8', 'Voice_ProgChange_Path1',
     'Voice_ProgChange: dispatch path 1'),
    ('LABEL_034ACD', 'Voice_ProgChange_Path2',
     'Voice_ProgChange: dispatch path 2'),
    ('LABEL_034B2A', 'Voice_ProgChange_InnerDispatch1',
     'Voice_ProgChange inner dispatch path 1'),
    ('LABEL_034B34', 'Voice_ProgChange_InnerDispatch2',
     'Voice_ProgChange inner dispatch path 2'),
    ('LABEL_034B45', 'Voice_ProgChange_InnerDispatch3',
     'Voice_ProgChange inner dispatch path 3'),

    # 034xxx - Voice clear all (26 voices x 3 EFF slots x 4 sub-slots)
    ('LABEL_034B4B', 'VoiceSlot_ClearAll',
     'Clear all 26 voice slots x 3 EFF slots x 4 sub-slots'),
    ('LABEL_034B59', 'VoiceSlot_ClearAll_OuterLoop',
     'VoiceSlot_ClearAll: outer voice loop body'),
    ('LABEL_034B66', 'VoiceSlot_ClearAll_MidLoop',
     'VoiceSlot_ClearAll: mid-level EFF loop body'),
    ('LABEL_034B72', 'VoiceSlot_ClearAll_InnerLoop',
     'VoiceSlot_ClearAll: inner sub-slot loop body'),
    ('LABEL_034BDE', 'VoiceSlot_ClearAll_InnerNext',
     'VoiceSlot_ClearAll: inner loop increment'),
    ('LABEL_034BE9', 'VoiceSlot_ClearAll_MidNext',
     'VoiceSlot_ClearAll: mid-loop increment'),
    ('LABEL_034BFB', 'VoiceSlot_ClearAll_OuterNext',
     'VoiceSlot_ClearAll: outer loop increment'),
    ('LABEL_034C07', 'VoiceSlot_ClearAll_SubLoop1',
     'VoiceSlot_ClearAll: sub-loop 1 body'),
    ('LABEL_034C13', 'VoiceSlot_ClearAll_SubLoop1Next',
     'VoiceSlot_ClearAll: sub-loop 1 increment'),
    ('LABEL_034C31', 'VoiceSlot_ClearAll_SubLoop2',
     'VoiceSlot_ClearAll: sub-loop 2 body'),
    ('LABEL_034C3B', 'VoiceSlot_ClearAll_Epilogue',
     'VoiceSlot_ClearAll: epilogue (ret)'),

    # 034xxx - Data padding and Audio_Process_Init branches
    ('LABEL_034CDA', 'Audio_Process_Init_Data',
     '1-byte data padding (0x0E) before Audio_Process_Init branches'),
    ('LABEL_034CED', 'Audio_Process_Init_BranchA',
     'Audio_Process_Init: branch A (init variant)'),
    ('LABEL_034CF5', 'Audio_Process_Init_BranchB',
     'Audio_Process_Init: branch B (init variant)'),

    # 034xxx - RingBuf_ReadByte empty/return paths
    ('LABEL_034D21', 'RingBuf_ReadByte_Empty',
     'RingBuf_ReadByte: buffer empty path (return 0)'),
    ('LABEL_034D24', 'RingBuf_ReadByte_Return',
     'RingBuf_ReadByte: read success, return byte in A'),
    ('LABEL_034D25', 'RingBuf_ReadByte_Data',
     'RingBuf_ReadByte: 6-byte data block after routine'),

    # 034xxx - RingBuf_SkipToEnd
    ('LABEL_034D37', 'RingBuf_SkipToEnd_Loop',
     'RingBuf_SkipToEnd: loop body advancing read pointer'),
    ('LABEL_034D40', 'RingBuf_SkipToEnd_Epilogue',
     'RingBuf_SkipToEnd: epilogue (ret)'),

    # 034xxx - DSP write count compute
    ('LABEL_034FE6', 'DSP_WriteCount_Compute',
     'Compute DSP write count: popcount scan over dirty flags'),
    ('LABEL_034FFA', 'DSP_WriteCount_Loop',
     'DSP_WriteCount_Compute: scan loop body'),

    # -------------------------------------------------------------------------
    # 035xxx - DSP flush, reinit, voice slot helpers
    # -------------------------------------------------------------------------
    ('LABEL_035000', 'DSP_WriteCount_Next',
     'DSP_WriteCount_Compute: loop increment and branch'),

    ('LABEL_035126', 'DSP_FlushAllSlots_Loop1',
     'DSP_FlushAllSlots: inner loop 1 body (flush slot state)'),
    ('LABEL_035156', 'DSP_FlushAllSlots_Loop1Next',
     'DSP_FlushAllSlots: inner loop 1 advance'),
    ('LABEL_03515E', 'DSP_FlushAllSlots_Loop2',
     'DSP_FlushAllSlots: inner loop 2 body'),
    ('LABEL_03516E', 'DSP_FlushAllSlots_Loop2Next',
     'DSP_FlushAllSlots: inner loop 2 advance'),
    ('LABEL_035176', 'DSP_FlushAllSlots_Loop3',
     'DSP_FlushAllSlots: inner loop 3 body'),
    ('LABEL_03519E', 'DSP_FlushAllSlots_Loop3Next',
     'DSP_FlushAllSlots: inner loop 3 advance'),
    ('LABEL_0351B3', 'DSP_FlushAllSlots_Data',
     'DSP_FlushAllSlots: data block after outer loop'),

    ('LABEL_03520B', 'DSP_ResetAlgoDefaults_Loop',
     'DSP_ResetAlgoDefaults: loop body writing default values'),

    ('LABEL_03523B', 'DSP_WriteAlgoBuffer_PathA',
     'DSP_WriteAlgoBuffer: path A (algo present)'),
    ('LABEL_035240', 'DSP_WriteAlgoBuffer_PathB',
     'DSP_WriteAlgoBuffer: path B (no algo)'),
    ('LABEL_035276', 'DSP_WriteAlgoBuffer_Loop',
     'DSP_WriteAlgoBuffer: inner write loop body'),
    ('LABEL_0352FA', 'DSP_WriteAlgoBuffer_LoopNext',
     'DSP_WriteAlgoBuffer: loop advance'),
    ('LABEL_035301', 'DSP_WriteAlgoBuffer_Epilogue',
     'DSP_WriteAlgoBuffer: epilogue'),
    ('LABEL_035321', 'DSP_WriteAlgoBuffer_Data',
     'DSP_WriteAlgoBuffer: data block after epilogue'),

    # 035xxx - DSP_Reinit_VoiceSlots branches
    ('LABEL_03536E', 'DSP_Reinit_VoiceSlots_Loop1',
     'DSP_Reinit_VoiceSlots: loop 1 body'),
    ('LABEL_03538B', 'DSP_Reinit_VoiceSlots_Loop1Next',
     'DSP_Reinit_VoiceSlots: loop 1 advance'),
    ('LABEL_0353C9', 'DSP_Reinit_VoiceSlots_Loop2',
     'DSP_Reinit_VoiceSlots: loop 2 body'),
    ('LABEL_0353D9', 'DSP_Reinit_VoiceSlots_Loop2A',
     'DSP_Reinit_VoiceSlots: loop 2 alternate path A'),
    ('LABEL_0353F4', 'DSP_Reinit_VoiceSlots_Loop2B',
     'DSP_Reinit_VoiceSlots: loop 2 alternate path B'),
    ('LABEL_0353FE', 'DSP_Reinit_VoiceSlots_Loop2Next',
     'DSP_Reinit_VoiceSlots: loop 2 advance'),
    ('LABEL_035418', 'DSP_Reinit_VoiceSlots_Loop3',
     'DSP_Reinit_VoiceSlots: loop 3 body'),
    ('LABEL_035427', 'DSP_Reinit_VoiceSlots_Loop3A',
     'DSP_Reinit_VoiceSlots: loop 3 path A'),
    ('LABEL_035432', 'DSP_Reinit_VoiceSlots_Loop3Next',
     'DSP_Reinit_VoiceSlots: loop 3 advance'),
    ('LABEL_035466', 'DSP_Reinit_VoiceSlots_OuterNext',
     'DSP_Reinit_VoiceSlots: outer loop advance'),
    ('LABEL_03547B', 'DSP_Reinit_VoiceSlots_DMAFlush',
     'DSP_Reinit_VoiceSlots: DMA flush epilogue'),

    # 035xxx - DSP_VoiceState_Dispatch
    ('LABEL_03549D', 'DSP_VoiceState_Dispatch_Scan',
     'DSP_VoiceState_Dispatch: inner scan loop start'),
    ('LABEL_0354CA', 'DSP_VoiceState_Dispatch_ActiveVoice',
     'DSP_VoiceState_Dispatch: active voice path (call dispatch fn)'),
    ('LABEL_035534', 'DSP_VoiceState_Dispatch_SubPathA',
     'DSP_VoiceState_Dispatch: sub-path A'),
    ('LABEL_03553F', 'DSP_VoiceState_Dispatch_SubPathB',
     'DSP_VoiceState_Dispatch: sub-path B'),
    ('LABEL_035551', 'DSP_VoiceState_Dispatch_LoopNext',
     'DSP_VoiceState_Dispatch: advance loop counter'),
    ('LABEL_03555B', 'DSP_VoiceState_Dispatch_Epilogue',
     'DSP_VoiceState_Dispatch: epilogue'),

    # 035xxx - Stub functions
    ('LABEL_035574', 'DSP_Stub_RetA',
     'Empty stub function A (ret only)'),
    ('LABEL_035575', 'DSP_Stub_RetB',
     'Empty stub function B (ret only)'),
    ('LABEL_035576', 'DSP_Stub_RetC',
     'Empty stub function C (ret only)'),

    # 035xxx - DSP_GetEffectRouting branch
    ('LABEL_03559B', 'DSP_GetEffectRouting_Path',
     'DSP_GetEffectRouting: alternate path reading 0x04137a'),

    # 035xxx - ToneGen_SetupPolyVoice branch
    ('LABEL_035609', 'ToneGen_SetupPolyVoice_Path',
     'ToneGen_SetupPolyVoice: voice allocation path'),

    # 035xxx - Voice_Poly_NoteOn inner (round-robin voice allocation)
    ('LABEL_0356E3', 'Voice_Poly_NoteOn_RoundRobin',
     'Voice_Poly_NoteOn: round-robin voice slot selection loop'),
    ('LABEL_035727', 'Voice_Poly_NoteOn_SlotSearch',
     'Voice_Poly_NoteOn: free slot search path'),
    ('LABEL_035749', 'Voice_Poly_NoteOn_SlotFound',
     'Voice_Poly_NoteOn: free slot found path'),
    ('LABEL_035799', 'Voice_Poly_NoteOn_ReleasePath',
     'Voice_Poly_NoteOn: release oldest active voice path'),
    ('LABEL_0357A6', 'Voice_Poly_NoteOn_ReleaseCheck',
     'Voice_Poly_NoteOn: check if slot can be released'),
    ('LABEL_0357D8', 'Voice_Poly_NoteOn_ReleaseNext',
     'Voice_Poly_NoteOn: advance release candidate'),
    ('LABEL_0357F9', 'Voice_Poly_NoteOn_ReleaseDone',
     'Voice_Poly_NoteOn: release voice done, assign slot'),
    ('LABEL_03580D', 'Voice_Poly_NoteOn_AssignSlot',
     'Voice_Poly_NoteOn: assign found/released slot'),
    ('LABEL_035816', 'Voice_Poly_NoteOn_Epilogue',
     'Voice_Poly_NoteOn: epilogue (ret)'),
    ('LABEL_03582E', 'Voice_Poly_NoteOn_Data',
     'Voice_Poly_NoteOn: 2-byte data padding after epilogue'),

    # 035xxx - DSP_RingBuf_Read empty/return paths
    ('LABEL_035855', 'DSP_RingBuf_Read_Empty',
     'DSP_RingBuf_Read: buffer empty path (return 0)'),
    ('LABEL_035858', 'DSP_RingBuf_Read_Return',
     'DSP_RingBuf_Read: read success, return byte'),
    ('LABEL_035859', 'DSP_RingBuf_Read_Data',
     'DSP_RingBuf_Read: 6-byte data block after routine'),

    # 035xxx - DSP_RingBuf_Skip
    ('LABEL_03586B', 'DSP_RingBuf_Skip_Loop',
     'DSP_RingBuf_Skip: loop body advancing read pointer'),
    ('LABEL_035874', 'DSP_RingBuf_Skip_Epilogue',
     'DSP_RingBuf_Skip: epilogue (ret)'),

    # 035xxx - Audio_CmdHandler_60_7F branches
    ('LABEL_0358AB', 'CmdHandler60_StreamSizeA',
     'Audio_CmdHandler_60_7F: stream size tracking path A'),
    ('LABEL_0358C1', 'CmdHandler60_StreamSizeB',
     'Audio_CmdHandler_60_7F: stream size tracking path B'),
    ('LABEL_0358CF', 'CmdHandler60_StreamSizeC',
     'Audio_CmdHandler_60_7F: stream size tracking path C'),

    # 035xxx - Shared enqueue-or-return path
    ('LABEL_03590A', 'DSP_EnqueueOrReturn',
     'Shared path: enqueue command to ring buffer or return on overflow'),

    # 035xxx - DSP_Cmd_LoadEffectPreset inner loops
    ('LABEL_035A0E', 'DSP_LoadEffPreset_Loop1',
     'DSP_Cmd_LoadEffectPreset: inner loop 1 body'),
    ('LABEL_035A24', 'DSP_LoadEffPreset_Loop1Next',
     'DSP_Cmd_LoadEffectPreset: inner loop 1 advance'),
    ('LABEL_035A31', 'DSP_LoadEffPreset_Loop2',
     'DSP_Cmd_LoadEffectPreset: inner loop 2 body'),
    ('LABEL_035A42', 'DSP_LoadEffPreset_Loop2Next',
     'DSP_Cmd_LoadEffectPreset: inner loop 2 advance'),
    ('LABEL_035A58', 'DSP_LoadEffPreset_Loop3',
     'DSP_Cmd_LoadEffectPreset: inner loop 3 body'),
    ('LABEL_035A60', 'DSP_LoadEffPreset_Loop3A',
     'DSP_Cmd_LoadEffectPreset: inner loop 3 path A'),
    ('LABEL_035A70', 'DSP_LoadEffPreset_Loop3Next',
     'DSP_Cmd_LoadEffectPreset: inner loop 3 advance'),
    ('LABEL_035A79', 'DSP_LoadEffPreset_Epilogue',
     'DSP_Cmd_LoadEffectPreset: epilogue'),

    # 035xxx - DSP_RingBuf_ReadAndCompare inner loop
    ('LABEL_035A8B', 'DSP_RingBuf_Compare_Loop',
     'DSP_RingBuf_ReadAndCompare: inner loop body'),
    ('LABEL_035A9B', 'DSP_RingBuf_Compare_MatchPath',
     'DSP_RingBuf_ReadAndCompare: match path'),
    ('LABEL_035AA6', 'DSP_RingBuf_Compare_MismatchPath',
     'DSP_RingBuf_ReadAndCompare: mismatch path'),
    ('LABEL_035ABC', 'DSP_RingBuf_Compare_LoopNext',
     'DSP_RingBuf_ReadAndCompare: loop advance'),
    ('LABEL_035AC2', 'DSP_RingBuf_Compare_FoundPath',
     'DSP_RingBuf_ReadAndCompare: found matching sequence path'),
    ('LABEL_035AC4', 'DSP_RingBuf_Compare_Epilogue',
     'DSP_RingBuf_ReadAndCompare: epilogue'),

    # 035xxx - Audio_Process_DSP message size check
    ('LABEL_035B1B', 'Audio_Process_DSP_MsgSizeCheck',
     'Audio_Process_DSP: message size boundary check branch'),

    # 035xxx - DSP_Cmd2B_AlgoSelect continuation
    ('LABEL_035BD6', 'DSP_Cmd2B_AlgoSelect_Continue',
     'DSP_Cmd2B_AlgoSelect: post-call continuation path'),

    # 035xxx - DSP_Cmd2B_SkipAndContinue skip path
    ('LABEL_035D6F', 'DSP_Cmd2B_SkipPath',
     'DSP_Cmd2B_SkipAndContinue: skip path, advance read position'),

    # 035xxx - DSP_CmdHandler_2C dispatch and sub-commands
    ('LABEL_035DBC', 'CmdHandler2C_JumpDispatch',
     'DSP_CmdHandler_2C: jump table dispatch entry'),
    ('LABEL_035DD2', 'CmdHandler2C_TableData',
     'DSP_CmdHandler_2C: jump table data block'),
    ('LABEL_035E7B', 'CmdHandler2C_SubCmd0',
     'DSP_CmdHandler_2C: sub-command 0 handler'),
    ('LABEL_035E84', 'CmdHandler2C_SubCmd1',
     'DSP_CmdHandler_2C: sub-command 1 handler'),
    ('LABEL_035ECE', 'CmdHandler2C_SubCmd2',
     'DSP_CmdHandler_2C: sub-command 2 handler'),
    ('LABEL_035ED7', 'CmdHandler2C_SubCmd3',
     'DSP_CmdHandler_2C: sub-command 3 handler'),
    ('LABEL_035EFA', 'CmdHandler2C_SubCmd4',
     'DSP_CmdHandler_2C: sub-command 4 handler'),
    ('LABEL_035F13', 'CmdHandler2C_SubCmd5',
     'DSP_CmdHandler_2C: sub-command 5 handler'),
    ('LABEL_035F1A', 'CmdHandler2C_SubCmd6',
     'DSP_CmdHandler_2C: sub-command 6 handler'),
    ('LABEL_035F29', 'CmdHandler2C_Epilogue',
     'DSP_CmdHandler_2C: epilogue path'),

    # 035xxx - DSP_CmdHandler_2D sub-paths
    ('LABEL_035F66', 'CmdHandler2D_PathA',
     'DSP_CmdHandler_2D: sub-path A'),
    ('LABEL_035FC3', 'CmdHandler2D_PathB',
     'DSP_CmdHandler_2D: sub-path B'),
    ('LABEL_035FCB', 'CmdHandler2D_PathC',
     'DSP_CmdHandler_2D: sub-path C'),
    ('LABEL_035FD3', 'CmdHandler2D_PathD',
     'DSP_CmdHandler_2D: sub-path D'),

    # -------------------------------------------------------------------------
    # 035xxx - CmdHandler_2D / CmdHandler_2C continuation branches
    # -------------------------------------------------------------------------
    ('LABEL_036001', 'CmdHandler2D_MsgSizeMatch',
     'CmdHandler_2D: body after ring-buf size match (3rd case)'),
    ('LABEL_036009', 'CmdHandler2D_EnqueueOrReturn',
     'CmdHandler_2D: enqueue cmd to ring buffer or early return'),
    ('LABEL_036025', 'CmdHandler2D_QueuedPath',
     'CmdHandler_2D: queued-command path, advance read ptr'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP algo preset / slot-state / EFF slot buffer helpers
    # -------------------------------------------------------------------------
    ('LABEL_036064', 'DSP_WriteAlgoInitPreset_PresetPath',
     'DSP_WriteAlgoInitPreset: preset present, write init data'),
    ('LABEL_036079', 'DSP_WriteAlgoInitPreset_DefaultPath',
     'DSP_WriteAlgoInitPreset: no preset, use default algo init'),
    ('LABEL_036088', 'DSP_WriteAlgoInitPreset_Epilogue',
     'DSP_WriteAlgoInitPreset: common epilogue'),
    ('LABEL_036098', 'DSP_ApplyAlgoForVoiceType_TypeF',
     'DSP_ApplyAlgoForVoiceType: algo type 0xF / 0x35 path'),
    ('LABEL_03611D', 'DSP_ApplyAlgoForVoiceType_Data',
     'DSP_ApplyAlgoForVoiceType: 1-byte constant data block'),
    ('LABEL_03613B', 'DSP_SlotState_DisplayRestore_ActivePath',
     'DSP_SlotState_DisplayRestore: active slot path, copy state'),
    ('LABEL_036152', 'DSP_SlotState_DisplayRestore_Epilogue',
     'DSP_SlotState_DisplayRestore: epilogue (pop + ret)'),
    ('LABEL_036177', 'DSP_ApplyConfig_ActivePath',
     'DSP_ApplyConfig: voice active, write config params'),
    ('LABEL_03617D', 'DSP_ApplyConfig_InactivePath',
     'DSP_ApplyConfig: voice inactive, skip param write'),
    ('LABEL_0361A0', 'DSP_ApplyConfig_BufSelectA',
     'DSP_ApplyConfig: buffer-select branch A'),
    ('LABEL_0361A8', 'DSP_ApplyConfig_BufSelectB',
     'DSP_ApplyConfig: buffer-select branch B'),
    ('LABEL_0361BA', 'DSP_ApplyConfig_Epilogue',
     'DSP_ApplyConfig: epilogue (pop + ret)'),
    ('LABEL_0361EF', 'EFF_GetSlotBuffer_NoSlot',
     'EFF_GetSlotBuffer: no matching slot found, return NULL'),
    ('LABEL_0361FF', 'EFF_GetSlotBuffer_LoopBody',
     'EFF_GetSlotBuffer: inner loop body scanning EFF slots'),
    ('LABEL_036204', 'EFF_GetSlotBuffer_Epilogue',
     'EFF_GetSlotBuffer: matched slot epilogue, return pointer'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP state table constant data block
    # -------------------------------------------------------------------------
    ('LABEL_036205', 'DSP_StateTable_DefaultData',
     'Default DSP state table values (written by DMA preset load)'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP command queue / task wake helper
    # -------------------------------------------------------------------------
    ('LABEL_036319', 'DSP_WaitForTaskSlot_Loop',
     'Poll task queue until slot available (timeout via LABEL_0200C0)'),
    ('LABEL_036325', 'DSP_WaitForTaskSlot_Epilogue',
     'DSP task slot wait: success epilogue (pop iz + ret)'),
    ('LABEL_036327', 'DSP_WaitForTaskSlot_Data',
     '4-byte data block after DSP task wait routine'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP2 SPI bit-bang timing NOP chains
    # (DSP2_SPI_ClockPulseHigh body: NOP delay steps 1..36)
    # -------------------------------------------------------------------------
    ('LABEL_03640F', 'DSP2_ClkHigh_Nop01',  'SPI clock-high NOP delay step 1'),
    ('LABEL_036412', 'DSP2_ClkHigh_Nop02',  'SPI clock-high NOP delay step 2'),
    ('LABEL_036415', 'DSP2_ClkHigh_Nop03',  'SPI clock-high NOP delay step 3'),
    ('LABEL_036418', 'DSP2_ClkHigh_Nop04',  'SPI clock-high NOP delay step 4'),
    ('LABEL_03641B', 'DSP2_ClkHigh_Nop05',  'SPI clock-high NOP delay step 5'),
    ('LABEL_03641E', 'DSP2_ClkHigh_Nop06',  'SPI clock-high NOP delay step 6'),
    ('LABEL_036421', 'DSP2_ClkHigh_Nop07',  'SPI clock-high NOP delay step 7'),
    ('LABEL_036424', 'DSP2_ClkHigh_Nop08',  'SPI clock-high NOP delay step 8'),
    ('LABEL_036427', 'DSP2_ClkHigh_Nop09',  'SPI clock-high NOP delay step 9'),
    ('LABEL_03642A', 'DSP2_ClkHigh_Nop10',  'SPI clock-high NOP delay step 10'),
    ('LABEL_03642D', 'DSP2_ClkHigh_Nop11',  'SPI clock-high NOP delay step 11'),
    ('LABEL_036430', 'DSP2_ClkHigh_Nop12',  'SPI clock-high NOP delay step 12'),
    ('LABEL_036433', 'DSP2_ClkHigh_Nop13',  'SPI clock-high NOP delay step 13'),
    ('LABEL_036436', 'DSP2_ClkHigh_Nop14',  'SPI clock-high NOP delay step 14'),
    ('LABEL_036439', 'DSP2_ClkHigh_Nop15',  'SPI clock-high NOP delay step 15'),
    ('LABEL_03643C', 'DSP2_ClkHigh_Nop16',  'SPI clock-high NOP delay step 16'),
    ('LABEL_03643F', 'DSP2_ClkHigh_Nop17',  'SPI clock-high NOP delay step 17'),
    ('LABEL_036442', 'DSP2_ClkHigh_Nop18',  'SPI clock-high NOP delay step 18'),
    ('LABEL_036445', 'DSP2_ClkHigh_Nop19',  'SPI clock-high NOP delay step 19'),
    ('LABEL_03644B', 'DSP2_ClkHigh_Nop20',  'SPI clock-high NOP delay step 20'),
    ('LABEL_036451', 'DSP2_ClkHigh_Nop21',  'SPI clock-high NOP delay step 21'),
    ('LABEL_036454', 'DSP2_ClkHigh_Nop22',  'SPI clock-high NOP delay step 22'),
    ('LABEL_036457', 'DSP2_ClkHigh_Nop23',  'SPI clock-high NOP delay step 23'),
    ('LABEL_03645A', 'DSP2_ClkHigh_Nop24',  'SPI clock-high NOP delay step 24'),
    ('LABEL_03645D', 'DSP2_ClkHigh_Nop25',  'SPI clock-high NOP delay step 25'),
    ('LABEL_036460', 'DSP2_ClkHigh_Nop26',  'SPI clock-high NOP delay step 26'),
    ('LABEL_036463', 'DSP2_ClkHigh_Nop27',  'SPI clock-high NOP delay step 27'),
    ('LABEL_036466', 'DSP2_ClkHigh_Nop28',  'SPI clock-high NOP delay step 28'),
    ('LABEL_036469', 'DSP2_ClkHigh_Nop29',  'SPI clock-high NOP delay step 29'),
    ('LABEL_03646C', 'DSP2_ClkHigh_Nop30',  'SPI clock-high NOP delay step 30'),
    ('LABEL_03646F', 'DSP2_ClkHigh_Nop31',  'SPI clock-high NOP delay step 31'),
    ('LABEL_036472', 'DSP2_ClkHigh_Nop32',  'SPI clock-high NOP delay step 32'),
    ('LABEL_036475', 'DSP2_ClkHigh_Nop33',  'SPI clock-high NOP delay step 33'),
    ('LABEL_036478', 'DSP2_ClkHigh_Nop34',  'SPI clock-high NOP delay step 34'),
    ('LABEL_03647B', 'DSP2_ClkHigh_Nop35',  'SPI clock-high NOP delay step 35'),
    ('LABEL_03647E', 'DSP2_ClkHigh_Nop36',  'SPI clock-high NOP delay step 36'),
    ('LABEL_036484', 'DSP2_ClkHigh_Nop37',  'SPI clock-high NOP delay step 37'),
    ('LABEL_036487', 'DSP2_ClkHigh_Nop38',  'SPI clock-high NOP delay step 38'),
    ('LABEL_03648A', 'DSP2_ClkHigh_Nop39',  'SPI clock-high NOP delay step 39'),
    ('LABEL_03648D', 'DSP2_ClkHigh_Nop40',  'SPI clock-high NOP delay step 40'),
    ('LABEL_036490', 'DSP2_ClkHigh_Nop41',  'SPI clock-high NOP delay step 41'),
    ('LABEL_036493', 'DSP2_ClkHigh_Nop42',  'SPI clock-high NOP delay step 42'),
    ('LABEL_036496', 'DSP2_ClkHigh_Nop43',  'SPI clock-high NOP delay step 43'),
    ('LABEL_036499', 'DSP2_ClkHigh_Nop44',  'SPI clock-high NOP delay step 44'),
    ('LABEL_03649C', 'DSP2_ClkHigh_Nop45',  'SPI clock-high NOP delay step 45'),
    ('LABEL_03649F', 'DSP2_ClkHigh_Nop46',  'SPI clock-high NOP delay step 46'),
    ('LABEL_0364A2', 'DSP2_ClkHigh_Nop47',  'SPI clock-high NOP delay step 47'),
    ('LABEL_0364A5', 'DSP2_ClkHigh_Nop48',  'SPI clock-high NOP delay step 48'),
    ('LABEL_0364A8', 'DSP2_ClkHigh_Nop49',  'SPI clock-high NOP delay step 49'),
    ('LABEL_0364AB', 'DSP2_ClkHigh_Nop50',  'SPI clock-high NOP delay step 50'),
    ('LABEL_0364AE', 'DSP2_ClkHigh_Nop51',  'SPI clock-high NOP delay step 51'),
    ('LABEL_0364B1', 'DSP2_ClkHigh_Nop52',  'SPI clock-high NOP delay step 52'),
    ('LABEL_0364B4', 'DSP2_ClkHigh_Nop53',  'SPI clock-high NOP delay step 53'),
    ('LABEL_0364B7', 'DSP2_ClkHigh_Nop54',  'SPI clock-high NOP delay step 54'),
    ('LABEL_0364BA', 'DSP2_ClkHigh_Nop55',  'SPI clock-high NOP delay step 55 (last; jp to debug log)'),

    # DSP2_SPI_BusIdle body: NOP delay steps for clock-low (1..18) then clock-raise (19..36) then data-set (37..56)
    ('LABEL_0364CC', 'DSP2_BusIdle_Nop01',   'SPI bus-idle NOP delay step 1'),
    ('LABEL_0364CF', 'DSP2_BusIdle_Nop02',   'SPI bus-idle NOP delay step 2'),
    ('LABEL_0364D2', 'DSP2_BusIdle_Nop03',   'SPI bus-idle NOP delay step 3'),
    ('LABEL_0364D5', 'DSP2_BusIdle_Nop04',   'SPI bus-idle NOP delay step 4'),
    ('LABEL_0364D8', 'DSP2_BusIdle_Nop05',   'SPI bus-idle NOP delay step 5'),
    ('LABEL_0364DB', 'DSP2_BusIdle_Nop06',   'SPI bus-idle NOP delay step 6'),
    ('LABEL_0364DE', 'DSP2_BusIdle_Nop07',   'SPI bus-idle NOP delay step 7'),
    ('LABEL_0364E1', 'DSP2_BusIdle_Nop08',   'SPI bus-idle NOP delay step 8'),
    ('LABEL_0364E4', 'DSP2_BusIdle_Nop09',   'SPI bus-idle NOP delay step 9'),
    ('LABEL_0364E7', 'DSP2_BusIdle_Nop10',   'SPI bus-idle NOP delay step 10'),
    ('LABEL_0364EA', 'DSP2_BusIdle_Nop11',   'SPI bus-idle NOP delay step 11'),
    ('LABEL_0364ED', 'DSP2_BusIdle_Nop12',   'SPI bus-idle NOP delay step 12'),
    ('LABEL_0364F0', 'DSP2_BusIdle_Nop13',   'SPI bus-idle NOP delay step 13'),
    ('LABEL_0364F3', 'DSP2_BusIdle_Nop14',   'SPI bus-idle NOP delay step 14'),
    ('LABEL_0364F6', 'DSP2_BusIdle_Nop15',   'SPI bus-idle NOP delay step 15'),
    ('LABEL_0364F9', 'DSP2_BusIdle_Nop16',   'SPI bus-idle NOP delay step 16'),
    ('LABEL_0364FC', 'DSP2_BusIdle_Nop17',   'SPI bus-idle NOP delay step 17'),
    ('LABEL_0364FF', 'DSP2_BusIdle_Nop18',   'SPI bus-idle NOP delay step 18'),
    # clock raised (set_dd8 2, 0x3C) then more NOPs
    ('LABEL_036502', 'DSP2_BusIdle_Nop19',   'SPI bus-idle NOP delay step 19 (after clk raise)'),
    ('LABEL_036508', 'DSP2_BusIdle_Nop20',   'SPI bus-idle NOP delay step 20'),
    ('LABEL_03650B', 'DSP2_BusIdle_Nop21',   'SPI bus-idle NOP delay step 21'),
    ('LABEL_03650E', 'DSP2_BusIdle_Nop22',   'SPI bus-idle NOP delay step 22'),
    ('LABEL_036511', 'DSP2_BusIdle_Nop23',   'SPI bus-idle NOP delay step 23'),
    ('LABEL_036514', 'DSP2_BusIdle_Nop24',   'SPI bus-idle NOP delay step 24'),
    ('LABEL_036517', 'DSP2_BusIdle_Nop25',   'SPI bus-idle NOP delay step 25'),
    ('LABEL_03651A', 'DSP2_BusIdle_Nop26',   'SPI bus-idle NOP delay step 26'),
    ('LABEL_03651D', 'DSP2_BusIdle_Nop27',   'SPI bus-idle NOP delay step 27'),
    ('LABEL_036520', 'DSP2_BusIdle_Nop28',   'SPI bus-idle NOP delay step 28'),
    ('LABEL_036523', 'DSP2_BusIdle_Nop29',   'SPI bus-idle NOP delay step 29'),
    ('LABEL_036526', 'DSP2_BusIdle_Nop30',   'SPI bus-idle NOP delay step 30'),
    ('LABEL_036529', 'DSP2_BusIdle_Nop31',   'SPI bus-idle NOP delay step 31'),
    ('LABEL_03652C', 'DSP2_BusIdle_Nop32',   'SPI bus-idle NOP delay step 32'),
    ('LABEL_03652F', 'DSP2_BusIdle_Nop33',   'SPI bus-idle NOP delay step 33'),
    ('LABEL_036532', 'DSP2_BusIdle_Nop34',   'SPI bus-idle NOP delay step 34'),
    ('LABEL_036535', 'DSP2_BusIdle_Nop35',   'SPI bus-idle NOP delay step 35'),
    ('LABEL_036538', 'DSP2_BusIdle_Nop36',   'SPI bus-idle NOP delay step 36'),
    # data pin set (set_dd8 0, 0x3C) then more NOPs
    ('LABEL_03653B', 'DSP2_BusIdle_Nop37',   'SPI bus-idle NOP delay step 37'),
    ('LABEL_03653E', 'DSP2_BusIdle_Nop38',   'SPI bus-idle NOP delay step 38 (after data set)'),
    ('LABEL_036544', 'DSP2_BusIdle_Nop39',   'SPI bus-idle NOP delay step 39'),
    ('LABEL_036547', 'DSP2_BusIdle_Nop40',   'SPI bus-idle NOP delay step 40'),
    ('LABEL_03654A', 'DSP2_BusIdle_Nop41',   'SPI bus-idle NOP delay step 41'),
    ('LABEL_03654D', 'DSP2_BusIdle_Nop42',   'SPI bus-idle NOP delay step 42'),
    ('LABEL_036550', 'DSP2_BusIdle_Nop43',   'SPI bus-idle NOP delay step 43'),
    ('LABEL_036553', 'DSP2_BusIdle_Nop44',   'SPI bus-idle NOP delay step 44'),
    ('LABEL_036556', 'DSP2_BusIdle_Nop45',   'SPI bus-idle NOP delay step 45'),
    ('LABEL_036559', 'DSP2_BusIdle_Nop46',   'SPI bus-idle NOP delay step 46'),
    ('LABEL_03655C', 'DSP2_BusIdle_Nop47',   'SPI bus-idle NOP delay step 47'),
    ('LABEL_03655F', 'DSP2_BusIdle_Nop48',   'SPI bus-idle NOP delay step 48'),
    ('LABEL_036562', 'DSP2_BusIdle_Nop49',   'SPI bus-idle NOP delay step 49'),
    ('LABEL_036565', 'DSP2_BusIdle_Nop50',   'SPI bus-idle NOP delay step 50'),
    ('LABEL_036568', 'DSP2_BusIdle_Nop51',   'SPI bus-idle NOP delay step 51'),
    ('LABEL_03656B', 'DSP2_BusIdle_Nop52',   'SPI bus-idle NOP delay step 52'),
    ('LABEL_03656E', 'DSP2_BusIdle_Nop53',   'SPI bus-idle NOP delay step 53'),
    ('LABEL_036571', 'DSP2_BusIdle_Nop54',   'SPI bus-idle NOP delay step 54'),
    ('LABEL_036574', 'DSP2_BusIdle_Nop55',   'SPI bus-idle NOP delay step 55'),
    ('LABEL_036577', 'DSP2_BusIdle_Nop56',   'SPI bus-idle NOP delay step 56'),
    ('LABEL_03657A', 'DSP2_BusIdle_Nop57',   'SPI bus-idle NOP delay step 57'),
    ('LABEL_03657D', 'DSP2_BusIdle_Nop58',   'SPI bus-idle NOP delay step 58'),
    ('LABEL_036580', 'DSP2_BusIdle_Nop59',   'SPI bus-idle NOP delay step 59'),
    ('LABEL_036583', 'DSP2_BusIdle_Nop60',   'SPI bus-idle NOP delay step 60'),
    ('LABEL_036586', 'DSP2_BusIdle_Nop61',   'SPI bus-idle NOP delay step 61'),
    ('LABEL_036589', 'DSP2_BusIdle_Nop62',   'SPI bus-idle NOP delay step 62'),
    ('LABEL_03658C', 'DSP2_BusIdle_Nop63',   'SPI bus-idle NOP delay step 63'),
    ('LABEL_03658F', 'DSP2_BusIdle_Nop64',   'SPI bus-idle NOP delay step 64'),
    ('LABEL_036592', 'DSP2_BusIdle_Nop65',   'SPI bus-idle NOP delay step 65'),
    ('LABEL_036595', 'DSP2_BusIdle_Nop66',   'SPI bus-idle NOP delay step 66'),
    ('LABEL_036598', 'DSP2_BusIdle_Nop67',   'SPI bus-idle NOP delay step 67'),
    ('LABEL_03659B', 'DSP2_BusIdle_Nop68',   'SPI bus-idle NOP delay step 68'),
    ('LABEL_03659E', 'DSP2_BusIdle_Nop69',   'SPI bus-idle NOP delay step 69'),
    ('LABEL_0365A1', 'DSP2_BusIdle_Nop70',   'SPI bus-idle NOP delay step 70'),
    ('LABEL_0365A4', 'DSP2_BusIdle_Nop71',   'SPI bus-idle NOP delay step 71'),
    ('LABEL_0365A7', 'DSP2_BusIdle_Nop72',   'SPI bus-idle NOP delay step 72'),
    ('LABEL_0365AA', 'DSP2_BusIdle_Nop73',   'SPI bus-idle NOP delay step 73'),
    ('LABEL_0365AD', 'DSP2_BusIdle_Nop74',   'SPI bus-idle NOP delay step 74'),
    ('LABEL_0365B0', 'DSP2_BusIdle_Nop75',   'SPI bus-idle NOP delay step 75'),
    ('LABEL_0365B3', 'DSP2_BusIdle_Nop76',   'SPI bus-idle NOP delay step 76'),
    ('LABEL_0365B6', 'DSP2_BusIdle_Nop77',   'SPI bus-idle NOP delay step 77'),
    ('LABEL_0365B9', 'DSP2_BusIdle_Nop78',   'SPI bus-idle NOP delay step 78'),
    ('LABEL_0365BC', 'DSP2_BusIdle_Nop79',   'SPI bus-idle NOP delay step 79'),
    ('LABEL_0365BF', 'DSP2_BusIdle_Nop80',   'SPI bus-idle NOP delay step 80'),
    ('LABEL_0365C2', 'DSP2_BusIdle_Nop81',   'SPI bus-idle NOP delay step 81'),
    ('LABEL_0365C5', 'DSP2_BusIdle_Nop82',   'SPI bus-idle NOP delay step 82'),
    ('LABEL_0365C8', 'DSP2_BusIdle_Nop83',   'SPI bus-idle NOP delay step 83'),
    ('LABEL_0365CB', 'DSP2_BusIdle_Nop84',   'SPI bus-idle NOP delay step 84'),
    ('LABEL_0365CE', 'DSP2_BusIdle_Nop85',   'SPI bus-idle NOP delay step 85'),
    ('LABEL_0365D1', 'DSP2_BusIdle_Nop86',   'SPI bus-idle NOP delay step 86'),
    ('LABEL_0365D4', 'DSP2_BusIdle_Nop87',   'SPI bus-idle NOP delay step 87'),
    ('LABEL_0365D7', 'DSP2_BusIdle_Nop88',   'SPI bus-idle NOP delay step 88'),
    ('LABEL_0365DA', 'DSP2_BusIdle_Nop89',   'SPI bus-idle NOP delay step 89'),
    ('LABEL_0365DD', 'DSP2_BusIdle_Nop90',   'SPI bus-idle NOP delay step 90'),
    ('LABEL_0365E0', 'DSP2_BusIdle_Nop91',   'SPI bus-idle NOP delay step 91'),
    ('LABEL_0365E3', 'DSP2_BusIdle_Nop92',   'SPI bus-idle NOP delay step 92'),
    ('LABEL_0365E6', 'DSP2_BusIdle_Nop93',   'SPI bus-idle NOP delay step 93'),
    ('LABEL_0365E9', 'DSP2_BusIdle_Nop94',   'SPI bus-idle NOP delay step 94'),
    ('LABEL_0365EC', 'DSP2_BusIdle_Nop95',   'SPI bus-idle NOP delay step 95'),
    ('LABEL_0365EF', 'DSP2_BusIdle_Nop96',   'SPI bus-idle NOP delay step 96'),
    ('LABEL_0365F2', 'DSP2_BusIdle_Nop97',   'SPI bus-idle NOP delay step 97'),
    ('LABEL_0365F5', 'DSP2_BusIdle_Nop98',   'SPI bus-idle NOP delay step 98'),
    ('LABEL_0365F8', 'DSP2_BusIdle_Nop99',   'SPI bus-idle NOP delay step 99'),
    ('LABEL_0365FB', 'DSP2_BusIdle_Nop100',  'SPI bus-idle NOP delay step 100'),
    ('LABEL_0365FE', 'DSP2_BusIdle_Nop101',  'SPI bus-idle NOP delay step 101'),
    ('LABEL_036601', 'DSP2_BusIdle_Nop102',  'SPI bus-idle NOP delay step 102'),
    ('LABEL_036604', 'DSP2_BusIdle_Nop103',  'SPI bus-idle NOP delay step 103'),
    ('LABEL_036607', 'DSP2_BusIdle_Nop104',  'SPI bus-idle NOP delay step 104'),
    ('LABEL_03660A', 'DSP2_BusIdle_Nop105',  'SPI bus-idle NOP delay step 105'),
    ('LABEL_03660D', 'DSP2_BusIdle_Nop106',  'SPI bus-idle NOP delay step 106'),
    ('LABEL_036610', 'DSP2_BusIdle_Nop107',  'SPI bus-idle NOP delay step 107'),
    ('LABEL_036613', 'DSP2_BusIdle_Nop108',  'SPI bus-idle NOP delay step 108'),
    ('LABEL_036616', 'DSP2_BusIdle_Nop109',  'SPI bus-idle NOP delay step 109'),
    ('LABEL_036619', 'DSP2_BusIdle_Nop110',  'SPI bus-idle NOP delay step 110'),
    ('LABEL_03661C', 'DSP2_BusIdle_Nop111',  'SPI bus-idle NOP delay step 111'),
    ('LABEL_03661F', 'DSP2_BusIdle_Nop112',  'SPI bus-idle NOP delay step 112'),
    ('LABEL_036622', 'DSP2_BusIdle_Nop113',  'SPI bus-idle NOP delay step 113'),
    ('LABEL_036625', 'DSP2_BusIdle_Nop114',  'SPI bus-idle NOP delay step 114'),
    ('LABEL_036628', 'DSP2_BusIdle_Nop115',  'SPI bus-idle NOP delay step 115'),
    ('LABEL_03662B', 'DSP2_BusIdle_Nop116',  'SPI bus-idle NOP delay step 116'),
    ('LABEL_03662E', 'DSP2_BusIdle_Nop117',  'SPI bus-idle NOP delay step 117'),
    ('LABEL_036631', 'DSP2_BusIdle_Nop118',  'SPI bus-idle NOP delay step 118'),
    ('LABEL_036634', 'DSP2_BusIdle_Nop119',  'SPI bus-idle NOP delay step 119'),
    ('LABEL_036637', 'DSP2_BusIdle_Nop120',  'SPI bus-idle NOP delay step 120'),
    ('LABEL_03663A', 'DSP2_BusIdle_Nop121',  'SPI bus-idle NOP delay step 121'),
    ('LABEL_03663D', 'DSP2_BusIdle_Nop122',  'SPI bus-idle NOP delay step 122'),
    ('LABEL_036640', 'DSP2_BusIdle_Nop123',  'SPI bus-idle NOP delay step 123'),
    ('LABEL_036643', 'DSP2_BusIdle_Nop124',  'SPI bus-idle NOP delay step 124'),
    ('LABEL_036646', 'DSP2_BusIdle_Nop125',  'SPI bus-idle NOP delay step 125'),
    ('LABEL_036649', 'DSP2_BusIdle_Nop126',  'SPI bus-idle NOP delay step 126'),
    ('LABEL_03664C', 'DSP2_BusIdle_Nop127',  'SPI bus-idle NOP delay step 127'),
    ('LABEL_03664F', 'DSP2_BusIdle_Nop128',  'SPI bus-idle NOP delay step 128'),
    ('LABEL_036652', 'DSP2_BusIdle_Nop129',  'SPI bus-idle NOP delay step 129'),
    ('LABEL_036655', 'DSP2_BusIdle_Nop130',  'SPI bus-idle NOP delay step 130'),
    ('LABEL_036658', 'DSP2_BusIdle_Nop131',  'SPI bus-idle NOP delay step 131'),
    ('LABEL_03665B', 'DSP2_BusIdle_Nop132',  'SPI bus-idle NOP delay step 132'),
    ('LABEL_03665E', 'DSP2_BusIdle_Nop133',  'SPI bus-idle NOP delay step 133'),
    ('LABEL_036661', 'DSP2_BusIdle_Nop134',  'SPI bus-idle NOP delay step 134 (last; jp to debug log)'),

    # -------------------------------------------------------------------------
    # DSP2_Send_Command bit-bang loop control and NOP chains
    # -------------------------------------------------------------------------
    ('LABEL_036696', 'DSP2_SendCmd_BitLoop',
     'DSP2_Send_Command: bit-bang loop body, test and set/clear MOSI'),
    ('LABEL_0366A1', 'DSP2_SendCmd_BitClear',
     'DSP2_Send_Command: MOSI bit = 0 path (res data pin)'),
    ('LABEL_0366A4', 'DSP2_SendCmd_BitSet_Done',
     'DSP2_Send_Command: after MOSI write, fall into clock-high NOPs'),
    ('LABEL_0366A6', 'DSP2_SendCmd_ClkHigh_Nop01',
     'DSP2_Send_Command: clock-high NOP step 1 (after MOSI set, before shift)'),
    # Clock-high NOP delay steps 2..16 (0x0366B0 through 0x0366DD)
    ('LABEL_0366B0', 'DSP2_SendCmd_ClkHigh_Nop02',  'DSP2_Send_Command: clock-high NOP step 2'),
    ('LABEL_0366B3', 'DSP2_SendCmd_ClkHigh_Nop03',  'DSP2_Send_Command: clock-high NOP step 3'),
    ('LABEL_0366B6', 'DSP2_SendCmd_ClkHigh_Nop04',  'DSP2_Send_Command: clock-high NOP step 4'),
    ('LABEL_0366B9', 'DSP2_SendCmd_ClkHigh_Nop05',  'DSP2_Send_Command: clock-high NOP step 5'),
    ('LABEL_0366BC', 'DSP2_SendCmd_ClkHigh_Nop06',  'DSP2_Send_Command: clock-high NOP step 6'),
    ('LABEL_0366BF', 'DSP2_SendCmd_ClkHigh_Nop07',  'DSP2_Send_Command: clock-high NOP step 7'),
    ('LABEL_0366C2', 'DSP2_SendCmd_ClkHigh_Nop08',  'DSP2_Send_Command: clock-high NOP step 8'),
    ('LABEL_0366C5', 'DSP2_SendCmd_ClkHigh_Nop09',  'DSP2_Send_Command: clock-high NOP step 9'),
    ('LABEL_0366C8', 'DSP2_SendCmd_ClkHigh_Nop10',  'DSP2_Send_Command: clock-high NOP step 10'),
    ('LABEL_0366CB', 'DSP2_SendCmd_ClkHigh_Nop11',  'DSP2_Send_Command: clock-high NOP step 11'),
    ('LABEL_0366CE', 'DSP2_SendCmd_ClkHigh_Nop12',  'DSP2_Send_Command: clock-high NOP step 12'),
    ('LABEL_0366D1', 'DSP2_SendCmd_ClkHigh_Nop13',  'DSP2_Send_Command: clock-high NOP step 13'),
    ('LABEL_0366D4', 'DSP2_SendCmd_ClkHigh_Nop14',  'DSP2_Send_Command: clock-high NOP step 14'),
    ('LABEL_0366D7', 'DSP2_SendCmd_ClkHigh_Nop15',  'DSP2_Send_Command: clock-high NOP step 15'),
    ('LABEL_0366DA', 'DSP2_SendCmd_ClkHigh_Nop16',  'DSP2_Send_Command: clock-high NOP step 16'),
    # Clock goes low (res_dd8 2) then clock-low NOP delay steps
    ('LABEL_0366DD', 'DSP2_SendCmd_ClkLow_Nop01',   'DSP2_Send_Command: clock-low NOP step 1 (after clk deassert)'),
    ('LABEL_0366E3', 'DSP2_SendCmd_ClkLow_Nop02',   'DSP2_Send_Command: clock-low NOP step 2'),
    ('LABEL_0366E6', 'DSP2_SendCmd_ClkLow_Nop03',   'DSP2_Send_Command: clock-low NOP step 3'),
    ('LABEL_0366E9', 'DSP2_SendCmd_ClkLow_Nop04',   'DSP2_Send_Command: clock-low NOP step 4'),
    ('LABEL_0366EC', 'DSP2_SendCmd_ClkLow_Nop05',   'DSP2_Send_Command: clock-low NOP step 5'),
    ('LABEL_0366EF', 'DSP2_SendCmd_ClkLow_Nop06',   'DSP2_Send_Command: clock-low NOP step 6'),
    ('LABEL_0366F2', 'DSP2_SendCmd_ClkLow_Nop07',   'DSP2_Send_Command: clock-low NOP step 7'),
    ('LABEL_0366F5', 'DSP2_SendCmd_ClkLow_Nop08',   'DSP2_Send_Command: clock-low NOP step 8'),
    ('LABEL_0366F8', 'DSP2_SendCmd_ClkLow_Nop09',   'DSP2_Send_Command: clock-low NOP step 9'),
    ('LABEL_0366FB', 'DSP2_SendCmd_ClkLow_Nop10',   'DSP2_Send_Command: clock-low NOP step 10'),
    ('LABEL_0366FE', 'DSP2_SendCmd_ClkLow_Nop11',   'DSP2_Send_Command: clock-low NOP step 11'),
    ('LABEL_036701', 'DSP2_SendCmd_ClkLow_Nop12',   'DSP2_Send_Command: clock-low NOP step 12'),
    ('LABEL_036704', 'DSP2_SendCmd_ClkLow_Nop13',   'DSP2_Send_Command: clock-low NOP step 13'),
    ('LABEL_036707', 'DSP2_SendCmd_ClkLow_Nop14',   'DSP2_Send_Command: clock-low NOP step 14'),
    ('LABEL_03670A', 'DSP2_SendCmd_ClkLow_Nop15',   'DSP2_Send_Command: clock-low NOP step 15'),
    ('LABEL_03670D', 'DSP2_SendCmd_ClkLow_Nop16',   'DSP2_Send_Command: clock-low NOP step 16'),
    ('LABEL_036710', 'DSP2_SendCmd_ClkLow_Nop17',   'DSP2_Send_Command: clock-low NOP step 17'),
    ('LABEL_036713', 'DSP2_SendCmd_ClkLow_Nop18',   'DSP2_Send_Command: clock-low NOP step 18'),
    ('LABEL_036716', 'DSP2_SendCmd_ClkLow_Nop19',   'DSP2_Send_Command: clock-low NOP step 19'),
    ('LABEL_036719', 'DSP2_SendCmd_ClkLow_Nop20',   'DSP2_Send_Command: clock-low NOP step 20 (loop branch)'),
    # Post-bit-loop: final clock-high pulse and epilogue NOPs
    ('LABEL_036721', 'DSP2_SendCmd_PostLoop_Entry',
     'DSP2_Send_Command: post-bit-loop entry (all 8 bits sent)'),
    ('LABEL_036723', 'DSP2_SendCmd_PostLoop_Nop01',
     'DSP2_Send_Command: post-loop NOP step 1 (after final clk-high)'),
    ('LABEL_036729', 'DSP2_SendCmd_PostLoop_Nop02',  'DSP2_Send_Command: post-loop NOP step 2'),
    ('LABEL_03672C', 'DSP2_SendCmd_PostLoop_Nop03',  'DSP2_Send_Command: post-loop NOP step 3'),
    ('LABEL_03672F', 'DSP2_SendCmd_PostLoop_Nop04',  'DSP2_Send_Command: post-loop NOP step 4'),
    ('LABEL_036732', 'DSP2_SendCmd_PostLoop_Nop05',  'DSP2_Send_Command: post-loop NOP step 5'),
    ('LABEL_036735', 'DSP2_SendCmd_PostLoop_Nop06',  'DSP2_Send_Command: post-loop NOP step 6'),
    ('LABEL_036738', 'DSP2_SendCmd_PostLoop_Nop07',  'DSP2_Send_Command: post-loop NOP step 7'),
    ('LABEL_03673B', 'DSP2_SendCmd_PostLoop_Nop08',  'DSP2_Send_Command: post-loop NOP step 8'),
    ('LABEL_03673E', 'DSP2_SendCmd_PostLoop_Nop09',  'DSP2_Send_Command: post-loop NOP step 9'),
    ('LABEL_036741', 'DSP2_SendCmd_PostLoop_Nop10',  'DSP2_Send_Command: post-loop NOP step 10'),
    ('LABEL_036744', 'DSP2_SendCmd_PostLoop_Nop11',  'DSP2_Send_Command: post-loop NOP step 11'),
    ('LABEL_036747', 'DSP2_SendCmd_PostLoop_Nop12',  'DSP2_Send_Command: post-loop NOP step 12'),
    ('LABEL_03674A', 'DSP2_SendCmd_PostLoop_Nop13',  'DSP2_Send_Command: post-loop NOP step 13'),
    ('LABEL_03674D', 'DSP2_SendCmd_PostLoop_Nop14',  'DSP2_Send_Command: post-loop NOP step 14'),
    ('LABEL_036750', 'DSP2_SendCmd_PostLoop_Nop15',  'DSP2_Send_Command: post-loop NOP step 15'),
    ('LABEL_036753', 'DSP2_SendCmd_PostLoop_Nop16',  'DSP2_Send_Command: post-loop NOP step 16'),
    ('LABEL_036756', 'DSP2_SendCmd_PostLoop_Nop17',  'DSP2_Send_Command: post-loop NOP step 17 (before clk-low)'),
    # Clock goes low after post-loop NOPs, then more delay NOPs
    ('LABEL_03675C', 'DSP2_SendCmd_PostClkLow_Nop01', 'DSP2_Send_Command: post-clk-low NOP step 1'),
    ('LABEL_03675F', 'DSP2_SendCmd_PostClkLow_Nop02', 'DSP2_Send_Command: post-clk-low NOP step 2'),
    ('LABEL_036762', 'DSP2_SendCmd_PostClkLow_Nop03', 'DSP2_Send_Command: post-clk-low NOP step 3'),
    ('LABEL_036765', 'DSP2_SendCmd_PostClkLow_Nop04', 'DSP2_Send_Command: post-clk-low NOP step 4'),
    ('LABEL_036768', 'DSP2_SendCmd_PostClkLow_Nop05', 'DSP2_Send_Command: post-clk-low NOP step 5'),
    ('LABEL_03676B', 'DSP2_SendCmd_PostClkLow_Nop06', 'DSP2_Send_Command: post-clk-low NOP step 6'),
    ('LABEL_03676E', 'DSP2_SendCmd_PostClkLow_Nop07', 'DSP2_Send_Command: post-clk-low NOP step 7'),
    ('LABEL_036771', 'DSP2_SendCmd_PostClkLow_Nop08', 'DSP2_Send_Command: post-clk-low NOP step 8'),
    ('LABEL_036774', 'DSP2_SendCmd_PostClkLow_Nop09', 'DSP2_Send_Command: post-clk-low NOP step 9'),
    ('LABEL_036777', 'DSP2_SendCmd_PostClkLow_Nop10', 'DSP2_Send_Command: post-clk-low NOP step 10'),
    ('LABEL_03677A', 'DSP2_SendCmd_PostClkLow_Nop11', 'DSP2_Send_Command: post-clk-low NOP step 11'),
    ('LABEL_03677D', 'DSP2_SendCmd_PostClkLow_Nop12', 'DSP2_Send_Command: post-clk-low NOP step 12'),
    ('LABEL_036780', 'DSP2_SendCmd_PostClkLow_Nop13', 'DSP2_Send_Command: post-clk-low NOP step 13'),
    ('LABEL_036783', 'DSP2_SendCmd_PostClkLow_Nop14', 'DSP2_Send_Command: post-clk-low NOP step 14'),
    ('LABEL_036786', 'DSP2_SendCmd_PostClkLow_Nop15', 'DSP2_Send_Command: post-clk-low NOP step 15'),
    ('LABEL_036789', 'DSP2_SendCmd_PostClkLow_Nop16', 'DSP2_Send_Command: post-clk-low NOP step 16'),
    ('LABEL_03678C', 'DSP2_SendCmd_PostClkLow_Nop17', 'DSP2_Send_Command: post-clk-low NOP step 17'),
    ('LABEL_03678F', 'DSP2_SendCmd_PostClkLow_Nop18', 'DSP2_Send_Command: post-clk-low NOP step 18'),
    ('LABEL_036792', 'DSP2_SendCmd_PostClkLow_Nop19', 'DSP2_Send_Command: post-clk-low NOP step 19 (then chip select restore)'),
    ('LABEL_03679C', 'DSP2_SendCmd_Epilogue_Nop01',   'DSP2_Send_Command: epilogue NOP step 1'),
    ('LABEL_03679F', 'DSP2_SendCmd_Epilogue_Nop02',   'DSP2_Send_Command: epilogue NOP step 2'),
    ('LABEL_0367A2', 'DSP2_SendCmd_Epilogue_Nop03',   'DSP2_Send_Command: epilogue NOP step 3'),
    ('LABEL_0367A5', 'DSP2_SendCmd_Epilogue_Nop04',   'DSP2_Send_Command: epilogue NOP step 4'),
    ('LABEL_0367A8', 'DSP2_SendCmd_Epilogue_Nop05',   'DSP2_Send_Command: epilogue NOP step 5'),
    ('LABEL_0367AB', 'DSP2_SendCmd_Epilogue_Nop06',   'DSP2_Send_Command: epilogue NOP step 6'),
    ('LABEL_0367AE', 'DSP2_SendCmd_Epilogue_Nop07',   'DSP2_Send_Command: epilogue NOP step 7'),
    ('LABEL_0367B1', 'DSP2_SendCmd_Epilogue_Nop08',   'DSP2_Send_Command: epilogue NOP step 8'),
    ('LABEL_0367B4', 'DSP2_SendCmd_Epilogue_Nop09',   'DSP2_Send_Command: epilogue NOP step 9'),
    ('LABEL_0367B7', 'DSP2_SendCmd_Epilogue_Nop10',   'DSP2_Send_Command: epilogue NOP step 10'),
    ('LABEL_0367BA', 'DSP2_SendCmd_Epilogue_Nop11',   'DSP2_Send_Command: epilogue NOP step 11'),
    ('LABEL_0367BD', 'DSP2_SendCmd_Epilogue_Nop12',   'DSP2_Send_Command: epilogue NOP step 12'),
    ('LABEL_0367C0', 'DSP2_SendCmd_Epilogue_Nop13',   'DSP2_Send_Command: epilogue NOP step 13'),
    ('LABEL_0367C3', 'DSP2_SendCmd_Epilogue_Nop14',   'DSP2_Send_Command: epilogue NOP step 14'),
    ('LABEL_0367C6', 'DSP2_SendCmd_Epilogue_Nop15',   'DSP2_Send_Command: epilogue NOP step 15'),
    ('LABEL_0367C9', 'DSP2_SendCmd_Epilogue_Nop16',   'DSP2_Send_Command: epilogue NOP step 16 (last; ei 0 + ret)'),

    # -------------------------------------------------------------------------
    # DSP2_Send_Data bit-bang loop control and NOP chains (mirror of Send_Command)
    # -------------------------------------------------------------------------
    ('LABEL_0368DF', 'DSP2_SendData_BitLoop',
     'DSP2_Send_Data: bit-bang loop body, test and set/clear MOSI'),
    ('LABEL_0368EA', 'DSP2_SendData_BitClear',
     'DSP2_Send_Data: MOSI bit = 0 path (res data pin)'),
    ('LABEL_0368ED', 'DSP2_SendData_BitSet_Done',
     'DSP2_Send_Data: after MOSI write, fall into clock-high NOPs'),
    ('LABEL_0368EF', 'DSP2_SendData_ClkHigh_Nop01',  'DSP2_Send_Data: clock-high NOP step 1'),
    ('LABEL_0368F9', 'DSP2_SendData_ClkHigh_Nop02',  'DSP2_Send_Data: clock-high NOP step 2'),
    ('LABEL_0368FC', 'DSP2_SendData_ClkHigh_Nop03',  'DSP2_Send_Data: clock-high NOP step 3'),
    ('LABEL_0368FF', 'DSP2_SendData_ClkHigh_Nop04',  'DSP2_Send_Data: clock-high NOP step 4'),
    ('LABEL_036902', 'DSP2_SendData_ClkHigh_Nop05',  'DSP2_Send_Data: clock-high NOP step 5'),
    ('LABEL_036905', 'DSP2_SendData_ClkHigh_Nop06',  'DSP2_Send_Data: clock-high NOP step 6'),
    ('LABEL_036908', 'DSP2_SendData_ClkHigh_Nop07',  'DSP2_Send_Data: clock-high NOP step 7'),
    ('LABEL_03690B', 'DSP2_SendData_ClkHigh_Nop08',  'DSP2_Send_Data: clock-high NOP step 8'),
    ('LABEL_03690E', 'DSP2_SendData_ClkHigh_Nop09',  'DSP2_Send_Data: clock-high NOP step 9'),
    ('LABEL_036911', 'DSP2_SendData_ClkHigh_Nop10',  'DSP2_Send_Data: clock-high NOP step 10'),
    ('LABEL_036914', 'DSP2_SendData_ClkHigh_Nop11',  'DSP2_Send_Data: clock-high NOP step 11'),
    ('LABEL_036917', 'DSP2_SendData_ClkHigh_Nop12',  'DSP2_Send_Data: clock-high NOP step 12'),
    ('LABEL_03691A', 'DSP2_SendData_ClkHigh_Nop13',  'DSP2_Send_Data: clock-high NOP step 13'),
    ('LABEL_03691D', 'DSP2_SendData_ClkHigh_Nop14',  'DSP2_Send_Data: clock-high NOP step 14'),
    ('LABEL_036920', 'DSP2_SendData_ClkHigh_Nop15',  'DSP2_Send_Data: clock-high NOP step 15'),
    ('LABEL_036923', 'DSP2_SendData_ClkHigh_Nop16',  'DSP2_Send_Data: clock-high NOP step 16'),
    ('LABEL_036926', 'DSP2_SendData_ClkHigh_Nop17',  'DSP2_Send_Data: clock-high NOP step 17 (before clk-low)'),
    ('LABEL_03692C', 'DSP2_SendData_ClkLow_Nop01',   'DSP2_Send_Data: clock-low NOP step 1'),
    ('LABEL_03692F', 'DSP2_SendData_ClkLow_Nop02',   'DSP2_Send_Data: clock-low NOP step 2'),
    ('LABEL_036932', 'DSP2_SendData_ClkLow_Nop03',   'DSP2_Send_Data: clock-low NOP step 3'),
    ('LABEL_036935', 'DSP2_SendData_ClkLow_Nop04',   'DSP2_Send_Data: clock-low NOP step 4'),
    ('LABEL_036938', 'DSP2_SendData_ClkLow_Nop05',   'DSP2_Send_Data: clock-low NOP step 5'),
    ('LABEL_03693B', 'DSP2_SendData_ClkLow_Nop06',   'DSP2_Send_Data: clock-low NOP step 6'),
    ('LABEL_03693E', 'DSP2_SendData_ClkLow_Nop07',   'DSP2_Send_Data: clock-low NOP step 7'),
    ('LABEL_036941', 'DSP2_SendData_ClkLow_Nop08',   'DSP2_Send_Data: clock-low NOP step 8'),
    ('LABEL_036944', 'DSP2_SendData_ClkLow_Nop09',   'DSP2_Send_Data: clock-low NOP step 9'),
    ('LABEL_036947', 'DSP2_SendData_ClkLow_Nop10',   'DSP2_Send_Data: clock-low NOP step 10'),
    ('LABEL_03694A', 'DSP2_SendData_ClkLow_Nop11',   'DSP2_Send_Data: clock-low NOP step 11'),
    ('LABEL_03694D', 'DSP2_SendData_ClkLow_Nop12',   'DSP2_Send_Data: clock-low NOP step 12'),
    ('LABEL_036950', 'DSP2_SendData_ClkLow_Nop13',   'DSP2_Send_Data: clock-low NOP step 13'),
    ('LABEL_036953', 'DSP2_SendData_ClkLow_Nop14',   'DSP2_Send_Data: clock-low NOP step 14'),
    ('LABEL_036956', 'DSP2_SendData_ClkLow_Nop15',   'DSP2_Send_Data: clock-low NOP step 15'),
    ('LABEL_036959', 'DSP2_SendData_ClkLow_Nop16',   'DSP2_Send_Data: clock-low NOP step 16'),
    ('LABEL_03695C', 'DSP2_SendData_ClkLow_Nop17',   'DSP2_Send_Data: clock-low NOP step 17'),
    ('LABEL_03695F', 'DSP2_SendData_ClkLow_Nop18',   'DSP2_Send_Data: clock-low NOP step 18'),
    ('LABEL_036962', 'DSP2_SendData_ClkLow_Nop19',   'DSP2_Send_Data: clock-low NOP step 19 (loop branch)'),
    ('LABEL_03696A', 'DSP2_SendData_PostLoop_Entry',
     'DSP2_Send_Data: post-bit-loop entry (all 8 bits sent)'),
    ('LABEL_03696C', 'DSP2_SendData_PostLoop_Nop01',  'DSP2_Send_Data: post-loop NOP step 1'),
    ('LABEL_036972', 'DSP2_SendData_PostLoop_Nop02',  'DSP2_Send_Data: post-loop NOP step 2'),
    ('LABEL_036975', 'DSP2_SendData_PostLoop_Nop03',  'DSP2_Send_Data: post-loop NOP step 3'),
    ('LABEL_036978', 'DSP2_SendData_PostLoop_Nop04',  'DSP2_Send_Data: post-loop NOP step 4'),
    ('LABEL_03697B', 'DSP2_SendData_PostLoop_Nop05',  'DSP2_Send_Data: post-loop NOP step 5'),
    ('LABEL_03697E', 'DSP2_SendData_PostLoop_Nop06',  'DSP2_Send_Data: post-loop NOP step 6'),
    ('LABEL_036981', 'DSP2_SendData_PostLoop_Nop07',  'DSP2_Send_Data: post-loop NOP step 7'),
    ('LABEL_036984', 'DSP2_SendData_PostLoop_Nop08',  'DSP2_Send_Data: post-loop NOP step 8'),
    ('LABEL_036987', 'DSP2_SendData_PostLoop_Nop09',  'DSP2_Send_Data: post-loop NOP step 9'),
    ('LABEL_03698A', 'DSP2_SendData_PostLoop_Nop10',  'DSP2_Send_Data: post-loop NOP step 10'),
    ('LABEL_03698D', 'DSP2_SendData_PostLoop_Nop11',  'DSP2_Send_Data: post-loop NOP step 11'),
    ('LABEL_036990', 'DSP2_SendData_PostLoop_Nop12',  'DSP2_Send_Data: post-loop NOP step 12'),
    ('LABEL_036993', 'DSP2_SendData_PostLoop_Nop13',  'DSP2_Send_Data: post-loop NOP step 13'),
    ('LABEL_036996', 'DSP2_SendData_PostLoop_Nop14',  'DSP2_Send_Data: post-loop NOP step 14'),
    ('LABEL_036999', 'DSP2_SendData_PostLoop_Nop15',  'DSP2_Send_Data: post-loop NOP step 15'),
    ('LABEL_03699C', 'DSP2_SendData_PostLoop_Nop16',  'DSP2_Send_Data: post-loop NOP step 16'),
    ('LABEL_03699F', 'DSP2_SendData_PostLoop_Nop17',  'DSP2_Send_Data: post-loop NOP step 17 (before clk-low)'),
    ('LABEL_0369A5', 'DSP2_SendData_PostClkLow_Nop01', 'DSP2_Send_Data: post-clk-low NOP step 1'),
    ('LABEL_0369A8', 'DSP2_SendData_PostClkLow_Nop02', 'DSP2_Send_Data: post-clk-low NOP step 2'),
    ('LABEL_0369AB', 'DSP2_SendData_PostClkLow_Nop03', 'DSP2_Send_Data: post-clk-low NOP step 3'),
    ('LABEL_0369AE', 'DSP2_SendData_PostClkLow_Nop04', 'DSP2_Send_Data: post-clk-low NOP step 4'),
    ('LABEL_0369B1', 'DSP2_SendData_PostClkLow_Nop05', 'DSP2_Send_Data: post-clk-low NOP step 5'),
    ('LABEL_0369B4', 'DSP2_SendData_PostClkLow_Nop06', 'DSP2_Send_Data: post-clk-low NOP step 6'),
    ('LABEL_0369B7', 'DSP2_SendData_PostClkLow_Nop07', 'DSP2_Send_Data: post-clk-low NOP step 7'),
    ('LABEL_0369BA', 'DSP2_SendData_PostClkLow_Nop08', 'DSP2_Send_Data: post-clk-low NOP step 8'),
    ('LABEL_0369BD', 'DSP2_SendData_PostClkLow_Nop09', 'DSP2_Send_Data: post-clk-low NOP step 9'),
    ('LABEL_0369C0', 'DSP2_SendData_PostClkLow_Nop10', 'DSP2_Send_Data: post-clk-low NOP step 10'),
    ('LABEL_0369C3', 'DSP2_SendData_PostClkLow_Nop11', 'DSP2_Send_Data: post-clk-low NOP step 11'),
    ('LABEL_0369C6', 'DSP2_SendData_PostClkLow_Nop12', 'DSP2_Send_Data: post-clk-low NOP step 12'),
    ('LABEL_0369C9', 'DSP2_SendData_PostClkLow_Nop13', 'DSP2_Send_Data: post-clk-low NOP step 13'),
    ('LABEL_0369CC', 'DSP2_SendData_PostClkLow_Nop14', 'DSP2_Send_Data: post-clk-low NOP step 14'),
    ('LABEL_0369CF', 'DSP2_SendData_PostClkLow_Nop15', 'DSP2_Send_Data: post-clk-low NOP step 15'),
    ('LABEL_0369D2', 'DSP2_SendData_PostClkLow_Nop16', 'DSP2_Send_Data: post-clk-low NOP step 16'),
    ('LABEL_0369D5', 'DSP2_SendData_PostClkLow_Nop17', 'DSP2_Send_Data: post-clk-low NOP step 17'),
    ('LABEL_0369D8', 'DSP2_SendData_PostClkLow_Nop18', 'DSP2_Send_Data: post-clk-low NOP step 18'),
    ('LABEL_0369DB', 'DSP2_SendData_PostClkLow_Nop19', 'DSP2_Send_Data: post-clk-low NOP step 19 (then chip-select restore)'),
    ('LABEL_0369E5', 'DSP2_SendData_Epilogue_Nop01',   'DSP2_Send_Data: epilogue NOP step 1'),
    ('LABEL_0369E8', 'DSP2_SendData_Epilogue_Nop02',   'DSP2_Send_Data: epilogue NOP step 2'),
    ('LABEL_0369EB', 'DSP2_SendData_Epilogue_Nop03',   'DSP2_Send_Data: epilogue NOP step 3'),
    ('LABEL_0369EE', 'DSP2_SendData_Epilogue_Nop04',   'DSP2_Send_Data: epilogue NOP step 4'),
    ('LABEL_0369F1', 'DSP2_SendData_Epilogue_Nop05',   'DSP2_Send_Data: epilogue NOP step 5'),
    ('LABEL_0369F4', 'DSP2_SendData_Epilogue_Nop06',   'DSP2_Send_Data: epilogue NOP step 6'),
    ('LABEL_0369F7', 'DSP2_SendData_Epilogue_Nop07',   'DSP2_Send_Data: epilogue NOP step 7'),
    ('LABEL_0369FA', 'DSP2_SendData_Epilogue_Nop08',   'DSP2_Send_Data: epilogue NOP step 8'),
    ('LABEL_0369FD', 'DSP2_SendData_Epilogue_Nop09',   'DSP2_Send_Data: epilogue NOP step 9'),
    ('LABEL_036A00', 'DSP2_SendData_Epilogue_Nop10',   'DSP2_Send_Data: epilogue NOP step 10'),
    ('LABEL_036A03', 'DSP2_SendData_Epilogue_Nop11',   'DSP2_Send_Data: epilogue NOP step 11'),
    ('LABEL_036A06', 'DSP2_SendData_Epilogue_Nop12',   'DSP2_Send_Data: epilogue NOP step 12'),
    ('LABEL_036A09', 'DSP2_SendData_Epilogue_Nop13',   'DSP2_Send_Data: epilogue NOP step 13'),
    ('LABEL_036A0C', 'DSP2_SendData_Epilogue_Nop14',   'DSP2_Send_Data: epilogue NOP step 14'),
    ('LABEL_036A0F', 'DSP2_SendData_Epilogue_Nop15',   'DSP2_Send_Data: epilogue NOP step 15'),
    ('LABEL_036A12', 'DSP2_SendData_Epilogue_Nop16',   'DSP2_Send_Data: epilogue NOP step 16 (last; ei 0 + ret)'),

    # -------------------------------------------------------------------------
    # 036xxx - DSP dispatch and diff helpers
    # -------------------------------------------------------------------------
    ('LABEL_036A42', 'DSP_DispatchCommand_DSP2Path',
     'DSP_DispatchCommand: chip=1, route to DSP2_Send_Command'),
    ('LABEL_036A49', 'DSP_DispatchCommand_InvalidChip',
     'DSP_DispatchCommand: unknown chip number, set error flag'),
    ('LABEL_036A4B', 'DSP_DispatchCommand_Epilogue',
     'DSP_DispatchCommand: common epilogue, return HL=error'),
    ('LABEL_036A63', 'DSP_DispatchData_DSP2Path',
     'DSP_DispatchData: chip=1, route to DSP2_Send_Data'),
    ('LABEL_036A6A', 'DSP_DispatchData_InvalidChip',
     'DSP_DispatchData: unknown chip number, set error flag'),
    ('LABEL_036A6C', 'DSP_DispatchData_Epilogue',
     'DSP_DispatchData: common epilogue, return HL=error'),

    ('LABEL_036A94', 'DSP_AlgoChange_NoChange',
     'DSP_AlgoChange_CheckAndFlag: algo unchanged, skip flag'),
    ('LABEL_036A9B', 'DSP_AlgoChange_FlagAndClear',
     'DSP_AlgoChange_CheckAndFlag: algo changed, set dirty flag'),

    ('LABEL_036AA8', 'DSP_SlotParam_DiffLoop',
     'DSP_SlotParam_DiffAndFlag: inner loop comparing slot param bytes'),
    ('LABEL_036AE4', 'DSP_SlotParam_DiffMatch',
     'DSP_SlotParam_DiffAndFlag: byte matches, continue loop'),
    ('LABEL_036AF6', 'DSP_SlotParam_DiffMismatch',
     'DSP_SlotParam_DiffAndFlag: mismatch found, set dirty flag'),

    ('LABEL_036B05', 'DSP_EFFParam_DiffOuter',
     'DSP_EFFParam_DiffAllAndFlag: outer EFF slot loop start'),
    ('LABEL_036B22', 'DSP_EFFParam_DiffMid',
     'DSP_EFFParam_DiffAllAndFlag: mid-level loop (2 entries per EFF slot)'),
    ('LABEL_036B89', 'DSP_EFFParam_DiffMidMatch',
     'DSP_EFFParam_DiffAllAndFlag: mid-level match path, next entry'),
    ('LABEL_036BA1', 'DSP_EFFParam_DiffMidNext',
     'DSP_EFFParam_DiffAllAndFlag: mid-level loop increment'),
    ('LABEL_036BA8', 'DSP_EFFParam_DiffInner',
     'DSP_EFFParam_DiffAllAndFlag: inner loop (0x11 param bytes per entry)'),
    ('LABEL_036BB1', 'DSP_EFFParam_DiffInnerBody',
     'DSP_EFFParam_DiffAllAndFlag: inner loop body comparing single byte'),
    ('LABEL_036C18', 'DSP_EFFParam_DiffInnerMatch',
     'DSP_EFFParam_DiffAllAndFlag: inner byte match, continue'),
    ('LABEL_036C30', 'DSP_EFFParam_DiffInnerNext',
     'DSP_EFFParam_DiffAllAndFlag: inner loop increment'),
    ('LABEL_036C39', 'DSP_EFFParam_DiffLevel4',
     'DSP_EFFParam_DiffAllAndFlag: 4th level loop (2-entry sub-block)'),
    ('LABEL_036C40', 'DSP_EFFParam_DiffLevel4Body',
     'DSP_EFFParam_DiffAllAndFlag: 4th level loop body'),
    ('LABEL_036CA7', 'DSP_EFFParam_DiffLevel4Match',
     'DSP_EFFParam_DiffAllAndFlag: 4th level match path'),
    ('LABEL_036CBF', 'DSP_EFFParam_DiffLevel4Next',
     'DSP_EFFParam_DiffAllAndFlag: 4th level loop increment'),
    ('LABEL_036CC6', 'DSP_EFFParam_DiffAlgoSection',
     'DSP_EFFParam_DiffAllAndFlag: algo-change diff section within loop'),
    ('LABEL_036D1F', 'DSP_EFFParam_AlgoChangePath',
     'DSP_EFFParam_DiffAllAndFlag: algo changed sub-path'),
    ('LABEL_036D35', 'DSP_EFFParam_DiffOuterNext',
     'DSP_EFFParam_DiffAllAndFlag: outer loop increment'),
    ('LABEL_036D7E', 'DSP_EFFParam_DiffEpilogue',
     'DSP_EFFParam_DiffAllAndFlag: epilogue (pop + ret)'),

    ('LABEL_036DAF', 'DSP_Config_ClampLoop',
     'DSP_Config_ClampLimits: loop body iterating param bytes'),
    ('LABEL_036DB5', 'DSP_Config_ClampApply',
     'DSP_Config_ClampLimits: apply clamp (copy limit value)'),
    ('LABEL_036DE3', 'DSP_Config_ClampNext',
     'DSP_Config_ClampLimits: loop increment and branch'),
    ('LABEL_036DEA', 'DSP_Config_ClampData',
     'DSP_Config_ClampLimits: 11-byte clamp limit table'),

    ('LABEL_036E12', 'CalcSampleAddr',
     'Calculate sample ROM address from voice waveform index'),

    ('LABEL_036E70', 'EFF_SlotActive_CheckSlot',
     'EFF_SlotActive_UpdateFlags: inner loop checking slot active condition'),
    ('LABEL_036E87', 'EFF_SlotActive_SlotActive',
     'EFF_SlotActive_UpdateFlags: slot is active, update flag word'),
    ('LABEL_036E8D', 'EFF_SlotActive_SlotInactive',
     'EFF_SlotActive_UpdateFlags: slot is inactive, clear flag'),
    ('LABEL_036EB9', 'EFF_SlotActive_VoiceCheck',
     'EFF_SlotActive_UpdateFlags: voice active check'),
    ('LABEL_036EBB', 'EFF_SlotActive_VoiceInactive',
     'EFF_SlotActive_UpdateFlags: voice not active, clear entry'),
    ('LABEL_036EED', 'EFF_SlotActive_AlgoCheck',
     'EFF_SlotActive_UpdateFlags: check algo index for slot match'),
    ('LABEL_036F0B', 'EFF_SlotActive_LoopNext',
     'EFF_SlotActive_UpdateFlags: advance outer loop counter'),
    ('LABEL_036FBA', 'EFF_SlotActive_InnerLoopNext',
     'EFF_SlotActive_UpdateFlags: advance inner sub-slot loop'),
    ('LABEL_036FCA', 'EFF_SlotActive_Epilogue',
     'EFF_SlotActive_UpdateFlags: epilogue (pop + ret)'),

    ('LABEL_036FE6', 'EFF_DSPLink_ResetFlags_ZeroPath',
     'EFF_DSPLink_ResetFlags: algo-link index is 0, skip reset'),
    ('LABEL_036FFD', 'EFF_DSPLink_ResetFlags_LoopNext',
     'EFF_DSPLink_ResetFlags: outer loop increment'),

    # -------------------------------------------------------------------------
    # 037xxx - EFF_DspChannel_InitFlags inner loop labels
    # -------------------------------------------------------------------------
    ('LABEL_037003', 'EFF_DSPLink_ResetFlags_InnerBody',
     'EFF_DSPLink_ResetFlags: inner loop body clearing link-reset flags'),
    ('LABEL_037020', 'EFF_DspChannel_Init_AlgoCheck',
     'EFF_DspChannel_InitFlags: algo-change check for this EFF slot'),
    ('LABEL_03703A', 'EFF_DspChannel_Init_SlotNext',
     'EFF_DspChannel_InitFlags: advance outer EFF slot loop counter'),
    ('LABEL_037057', 'EFF_DspChannel_Init_FreqLoop',
     'EFF_DspChannel_InitFlags: freq-param dirty-flag loop (0x11 entries)'),
    ('LABEL_037077', 'EFF_DspChannel_Init_CoeffLoop',
     'EFF_DspChannel_InitFlags: coeff-param dirty-flag loop (2 entries)'),
    ('LABEL_03707D', 'EFF_DspChannel_Init_CoeffNext',
     'EFF_DspChannel_InitFlags: coeff loop increment and branch'),
    ('LABEL_03709B', 'EFF_DspChannel_Init_Coeff2Loop',
     'EFF_DspChannel_InitFlags: second coeff dirty-flag loop'),
    ('LABEL_0370A1', 'EFF_DspChannel_Init_Coeff2Next',
     'EFF_DspChannel_InitFlags: second coeff loop increment and branch'),
    ('LABEL_0370BF', 'EFF_DspChannel_Init_MultiTableDirty',
     'EFF_DspChannel_InitFlags: set dirty flags across multiple state tables'),
    ('LABEL_037159', 'EFF_DspChannel_Init_AlgoTypePath',
     'EFF_DspChannel_InitFlags: algo-type-specific dirty flag propagation'),
    ('LABEL_03716D', 'EFF_DspChannel_Init_OuterNext',
     'EFF_DspChannel_InitFlags: outer slot loop increment'),

    # Per-algo-type dirty-flag sub-paths (37 algo types, each sets different state words)
    ('LABEL_0371CE', 'EFF_DspChanInit_AlgoType0_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x00 dirty flag table entry'),
    ('LABEL_037210', 'EFF_DspChanInit_AlgoType1_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x01 dirty flag table entry'),
    ('LABEL_037258', 'EFF_DspChanInit_AlgoType2_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x02 dirty flag table entry'),
    ('LABEL_03729A', 'EFF_DspChanInit_AlgoType3_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x03 dirty flag table entry'),
    ('LABEL_0372E2', 'EFF_DspChanInit_AlgoType4_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x04 dirty flag table entry'),
    ('LABEL_037324', 'EFF_DspChanInit_AlgoType5_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x05 dirty flag table entry'),
    ('LABEL_03736C', 'EFF_DspChanInit_AlgoType6_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x06 dirty flag table entry'),
    ('LABEL_0373AE', 'EFF_DspChanInit_AlgoType7_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x07 dirty flag table entry'),
    ('LABEL_0373F6', 'EFF_DspChanInit_AlgoType8_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x08 dirty flag table entry'),
    ('LABEL_037438', 'EFF_DspChanInit_AlgoType9_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x09 dirty flag table entry'),
    ('LABEL_037495', 'EFF_DspChanInit_AlgoType4F_SubA',
     'EFF_DspChannel_InitFlags: algo type 0x4F dirty sub-path A'),
    ('LABEL_0374D9', 'EFF_DspChanInit_AlgoType4F_SubB',
     'EFF_DspChannel_InitFlags: algo type 0x4F dirty sub-path B'),
    ('LABEL_03751D', 'EFF_DspChanInit_AlgoType4F_SubC',
     'EFF_DspChannel_InitFlags: algo type 0x4F dirty sub-path C'),
    ('LABEL_037561', 'EFF_DspChanInit_AlgoType4F_Epilogue',
     'EFF_DspChannel_InitFlags: algo type 0x4F dirty epilogue'),
    ('LABEL_037592', 'EFF_DspChanInit_AlgoType35_Dirty',
     'EFF_DspChannel_InitFlags: algo type 0x35/0x0F dirty flag path'),
    ('LABEL_03761E', 'EFF_DspChanInit_AlgoType35_SubA',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path A'),
    ('LABEL_037676', 'EFF_DspChanInit_AlgoType35_SubB',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path B'),
    ('LABEL_03768E', 'EFF_DspChanInit_AlgoType35_SubC',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path C'),
    ('LABEL_0376D6', 'EFF_DspChanInit_AlgoType35_SubD',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path D'),
    ('LABEL_0376EC', 'EFF_DspChanInit_AlgoType35_SubE',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path E'),
    ('LABEL_037702', 'EFF_DspChanInit_AlgoType35_SubF',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty sub-path F'),
    ('LABEL_037746', 'EFF_DspChanInit_AlgoType35_Epilogue',
     'EFF_DspChannel_InitFlags: algo 0x35/0x0F dirty epilogue'),

    # EFF_MuteLoop inner labels
    ('LABEL_037769', 'EFF_MuteLoop_SlotBody',
     'EFF_MuteLoop: inner loop body checking slot active and voice link'),
    ('LABEL_0377BD', 'EFF_MuteLoop_NoMute',
     'EFF_MuteLoop: slot not active or not mutable, call mute helper'),
    ('LABEL_0377C5', 'EFF_MuteLoop_SlotNext',
     'EFF_MuteLoop: advance slot counter and branch'),
    ('LABEL_0377CB', 'EFF_MuteLoop_Epilogue',
     'EFF_MuteLoop: epilogue, optionally flush mute (pop iz + ret)'),
    ('LABEL_0377D6', 'EFF_MuteLoop_NoFlush',
     'EFF_MuteLoop: no mute action taken, return without flush'),

    # DSP_ResetLoop inner labels
    ('LABEL_0377DF', 'DSP_ResetLoop_Body',
     'DSP_ResetLoop: loop body calling chip reset for each DSP (0..1)'),
    ('LABEL_0377EB', 'DSP_ResetLoop_Epilogue',
     'DSP_ResetLoop: epilogue (popw iz + ret)'),

    # DSP_MuteLoop inner labels
    ('LABEL_0377F4', 'DSP_MuteLoop_Body',
     'DSP_MuteLoop: loop body; mute DSP chip if state flag set'),
    ('LABEL_03780C', 'DSP_MuteLoop_Next',
     'DSP_MuteLoop: advance chip counter and branch'),
    ('LABEL_037812', 'DSP_MuteLoop_Epilogue',
     'DSP_MuteLoop: epilogue (popw iz + ret)'),

    # DSP_UnmuteLoop inner labels
    ('LABEL_03781B', 'DSP_UnmuteLoop_Body',
     'DSP_UnmuteLoop: loop body; unmute DSP chip if state flag set'),
    ('LABEL_037833', 'DSP_UnmuteLoop_Next',
     'DSP_UnmuteLoop: advance chip counter and branch'),
    ('LABEL_037839', 'DSP_UnmuteLoop_Epilogue',
     'DSP_UnmuteLoop: epilogue (popw iz + ret)'),

    # Unsigned_Max_Select body
    ('LABEL_03784E', 'Unsigned_Max_Select_Return',
     'Unsigned_Max_Select: BC <= WA path, return WA as max in HL'),

    # EFF_ParamIterator_Process inner labels
    ('LABEL_0378A4', 'EFF_ParamIter_CountClamp',
     'EFF_ParamIterator_Process: clamp iteration count to 0x11 max'),
    ('LABEL_0378AC', 'EFF_ParamIter_StdLoop',
     'EFF_ParamIterator_Process: standard loop body (non-0x35/0xF algo)'),
    ('LABEL_037903', 'EFF_ParamIter_StdLoopNext',
     'EFF_ParamIterator_Process: standard loop increment and branch'),
    ('LABEL_03790C', 'EFF_ParamIter_SpecialAlgoPath',
     'EFF_ParamIterator_Process: special path for algo 0x35 / 0xF'),
    ('LABEL_03793A', 'EFF_ParamIter_SpecialLoop',
     'EFF_ParamIterator_Process: special algo loop body over param table'),
    ('LABEL_037980', 'EFF_ParamIter_SpecialLoopNext',
     'EFF_ParamIterator_Process: special loop advance (inc xiz) and branch'),
    ('LABEL_037987', 'EFF_ParamIter_Epilogue',
     'EFF_ParamIterator_Process: epilogue (pop xiz + inc 6,xsp + ret)'),

    # EFF_Change_Handler dispatch labels
    ('LABEL_0379E2', 'EFF_Change_Handler_NonSlot2',
     'EFF_Change_Handler: iz != 2, call generic EFF change path'),
    ('LABEL_0379EE', 'EFF_Change_Handler_SlotDispatch',
     'EFF_Change_Handler: dispatch on slot index (2/3/4 vs other)'),
    ('LABEL_037A19', 'EFF_Change_Handler_Slot234_AlgoPath',
     'EFF_Change_Handler: slots 2/3/4, check preset type for algo path'),
    ('LABEL_037A40', 'EFF_Change_Handler_Slot234_AltPath',
     'EFF_Change_Handler: slots 2/3/4, alternate preset type (call 0x381BC)'),
    ('LABEL_037A5B', 'EFF_Change_Handler_Epilogue',
     'EFF_Change_Handler: common epilogue (volume check + ret)'),

    # EFF_HeaderChangeDataLoop inner labels
    ('LABEL_037A78', 'EFF_HeaderChangeLoop_Body',
     'EFF_HeaderChangeDataLoop: main loop body per EFF slot'),
    ('LABEL_037A8C', 'EFF_HeaderChangeLoop_CallAlgo',
     'EFF_HeaderChangeDataLoop: algo-applicable path, call 0x380AB'),
    ('LABEL_037A92', 'EFF_HeaderChangeLoop_PostAlgo',
     'EFF_HeaderChangeDataLoop: check active state table entry'),
    ('LABEL_037AAF', 'EFF_HeaderChangeLoop_ActiveSlot',
     'EFF_HeaderChangeDataLoop: slot active, compute max volume'),
    ('LABEL_037AC6', 'EFF_HeaderChangeLoop_CallChange',
     'EFF_HeaderChangeDataLoop: call EFF_Change_Handler for this slot'),
    ('LABEL_037AD6', 'EFF_HeaderChangeLoop_Epilogue',
     'EFF_HeaderChangeDataLoop: epilogue, optional state-apply call'),
    ('LABEL_037AE2', 'EFF_HeaderChangeLoop_SkipApply',
     'EFF_HeaderChangeDataLoop: skip state-apply (no active slots), return'),

    # EFF_LinkLoop inner labels
    ('LABEL_037AF4', 'EFF_LinkLoop_Body',
     'EFF_LinkLoop: main loop body per EFF slot (check link active)'),
    ('LABEL_037B31', 'EFF_LinkLoop_Next',
     'EFF_LinkLoop: advance slot counter and branch'),
    ('LABEL_037B39', 'EFF_LinkLoop_Epilogue',
     'EFF_LinkLoop: epilogue (popw iz + inc 4,xsp + ret)'),

    # EFF_SecondaryLinkPath inner labels
    ('LABEL_037B4F', 'EFF_SecLinkPath_Pass1Body',
     'EFF_SecondaryLinkPath: pass-1 loop body (find max disconnect volume)'),
    ('LABEL_037B8C', 'EFF_SecLinkPath_Pass1Next',
     'EFF_SecondaryLinkPath: pass-1 loop decrement and branch'),
    ('LABEL_037B96', 'EFF_SecLinkPath_Pass1Epilogue',
     'EFF_SecondaryLinkPath: pass-1 done, call flush if iz > 0'),
    ('LABEL_037BA0', 'EFF_SecLinkPath_Pass2Start',
     'EFF_SecondaryLinkPath: pass-2 loop start'),
    ('LABEL_037BAC', 'EFF_SecLinkPath_Pass2Body',
     'EFF_SecondaryLinkPath: pass-2 loop body (apply link disconnect)'),
    ('LABEL_037BF6', 'EFF_SecLinkPath_Pass2MaxVol',
     'EFF_SecondaryLinkPath: pass-2 max-volume accumulate step'),
    ('LABEL_037C0D', 'EFF_SecLinkPath_Pass2Next',
     'EFF_SecondaryLinkPath: pass-2 loop decrement and branch'),
    ('LABEL_037C17', 'EFF_SecLinkPath_Pass2Epilogue',
     'EFF_SecondaryLinkPath: pass-2 done, call flush if iz > 0'),
    ('LABEL_037C21', 'EFF_SecLinkPath_Epilogue',
     'EFF_SecondaryLinkPath: full epilogue (pop xiz + inc 4,xsp + ret)'),

    # EFF_VolumeLoop inner labels
    ('LABEL_037C32', 'EFF_VolumeLoop_Body',
     'EFF_VolumeLoop: main loop body (check dirty vol flag, compute delta)'),
    ('LABEL_037D16', 'EFF_VolumeLoop_ApplyDelta',
     'EFF_VolumeLoop: apply computed volume delta, call write helper'),
    ('LABEL_037D35', 'EFF_VolumeLoop_Next',
     'EFF_VolumeLoop: advance slot counter and branch'),
    ('LABEL_037D3C', 'EFF_VolumeLoop_Epilogue',
     'EFF_VolumeLoop: epilogue (popw iz + inc 4,xsp + ret)'),

    # EFF_DisconnectLoop inner labels
    ('LABEL_037D4E', 'EFF_DisconnectLoop_Body',
     'EFF_DisconnectLoop: main loop body (skip slots 2 and 3, call disconnect)'),
    ('LABEL_037D62', 'EFF_DisconnectLoop_Next',
     'EFF_DisconnectLoop: advance slot counter and branch'),
    ('LABEL_037D6A', 'EFF_DisconnectLoop_Epilogue',
     'EFF_DisconnectLoop: epilogue (popw iz + inc 4,xsp + ret)'),

    # DSP_State_Dispatcher inner labels
    ('LABEL_037D7D', 'DSP_StateDispatcher_MutePath',
     'DSP_State_Dispatcher: no reset flag, call EFF_MuteLoop instead'),
    ('LABEL_037D82', 'DSP_StateDispatcher_PostMute',
     'DSP_State_Dispatcher: after mute/reset, call DSP_MuteLoop'),
    ('LABEL_037D98', 'DSP_StateDispatcher_DisconnectPath',
     'DSP_State_Dispatcher: reset or preset change, call EFF_DisconnectLoop'),
    ('LABEL_037DA3', 'DSP_StateDispatcher_UnmutePath',
     'DSP_State_Dispatcher: call DSP_UnmuteLoop then chain all EFF loops'),
    ('LABEL_037DC2', 'DSP_StateDispatcher_AlgoLoop',
     'DSP_State_Dispatcher: algo index update loop (EFF slots 4..0)'),
    ('LABEL_037E16', 'DSP_StateDispatcher_AlgoClear',
     'DSP_State_Dispatcher: clear algo index entry (voice not mapped)'),
    ('LABEL_037E26', 'DSP_StateDispatcher_AlgoNext',
     'DSP_State_Dispatcher: advance algo loop counter and branch'),
    ('LABEL_037E2E', 'DSP_StateDispatcher_Epilogue',
     'DSP_State_Dispatcher: epilogue (pop xiz + ret)'),
]


def main():
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(base, 'subcpu', 'kn5000_subprogram_v142.s')

    with open(src, 'rb') as f:
        content = f.read().decode('latin-1')

    renamed = 0
    for old_label, new_label, comment in RENAMES:
        if old_label + ':' not in content:
            print(f'  WARNING: {old_label} not found, skipping')
            continue

        refs = len(re.findall(r'\b' + re.escape(old_label) + r'\b', content))
        new_content = re.sub(r'\b' + re.escape(old_label) + r'\b', new_label, content)

        if new_content != content:
            content = new_content
            renamed += 1
            print(f'  {old_label:25s} -> {new_label:45s} ({refs} refs)')

    # Check maincpu for cross-references
    maincpu_src = os.path.join(base, 'maincpu', 'kn5000_v10_program.s')
    with open(maincpu_src, 'rb') as f:
        maincpu_content = f.read().decode('latin-1')

    maincpu_renames = 0
    for old_label, new_label, _ in RENAMES:
        if old_label in maincpu_content:
            maincpu_content = re.sub(r'\b' + re.escape(old_label) + r'\b', new_label, maincpu_content)
            maincpu_renames += 1

    with open(src, 'wb') as f:
        f.write(content.encode('latin-1'))

    if maincpu_renames > 0:
        with open(maincpu_src, 'wb') as f:
            f.write(maincpu_content.encode('latin-1'))

    print(f'\nRenamed {renamed} labels in subcpu ({maincpu_renames} cross-refs in maincpu)')


if __name__ == '__main__':
    main()
