#!/usr/bin/env python3
r"""WHICH INSTRUCTION FORMS DOES THE WSA1 TREE STILL CARRY AS `.byte`, AND WHY?

QUESTION IT ANSWERS
    The SX-WSA1R counterpart of `../../../notes/sound/kn5000_unspellable_forms.py`.
    Per FORM: what the bytes are, how many sites carry them, whether llvm-mc can
    spell them at all, and -- the number the sound-disassembly goal is about --
    HOW MANY OF THOSE SITES SIT INSIDE A ROUTINE THAT TOUCHES A SOUND DEVICE.

    Before this file existed the WSA1's unspelt population could not be
    quantified.  The nearest thing to a figure was "334 candidate lines in
    prom_a, 0 in prom_b, 0 in prom_c", produced by matching any `.byte` whose
    comment starts with a letter.  In THIS tree every `.byte` comment starts
    with a letter, because the convention is `; F831FF  ...` and hex addresses
    here all begin `F`.  That regex matches data tables and code alike; it is
    the same false-positive class that once made the KN5000's "562 bytes in 45
    forms" spurious.

⚠ "NO SPELLING" IS NOT THE SAME AS "THE BACKEND CANNOT ENCODE IT".  A form is
  listed when NEITHER route in gate 4 produced its bytes.  For most of them the
  honest statement is "nobody has written a route yet": the decoder covers the
  exotic families it was built for, and the verbatim route fails on things like
  the 16-bit-address memory operand, which llvm-mc CAN write -- as
  `or (0x2134:16), 0x0002` -- but not in the spelling unidasm prints.  The
  per-form line says which route failed and how, so the two are never merged
  into one number.  Deciding which of the 97 remaining forms are real backend
  gaps is the next lane's job, and this is its work list.

★ FOUR INDEPENDENT GATES MAKE THIS A MEASUREMENT RATHER THAN A GREP
    A line is counted only if ALL of these hold:
      1. its comment is this tree's code convention, `; ADDR  b0 b1 ...`, and
         the echoed byte string is EXACTLY the `.byte` operands;
      2. the ORIGINAL ROM at ADDR holds exactly those bytes -- so the line is
         really at the address it claims, with the bytes it claims;
      3. the COMMITTED MAME UNIDASM LISTING for that image frames exactly that
         byte string as ONE INSTRUCTION (`original_ROMs/*.unidasm`, generated by
         the command in `original_ROMs/README-unidasm.md`).  ⚠ `db` IS NOT AN
         INSTRUCTION: it is unidasm's marker for bytes it cannot decode, and it
         is rejected here.  24 prom_a sites (`80 0f`, the (XWA) byte prefix with
         undefined sub-opcode 0x0F) render that way; counting them as unspelt
         would blame the assembler for an opcode the CPU does not have;
      4. "spellable" means THE BYTES CAME BACK.  Two routes are tried and both
         are judged the same way -- by the encoding, never by acceptance, because
         this backend has been caught accepting `push (0x1234)` while truncating
         the address:
           * `../../../scripts/converters/convert_unspellable_forms.py`'s
             decoder, which reads the OPCODE BYTES and knows the exotic families;
           * failing that, unidasm's own rendering typed VERBATIM.  Much of the
             tree is already written that way, so a form the decoder has no
             branch for may still be perfectly writable.
           * failing that, the same rendering with a NEGATIVE 8-bit
             displacement.  unidasm prints d8 unsigned, and llvm-mc reads
             `(XIZ+0xfc)` as +252 and widens to the d16 form -- five bytes where
             the ROM has three.  `(xiz-4)` is the same slot, is what prom_c's
             own sources write, and encodes exactly.
         ⚠ THE VERBATIM ROUTE IS REFUSED FOR PC-RELATIVE MNEMONICS,
         whatever the bytes say.  `calr 0x0000040b` reproduces `1e 0b 04` only
         when the assembler's PC happens to match the one the target was
         resolved against; at any other address the same text is a different
         instruction, and the byte gate would catch it only if some OTHER byte
         moved.

    Gate 1 has three grades, reported separately because they are not equally
    strong evidence:
      A  the comment ALSO carries unidasm's rendering and it matches gate 3's.
      P  same, but the form is PC-RELATIVE and only the MNEMONIC matches: the
         source's comment resolves the target against the site's own address,
         while gate 3 harvests the rendering by BYTE STRING and so resolves it
         against wherever the linear decode happened to meet those bytes.
         `jr Z,0xfa7097` in the source is `jr Z,0xff7771` in the listing -- same
         two bytes, same instruction, different PC.  13 prom_a sites.  Dropping
         them would silently lose real unspelt code; accepting them unnormalised
         would accept a rendering that disagrees.  So the targets are normalised
         away and the grade records that it happened.
      B  the comment stops after the bytes.  Gates 2-4 still hold; only the
         human-readable cross-check is absent.

⚠ THE WORK LIST IS SUPPOSED TO EMPTY.  --selftest asserts INVARIANTS, never a
  pinned count: a pinned "N forms" turns green work into a red test.  What it
  asserts is that anything still listed is genuinely UNSPELLABLE, and that the
  census can see a form at all (positive control) and rejects a data row that
  merely looks like one (negative control).

⚠ prom_d IS NOT CENSUSED.  It is a data image linked at ORIGIN 0 (see
  `prom_d/prom_d.ld`); it contains no instructions and no sound-device access,
  so there is nothing for this instrument to weigh.  It has no committed
  listing for the same reason.  Its `.byte` comments are bare addresses and
  gate 1 rejects every one of them -- run with --include-prom-d to see that.

RUN:  python3 notes/sound/wsa1_unspellable_forms.py            # the three code images
      python3 notes/sound/wsa1_unspellable_forms.py --sites    # + file:line
      python3 notes/sound/wsa1_unspellable_forms.py --selftest
"""
import collections
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))            # .../wsa1
REPO = os.path.dirname(ROOT)                             # .../kn5000-roms-disasm
sys.path.insert(0, os.path.join(ROOT, "notes"))
from asm_source import image_files, _resolve, INCLUDE_RE  # noqa: E402

_spec = importlib.util.spec_from_file_location(
    "conv", os.path.join(REPO, "scripts", "converters",
                         "convert_unspellable_forms.py"))
conv = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(conv)

_bspec = importlib.util.spec_from_file_location(
    "wsa1_sound_boundary", os.path.join(HERE, "wsa1_sound_boundary.py"))
boundary = importlib.util.module_from_spec(_bspec)
_bspec.loader.exec_module(boundary)

# name, primary source, ROM, base address, committed unidasm listing
Image = collections.namedtuple("Image", "name primary rom base listing")
IMAGES = [
    Image("prom_a", "prom_a/wsa1_prom_a.s", "original_ROMs/wsa1_prom_a.ic12",
          0xF80000, "original_ROMs/wsa1_prom_a.ic12.unidasm"),
    Image("prom_b", "prom_b/wsa1_prom_b.s", "original_ROMs/wsa1_prom_b.ic13",
          0xF00000, "original_ROMs/wsa1_prom_b.ic13.unidasm"),
    Image("prom_c", "prom_c/wsa1_prom_c.s", "original_ROMs/wsa1_prom_c.ic28",
          0xF80000, "original_ROMs/wsa1_prom_c.ic28.unidasm"),
]
PROM_D = Image("prom_d", "prom_d/wsa1_prom_d.s", "original_ROMs/wsa1_prom_d.bin",
               0x000000, None)

# `\t.byte 0xc7, 0xe3, 0x99      ; F831FF  c7 e3 99   ld QW,A`
#                                  ^addr    ^echo      ^rendering (optional)
BYTELINE = re.compile(r'^\s*\.byte\s+([^;]*?)\s*;\s*(\S.*?)\s*$')
CODECOMMENT = re.compile(
    r'^([0-9A-Fa-f]{6})\s+((?:[0-9a-f]{2}\s)*[0-9a-f]{2})(?:\s\s+(\S.*?))?\s*$')
UNILINE = re.compile(r'^([0-9a-f]{4,6}): ((?:[0-9a-f]{2} )+)\s+(\S.*?)\s*$')
LABEL_RE = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*):')
NUM = re.compile(r'0x[0-9A-Fa-f]+')


def _norm(s):
    return "".join(s.split()).lower()


def unidasm_forms(listing):
    """{byte string: rendering} for every line of the committed listing.

    Keyed on the BYTES, so where in the linear decode the framing was found does
    not matter -- TLCS-900 decoding is context-free, and asking whether a byte
    string is one instruction is a question about the byte string alone.
    """
    out = {}
    with open(os.path.join(ROOT, listing), errors="replace") as fh:
        for line in fh:
            m = UNILINE.match(line.rstrip())
            if m:
                out[" ".join(m.group(2).split())] = m.group(3)
    return out


def image_lines_with_origin(primary):
    """(path, lineno, text) for the token stream the assembler sees.

    asm_source.image_lines() flattens the includes and so loses file:line, which
    a work list has to print.  This mirrors its expansion exactly -- ROOT-first
    resolution, a repeated definitions `.inc` expanded once -- and keeps the
    origin of each line.
    """
    files = image_files(ROOT, primary)
    text = {p: open(p, encoding="utf-8").read().split("\n") for p in files}
    done = set()

    def emit(path):
        if path in done:
            return
        done.add(path)
        for i, ln in enumerate(text[path], 1):
            m = INCLUDE_RE.match(ln)
            if m:
                yield from emit(_resolve(ROOT, m.group(1), path))
            else:
                yield path, i, ln

    yield from emit(files[0])


def sound_routines():
    """{image name: {routine label that touches a sound device}}.

    The definition of "sound routine" is not this file's to make; it is
    wsa1_sound_boundary.py's, and this imports it so the two cannot drift.
    """
    out = {}
    for image, d in boundary.collect().items():
        out[image] = {a.label for a in d["acc"]}
    return out


Site = collections.namedtuple("Site", "path line addr bytes rendering grade routine")


def census(img):
    """-> {form: [Site, ...]}, every gate passed.  Also -> rejected counts."""
    forms = unidasm_forms(img.listing) if img.listing else {}
    rom = open(os.path.join(ROOT, img.rom), "rb").read()
    out = collections.defaultdict(list)
    rej = collections.Counter()

    routine = "<top>"
    for path, lineno, ln in image_lines_with_origin(img.primary):
        lm = LABEL_RE.match(ln)
        if lm:
            lbl = lm.group(1)
            if not boundary.is_local(lbl, routine):
                routine = lbl
        m = BYTELINE.match(ln)
        if not m:
            continue
        try:
            bs = [int(x, 0) for x in m.group(1).split(",") if x.strip()]
        except ValueError:
            rej["operands not integers"] += 1
            continue
        if not bs or not all(0 <= b <= 0xFF for b in bs):
            rej["operands not bytes"] += 1
            continue

        # GATE 1 -- the comment is this tree's code convention, and its byte
        # echo is EXACTLY the operands.
        cm = CODECOMMENT.match(m.group(2))
        if not cm:
            rej["comment is not ADDR + byte echo"] += 1
            continue
        want = " ".join(f"{b:02x}" for b in bs)
        echo = " ".join(cm.group(2).split())
        if echo != want:
            # ⚠ `db` is two hex digits, so a comment that says `; ADDR  db` --
            # unidasm's undecodable marker, copied verbatim -- parses as an echo
            # of the byte 0xDB.  All 7 prom_b hits are that, not a wrong echo.
            rej["comment carries unidasm's `db` marker, not a byte echo"
                if echo == "db" else
                "byte echo disagrees with the operands"] += 1
            continue
        addr = int(cm.group(1), 16)

        # GATE 2 -- the ORIGINAL ROM really holds those bytes at that address.
        off = addr - img.base
        if not (0 <= off and off + len(bs) <= len(rom)):
            rej["address outside this image"] += 1
            continue
        if list(rom[off:off + len(bs)]) != bs:
            rej["ROM disagrees at that address"] += 1
            continue

        # GATE 3 -- the committed listing frames exactly those bytes as ONE
        # instruction.
        rend = forms.get(want)
        if rend is None:
            rej["unidasm does not frame these bytes as one instruction"] += 1
            continue
        if rend.split()[0] in ("db", "dw", "dd"):
            rej["unidasm cannot decode these bytes either (renders `%s`)"
                % rend.split()[0]] += 1
            continue

        # GATE 1, grade: does the comment also carry that rendering?
        if cm.group(3) is None:
            grade = "B"
        elif _norm(cm.group(3)).startswith(_norm(rend)):
            grade = "A"
        elif _norm(NUM.sub("N", cm.group(3))).startswith(
                _norm(NUM.sub("N", rend))):
            grade = "P"                   # PC-relative; see the header
        else:
            rej["comment rendering disagrees with unidasm"] += 1
            continue

        out[NUM.sub("N", rend).strip()].append(
            Site(os.path.relpath(path, ROOT), lineno, addr, bs, rend, grade,
                 routine))
    return out, rej


# ⚠ PC-RELATIVE.  Their operand is an ADDRESS in the rendering and a
# DISPLACEMENT in the encoding, so the same text means different bytes at
# different PCs.  Never spelt from a rendering.
PCREL = ("jr", "jrl", "calr", "djnz")


# unidasm prints an 8-bit displacement UNSIGNED -- `srl (XIZ+0xfc)` -- and
# llvm-mc reads 0xFC as 252, which does not fit a signed d8, so it widens to the
# (Xrr+d16) form: `c3 f9 fc 00 7f`, five bytes where the ROM has three.  The
# same slot spelt `(xiz-4)` gives `8e fc 7f` exactly, and that IS this tree's
# own dialect -- prom_c's split sources already write `(xiz-4)`.  So a rendering
# whose displacement is >= 0x80 gets a second try, signed.  The round-trip is
# still the only judge; nothing here is trusted because it looks right.
DISP = re.compile(r'\((x(?:wa|bc|de|hl|ix|iy|iz|sp))\+0x([0-9a-f]{2})\)')


def _signed_disp(text):
    """The same text with any d8 >= 0x80 written as a negative, or None."""
    if not DISP.search(text):
        return None
    out = DISP.sub(lambda m: "(%s%+d)" % (m.group(1), int(m.group(2), 16) - 256)
                   if int(m.group(2), 16) >= 0x80 else m.group(0), text)
    return out if out != text else None


def _roundtrip(text, bs):
    got = conv.assemble([text])
    if got is None:
        return f"`{text}` did not assemble", False
    if got[0] != bs:
        return (f"`{text}` assembles to "
                + " ".join(f"{b:#04x}" for b in got[0])), False
    return text, True


def spelling(bs, rendering=None):
    """-> (text, True) if llvm-mc reproduces these EXACT bytes, else (why, False).

    Route 1 is the byte decoder; route 2 is unidasm's rendering typed verbatim.
    `rendering` is the SITE's own rendering where the caller has one -- a form's
    exemplar carries one displacement and its siblings carry others.
    """
    text = conv.decode(bs)
    if text is not None:
        return _roundtrip(text, bs)
    if rendering is None:
        return "no decoder for this form, and no rendering to try", False
    if rendering.split()[0].lower() in PCREL:
        return ("no decoder for this form; PC-relative, so its rendering "
                "cannot be typed verbatim"), False
    why, ok = _roundtrip(rendering.lower(), bs)
    if ok:
        return why, True
    signed = _signed_disp(rendering.lower())
    if signed is not None:
        why2, ok2 = _roundtrip(signed, bs)
        if ok2:
            return why2, True
        why = f"{why}; as `{signed}`, {why2.split(', ', 1)[-1]}"
    return f"no decoder for this form, and {why}", False


def report(show_sites, images):
    snd = sound_routines()
    tot = collections.Counter()
    print("WSA1 UNSPELT INSTRUCTION FORMS -- sites still carried as `.byte`")
    print("=" * 78)
    for img in images:
        c, rej = census(img)
        inside = snd.get(img.name, set())
        sites = sum(len(v) for v in c.values())
        nb = sum(len(s.bytes) for v in c.values() for s in v)
        sound_sites = [s for v in c.values() for s in v if s.routine in inside]
        unspelt = {f: v for f, v in c.items()
                   if not spelling(v[0].bytes, v[0].rendering)[1]}
        u_sites = sum(len(v) for v in unspelt.values())
        u_sound = [s for v in unspelt.values() for s in v if s.routine in inside]
        tot["sites"] += sites
        tot["bytes"] += nb
        tot["unspelt"] += u_sites
        tot["unspelt_sound"] += len(u_sound)
        tot["sound"] += len(sound_sites)

        print(f"\n=== {img.name} ===")
        if img.listing is None:
            print("    no committed unidasm listing -- gate 3 rejects everything")
        print(f"  {sites} certified site(s), {nb} byte(s), {len(c)} form(s); "
              f"{len(sound_sites)} site(s) inside a sound routine")
        print(f"  {u_sites} of those site(s) have NO SPELLING, "
              f"{len(u_sound)} of them inside a sound routine")
        for form, hits in sorted(c.items(), key=lambda kv: -len(kv[1])):
            text, ok = spelling(hits[0].bytes, hits[0].rendering)
            in_snd = [h for h in hits if h.routine in inside]
            grades = collections.Counter(h.grade for h in hits)
            mark = "spellable" if ok else "★ NO SPELLING"
            print(f"    {len(hits):4d} x {len(hits[0].bytes)}B  {form}"
                  f"   [grade {'/'.join(f'{g}:{n}' for g, n in sorted(grades.items()))}]"
                  + (f"   ★ {len(in_snd)} IN A SOUND ROUTINE" if in_snd else ""))
            print(f"           {' '.join(f'{b:02x}' for b in hits[0].bytes)}   "
                  f"{mark}: {text}")
            if show_sites:
                for h in hits:
                    star = " ★sound" if h.routine in inside else ""
                    print(f"             {h.path}:{h.line}  {h.addr:06X}  "
                          f"{h.routine}{star}")
        if not c:
            print("    (none -- every instruction in this image is spelt)")
        if rej:
            print("  rejected by the gates:")
            for why, n in rej.most_common():
                print(f"    {n:7d}  {why}")
    print("\n" + "=" * 78)
    print(f"TOTAL {tot['sites']} certified site(s), {tot['bytes']} byte(s)")
    print(f"      {tot['sound']} inside a sound routine")
    print(f"★     {tot['unspelt']} site(s) with NO SPELLING, "
          f"of which {tot['unspelt_sound']} inside a sound routine")
    return 0


def selftest():
    """INVARIANTS.  None of them is a pinned count."""
    bad = 0

    # 1. ROOT/REPO are derived, not hard-coded, and point at these trees.
    if not os.path.isfile(os.path.join(ROOT, "Makefile")) or \
       not os.path.isdir(os.path.join(REPO, "scripts", "converters")):
        print(f"FAIL  paths derived from __file__ are wrong: {ROOT} / {REPO}")
        bad += 1

    # 2. POSITIVE CONTROL: the census must be able to SEE a form.  Without this
    #    an empty work list could just mean the matcher is broken.
    forms = unidasm_forms(IMAGES[0].listing)
    probe = "c7 3c 99"                      # prom_a F819C2, `ld RL3,A`
    if forms.get(probe) is None:
        print(f"FAIL  the committed listing has no entry for {probe}")
        bad += 1
    total = sum(len(v) for img in IMAGES for v in census(img)[0].values())
    if total == 0:
        print("FAIL  the census sees nothing at all in three code images; "
              "a positive control that cannot fire is not a control")
        bad += 1

    # 3. NEGATIVE CONTROL: a data row must be rejected.  These are the exact
    #    bytes and address of a REAL unspelt site, so what is being tested is
    #    the comment convention alone.
    real = "\t.byte 0xc7, 0x3c, 0x99   ; F819C2  c7 3c 99   ld RL3,A\n"
    fake = "\t.byte 0xc7, 0x3c, 0x99   ; F819C2\n"
    lie = "\t.byte 0xc7, 0x3c, 0x99   ; F819C2  c7 3c 99   velocity curve row 3\n"
    for text, want, what in ((real, True, "a genuine unspelt line"),
                             (fake, False, "a bare-address data comment"),
                             (lie, False, "a data-table annotation")):
        m = BYTELINE.match(text)
        cm = CODECOMMENT.match(m.group(2)) if m else None
        ok = bool(cm) and cm.group(3) is not None and \
            _norm(cm.group(3)).startswith(_norm(forms[probe]))
        if ok != want:
            print(f"FAIL  {what} was graded {ok}, expected {want}")
            bad += 1

    # 3b. `db` IS NOT AN INSTRUCTION.  unidasm's undecodable marker must not be
    #     counted as a form the assembler failed to spell.
    if forms.get("80 0f") != "db":
        print("FAIL  the `db` probe is no longer unidasm's marker; "
              "check the listing before trusting gate 3")
        bad += 1
    for f, hits in census(IMAGES[0])[0].items():
        if f.split()[0] in ("db", "dw", "dd"):
            print(f"FAIL  `{f}` reached the census; `db` is not an instruction")
            bad += 1

    # 3c. THE PC-RELATIVE GRADE IS NOT A BLANKET PASS.  Normalising the target
    #     must not let a DIFFERENT mnemonic through.
    if _norm(NUM.sub("N", "jr Z,0xfa7097")).startswith(
            _norm(NUM.sub("N", "jr NZ,0xff7771"))):
        print("FAIL  target normalisation accepted a different condition code")
        bad += 1

    # 4. GATE 2 IS LIVE: the ROM check must reject a real byte string placed at
    #    an address that does not hold it.
    rom = open(os.path.join(ROOT, IMAGES[0].rom), "rb").read()
    off = 0xF819C2 - IMAGES[0].base
    if list(rom[off:off + 3]) != [0xc7, 0x3c, 0x99]:
        print("FAIL  the ROM does not hold the probe's bytes at its address")
        bad += 1
    if list(rom[off + 1:off + 4]) == [0xc7, 0x3c, 0x99]:
        print("FAIL  the ROM check cannot discriminate; it matches everywhere")
        bad += 1

    # 5. THE WORK LIST IS THE TEST.  Anything still listed must be genuinely
    #    unspellable -- if a form has a spelling, the tree should carry it as an
    #    instruction, not as `.byte`.  An EMPTY list is the finished state and
    #    passes; it does not go red when the work succeeds.
    for img in IMAGES:
        for form, hits in census(img)[0].items():
            text, ok = spelling(hits[0].bytes, hits[0].rendering)
            if ok:
                print(f"FAIL  {img.name}: `{form}` is spellable as `{text}` and "
                      f"is still .byte at {hits[0].path}:{hits[0].line}")
                bad += 1

    # 5b. THE PC-RELATIVE REFUSAL IS LIVE.  `1e 0b 04` is `calr 0x0000040b`,
    #     and typed verbatim it reproduces those bytes at PC 0 and nowhere else.
    #     `spelling` must refuse it even though the round-trip would pass.
    if _roundtrip("calr 0x0000040b", [0x1e, 0x0b, 0x04])[1] is not True:
        print("FAIL  the PC-relative probe no longer round-trips at PC 0; "
              "the refusal below is no longer testing anything")
        bad += 1
    if spelling([0x1e, 0x0b, 0x04], "calr 0x0000040b")[1]:
        print("FAIL  a PC-relative form was spelt from its rendering")
        bad += 1

    # 5c. THE SIGNED-DISPLACEMENT ROUTE, and its refusal to fire on a d8 that
    #     already fits.  `8e fc 7f` is `srl (XIZ+0xfc)` and needs it; `8e 08 7f`
    #     is `srl (XIZ+0x08)` and must be left alone.
    if _signed_disp("srl (xiz+0xfc)") != "srl (xiz-4)":
        print("FAIL  the signed-displacement rewrite is wrong: "
              + repr(_signed_disp("srl (xiz+0xfc)")))
        bad += 1
    if _signed_disp("srl (xiz+0x08)") is not None:
        print("FAIL  a displacement that already fits was rewritten")
        bad += 1
    if not spelling([0x8e, 0xfc, 0x7f], "srl (XIZ+0xfc)")[1]:
        print("FAIL  the signed-displacement route did not spell `8e fc 7f`")
        bad += 1

    # 6. NEGATIVE CONTROL for `spelling`: bytes one bit off must not round-trip
    #    to the same text.
    if conv.decode([0xc7, 0x3c, 0x99]) == conv.decode([0xc7, 0x3c, 0x9b]):
        print("FAIL  two different encodings produced the same spelling")
        bad += 1

    # 7. prom_d really is out of scope: the gates reject all of it.
    if sum(len(v) for v in census(PROM_D)[0].values()):
        print("FAIL  prom_d, a data image with no listing, yielded sites")
        bad += 1

    print("selftest: " + ("OK" if bad == 0 else f"{bad} FAILURE(S)"))
    return 1 if bad else 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    imgs = list(IMAGES) + ([PROM_D] if "--include-prom-d" in sys.argv else [])
    sys.exit(report("--sites" in sys.argv, imgs))
