/**
 * naka_normal_mode.c — NAKA widget descriptors (fully decoded)
 *
 * Base ROM address: 0xED333C
 * Total size: 1168 bytes
 * Auto-generated by scripts/naka_struct_decode.py
 */

#include "naka_types.h"

/* ── External symbols (resolved by linker script) ── */

extern const char CRTC_LINE_COMPARE;
extern const char Naka_PresentationRootState;

#define BASE  0x00ED333Cu

/* NAKA class TtlScreen -- class id 0x01600034 (Class table slot 0x160, entry 52),
 * parent Screen; allsize 42.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
/* NakaWidget_N1's element (scripts/converters/nakarest_reviewed_slices.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;
    uint16_t super;
    uint16_t sub;
    uint16_t next;
    uint16_t prev;
    uint16_t flag;
    int16_t rect[4];
} NakaWidget_N1_t;

typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint32_t exit;              /* +26 a */
    uint32_t window;            /* +30 r */
    uint32_t title;             /* +34 X */
    uint32_t icon;              /* +38 b */
} naka_cls_TtlScreen_t;

/* NAKA class NormScreen -- class id 0x01620000 (Class table slot 0x162, entry 0),
 * parent TtlScreen; allsize 42.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint32_t exit;              /* +26 a */
    uint32_t window;            /* +30 r */
    uint32_t title;             /* +34 X */
    uint32_t icon;              /* +38 b */
} naka_cls_NormScreen_t;

/* NAKA class AcTempoBox -- class id 0x01600014 (Class table slot 0x160, entry 20),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_AcTempoBox_t;

/* NAKA class AcPmemName -- class id 0x0160003B (Class table slot 0x160, entry 59),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_AcPmemName_t;

/* NAKA class AcRhythmName -- class id 0x0160003A (Class table slot 0x160, entry 58),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_AcRhythmName_t;

/* NAKA class AcSoundName -- class id 0x0160002A (Class table slot 0x160, entry 42),
 * parent PsParaBox; allsize 38.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
    uint16_t part;              /* +36 u */
} naka_cls_AcSoundName_t;

/* NAKA class StringBox -- class id 0x01600037 (Class table slot 0x160, entry 55),
 * parent Box; allsize 38.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint32_t str;               /* +26 X */
    uint32_t font;              /* +30 c */
    uint16_t fontcolor;         /* +34 ^ */
    uint16_t alignment;         /* +36 d */
} naka_cls_StringBox_t;

/* NAKA class TransposeBox -- class id 0x01620003 (Class table slot 0x162, entry 3),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_TransposeBox_t;

/* NAKA class ChordBox -- class id 0x01620004 (Class table slot 0x162, entry 4),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_ChordBox_t;

/* NAKA class AcLswBox -- class id 0x01600013 (Class table slot 0x160, entry 19),
 * parent PsParaBox; allsize 44.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
    uint32_t func;              /* +36 j */
    uint32_t data;              /* +40 n */
} naka_cls_AcLswBox_t;

/* NAKA class IvWindowPageControl -- class id 0x0162000C (Class table slot 0x162, entry 12),
 * parent PsInvisibleBox; allsize 26.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint32_t page;              /* +22 n */
} naka_cls_IvWindowPageControl_t;

/* NAKA class FreeSplitBox -- class id 0x01620005 (Class table slot 0x162, entry 5),
 * parent PsParaBox; allsize 36.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t color;             /* +22 ^ */
    uint16_t border;            /* +24 _ */
    uint16_t index;             /* +26 A */
    uint32_t font;              /* +28 c */
    uint16_t fontcolor;         /* +32 ^ */
    uint16_t align;             /* +34 d */
} naka_cls_FreeSplitBox_t;

/* NAKA class IvPageOverWr -- class id 0x0162001B (Class table slot 0x162, entry 27),
 * parent PsInvisibleBox; allsize 28.  Field names and type characters are the
 * class chain's own propname / propdata (see THE CLASS SYSTEM in
 * scripts/analysis/nakarest_objtab_map.py). */
typedef struct __attribute__((packed)) {
    uint32_t class_;            /* +0 M */
    uint16_t super;             /* +4 [ */
    uint16_t sub;               /* +6 [ */
    uint16_t next;              /* +8 [ */
    uint16_t prev;              /* +10 [ */
    uint16_t flag;              /* +12 ] */
    int16_t rect[4];          /* +14 P */
    uint16_t page;              /* +22 A */
    uint32_t window;            /* +24 t */
} naka_cls_IvPageOverWr_t;

typedef struct __attribute__((packed)) {
    char TEST6FUNC_str[10];
    char TEST4FUNC_str[10];
    char TEST3FUNC_str[10];
    char TEST2FUNC_str[10];
    char MainWallSetFlashFunc_str[22];
    char MainTimeFlashFunc_str[18];
    char MainMssSetUp_str[14];
    char FswAsIniFunc_str[14];
    char CntIniFunc_code[12];
    char MainSysControl_name[16];
    char OneTchFUNC_code[12];
    char MainPmGet_name[10];
    char MainChordPre_str[14];
    char MainGetRhyGrpName_str[18];
    char MainGetSndGrpName_str[18];
    char MainGetRhyName_str[16];
    char MainRvariIni_str[14];
    char MainGetSndName_str[16];
    char MainSvariIni_str[14];
    char MainVariSet_str[12];
    /* element 0 of Viewable slot 0x1 "Normal": TtlScreen (class id 0x01600034) */
    naka_cls_TtlScreen_t Normal;
    char Normal_text[8];
    /* element 1 of Viewable slot 0x1 "normal": NormScreen (class id 0x01620000) */
    naka_cls_NormScreen_t normal;
    uint8_t field_0174;
    uint8_t field_0175;
    /* element 2 of Viewable slot 0x1: AcTempoBox (class id 0x01600014) */
    naka_cls_AcTempoBox_t normal_AcTempoBox;
    /* element 3 of Viewable slot 0x1: AcPmemName (class id 0x0160003B) */
    naka_cls_AcPmemName_t normal_AcPmemName;
    /* element 4 of Viewable slot 0x1: AcRhythmName (class id 0x0160003A) */
    naka_cls_AcRhythmName_t normal_AcRhythmName;
    /* element 5 of Viewable slot 0x1: AcSoundName (class id 0x0160002A) */
    naka_cls_AcSoundName_t normal_AcSoundName;
    /* element 6 of Viewable slot 0x1: AcSoundName (class id 0x0160002A) */
    naka_cls_AcSoundName_t normal_AcSoundName_2;
    /* element 7 of Viewable slot 0x1: StringBox (class id 0x01600037) */
    naka_cls_StringBox_t RIGHT2_StringBox;
    char RIGHT2_str[8];
    /* element 8 of Viewable slot 0x1: AcSoundName (class id 0x0160002A) */
    naka_cls_AcSoundName_t normal_AcSoundName_3;
    /* element 9 of Viewable slot 0x1: StringBox (class id 0x01600037) */
    naka_cls_StringBox_t RIGHT1_StringBox;
    char RIGHT1_str[8];
    /* element 10 of Viewable slot 0x1: StringBox (class id 0x01600037) */
    naka_cls_StringBox_t LEFT_StringBox;
    char LEFT_str[6];
    /* element 11 of Viewable slot 0x1: StringBox (class id 0x01600037) */
    naka_cls_StringBox_t RHYTHM_StringBox;
    char RHYTHM_str[8];
    /* element 12 of Viewable slot 0x1: TransposeBox (class id 0x01620003) */
    naka_cls_TransposeBox_t normal_TransposeBox;
    /* element 13 of Viewable slot 0x1: ChordBox (class id 0x01620004) */
    naka_cls_ChordBox_t normal_ChordBox;
    /* element 14 of Viewable slot 0x1: AcLswBox (class id 0x01600013) */
    naka_cls_AcLswBox_t normal_AcLswBox;
    /* element 15 of Viewable slot 0x1: IvWindowPageControl (class id 0x0162000C) */
    naka_cls_IvWindowPageControl_t normal_IvWindowPageControl;
    /* element 16 of Viewable slot 0x1: FreeSplitBox (class id 0x01620005) */
    naka_cls_FreeSplitBox_t normal_FreeSplitBox;
    /* element 17 of Viewable slot 0x1: IvPageOverWr (class id 0x0162001B) */
    naka_cls_IvPageOverWr_t normal_IvPageOverWr;
    /* element 18 of Viewable slot 0x1: IvPageOverWr (class id 0x0162001B) */
    naka_cls_IvPageOverWr_t normal_IvPageOverWr_2;
    /* element 19 of Viewable slot 0x1: IvPageOverWr (class id 0x0162001B) */
    naka_cls_IvPageOverWr_t normal_IvPageOverWr_3;
    /* element 20 of Viewable slot 0x1: IvPageOverWr (class id 0x0162001B) */
    naka_cls_IvPageOverWr_t normal_IvPageOverWr_4;
    /* element 21 of Viewable slot 0x1: IvPageOverWr (class id 0x0162001B) */
    naka_cls_IvPageOverWr_t normal_IvPageOverWr_5;
    /* element 22 of Viewable slot 0x1: IvPageOverWr (class id 0x0162001B) */
    naka_cls_IvPageOverWr_t normal_IvPageOverWr_6;
    uint8_t bytes_0464[22];  /* 0x47 */
    /* zero padding */
    /* Window view record "N1", first 22 bytes (the Viewable part); color..child continue in extensions/extension_data.s */
    NakaWidget_N1_t NakaWidget_N1;
} naka_normal_mode_t;

#define SELF(field) \
    ((uint32_t)(BASE + __builtin_offsetof(naka_normal_mode_t, field)))

_Static_assert(sizeof(naka_normal_mode_t) == 1168,
    "naka_normal_mode must be exactly 1168 bytes");

const naka_normal_mode_t naka_normal_mode_data
    __attribute__((section(".text"), used)) = {

    .TEST6FUNC_str = "TEST6FUNC",

    .TEST4FUNC_str = "TEST4FUNC",

    .TEST3FUNC_str = "TEST3FUNC",

    .TEST2FUNC_str = "TEST2FUNC",

    .MainWallSetFlashFunc_str = ALIGNED_STRING("MainWallSetFlashFunc"),

    .MainTimeFlashFunc_str = "MainTimeFlashFunc",

    .MainMssSetUp_str = ALIGNED_STRING("MainMssSetUp"),

    .FswAsIniFunc_str = ALIGNED_STRING("FswAsIniFunc"),

    .CntIniFunc_code = ALIGNED_STRING("CntIniFunc"),

    .MainSysControl_name = ALIGNED_STRING("MainSysControl"),

    .OneTchFUNC_code = ALIGNED_STRING("OneTchFUNC"),

    .MainPmGet_name = "MainPmGet",

    .MainChordPre_str = ALIGNED_STRING("MainChordPre"),

    .MainGetRhyGrpName_str = "MainGetRhyGrpName",

    .MainGetSndGrpName_str = "MainGetSndGrpName",

    .MainGetRhyName_str = ALIGNED_STRING("MainGetRhyName"),

    .MainRvariIni_str = ALIGNED_STRING("MainRvariIni"),

    .MainGetSndName_str = ALIGNED_STRING("MainGetSndName"),

    .MainSvariIni_str = ALIGNED_STRING("MainSvariIni"),

    .MainVariSet_str = "MainVariSet",

    .Normal = {
        .class_ = 0x01600034,
        .super = NAKA_NONE,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x000A,
        .rect = { 0, 0, 319, 239 },
        .color = 0x00FF,
        .border = 0x0000,
        .exit = 0x01A00000,
        .window = 0x0003F3F8,
        .title = SELF(Normal_text),
        .icon = 0x00000001,
    },

    .Normal_text = ALIGNED_STRING("NORMAL"),

    .normal = {
        .class_ = 0x01620000,
        .super = NAKA_NONE,
        .sub = 2,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x000A,
        .rect = { 0, 0, 319, 239 },
        .color = 0x00FF,
        .border = 0x0001,
        .exit = 0x01A00000,
        .window = 0x0003F3FC,
        .title = SELF(field_0174),
        .icon = 0x00000000,
    },

    .field_0174 = 0x00,

    .field_0175 = 0xFF,

    .normal_AcTempoBox = {
        .class_ = 0x01600014,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 3,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 0, 67, 79, 86 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000004,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .normal_AcPmemName = {
        .class_ = 0x0160003B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 4,
        .prev = 2,
        .flag = 0x0008,
        .rect = { 8, 3, 312, 22 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000004,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .normal_AcRhythmName = {
        .class_ = 0x0160003A,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 5,
        .prev = 3,
        .flag = 0x0008,
        .rect = { 4, 40, 123, 59 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000001,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .normal_AcSoundName = {
        .class_ = 0x0160002A,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 6,
        .prev = 4,
        .flag = 0x0008,
        .rect = { 172, 36, 311, 55 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000001,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .part = 0x0000,
    },

    .normal_AcSoundName_2 = {
        .class_ = 0x0160002A,
        .super = 1,
        .sub = 7,
        .next = 8,
        .prev = 5,
        .flag = 0x0008,
        .rect = { 172, 68, 311, 87 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000001,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .part = 0x0001,
    },

    .RIGHT2_StringBox = {
        .class_ = 0x01600037,
        .super = 6,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 176, 60, 220, 70 },
        .color = 0x0002,
        .border = 0x0000,
        .str = SELF(RIGHT2_str),
        .font = 0x00000003,
        .fontcolor = 0x00FF,
        .alignment = 0x0000,
    },

    .RIGHT2_str = ALIGNED_STRING("RIGHT2"),

    .normal_AcSoundName_3 = {
        .class_ = 0x0160002A,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 9,
        .prev = 6,
        .flag = 0x0008,
        .rect = { 172, 100, 311, 119 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000001,
        .fontcolor = 0x00FF,
        .align = 0x0000,
        .part = 0x0002,
    },

    .RIGHT1_StringBox = {
        .class_ = 0x01600037,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 10,
        .prev = 8,
        .flag = 0x0008,
        .rect = { 176, 28, 220, 38 },
        .color = 0x0002,
        .border = 0x0000,
        .str = SELF(RIGHT1_str),
        .font = 0x00000003,
        .fontcolor = 0x00FF,
        .alignment = 0x0000,
    },

    .RIGHT1_str = ALIGNED_STRING("RIGHT1"),

    .LEFT_StringBox = {
        .class_ = 0x01600037,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 11,
        .prev = 9,
        .flag = 0x0008,
        .rect = { 176, 92, 220, 102 },
        .color = 0x0002,
        .border = 0x0000,
        .str = SELF(LEFT_str),
        .font = 0x00000003,
        .fontcolor = 0x00FF,
        .alignment = 0x0000,
    },

    .LEFT_str = ALIGNED_STRING("LEFT"),

    .RHYTHM_StringBox = {
        .class_ = 0x01600037,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 12,
        .prev = 10,
        .flag = 0x0008,
        .rect = { 12, 28, 51, 38 },
        .color = 0x000C,
        .border = 0x0000,
        .str = SELF(RHYTHM_str),
        .font = 0x00000003,
        .fontcolor = 0x00FF,
        .alignment = 0x0000,
    },

    .RHYTHM_str = ALIGNED_STRING("RHYTHM"),

    .normal_TransposeBox = {
        .class_ = 0x01620003,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 13,
        .prev = 11,
        .flag = 0x0008,
        .rect = { 87, 67, 131, 86 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000004,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .normal_ChordBox = {
        .class_ = 0x01620004,
        .super = 1,
        .sub = 14,
        .next = 15,
        .prev = 12,
        .flag = 0x0008,
        .rect = { 3, 87, 139, 115 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000004,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .normal_AcLswBox = {
        .class_ = 0x01600013,
        .super = 13,
        .sub = NAKA_NONE,
        .next = NAKA_NONE,
        .prev = NAKA_NONE,
        .flag = 0x0008,
        .rect = { 6, 90, 37, 121 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000000,
        .fontcolor = 0x0000,
        .align = 0x0000,
        .func = 0x0122001A,
        .data = 0x0003F400,
    },

    .normal_IvWindowPageControl = {
        .class_ = 0x0162000C,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 16,
        .prev = 13,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .page = 0x0003F402,
    },

    .normal_FreeSplitBox = {
        .class_ = 0x01620005,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 17,
        .prev = 15,
        .flag = 0x0008,
        .rect = { 34, 116, 113, 127 },
        .color = 0x00F5,
        .border = 0x0000,
        .index = 0xFFFF,
        .font = 0x00000003,
        .fontcolor = 0x00FF,
        .align = 0x0000,
    },

    .normal_IvPageOverWr = {
        .class_ = 0x0162001B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 18,
        .prev = 16,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .page = 0x0001,
        .window = 0x00010018,
    },

    .normal_IvPageOverWr_2 = {
        .class_ = 0x0162001B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 19,
        .prev = 17,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .page = 0x0002,
        .window = 0x00010021,
    },

    .normal_IvPageOverWr_3 = {
        .class_ = 0x0162001B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 20,
        .prev = 18,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .page = 0x0003,
        .window = 0x00010027,
    },

    .normal_IvPageOverWr_4 = {
        .class_ = 0x0162001B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 21,
        .prev = 19,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .page = 0x0004,
        .window = 0x00010030,
    },

    .normal_IvPageOverWr_5 = {
        .class_ = 0x0162001B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 22,
        .prev = 20,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .page = 0x0005,
        .window = 0x00010039,
    },

    .normal_IvPageOverWr_6 = {
        .class_ = 0x0162001B,
        .super = 1,
        .sub = NAKA_NONE,
        .next = 23,
        .prev = 21,
        .flag = 0x0018,
        .rect = { 0, 0, 31, 31 },
        .page = 0x0006,
        .window = 0x0001003C,
    },

    .bytes_0464 = { 0x47, 0x00, 0x60, 0x01, 0x01, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x16, 0x00, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1F, 0x00, 0x1F, 0x00 },

    .NakaWidget_N1 = { 0x01600035, 0xFFFF, 0x0019, 0xFFFF, 0xFFFF, 0x0008, { 0, 127, 319, 236 } },

};

#undef SELF
#undef BASE
