export const meta = {
  name: 'wave3-docs',
  description: 'Bring technics-docs up to date with the Wave 2 findings (two writers in worktrees + two fact-checkers)',
  phases: [{ title: 'Write' }, { title: 'Fact-check' }],
}
const DIS = '/home/fsanches/compartilhado/kn5000-roms-disasm'
const W = '/home/fsanches/compartilhado/disasm-lanes'
const COMMON = (wt, br) => `You update the Jekyll documentation site for the Technics KN5000 / SX-WSA1R reverse-engineering project. Your worktree: ${W}/${wt} (branch ${br} of /home/fsanches/compartilhado/technics-docs). Work ONLY there (prefix commands with cd ${W}/${wt} &&). Read its CLAUDE.md first: the site is NOT a changelog -- facts go on the page that owns the subject, stated as current knowledge, with the evidence (script / notes path in the disassembly repo) that reproduces them; open questions go to questions.md; every new page needs an entry in _data/navigation.yml. Symbol names you quote must exist in the CURRENT disassembly sources in ${DIS} (verify each with \`command grep -rn NAME ${DIS}/v10/maincpu ...\`; the grep wrapper skips latin-1 files, always use \`command grep\`) -- a different agent is committing assembler-spelling changes to ${DIS} right now, so read it but NEVER write to it. Build-check before every commit: \`JEKYLL_NO_BUNDLER_REQUIRE=true jekyll build -q -d ${W}/docs-site-${wt}\` must exit 0 (bundle exec does not work here). Commit granularly with \`Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>\`; name files in git add; never push.

SOURCE MATERIAL (read it; do not invent): ${DIS}/notes/lanes/wave2-2026-09-25/ -- README.md (headline figures), WAVE3-LEADS.md (every finding, grouped), lane-reports/<lane>.json (each lane's measured figures, what it could not do, leads), census-after-wave2.txt; the notes/ and scripts/ each lane committed (paths in the reports); and the merged sources themselves. Where a report says a claim is unverified or an admission remains, say so on the page.`

const KN = `YOUR PAGES: everything KN5000 (main CPU, sub CPU, table data, custom data, HD-AE5000). Mandatory items:
1. EVENT CODE FRESHNESS POLICY (strict): event-codes.md gets 0x01C00014 = mode request (param 0x0180nnnn) and 0x01C00015/16 = title requests (0x01A0nnnn; 0x7F TT_HDDEXT, 0xEE TT_MESAGE), with dispatch paths; also update hdae5000-homebrew.md if handler registration/activation is affected, and /home/fsanches/compartilhado/Mines/CLAUDE.md if applicable (that repo has other people's untracked files -- commit ONLY the file you edit, by name, and nothing else).
2. HD-AE5000 corrections disproved by the code (lane hdae): hdae5000-filesystem.md vtable (+0x0100 SendEvent not SetDisplayCell, +0x0124 ApPostEvent not RegisterEventHandler, +0x050C GetNamingWindowID); boot-sequence.md Table B (+0x0100/0104/0108 are GetAdr_sqbtof/sq_beadt/sqsrtc, the 0x0270 call is RegisterTitle(0x7F "TT_HDDEXT")); memory-map (0x23A19E lyric box object; 0x23A0AA six 40-byte lyric lines); "PPI port 0x016000nn" is a proc class id; module scheme (object-table index = kind + module: root 0, Hama 9, HD-AE5000 0x0A); the lyric file format (one-track SMF, "TLhd"/"TLtr" chunks; Lyrics_CheckFile header checks are dead code) -- a section on the right page (or a new page with a nav entry).
3. The NAKA widget class system (lanes nakabig + nakarest): class id = table_id<<16|index = the first word of every record, 292 ClassProc descriptors, sig letters -> property sizes, propname -> field names; record words +4 parent / +6 first child / +8 next sibling / +10 previous sibling, +0x0E..+0x14 screen rectangle (lane ext) -- on the widget/UI framework page (find it; create one with a nav entry if none).
4. Work-RAM mirror (Boot_InitWorkRAM copies ROM 0xEED8C8.. -> RAM 0x3D524, ROM 0xEEFA66.. -> RAM 0xE35E; v7 differs) on memory-map / boot-sequence.
5. Tone database: the KN5000 index maps are exact inverses of the catalogue (333/333, 339/339, 141/141, 144/144 -- lane promcd, prom_d_index_maps.py), Music Stylist 1000-record database now fully typed (lane tonedb), preset banks / help DBs / fonts evidence (lane tdata) -- on tone-database / table-data-rom / music-stylist pages.
6. DSP effect-parameter metadata: maincpu ToneKit_* 0xEE4FC6-0xEE636B is the effect-parameter metadata read by DSPCfg_*; WidgetParam_Config_000..057 are twins of the sub-CPU DSP_EffNN_Param_Values tables (lane subcpu) -- effects pages.
7. Kernel/task names corrected (lane subcpu): Show_ScreenGroup_Entry = TaskSched_SpawnTask, TaskSched_Resume blocks the caller, Audio_Lock_* are generic kernel semaphores -- wherever those names appear on the site, using the names the sources now carry (check!).
8. The "Preset Data Destination" dispute (lzss-compression.md and wherever it appears): lane tdata's finding -- SubCPU_Send_Payload's fallback ships table data from 0x800000, the bitmap bank, so the 0xF7 bytes are the bitmaps' transparent palette index -- stated as a STRONG LEAD NOT YET CONFIRMED IN MAME, not as resolved.
9. Any other page whose statements the Wave 2 reports contradict (sweep: grep the site for names the lanes renamed -- the renaming sed scripts are in ${DIS}/scripts/renaming/ and the lane reports list renames).`

const WS = `YOUR PAGES: the SX-WSA1R pages, and the project-status pages (rom-reconstruction.md, and any page quoting disassembly-completeness figures). Mandatory items:
1. rom-reconstruction.md: current figures from census-after-wave2.txt (strict 64.15% -> 95.04%, per-image strict shares, KNOWN-A/B, research targets 5,077 ranges / 328,853 B, UNKNOWN 56,567 B) with the command that re-derives them; explain the grades briefly (CODE / KNOWN-A evidence header / KNOWN-B name only / UNKNOWN / FILLER) and the honest reading that UNKNOWN rose because hiding names were replaced by admissions. Keep the existing numeric-branch section (it is current) but update its table if the figures moved (re-count with the one-liner in ${DIS}/scripts/converters/README-symbolize-branches.md).
2. WSA1 CPU-1 parameter-number space (lane proma): 4-byte records [number][class][value][mask], MIDI-in builds them at RAM 0x1950, panel expander -> list 0x2030 -> List2030_TranslateToQueue2C00 -> Dispatch_By_60F080 -> 0x2C00 queue; number ranges (0x00-0x1F part n with class = attribute: 0 program, 3 volume, 5/6/7 effect depths, 8 pan, 9-11 RPN; 0x20-0x3F second half; 0xB1 pitch bend, 0xB2 CC01, 0xB3 CC0B, 0xB4 channel pressure, 0xB5 CC40, 0xB8-BB CC10-13, 0xBC CC02, 0xBD CC04, 0xAD/0xAE CC79/CC78; controller numbers fan out over a 32-bit part mask at RAM 0x60F280+); the panel assignment byte is a MIDI CC number.
3. prom_b stale older-build remnants (lane promb): 0xF0ED50-0xF0EFFF = live - 0x23001, 0xF17A5F-0xF17BFF = live - 0x1A401, 0xF6F000-0xF6F3FF = live - 0xBA00, each proven by a script under ${DIS}/notes/promb-2026-09-25/; why it matters for emulation (unreached code may be stale, not a missed path).
4. prom_c/prom_d (lane promcd): tone DB index maps are exact inverses of the catalogue on BOTH models; prom_c preset bank reader; Double_Sin/Cos/Tan/Exp/Log/Pow/Abs/MakeInfinity names for the old sub_FC8C45... routines; P7 descriptor letters decoded -- fix any page still saying these are unknown.
5. Any WSA1 page statement the Wave 2 WSA1 reports (proma, promb, promcd) contradict.`

const V = (wt, br, area) => `You FACT-CHECK the documentation changes on branch ${br} (worktree ${W}/${wt}) -- ${area}. READ-ONLY: do not edit or commit. See the changes: \`cd ${W}/${wt} && git log --oneline b692eac..HEAD && git diff b692eac..HEAD\`. For at least 30 specific claims (addresses, field layouts, counts, names, figures), verify against the disassembly sources in ${DIS} (\`command grep\`), the lane reports in ${DIS}/notes/lanes/wave2-2026-09-25/lane-reports/, the ROM bytes (${DIS}/original_ROMs, ${DIS}/wsa1/original_ROMs) and the cited scripts (run them if cheap). Also check: every quoted symbol name exists in the current sources; new pages have nav entries; nothing is written as a changelog; unconfirmed items are marked as such; \`JEKYLL_NO_BUNDLER_REQUIRE=true jekyll build -q -d ${W}/docs-verify-${wt}\` exits 0. Report each false or unsupported claim with the file, the claim, the evidence, and the fix.`
const VS = { type: 'object', properties: { checked: { type: 'integer' }, problems: { type: 'array', items: { type: 'object', properties: { file: { type: 'string' }, claim: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['file', 'claim', 'evidence', 'fix'] } }, build_ok: { type: 'boolean' } }, required: ['checked', 'problems', 'build_ok'] }
const WSCH = { type: 'object', properties: { commits: { type: 'array', items: { type: 'string' } }, pages_changed: { type: 'array', items: { type: 'string' } }, not_done: { type: 'string' } }, required: ['commits', 'pages_changed', 'not_done'] }

const areas = [
  { wt: 'docs-kn5000', br: 'docs/w2-kn5000', task: KN, area: 'KN5000 pages' },
  { wt: 'docs-wsa1status', br: 'docs/w2-wsa1status', task: WS, area: 'WSA1 + status pages' },
]
const out = await pipeline(areas,
  a => agent(COMMON(a.wt, a.br) + '\n\n' + a.task + '\n\nReturn your commits, pages changed and what you did not do.', { label: `write:${a.wt}`, phase: 'Write', schema: WSCH }),
  async (w, a) => {
    const v = await agent(V(a.wt, a.br, a.area), { label: `check:${a.wt}`, phase: 'Fact-check', schema: VS })
    if (v && v.problems && v.problems.length) {
      const f = await agent(COMMON(a.wt, a.br) + `\n\nA fact-checker found these problems in your branch; fix each one (new commits), re-build, and report: ${JSON.stringify(v.problems).slice(0, 8000)}`, { label: `fix:${a.wt}`, phase: 'Fact-check', schema: WSCH })
      return { write: w, check: v, fix: f }
    }
    return { write: w, check: v }
  })
return out
