#!/usr/bin/env python3
"""Do the transcribed effect data tables check out arithmetically?

QUESTION IT ANSWERS
  Chapter 9 names each effect's VALUE bytes but a byte is not a quantity: the
  guide's page 33 carries eighteen tables turning a parameter into seconds,
  hertz, decibels or cents.  Without them a librarian can label a control but
  not display it.

  Those tables are transcribed here, and like every transcription in this
  project they are checked rather than trusted -- this time by the tables' own
  arithmetic.  Each row gives a parameter span, a first value, a last value and
  a step, and those four numbers are not independent:

      v_lo + step x (p_hi - p_lo)  ==  v_hi

  A misread endpoint or a misread step breaks the identity.  Forty-one rows,
  forty-one chances for the transcription to fail.

WHY THAT IS A REAL CHECK
  The guide prints all four numbers, so the identity is redundant information
  that a correct reading must satisfy and a wrong one almost certainly will not.
  It is the same shape as the tiling check on the sound layout: the document
  over-determines itself, and the redundancy is the test.

WHAT IT DOES NOT CHECK
  A table's TITLE, its unit, or an enumerated table's words -- those carry no
  arithmetic.  And tables 17 and 18, which describe how two fields share a byte,
  are not transcribed at all.

SIGNAL BEING READ
  `conversion_tables.json` only.

RUN
  python3 wsa1/notes/sysex-probes/sysex_conversion_tables.py
  python3 wsa1/notes/sysex-probes/sysex_conversion_tables.py --tex <file>

PASS CRITERION
  Every arithmetic row satisfies the identity, and OK.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TABLES = os.path.join(HERE, "conversion_tables.json")
EPS = 1e-9


def fmt(v):
    if isinstance(v, float) and v != int(v):
        return ("%.3f" % v).rstrip("0")
    return "%g" % v


def main():
    doc = json.load(open(TABLES))
    checked = 0
    print("\nEFFECT DATA TABLES")
    for t in doc["tables"]:
        kind = "%d rows" % len(t["rows"]) if "rows" in t else \
               "%d values" % len(t["values"])
        print("  TABLE %-3d %-42s %-22s %s"
              % (t["n"], t["title"], t["unit"] or "--", kind))
        for r in t.get("rows", []):
            span = r["p_hi"] - r["p_lo"]
            want = r["v_lo"] + r["step"] * span
            assert abs(want - r["v_hi"]) < max(EPS, abs(r["v_hi"]) * 1e-9), \
                ("TABLE %d: %s to %s in steps of %s over %d parameters reaches %s, "
                 "not the %s printed" % (t["n"], fmt(r["v_lo"]), fmt(r["v_hi"]),
                                         fmt(r["step"]), span, fmt(want),
                                         fmt(r["v_hi"])))
            checked += 1

    # The packed formats: a field must be wide enough for its table's range.
    by_n = {t["n"]: t for t in doc["tables"]}
    print("\nPACKED FIELDS (the guide's tables 17 and 18, and its equaliser note)")
    for pk in doc.get("packings", []):
        for f in pk["fields"]:
            t = by_n[f["table"]]
            top = max(r["p_hi"] for r in t["rows"]) if "rows" in t \
                else len(t["values"]) - 1
            need = max(1, top.bit_length())
            assert f["bits"] >= need, \
                ("%s is given %d bits but table %d reaches parameter %d, "
                 "which needs %d" % (f["name"], f["bits"], f["table"], top, need))
            print("    %-14s %d bits, table %-2d reaches %3d and needs %d"
                  % (f["name"], f["bits"], f["table"], top, need))

    print("\n  %d tables, %d arithmetic rows, every one satisfying"
          % (len(doc["tables"]), checked))
    print("  v_lo + step x (p_hi - p_lo) == v_hi")

    if "--tex" in sys.argv:
        out = ["%% GENERATED by notes/sysex-probes/sysex_conversion_tables.py --tex",
               "%% Source: conversion_tables.json. Do not edit.", "", "{\\small"]
        for t in doc["tables"]:
            unit = (" (%s)" % t["unit"]) if t["unit"] else ""
            out.append("\\paragraph{Table %d: %s%s}" % (t["n"], t["title"], unit))
            if t.get("note"):
                note = t["note"][0].upper() + t["note"][1:] + "."
                out.append(note + "\\par")
            if "values" in t:
                vals = t["values"]
                if all(isinstance(v, (int, float)) for v in vals):
                    out.append("Parameter \\bytes{00}--\\bytes{%02X} selects, in order: %s."
                               % (len(vals) - 1,
                                  ", ".join(str(v) for v in vals)))
                else:
                    out.append(", ".join("\\bytes{%02X} %s" % (i, v)
                                         for i, v in enumerate(vals)) + ".")
                out.append("")
                continue
            out += ["\\begin{center}", "\\begin{tabular}{llr}", "\\toprule",
                    "parameter & value & step \\\\", "\\midrule"]
            for r in t["rows"]:
                out.append("%s--%s & %s--%s & %s \\\\"
                           % (fmt(r["p_lo"]), fmt(r["p_hi"]),
                              fmt(r["v_lo"]), fmt(r["v_hi"]), fmt(r["step"])))
            out += ["\\bottomrule", "\\end{tabular}", "\\end{center}", ""]
        out.append("\\paragraph{Packed fields}")
        out.append("Three of the guide's tables describe fields sharing two bytes "
                   "rather than a conversion. Each is listed with its width.")
        out += ["\\begin{center}",
                "\\begin{tabular}{p{38mm}l>{\\raggedright\\arraybackslash}p{62mm}}",
                "\\toprule", "format & field & width \\\\", "\\midrule"]
        for pk in doc.get("packings", []):
            first = True
            for f in pk["fields"]:
                note = (" --- " + f["note"]) if f.get("note") else ""
                out.append("%s & %s & %d bits%s \\\\"
                           % (pk["title"] if first else "", f["name"],
                              f["bits"], note))
                first = False
        out += ["\\bottomrule", "\\end{tabular}", "\\end{center}", ""]
        out += ["}", ""]
        target = sys.argv[sys.argv.index("--tex") + 1]
        open(target, "w").write("\n".join(out) + "\n")
        print("\n  wrote %s" % target)
    print("OK")


if __name__ == "__main__":
    main()
