#!/usr/bin/env python3
"""Does the transcribed effect catalogue agree with the one read out of the ROMs?

QUESTION IT ANSWERS
  An effect block's TYPE byte selects an effect, and its twenty VALUE bytes mean
  whatever that effect says they mean.  `effects.json` transcribes both -- the
  effect numbers and the VALUE order -- from Technics' Reference Guide, whose
  DSP EFFECT pages are image-only and had to be rendered and read.

  The numbers are checkable, and by something entirely independent: this project
  had already disassembled the effects DSP and produced `wsa1/dsp/programs.tsv`,
  a manifest of every distinct effect program with the number that selects it.
  That manifest came from the ROMs; the guide is a printed book.  If a number
  was misread here, the two sets will not match.

  So this asserts SET EQUALITY on the effect numbers, and prints the ROM's own
  name beside the guide's.

WHAT IT DOES NOT CHECK
  The VALUE lists.  Nothing independent states them, so a misreading survives,
  and the chapter says so.  The names differ in spelling between the two sources
  by design -- the ROM carries the short names the instrument displays
  (`S.DELAY+CHORUS`), the guide prints the long ones -- so the names are shown
  side by side and only the NUMBERS are asserted.

SIGNAL BEING READ
  `effects.json` and `../../dsp/programs.tsv`.

RUN
  python3 wsa1/notes/sysex-probes/sysex_effects.py
  python3 wsa1/notes/sysex-probes/sysex_effects.py --tex <file>

PASS CRITERION
  The two number sets are equal, every effect has a VALUE list of at most 20,
  and OK.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CATALOGUE = os.path.join(HERE, "effects.json")
PROGRAMS = os.path.abspath(os.path.join(HERE, "..", "..", "dsp", "programs.tsv"))

MAX_VALUES = 20        # an effect block carries VALUE1..VALUE20


def rom_catalogue():
    out = {}
    for line in open(PROGRAMS):
        if line.startswith("#") or not line.strip():
            continue
        f = line.rstrip("\n").split("\t")
        out[int(f[2])] = f[1]
    return out


def tex_escape(s):
    return (s.replace("&", "\\&").replace("_", "\\_").replace("%", "\\%")
             .replace("#", "\\#"))


def main():
    doc = json.load(open(CATALOGUE))
    guide = {e["prog"]: e for e in doc["effects"]}
    rom = rom_catalogue()

    only_guide = sorted(set(guide) - set(rom))
    only_rom = sorted(set(rom) - set(guide))
    print("\nEFFECT NUMBERS")
    print("  %d in the guide, %d in the ROM manifest" % (len(guide), len(rom)))
    if only_guide:
        print("  only in the guide: %s" % only_guide)
    if only_rom:
        print("  only in the ROM:   %s" % [(n, rom[n]) for n in only_rom])
    assert not only_guide and not only_rom, \
        "the two catalogues disagree on which effect numbers exist"
    print("  the two sets are equal")

    print("\n  %-4s %-26s %s" % ("no.", "ROM manifest", "guide, and VALUE count"))
    for n in sorted(guide):
        vals = guide[n]["values"]
        assert len(vals) <= MAX_VALUES, \
            "effect %d has %d values, more than the %d an effect block carries" \
            % (n, len(vals), MAX_VALUES)
        print("  %-4d %-26s %-34s %d" % (n, rom[n], guide[n]["guide_name"], len(vals)))

    counts = {}
    for n, e in guide.items():
        counts.setdefault(len(e["values"]), []).append(n)
    print("\n  %d effects, VALUE counts from %d to %d"
          % (len(guide), min(counts), max(counts)))

    if "--tex" in sys.argv:
        # effect_value_numbers.json gives the VALUE byte each parameter
        # occupies -- it is NOT one per name (see sysex_effect_value_numbers.py).
        bytes_path = os.path.join(HERE, "effect_value_numbers.json")
        bytemap = {e["prog"]: e
                   for e in json.load(open(bytes_path))["effects"]}
        # effect_data_tables.json gives the conversion table each parameter
        # uses, from the guide's MIDI DATA column.
        tbl_path = os.path.join(HERE, "effect_data_tables.json")
        tblmap = {e["prog"]: [q["table"] for q in e["parameters"]]
                  for e in json.load(open(tbl_path))["effects"]}
        assert set(bytemap) == set(guide), \
            "effect_value_numbers.json and effects.json disagree on which " \
            "effects exist: %s" % (set(bytemap) ^ set(guide))

        out = ["%% GENERATED by notes/sysex-probes/sysex_effects.py --tex",
               "%% Source: effects.json, effect_value_numbers.json,",
               "%% effect_data_tables.json and dsp/programs.tsv. Do not edit.", "",
               "{\\small",
               "\\begin{longtable}{ll>{\\raggedright\\arraybackslash}p{40mm}"
               ">{\\raggedright\\arraybackslash}p{78mm}}",
               "\\toprule",
               "no. & n & effect & parameters: \\textsc{value} byte, then the "
               "conversion table \\\\",
               "\\midrule\\endfirsthead",
               "\\toprule no. & n & effect & parameters: \\textsc{value} byte, "
               "then the conversion table \\\\",
               "\\midrule\\endhead"]
        for n in sorted(guide):
            ent = bytemap[n]
            params = ent["parameters"]
            names_json = guide[n]["values"]
            assert [q["name"] for q in params] == names_json, \
                "effect %d: the two files' name lists differ" % n
            conv = tblmap[n]
            assert len(conv) == len(params), \
                "effect %d: %d DATA cells but %d parameters" \
                % (n, len(conv), len(params))
            bits = []
            for q, t in zip(params, conv):
                b = q["bytes"]
                span = "--".join(str(x) for x in (b[0], b[-1])) \
                    if len(b) > 1 else (str(b[0]) if b else "?")
                mark = "" if t is None else "$^{*%s}$" % t
                bits.append("%s~\\textbf{%s}%s"
                            % (tex_escape(q["name"]), span, mark))
            body = ", ".join(bits) if bits else "---"
            out.append("\\bytes{%02X} & %d & %s & %s \\\\"
                       % (n, ent["value_bytes"],
                          tex_escape(guide[n]["guide_name"]), body))
        out += ["\\bottomrule", "\\end{longtable}", "}", ""]
        target = sys.argv[sys.argv.index("--tex") + 1]
        open(target, "w").write("\n".join(out) + "\n")
        print("\n  wrote %s" % target)

    print("OK")


if __name__ == "__main__":
    main()
