/**
 * se_compare_screen — Screen Layout Data
 *
 * Base address: 0xF12F95
 * Size: 139 bytes, 13 commands
 *
 * Auto-generated by screendata_parser.py
 */

#include "screendata_types.h"
#include <stddef.h>

/* Handler data tables (resolved by linker via se_screens_link.ld) */
extern const char SE_CompareScreen_CursorCoords;
extern const char SE_Compare_ParamAddr_R1;
extern const char SE_Compare_ParamAddr_R2;
extern const char SE_Compare_ParamAddr_R3;
extern const char SE_Compare_ParamAddr_R4;
extern const char SE_Compare_FlaggedAddr_R1;
extern const char SE_Compare_FlaggedAddr_R2;
extern const char SE_Compare_FlaggedAddr_R3;
extern const char SE_Compare_FlaggedAddr_R4;

#define HANDLER_ADDR(sym) ((uint32_t)&(sym))

typedef struct __attribute__((packed)) {
	sd_nop_10_t                    nop_0;
	sd_nop_10_t                    nop_1;
	sd_nop_10_t                    nop_2;
	sd_nop_10_t                    nop_3;
	sd_block_hdr_t                 setup5_0;  /* id=0x0665 DRAM param R1 */
	sd_block_hdr_t                 setup5_1;  /* id=0x0666 DRAM param R2 */
	sd_block_hdr_t                 setup5_2;  /* id=0x0667 DRAM param R3 */
	sd_block_hdr_t                 setup5_3;  /* id=0x0668 DRAM param R4 */
	sd_block_hdr_t                 setup5_4;  /* id=0x0669 flagged R1 */
	sd_block_hdr_t                 setup5_5;  /* id=0x066a flagged R2 */
	sd_block_hdr_t                 setup5_6;  /* id=0x066b flagged R3 */
	sd_block_hdr_t                 setup5_7;  /* id=0x066c flagged R4 */
	sd_block_hdr_t                 setup_0;  /* id=0x065d cursor coords */
} screendata_se_compare_screen_t;

_Static_assert(sizeof(screendata_se_compare_screen_t) == 139,
	"se_compare_screen must be exactly 139 bytes");

#define SE_COMPARE_SCREEN_BASE  0x00F12F95u
#define SD_PTR(field)  (SE_COMPARE_SCREEN_BASE + offsetof(screendata_se_compare_screen_t, field))

const screendata_se_compare_screen_t se_compare_screen
	__attribute__((section(".text"), used)) = {
	.nop_0 = { .opcode = 0x00, .length = 0x0a, .data = { 0x61, 0x06, 0x7f, 0x00, 0x20, 0x51, 0x0d, 0x03 } },
	.nop_1 = { .opcode = 0x00, .length = 0x0a, .data = { 0x62, 0x06, 0x7f, 0x00, 0x20, 0x51, 0x12, 0x03 } },
	.nop_2 = { .opcode = 0x00, .length = 0x0a, .data = { 0x63, 0x06, 0x7f, 0x00, 0x20, 0x79, 0x17, 0x03 } },
	.nop_3 = { .opcode = 0x00, .length = 0x0a, .data = { 0x64, 0x06, 0x7f, 0x00, 0x20, 0x79, 0x1c, 0x03 } },
	.setup5_0 = { .type = 0x05, .length = 0x0b, .id = 0x0665, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_Compare_ParamAddr_R1) },
	.setup5_1 = { .type = 0x05, .length = 0x0b, .id = 0x0666, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_Compare_ParamAddr_R2) },
	.setup5_2 = { .type = 0x05, .length = 0x0b, .id = 0x0667, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_Compare_ParamAddr_R3) },
	.setup5_3 = { .type = 0x05, .length = 0x0b, .id = 0x0668, .flags = 0x00ff, .tag = 0x20, .handler = HANDLER_ADDR(SE_Compare_ParamAddr_R4) },
	.setup5_4 = { .type = 0x05, .length = 0x0b, .id = 0x0669, .flags = 0x05e0, .tag = 0x20, .handler = HANDLER_ADDR(SE_Compare_FlaggedAddr_R1) },
	.setup5_5 = { .type = 0x05, .length = 0x0b, .id = 0x066a, .flags = 0x05e0, .tag = 0x20, .handler = HANDLER_ADDR(SE_Compare_FlaggedAddr_R2) },
	.setup5_6 = { .type = 0x05, .length = 0x0b, .id = 0x066b, .flags = 0x05e0, .tag = 0x20, .handler = HANDLER_ADDR(SE_Compare_FlaggedAddr_R3) },
	.setup5_7 = { .type = 0x05, .length = 0x0b, .id = 0x066c, .flags = 0x05e0, .tag = 0x20, .handler = HANDLER_ADDR(SE_Compare_FlaggedAddr_R4) },
	.setup_0 = { .type = SD_BLOCK_SETUP, .length = 0x0b, .id = 0x065d, .flags = 0x000f, .tag = 0x05, .handler = HANDLER_ADDR(SE_CompareScreen_CursorCoords) },
};
